//! Generates the shipped C# `MAType` and `FuncUnstId` enums from `enums.yaml` —
//! the same source of truth as the C `include/ta_defs.h` enums and the Java
//! `MAType.java` / `FuncUnstId.java`.
//!
//! Unlike the Java emitter these are written as **whole files**: the C# library
//! is green field, so there is no hand-written head to preserve and therefore no
//! split-at-the-declaration trick.
//!
//! Two shape differences from Java are load-bearing:
//!
//! - C# enums carry explicit values natively, so `ALL = 65535` is a plain member
//!   rather than Java's constructor-plus-`value()` accessor.
//! - C# enums cannot hold static members, so Java's `COUNT` field has no home
//!   inside the enum. Emitting it *as a member* would make it an id and corrupt
//!   the ABI, so it goes in a sibling `FuncUnstIds` static class.

use crate::ir::{EnumDef, FuncDef};
use crate::registry::Lang;
use std::collections::HashMap;
use std::path::Path;

/// Namespace for the shipped C# library. The NuGet prefix is `TALib.*`.
const NAMESPACE: &str = "TALib";

/// Generate the shipped C# `MAType` enum.
///
/// The variant declaration ORDER is the value that indexes `optInMAType`; the
/// ordinal-equals-`value:` assert catches a non-contiguous edit before it can
/// silently reorder the ABI.
#[allow(clippy::implicit_hasher)]
pub fn generate_matype(funcs: &[FuncDef], enums: &HashMap<String, EnumDef>, path: &Path) {
    let ma = enums
        .get("MAType")
        .expect("MAType enum missing from enums.yaml");
    let s = render_matype(funcs, enums);
    super::write_if_changed(path, &s, "MAType.cs", ma.variants.len());
}

/// Render `MAType.cs`. Split from [`generate_matype`] so tests can assert on the
/// emitted text rather than merely on the emitter having run.
///
/// `funcs` decides only whether the `MATypes` limit companion is emitted — it is,
/// for an enum some optional parameter is declared with, because the generated
/// prologue range-checks such a parameter and needs a name for the bound.
#[allow(clippy::implicit_hasher)]
#[must_use]
pub fn render_matype(funcs: &[FuncDef], enums: &HashMap<String, EnumDef>) -> String {
    let ma = enums
        .get("MAType")
        .expect("MAType enum missing from enums.yaml");

    let mut s = String::from(super::ta_abstract_c::LICENSE);
    s.push_str("\n/* Generated by ta_codegen from enums.yaml \u{2014} do not edit. */\n\n");
    s.push_str(&format!("namespace {NAMESPACE};\n\n"));
    s.push_str("/// <summary>Moving-average type selected by an <c>optInMAType</c> parameter.</summary>\n");
    s.push_str("public enum MAType\n{\n");
    for (i, v) in ma.variants.iter().enumerate() {
        assert_eq!(
            i32::try_from(i).unwrap(),
            v.value,
            "MAType values must be contiguous from 0 ({} breaks the sequence)",
            v.c_name
        );
        let summary = super::common::ma_pseudo_member_doc(&v.name).map_or_else(
            || format!("The <c>{}</c> moving average.", v.c_name),
            str::to_string,
        );
        s.push_str(&format!("    /// <summary>{summary}</summary>\n"));
        s.push_str(&format!("    {} = {},\n", v.name, v.value));
    }
    s.push_str("}\n");
    if super::common::param_enum_names(funcs).contains(&ma.name) {
        s.push_str(&render_limits(ma));
    }
    s
}

/// The `MATypes` companion holding the enum's inclusive value limits.
///
/// C# surfaces `optInMAType` as an enum with no implicit int conversion but no
/// domain check either — `(MAType)42` is a legal cast — so the generated
/// prologue range-checks it, and these are what that check names. Derived from
/// the member list, so appending a member widens every check at once instead of
/// leaving a literal bound in each of them.
///
/// A C# enum cannot hold static members, hence the sibling class, exactly as
/// `FuncUnstIds.Count` does for `FuncUnstId`.
fn render_limits(def: &EnumDef) -> String {
    let (lo, hi) = super::common::enum_value_bounds_of(def).expect("a parameter enum has members");
    let (min_name, max_name) =
        super::common::enum_limit_names_of(def, Lang::CSharp).expect("C# declares enum limits");
    // The registry hands back qualified names (`MATypes.Min`); the declaration
    // needs the class and the member apart.
    let (class, min_member) = split_qualified(&min_name);
    let (_, max_member) = split_qualified(&max_name);
    let ty = &def.name;
    format!(
        "\n/// <summary>Companion constants for <see cref=\"{ty}\"/>.</summary>\n\
         public static class {class}\n{{\n\
         \x20   /// <summary>Lowest value <see cref=\"{ty}\"/> defines. Not a member:\n\
         \x20   /// the inclusive lower bound of the domain a parameter of that type\n\
         \x20   /// accepts.</summary>\n\
         \x20   public const int {min_member} = {lo};\n\n\
         \x20   /// <summary>Highest value <see cref=\"{ty}\"/> defines. Grows when a\n\
         \x20   /// member is appended.</summary>\n\
         \x20   public const int {max_member} = {hi};\n\
         }}\n"
    )
}

/// Split `Class.Member` into its two halves.
fn split_qualified(name: &str) -> (&str, &str) {
    name.split_once('.')
        .unwrap_or_else(|| panic!("expected a qualified C# constant name, got {name}"))
}

/// Generate the shipped C# `FuncUnstId` enum plus its `FuncUnstIds.Count`.
///
/// Each variant's value IS the index into the unstable-period table and equals
/// the C value; the assert pins that. `ALL` carries C's pinned 65535, which no
/// ordinal can express, and is deliberately NOT a table index.
#[allow(clippy::implicit_hasher)]
pub fn generate(enums: &HashMap<String, EnumDef>, path: &Path) {
    let fu = enums
        .get("FuncUnstId")
        .expect("FuncUnstId enum missing from enums.yaml");
    let s = render_funcunstid(enums);
    super::write_if_changed(path, &s, "FuncUnstId.cs", fu.variants.len());
}

/// Render `FuncUnstId.cs`. Split from [`generate`] so tests can assert on the
/// emitted text — in particular the pinned `ALL = 65535` and the `Count`.
#[allow(clippy::implicit_hasher)]
#[must_use]
pub fn render_funcunstid(enums: &HashMap<String, EnumDef>) -> String {
    let fu = enums
        .get("FuncUnstId")
        .expect("FuncUnstId enum missing from enums.yaml");

    let mut s = String::from(super::ta_abstract_c::LICENSE);
    s.push_str("\n/* Generated by ta_codegen from enums.yaml \u{2014} do not edit. */\n\n");
    s.push_str(&format!("namespace {NAMESPACE};\n\n"));
    s.push_str("/// <summary>Identifies a function whose unstable period can be set.</summary>\n");
    s.push_str("public enum FuncUnstId\n{\n");
    for (i, v) in fu.variants.iter().enumerate() {
        // The ABI pin: a renumber here silently repoints every caller's
        // set_unstable_period. Nothing caught one before this assert existed.
        assert_eq!(
            i32::try_from(i).unwrap(),
            v.value,
            "FuncUnstId values must be contiguous from 0 ({} breaks the sequence)",
            v.c_name
        );
        s.push_str(&format!(
            "    /// <summary>Unstable-period id for <c>{}</c>.</summary>\n",
            v.c_name
        ));
        s.push_str(&format!("    {} = {},\n", v.name, v.value));
    }
    s.push('\n');
    s.push_str("    /// <summary>Wildcard: sets the unstable period for every function at\n");
    s.push_str("    /// once. Pinned, so adding an indicator can never move it.</summary>\n");
    s.push_str("    ALL = 65535,\n");
    s.push_str("}\n\n");

    s.push_str("/// <summary>Companion constants for <see cref=\"FuncUnstId\"/>.</summary>\n");
    s.push_str("public static class FuncUnstIds\n{\n");
    s.push_str("    /// <summary>Number of function ids — the size of the unstable-period\n");
    s.push_str("    /// table. Not an id, and not <see cref=\"FuncUnstId.ALL\"/>. Mirrors C's\n");
    s.push_str("    /// TA_FUNC_UNST_COUNT.</summary>\n");
    s.push_str(&format!(
        "    public const int Count = {};\n",
        fu.variants.len()
    ));
    s.push_str("}\n");
    s
}
