/* TA-LIB Copyright (c) 1999-2003, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Note: This file is generated by gencode, do not
 *       modify directly.
 */

/* The function define in this file allows to have a consistent
 * framework for calling all the TA function through
 * the TA_CallFunc mechanism.
 *
 * See "ta_abstract.h"
 */

#ifndef TA_FUNC_H
   #include "ta_func.h"
#endif

#ifndef TA_FRAME_PRIV_H
   #include "ta_frame_priv.h"
#endif

#ifndef TA_FRAME_H
   #include "ta_frame.h"
#endif

/* NEVER CALL directly these functions! Use TA_CallFunc. */

TA_RetCode TA_MAX_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_MAX(
            startIdx,
            endIdx,
            params->in[0].data.inReal, /* inReal_0 */
            params->optIn[0].data.optInInteger, /* optInTimePeriod_0 */
            outBegIdx, 
            outNbElement, 
            params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_MIN_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_MIN(
            startIdx,
            endIdx,
            params->in[0].data.inReal, /* inReal_0 */
            params->optIn[0].data.optInInteger, /* optInTimePeriod_0 */
            outBegIdx, 
            outNbElement, 
            params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_BBANDS_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_BBANDS(
               startIdx,
               endIdx,
               params->in[0].data.inReal, /* inReal_0 */
               params->optIn[0].data.optInInteger, /* optInTimePeriod_0 */
               params->optIn[1].data.optInReal, /* optInNbDevUp_1 */
               params->optIn[2].data.optInReal, /* optInNbDevDn_2 */
               params->optIn[3].data.optInInteger, /* optInMethod_3 */
               outBegIdx, 
               outNbElement, 
               params->out[0].data.outReal, /*  outRealUpperBand_0 */
               params->out[1].data.outReal, /*  outRealMiddleBand_1 */
               params->out[2].data.outReal /*  outRealLowerBand_2 */ );
}
TA_RetCode TA_DEMA_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_DEMA(
             startIdx,
             endIdx,
             params->in[0].data.inReal, /* inReal_0 */
             params->optIn[0].data.optInInteger, /* optInTimePeriod_0 */
             outBegIdx, 
             outNbElement, 
             params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_EMA_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_EMA(
            startIdx,
            endIdx,
            params->in[0].data.inReal, /* inReal_0 */
            params->optIn[0].data.optInInteger, /* optInTimePeriod_0 */
            outBegIdx, 
            outNbElement, 
            params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_MA_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_MA(
           startIdx,
           endIdx,
           params->in[0].data.inReal, /* inReal_0 */
           params->optIn[0].data.optInInteger, /* optInTimePeriod_0 */
           params->optIn[1].data.optInInteger, /* optInMethod_1 */
           outBegIdx, 
           outNbElement, 
           params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_MIDPRICE_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_MIDPRICE(
                 startIdx,
                 endIdx,
                 params->in[0].data.inPrice.high, /* inHigh_0 */
                 params->in[0].data.inPrice.low, /* inLow_0 */
                 params->optIn[0].data.optInInteger, /* optInTimePeriod_0 */
                 outBegIdx, 
                 outNbElement, 
                 params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_MIDPOINT_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_MIDPOINT(
                 startIdx,
                 endIdx,
                 params->in[0].data.inReal, /* inReal_0 */
                 params->optIn[0].data.optInInteger, /* optInTimePeriod_0 */
                 outBegIdx, 
                 outNbElement, 
                 params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_SAR_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_SAR(
            startIdx,
            endIdx,
            params->in[0].data.inPrice.high, /* inHigh_0 */
            params->in[0].data.inPrice.low, /* inLow_0 */
            params->optIn[0].data.optInReal, /* optInAcceleration_0 */
            params->optIn[1].data.optInReal, /* optInMaximum_1 */
            outBegIdx, 
            outNbElement, 
            params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_SMA_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_SMA(
            startIdx,
            endIdx,
            params->in[0].data.inReal, /* inReal_0 */
            params->optIn[0].data.optInInteger, /* optInTimePeriod_0 */
            outBegIdx, 
            outNbElement, 
            params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_TEMA_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_TEMA(
             startIdx,
             endIdx,
             params->in[0].data.inReal, /* inReal_0 */
             params->optIn[0].data.optInInteger, /* optInTimePeriod_0 */
             outBegIdx, 
             outNbElement, 
             params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_TRIMA_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_TRIMA(
              startIdx,
              endIdx,
              params->in[0].data.inReal, /* inReal_0 */
              params->optIn[0].data.optInInteger, /* optInTimePeriod_0 */
              outBegIdx, 
              outNbElement, 
              params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_WMA_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_WMA(
            startIdx,
            endIdx,
            params->in[0].data.inReal, /* inReal_0 */
            params->optIn[0].data.optInInteger, /* optInTimePeriod_0 */
            outBegIdx, 
            outNbElement, 
            params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_ATR_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_ATR(
            startIdx,
            endIdx,
            params->in[0].data.inPrice.high, /* inHigh_0 */
            params->in[0].data.inPrice.low, /* inLow_0 */
            params->in[0].data.inPrice.close, /* inClose_0 */
            params->optIn[0].data.optInInteger, /* optInTimePeriod_0 */
            outBegIdx, 
            outNbElement, 
            params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_TRANGE_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_TRANGE(
               startIdx,
               endIdx,
               params->in[0].data.inPrice.high, /* inHigh_0 */
               params->in[0].data.inPrice.low, /* inLow_0 */
               params->in[0].data.inPrice.close, /* inClose_0 */
               outBegIdx, 
               outNbElement, 
               params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_ADX_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_ADX(
            startIdx,
            endIdx,
            params->in[0].data.inPrice.high, /* inHigh_0 */
            params->in[0].data.inPrice.low, /* inLow_0 */
            params->in[0].data.inPrice.close, /* inClose_0 */
            params->optIn[0].data.optInInteger, /* optInTimePeriod_0 */
            outBegIdx, 
            outNbElement, 
            params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_ADXR_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_ADXR(
             startIdx,
             endIdx,
             params->in[0].data.inPrice.high, /* inHigh_0 */
             params->in[0].data.inPrice.low, /* inLow_0 */
             params->in[0].data.inPrice.close, /* inClose_0 */
             params->optIn[0].data.optInInteger, /* optInTimePeriod_0 */
             outBegIdx, 
             outNbElement, 
             params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_APO_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_APO(
            startIdx,
            endIdx,
            params->in[0].data.inReal, /* inReal_0 */
            params->optIn[0].data.optInInteger, /* optInFastPeriod_0 */
            params->optIn[1].data.optInInteger, /* optInSlowPeriod_1 */
            params->optIn[2].data.optInInteger, /* optInMethod_2 */
            outBegIdx, 
            outNbElement, 
            params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_CCI_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_CCI(
            startIdx,
            endIdx,
            params->in[0].data.inPrice.high, /* inHigh_0 */
            params->in[0].data.inPrice.low, /* inLow_0 */
            params->in[0].data.inPrice.close, /* inClose_0 */
            params->optIn[0].data.optInInteger, /* optInTimePeriod_0 */
            outBegIdx, 
            outNbElement, 
            params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_DX_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_DX(
           startIdx,
           endIdx,
           params->in[0].data.inPrice.high, /* inHigh_0 */
           params->in[0].data.inPrice.low, /* inLow_0 */
           params->in[0].data.inPrice.close, /* inClose_0 */
           params->optIn[0].data.optInInteger, /* optInTimePeriod_0 */
           outBegIdx, 
           outNbElement, 
           params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_MACD_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_MACD(
             startIdx,
             endIdx,
             params->in[0].data.inReal, /* inReal_0 */
             params->optIn[0].data.optInInteger, /* optInFastPeriod_0 */
             params->optIn[1].data.optInInteger, /* optInSlowPeriod_1 */
             params->optIn[2].data.optInInteger, /* optInSignalPeriod_2 */
             outBegIdx, 
             outNbElement, 
             params->out[0].data.outReal, /*  outRealMACD_0 */
             params->out[1].data.outReal, /*  outRealMACDSignal_1 */
             params->out[2].data.outReal /*  outRealMACDHist_2 */ );
}
TA_RetCode TA_MACDEXT_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_MACDEXT(
                startIdx,
                endIdx,
                params->in[0].data.inReal, /* inReal_0 */
                params->optIn[0].data.optInInteger, /* optInFastPeriod_0 */
                params->optIn[1].data.optInInteger, /* optInFastMAType_1 */
                params->optIn[2].data.optInInteger, /* optInSlowPeriod_2 */
                params->optIn[3].data.optInInteger, /* optInSlowMAType_3 */
                params->optIn[4].data.optInInteger, /* optInSignalPeriod_4 */
                params->optIn[5].data.optInInteger, /* optInSignalMAType_5 */
                outBegIdx, 
                outNbElement, 
                params->out[0].data.outReal, /*  outRealMACD_0 */
                params->out[1].data.outReal, /*  outRealMACDSignal_1 */
                params->out[2].data.outReal /*  outRealMACDHist_2 */ );
}
TA_RetCode TA_MACDFIX_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_MACDFIX(
                startIdx,
                endIdx,
                params->in[0].data.inReal, /* inReal_0 */
                params->optIn[0].data.optInInteger, /* optInSignalPeriod_0 */
                outBegIdx, 
                outNbElement, 
                params->out[0].data.outReal, /*  outRealMACD_0 */
                params->out[1].data.outReal, /*  outRealMACDSignal_1 */
                params->out[2].data.outReal /*  outRealMACDHist_2 */ );
}
TA_RetCode TA_MFI_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_MFI(
            startIdx,
            endIdx,
            params->in[0].data.inPrice.high, /* inHigh_0 */
            params->in[0].data.inPrice.low, /* inLow_0 */
            params->in[0].data.inPrice.close, /* inClose_0 */
            params->in[0].data.inPrice.volume, /* inVolume_0 */
            params->optIn[0].data.optInInteger, /* optInTimePeriod_0 */
            outBegIdx, 
            outNbElement, 
            params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_MINUS_DI_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_MINUS_DI(
                 startIdx,
                 endIdx,
                 params->in[0].data.inPrice.high, /* inHigh_0 */
                 params->in[0].data.inPrice.low, /* inLow_0 */
                 params->in[0].data.inPrice.close, /* inClose_0 */
                 params->optIn[0].data.optInInteger, /* optInTimePeriod_0 */
                 outBegIdx, 
                 outNbElement, 
                 params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_MINUS_DM_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_MINUS_DM(
                 startIdx,
                 endIdx,
                 params->in[0].data.inPrice.high, /* inHigh_0 */
                 params->in[0].data.inPrice.low, /* inLow_0 */
                 params->optIn[0].data.optInInteger, /* optInTimePeriod_0 */
                 outBegIdx, 
                 outNbElement, 
                 params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_MOM_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_MOM(
            startIdx,
            endIdx,
            params->in[0].data.inReal, /* inReal_0 */
            params->optIn[0].data.optInInteger, /* optInTimePeriod_0 */
            outBegIdx, 
            outNbElement, 
            params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_PPO_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_PPO(
            startIdx,
            endIdx,
            params->in[0].data.inReal, /* inReal_0 */
            params->optIn[0].data.optInInteger, /* optInFastPeriod_0 */
            params->optIn[1].data.optInInteger, /* optInSlowPeriod_1 */
            params->optIn[2].data.optInInteger, /* optInMethod_2 */
            outBegIdx, 
            outNbElement, 
            params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_PLUS_DI_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_PLUS_DI(
                startIdx,
                endIdx,
                params->in[0].data.inPrice.high, /* inHigh_0 */
                params->in[0].data.inPrice.low, /* inLow_0 */
                params->in[0].data.inPrice.close, /* inClose_0 */
                params->optIn[0].data.optInInteger, /* optInTimePeriod_0 */
                outBegIdx, 
                outNbElement, 
                params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_PLUS_DM_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_PLUS_DM(
                startIdx,
                endIdx,
                params->in[0].data.inPrice.high, /* inHigh_0 */
                params->in[0].data.inPrice.low, /* inLow_0 */
                params->optIn[0].data.optInInteger, /* optInTimePeriod_0 */
                outBegIdx, 
                outNbElement, 
                params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_ROC_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_ROC(
            startIdx,
            endIdx,
            params->in[0].data.inReal, /* inReal_0 */
            params->optIn[0].data.optInInteger, /* optInTimePeriod_0 */
            outBegIdx, 
            outNbElement, 
            params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_ROCP_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_ROCP(
             startIdx,
             endIdx,
             params->in[0].data.inReal, /* inReal_0 */
             params->optIn[0].data.optInInteger, /* optInTimePeriod_0 */
             outBegIdx, 
             outNbElement, 
             params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_ROCR_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_ROCR(
             startIdx,
             endIdx,
             params->in[0].data.inReal, /* inReal_0 */
             params->optIn[0].data.optInInteger, /* optInTimePeriod_0 */
             outBegIdx, 
             outNbElement, 
             params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_ROCR100_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_ROCR100(
                startIdx,
                endIdx,
                params->in[0].data.inReal, /* inReal_0 */
                params->optIn[0].data.optInInteger, /* optInTimePeriod_0 */
                outBegIdx, 
                outNbElement, 
                params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_RSI_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_RSI(
            startIdx,
            endIdx,
            params->in[0].data.inReal, /* inReal_0 */
            params->optIn[0].data.optInInteger, /* optInTimePeriod_0 */
            outBegIdx, 
            outNbElement, 
            params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_STOCH_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_STOCH(
              startIdx,
              endIdx,
              params->in[0].data.inPrice.high, /* inHigh_0 */
              params->in[0].data.inPrice.low, /* inLow_0 */
              params->in[0].data.inPrice.close, /* inClose_0 */
              params->optIn[0].data.optInInteger, /* optInFastK_Period_0 */
              params->optIn[1].data.optInInteger, /* optInSlowK_Period_1 */
              params->optIn[2].data.optInInteger, /* optInSlowK_MAType_2 */
              params->optIn[3].data.optInInteger, /* optInSlowD_Period_3 */
              params->optIn[4].data.optInInteger, /* optInSlowD_MAType_4 */
              outBegIdx, 
              outNbElement, 
              params->out[0].data.outReal, /*  outSlowK_0 */
              params->out[1].data.outReal /*  outSlowD_1 */ );
}
TA_RetCode TA_STOCHF_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_STOCHF(
               startIdx,
               endIdx,
               params->in[0].data.inPrice.high, /* inHigh_0 */
               params->in[0].data.inPrice.low, /* inLow_0 */
               params->in[0].data.inPrice.close, /* inClose_0 */
               params->optIn[0].data.optInInteger, /* optInFastK_Period_0 */
               params->optIn[1].data.optInInteger, /* optInFastD_Period_1 */
               params->optIn[2].data.optInInteger, /* optInFastD_MAType_2 */
               outBegIdx, 
               outNbElement, 
               params->out[0].data.outReal, /*  outFastK_0 */
               params->out[1].data.outReal /*  outFastD_1 */ );
}
TA_RetCode TA_TRIX_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_TRIX(
             startIdx,
             endIdx,
             params->in[0].data.inReal, /* inReal_0 */
             params->optIn[0].data.optInInteger, /* optInTimePeriod_0 */
             outBegIdx, 
             outNbElement, 
             params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_WILLR_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_WILLR(
              startIdx,
              endIdx,
              params->in[0].data.inPrice.high, /* inHigh_0 */
              params->in[0].data.inPrice.low, /* inLow_0 */
              params->in[0].data.inPrice.close, /* inClose_0 */
              params->optIn[0].data.optInInteger, /* optInTimePeriod_0 */
              outBegIdx, 
              outNbElement, 
              params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_OBV_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_OBV(
            startIdx,
            endIdx,
            params->in[0].data.inReal, /* inReal_0 */
            params->in[1].data.inPrice.volume, /* inVolume_1 */
            outBegIdx, 
            outNbElement, 
            params->out[0].data.outInteger /*  outInteger_0 */ );
}
TA_RetCode TA_STDDEV_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_STDDEV(
               startIdx,
               endIdx,
               params->in[0].data.inReal, /* inReal_0 */
               params->optIn[0].data.optInInteger, /* optInTimePeriod_0 */
               params->optIn[1].data.optInReal, /* optInNbDev_1 */
               outBegIdx, 
               outNbElement, 
               params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_VAR_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_VAR(
            startIdx,
            endIdx,
            params->in[0].data.inReal, /* inReal_0 */
            params->optIn[0].data.optInInteger, /* optInTimePeriod_0 */
            params->optIn[1].data.optInReal, /* optInNbDev_1 */
            outBegIdx, 
            outNbElement, 
            params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_AVGPRICE_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_AVGPRICE(
                 startIdx,
                 endIdx,
                 params->in[0].data.inPrice.open, /* inOpen_0 */
                 params->in[0].data.inPrice.high, /* inHigh_0 */
                 params->in[0].data.inPrice.low, /* inLow_0 */
                 params->in[0].data.inPrice.close, /* inClose_0 */
                 outBegIdx, 
                 outNbElement, 
                 params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_MEDPRICE_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_MEDPRICE(
                 startIdx,
                 endIdx,
                 params->in[0].data.inPrice.high, /* inHigh_0 */
                 params->in[0].data.inPrice.low, /* inLow_0 */
                 outBegIdx, 
                 outNbElement, 
                 params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_TYPPRICE_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_TYPPRICE(
                 startIdx,
                 endIdx,
                 params->in[0].data.inPrice.high, /* inHigh_0 */
                 params->in[0].data.inPrice.low, /* inLow_0 */
                 params->in[0].data.inPrice.close, /* inClose_0 */
                 outBegIdx, 
                 outNbElement, 
                 params->out[0].data.outReal /*  outReal_0 */ );
}
TA_RetCode TA_WCLPRICE_FramePP( const TA_ParamHolderPriv *params,
                          TA_Integer            startIdx,
                          TA_Integer            endIdx,
                          TA_Integer           *outBegIdx,
                          TA_Integer           *outNbElement )

{
   return TA_WCLPRICE(
                 startIdx,
                 endIdx,
                 params->in[0].data.inPrice.high, /* inHigh_0 */
                 params->in[0].data.inPrice.low, /* inLow_0 */
                 params->in[0].data.inPrice.close, /* inClose_0 */
                 outBegIdx, 
                 outNbElement, 
                 params->out[0].data.outReal /*  outReal_0 */ );
}

/***************/
/* End of File */
/***************/

