/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_unguarded.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  AB       Anatoliy Belsky
 *
 * Change history:
 *
 *  MMDDYY BY     Description
 *  -------------------------------------------------------------------
 *  090812 AB     Initial Version
 */

TA_LIB_API int TA_AVGDEV_Lookback( int optInTimePeriod )
{
   if( (int)optInTimePeriod == (int)0x80000000 )
      optInTimePeriod = 14;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return -1;
   return optInTimePeriod - 1;
}

TA_LIB_API TA_RetCode TA_AVGDEV( int    startIdx,
                                 int    endIdx,
                                 const double inReal[],
                                 int optInTimePeriod,
                                 int          *outBegIdx,
                                 int          *outNBElement,
                                 double        outReal[] )
{
   int today;
   int outIdx;
   int lookback;

   if( startIdx < 0 )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( !inReal )
      return TA_BAD_PARAM;
   if( (int)optInTimePeriod == (int)0x80000000 )
      optInTimePeriod = 14;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   lookback = optInTimePeriod - 1;
   if( startIdx < lookback )
   {
      startIdx = lookback;
   }
   today = startIdx;
   /* Make sure there is still something to evaluate. */
   if( today > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   /* Process the initial DM and TR */
   *outBegIdx= today;
   outIdx = 0;
   while( today <= endIdx )
   {
      double todaySum;
      double todayDev;
      int i;
      todaySum = 0.0;
      for( i = 0; i < optInTimePeriod; i += 1 )
      {
         todaySum += inReal[today - i];
      }
      todayDev = 0.0;
      for( i = 0; i < optInTimePeriod; i += 1 )
      {
         todayDev += fabs(inReal[today - i] - todaySum / optInTimePeriod);
      }
      outReal[outIdx] = todayDev / optInTimePeriod;
      outIdx += 1;
      today += 1;
   }
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_AVGDEV_Unguarded( int    startIdx,
                                           int    endIdx,
                                           const double inReal[],
                                           int optInTimePeriod,
                                           int          *outBegIdx,
                                           int          *outNBElement,
                                           double        outReal[] )
{
   int today;
   int outIdx;
   int lookback;

   lookback = optInTimePeriod - 1;
   if( startIdx < lookback )
   {
      startIdx = lookback;
   }
   today = startIdx;
   if( today > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   *outBegIdx= today;
   outIdx = 0;
   while( today <= endIdx )
   {
      double todaySum;
      double todayDev;
      int i;
      todaySum = 0.0;
      for( i = 0; i < optInTimePeriod; i += 1 )
      {
         todaySum += inReal[today - i];
      }
      todayDev = 0.0;
      for( i = 0; i < optInTimePeriod; i += 1 )
      {
         todayDev += fabs(inReal[today - i] - todaySum / optInTimePeriod);
      }
      outReal[outIdx] = todayDev / optInTimePeriod;
      outIdx += 1;
      today += 1;
   }
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

TA_RetCode TA_S_AVGDEV( int    startIdx,
                        int    endIdx,
                        const float inReal[],
                        int optInTimePeriod,
                        int          *outBegIdx,
                        int          *outNBElement,
                        double        outReal[] )
{
   int today;
   int outIdx;
   int lookback;

   if( startIdx < 0 )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( !inReal )
      return TA_BAD_PARAM;
   if( (int)optInTimePeriod == (int)0x80000000 )
      optInTimePeriod = 14;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   lookback = optInTimePeriod - 1;
   if( startIdx < lookback )
   {
      startIdx = lookback;
   }
   today = startIdx;
   if( today > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   *outBegIdx= today;
   outIdx = 0;
   while( today <= endIdx )
   {
      double todaySum;
      double todayDev;
      int i;
      todaySum = 0.0;
      for( i = 0; i < optInTimePeriod; i += 1 )
      {
         todaySum += (double)inReal[today - i];
      }
      todayDev = 0.0;
      for( i = 0; i < optInTimePeriod; i += 1 )
      {
         todayDev += fabs((double)inReal[today - i] - todaySum / optInTimePeriod);
      }
      outReal[outIdx] = todayDev / optInTimePeriod;
      outIdx += 1;
      today += 1;
   }
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

TA_RetCode TA_S_AVGDEV_Unguarded( int    startIdx,
                                  int    endIdx,
                                  const float inReal[],
                                  int optInTimePeriod,
                                  int          *outBegIdx,
                                  int          *outNBElement,
                                  double        outReal[] )
{
   int today;
   int outIdx;
   int lookback;

   lookback = optInTimePeriod - 1;
   if( startIdx < lookback )
   {
      startIdx = lookback;
   }
   today = startIdx;
   if( today > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   *outBegIdx= today;
   outIdx = 0;
   while( today <= endIdx )
   {
      double todaySum;
      double todayDev;
      int i;
      todaySum = 0.0;
      for( i = 0; i < optInTimePeriod; i += 1 )
      {
         todaySum += (double)inReal[today - i];
      }
      todayDev = 0.0;
      for( i = 0; i < optInTimePeriod; i += 1 )
      {
         todayDev += fabs((double)inReal[today - i] - todaySum / optInTimePeriod);
      }
      outReal[outIdx] = todayDev / optInTimePeriod;
      outIdx += 1;
      today += 1;
   }
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

