/* TA-LIB Copyright (c) 1999-2026, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_stream_private.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  RM       Robert Meier
 *  MF       Mario Fortier
 *  CC       Claude Code (AI assistant)
 *
 * Change history:
 *
 *  MMDDYY BY     Description
 *  -------------------------------------------------------------------
 *  120307 RM     Initial Version
 *  120907 MF     Handling of a few limit cases
 *  071226 MF,CC  Fused single-loop rewrite: maintain the three band running
 *                sums (close for the middle band; the pointwise High/Low map for
 *                the upper/lower bands) over one shared trailing window, instead
 *                of two scratch buffers + three sma() calls. Enables streaming
 *                and is bit-identical to the prior three-SMA form (verified vs
 *                v0.6.4).
 *  082326 MF,CC  Fix #253. Scale the High+Low cancellation test to its own
 *                operands instead of the fixed TA_IS_ZERO band, which widened
 *                the bands of any instrument quoted small enough to fall
 *                under it.
 */

TA_LIB_API int TA_ACCBANDS_Lookback( int optInTimePeriod )
{
   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 20;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return -1;
   return TA_SMA_Lookback(optInTimePeriod);
}

TA_LIB_API TA_RetCode TA_ACCBANDS( int    startIdx,
                                   int    endIdx,
                                   const double inHigh[],
                                   const double inLow[],
                                   const double inClose[],
                                   int optInTimePeriod,
                                   int          *outBegIdx,
                                   int          *outNBElement,
                                   double        outRealUpperBand[],
                                   double        outRealMiddleBand[],
                                   double        outRealLowerBand[] )
{
   double periodTotalUpper;
   double periodTotalMiddle;
   double periodTotalLower;
   double tempUpper;
   double tempMiddle;
   double tempLower;
   double tempReal;
   int i;
   int outIdx;
   int trailingIdx;
   int lookbackTotal;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 20;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !inClose )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outRealUpperBand )
      return TA_BAD_PARAM;
   if( !outRealMiddleBand )
      return TA_BAD_PARAM;
   if( !outRealLowerBand )
      return TA_BAD_PARAM;
   if( outRealUpperBand == outRealMiddleBand || outRealUpperBand == outRealLowerBand || outRealMiddleBand == outRealLowerBand )
      return TA_BAD_PARAM;

   /* Identify the minimum number of price bar needed
    * to calculate at least one output.
    */
   lookbackTotal = TA_SMA_Lookback(optInTimePeriod);
   /* Move up the start index if there is not
    * enough initial data.
    */
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   /* Make sure there is still something to evaluate. */
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   /* Each band is a simple moving average maintained as a running sum over a
    * shared trailing window (all three share optInTimePeriod, so one trailing
    * index walks all three windows in lockstep):
    *    middle = SMA( close )
    *    upper  = SMA( high * (1 + 4*(high-low)/(high+low)) )
    *    lower  = SMA( low  * (1 - 4*(high-low)/(high+low)) )
    * When high+low is zero the upper/lower map degenerates to high/low.
    * Fusing the three moving averages into one loop is bit-identical to the
    * former "two scratch buffers + three sma() calls": each accumulator's
    * add/record/subtract order is unchanged, and the High/Low map is a pure
    * function recomputed from the raw trailing bar.
    */
   periodTotalUpper = 0.0;
   periodTotalMiddle = 0.0;
   periodTotalLower = 0.0;
   trailingIdx = startIdx - lookbackTotal;
   /* Warm up the running sums with the initial period,
    * except for the last value.
    */
   i = trailingIdx;
   while( i < startIdx )
   {
      /* The band factor 4*(H-L)/(H+L) is a ratio of two prices, so it is
       * scale-free -- but H+L is a sum that CANCELS when the two prices have
       * opposite signs, and the factor then blows up on what is left of the
       * operands' last bits. Test the sum against ITS OWN operands, not against
       * a fixed band: an absolute threshold answers "cancelled" for every bar
       * of an instrument quoted small enough to fall under it, and widened
       * every band it touched (issue #253). Same test on all three sites, so
       * the bar that enters a running sum is the one that later leaves it.
       */
      tempReal = inHigh[i] + inLow[i];
      if( !TA_IS_ZERO_SCALED(tempReal, fabs(inHigh[i]) + fabs(inLow[i])) )
      {
         tempReal = 4 * (inHigh[i] - inLow[i]) / tempReal;
         periodTotalUpper += inHigh[i] * (1 + tempReal);
         periodTotalLower += inLow[i] * (1 - tempReal);
      } else 
      {
         periodTotalUpper += inHigh[i];
         periodTotalLower += inLow[i];
      }
      periodTotalMiddle += inClose[i];
      i = i + 1;
   }
   /* Proceed with the calculation for the requested range.
    * Note that this algorithm allows the input and output to be the
    * same buffer: every trailing bar is read before any output is written.
    */
   outIdx = 0;
   while( i <= endIdx )
   {
      /* Add the incoming bar to each running sum. */
      tempReal = inHigh[i] + inLow[i];
      if( !TA_IS_ZERO_SCALED(tempReal, fabs(inHigh[i]) + fabs(inLow[i])) )
      {
         tempReal = 4 * (inHigh[i] - inLow[i]) / tempReal;
         periodTotalUpper += inHigh[i] * (1 + tempReal);
         periodTotalLower += inLow[i] * (1 - tempReal);
      } else 
      {
         periodTotalUpper += inHigh[i];
         periodTotalLower += inLow[i];
      }
      periodTotalMiddle += inClose[i];
      i = i + 1;
      /* Record the current window sums. */
      tempUpper = periodTotalUpper;
      tempMiddle = periodTotalMiddle;
      tempLower = periodTotalLower;
      /* Remove the trailing bar from each running sum. */
      tempReal = inHigh[trailingIdx] + inLow[trailingIdx];
      if( !TA_IS_ZERO_SCALED(tempReal, fabs(inHigh[trailingIdx]) + fabs(inLow[trailingIdx])) )
      {
         tempReal = 4 * (inHigh[trailingIdx] - inLow[trailingIdx]) / tempReal;
         periodTotalUpper -= inHigh[trailingIdx] * (1 + tempReal);
         periodTotalLower -= inLow[trailingIdx] * (1 - tempReal);
      } else 
      {
         periodTotalUpper -= inHigh[trailingIdx];
         periodTotalLower -= inLow[trailingIdx];
      }
      periodTotalMiddle -= inClose[trailingIdx];
      trailingIdx = trailingIdx + 1;
      /* Write the three bands. */
      outRealUpperBand[outIdx] = tempUpper / (double)optInTimePeriod;
      outRealMiddleBand[outIdx] = tempMiddle / (double)optInTimePeriod;
      outRealLowerBand[outIdx] = tempLower / (double)optInTimePeriod;
      outIdx = outIdx + 1;
   }
   *outBegIdx= startIdx;
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

TA_RetCode TA_S_ACCBANDS( int    startIdx,
                          int    endIdx,
                          const float inHigh[],
                          const float inLow[],
                          const float inClose[],
                          int optInTimePeriod,
                          int          *outBegIdx,
                          int          *outNBElement,
                          double        outRealUpperBand[],
                          double        outRealMiddleBand[],
                          double        outRealLowerBand[] )
{
   double periodTotalUpper;
   double periodTotalMiddle;
   double periodTotalLower;
   double tempUpper;
   double tempMiddle;
   double tempLower;
   double tempReal;
   int i;
   int outIdx;
   int trailingIdx;
   int lookbackTotal;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 20;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !inClose )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outRealUpperBand )
      return TA_BAD_PARAM;
   if( !outRealMiddleBand )
      return TA_BAD_PARAM;
   if( !outRealLowerBand )
      return TA_BAD_PARAM;
   if( outRealUpperBand == outRealMiddleBand || outRealUpperBand == outRealLowerBand || outRealMiddleBand == outRealLowerBand )
      return TA_BAD_PARAM;

   lookbackTotal = TA_SMA_Lookback(optInTimePeriod);
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   periodTotalUpper = 0.0;
   periodTotalMiddle = 0.0;
   periodTotalLower = 0.0;
   trailingIdx = startIdx - lookbackTotal;
   i = trailingIdx;
   while( i < startIdx )
   {
      tempReal = (double)inHigh[i] + (double)inLow[i];
      if( !TA_IS_ZERO_SCALED(tempReal, fabs((double)inHigh[i]) + fabs((double)inLow[i])) )
      {
         tempReal = 4 * ((double)inHigh[i] - (double)inLow[i]) / tempReal;
         periodTotalUpper += (double)inHigh[i] * (1 + tempReal);
         periodTotalLower += (double)inLow[i] * (1 - tempReal);
      } else 
      {
         periodTotalUpper += (double)inHigh[i];
         periodTotalLower += (double)inLow[i];
      }
      periodTotalMiddle += (double)inClose[i];
      i = i + 1;
   }
   outIdx = 0;
   while( i <= endIdx )
   {
      tempReal = (double)inHigh[i] + (double)inLow[i];
      if( !TA_IS_ZERO_SCALED(tempReal, fabs((double)inHigh[i]) + fabs((double)inLow[i])) )
      {
         tempReal = 4 * ((double)inHigh[i] - (double)inLow[i]) / tempReal;
         periodTotalUpper += (double)inHigh[i] * (1 + tempReal);
         periodTotalLower += (double)inLow[i] * (1 - tempReal);
      } else 
      {
         periodTotalUpper += (double)inHigh[i];
         periodTotalLower += (double)inLow[i];
      }
      periodTotalMiddle += (double)inClose[i];
      i = i + 1;
      tempUpper = periodTotalUpper;
      tempMiddle = periodTotalMiddle;
      tempLower = periodTotalLower;
      tempReal = (double)inHigh[trailingIdx] + (double)inLow[trailingIdx];
      if( !TA_IS_ZERO_SCALED(tempReal, fabs((double)inHigh[trailingIdx]) + fabs((double)inLow[trailingIdx])) )
      {
         tempReal = 4 * ((double)inHigh[trailingIdx] - (double)inLow[trailingIdx]) / tempReal;
         periodTotalUpper -= (double)inHigh[trailingIdx] * (1 + tempReal);
         periodTotalLower -= (double)inLow[trailingIdx] * (1 - tempReal);
      } else 
      {
         periodTotalUpper -= (double)inHigh[trailingIdx];
         periodTotalLower -= (double)inLow[trailingIdx];
      }
      periodTotalMiddle -= (double)inClose[trailingIdx];
      trailingIdx = trailingIdx + 1;
      outRealUpperBand[outIdx] = tempUpper / (double)optInTimePeriod;
      outRealMiddleBand[outIdx] = tempMiddle / (double)optInTimePeriod;
      outRealLowerBand[outIdx] = tempLower / (double)optInTimePeriod;
      outIdx = outIdx + 1;
   }
   *outBegIdx= startIdx;
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

/**** Streaming API *****/

struct TA_ACCBANDS_Stream {
   /* The bars this handle has an output for (see TA_StreamOutRange).
    * Kept first, and in this order, in every stream struct. */
   int outRangeBegIdx;
   int outRangeCount;
   /* The value(s) at the last bar the stream counted (see TA_ACCBANDS_Value). */
   double cur_outRealUpperBand;
   double cur_outRealMiddleBand;
   double cur_outRealLowerBand;
   int optInTimePeriod;
   double periodTotalUpper;
   double periodTotalMiddle;
   double periodTotalLower;
   int ringPos_trailingIdx;
   int ringCap_trailingIdx;
   double *ring_trailingIdx_inHigh;
   double *ring_trailingIdx_inLow;
   double *ring_trailingIdx_inClose;
};

/* Private function, not in public API. */
static void TA_ACCBANDS_ReleaseImpl( struct TA_ACCBANDS_Stream *sp )
{
   if( !sp ) return;
   if( sp->ring_trailingIdx_inHigh ) TA_Free( sp->ring_trailingIdx_inHigh );
   if( sp->ring_trailingIdx_inLow ) TA_Free( sp->ring_trailingIdx_inLow );
   if( sp->ring_trailingIdx_inClose ) TA_Free( sp->ring_trailingIdx_inClose );
   TA_Free( sp );
}

/* Private function, not in public API. */
static void TA_ACCBANDS_StepImpl( struct TA_ACCBANDS_Stream *sp, double inHigh, double inLow, double inClose, double *outRealUpperBand, double *outRealMiddleBand, double *outRealLowerBand )
{
   double tempUpper;
   double tempMiddle;
   double tempLower;
   double tempReal;

   if( sp->ringCap_trailingIdx == 0 )
   {
      sp->ring_trailingIdx_inHigh[0] = inHigh;
      sp->ring_trailingIdx_inLow[0] = inLow;
      sp->ring_trailingIdx_inClose[0] = inClose;
   }
   /* Add the incoming bar to each running sum. */
   tempReal = inHigh + inLow;
   if( !TA_IS_ZERO_SCALED(tempReal, fabs(inHigh) + fabs(inLow)) )
   {
      tempReal = 4 * (inHigh - inLow) / tempReal;
      sp->periodTotalUpper += inHigh * (1 + tempReal);
      sp->periodTotalLower += inLow * (1 - tempReal);
   } else 
   {
      sp->periodTotalUpper += inHigh;
      sp->periodTotalLower += inLow;
   }
   sp->periodTotalMiddle += inClose;
   /* Record the current window sums. */
   tempUpper = sp->periodTotalUpper;
   tempMiddle = sp->periodTotalMiddle;
   tempLower = sp->periodTotalLower;
   /* Remove the trailing bar from each running sum. */
   tempReal = sp->ring_trailingIdx_inHigh[sp->ringPos_trailingIdx] + sp->ring_trailingIdx_inLow[sp->ringPos_trailingIdx];
   if( !TA_IS_ZERO_SCALED(tempReal, fabs(sp->ring_trailingIdx_inHigh[sp->ringPos_trailingIdx]) + fabs(sp->ring_trailingIdx_inLow[sp->ringPos_trailingIdx])) )
   {
      tempReal = 4 * (sp->ring_trailingIdx_inHigh[sp->ringPos_trailingIdx] - sp->ring_trailingIdx_inLow[sp->ringPos_trailingIdx]) / tempReal;
      sp->periodTotalUpper -= sp->ring_trailingIdx_inHigh[sp->ringPos_trailingIdx] * (1 + tempReal);
      sp->periodTotalLower -= sp->ring_trailingIdx_inLow[sp->ringPos_trailingIdx] * (1 - tempReal);
   } else 
   {
      sp->periodTotalUpper -= sp->ring_trailingIdx_inHigh[sp->ringPos_trailingIdx];
      sp->periodTotalLower -= sp->ring_trailingIdx_inLow[sp->ringPos_trailingIdx];
   }
   sp->periodTotalMiddle -= sp->ring_trailingIdx_inClose[sp->ringPos_trailingIdx];
   /* Write the three bands. */
   *outRealUpperBand= tempUpper / (double)sp->optInTimePeriod;
   *outRealMiddleBand= tempMiddle / (double)sp->optInTimePeriod;
   *outRealLowerBand= tempLower / (double)sp->optInTimePeriod;
   sp->cur_outRealUpperBand = *outRealUpperBand;
   sp->cur_outRealMiddleBand = *outRealMiddleBand;
   sp->cur_outRealLowerBand = *outRealLowerBand;
   sp->ring_trailingIdx_inHigh[sp->ringPos_trailingIdx] = inHigh;
   sp->ring_trailingIdx_inLow[sp->ringPos_trailingIdx] = inLow;
   sp->ring_trailingIdx_inClose[sp->ringPos_trailingIdx] = inClose;
   sp->ringPos_trailingIdx = sp->ringPos_trailingIdx + 1;
   if( sp->ringPos_trailingIdx >= sp->ringCap_trailingIdx )
   {
      sp->ringPos_trailingIdx = 0;
   }
}

static TA_RetCode TA_ACCBANDS_OpenImpl( struct TA_ACCBANDS_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], int startIdx, int historyLen, int optInTimePeriod, int *outBegIdx, int *outNBElement, double outRealUpperBand[], double outRealMiddleBand[], double outRealLowerBand[], int outStride )
{
   struct TA_ACCBANDS_Stream *sp;
   int endIdx;
   int dummyBegIdx;
   int dummyNBElement;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !inClose || !outRealUpperBand || !outRealMiddleBand || !outRealLowerBand ) return TA_BAD_PARAM;
   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 20;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( startIdx > historyLen - 1 )
   {
      *outBegIdx = 0;
      *outNBElement = 0;
      return TA_INSUFFICIENT_HISTORY;
   }

   endIdx = historyLen - 1;
   dummyBegIdx = 0;
   dummyNBElement = 0;
   (void)startIdx; (void)dummyBegIdx; (void)dummyNBElement;

   {
      double periodTotalUpper = 0.0;
      double periodTotalMiddle = 0.0;
      double periodTotalLower = 0.0;
      double tempUpper;
      double tempMiddle;
      double tempLower;
      double tempReal;
      int i;
      int outIdx;
      int trailingIdx;
      int lookbackTotal;
      /* Identify the minimum number of price bar needed
       * to calculate at least one output.
       */
      lookbackTotal = TA_SMA_Lookback(optInTimePeriod);
      /* Move up the start index if there is not
       * enough initial data.
       */
      if( startIdx < lookbackTotal )
      {
         startIdx = lookbackTotal;
      }
      /* Make sure there is still something to evaluate. */
      if( startIdx > endIdx )
      {
         *outBegIdx= 0;
         *outNBElement= 0;
         return TA_INSUFFICIENT_HISTORY;
      }
      /* Each band is a simple moving average maintained as a running sum over a
       * shared trailing window (all three share optInTimePeriod, so one trailing
       * index walks all three windows in lockstep):
       *    middle = SMA( close )
       *    upper  = SMA( high * (1 + 4*(high-low)/(high+low)) )
       *    lower  = SMA( low  * (1 - 4*(high-low)/(high+low)) )
       * When high+low is zero the upper/lower map degenerates to high/low.
       * Fusing the three moving averages into one loop is bit-identical to the
       * former "two scratch buffers + three sma() calls": each accumulator's
       * add/record/subtract order is unchanged, and the High/Low map is a pure
       * function recomputed from the raw trailing bar.
       */
      periodTotalUpper = 0.0;
      periodTotalMiddle = 0.0;
      periodTotalLower = 0.0;
      trailingIdx = startIdx - lookbackTotal;
      /* Warm up the running sums with the initial period,
       * except for the last value.
       */
      i = trailingIdx;
      while( i < startIdx )
      {
         /* The band factor 4*(H-L)/(H+L) is a ratio of two prices, so it is
          * scale-free -- but H+L is a sum that CANCELS when the two prices have
          * opposite signs, and the factor then blows up on what is left of the
          * operands' last bits. Test the sum against ITS OWN operands, not against
          * a fixed band: an absolute threshold answers "cancelled" for every bar
          * of an instrument quoted small enough to fall under it, and widened
          * every band it touched (issue #253). Same test on all three sites, so
          * the bar that enters a running sum is the one that later leaves it.
          */
         tempReal = inHigh[i] + inLow[i];
         if( !TA_IS_ZERO_SCALED(tempReal, fabs(inHigh[i]) + fabs(inLow[i])) )
         {
            tempReal = 4 * (inHigh[i] - inLow[i]) / tempReal;
            periodTotalUpper += inHigh[i] * (1 + tempReal);
            periodTotalLower += inLow[i] * (1 - tempReal);
         } else 
         {
            periodTotalUpper += inHigh[i];
            periodTotalLower += inLow[i];
         }
         periodTotalMiddle += inClose[i];
         i = i + 1;
      }
      /* Proceed with the calculation for the requested range.
       * Note that this algorithm allows the input and output to be the
       * same buffer: every trailing bar is read before any output is written.
       */
      outIdx = 0;
      while( i <= endIdx )
      {
         /* Add the incoming bar to each running sum. */
         tempReal = inHigh[i] + inLow[i];
         if( !TA_IS_ZERO_SCALED(tempReal, fabs(inHigh[i]) + fabs(inLow[i])) )
         {
            tempReal = 4 * (inHigh[i] - inLow[i]) / tempReal;
            periodTotalUpper += inHigh[i] * (1 + tempReal);
            periodTotalLower += inLow[i] * (1 - tempReal);
         } else 
         {
            periodTotalUpper += inHigh[i];
            periodTotalLower += inLow[i];
         }
         periodTotalMiddle += inClose[i];
         i = i + 1;
         /* Record the current window sums. */
         tempUpper = periodTotalUpper;
         tempMiddle = periodTotalMiddle;
         tempLower = periodTotalLower;
         /* Remove the trailing bar from each running sum. */
         tempReal = inHigh[trailingIdx] + inLow[trailingIdx];
         if( !TA_IS_ZERO_SCALED(tempReal, fabs(inHigh[trailingIdx]) + fabs(inLow[trailingIdx])) )
         {
            tempReal = 4 * (inHigh[trailingIdx] - inLow[trailingIdx]) / tempReal;
            periodTotalUpper -= inHigh[trailingIdx] * (1 + tempReal);
            periodTotalLower -= inLow[trailingIdx] * (1 - tempReal);
         } else 
         {
            periodTotalUpper -= inHigh[trailingIdx];
            periodTotalLower -= inLow[trailingIdx];
         }
         periodTotalMiddle -= inClose[trailingIdx];
         trailingIdx = trailingIdx + 1;
         /* Write the three bands. */
         outRealUpperBand[outIdx * outStride] = tempUpper / (double)optInTimePeriod;
         outRealMiddleBand[outIdx * outStride] = tempMiddle / (double)optInTimePeriod;
         outRealLowerBand[outIdx * outStride] = tempLower / (double)optInTimePeriod;
         outIdx = outIdx + 1;
      }
      *outBegIdx= startIdx;
      *outNBElement= outIdx;

      /* Capture the live batch state into the handle. */
      sp = (struct TA_ACCBANDS_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) { return TA_ALLOC_ERR; }
      memset( sp, 0, sizeof(*sp) );
      sp->optInTimePeriod = optInTimePeriod;
      sp->periodTotalUpper = periodTotalUpper;
      sp->periodTotalMiddle = periodTotalMiddle;
      sp->periodTotalLower = periodTotalLower;
      sp->ringCap_trailingIdx = (int)(i - trailingIdx);
      if( sp->ringCap_trailingIdx < 0 || sp->ringCap_trailingIdx > historyLen ) { TA_ACCBANDS_ReleaseImpl( sp ); return TA_INTERNAL_ERROR(185); }
      { size_t allocN = (size_t)(sp->ringCap_trailingIdx > 0 ? sp->ringCap_trailingIdx : 1);
        sp->ring_trailingIdx_inHigh = (double *)TA_Malloc( sizeof(double) * allocN );
        if( !sp->ring_trailingIdx_inHigh ) { TA_ACCBANDS_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
        memcpy( sp->ring_trailingIdx_inHigh, inHigh + (historyLen - sp->ringCap_trailingIdx), sizeof(double) * (size_t)sp->ringCap_trailingIdx );
        sp->ring_trailingIdx_inLow = (double *)TA_Malloc( sizeof(double) * allocN );
        if( !sp->ring_trailingIdx_inLow ) { TA_ACCBANDS_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
        memcpy( sp->ring_trailingIdx_inLow, inLow + (historyLen - sp->ringCap_trailingIdx), sizeof(double) * (size_t)sp->ringCap_trailingIdx );
        sp->ring_trailingIdx_inClose = (double *)TA_Malloc( sizeof(double) * allocN );
        if( !sp->ring_trailingIdx_inClose ) { TA_ACCBANDS_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
        memcpy( sp->ring_trailingIdx_inClose, inClose + (historyLen - sp->ringCap_trailingIdx), sizeof(double) * (size_t)sp->ringCap_trailingIdx );
      }
      sp->ringPos_trailingIdx = 0;
      sp->outRangeBegIdx = *outBegIdx;
      sp->outRangeCount = *outNBElement;
      sp->cur_outRealUpperBand = outRealUpperBand[(*outNBElement - 1) * outStride];
      sp->cur_outRealMiddleBand = outRealMiddleBand[(*outNBElement - 1) * outStride];
      sp->cur_outRealLowerBand = outRealLowerBand[(*outNBElement - 1) * outStride];
      *stream = sp;
      return TA_SUCCESS;
   }
}

/* Private function, not in public API. */
TA_RetCode TA_ACCBANDS_OpenInternal( struct TA_ACCBANDS_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], int startIdx, int historyLen, int optInTimePeriod, double *outRealUpperBand, double *outRealMiddleBand, double *outRealLowerBand )
{
   TA_RetCode retCode;
   int dummyBegIdx = 0;
   int dummyNBElement = 0;
   double sink_outRealUpperBand = 0.0;
   double sink_outRealMiddleBand = 0.0;
   double sink_outRealLowerBand = 0.0;
   retCode = TA_ACCBANDS_OpenImpl( stream, inHigh, inLow, inClose, startIdx, historyLen, optInTimePeriod, &dummyBegIdx, &dummyNBElement, &sink_outRealUpperBand, &sink_outRealMiddleBand, &sink_outRealLowerBand, 0 );
   if( retCode == TA_SUCCESS )
   {
      *outRealUpperBand = sink_outRealUpperBand;
      *outRealMiddleBand = sink_outRealMiddleBand;
      *outRealLowerBand = sink_outRealLowerBand;
   }
   return retCode;
}

TA_LIB_API TA_RetCode TA_ACCBANDS_Open( TA_ACCBANDS_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], int historyLen, int optInTimePeriod, double *outRealUpperBand, double *outRealMiddleBand, double *outRealLowerBand )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !inClose || !outRealUpperBand || !outRealMiddleBand || !outRealLowerBand ) return TA_BAD_PARAM;
   return TA_ACCBANDS_OpenInternal( stream, inHigh, inLow, inClose, 0, historyLen, optInTimePeriod, outRealUpperBand, outRealMiddleBand, outRealLowerBand );
}

TA_LIB_API TA_RetCode TA_ACCBANDS_OpenAndFill( TA_ACCBANDS_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], int historyLen, int optInTimePeriod, int *outBegIdx, int *outNBElement, double outRealUpperBand[], double outRealMiddleBand[], double outRealLowerBand[] )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !inClose || !outBegIdx || !outNBElement || !outRealUpperBand || !outRealMiddleBand || !outRealLowerBand ) return TA_BAD_PARAM;
   if( (const void *)outRealUpperBand == (const void *)inHigh || (const void *)outRealUpperBand == (const void *)inLow || (const void *)outRealUpperBand == (const void *)inClose || (const void *)outRealMiddleBand == (const void *)inHigh || (const void *)outRealMiddleBand == (const void *)inLow || (const void *)outRealMiddleBand == (const void *)inClose || (const void *)outRealLowerBand == (const void *)inHigh || (const void *)outRealLowerBand == (const void *)inLow || (const void *)outRealLowerBand == (const void *)inClose || (const void *)outRealUpperBand == (const void *)outRealMiddleBand || (const void *)outRealUpperBand == (const void *)outRealLowerBand || (const void *)outRealMiddleBand == (const void *)outRealLowerBand ) return TA_BAD_PARAM;
   return TA_ACCBANDS_OpenAndFillInternal( stream, inHigh, inLow, inClose, 0, historyLen, optInTimePeriod, outBegIdx, outNBElement, outRealUpperBand, outRealMiddleBand, outRealLowerBand );
}

/* Private function, not in public API. */
TA_RetCode TA_ACCBANDS_OpenAndFillInternal( struct TA_ACCBANDS_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], int startIdx, int historyLen, int optInTimePeriod, int *outBegIdx, int *outNBElement, double outRealUpperBand[], double outRealMiddleBand[], double outRealLowerBand[] )
{
   return TA_ACCBANDS_OpenImpl( stream, inHigh, inLow, inClose, startIdx, historyLen, optInTimePeriod, outBegIdx, outNBElement, outRealUpperBand, outRealMiddleBand, outRealLowerBand, 1 );
}

TA_LIB_API TA_RetCode TA_ACCBANDS_Update( TA_ACCBANDS_Stream *stream, double inHigh, double inLow, double inClose, double *outRealUpperBand, double *outRealMiddleBand, double *outRealLowerBand )
{
   if( !stream || !outRealUpperBand || !outRealMiddleBand || !outRealLowerBand ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) || !TA_IS_FINITE( inClose ) )
   {
      if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
      return TA_BAD_PARAM;
   }
   TA_ACCBANDS_StepImpl( stream, inHigh, inLow, inClose, outRealUpperBand, outRealMiddleBand, outRealLowerBand );
   if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_ACCBANDS_Peek( const TA_ACCBANDS_Stream *stream, double inHigh, double inLow, double inClose, double *outRealUpperBand, double *outRealMiddleBand, double *outRealLowerBand )
{
   struct TA_ACCBANDS_Stream scratch;
   struct TA_ACCBANDS_Stream *sp = &scratch;
   double tempUpper;
   double tempMiddle;
   double tempLower;
   double tempReal;
   int pkSlot0 = -1;
   double pkVal0 = 0.0;
   int pkSlot1 = -1;
   double pkVal1 = 0.0;
   int pkSlot2 = -1;
   double pkVal2 = 0.0;

   if( !stream || !outRealUpperBand || !outRealMiddleBand || !outRealLowerBand ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) || !TA_IS_FINITE( inClose ) ) return TA_BAD_PARAM;
   scratch = *stream;
   if( sp->ringCap_trailingIdx == 0 )
   {
      pkSlot0 = 0;
      pkVal0 = inHigh;
      pkSlot1 = 0;
      pkVal1 = inLow;
      pkSlot2 = 0;
      pkVal2 = inClose;
   }
   /* Add the incoming bar to each running sum. */
   tempReal = inHigh + inLow;
   if( !TA_IS_ZERO_SCALED(tempReal, fabs(inHigh) + fabs(inLow)) )
   {
      tempReal = 4 * (inHigh - inLow) / tempReal;
      sp->periodTotalUpper += inHigh * (1 + tempReal);
      sp->periodTotalLower += inLow * (1 - tempReal);
   } else 
   {
      sp->periodTotalUpper += inHigh;
      sp->periodTotalLower += inLow;
   }
   sp->periodTotalMiddle += inClose;
   /* Record the current window sums. */
   tempUpper = sp->periodTotalUpper;
   tempMiddle = sp->periodTotalMiddle;
   tempLower = sp->periodTotalLower;
   /* Remove the trailing bar from each running sum. */
   tempReal = ((sp->ringPos_trailingIdx != pkSlot0) ? sp->ring_trailingIdx_inHigh[sp->ringPos_trailingIdx] : pkVal0) + ((sp->ringPos_trailingIdx != pkSlot1) ? sp->ring_trailingIdx_inLow[sp->ringPos_trailingIdx] : pkVal1);
   if( !TA_IS_ZERO_SCALED(tempReal, fabs((sp->ringPos_trailingIdx != pkSlot0) ? sp->ring_trailingIdx_inHigh[sp->ringPos_trailingIdx] : pkVal0) + fabs((sp->ringPos_trailingIdx != pkSlot1) ? sp->ring_trailingIdx_inLow[sp->ringPos_trailingIdx] : pkVal1)) )
   {
      tempReal = 4 * (((sp->ringPos_trailingIdx != pkSlot0) ? sp->ring_trailingIdx_inHigh[sp->ringPos_trailingIdx] : pkVal0) - ((sp->ringPos_trailingIdx != pkSlot1) ? sp->ring_trailingIdx_inLow[sp->ringPos_trailingIdx] : pkVal1)) / tempReal;
      sp->periodTotalUpper -= ((sp->ringPos_trailingIdx != pkSlot0) ? sp->ring_trailingIdx_inHigh[sp->ringPos_trailingIdx] : pkVal0) * (1 + tempReal);
      sp->periodTotalLower -= ((sp->ringPos_trailingIdx != pkSlot1) ? sp->ring_trailingIdx_inLow[sp->ringPos_trailingIdx] : pkVal1) * (1 - tempReal);
   } else 
   {
      sp->periodTotalUpper -= (sp->ringPos_trailingIdx != pkSlot0) ? sp->ring_trailingIdx_inHigh[sp->ringPos_trailingIdx] : pkVal0;
      sp->periodTotalLower -= (sp->ringPos_trailingIdx != pkSlot1) ? sp->ring_trailingIdx_inLow[sp->ringPos_trailingIdx] : pkVal1;
   }
   sp->periodTotalMiddle -= (sp->ringPos_trailingIdx != pkSlot2) ? sp->ring_trailingIdx_inClose[sp->ringPos_trailingIdx] : pkVal2;
   /* Write the three bands. */
   *outRealUpperBand= tempUpper / (double)sp->optInTimePeriod;
   *outRealMiddleBand= tempMiddle / (double)sp->optInTimePeriod;
   *outRealLowerBand= tempLower / (double)sp->optInTimePeriod;
   sp->cur_outRealUpperBand = *outRealUpperBand;
   sp->cur_outRealMiddleBand = *outRealMiddleBand;
   sp->cur_outRealLowerBand = *outRealLowerBand;
   sp->ringPos_trailingIdx = sp->ringPos_trailingIdx + 1;
   if( sp->ringPos_trailingIdx >= sp->ringCap_trailingIdx )
   {
      sp->ringPos_trailingIdx = 0;
   }
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_ACCBANDS_UpdateAndFill( TA_ACCBANDS_Stream *stream, const double inHigh[], const double inLow[], const double inClose[], int barCount, double outRealUpperBand[], double outRealMiddleBand[], double outRealLowerBand[] )
{
   int i;

   if( !stream || !inHigh || !inLow || !inClose || !outRealUpperBand || !outRealMiddleBand || !outRealLowerBand ) return TA_BAD_PARAM;
   if( barCount < 0 ) return TA_BAD_PARAM;
   if( (const void *)outRealUpperBand == (const void *)inHigh || (const void *)outRealUpperBand == (const void *)inLow || (const void *)outRealUpperBand == (const void *)inClose || (const void *)outRealMiddleBand == (const void *)inHigh || (const void *)outRealMiddleBand == (const void *)inLow || (const void *)outRealMiddleBand == (const void *)inClose || (const void *)outRealLowerBand == (const void *)inHigh || (const void *)outRealLowerBand == (const void *)inLow || (const void *)outRealLowerBand == (const void *)inClose || (const void *)outRealUpperBand == (const void *)outRealMiddleBand || (const void *)outRealUpperBand == (const void *)outRealLowerBand || (const void *)outRealMiddleBand == (const void *)outRealLowerBand ) return TA_BAD_PARAM;
   for( i = 0; i < barCount; i++ )
   {
      if( !TA_IS_FINITE( inHigh[i] ) || !TA_IS_FINITE( inLow[i] ) || !TA_IS_FINITE( inClose[i] ) )
      {
         if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
         return TA_BAD_PARAM;
      }
      TA_ACCBANDS_StepImpl( stream, inHigh[i], inLow[i], inClose[i], &outRealUpperBand[i], &outRealMiddleBand[i], &outRealLowerBand[i] );
      if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   }
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_ACCBANDS_Close( TA_ACCBANDS_Stream *stream )
{
   TA_ACCBANDS_ReleaseImpl( stream );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_ACCBANDS_Value( const TA_ACCBANDS_Stream *stream, double *outRealUpperBand, double *outRealMiddleBand, double *outRealLowerBand )
{
   if( !stream || !outRealUpperBand || !outRealMiddleBand || !outRealLowerBand ) return TA_BAD_PARAM;
   *outRealUpperBand = stream->cur_outRealUpperBand;
   *outRealMiddleBand = stream->cur_outRealMiddleBand;
   *outRealLowerBand = stream->cur_outRealLowerBand;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_ACCBANDS_Clone( const TA_ACCBANDS_Stream *stream, TA_ACCBANDS_Stream **clone )
{
   struct TA_ACCBANDS_Stream *sp;

   if( !clone ) return TA_BAD_PARAM;
   *clone = NULL;
   if( !stream ) return TA_BAD_PARAM;
   sp = (struct TA_ACCBANDS_Stream *)TA_Malloc( sizeof(*sp) );
   if( !sp ) return TA_ALLOC_ERR;
   *sp = *stream;
   sp->ring_trailingIdx_inHigh = NULL;
   sp->ring_trailingIdx_inLow = NULL;
   sp->ring_trailingIdx_inClose = NULL;
   if( stream->ring_trailingIdx_inHigh )
   { size_t copyN = (size_t)(sp->ringCap_trailingIdx > 0 ? sp->ringCap_trailingIdx : 1);
     sp->ring_trailingIdx_inHigh = (double *)TA_Malloc( sizeof(double) * copyN );
     if( !sp->ring_trailingIdx_inHigh ) { TA_ACCBANDS_Close( sp ); return TA_ALLOC_ERR; }
     memcpy( sp->ring_trailingIdx_inHigh, stream->ring_trailingIdx_inHigh, sizeof(double) * copyN ); }
   if( stream->ring_trailingIdx_inLow )
   { size_t copyN = (size_t)(sp->ringCap_trailingIdx > 0 ? sp->ringCap_trailingIdx : 1);
     sp->ring_trailingIdx_inLow = (double *)TA_Malloc( sizeof(double) * copyN );
     if( !sp->ring_trailingIdx_inLow ) { TA_ACCBANDS_Close( sp ); return TA_ALLOC_ERR; }
     memcpy( sp->ring_trailingIdx_inLow, stream->ring_trailingIdx_inLow, sizeof(double) * copyN ); }
   if( stream->ring_trailingIdx_inClose )
   { size_t copyN = (size_t)(sp->ringCap_trailingIdx > 0 ? sp->ringCap_trailingIdx : 1);
     sp->ring_trailingIdx_inClose = (double *)TA_Malloc( sizeof(double) * copyN );
     if( !sp->ring_trailingIdx_inClose ) { TA_ACCBANDS_Close( sp ); return TA_ALLOC_ERR; }
     memcpy( sp->ring_trailingIdx_inClose, stream->ring_trailingIdx_inClose, sizeof(double) * copyN ); }
   *clone = sp;
   return TA_SUCCESS;
}

