/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_unguarded.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  MF       Mario Fortier
 *  JD       jdoyle
 *
 * Change history:
 *
 *  MMDDYY BY     Description
 *  -------------------------------------------------------------------
 *  120802 MF     Template creation.
 *  052603 MF     Adapt code to compile with .NET Managed C++
 *  111705 MF,JD  Fix#1359452 for handling properly start/end range.
 */

TA_LIB_API int TA_AD_Lookback( void )
{
   /* This function have no lookback needed. */
   return 0;
}

TA_LIB_API TA_RetCode TA_AD( int    startIdx,
                             int    endIdx,
                             const double inHigh[],
                             const double inLow[],
                             const double inClose[],
                             const double inVolume[],
                             int          *outBegIdx,
                             int          *outNBElement,
                             double        outReal[] )
{
   int nbBar;
   int currentBar;
   int outIdx;
   double high;
   double low;
   double close;
   double tmp;
   double ad;

   if( startIdx < 0 )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !inClose )
      return TA_BAD_PARAM;
   if( !inVolume )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   /* Note: Results from this function might vary slightly
    *       from Metastock outputs. The reason being that
    *       Metastock use float instead of double and this
    *       cause a different floating-point precision to
    *       be used.
    *
    *       For most function, this is not an apparent difference
    *       but for function using large cummulative values (like
    *       this AD function), minor imprecision adds up and becomes
    *       significative.
    *
    *       For better precision, TA-Lib use double in all its
    *       its calculations.
    */
   /* Default return values */
   nbBar = endIdx - startIdx + 1;
   *outNBElement= nbBar;
   *outBegIdx= startIdx;
   currentBar = startIdx;
   outIdx = 0;
   ad = 0.0;
   while( nbBar != 0 )
   {
      high = inHigh[currentBar];
      low = inLow[currentBar];
      tmp = high - low;
      close = inClose[currentBar];
      if( tmp > 0.0 )
      {
         ad += (close - low - (high - close)) / tmp * (double)inVolume[currentBar];
      }
      outReal[outIdx++] = ad;
      currentBar += 1;
      nbBar -= 1;
   }
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_AD_Unguarded( int    startIdx,
                                       int    endIdx,
                                       const double inHigh[],
                                       const double inLow[],
                                       const double inClose[],
                                       const double inVolume[],
                                       int          *outBegIdx,
                                       int          *outNBElement,
                                       double        outReal[] )
{
   int nbBar;
   int currentBar;
   int outIdx;
   double high;
   double low;
   double close;
   double tmp;
   double ad;

   nbBar = endIdx - startIdx + 1;
   *outNBElement= nbBar;
   *outBegIdx= startIdx;
   currentBar = startIdx;
   outIdx = 0;
   ad = 0.0;
   while( nbBar != 0 )
   {
      high = inHigh[currentBar];
      low = inLow[currentBar];
      tmp = high - low;
      close = inClose[currentBar];
      if( tmp > 0.0 )
      {
         ad += (close - low - (high - close)) / tmp * (double)inVolume[currentBar];
      }
      outReal[outIdx++] = ad;
      currentBar += 1;
      nbBar -= 1;
   }
   return TA_SUCCESS;
}

TA_RetCode TA_S_AD( int    startIdx,
                    int    endIdx,
                    const float inHigh[],
                    const float inLow[],
                    const float inClose[],
                    const float inVolume[],
                    int          *outBegIdx,
                    int          *outNBElement,
                    double        outReal[] )
{
   int nbBar;
   int currentBar;
   int outIdx;
   double high;
   double low;
   double close;
   double tmp;
   double ad;

   if( startIdx < 0 )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !inClose )
      return TA_BAD_PARAM;
   if( !inVolume )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   nbBar = endIdx - startIdx + 1;
   *outNBElement= nbBar;
   *outBegIdx= startIdx;
   currentBar = startIdx;
   outIdx = 0;
   ad = 0.0;
   while( nbBar != 0 )
   {
      high = (double)inHigh[currentBar];
      low = (double)inLow[currentBar];
      tmp = high - low;
      close = (double)inClose[currentBar];
      if( tmp > 0.0 )
      {
         ad += (close - low - (high - close)) / tmp * (double)inVolume[currentBar];
      }
      outReal[outIdx++] = ad;
      currentBar += 1;
      nbBar -= 1;
   }
   return TA_SUCCESS;
}

TA_RetCode TA_S_AD_Unguarded( int    startIdx,
                              int    endIdx,
                              const float inHigh[],
                              const float inLow[],
                              const float inClose[],
                              const float inVolume[],
                              int          *outBegIdx,
                              int          *outNBElement,
                              double        outReal[] )
{
   int nbBar;
   int currentBar;
   int outIdx;
   double high;
   double low;
   double close;
   double tmp;
   double ad;

   nbBar = endIdx - startIdx + 1;
   *outNBElement= nbBar;
   *outBegIdx= startIdx;
   currentBar = startIdx;
   outIdx = 0;
   ad = 0.0;
   while( nbBar != 0 )
   {
      high = (double)inHigh[currentBar];
      low = (double)inLow[currentBar];
      tmp = high - low;
      close = (double)inClose[currentBar];
      if( tmp > 0.0 )
      {
         ad += (close - low - (high - close)) / tmp * (double)inVolume[currentBar];
      }
      outReal[outIdx++] = ad;
      currentBar += 1;
      nbBar -= 1;
   }
   return TA_SUCCESS;
}

