/* TA-LIB Copyright (c) 1999-2026, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_stream_private.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  MF       Mario Fortier
 *  AM       Adrian Michel <michel@pacbell.net>
 *
 * Change history:
 *
 *  MMDDYY BY   Description
 *  -------------------------------------------------------------------
 *  120802 MF   Template creation.
 *  052603 MF   Adapt code to compile with .NET Managed C++
 *  050703 MF   Fix algorithm base on Adrian Michel bug report #748163
 */

TA_LIB_API int TA_AROON_Lookback( int optInTimePeriod )
{
   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 14;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return -1;
   return optInTimePeriod;
}

TA_LIB_API TA_RetCode TA_AROON( int    startIdx,
                                int    endIdx,
                                const double inHigh[],
                                const double inLow[],
                                int optInTimePeriod,
                                int          *outBegIdx,
                                int          *outNBElement,
                                double        outAroonDown[],
                                double        outAroonUp[] )
{
   double lowest;
   double highest;
   double tmp;
   double factor;
   int outIdx;
   int trailingIdx;
   int lowestIdx;
   int highestIdx;
   int today;
   int i;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 14;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outAroonDown )
      return TA_BAD_PARAM;
   if( !outAroonUp )
      return TA_BAD_PARAM;
   if( outAroonDown == outAroonUp )
      return TA_BAD_PARAM;

   /* This function is using a speed optimized algorithm
    * for the min/max logic.
    *
    * You might want to first look at how TA_MIN/TA_MAX works
    * and this function will become easier to understand.
    */
   /* Move up the start index if there is not
    * enough initial data.
    */
   if( startIdx < optInTimePeriod )
   {
      startIdx = optInTimePeriod;
   }
   /* Make sure there is still something to evaluate. */
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   /* Proceed with the calculation for the requested range.
    * Note that this algorithm allows the input and
    * output to be the same buffer.
    */
   outIdx = 0;
   today = startIdx;
   trailingIdx = startIdx - optInTimePeriod;
   lowestIdx = 0 - 1;
   highestIdx = 0 - 1;
   lowest = 0.0;
   highest = 0.0;
   factor = (double)100.0 / (double)optInTimePeriod;
   while( today <= endIdx )
   {
      /* Keep track of the lowestIdx */
      tmp = inLow[today];
      if( lowestIdx < trailingIdx )
      {
         lowestIdx = trailingIdx;
         lowest = inLow[lowestIdx];
         i = lowestIdx;
         TA_UNROLL(4)
         while( ++i <= today )
         {
            tmp = inLow[i];
            if( tmp <= lowest )
            {
               lowestIdx = i;
               lowest = tmp;
            }
         }
      } else if( tmp <= lowest )
      {
         lowestIdx = today;
         lowest = tmp;
      }
      /* Keep track of the highestIdx */
      tmp = inHigh[today];
      if( highestIdx < trailingIdx )
      {
         highestIdx = trailingIdx;
         highest = inHigh[highestIdx];
         i = highestIdx;
         TA_UNROLL(4)
         while( ++i <= today )
         {
            tmp = inHigh[i];
            if( tmp >= highest )
            {
               highestIdx = i;
               highest = tmp;
            }
         }
      } else if( tmp >= highest )
      {
         highestIdx = today;
         highest = tmp;
      }
      /* Note: Do not forget that input and output buffer can be the same,
       *       so writing to the output is the last thing being done here.
       */
      outAroonUp[outIdx] = factor * (optInTimePeriod - (today - highestIdx));
      outAroonDown[outIdx] = factor * (optInTimePeriod - (today - lowestIdx));
      outIdx += 1;
      trailingIdx += 1;
      today += 1;
   }
   /* Keep the outBegIdx relative to the
    * caller input before returning.
    */
   *outBegIdx= startIdx;
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

TA_RetCode TA_S_AROON( int    startIdx,
                       int    endIdx,
                       const float inHigh[],
                       const float inLow[],
                       int optInTimePeriod,
                       int          *outBegIdx,
                       int          *outNBElement,
                       double        outAroonDown[],
                       double        outAroonUp[] )
{
   double lowest;
   double highest;
   double tmp;
   double factor;
   int outIdx;
   int trailingIdx;
   int lowestIdx;
   int highestIdx;
   int today;
   int i;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 14;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outAroonDown )
      return TA_BAD_PARAM;
   if( !outAroonUp )
      return TA_BAD_PARAM;
   if( outAroonDown == outAroonUp )
      return TA_BAD_PARAM;

   if( startIdx < optInTimePeriod )
   {
      startIdx = optInTimePeriod;
   }
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   outIdx = 0;
   today = startIdx;
   trailingIdx = startIdx - optInTimePeriod;
   lowestIdx = 0 - 1;
   highestIdx = 0 - 1;
   lowest = 0.0;
   highest = 0.0;
   factor = (double)100.0 / (double)optInTimePeriod;
   while( today <= endIdx )
   {
      tmp = (double)inLow[today];
      if( lowestIdx < trailingIdx )
      {
         lowestIdx = trailingIdx;
         lowest = (double)inLow[lowestIdx];
         i = lowestIdx;
         TA_UNROLL(4)
         while( ++i <= today )
         {
            tmp = (double)inLow[i];
            if( tmp <= lowest )
            {
               lowestIdx = i;
               lowest = tmp;
            }
         }
      } else if( tmp <= lowest )
      {
         lowestIdx = today;
         lowest = tmp;
      }
      tmp = (double)inHigh[today];
      if( highestIdx < trailingIdx )
      {
         highestIdx = trailingIdx;
         highest = (double)inHigh[highestIdx];
         i = highestIdx;
         TA_UNROLL(4)
         while( ++i <= today )
         {
            tmp = (double)inHigh[i];
            if( tmp >= highest )
            {
               highestIdx = i;
               highest = tmp;
            }
         }
      } else if( tmp >= highest )
      {
         highestIdx = today;
         highest = tmp;
      }
      outAroonUp[outIdx] = factor * (optInTimePeriod - (today - highestIdx));
      outAroonDown[outIdx] = factor * (optInTimePeriod - (today - lowestIdx));
      outIdx += 1;
      trailingIdx += 1;
      today += 1;
   }
   *outBegIdx= startIdx;
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

/**** Streaming API *****/

struct TA_AROON_Stream {
   /* The bars this handle has an output for (see TA_StreamOutRange).
    * Kept first, and in this order, in every stream struct. */
   int outRangeBegIdx;
   int outRangeCount;
   /* The value(s) at the last bar the stream counted (see TA_AROON_Value). */
   double cur_outAroonDown;
   double cur_outAroonUp;
   int optInTimePeriod;
   double lowest;
   double highest;
   double factor;
   int trailingIdx;
   int lowestIdx;
   int highestIdx;
   int i;
   int today;
   int xCap;
   int xPhys;
   int xMask;
   double *x_inHigh;
   double *x_inLow;
};

/* Private function, not in public API. */
static void TA_AROON_ReleaseImpl( struct TA_AROON_Stream *sp )
{
   if( !sp ) return;
   if( sp->x_inHigh ) TA_Free( sp->x_inHigh );
   if( sp->x_inLow ) TA_Free( sp->x_inLow );
   TA_Free( sp );
}

/* Private function, not in public API. */
static void TA_AROON_StepImpl( struct TA_AROON_Stream *sp, double inHigh, double inLow, double *outAroonDown, double *outAroonUp )
{
   double tmp;

   if( sp->today >= 1073741824 )
   {
      int rebaseShift = sp->trailingIdx & ~sp->xMask;
      sp->today -= rebaseShift;
      sp->trailingIdx -= rebaseShift;
      sp->highestIdx -= rebaseShift;
      sp->i -= rebaseShift;
      sp->lowestIdx -= rebaseShift;
   }
   sp->x_inHigh[sp->today & sp->xMask] = inHigh;
   sp->x_inLow[sp->today & sp->xMask] = inLow;
   /* Keep track of the lowestIdx */
   tmp = sp->x_inLow[sp->today & sp->xMask];
   if( sp->lowestIdx < sp->trailingIdx )
   {
      sp->lowestIdx = sp->trailingIdx;
      sp->lowest = sp->x_inLow[sp->lowestIdx & sp->xMask];
      sp->i = sp->lowestIdx;
      TA_UNROLL(4)
      while( ++sp->i <= sp->today )
      {
         tmp = sp->x_inLow[sp->i & sp->xMask];
         if( tmp <= sp->lowest )
         {
            sp->lowestIdx = sp->i;
            sp->lowest = tmp;
         }
      }
   } else if( tmp <= sp->lowest )
   {
      sp->lowestIdx = sp->today;
      sp->lowest = tmp;
   }
   /* Keep track of the highestIdx */
   tmp = sp->x_inHigh[sp->today & sp->xMask];
   if( sp->highestIdx < sp->trailingIdx )
   {
      sp->highestIdx = sp->trailingIdx;
      sp->highest = sp->x_inHigh[sp->highestIdx & sp->xMask];
      sp->i = sp->highestIdx;
      TA_UNROLL(4)
      while( ++sp->i <= sp->today )
      {
         tmp = sp->x_inHigh[sp->i & sp->xMask];
         if( tmp >= sp->highest )
         {
            sp->highestIdx = sp->i;
            sp->highest = tmp;
         }
      }
   } else if( tmp >= sp->highest )
   {
      sp->highestIdx = sp->today;
      sp->highest = tmp;
   }
   /* Note: Do not forget that input and output buffer can be the same,
    *       so writing to the output is the last thing being done here.
    */
   *outAroonUp= sp->factor * (sp->optInTimePeriod - (sp->today - sp->highestIdx));
   *outAroonDown= sp->factor * (sp->optInTimePeriod - (sp->today - sp->lowestIdx));
   sp->trailingIdx += 1;
   sp->today += 1;
   sp->cur_outAroonDown = *outAroonDown;
   sp->cur_outAroonUp = *outAroonUp;
}

static TA_RetCode TA_AROON_OpenImpl( struct TA_AROON_Stream **stream, const double inHigh[], const double inLow[], int startIdx, int historyLen, int optInTimePeriod, int *outBegIdx, int *outNBElement, double outAroonDown[], double outAroonUp[], int outStride )
{
   struct TA_AROON_Stream *sp;
   int endIdx;
   int dummyBegIdx;
   int dummyNBElement;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !outAroonDown || !outAroonUp ) return TA_BAD_PARAM;
   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 14;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( startIdx > historyLen - 1 )
   {
      *outBegIdx = 0;
      *outNBElement = 0;
      return TA_INSUFFICIENT_HISTORY;
   }

   endIdx = historyLen - 1;
   dummyBegIdx = 0;
   dummyNBElement = 0;
   (void)startIdx; (void)dummyBegIdx; (void)dummyNBElement;

   {
      double lowest = 0.0;
      double highest = 0.0;
      double tmp;
      double factor = 0.0;
      int outIdx;
      int trailingIdx = 0;
      int lowestIdx = 0;
      int highestIdx = 0;
      int today = 0;
      int i = 0;
      /* This function is using a speed optimized algorithm
       * for the min/max logic.
       *
       * You might want to first look at how TA_MIN/TA_MAX works
       * and this function will become easier to understand.
       */
      /* Move up the start index if there is not
       * enough initial data.
       */
      if( startIdx < optInTimePeriod )
      {
         startIdx = optInTimePeriod;
      }
      /* Make sure there is still something to evaluate. */
      if( startIdx > endIdx )
      {
         *outBegIdx= 0;
         *outNBElement= 0;
         return TA_INSUFFICIENT_HISTORY;
      }
      /* Proceed with the calculation for the requested range.
       * Note that this algorithm allows the input and
       * output to be the same buffer.
       */
      outIdx = 0;
      today = startIdx;
      trailingIdx = startIdx - optInTimePeriod;
      lowestIdx = 0 - 1;
      highestIdx = 0 - 1;
      lowest = 0.0;
      highest = 0.0;
      factor = (double)100.0 / (double)optInTimePeriod;
      while( today <= endIdx )
      {
         /* Keep track of the lowestIdx */
         tmp = inLow[today];
         if( lowestIdx < trailingIdx )
         {
            lowestIdx = trailingIdx;
            lowest = inLow[lowestIdx];
            i = lowestIdx;
            TA_UNROLL(4)
            while( ++i <= today )
            {
               tmp = inLow[i];
               if( tmp <= lowest )
               {
                  lowestIdx = i;
                  lowest = tmp;
               }
            }
         } else if( tmp <= lowest )
         {
            lowestIdx = today;
            lowest = tmp;
         }
         /* Keep track of the highestIdx */
         tmp = inHigh[today];
         if( highestIdx < trailingIdx )
         {
            highestIdx = trailingIdx;
            highest = inHigh[highestIdx];
            i = highestIdx;
            TA_UNROLL(4)
            while( ++i <= today )
            {
               tmp = inHigh[i];
               if( tmp >= highest )
               {
                  highestIdx = i;
                  highest = tmp;
               }
            }
         } else if( tmp >= highest )
         {
            highestIdx = today;
            highest = tmp;
         }
         /* Note: Do not forget that input and output buffer can be the same,
          *       so writing to the output is the last thing being done here.
          */
         outAroonUp[outIdx * outStride] = factor * (optInTimePeriod - (today - highestIdx));
         outAroonDown[outIdx * outStride] = factor * (optInTimePeriod - (today - lowestIdx));
         outIdx += 1;
         trailingIdx += 1;
         today += 1;
      }
      /* Keep the outBegIdx relative to the
       * caller input before returning.
       */
      *outBegIdx= startIdx;
      *outNBElement= outIdx;

      /* Capture the live batch state into the handle. */
      sp = (struct TA_AROON_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) { return TA_ALLOC_ERR; }
      memset( sp, 0, sizeof(*sp) );
      sp->optInTimePeriod = optInTimePeriod;
      sp->lowest = lowest;
      sp->highest = highest;
      sp->factor = factor;
      sp->trailingIdx = trailingIdx;
      sp->lowestIdx = lowestIdx;
      sp->highestIdx = highestIdx;
      sp->i = i;
      sp->today = today;
      sp->xCap = (int)(today - trailingIdx) + 1;
      if( sp->xCap < 1 || sp->xCap > historyLen ) { TA_AROON_ReleaseImpl( sp ); return TA_INTERNAL_ERROR(188); }
      sp->xPhys = 1;
      while( sp->xPhys < sp->xCap ) sp->xPhys <<= 1;
      sp->xMask = sp->xPhys - 1;
      sp->x_inHigh = (double *)TA_Malloc( sizeof(double) * (size_t)sp->xPhys );
      if( !sp->x_inHigh ) { TA_AROON_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
      sp->x_inLow = (double *)TA_Malloc( sizeof(double) * (size_t)sp->xPhys );
      if( !sp->x_inLow ) { TA_AROON_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
      { int fillJ;
        for( fillJ = historyLen - sp->xCap; fillJ < historyLen; fillJ++ )
        {
           sp->x_inHigh[fillJ & sp->xMask] = inHigh[fillJ];
           sp->x_inLow[fillJ & sp->xMask] = inLow[fillJ];
        }
      }
      sp->outRangeBegIdx = *outBegIdx;
      sp->outRangeCount = *outNBElement;
      sp->cur_outAroonDown = outAroonDown[(*outNBElement - 1) * outStride];
      sp->cur_outAroonUp = outAroonUp[(*outNBElement - 1) * outStride];
      *stream = sp;
      return TA_SUCCESS;
   }
}

/* Private function, not in public API. */
TA_RetCode TA_AROON_OpenInternal( struct TA_AROON_Stream **stream, const double inHigh[], const double inLow[], int startIdx, int historyLen, int optInTimePeriod, double *outAroonDown, double *outAroonUp )
{
   TA_RetCode retCode;
   int dummyBegIdx = 0;
   int dummyNBElement = 0;
   double sink_outAroonDown = 0.0;
   double sink_outAroonUp = 0.0;
   retCode = TA_AROON_OpenImpl( stream, inHigh, inLow, startIdx, historyLen, optInTimePeriod, &dummyBegIdx, &dummyNBElement, &sink_outAroonDown, &sink_outAroonUp, 0 );
   if( retCode == TA_SUCCESS )
   {
      *outAroonDown = sink_outAroonDown;
      *outAroonUp = sink_outAroonUp;
   }
   return retCode;
}

TA_LIB_API TA_RetCode TA_AROON_Open( TA_AROON_Stream **stream, const double inHigh[], const double inLow[], int historyLen, int optInTimePeriod, double *outAroonDown, double *outAroonUp )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !outAroonDown || !outAroonUp ) return TA_BAD_PARAM;
   return TA_AROON_OpenInternal( stream, inHigh, inLow, 0, historyLen, optInTimePeriod, outAroonDown, outAroonUp );
}

TA_LIB_API TA_RetCode TA_AROON_OpenAndFill( TA_AROON_Stream **stream, const double inHigh[], const double inLow[], int historyLen, int optInTimePeriod, int *outBegIdx, int *outNBElement, double outAroonDown[], double outAroonUp[] )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !outBegIdx || !outNBElement || !outAroonDown || !outAroonUp ) return TA_BAD_PARAM;
   if( (const void *)outAroonDown == (const void *)inHigh || (const void *)outAroonDown == (const void *)inLow || (const void *)outAroonUp == (const void *)inHigh || (const void *)outAroonUp == (const void *)inLow || (const void *)outAroonDown == (const void *)outAroonUp ) return TA_BAD_PARAM;
   return TA_AROON_OpenAndFillInternal( stream, inHigh, inLow, 0, historyLen, optInTimePeriod, outBegIdx, outNBElement, outAroonDown, outAroonUp );
}

/* Private function, not in public API. */
TA_RetCode TA_AROON_OpenAndFillInternal( struct TA_AROON_Stream **stream, const double inHigh[], const double inLow[], int startIdx, int historyLen, int optInTimePeriod, int *outBegIdx, int *outNBElement, double outAroonDown[], double outAroonUp[] )
{
   return TA_AROON_OpenImpl( stream, inHigh, inLow, startIdx, historyLen, optInTimePeriod, outBegIdx, outNBElement, outAroonDown, outAroonUp, 1 );
}

TA_LIB_API TA_RetCode TA_AROON_Update( TA_AROON_Stream *stream, double inHigh, double inLow, double *outAroonDown, double *outAroonUp )
{
   if( !stream || !outAroonDown || !outAroonUp ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) )
   {
      if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
      return TA_BAD_PARAM;
   }
   TA_AROON_StepImpl( stream, inHigh, inLow, outAroonDown, outAroonUp );
   if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_AROON_Peek( const TA_AROON_Stream *stream, double inHigh, double inLow, double *outAroonDown, double *outAroonUp )
{
   struct TA_AROON_Stream scratch;
   struct TA_AROON_Stream *sp = &scratch;
   double tmp;
   int pkSlot0 = -1;
   double pkVal0 = 0.0;
   int pkSlot1 = -1;
   double pkVal1 = 0.0;

   if( !stream || !outAroonDown || !outAroonUp ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) ) return TA_BAD_PARAM;
   scratch = *stream;
   if( sp->today >= 1073741824 )
   {
      int rebaseShift = sp->trailingIdx & ~sp->xMask;
      sp->today -= rebaseShift;
      sp->trailingIdx -= rebaseShift;
      sp->highestIdx -= rebaseShift;
      sp->i -= rebaseShift;
      sp->lowestIdx -= rebaseShift;
   }
   pkSlot0 = sp->today & sp->xMask;
   pkVal0 = inHigh;
   pkSlot1 = sp->today & sp->xMask;
   pkVal1 = inLow;
   /* Keep track of the lowestIdx */
   tmp = ((sp->today & sp->xMask) != pkSlot1) ? sp->x_inLow[sp->today & sp->xMask] : pkVal1;
   if( sp->lowestIdx < sp->trailingIdx )
   {
      sp->lowestIdx = sp->trailingIdx;
      sp->lowest = ((sp->lowestIdx & sp->xMask) != pkSlot1) ? sp->x_inLow[sp->lowestIdx & sp->xMask] : pkVal1;
      sp->i = sp->lowestIdx;
      TA_UNROLL(4)
      while( ++sp->i <= sp->today )
      {
         tmp = ((sp->i & sp->xMask) != pkSlot1) ? sp->x_inLow[sp->i & sp->xMask] : pkVal1;
         if( tmp <= sp->lowest )
         {
            sp->lowestIdx = sp->i;
            sp->lowest = tmp;
         }
      }
   } else if( tmp <= sp->lowest )
   {
      sp->lowestIdx = sp->today;
      sp->lowest = tmp;
   }
   /* Keep track of the highestIdx */
   tmp = ((sp->today & sp->xMask) != pkSlot0) ? sp->x_inHigh[sp->today & sp->xMask] : pkVal0;
   if( sp->highestIdx < sp->trailingIdx )
   {
      sp->highestIdx = sp->trailingIdx;
      sp->highest = ((sp->highestIdx & sp->xMask) != pkSlot0) ? sp->x_inHigh[sp->highestIdx & sp->xMask] : pkVal0;
      sp->i = sp->highestIdx;
      TA_UNROLL(4)
      while( ++sp->i <= sp->today )
      {
         tmp = ((sp->i & sp->xMask) != pkSlot0) ? sp->x_inHigh[sp->i & sp->xMask] : pkVal0;
         if( tmp >= sp->highest )
         {
            sp->highestIdx = sp->i;
            sp->highest = tmp;
         }
      }
   } else if( tmp >= sp->highest )
   {
      sp->highestIdx = sp->today;
      sp->highest = tmp;
   }
   /* Note: Do not forget that input and output buffer can be the same,
    *       so writing to the output is the last thing being done here.
    */
   *outAroonUp= sp->factor * (sp->optInTimePeriod - (sp->today - sp->highestIdx));
   *outAroonDown= sp->factor * (sp->optInTimePeriod - (sp->today - sp->lowestIdx));
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_AROON_UpdateAndFill( TA_AROON_Stream *stream, const double inHigh[], const double inLow[], int barCount, double outAroonDown[], double outAroonUp[] )
{
   int i;

   if( !stream || !inHigh || !inLow || !outAroonDown || !outAroonUp ) return TA_BAD_PARAM;
   if( barCount < 0 ) return TA_BAD_PARAM;
   if( (const void *)outAroonDown == (const void *)inHigh || (const void *)outAroonDown == (const void *)inLow || (const void *)outAroonUp == (const void *)inHigh || (const void *)outAroonUp == (const void *)inLow || (const void *)outAroonDown == (const void *)outAroonUp ) return TA_BAD_PARAM;
   for( i = 0; i < barCount; i++ )
   {
      if( !TA_IS_FINITE( inHigh[i] ) || !TA_IS_FINITE( inLow[i] ) )
      {
         if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
         return TA_BAD_PARAM;
      }
      TA_AROON_StepImpl( stream, inHigh[i], inLow[i], &outAroonDown[i], &outAroonUp[i] );
      if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   }
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_AROON_Close( TA_AROON_Stream *stream )
{
   TA_AROON_ReleaseImpl( stream );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_AROON_Value( const TA_AROON_Stream *stream, double *outAroonDown, double *outAroonUp )
{
   if( !stream || !outAroonDown || !outAroonUp ) return TA_BAD_PARAM;
   *outAroonDown = stream->cur_outAroonDown;
   *outAroonUp = stream->cur_outAroonUp;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_AROON_Clone( const TA_AROON_Stream *stream, TA_AROON_Stream **clone )
{
   struct TA_AROON_Stream *sp;

   if( !clone ) return TA_BAD_PARAM;
   *clone = NULL;
   if( !stream ) return TA_BAD_PARAM;
   sp = (struct TA_AROON_Stream *)TA_Malloc( sizeof(*sp) );
   if( !sp ) return TA_ALLOC_ERR;
   *sp = *stream;
   sp->x_inHigh = NULL;
   sp->x_inLow = NULL;
   if( stream->x_inHigh )
   { size_t copyN = (size_t)(sp->xPhys);
     sp->x_inHigh = (double *)TA_Malloc( sizeof(double) * copyN );
     if( !sp->x_inHigh ) { TA_AROON_Close( sp ); return TA_ALLOC_ERR; }
     memcpy( sp->x_inHigh, stream->x_inHigh, sizeof(double) * copyN ); }
   if( stream->x_inLow )
   { size_t copyN = (size_t)(sp->xPhys);
     sp->x_inLow = (double *)TA_Malloc( sizeof(double) * copyN );
     if( !sp->x_inLow ) { TA_AROON_Close( sp ); return TA_ALLOC_ERR; }
     memcpy( sp->x_inLow, stream->x_inLow, sizeof(double) * copyN ); }
   *clone = sp;
   return TA_SUCCESS;
}

