/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_unguarded.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  MF       Mario Fortier
 *
 *
 * Change history:
 *
 *  MMDDYY BY   Description
 *  -------------------------------------------------------------------
 *  112605 MF   Initial coding.
 */

TA_LIB_API int TA_BOP_Lookback( void )
{
   return 0;
}

TA_LIB_API TA_RetCode TA_BOP( int    startIdx,
                              int    endIdx,
                              const double inOpen[],
                              const double inHigh[],
                              const double inLow[],
                              const double inClose[],
                              int          *outBegIdx,
                              int          *outNBElement,
                              double        outReal[] )
{
   int outIdx;
   int i;
   double tempReal;

   if( startIdx < 0 )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( !inOpen )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !inClose )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   /* BOP = (Close - Open)/(High - Low) */
   outIdx = 0;
   for( i = startIdx; i <= endIdx; i += 1 )
   {
      tempReal = inHigh[i] - inLow[i];
      if( TA_IS_ZERO_OR_NEG(tempReal) )
      {
         outReal[outIdx++] = 0.0;
      } else 
      {
         outReal[outIdx++] = (inClose[i] - inOpen[i]) / tempReal;
      }
   }
   *outNBElement= outIdx;
   *outBegIdx= startIdx;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_BOP_Unguarded( int    startIdx,
                                        int    endIdx,
                                        const double inOpen[],
                                        const double inHigh[],
                                        const double inLow[],
                                        const double inClose[],
                                        int          *outBegIdx,
                                        int          *outNBElement,
                                        double        outReal[] )
{
   int outIdx;
   int i;
   double tempReal;

   outIdx = 0;
   for( i = startIdx; i <= endIdx; i += 1 )
   {
      tempReal = inHigh[i] - inLow[i];
      if( TA_IS_ZERO_OR_NEG(tempReal) )
      {
         outReal[outIdx++] = 0.0;
      } else 
      {
         outReal[outIdx++] = (inClose[i] - inOpen[i]) / tempReal;
      }
   }
   *outNBElement= outIdx;
   *outBegIdx= startIdx;
   return TA_SUCCESS;
}

TA_RetCode TA_S_BOP( int    startIdx,
                     int    endIdx,
                     const float inOpen[],
                     const float inHigh[],
                     const float inLow[],
                     const float inClose[],
                     int          *outBegIdx,
                     int          *outNBElement,
                     double        outReal[] )
{
   int outIdx;
   int i;
   double tempReal;

   if( startIdx < 0 )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( !inOpen )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !inClose )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   outIdx = 0;
   for( i = startIdx; i <= endIdx; i += 1 )
   {
      tempReal = (double)inHigh[i] - (double)inLow[i];
      if( TA_IS_ZERO_OR_NEG(tempReal) )
      {
         outReal[outIdx++] = 0.0;
      } else 
      {
         outReal[outIdx++] = ((double)inClose[i] - (double)inOpen[i]) / tempReal;
      }
   }
   *outNBElement= outIdx;
   *outBegIdx= startIdx;
   return TA_SUCCESS;
}

TA_RetCode TA_S_BOP_Unguarded( int    startIdx,
                               int    endIdx,
                               const float inOpen[],
                               const float inHigh[],
                               const float inLow[],
                               const float inClose[],
                               int          *outBegIdx,
                               int          *outNBElement,
                               double        outReal[] )
{
   int outIdx;
   int i;
   double tempReal;

   outIdx = 0;
   for( i = startIdx; i <= endIdx; i += 1 )
   {
      tempReal = (double)inHigh[i] - (double)inLow[i];
      if( TA_IS_ZERO_OR_NEG(tempReal) )
      {
         outReal[outIdx++] = 0.0;
      } else 
      {
         outReal[outIdx++] = ((double)inClose[i] - (double)inOpen[i]) / tempReal;
      }
   }
   *outNBElement= outIdx;
   *outBegIdx= startIdx;
   return TA_SUCCESS;
}

/**** Streaming API *****/

struct TA_BOP_Stream {
   int unused; /* T1: stateless map */
};

static void TA_BOP_StreamStep( struct TA_BOP_Stream *sp, double inOpen, double inHigh, double inLow, double inClose, double *outReal )
{
   double tempReal;

   (void)sp;
   tempReal = inHigh - inLow;
   if( TA_IS_ZERO_OR_NEG(tempReal) )
   {
      *outReal= 0.0;
   } else 
   {
      *outReal= (inClose - inOpen) / tempReal;
   }
}

TA_LIB_API TA_RetCode TA_BOP_Open( const double inOpen[], const double inHigh[], const double inLow[], const double inClose[], int historyLen, TA_BOP_Stream **stream, double *outReal )
{
   struct TA_BOP_Stream *sp;
   int startIdx;
   int endIdx;
   int dummyBegIdx;
   int dummyNBElement;
   double lastValue_outReal;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( !inOpen || !inHigh || !inLow || !inClose || !outReal ) return TA_BAD_PARAM;
   if( historyLen < 1 ) return TA_BAD_PARAM;

   startIdx = 0;
   endIdx = historyLen - 1;
   dummyBegIdx = 0;
   dummyNBElement = 0;
   lastValue_outReal = 0.0;
   (void)startIdx; (void)dummyBegIdx; (void)dummyNBElement;

   {
      int outIdx;
      int i;
      double tempReal;
      /* BOP = (Close - Open)/(High - Low) */
      outIdx = 0;
      for( i = startIdx; i <= endIdx; i += 1 )
      {
         tempReal = inHigh[i] - inLow[i];
         if( TA_IS_ZERO_OR_NEG(tempReal) )
         {
            lastValue_outReal = 0.0;
         } else 
         {
            lastValue_outReal = (inClose[i] - inOpen[i]) / tempReal;
         }
      }
      dummyNBElement = outIdx;
      dummyBegIdx = startIdx;

      /* Capture the live batch state into the handle. */
      sp = (struct TA_BOP_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) return TA_ALLOC_ERR;
      memset( sp, 0, sizeof(*sp) );
      *outReal = lastValue_outReal;
      *stream = sp;
      return TA_SUCCESS;
   }
}

TA_LIB_API TA_RetCode TA_BOP_Update( TA_BOP_Stream *stream, double inOpen, double inHigh, double inLow, double inClose, double *outReal )
{
   if( !stream || !outReal ) return TA_BAD_PARAM;
   TA_BOP_StreamStep( stream, inOpen, inHigh, inLow, inClose, outReal );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_BOP_Peek( const TA_BOP_Stream *stream, double inOpen, double inHigh, double inLow, double inClose, double *outReal )
{
   struct TA_BOP_Stream scratch;

   if( !stream || !outReal ) return TA_BAD_PARAM;
   scratch = *stream;
   TA_BOP_StreamStep( &scratch, inOpen, inHigh, inLow, inClose, outReal );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_BOP_Close( TA_BOP_Stream *stream )
{
   if( stream ) TA_Free( stream );
   return TA_SUCCESS;
}

