/* TA-LIB Copyright (c) 1999-2026, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_stream_private.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  MF       Mario Fortier
 *  JV       Jesus Viver <324122@cienz.unizar.es>
 *  CC       Claude Code (AI assistant)
 *
 *
 * Change history:
 *
 *  MMDDYY BY     Description
 *  -------------------------------------------------------------------
 *  112400 MF     Template creation.
 *  010503 MF     Fix to always use SMA for the STDDEV (Thanks to JV).
 *  052603 MF     Adapt code to compile with .NET Managed C++
 *  070626 MF,CC  Fix #99: realign the middle band when the standard
 *                deviation clamps to a later begIdx than the
 *                (period-independent) MAMA lookback, for
 *                optInTimePeriod >= 34.
 *  071126 MF,CC  Split into an SMA fast path (reuses the moving average as the
 *                mean) and a general MA + STDDEV path, so BBANDS streams as a
 *                composition of the TA_MA and TA_STDDEV streams. Bit-identical.
 *  071626 MF,CC  #117 speed optimization: fuse the SMA fast path's moving
 *                average and standard deviation into a single pass. Bit-identical.
 *  071726 MF,CC  #118 SMA-path deviation now uses the cancellation-free variance
 *                (var.c); two recurrences in one pass. Bit-identical.
 *  072426 MF,CC  Lookback is now max(MA, STDDEV) so it is honest for MA types
 *                whose lookback is below the deviation's (MAMA >= 34, and
 *                TA_MAType_DISABLED); required for streaming (issue #93).
 *  082326 MF,CC  #243 the SMA path's TA_EPSILON test on the variance is replaced
 *                by var.c's scale-relative reseed floor; the square root is
 *                unconditional. Bands no longer collapse on a fine tick.
 */

TA_LIB_API int TA_BBANDS_Lookback( int optInTimePeriod, double optInNbDevUp, double optInNbDevDn, TA_MAType optInMAType )
{
   int maLookback;
   int stddevLookback;
   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 20;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return -1;
   if( optInNbDevUp == TA_REAL_DEFAULT )
      optInNbDevUp = 2;
   else if( !(optInNbDevUp >= TA_REAL_MIN && optInNbDevUp <= TA_REAL_MAX) )
      return -1;
   if( optInNbDevDn == TA_REAL_DEFAULT )
      optInNbDevDn = 2;
   else if( !(optInNbDevDn >= TA_REAL_MIN && optInNbDevDn <= TA_REAL_MAX) )
      return -1;
   if( (int)optInMAType == TA_INTEGER_DEFAULT || optInMAType == TA_MAType_DEFAULT )
      optInMAType = 0;
   else if( (int)optInMAType < TA_MATYPE_MIN || (int)optInMAType > TA_MATYPE_MAX )
      return -1;
   /* A band value needs BOTH the middle-band moving average and the standard
    * deviation of the outer bands, so the first valid output is the later of the
    * two lookbacks. For every MA type whose lookback is at least
    * optInTimePeriod-1 this equals the MA lookback (unchanged); it rises above it
    * only when the MA lookback is the smaller one - TA_MAType_MAMA at
    * optInTimePeriod >= 34 (constant MAMA lookback 32) and TA_MAType_DISABLED
    * (MA lookback 0, issue #93). Reporting the honest value keeps
    * outBegIdx == lookback: issue #99 kept it at the MA lookback, which
    * under-reported those cases (outBegIdx > lookback) and broke streaming, whose
    * Open is tied to lookback+1. The middle band still begins at the MA's earlier
    * begIdx internally and is realigned to this later bar in bbands() below.
    */
   maLookback = TA_MA_Lookback(optInTimePeriod,optInMAType);
   stddevLookback = TA_STDDEV_Lookback(optInTimePeriod,1.0);
   return (maLookback > stddevLookback) ? maLookback : stddevLookback;
}

TA_FMA_MULTIVERSION
TA_LIB_API TA_RetCode TA_BBANDS( int    startIdx,
                                 int    endIdx,
                                 const double inReal[],
                                 int optInTimePeriod,
                                 double optInNbDevUp,
                                 double optInNbDevDn,
                                 TA_MAType optInMAType,
                                 int          *outBegIdx,
                                 int          *outNBElement,
                                 double        outRealUpperBand[],
                                 double        outRealMiddleBand[],
                                 double        outRealLowerBand[] )
{
   TA_RetCode retCode;
   int i;
   int maBegIdx;
   int shiftIdx;
   double tempReal;
   double tempReal2;
   double *tempBuffer1;
   double *tempBuffer2;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 20;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( optInNbDevUp == TA_REAL_DEFAULT )
      optInNbDevUp = 2;
   else if( !(optInNbDevUp >= TA_REAL_MIN && optInNbDevUp <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( optInNbDevDn == TA_REAL_DEFAULT )
      optInNbDevDn = 2;
   else if( !(optInNbDevDn >= TA_REAL_MIN && optInNbDevDn <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( (int)optInMAType == TA_INTEGER_DEFAULT || optInMAType == TA_MAType_DEFAULT )
      optInMAType = 0;
   else if( (int)optInMAType < TA_MATYPE_MIN || (int)optInMAType > TA_MATYPE_MAX )
      return TA_BAD_PARAM;
   if( !inReal )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outRealUpperBand )
      return TA_BAD_PARAM;
   if( !outRealMiddleBand )
      return TA_BAD_PARAM;
   if( !outRealLowerBand )
      return TA_BAD_PARAM;
   if( outRealUpperBand == outRealMiddleBand || outRealUpperBand == outRealLowerBand || outRealMiddleBand == outRealLowerBand )
      return TA_BAD_PARAM;

   if( optInMAType == TA_MAType_SMA )
   {
      /* SMA fast path: the middle band (SMA) and the standard deviation share one
       * pass over the window below. Bit-identical to the general MA + STDDEV path
       * (which the stream composes for every MA type).
       *
       * Identify TWO temporary buffers among the outputs so the calculation
       * needs no memory allocation; whenever possible make tempBuffer1 be the
       * middle band output, saving one copy operation.
       */
      if( inReal == outRealUpperBand )
      {
         tempBuffer1 = outRealMiddleBand;
         tempBuffer2 = outRealLowerBand;
      } else if( inReal == outRealLowerBand )
      {
         tempBuffer1 = outRealMiddleBand;
         tempBuffer2 = outRealUpperBand;
      } else if( inReal == outRealMiddleBand )
      {
         tempBuffer1 = outRealLowerBand;
         tempBuffer2 = outRealUpperBand;
      } else 
      {
         tempBuffer1 = outRealMiddleBand;
         tempBuffer2 = outRealUpperBand;
      }
      /* Check that the caller is not doing tricky things.
       * (like using the input buffer in two output!)
       */
      if( tempBuffer1 == inReal || tempBuffer2 == inReal )
      {
         return TA_BAD_PARAM;
      }
      /* One pass with two independent recurrences: the SMA running sum (maTotal,
       * mean -> tempBuffer1, bit-identical to TA_MA(SMA)) and the shifted-data
       * variance (-> tempBuffer2, bit-identical to TA_STDDEV/TA_VAR - see var.c).
       * The variance carries its own shift and reseed; the SMA sum is untouched by
       * it. tempBuffer1/2 never alias inReal (checked above).
       */
      double maTotal;
      double shift;
      double varTotal1;
      double varTotal2;
      double meanValue1;
      double variance;
      double _invPeriod;
      double _tempReal;
      int _i;
      int _j;
      int _outIdx;
      int _trailingIdx;
      int _windowStart;
      int _lookbackTotal;
      int _barsSinceReseed;
      _lookbackTotal = optInTimePeriod - 1;
      if( startIdx < _lookbackTotal )
      {
         startIdx = _lookbackTotal;
      }
      if( startIdx > endIdx )
      {
         *outBegIdx= 0;
         *outNBElement= 0;
         return TA_SUCCESS;
      }
      _invPeriod = 1.0 / (double)optInTimePeriod;
      _trailingIdx = startIdx - _lookbackTotal;
      shift = inReal[_trailingIdx];
      maTotal = 0.0;
      varTotal1 = 0.0;
      varTotal2 = 0.0;
      for( _j = _trailingIdx; _j < startIdx; _j += 1 )
      {
         maTotal += inReal[_j];
         _tempReal = inReal[_j] - shift;
         varTotal1 += _tempReal;
         _tempReal *= _tempReal;
         varTotal2 += _tempReal;
      }
      _i = startIdx;
      _outIdx = 0;
      _barsSinceReseed = 32 * optInTimePeriod;
      do
      {
         maTotal += inReal[_i];
         _tempReal = inReal[_i] - shift;
         varTotal1 += _tempReal;
         _tempReal *= _tempReal;
         varTotal2 += _tempReal;
         meanValue1 = varTotal1 * _invPeriod;
         variance = varTotal2 * _invPeriod - meanValue1 * meanValue1;
         tempBuffer1[_outIdx] = maTotal / optInTimePeriod;
         maTotal -= inReal[_trailingIdx];
         _tempReal = inReal[_trailingIdx] - shift;
         varTotal1 -= _tempReal;
         _tempReal *= _tempReal;
         varTotal2 -= _tempReal;
         _trailingIdx += 1;
         _barsSinceReseed -= 1;
         if( variance < 0.000001 * (varTotal2 * _invPeriod) || _tempReal > 1000000.0 * varTotal2 || _barsSinceReseed <= 0 )
         {
            _barsSinceReseed = 32 * optInTimePeriod;
            _windowStart = _i - _lookbackTotal;
            _tempReal = 0.0;
            for( _j = _windowStart; _j <= _i; _j += 1 )
            {
               _tempReal += inReal[_j];
            }
            shift = _tempReal * _invPeriod;
            varTotal1 = 0.0;
            varTotal2 = 0.0;
            for( _j = _windowStart; _j <= _i; _j += 1 )
            {
               _tempReal = inReal[_j] - shift;
               varTotal1 += _tempReal;
               _tempReal *= _tempReal;
               varTotal2 += _tempReal;
            }
            meanValue1 = varTotal1 * _invPeriod;
            variance = varTotal2 * _invPeriod - meanValue1 * meanValue1;
            /* The floor from var.c, verbatim: it owns both the sign and the
             * dead-zone, so the square root below can be unconditional.
             */
            if( variance < 0.000000000001 * (varTotal2 * _invPeriod) )
            {
               variance = 0.0;
            }
            _tempReal = inReal[_windowStart] - shift;
            varTotal1 -= _tempReal;
            _tempReal *= _tempReal;
            varTotal2 -= _tempReal;
         }
         /* The TA_EPSILON test that used to stand here compared a SQUARED
          * quantity to a fixed 1e-14 and flattened all three bands onto each
          * other for any finely quoted series (#243). What replaces it skips
          * the root ONLY where the answer is already known, because the
          * reseed floor above has made it exactly 0 -- worth doing because
          * this root, unlike stddev.c's, sits in the fused loop with a
          * carried dependency and cannot vectorize, so running it on flat
          * input cost 1.59x.
          *
          * `!= 0.0` and not `> 0.0`: the two differ only on NaN, and `> 0.0`
          * sends it to the false arm, which would emit a zero-width band
          * where stddev.c, BBANDS' own non-SMA paths and BBANDS_Open all
          * return NaN. Reaching it needs a squared deviation to overflow
          * (|x| ~ 1.3e154, far outside TA_REAL_MAX), so nothing in the
          * declared domain can tell the two apart -- but there is no reason
          * to buy the disagreement, and `!= 0.0` is what this is for.
          */
         tempBuffer2[_outIdx] = (variance != 0.0) ? sqrt(variance) : 0.0;
         _outIdx += 1;
         _i += 1;
      } while( _i <= endIdx );
      *outNBElement= _outIdx;
      *outBegIdx= startIdx;
      /* Copy the MA calculation into the middle band ouput, unless
       * the calculation was done into it already!
       */
      if( tempBuffer1 != outRealMiddleBand )
      {
         memcpy(outRealMiddleBand,tempBuffer1,*outNBElement * sizeof(double));
      }
      /* Now do a tight loop to calculate the upper/lower band at the same time. */
      if( optInNbDevUp == optInNbDevDn )
      {
         for( i = 0; i < (int)*outNBElement; i += 1 )
         {
            tempReal = tempBuffer2[i] * optInNbDevUp;
            tempReal2 = outRealMiddleBand[i];
            outRealUpperBand[i] = tempReal2 + tempReal;
            outRealLowerBand[i] = tempReal2 - tempReal;
         }
      } else 
      {
         for( i = 0; i < (int)*outNBElement; i += 1 )
         {
            tempReal = tempBuffer2[i];
            tempReal2 = outRealMiddleBand[i];
            outRealUpperBand[i] = fma(tempReal, optInNbDevUp, tempReal2);
            outRealLowerBand[i] = tempReal2 - tempReal * optInNbDevDn;
         }
      }
      return TA_SUCCESS;
   }
   /* General path (every MA type other than SMA): the middle band is the moving
    * average and the deviation is the standard deviation of the input, combined
    * at the same bar. Two intermediate buffers are allocated so the input may
    * safely alias an output (it is only read here).
    */
   /* Nothing to produce: the range is shorter than the lookback. Return before
    * touching anything.
    *
    * Without this the moving average below runs first, and for the MA types whose
    * lookback is BELOW the deviation's - TA_MAType_DISABLED (MA lookback 0) and
    * TA_MAType_MAMA at optInTimePeriod >= 34 - it reads the whole range and
    * computes a middle band the empty standard deviation then discards.
    * Observably identical (the empty deviation already yields 0,0 here), but it
    * is the difference between "a range shorter than the lookback reads nothing"
    * being true of this function and being false: with a caller-supplied inReal
    * that stops short of endIdx, that discarded work is an out-of-bounds read.
    * The SMA fast path above needs no such guard - its own lookback IS the
    * deviation's, so its clamp already covers it. Pinned by the zero-length
    * no-I/O probe over every guarded core, at every MA type.
    */
   if( TA_BBANDS_Lookback(optInTimePeriod,optInNbDevUp,optInNbDevDn,optInMAType) > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   tempBuffer1 = malloc((endIdx - startIdx + 1) * sizeof(double));
   if( !tempBuffer1 )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_ALLOC_ERR;
   }
   tempBuffer2 = malloc((endIdx - startIdx + 1) * sizeof(double));
   if( !tempBuffer2 )
   {
      free(tempBuffer1);
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_ALLOC_ERR;
   }
   /* Calculate the middle band moving average. */
   retCode = TA_MA(startIdx,endIdx,inReal,optInTimePeriod,optInMAType,outBegIdx,outNBElement,tempBuffer1);
   if( retCode != TA_SUCCESS || (int)*outNBElement == 0 )
   {
      *outNBElement= 0;
      free(tempBuffer1);
      free(tempBuffer2);
      return retCode;
   }
   /* Remember where the moving average begins, to realign it below. */
   maBegIdx = (int)*outBegIdx;
   /* Calculate the Standard Deviation into tempBuffer2. */
   retCode = TA_STDDEV((int)*outBegIdx,endIdx,inReal,optInTimePeriod,1.0,outBegIdx,outNBElement,tempBuffer2);
   if( retCode != TA_SUCCESS )
   {
      *outNBElement= 0;
      free(tempBuffer1);
      free(tempBuffer2);
      return retCode;
   }
   /* When the standard deviation (lookback optInTimePeriod-1) clamps to a later
    * begIdx than the moving average did - as with TA_MAType_MAMA (constant
    * lookback 32) and optInTimePeriod >= 34 - the MA in tempBuffer1 still starts
    * at the earlier maBegIdx. Copy it forward from that shift into the middle
    * band so each band value pairs the moving average and standard deviation of
    * the same bar. The guarded subtraction keeps shiftIdx non-negative even when
    * the standard deviation produced no output (an empty range leaves *outBegIdx
    * at 0), which the unconditional copy below then handles as a zero-length move.
    */
   if( (int)*outBegIdx > maBegIdx )
   {
      shiftIdx = (int)*outBegIdx - maBegIdx;
   } else 
   {
      shiftIdx = 0;
   }
   memmove(outRealMiddleBand,&tempBuffer1[shiftIdx],*outNBElement * sizeof(double));
   /* Now do a tight loop to calculate the upper/lower band at the same time. */
   if( optInNbDevUp == optInNbDevDn )
   {
      for( i = 0; i < (int)*outNBElement; i += 1 )
      {
         tempReal = tempBuffer2[i] * optInNbDevUp;
         tempReal2 = outRealMiddleBand[i];
         outRealUpperBand[i] = tempReal2 + tempReal;
         outRealLowerBand[i] = tempReal2 - tempReal;
      }
   } else 
   {
      for( i = 0; i < (int)*outNBElement; i += 1 )
      {
         tempReal2 = outRealMiddleBand[i];
         outRealUpperBand[i] = fma(tempBuffer2[i], optInNbDevUp, tempReal2);
         outRealLowerBand[i] = tempReal2 - tempBuffer2[i] * optInNbDevDn;
      }
   }
   free(tempBuffer1);
   free(tempBuffer2);
   return TA_SUCCESS;
}

TA_FMA_MULTIVERSION
TA_RetCode TA_S_BBANDS( int    startIdx,
                        int    endIdx,
                        const float inReal[],
                        int optInTimePeriod,
                        double optInNbDevUp,
                        double optInNbDevDn,
                        TA_MAType optInMAType,
                        int          *outBegIdx,
                        int          *outNBElement,
                        double        outRealUpperBand[],
                        double        outRealMiddleBand[],
                        double        outRealLowerBand[] )
{
   TA_RetCode retCode;
   int i;
   int maBegIdx;
   int shiftIdx;
   double tempReal;
   double tempReal2;
   double *tempBuffer1;
   double *tempBuffer2;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 20;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( optInNbDevUp == TA_REAL_DEFAULT )
      optInNbDevUp = 2;
   else if( !(optInNbDevUp >= TA_REAL_MIN && optInNbDevUp <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( optInNbDevDn == TA_REAL_DEFAULT )
      optInNbDevDn = 2;
   else if( !(optInNbDevDn >= TA_REAL_MIN && optInNbDevDn <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( (int)optInMAType == TA_INTEGER_DEFAULT || optInMAType == TA_MAType_DEFAULT )
      optInMAType = 0;
   else if( (int)optInMAType < TA_MATYPE_MIN || (int)optInMAType > TA_MATYPE_MAX )
      return TA_BAD_PARAM;
   if( !inReal )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outRealUpperBand )
      return TA_BAD_PARAM;
   if( !outRealMiddleBand )
      return TA_BAD_PARAM;
   if( !outRealLowerBand )
      return TA_BAD_PARAM;
   if( outRealUpperBand == outRealMiddleBand || outRealUpperBand == outRealLowerBand || outRealMiddleBand == outRealLowerBand )
      return TA_BAD_PARAM;

   if( optInMAType == TA_MAType_SMA )
   {
      if( 0 )
      {
         tempBuffer1 = outRealMiddleBand;
         tempBuffer2 = outRealLowerBand;
      } else if( 0 )
      {
         tempBuffer1 = outRealMiddleBand;
         tempBuffer2 = outRealUpperBand;
      } else if( 0 )
      {
         tempBuffer1 = outRealLowerBand;
         tempBuffer2 = outRealUpperBand;
      } else 
      {
         tempBuffer1 = outRealMiddleBand;
         tempBuffer2 = outRealUpperBand;
      }
      if( 0 || 0 )
      {
         return TA_BAD_PARAM;
      }
      double maTotal;
      double shift;
      double varTotal1;
      double varTotal2;
      double meanValue1;
      double variance;
      double _invPeriod;
      double _tempReal;
      int _i;
      int _j;
      int _outIdx;
      int _trailingIdx;
      int _windowStart;
      int _lookbackTotal;
      int _barsSinceReseed;
      _lookbackTotal = optInTimePeriod - 1;
      if( startIdx < _lookbackTotal )
      {
         startIdx = _lookbackTotal;
      }
      if( startIdx > endIdx )
      {
         *outBegIdx= 0;
         *outNBElement= 0;
         return TA_SUCCESS;
      }
      _invPeriod = 1.0 / (double)optInTimePeriod;
      _trailingIdx = startIdx - _lookbackTotal;
      shift = (double)inReal[_trailingIdx];
      maTotal = 0.0;
      varTotal1 = 0.0;
      varTotal2 = 0.0;
      for( _j = _trailingIdx; _j < startIdx; _j += 1 )
      {
         maTotal += (double)inReal[_j];
         _tempReal = (double)inReal[_j] - shift;
         varTotal1 += _tempReal;
         _tempReal *= _tempReal;
         varTotal2 += _tempReal;
      }
      _i = startIdx;
      _outIdx = 0;
      _barsSinceReseed = 32 * optInTimePeriod;
      do
      {
         maTotal += (double)inReal[_i];
         _tempReal = (double)inReal[_i] - shift;
         varTotal1 += _tempReal;
         _tempReal *= _tempReal;
         varTotal2 += _tempReal;
         meanValue1 = varTotal1 * _invPeriod;
         variance = varTotal2 * _invPeriod - meanValue1 * meanValue1;
         tempBuffer1[_outIdx] = maTotal / optInTimePeriod;
         maTotal -= (double)inReal[_trailingIdx];
         _tempReal = (double)inReal[_trailingIdx] - shift;
         varTotal1 -= _tempReal;
         _tempReal *= _tempReal;
         varTotal2 -= _tempReal;
         _trailingIdx += 1;
         _barsSinceReseed -= 1;
         if( variance < 0.000001 * (varTotal2 * _invPeriod) || _tempReal > 1000000.0 * varTotal2 || _barsSinceReseed <= 0 )
         {
            _barsSinceReseed = 32 * optInTimePeriod;
            _windowStart = _i - _lookbackTotal;
            _tempReal = 0.0;
            for( _j = _windowStart; _j <= _i; _j += 1 )
            {
               _tempReal += (double)inReal[_j];
            }
            shift = _tempReal * _invPeriod;
            varTotal1 = 0.0;
            varTotal2 = 0.0;
            for( _j = _windowStart; _j <= _i; _j += 1 )
            {
               _tempReal = (double)inReal[_j] - shift;
               varTotal1 += _tempReal;
               _tempReal *= _tempReal;
               varTotal2 += _tempReal;
            }
            meanValue1 = varTotal1 * _invPeriod;
            variance = varTotal2 * _invPeriod - meanValue1 * meanValue1;
            if( variance < 0.000000000001 * (varTotal2 * _invPeriod) )
            {
               variance = 0.0;
            }
            _tempReal = (double)inReal[_windowStart] - shift;
            varTotal1 -= _tempReal;
            _tempReal *= _tempReal;
            varTotal2 -= _tempReal;
         }
         tempBuffer2[_outIdx] = (variance != 0.0) ? sqrt(variance) : 0.0;
         _outIdx += 1;
         _i += 1;
      } while( _i <= endIdx );
      *outNBElement= _outIdx;
      *outBegIdx= startIdx;
      if( tempBuffer1 != outRealMiddleBand )
      {
         memcpy(outRealMiddleBand,tempBuffer1,*outNBElement * sizeof(double));
      }
      if( optInNbDevUp == optInNbDevDn )
      {
         for( i = 0; i < (int)*outNBElement; i += 1 )
         {
            tempReal = tempBuffer2[i] * optInNbDevUp;
            tempReal2 = outRealMiddleBand[i];
            outRealUpperBand[i] = tempReal2 + tempReal;
            outRealLowerBand[i] = tempReal2 - tempReal;
         }
      } else 
      {
         for( i = 0; i < (int)*outNBElement; i += 1 )
         {
            tempReal = tempBuffer2[i];
            tempReal2 = outRealMiddleBand[i];
            outRealUpperBand[i] = fma(tempReal, optInNbDevUp, tempReal2);
            outRealLowerBand[i] = tempReal2 - tempReal * optInNbDevDn;
         }
      }
      return TA_SUCCESS;
   }
   if( TA_BBANDS_Lookback(optInTimePeriod,optInNbDevUp,optInNbDevDn,optInMAType) > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   tempBuffer1 = malloc((endIdx - startIdx + 1) * sizeof(double));
   if( !tempBuffer1 )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_ALLOC_ERR;
   }
   tempBuffer2 = malloc((endIdx - startIdx + 1) * sizeof(double));
   if( !tempBuffer2 )
   {
      free(tempBuffer1);
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_ALLOC_ERR;
   }
   retCode = TA_S_MA(startIdx,endIdx,inReal,optInTimePeriod,optInMAType,outBegIdx,outNBElement,tempBuffer1);
   if( retCode != TA_SUCCESS || (int)*outNBElement == 0 )
   {
      *outNBElement= 0;
      free(tempBuffer1);
      free(tempBuffer2);
      return retCode;
   }
   maBegIdx = (int)*outBegIdx;
   retCode = TA_S_STDDEV((int)*outBegIdx,endIdx,inReal,optInTimePeriod,1.0,outBegIdx,outNBElement,tempBuffer2);
   if( retCode != TA_SUCCESS )
   {
      *outNBElement= 0;
      free(tempBuffer1);
      free(tempBuffer2);
      return retCode;
   }
   if( (int)*outBegIdx > maBegIdx )
   {
      shiftIdx = (int)*outBegIdx - maBegIdx;
   } else 
   {
      shiftIdx = 0;
   }
   memmove(outRealMiddleBand,&tempBuffer1[shiftIdx],*outNBElement * sizeof(double));
   if( optInNbDevUp == optInNbDevDn )
   {
      for( i = 0; i < (int)*outNBElement; i += 1 )
      {
         tempReal = tempBuffer2[i] * optInNbDevUp;
         tempReal2 = outRealMiddleBand[i];
         outRealUpperBand[i] = tempReal2 + tempReal;
         outRealLowerBand[i] = tempReal2 - tempReal;
      }
   } else 
   {
      for( i = 0; i < (int)*outNBElement; i += 1 )
      {
         tempReal2 = outRealMiddleBand[i];
         outRealUpperBand[i] = fma(tempBuffer2[i], optInNbDevUp, tempReal2);
         outRealLowerBand[i] = tempReal2 - tempBuffer2[i] * optInNbDevDn;
      }
   }
   free(tempBuffer1);
   free(tempBuffer2);
   return TA_SUCCESS;
}

/**** Streaming API *****/

struct TA_BBANDS_Stream {
   /* The bars this handle has an output for (see TA_StreamOutRange).
    * Kept first, and in this order, in every stream struct. */
   int outRangeBegIdx;
   int outRangeCount;
   /* The value(s) at the last bar the stream counted (see TA_BBANDS_Value). */
   double cur_outRealUpperBand;
   double cur_outRealMiddleBand;
   double cur_outRealLowerBand;
   int optInTimePeriod;
   double optInNbDevUp;
   double optInNbDevDn;
   TA_MAType optInMAType;
   TA_MA_Stream *sub0;
   TA_STDDEV_Stream *sub1;
};

/* Private function, not in public API. */
static TA_RetCode TA_BBANDS_StepImpl( struct TA_BBANDS_Stream *sp, double inReal, double *outRealUpperBand, double *outRealMiddleBand, double *outRealLowerBand )
{
   double tempReal;
   double tempReal2;
   double cur_tempBuffer1 = 0.0;
   double cur_tempBuffer2 = 0.0;
   double cur_outRealUpperBand = 0.0;
   double cur_outRealLowerBand = 0.0;


   /* Pipeline the new bar through the sub-streams (batch tail order). */
   {
      TA_RetCode subRc = TA_MA_Update( sp->sub0, inReal, &cur_tempBuffer1 );
      if( subRc != TA_SUCCESS ) return subRc;
   }
   {
      TA_RetCode subRc = TA_STDDEV_Update( sp->sub1, inReal, &cur_tempBuffer2 );
      if( subRc != TA_SUCCESS ) return subRc;
   }
   /* Combine map (batch tail, per bar). */
   if( sp->optInNbDevUp == sp->optInNbDevDn )
   {
      tempReal = cur_tempBuffer2 * sp->optInNbDevUp;
      tempReal2 = cur_tempBuffer1;
      cur_outRealUpperBand = tempReal2 + tempReal;
      cur_outRealLowerBand = tempReal2 - tempReal;
   } else 
   {
      tempReal2 = cur_tempBuffer1;
      cur_outRealUpperBand = fma(cur_tempBuffer2, sp->optInNbDevUp, tempReal2);
      cur_outRealLowerBand = tempReal2 - cur_tempBuffer2 * sp->optInNbDevDn;
   }
   *outRealUpperBand = cur_outRealUpperBand;
   *outRealMiddleBand = cur_tempBuffer1;
   *outRealLowerBand = cur_outRealLowerBand;
   return TA_SUCCESS;
}

static TA_RetCode TA_BBANDS_OpenImpl( struct TA_BBANDS_Stream **stream, const double inReal[], int startIdx, int historyLen, int optInTimePeriod, double optInNbDevUp, double optInNbDevDn, TA_MAType optInMAType, int *outBegIdx, int *outNBElement, double outRealUpperBand[], double outRealMiddleBand[], double outRealLowerBand[], int outStride )
{
   struct TA_BBANDS_Stream *sp;
   int endIdx;
   int dummyBegIdx;
   int dummyNBElement;
   TA_RetCode subRc;
   double subOpenDummy;
   double *sc_outRealUpperBand;
   double *sc_outRealMiddleBand;
   double *sc_outRealLowerBand;
   TA_MA_Stream *sub0;
   TA_STDDEV_Stream *sub1;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inReal || !outRealUpperBand || !outRealMiddleBand || !outRealLowerBand ) return TA_BAD_PARAM;
   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 20;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( optInNbDevUp == TA_REAL_DEFAULT )
      optInNbDevUp = 2;
   else if( !(optInNbDevUp >= TA_REAL_MIN && optInNbDevUp <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( optInNbDevDn == TA_REAL_DEFAULT )
      optInNbDevDn = 2;
   else if( !(optInNbDevDn >= TA_REAL_MIN && optInNbDevDn <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( (int)optInMAType == TA_INTEGER_DEFAULT || optInMAType == TA_MAType_DEFAULT )
      optInMAType = 0;
   else if( (int)optInMAType < TA_MATYPE_MIN || (int)optInMAType > TA_MATYPE_MAX )
      return TA_BAD_PARAM;
   if( startIdx > historyLen - 1 )
   {
      *outBegIdx = 0;
      *outNBElement = 0;
      return TA_INSUFFICIENT_HISTORY;
   }

   endIdx = historyLen - 1;
   dummyBegIdx = 0;
   dummyNBElement = 0;
   subRc = TA_SUCCESS;
   subOpenDummy = 0.0;
   sub0 = NULL;
   sub1 = NULL;
   (void)startIdx; (void)dummyBegIdx; (void)dummyNBElement; (void)subRc; (void)subOpenDummy;
   if( outStride ) sc_outRealUpperBand = outRealUpperBand;
   else
   {
      sc_outRealUpperBand = (double *)TA_Malloc( sizeof(double) * (size_t)historyLen );
      if( !sc_outRealUpperBand ) { return TA_ALLOC_ERR; }
   }
   if( outStride ) sc_outRealMiddleBand = outRealMiddleBand;
   else
   {
      sc_outRealMiddleBand = (double *)TA_Malloc( sizeof(double) * (size_t)historyLen );
      if( !sc_outRealMiddleBand ) { TA_Free( sc_outRealUpperBand ); return TA_ALLOC_ERR; }
   }
   if( outStride ) sc_outRealLowerBand = outRealLowerBand;
   else
   {
      sc_outRealLowerBand = (double *)TA_Malloc( sizeof(double) * (size_t)historyLen );
      if( !sc_outRealLowerBand ) { TA_Free( sc_outRealUpperBand ); TA_Free( sc_outRealMiddleBand ); return TA_ALLOC_ERR; }
   }

   {
      TA_RetCode retCode;
      int i;
      int maBegIdx;
      int shiftIdx;
      double tempReal;
      double tempReal2;
      double *tempBuffer1;
      double *tempBuffer2;
      /* General path (every MA type other than SMA): the middle band is the moving
       * average and the deviation is the standard deviation of the input, combined
       * at the same bar. Two intermediate buffers are allocated so the input may
       * safely alias an output (it is only read here).
       */
      /* Nothing to produce: the range is shorter than the lookback. Return before
       * touching anything.
       *
       * Without this the moving average below runs first, and for the MA types whose
       * lookback is BELOW the deviation's - TA_MAType_DISABLED (MA lookback 0) and
       * TA_MAType_MAMA at optInTimePeriod >= 34 - it reads the whole range and
       * computes a middle band the empty standard deviation then discards.
       * Observably identical (the empty deviation already yields 0,0 here), but it
       * is the difference between "a range shorter than the lookback reads nothing"
       * being true of this function and being false: with a caller-supplied inReal
       * that stops short of endIdx, that discarded work is an out-of-bounds read.
       * The SMA fast path above needs no such guard - its own lookback IS the
       * deviation's, so its clamp already covers it. Pinned by the zero-length
       * no-I/O probe over every guarded core, at every MA type.
       */
      if( TA_BBANDS_Lookback(optInTimePeriod,optInNbDevUp,optInNbDevDn,optInMAType) > endIdx )
      {
         dummyBegIdx = 0;
         dummyNBElement = 0;
         TA_MA_Close( sub0 ); TA_STDDEV_Close( sub1 ); if( !outStride ) TA_Free( sc_outRealUpperBand ); if( !outStride ) TA_Free( sc_outRealMiddleBand ); if( !outStride ) TA_Free( sc_outRealLowerBand );
         return TA_INSUFFICIENT_HISTORY;
      }
      tempBuffer1 = malloc((endIdx - startIdx + 1) * sizeof(double));
      if( !tempBuffer1 )
      {
         TA_MA_Close( sub0 ); TA_STDDEV_Close( sub1 ); if( !outStride ) TA_Free( sc_outRealUpperBand ); if( !outStride ) TA_Free( sc_outRealMiddleBand ); if( !outStride ) TA_Free( sc_outRealLowerBand );
         return TA_ALLOC_ERR;
      }
      tempBuffer2 = malloc((endIdx - startIdx + 1) * sizeof(double));
      if( !tempBuffer2 )
      {
         free( tempBuffer1 ); TA_MA_Close( sub0 ); TA_STDDEV_Close( sub1 ); if( !outStride ) TA_Free( sc_outRealUpperBand ); if( !outStride ) TA_Free( sc_outRealMiddleBand ); if( !outStride ) TA_Free( sc_outRealLowerBand );
         return TA_ALLOC_ERR;
      }
      /* Calculate the middle band moving average. */
      /* Sub-stream 0: ma over `inReal`, warmed from bar 0 up to the
       * sub-call's own startIdx (the seeding point). */
      {
         subRc = TA_MA_OpenAndFillInternal( &sub0, inReal, (startIdx), (endIdx) + 1, optInTimePeriod, optInMAType, &dummyBegIdx, &dummyNBElement, tempBuffer1 );
         if( subRc != TA_SUCCESS )
         {
            free(tempBuffer1);
            free(tempBuffer2);
            TA_MA_Close( sub0 ); TA_STDDEV_Close( sub1 ); if( !outStride ) TA_Free( sc_outRealUpperBand ); if( !outStride ) TA_Free( sc_outRealMiddleBand ); if( !outStride ) TA_Free( sc_outRealLowerBand );
            return subRc;
         }
      }
      retCode = subRc;
      if( retCode != TA_SUCCESS || (int)dummyNBElement == 0 )
      {
         dummyNBElement = 0;
         free(tempBuffer1);
         free(tempBuffer2);
         TA_MA_Close( sub0 ); TA_STDDEV_Close( sub1 ); if( !outStride ) TA_Free( sc_outRealUpperBand ); if( !outStride ) TA_Free( sc_outRealMiddleBand ); if( !outStride ) TA_Free( sc_outRealLowerBand );
         return retCode;
      }
      /* Remember where the moving average begins, to realign it below. */
      maBegIdx = (int)dummyBegIdx;
      /* Calculate the Standard Deviation into tempBuffer2. */
      /* Sub-stream 1: stddev over `inReal`, warmed from bar 0 up to the
       * sub-call's own startIdx (the seeding point). */
      {
         subRc = TA_STDDEV_OpenAndFillInternal( &sub1, inReal, ((int)dummyBegIdx), (endIdx) + 1, optInTimePeriod, 1.0, &dummyBegIdx, &dummyNBElement, tempBuffer2 );
         if( subRc != TA_SUCCESS )
         {
            free(tempBuffer1);
            free(tempBuffer2);
            TA_MA_Close( sub0 ); TA_STDDEV_Close( sub1 ); if( !outStride ) TA_Free( sc_outRealUpperBand ); if( !outStride ) TA_Free( sc_outRealMiddleBand ); if( !outStride ) TA_Free( sc_outRealLowerBand );
            return subRc;
         }
      }
      retCode = subRc;
      if( retCode != TA_SUCCESS )
      {
         dummyNBElement = 0;
         free(tempBuffer1);
         free(tempBuffer2);
         TA_MA_Close( sub0 ); TA_STDDEV_Close( sub1 ); if( !outStride ) TA_Free( sc_outRealUpperBand ); if( !outStride ) TA_Free( sc_outRealMiddleBand ); if( !outStride ) TA_Free( sc_outRealLowerBand );
         return retCode;
      }
      /* When the standard deviation (lookback optInTimePeriod-1) clamps to a later
       * begIdx than the moving average did - as with TA_MAType_MAMA (constant
       * lookback 32) and optInTimePeriod >= 34 - the MA in tempBuffer1 still starts
       * at the earlier maBegIdx. Copy it forward from that shift into the middle
       * band so each band value pairs the moving average and standard deviation of
       * the same bar. The guarded subtraction keeps shiftIdx non-negative even when
       * the standard deviation produced no output (an empty range leaves *outBegIdx
       * at 0), which the unconditional copy below then handles as a zero-length move.
       */
      if( (int)dummyBegIdx > maBegIdx )
      {
         shiftIdx = (int)dummyBegIdx - maBegIdx;
      } else 
      {
         shiftIdx = 0;
      }
      memmove(sc_outRealMiddleBand,&tempBuffer1[shiftIdx],dummyNBElement * sizeof(double));
      /* Now do a tight loop to calculate the upper/lower band at the same time. */
      if( optInNbDevUp == optInNbDevDn )
      {
         for( i = 0; i < (int)dummyNBElement; i += 1 )
         {
            tempReal = tempBuffer2[i] * optInNbDevUp;
            tempReal2 = sc_outRealMiddleBand[i];
            sc_outRealUpperBand[i] = tempReal2 + tempReal;
            sc_outRealLowerBand[i] = tempReal2 - tempReal;
         }
      } else 
      {
         for( i = 0; i < (int)dummyNBElement; i += 1 )
         {
            tempReal2 = sc_outRealMiddleBand[i];
            sc_outRealUpperBand[i] = fma(tempBuffer2[i], optInNbDevUp, tempReal2);
            sc_outRealLowerBand[i] = tempReal2 - tempBuffer2[i] * optInNbDevDn;
         }
      }
      free(tempBuffer1);
      free(tempBuffer2);

      /* Capture the live producer state + sub handles. */
      if( dummyNBElement < 1 ) { TA_MA_Close( sub0 ); TA_STDDEV_Close( sub1 ); if( !outStride ) TA_Free( sc_outRealUpperBand ); if( !outStride ) TA_Free( sc_outRealMiddleBand ); if( !outStride ) TA_Free( sc_outRealLowerBand ); return TA_INSUFFICIENT_HISTORY; }
      sp = (struct TA_BBANDS_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) { TA_MA_Close( sub0 ); TA_STDDEV_Close( sub1 ); if( !outStride ) TA_Free( sc_outRealUpperBand ); if( !outStride ) TA_Free( sc_outRealMiddleBand ); if( !outStride ) TA_Free( sc_outRealLowerBand ); return TA_ALLOC_ERR; }
      memset( sp, 0, sizeof(*sp) );
      sp->optInTimePeriod = optInTimePeriod;
      sp->optInNbDevUp = optInNbDevUp;
      sp->optInNbDevDn = optInNbDevDn;
      sp->optInMAType = optInMAType;
      sp->sub0 = sub0;
      sp->sub1 = sub1;
      *outBegIdx = dummyBegIdx;
      *outNBElement = dummyNBElement;
      if( !outStride ) outRealUpperBand[0] = sc_outRealUpperBand[dummyNBElement - 1];
      if( !outStride ) outRealMiddleBand[0] = sc_outRealMiddleBand[dummyNBElement - 1];
      if( !outStride ) outRealLowerBand[0] = sc_outRealLowerBand[dummyNBElement - 1];
      if( !outStride ) TA_Free( sc_outRealUpperBand );
      if( !outStride ) TA_Free( sc_outRealMiddleBand );
      if( !outStride ) TA_Free( sc_outRealLowerBand );
      sp->outRangeBegIdx = *outBegIdx;
      sp->outRangeCount = *outNBElement;
      sp->cur_outRealUpperBand = outRealUpperBand[(*outNBElement - 1) * outStride];
      sp->cur_outRealMiddleBand = outRealMiddleBand[(*outNBElement - 1) * outStride];
      sp->cur_outRealLowerBand = outRealLowerBand[(*outNBElement - 1) * outStride];
      *stream = sp;
      return TA_SUCCESS;
   }
}

/* Private function, not in public API. */
TA_RetCode TA_BBANDS_OpenInternal( struct TA_BBANDS_Stream **stream, const double inReal[], int startIdx, int historyLen, int optInTimePeriod, double optInNbDevUp, double optInNbDevDn, TA_MAType optInMAType, double *outRealUpperBand, double *outRealMiddleBand, double *outRealLowerBand )
{
   TA_RetCode retCode;
   int dummyBegIdx = 0;
   int dummyNBElement = 0;
   double sink_outRealUpperBand = 0.0;
   double sink_outRealMiddleBand = 0.0;
   double sink_outRealLowerBand = 0.0;
   retCode = TA_BBANDS_OpenImpl( stream, inReal, startIdx, historyLen, optInTimePeriod, optInNbDevUp, optInNbDevDn, optInMAType, &dummyBegIdx, &dummyNBElement, &sink_outRealUpperBand, &sink_outRealMiddleBand, &sink_outRealLowerBand, 0 );
   if( retCode == TA_SUCCESS )
   {
      *outRealUpperBand = sink_outRealUpperBand;
      *outRealMiddleBand = sink_outRealMiddleBand;
      *outRealLowerBand = sink_outRealLowerBand;
   }
   return retCode;
}

TA_LIB_API TA_RetCode TA_BBANDS_Open( TA_BBANDS_Stream **stream, const double inReal[], int historyLen, int optInTimePeriod, double optInNbDevUp, double optInNbDevDn, TA_MAType optInMAType, double *outRealUpperBand, double *outRealMiddleBand, double *outRealLowerBand )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inReal || !outRealUpperBand || !outRealMiddleBand || !outRealLowerBand ) return TA_BAD_PARAM;
   return TA_BBANDS_OpenInternal( stream, inReal, 0, historyLen, optInTimePeriod, optInNbDevUp, optInNbDevDn, optInMAType, outRealUpperBand, outRealMiddleBand, outRealLowerBand );
}

TA_LIB_API TA_RetCode TA_BBANDS_OpenAndFill( TA_BBANDS_Stream **stream, const double inReal[], int historyLen, int optInTimePeriod, double optInNbDevUp, double optInNbDevDn, TA_MAType optInMAType, int *outBegIdx, int *outNBElement, double outRealUpperBand[], double outRealMiddleBand[], double outRealLowerBand[] )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inReal || !outBegIdx || !outNBElement || !outRealUpperBand || !outRealMiddleBand || !outRealLowerBand ) return TA_BAD_PARAM;
   if( (const void *)outRealUpperBand == (const void *)inReal || (const void *)outRealMiddleBand == (const void *)inReal || (const void *)outRealLowerBand == (const void *)inReal || (const void *)outRealUpperBand == (const void *)outRealMiddleBand || (const void *)outRealUpperBand == (const void *)outRealLowerBand || (const void *)outRealMiddleBand == (const void *)outRealLowerBand ) return TA_BAD_PARAM;
   return TA_BBANDS_OpenAndFillInternal( stream, inReal, 0, historyLen, optInTimePeriod, optInNbDevUp, optInNbDevDn, optInMAType, outBegIdx, outNBElement, outRealUpperBand, outRealMiddleBand, outRealLowerBand );
}

/* Private function, not in public API. */
TA_RetCode TA_BBANDS_OpenAndFillInternal( struct TA_BBANDS_Stream **stream, const double inReal[], int startIdx, int historyLen, int optInTimePeriod, double optInNbDevUp, double optInNbDevDn, TA_MAType optInMAType, int *outBegIdx, int *outNBElement, double outRealUpperBand[], double outRealMiddleBand[], double outRealLowerBand[] )
{
   return TA_BBANDS_OpenImpl( stream, inReal, startIdx, historyLen, optInTimePeriod, optInNbDevUp, optInNbDevDn, optInMAType, outBegIdx, outNBElement, outRealUpperBand, outRealMiddleBand, outRealLowerBand, 1 );
}

TA_LIB_API TA_RetCode TA_BBANDS_Update( TA_BBANDS_Stream *stream, double inReal, double *outRealUpperBand, double *outRealMiddleBand, double *outRealLowerBand )
{
   TA_RetCode retCode;

   if( !stream || !outRealUpperBand || !outRealMiddleBand || !outRealLowerBand ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inReal ) )
   {
      if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
      return TA_BAD_PARAM;
   }
   retCode = TA_BBANDS_StepImpl( stream, inReal, outRealUpperBand, outRealMiddleBand, outRealLowerBand );
   if( retCode != TA_SUCCESS ) return retCode;
   stream->cur_outRealUpperBand = *outRealUpperBand;
   stream->cur_outRealMiddleBand = *outRealMiddleBand;
   stream->cur_outRealLowerBand = *outRealLowerBand;
   if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_BBANDS_Peek( const TA_BBANDS_Stream *stream, double inReal, double *outRealUpperBand, double *outRealMiddleBand, double *outRealLowerBand )
{
   const struct TA_BBANDS_Stream *sp = stream;
   double tempReal;
   double tempReal2;
   double cur_tempBuffer1 = 0.0;
   double cur_tempBuffer2 = 0.0;
   double cur_outRealUpperBand = 0.0;
   double cur_outRealLowerBand = 0.0;

   if( !stream || !outRealUpperBand || !outRealMiddleBand || !outRealLowerBand ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inReal ) ) return TA_BAD_PARAM;

   /* Pipeline the new bar through the sub-streams (batch tail order). */
   {
      TA_RetCode subRc = TA_MA_Peek( (const TA_MA_Stream *)sp->sub0, inReal, &cur_tempBuffer1 );
      if( subRc != TA_SUCCESS ) return subRc;
   }
   {
      TA_RetCode subRc = TA_STDDEV_Peek( (const TA_STDDEV_Stream *)sp->sub1, inReal, &cur_tempBuffer2 );
      if( subRc != TA_SUCCESS ) return subRc;
   }
   /* Combine map (batch tail, per bar). */
   if( sp->optInNbDevUp == sp->optInNbDevDn )
   {
      tempReal = cur_tempBuffer2 * sp->optInNbDevUp;
      tempReal2 = cur_tempBuffer1;
      cur_outRealUpperBand = tempReal2 + tempReal;
      cur_outRealLowerBand = tempReal2 - tempReal;
   } else 
   {
      tempReal2 = cur_tempBuffer1;
      cur_outRealUpperBand = fma(cur_tempBuffer2, sp->optInNbDevUp, tempReal2);
      cur_outRealLowerBand = tempReal2 - cur_tempBuffer2 * sp->optInNbDevDn;
   }
   *outRealUpperBand = cur_outRealUpperBand;
   *outRealMiddleBand = cur_tempBuffer1;
   *outRealLowerBand = cur_outRealLowerBand;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_BBANDS_UpdateAndFill( TA_BBANDS_Stream *stream, const double inReal[], int barCount, double outRealUpperBand[], double outRealMiddleBand[], double outRealLowerBand[] )
{
   int i;
   TA_RetCode retCode;

   if( !stream || !inReal || !outRealUpperBand || !outRealMiddleBand || !outRealLowerBand ) return TA_BAD_PARAM;
   if( barCount < 0 ) return TA_BAD_PARAM;
   if( (const void *)outRealUpperBand == (const void *)inReal || (const void *)outRealMiddleBand == (const void *)inReal || (const void *)outRealLowerBand == (const void *)inReal || (const void *)outRealUpperBand == (const void *)outRealMiddleBand || (const void *)outRealUpperBand == (const void *)outRealLowerBand || (const void *)outRealMiddleBand == (const void *)outRealLowerBand ) return TA_BAD_PARAM;
   for( i = 0; i < barCount; i++ )
   {
      if( !TA_IS_FINITE( inReal[i] ) )
      {
         if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
         return TA_BAD_PARAM;
      }
      retCode = TA_BBANDS_StepImpl( stream, inReal[i], &outRealUpperBand[i], &outRealMiddleBand[i], &outRealLowerBand[i] );
      if( retCode != TA_SUCCESS ) return retCode;
      stream->cur_outRealUpperBand = outRealUpperBand[i];
      stream->cur_outRealMiddleBand = outRealMiddleBand[i];
      stream->cur_outRealLowerBand = outRealLowerBand[i];
      if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   }
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_BBANDS_Close( TA_BBANDS_Stream *stream )
{
   if( !stream ) return TA_SUCCESS;
   TA_MA_Close( stream->sub0 );
   TA_STDDEV_Close( stream->sub1 );
   TA_Free( stream );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_BBANDS_Value( const TA_BBANDS_Stream *stream, double *outRealUpperBand, double *outRealMiddleBand, double *outRealLowerBand )
{
   if( !stream || !outRealUpperBand || !outRealMiddleBand || !outRealLowerBand ) return TA_BAD_PARAM;
   *outRealUpperBand = stream->cur_outRealUpperBand;
   *outRealMiddleBand = stream->cur_outRealMiddleBand;
   *outRealLowerBand = stream->cur_outRealLowerBand;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_BBANDS_Clone( const TA_BBANDS_Stream *stream, TA_BBANDS_Stream **clone )
{
   struct TA_BBANDS_Stream *sp;

   if( !clone ) return TA_BAD_PARAM;
   *clone = NULL;
   if( !stream ) return TA_BAD_PARAM;
   sp = (struct TA_BBANDS_Stream *)TA_Malloc( sizeof(*sp) );
   if( !sp ) return TA_ALLOC_ERR;
   *sp = *stream;
   sp->sub0 = NULL;
   sp->sub1 = NULL;
   if( stream->sub0 )
   { TA_RetCode subRc = TA_MA_Clone( stream->sub0, &sp->sub0 );
     if( subRc != TA_SUCCESS ) { TA_BBANDS_Close( sp ); return subRc; } }
   if( stream->sub1 )
   { TA_RetCode subRc = TA_STDDEV_Clone( stream->sub1, &sp->sub1 );
     if( subRc != TA_SUCCESS ) { TA_BBANDS_Close( sp ); return subRc; } }
   *clone = sp;
   return TA_SUCCESS;
}

