/* TA-LIB Copyright (c) 1999-2026, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_stream_private.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  MF       Mario Fortier
 *  CC       Claude Code (AI assistant)
 *
 * Change history:
 *
 *  MMDDYY BY     Description
 *  -------------------------------------------------------------------
 *  092226 MF,CC  Initial version (#431).
 */

TA_LIB_API int TA_CRSI_Lookback( int optInTimePeriod, int optInStreakPeriod, int optInRankPeriod )
{
   int retValue;
   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 3;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return -1;
   if( (int)optInStreakPeriod == TA_INTEGER_DEFAULT )
      optInStreakPeriod = 2;
   else if( (int)optInStreakPeriod < 2 || (int)optInStreakPeriod > 100000 )
      return -1;
   if( (int)optInRankPeriod == TA_INTEGER_DEFAULT )
      optInRankPeriod = 100;
   else if( (int)optInRankPeriod < 2 || (int)optInRankPeriod > 10000 )
      return -1;
   retValue = TA_RSI_Lookback(optInTimePeriod);
   retValue = max(retValue,TA_RSI_Lookback(optInStreakPeriod) + 1);
   retValue = max(retValue,TA_PERCENTRANK_Lookback(optInRankPeriod) + TA_ROCP_Lookback(1));
   return retValue;
}

TA_LIB_API TA_RetCode TA_CRSI( int    startIdx,
                               int    endIdx,
                               const double inReal[],
                               int optInTimePeriod,
                               int optInStreakPeriod,
                               int optInRankPeriod,
                               int          *outBegIdx,
                               int          *outNBElement,
                               double        outReal[] )
{
   double *tempRSI;
   double *tempStreak;
   double *tempStreakRSI;
   TA_RetCode retCode;
   int lookbackTotal;
   int anchorIdx;
   int today;
   int outIdx;
   int i;
   int offsetRSI;
   int offsetStreak;
   int tempBegIdx;
   int rsiNb;
   int streakNb;
   int rocNb;
   double prevClose;
   double close;
   double streak;

   if( (startIdx < 0) || (startIdx > TA_INDEX_MAX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_INDEX_MAX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 3;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInStreakPeriod == TA_INTEGER_DEFAULT )
      optInStreakPeriod = 2;
   else if( (int)optInStreakPeriod < 2 || (int)optInStreakPeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInRankPeriod == TA_INTEGER_DEFAULT )
      optInRankPeriod = 100;
   else if( (int)optInRankPeriod < 2 || (int)optInRankPeriod > 10000 )
      return TA_BAD_PARAM;
   if( !inReal )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   *outBegIdx= 0;
   *outNBElement= 0;
   lookbackTotal = TA_CRSI_Lookback(optInTimePeriod,optInStreakPeriod,optInRankPeriod);
   if( lookbackTotal > endIdx )
   {
      return TA_SUCCESS;
   }
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   /* Both RSI legs start on the bar lookbackTotal before startIdx (the streak,
    * a difference, one bar later), so the leg with the shorter lookback warms
    * up over the spare bars instead of starting cold at its own lookback.
    */
   anchorIdx = startIdx - lookbackTotal;
   tempStreak = malloc((endIdx - anchorIdx) * sizeof(double));
   if( !tempStreak )
   {
      return TA_ALLOC_ERR;
   }
   tempRSI = malloc((endIdx - anchorIdx - TA_RSI_Lookback(optInTimePeriod) + 1) * sizeof(double));
   if( !tempRSI )
   {
      free(tempStreak);
      return TA_ALLOC_ERR;
   }
   tempStreakRSI = malloc((endIdx - anchorIdx - TA_RSI_Lookback(optInStreakPeriod)) * sizeof(double));
   if( !tempStreakRSI )
   {
      free(tempStreak);
      free(tempRSI);
      return TA_ALLOC_ERR;
   }
   streak = 0.0;
   prevClose = inReal[anchorIdx];
   outIdx = 0;
   today = anchorIdx + 1;
   while( today <= endIdx )
   {
      close = inReal[today];
      if( close > prevClose )
      {
         streak = (streak > 0.0) ? streak + 1.0 : 1.0;
      } else if( close < prevClose )
      {
         streak = (streak < 0.0) ? streak - 1.0 : 0 - 1.0;
      } else 
      {
         streak = 0.0;
      }
      tempStreak[outIdx++] = streak;
      prevClose = close;
      today += 1;
   }
   retCode = TA_RSI(0,outIdx - 1,tempStreak,optInStreakPeriod,&tempBegIdx,&streakNb,tempStreakRSI);
   if( retCode != TA_SUCCESS )
   {
      free(tempStreak);
      free(tempRSI);
      free(tempStreakRSI);
      return retCode;
   }
   retCode = TA_RSI(anchorIdx + TA_RSI_Lookback(optInTimePeriod),endIdx,inReal,optInTimePeriod,&tempBegIdx,&rsiNb,tempRSI);
   if( retCode != TA_SUCCESS )
   {
      free(tempStreak);
      free(tempRSI);
      free(tempStreakRSI);
      return retCode;
   }
   /* The streak is consumed: its buffer holds the returns. */
   retCode = TA_ROCP(startIdx - optInRankPeriod,endIdx,inReal,1,&tempBegIdx,&rocNb,tempStreak);
   if( retCode != TA_SUCCESS )
   {
      free(tempStreak);
      free(tempRSI);
      free(tempStreakRSI);
      return retCode;
   }
   retCode = TA_PERCENTRANK(0,rocNb - 1,tempStreak,optInRankPeriod,outBegIdx,outNBElement,outReal);
   if( retCode != TA_SUCCESS )
   {
      free(tempStreak);
      free(tempRSI);
      free(tempStreakRSI);
      *outBegIdx= 0;
      *outNBElement= 0;
      return retCode;
   }
   offsetRSI = rsiNb - *outNBElement;
   offsetStreak = streakNb - *outNBElement;
   for( i = 0; i < (int)*outNBElement; i += 1 )
   {
      outReal[i] = (tempRSI[i + offsetRSI] + tempStreakRSI[i + offsetStreak] + outReal[i]) / 3.0;
   }
   free(tempStreak);
   free(tempRSI);
   free(tempStreakRSI);
   *outBegIdx= startIdx;
   return TA_SUCCESS;
}

TA_RetCode TA_S_CRSI( int    startIdx,
                      int    endIdx,
                      const float inReal[],
                      int optInTimePeriod,
                      int optInStreakPeriod,
                      int optInRankPeriod,
                      int          *outBegIdx,
                      int          *outNBElement,
                      double        outReal[] )
{
   double *tempRSI;
   double *tempStreak;
   double *tempStreakRSI;
   TA_RetCode retCode;
   int lookbackTotal;
   int anchorIdx;
   int today;
   int outIdx;
   int i;
   int offsetRSI;
   int offsetStreak;
   int tempBegIdx;
   int rsiNb;
   int streakNb;
   int rocNb;
   double prevClose;
   double close;
   double streak;

   if( (startIdx < 0) || (startIdx > TA_INDEX_MAX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_INDEX_MAX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 3;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInStreakPeriod == TA_INTEGER_DEFAULT )
      optInStreakPeriod = 2;
   else if( (int)optInStreakPeriod < 2 || (int)optInStreakPeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInRankPeriod == TA_INTEGER_DEFAULT )
      optInRankPeriod = 100;
   else if( (int)optInRankPeriod < 2 || (int)optInRankPeriod > 10000 )
      return TA_BAD_PARAM;
   if( !inReal )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   *outBegIdx= 0;
   *outNBElement= 0;
   lookbackTotal = TA_CRSI_Lookback(optInTimePeriod,optInStreakPeriod,optInRankPeriod);
   if( lookbackTotal > endIdx )
   {
      return TA_SUCCESS;
   }
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   anchorIdx = startIdx - lookbackTotal;
   tempStreak = malloc((endIdx - anchorIdx) * sizeof(double));
   if( !tempStreak )
   {
      return TA_ALLOC_ERR;
   }
   tempRSI = malloc((endIdx - anchorIdx - TA_RSI_Lookback(optInTimePeriod) + 1) * sizeof(double));
   if( !tempRSI )
   {
      free(tempStreak);
      return TA_ALLOC_ERR;
   }
   tempStreakRSI = malloc((endIdx - anchorIdx - TA_RSI_Lookback(optInStreakPeriod)) * sizeof(double));
   if( !tempStreakRSI )
   {
      free(tempStreak);
      free(tempRSI);
      return TA_ALLOC_ERR;
   }
   streak = 0.0;
   prevClose = (double)inReal[anchorIdx];
   outIdx = 0;
   today = anchorIdx + 1;
   while( today <= endIdx )
   {
      close = (double)inReal[today];
      if( close > prevClose )
      {
         streak = (streak > 0.0) ? streak + 1.0 : 1.0;
      } else if( close < prevClose )
      {
         streak = (streak < 0.0) ? streak - 1.0 : 0 - 1.0;
      } else 
      {
         streak = 0.0;
      }
      tempStreak[outIdx++] = streak;
      prevClose = close;
      today += 1;
   }
   retCode = TA_RSI(0,outIdx - 1,tempStreak,optInStreakPeriod,&tempBegIdx,&streakNb,tempStreakRSI);
   if( retCode != TA_SUCCESS )
   {
      free(tempStreak);
      free(tempRSI);
      free(tempStreakRSI);
      return retCode;
   }
   retCode = TA_S_RSI(anchorIdx + TA_RSI_Lookback(optInTimePeriod),endIdx,inReal,optInTimePeriod,&tempBegIdx,&rsiNb,tempRSI);
   if( retCode != TA_SUCCESS )
   {
      free(tempStreak);
      free(tempRSI);
      free(tempStreakRSI);
      return retCode;
   }
   retCode = TA_S_ROCP(startIdx - optInRankPeriod,endIdx,inReal,1,&tempBegIdx,&rocNb,tempStreak);
   if( retCode != TA_SUCCESS )
   {
      free(tempStreak);
      free(tempRSI);
      free(tempStreakRSI);
      return retCode;
   }
   retCode = TA_PERCENTRANK(0,rocNb - 1,tempStreak,optInRankPeriod,outBegIdx,outNBElement,outReal);
   if( retCode != TA_SUCCESS )
   {
      free(tempStreak);
      free(tempRSI);
      free(tempStreakRSI);
      *outBegIdx= 0;
      *outNBElement= 0;
      return retCode;
   }
   offsetRSI = rsiNb - *outNBElement;
   offsetStreak = streakNb - *outNBElement;
   for( i = 0; i < (int)*outNBElement; i += 1 )
   {
      outReal[i] = (tempRSI[i + offsetRSI] + tempStreakRSI[i + offsetStreak] + outReal[i]) / 3.0;
   }
   free(tempStreak);
   free(tempRSI);
   free(tempStreakRSI);
   *outBegIdx= startIdx;
   return TA_SUCCESS;
}

/**** Streaming API *****/

struct TA_CRSI_Stream {
   /* The bars this handle has an output for (see TA_CRSI_OutRange). */
   int outRangeBegIdx;
   int outRangeCount;
   /* The value(s) at the last bar the stream counted (see TA_CRSI_Value). */
   double cur_outReal;
   int optInTimePeriod;
   int optInStreakPeriod;
   int optInRankPeriod;
   double prevClose;
   double streak;
   TA_RSI_Stream *sub0;
   TA_RSI_Stream *sub1;
   TA_ROCP_Stream *sub2;
   TA_PERCENTRANK_Stream *sub3;
};

/* Private function, not in public API. */
static TA_RetCode TA_CRSI_StepImpl( struct TA_CRSI_Stream *sp, double inReal, double *outReal )
{
   double cur_tempStreak = 0.0;
   double cur_tempStreakRSI = 0.0;
   double cur_tempRSI = 0.0;
   double cur_outReal = 0.0;
   double close;

   close = inReal;
   if( close > sp->prevClose )
   {
      sp->streak = (sp->streak > 0.0) ? sp->streak + 1.0 : 1.0;
   } else if( close < sp->prevClose )
   {
      sp->streak = (sp->streak < 0.0) ? sp->streak - 1.0 : 0 - 1.0;
   } else 
   {
      sp->streak = 0.0;
   }
   cur_tempStreak = sp->streak;
   sp->prevClose = close;

   /* Pipeline the new bar through the sub-streams (batch tail order). */
   {
      TA_RetCode subRc = TA_RSI_Update( sp->sub0, cur_tempStreak, &cur_tempStreakRSI );
      if( subRc != TA_SUCCESS ) return subRc;
   }
   {
      TA_RetCode subRc = TA_RSI_Update( sp->sub1, inReal, &cur_tempRSI );
      if( subRc != TA_SUCCESS ) return subRc;
   }
   {
      TA_RetCode subRc = TA_ROCP_Update( sp->sub2, inReal, &cur_tempStreak );
      if( subRc != TA_SUCCESS ) return subRc;
   }
   {
      TA_RetCode subRc = TA_PERCENTRANK_Update( sp->sub3, cur_tempStreak, &cur_outReal );
      if( subRc != TA_SUCCESS ) return subRc;
   }
   /* Combine map (batch tail, per bar). */
   cur_outReal = (cur_tempRSI + cur_tempStreakRSI + cur_outReal) / 3.0;
   *outReal = cur_outReal;
   return TA_SUCCESS;
}

static TA_RetCode TA_CRSI_OpenImpl( struct TA_CRSI_Stream **stream, const double inReal[], int startIdx, int historyLen, int optInTimePeriod, int optInStreakPeriod, int optInRankPeriod, int *outBegIdx, int *outNBElement, double outReal[], int outStride )
{
   struct TA_CRSI_Stream *sp;
   int endIdx;
   int dummyBegIdx;
   int dummyNBElement;
   TA_RetCode subRc;
   double *sc_outReal;
   TA_RSI_Stream *sub0;
   TA_RSI_Stream *sub1;
   TA_ROCP_Stream *sub2;
   TA_PERCENTRANK_Stream *sub3;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_INDEX_MAX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inReal || !outReal ) return TA_BAD_PARAM;
   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 3;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInStreakPeriod == TA_INTEGER_DEFAULT )
      optInStreakPeriod = 2;
   else if( (int)optInStreakPeriod < 2 || (int)optInStreakPeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInRankPeriod == TA_INTEGER_DEFAULT )
      optInRankPeriod = 100;
   else if( (int)optInRankPeriod < 2 || (int)optInRankPeriod > 10000 )
      return TA_BAD_PARAM;
   if( startIdx > historyLen - 1 )
   {
      *outBegIdx = 0;
      *outNBElement = 0;
      return TA_INSUFFICIENT_HISTORY;
   }

   endIdx = historyLen - 1;
   dummyBegIdx = 0;
   dummyNBElement = 0;
   subRc = TA_SUCCESS;
   sub0 = NULL;
   sub1 = NULL;
   sub2 = NULL;
   sub3 = NULL;
   if( outStride ) sc_outReal = outReal;
   else
   {
      sc_outReal = (double *)TA_Malloc( sizeof(double) * (size_t)historyLen );
      if( !sc_outReal ) { return TA_ALLOC_ERR; }
   }

   {
      double *tempRSI;
      double *tempStreak;
      double *tempStreakRSI;
      TA_RetCode retCode;
      int lookbackTotal;
      int anchorIdx;
      int today;
      int outIdx;
      int i;
      int offsetRSI;
      int offsetStreak;
      int tempBegIdx;
      int rsiNb;
      int streakNb;
      int rocNb;
      double prevClose;
      double close;
      double streak;
      dummyBegIdx = 0;
      dummyNBElement = 0;
      lookbackTotal = TA_CRSI_Lookback(optInTimePeriod,optInStreakPeriod,optInRankPeriod);
      if( lookbackTotal > endIdx )
      {
         *outBegIdx = 0; *outNBElement = 0;
         TA_RSI_Close( sub0 ); TA_RSI_Close( sub1 ); TA_ROCP_Close( sub2 ); TA_PERCENTRANK_Close( sub3 ); if( !outStride ) TA_Free( sc_outReal );
         return TA_INSUFFICIENT_HISTORY;
      }
      if( startIdx < lookbackTotal )
      {
         startIdx = lookbackTotal;
      }
      /* Both RSI legs start on the bar lookbackTotal before startIdx (the streak,
       * a difference, one bar later), so the leg with the shorter lookback warms
       * up over the spare bars instead of starting cold at its own lookback.
       */
      anchorIdx = startIdx - lookbackTotal;
      tempStreak = malloc((endIdx - anchorIdx) * sizeof(double));
      if( !tempStreak )
      {
         TA_RSI_Close( sub0 ); TA_RSI_Close( sub1 ); TA_ROCP_Close( sub2 ); TA_PERCENTRANK_Close( sub3 ); if( !outStride ) TA_Free( sc_outReal );
         return TA_ALLOC_ERR;
      }
      tempRSI = malloc((endIdx - anchorIdx - TA_RSI_Lookback(optInTimePeriod) + 1) * sizeof(double));
      if( !tempRSI )
      {
         free( tempStreak ); TA_RSI_Close( sub0 ); TA_RSI_Close( sub1 ); TA_ROCP_Close( sub2 ); TA_PERCENTRANK_Close( sub3 ); if( !outStride ) TA_Free( sc_outReal );
         return TA_ALLOC_ERR;
      }
      tempStreakRSI = malloc((endIdx - anchorIdx - TA_RSI_Lookback(optInStreakPeriod)) * sizeof(double));
      if( !tempStreakRSI )
      {
         free( tempStreak ); free( tempRSI ); TA_RSI_Close( sub0 ); TA_RSI_Close( sub1 ); TA_ROCP_Close( sub2 ); TA_PERCENTRANK_Close( sub3 ); if( !outStride ) TA_Free( sc_outReal );
         return TA_ALLOC_ERR;
      }
      streak = 0.0;
      prevClose = inReal[anchorIdx];
      outIdx = 0;
      today = anchorIdx + 1;
      while( today <= endIdx )
      {
         close = inReal[today];
         if( close > prevClose )
         {
            streak = (streak > 0.0) ? streak + 1.0 : 1.0;
         } else if( close < prevClose )
         {
            streak = (streak < 0.0) ? streak - 1.0 : 0 - 1.0;
         } else 
         {
            streak = 0.0;
         }
         tempStreak[outIdx++] = streak;
         prevClose = close;
         today += 1;
      }
      /* Sub-stream 0: rsi over `tempStreak`, warmed from bar 0 up to the
       * sub-call's own startIdx (the seeding point). */
      {
         subRc = TA_RSI_OpenAndFillInternal( &sub0, tempStreak, (0), (outIdx - 1) + 1, optInStreakPeriod, &tempBegIdx, &streakNb, tempStreakRSI );
         if( subRc != TA_SUCCESS )
         {
            free(tempStreak);
            free(tempRSI);
            free(tempStreakRSI);
            TA_RSI_Close( sub0 ); TA_RSI_Close( sub1 ); TA_ROCP_Close( sub2 ); TA_PERCENTRANK_Close( sub3 ); if( !outStride ) TA_Free( sc_outReal );
            return subRc;
         }
      }
      retCode = subRc;
      if( retCode != TA_SUCCESS )
      {
         free(tempStreak);
         free(tempRSI);
         free(tempStreakRSI);
         TA_RSI_Close( sub0 ); TA_RSI_Close( sub1 ); TA_ROCP_Close( sub2 ); TA_PERCENTRANK_Close( sub3 ); if( !outStride ) TA_Free( sc_outReal );
         return retCode;
      }
      /* Sub-stream 1: rsi over `inReal`, warmed from bar 0 up to the
       * sub-call's own startIdx (the seeding point). */
      {
         subRc = TA_RSI_OpenAndFillInternal( &sub1, inReal, (anchorIdx + TA_RSI_Lookback(optInTimePeriod)), (endIdx) + 1, optInTimePeriod, &tempBegIdx, &rsiNb, tempRSI );
         if( subRc != TA_SUCCESS )
         {
            free(tempStreak);
            free(tempRSI);
            free(tempStreakRSI);
            TA_RSI_Close( sub0 ); TA_RSI_Close( sub1 ); TA_ROCP_Close( sub2 ); TA_PERCENTRANK_Close( sub3 ); if( !outStride ) TA_Free( sc_outReal );
            return subRc;
         }
      }
      retCode = subRc;
      if( retCode != TA_SUCCESS )
      {
         free(tempStreak);
         free(tempRSI);
         free(tempStreakRSI);
         TA_RSI_Close( sub0 ); TA_RSI_Close( sub1 ); TA_ROCP_Close( sub2 ); TA_PERCENTRANK_Close( sub3 ); if( !outStride ) TA_Free( sc_outReal );
         return retCode;
      }
      /* The streak is consumed: its buffer holds the returns. */
      /* Sub-stream 2: rocp over `inReal`, warmed from bar 0 up to the
       * sub-call's own startIdx (the seeding point). */
      {
         subRc = TA_ROCP_OpenAndFillInternal( &sub2, inReal, (startIdx - optInRankPeriod), (endIdx) + 1, 1, &tempBegIdx, &rocNb, tempStreak );
         if( subRc != TA_SUCCESS )
         {
            free(tempStreak);
            free(tempRSI);
            free(tempStreakRSI);
            TA_RSI_Close( sub0 ); TA_RSI_Close( sub1 ); TA_ROCP_Close( sub2 ); TA_PERCENTRANK_Close( sub3 ); if( !outStride ) TA_Free( sc_outReal );
            return subRc;
         }
      }
      retCode = subRc;
      if( retCode != TA_SUCCESS )
      {
         free(tempStreak);
         free(tempRSI);
         free(tempStreakRSI);
         TA_RSI_Close( sub0 ); TA_RSI_Close( sub1 ); TA_ROCP_Close( sub2 ); TA_PERCENTRANK_Close( sub3 ); if( !outStride ) TA_Free( sc_outReal );
         return retCode;
      }
      /* Sub-stream 3: percentrank over `tempStreak`, warmed from bar 0 up to the
       * sub-call's own startIdx (the seeding point). */
      {
         subRc = TA_PERCENTRANK_OpenAndFillInternal( &sub3, tempStreak, (0), (rocNb - 1) + 1, optInRankPeriod, &dummyBegIdx, &dummyNBElement, sc_outReal );
         if( subRc != TA_SUCCESS )
         {
            free(tempStreak);
            free(tempRSI);
            free(tempStreakRSI);
            TA_RSI_Close( sub0 ); TA_RSI_Close( sub1 ); TA_ROCP_Close( sub2 ); TA_PERCENTRANK_Close( sub3 ); if( !outStride ) TA_Free( sc_outReal );
            return subRc;
         }
      }
      retCode = subRc;
      if( retCode != TA_SUCCESS )
      {
         free(tempStreak);
         free(tempRSI);
         free(tempStreakRSI);
         dummyBegIdx = 0;
         dummyNBElement = 0;
         TA_RSI_Close( sub0 ); TA_RSI_Close( sub1 ); TA_ROCP_Close( sub2 ); TA_PERCENTRANK_Close( sub3 ); if( !outStride ) TA_Free( sc_outReal );
         return retCode;
      }
      offsetRSI = rsiNb - dummyNBElement;
      offsetStreak = streakNb - dummyNBElement;
      for( i = 0; i < (int)dummyNBElement; i += 1 )
      {
         sc_outReal[i] = (tempRSI[i + offsetRSI] + tempStreakRSI[i + offsetStreak] + sc_outReal[i]) / 3.0;
      }
      free(tempStreak);
      free(tempRSI);
      free(tempStreakRSI);
      dummyBegIdx = startIdx;

      /* Capture the live producer state + sub handles. */
      if( dummyNBElement < 1 ) { *outBegIdx = 0; *outNBElement = 0; TA_RSI_Close( sub0 ); TA_RSI_Close( sub1 ); TA_ROCP_Close( sub2 ); TA_PERCENTRANK_Close( sub3 ); if( !outStride ) TA_Free( sc_outReal ); return TA_INSUFFICIENT_HISTORY; }
      sp = (struct TA_CRSI_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) { TA_RSI_Close( sub0 ); TA_RSI_Close( sub1 ); TA_ROCP_Close( sub2 ); TA_PERCENTRANK_Close( sub3 ); if( !outStride ) TA_Free( sc_outReal ); return TA_ALLOC_ERR; }
      memset( sp, 0, sizeof(*sp) );
      sp->optInTimePeriod = optInTimePeriod;
      sp->optInStreakPeriod = optInStreakPeriod;
      sp->optInRankPeriod = optInRankPeriod;
      sp->prevClose = prevClose;
      sp->streak = streak;
      sp->sub0 = sub0;
      sp->sub1 = sub1;
      sp->sub2 = sub2;
      sp->sub3 = sub3;
      *outBegIdx = dummyBegIdx;
      *outNBElement = dummyNBElement;
      if( !outStride ) outReal[0] = sc_outReal[dummyNBElement - 1];
      if( !outStride ) TA_Free( sc_outReal );
      sp->outRangeBegIdx = *outBegIdx;
      sp->outRangeCount = *outNBElement;
      sp->cur_outReal = outReal[(*outNBElement - 1) * outStride];
      *stream = sp;
      return TA_SUCCESS;
   }
}

/* Private function, not in public API. */
TA_RetCode TA_CRSI_OpenInternal( struct TA_CRSI_Stream **stream, const double inReal[], int startIdx, int historyLen, int optInTimePeriod, int optInStreakPeriod, int optInRankPeriod, double *outReal )
{
   TA_RetCode retCode;
   int dummyBegIdx = 0;
   int dummyNBElement = 0;
   double sink_outReal = 0.0;
   retCode = TA_CRSI_OpenImpl( stream, inReal, startIdx, historyLen, optInTimePeriod, optInStreakPeriod, optInRankPeriod, &dummyBegIdx, &dummyNBElement, &sink_outReal, 0 );
   if( retCode == TA_SUCCESS )
   {
      *outReal = sink_outReal;
   }
   return retCode;
}

TA_LIB_API TA_RetCode TA_CRSI_Open( TA_CRSI_Stream **stream, const double inReal[], int historyLen, int optInTimePeriod, int optInStreakPeriod, int optInRankPeriod, double *outReal )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_INDEX_MAX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inReal || !outReal ) return TA_BAD_PARAM;
   return TA_CRSI_OpenInternal( stream, inReal, 0, historyLen, optInTimePeriod, optInStreakPeriod, optInRankPeriod, outReal );
}

TA_LIB_API TA_RetCode TA_CRSI_OpenAndFill( TA_CRSI_Stream **stream, const double inReal[], int historyLen, int optInTimePeriod, int optInStreakPeriod, int optInRankPeriod, int *outBegIdx, int *outNBElement, double outReal[] )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_INDEX_MAX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inReal || !outBegIdx || !outNBElement || !outReal ) return TA_BAD_PARAM;
   if( (const void *)outReal == (const void *)inReal ) return TA_BAD_PARAM;
   return TA_CRSI_OpenAndFillInternal( stream, inReal, 0, historyLen, optInTimePeriod, optInStreakPeriod, optInRankPeriod, outBegIdx, outNBElement, outReal );
}

/* Private function, not in public API. */
TA_RetCode TA_CRSI_OpenAndFillInternal( struct TA_CRSI_Stream **stream, const double inReal[], int startIdx, int historyLen, int optInTimePeriod, int optInStreakPeriod, int optInRankPeriod, int *outBegIdx, int *outNBElement, double outReal[] )
{
   return TA_CRSI_OpenImpl( stream, inReal, startIdx, historyLen, optInTimePeriod, optInStreakPeriod, optInRankPeriod, outBegIdx, outNBElement, outReal, 1 );
}

TA_LIB_API TA_RetCode TA_CRSI_Update( TA_CRSI_Stream *stream, double inReal, double *outReal )
{
   TA_RetCode retCode;

   if( !stream ) return TA_BAD_PARAM;
   if( stream->outRangeBegIdx + stream->outRangeCount > TA_INDEX_MAX )
      return TA_OUT_OF_RANGE_END_INDEX;
   if( !outReal ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inReal ) ) return TA_BAD_PARAM;
   retCode = TA_CRSI_StepImpl( stream, inReal, outReal );
   if( retCode != TA_SUCCESS ) return retCode;
   stream->cur_outReal = *outReal;
   stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_CRSI_Peek( const TA_CRSI_Stream *stream, double inReal, double *outReal )
{
   const struct TA_CRSI_Stream *sp = stream;
   double cur_tempStreak = 0.0;
   double cur_tempStreakRSI = 0.0;
   double cur_tempRSI = 0.0;
   double cur_outReal = 0.0;
   double close;
   double streak;

   if( !stream || !outReal ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inReal ) ) return TA_BAD_PARAM;
   streak = sp->streak;
   close = inReal;
   if( close > sp->prevClose )
   {
      streak = (streak > 0.0) ? streak + 1.0 : 1.0;
   } else if( close < sp->prevClose )
   {
      streak = (streak < 0.0) ? streak - 1.0 : 0 - 1.0;
   } else 
   {
      streak = 0.0;
   }
   cur_tempStreak = streak;

   /* Pipeline the new bar through the sub-streams (batch tail order). */
   {
      TA_RetCode subRc = TA_RSI_Peek( (const TA_RSI_Stream *)sp->sub0, cur_tempStreak, &cur_tempStreakRSI );
      if( subRc != TA_SUCCESS ) return subRc;
   }
   {
      TA_RetCode subRc = TA_RSI_Peek( (const TA_RSI_Stream *)sp->sub1, inReal, &cur_tempRSI );
      if( subRc != TA_SUCCESS ) return subRc;
   }
   {
      TA_RetCode subRc = TA_ROCP_Peek( (const TA_ROCP_Stream *)sp->sub2, inReal, &cur_tempStreak );
      if( subRc != TA_SUCCESS ) return subRc;
   }
   {
      TA_RetCode subRc = TA_PERCENTRANK_Peek( (const TA_PERCENTRANK_Stream *)sp->sub3, cur_tempStreak, &cur_outReal );
      if( subRc != TA_SUCCESS ) return subRc;
   }
   /* Combine map (batch tail, per bar). */
   cur_outReal = (cur_tempRSI + cur_tempStreakRSI + cur_outReal) / 3.0;
   *outReal = cur_outReal;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_CRSI_Close( TA_CRSI_Stream *stream )
{
   if( !stream ) return TA_SUCCESS;
   TA_RSI_Close( stream->sub0 );
   TA_RSI_Close( stream->sub1 );
   TA_ROCP_Close( stream->sub2 );
   TA_PERCENTRANK_Close( stream->sub3 );
   TA_Free( stream );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_CRSI_Value( const TA_CRSI_Stream *stream, double *outReal )
{
   if( !stream || !outReal ) return TA_BAD_PARAM;
   *outReal = stream->cur_outReal;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_CRSI_OutRange( const TA_CRSI_Stream *stream, int *outBegIdx, int *outNBElement )
{
   if( !stream || !outBegIdx || !outNBElement ) return TA_BAD_PARAM;
   *outBegIdx = stream->outRangeBegIdx;
   *outNBElement = stream->outRangeCount;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_CRSI_Advance( TA_CRSI_Stream *stream )
{
   if( !stream ) return TA_BAD_PARAM;
   if( stream->outRangeBegIdx + stream->outRangeCount > TA_INDEX_MAX )
      return TA_OUT_OF_RANGE_END_INDEX;
   stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_CRSI_Clone( const TA_CRSI_Stream *stream, TA_CRSI_Stream **clone )
{
   struct TA_CRSI_Stream *sp;

   if( !clone ) return TA_BAD_PARAM;
   *clone = NULL;
   if( !stream ) return TA_BAD_PARAM;
   sp = (struct TA_CRSI_Stream *)TA_Malloc( sizeof(*sp) );
   if( !sp ) return TA_ALLOC_ERR;
   *sp = *stream;
   sp->sub0 = NULL;
   sp->sub1 = NULL;
   sp->sub2 = NULL;
   sp->sub3 = NULL;
   if( stream->sub0 )
   { TA_RetCode subRc = TA_RSI_Clone( stream->sub0, &sp->sub0 );
     if( subRc != TA_SUCCESS ) { TA_CRSI_Close( sp ); return subRc; } }
   if( stream->sub1 )
   { TA_RetCode subRc = TA_RSI_Clone( stream->sub1, &sp->sub1 );
     if( subRc != TA_SUCCESS ) { TA_CRSI_Close( sp ); return subRc; } }
   if( stream->sub2 )
   { TA_RetCode subRc = TA_ROCP_Clone( stream->sub2, &sp->sub2 );
     if( subRc != TA_SUCCESS ) { TA_CRSI_Close( sp ); return subRc; } }
   if( stream->sub3 )
   { TA_RetCode subRc = TA_PERCENTRANK_Clone( stream->sub3, &sp->sub3 );
     if( subRc != TA_SUCCESS ) { TA_CRSI_Close( sp ); return subRc; } }
   *clone = sp;
   return TA_SUCCESS;
}

