/* TA-LIB Copyright (c) 1999-2026, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_stream_private.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  AC       Angelo Ciceri
 *
 *
 * Change history:
 *
 *  MMDDYY BY   Description
 *  -------------------------------------------------------------------
 *  020605 AC   Creation
 */

TA_LIB_API int TA_CDLRISEFALL3METHODS_Lookback( void )
{
   int BodyLong_avgPeriod = TA_Globals->candleSettings[TA_BodyLong].avgPeriod;
   int BodyShort_avgPeriod = TA_Globals->candleSettings[TA_BodyShort].avgPeriod;
   return max(BodyShort_avgPeriod,BodyLong_avgPeriod) + 4;
}

TA_LIB_API TA_RetCode TA_CDLRISEFALL3METHODS( int    startIdx,
                                              int    endIdx,
                                              const double inOpen[],
                                              const double inHigh[],
                                              const double inLow[],
                                              const double inClose[],
                                              int          *outBegIdx,
                                              int          *outNBElement,
                                              int        outInteger[] )
{
   double BodyPeriodTotal[5];
   int i;
   int outIdx;
   int totIdx;
   int BodyShortTrailingIdx;
   int BodyLongTrailingIdx;
   int lookbackTotal;
   int BodyLong_avgPeriod = TA_Globals->candleSettings[TA_BodyLong].avgPeriod;
   int BodyShort_avgPeriod = TA_Globals->candleSettings[TA_BodyShort].avgPeriod;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( !inOpen )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !inClose )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outInteger )
      return TA_BAD_PARAM;

   /* Identify the minimum number of price bar needed
    * to calculate at least one output.
    */
   lookbackTotal = TA_CDLRISEFALL3METHODS_Lookback();
   /* Move up the start index if there is not
    * enough initial data.
    */
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   /* Make sure there is still something to evaluate. */
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   /* Do the calculation using tight loops. */
   /* Add-up the initial period, except for the last value. */
   BodyPeriodTotal[4] = 0;
   BodyPeriodTotal[3] = 0;
   BodyPeriodTotal[2] = 0;
   BodyPeriodTotal[1] = 0;
   BodyPeriodTotal[0] = 0;
   BodyShortTrailingIdx = startIdx - BodyShort_avgPeriod;
   BodyLongTrailingIdx = startIdx - BodyLong_avgPeriod;
   i = BodyShortTrailingIdx;
   while( i < startIdx )
   {
      BodyPeriodTotal[3] = BodyPeriodTotal[3] + TA_CANDLERANGE(BodyShort,i - 3);
      BodyPeriodTotal[2] = BodyPeriodTotal[2] + TA_CANDLERANGE(BodyShort,i - 2);
      BodyPeriodTotal[1] = BodyPeriodTotal[1] + TA_CANDLERANGE(BodyShort,i - 1);
      i += 1;
   }
   i = BodyLongTrailingIdx;
   while( i < startIdx )
   {
      BodyPeriodTotal[4] = BodyPeriodTotal[4] + TA_CANDLERANGE(BodyLong,i - 4);
      BodyPeriodTotal[0] = BodyPeriodTotal[0] + TA_CANDLERANGE(BodyLong,i);
      i += 1;
   }
   i = startIdx;
   /* Proceed with the calculation for the requested range.
    * Must have:
    * - first candle: long white (black) candlestick
    * - then: group of falling (rising) small real body candlesticks (commonly black (white)) that hold within
    *   the prior long candle's range: ideally they should be three but two or more than three are ok too
    * - final candle: long white (black) candle that opens above (below) the previous small candle's close
    *   and closes above (below) the first long candle's close
    * The meaning of "short" and "long" is specified with TA_SetCandleSettings; here only patterns with 3 small candles
    * are considered;
    * outInteger is positive (1 to 100) or negative (-1 to -100)
    */
   outIdx = 0;
   do
   {
      if( ((inClose[i - 4] >= inOpen[i - 4]) ? 1 : 0 - 1) == 0 - ((inClose[i - 3] >= inOpen[i - 3]) ? 1 : 0 - 1) && /* white, 3 black, white  ||  black, 3 white, black */
          ((inClose[i - 3] >= inOpen[i - 3]) ? 1 : 0 - 1) == ((inClose[i - 2] >= inOpen[i - 2]) ? 1 : 0 - 1) &&
          ((inClose[i - 2] >= inOpen[i - 2]) ? 1 : 0 - 1) == ((inClose[i - 1] >= inOpen[i - 1]) ? 1 : 0 - 1) &&
          ((inClose[i - 1] >= inOpen[i - 1]) ? 1 : 0 - 1) == 0 - ((inClose[i] >= inOpen[i]) ? 1 : 0 - 1) &&
          min(inOpen[i - 3],inClose[i - 3]) < inHigh[i - 4] && /* 2nd to 4th hold within 1st: a part of the real body must be within 1st range */
          max(inOpen[i - 3],inClose[i - 3]) > inLow[i - 4] &&
          min(inOpen[i - 2],inClose[i - 2]) < inHigh[i - 4] &&
          max(inOpen[i - 2],inClose[i - 2]) > inLow[i - 4] &&
          min(inOpen[i - 1],inClose[i - 1]) < inHigh[i - 4] &&
          max(inOpen[i - 1],inClose[i - 1]) > inLow[i - 4] &&
          inClose[i - 2] * ((inClose[i - 4] >= inOpen[i - 4]) ? 1 : 0 - 1) < inClose[i - 3] * ((inClose[i - 4] >= inOpen[i - 4]) ? 1 : 0 - 1) && /* 2nd to 4th are falling (rising) */
          inClose[i - 1] * ((inClose[i - 4] >= inOpen[i - 4]) ? 1 : 0 - 1) < inClose[i - 2] * ((inClose[i - 4] >= inOpen[i - 4]) ? 1 : 0 - 1) &&
          inOpen[i] * ((inClose[i - 4] >= inOpen[i - 4]) ? 1 : 0 - 1) > inClose[i - 1] * ((inClose[i - 4] >= inOpen[i - 4]) ? 1 : 0 - 1) && /* 5th opens above (below) the prior close */
          inClose[i] * ((inClose[i - 4] >= inOpen[i - 4]) ? 1 : 0 - 1) > inClose[i - 4] * ((inClose[i - 4] >= inOpen[i - 4]) ? 1 : 0 - 1) && /* 5th closes above (below) the 1st close */
          fabs(inClose[i - 4] - inOpen[i - 4]) > TA_CANDLEAVERAGE(BodyLong,BodyPeriodTotal[4],i - 4) && /* 1st long, then 3 small, 5th long */
          fabs(inClose[i - 3] - inOpen[i - 3]) < TA_CANDLEAVERAGE(BodyShort,BodyPeriodTotal[3],i - 3) &&
          fabs(inClose[i - 2] - inOpen[i - 2]) < TA_CANDLEAVERAGE(BodyShort,BodyPeriodTotal[2],i - 2) &&
          fabs(inClose[i - 1] - inOpen[i - 1]) < TA_CANDLEAVERAGE(BodyShort,BodyPeriodTotal[1],i - 1) &&
          fabs(inClose[i] - inOpen[i]) > TA_CANDLEAVERAGE(BodyLong,BodyPeriodTotal[0],i) )
      {
         outInteger[outIdx++] = 100 * ((inClose[i - 4] >= inOpen[i - 4]) ? 1 : 0 - 1);
      } else 
      {
         outInteger[outIdx++] = 0;
      }
      /* add the current range and subtract the first range: this is done after the pattern recognition
       * when avgPeriod is not 0, that means "compare with the previous candles" (it excludes the current candle)
       */
      BodyPeriodTotal[4] = BodyPeriodTotal[4] + (TA_CANDLERANGE(BodyLong,i - 4) - TA_CANDLERANGE(BodyLong,BodyLongTrailingIdx - 4));
      for( totIdx = 3; totIdx >= 1; totIdx -= 1 )
      {
         BodyPeriodTotal[totIdx] = BodyPeriodTotal[totIdx] + (TA_CANDLERANGE(BodyShort,i - totIdx) - TA_CANDLERANGE(BodyShort,BodyShortTrailingIdx - totIdx));
      }
      BodyPeriodTotal[0] = BodyPeriodTotal[0] + (TA_CANDLERANGE(BodyLong,i) - TA_CANDLERANGE(BodyLong,BodyLongTrailingIdx));
      i += 1;
      BodyShortTrailingIdx += 1;
      BodyLongTrailingIdx += 1;
   } while( i <= endIdx );
   /* All done. Indicate the output limits and return. */
   *outNBElement= outIdx;
   *outBegIdx= startIdx;
   return TA_SUCCESS;
}

TA_RetCode TA_S_CDLRISEFALL3METHODS( int    startIdx,
                                     int    endIdx,
                                     const float inOpen[],
                                     const float inHigh[],
                                     const float inLow[],
                                     const float inClose[],
                                     int          *outBegIdx,
                                     int          *outNBElement,
                                     int        outInteger[] )
{
   double BodyPeriodTotal[5];
   int i;
   int outIdx;
   int totIdx;
   int BodyShortTrailingIdx;
   int BodyLongTrailingIdx;
   int lookbackTotal;
   int BodyLong_avgPeriod = TA_Globals->candleSettings[TA_BodyLong].avgPeriod;
   int BodyShort_avgPeriod = TA_Globals->candleSettings[TA_BodyShort].avgPeriod;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( !inOpen )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !inClose )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outInteger )
      return TA_BAD_PARAM;

   lookbackTotal = TA_CDLRISEFALL3METHODS_Lookback();
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   BodyPeriodTotal[4] = 0;
   BodyPeriodTotal[3] = 0;
   BodyPeriodTotal[2] = 0;
   BodyPeriodTotal[1] = 0;
   BodyPeriodTotal[0] = 0;
   BodyShortTrailingIdx = startIdx - BodyShort_avgPeriod;
   BodyLongTrailingIdx = startIdx - BodyLong_avgPeriod;
   i = BodyShortTrailingIdx;
   while( i < startIdx )
   {
      BodyPeriodTotal[3] = BodyPeriodTotal[3] + TA_CANDLERANGE(BodyShort,i - 3);
      BodyPeriodTotal[2] = BodyPeriodTotal[2] + TA_CANDLERANGE(BodyShort,i - 2);
      BodyPeriodTotal[1] = BodyPeriodTotal[1] + TA_CANDLERANGE(BodyShort,i - 1);
      i += 1;
   }
   i = BodyLongTrailingIdx;
   while( i < startIdx )
   {
      BodyPeriodTotal[4] = BodyPeriodTotal[4] + TA_CANDLERANGE(BodyLong,i - 4);
      BodyPeriodTotal[0] = BodyPeriodTotal[0] + TA_CANDLERANGE(BodyLong,i);
      i += 1;
   }
   i = startIdx;
   outIdx = 0;
   do
   {
      if( (((double)inClose[i - 4] >= (double)inOpen[i - 4]) ? 1 : 0 - 1) == 0 - (((double)inClose[i - 3] >= (double)inOpen[i - 3]) ? 1 : 0 - 1) && (((double)inClose[i - 3] >= (double)inOpen[i - 3]) ? 1 : 0 - 1) == (((double)inClose[i - 2] >= (double)inOpen[i - 2]) ? 1 : 0 - 1) && (((double)inClose[i - 2] >= (double)inOpen[i - 2]) ? 1 : 0 - 1) == (((double)inClose[i - 1] >= (double)inOpen[i - 1]) ? 1 : 0 - 1) && (((double)inClose[i - 1] >= (double)inOpen[i - 1]) ? 1 : 0 - 1) == 0 - (((double)inClose[i] >= (double)inOpen[i]) ? 1 : 0 - 1) && min((double)inOpen[i - 3],(double)inClose[i - 3]) < (double)inHigh[i - 4] && max((double)inOpen[i - 3],(double)inClose[i - 3]) > (double)inLow[i - 4] && min((double)inOpen[i - 2],(double)inClose[i - 2]) < (double)inHigh[i - 4] && max((double)inOpen[i - 2],(double)inClose[i - 2]) > (double)inLow[i - 4] && min((double)inOpen[i - 1],(double)inClose[i - 1]) < (double)inHigh[i - 4] && max((double)inOpen[i - 1],(double)inClose[i - 1]) > (double)inLow[i - 4] && (double)inClose[i - 2] * (((double)inClose[i - 4] >= (double)inOpen[i - 4]) ? 1 : 0 - 1) < (double)inClose[i - 3] * (((double)inClose[i - 4] >= (double)inOpen[i - 4]) ? 1 : 0 - 1) && (double)inClose[i - 1] * (((double)inClose[i - 4] >= (double)inOpen[i - 4]) ? 1 : 0 - 1) < (double)inClose[i - 2] * (((double)inClose[i - 4] >= (double)inOpen[i - 4]) ? 1 : 0 - 1) && (double)inOpen[i] * (((double)inClose[i - 4] >= (double)inOpen[i - 4]) ? 1 : 0 - 1) > (double)inClose[i - 1] * (((double)inClose[i - 4] >= (double)inOpen[i - 4]) ? 1 : 0 - 1) && (double)inClose[i] * (((double)inClose[i - 4] >= (double)inOpen[i - 4]) ? 1 : 0 - 1) > (double)inClose[i - 4] * (((double)inClose[i - 4] >= (double)inOpen[i - 4]) ? 1 : 0 - 1) && fabs((double)inClose[i - 4] - (double)inOpen[i - 4]) > TA_CANDLEAVERAGE(BodyLong,BodyPeriodTotal[4],i - 4) && fabs((double)inClose[i - 3] - (double)inOpen[i - 3]) < TA_CANDLEAVERAGE(BodyShort,BodyPeriodTotal[3],i - 3) && fabs((double)inClose[i - 2] - (double)inOpen[i - 2]) < TA_CANDLEAVERAGE(BodyShort,BodyPeriodTotal[2],i - 2) && fabs((double)inClose[i - 1] - (double)inOpen[i - 1]) < TA_CANDLEAVERAGE(BodyShort,BodyPeriodTotal[1],i - 1) && fabs((double)inClose[i] - (double)inOpen[i]) > TA_CANDLEAVERAGE(BodyLong,BodyPeriodTotal[0],i) )
      {
         outInteger[outIdx++] = 100 * (((double)inClose[i - 4] >= (double)inOpen[i - 4]) ? 1 : 0 - 1);
      } else 
      {
         outInteger[outIdx++] = 0;
      }
      BodyPeriodTotal[4] = BodyPeriodTotal[4] + (TA_CANDLERANGE(BodyLong,i - 4) - TA_CANDLERANGE(BodyLong,BodyLongTrailingIdx - 4));
      for( totIdx = 3; totIdx >= 1; totIdx -= 1 )
      {
         BodyPeriodTotal[totIdx] = BodyPeriodTotal[totIdx] + (TA_CANDLERANGE(BodyShort,i - totIdx) - TA_CANDLERANGE(BodyShort,BodyShortTrailingIdx - totIdx));
      }
      BodyPeriodTotal[0] = BodyPeriodTotal[0] + (TA_CANDLERANGE(BodyLong,i) - TA_CANDLERANGE(BodyLong,BodyLongTrailingIdx));
      i += 1;
      BodyShortTrailingIdx += 1;
      BodyLongTrailingIdx += 1;
   } while( i <= endIdx );
   *outNBElement= outIdx;
   *outBegIdx= startIdx;
   return TA_SUCCESS;
}

/**** Streaming API *****/

struct TA_CDLRISEFALL3METHODS_Stream {
   /* The bars this handle has an output for (see TA_StreamOutRange).
    * Kept first, and in this order, in every stream struct. */
   int outRangeBegIdx;
   int outRangeCount;
   /* The value(s) at the last bar the stream counted (see TA_CDLRISEFALL3METHODS_Value). */
   int cur_outInteger;
   double BodyPeriodTotal[5];
   double lag1_inOpen;
   double lag2_inOpen;
   double lag3_inOpen;
   double lag4_inOpen;
   double lag1_inHigh;
   double lag2_inHigh;
   double lag3_inHigh;
   double lag4_inHigh;
   double lag1_inLow;
   double lag2_inLow;
   double lag3_inLow;
   double lag4_inLow;
   double lag1_inClose;
   double lag2_inClose;
   double lag3_inClose;
   double lag4_inClose;
   int ringPos_BodyLongTrailingIdx;
   int ringCap_BodyLongTrailingIdx;
   int ringLag_BodyLongTrailingIdx;
   double *ring_BodyLongTrailingIdx_derived;
   int ringPos_BodyShortTrailingIdx;
   int ringCap_BodyShortTrailingIdx;
   int ringLag_BodyShortTrailingIdx;
   double *ring_BodyShortTrailingIdx_derived;
};

/* Private function, not in public API. */
static void TA_CDLRISEFALL3METHODS_ReleaseImpl( struct TA_CDLRISEFALL3METHODS_Stream *sp )
{
   if( !sp ) return;
   if( sp->ring_BodyLongTrailingIdx_derived ) TA_Free( sp->ring_BodyLongTrailingIdx_derived );
   if( sp->ring_BodyShortTrailingIdx_derived ) TA_Free( sp->ring_BodyShortTrailingIdx_derived );
   TA_Free( sp );
}

/* Private function, not in public API. */
static void TA_CDLRISEFALL3METHODS_StepImpl( struct TA_CDLRISEFALL3METHODS_Stream *sp, double inOpen, double inHigh, double inLow, double inClose, int *outInteger )
{
   int totIdx;

   sp->ring_BodyLongTrailingIdx_derived[sp->ringPos_BodyLongTrailingIdx] = TA_STREAM_CANDLERANGE(BodyLong,inOpen,inHigh,inLow,inClose);
   sp->ring_BodyShortTrailingIdx_derived[sp->ringPos_BodyShortTrailingIdx] = TA_STREAM_CANDLERANGE(BodyShort,inOpen,inHigh,inLow,inClose);
   if( ((sp->lag4_inClose >= sp->lag4_inOpen) ? 1 : 0 - 1) == 0 - ((sp->lag3_inClose >= sp->lag3_inOpen) ? 1 : 0 - 1) && /* white, 3 black, white  ||  black, 3 white, black */
       ((sp->lag3_inClose >= sp->lag3_inOpen) ? 1 : 0 - 1) == ((sp->lag2_inClose >= sp->lag2_inOpen) ? 1 : 0 - 1) &&
       ((sp->lag2_inClose >= sp->lag2_inOpen) ? 1 : 0 - 1) == ((sp->lag1_inClose >= sp->lag1_inOpen) ? 1 : 0 - 1) &&
       ((sp->lag1_inClose >= sp->lag1_inOpen) ? 1 : 0 - 1) == 0 - ((inClose >= inOpen) ? 1 : 0 - 1) &&
       min(sp->lag3_inOpen,sp->lag3_inClose) < sp->lag4_inHigh && /* 2nd to 4th hold within 1st: a part of the real body must be within 1st range */
       max(sp->lag3_inOpen,sp->lag3_inClose) > sp->lag4_inLow &&
       min(sp->lag2_inOpen,sp->lag2_inClose) < sp->lag4_inHigh &&
       max(sp->lag2_inOpen,sp->lag2_inClose) > sp->lag4_inLow &&
       min(sp->lag1_inOpen,sp->lag1_inClose) < sp->lag4_inHigh &&
       max(sp->lag1_inOpen,sp->lag1_inClose) > sp->lag4_inLow &&
       sp->lag2_inClose * ((sp->lag4_inClose >= sp->lag4_inOpen) ? 1 : 0 - 1) < sp->lag3_inClose * ((sp->lag4_inClose >= sp->lag4_inOpen) ? 1 : 0 - 1) && /* 2nd to 4th are falling (rising) */
       sp->lag1_inClose * ((sp->lag4_inClose >= sp->lag4_inOpen) ? 1 : 0 - 1) < sp->lag2_inClose * ((sp->lag4_inClose >= sp->lag4_inOpen) ? 1 : 0 - 1) &&
       inOpen * ((sp->lag4_inClose >= sp->lag4_inOpen) ? 1 : 0 - 1) > sp->lag1_inClose * ((sp->lag4_inClose >= sp->lag4_inOpen) ? 1 : 0 - 1) && /* 5th opens above (below) the prior close */
       inClose * ((sp->lag4_inClose >= sp->lag4_inOpen) ? 1 : 0 - 1) > sp->lag4_inClose * ((sp->lag4_inClose >= sp->lag4_inOpen) ? 1 : 0 - 1) && /* 5th closes above (below) the 1st close */
       fabs(sp->lag4_inClose - sp->lag4_inOpen) > TA_STREAM_CANDLEAVERAGE(BodyLong,sp->BodyPeriodTotal[4],sp->lag4_inOpen,sp->lag4_inHigh,sp->lag4_inLow,sp->lag4_inClose) && /* 1st long, then 3 small, 5th long */
       fabs(sp->lag3_inClose - sp->lag3_inOpen) < TA_STREAM_CANDLEAVERAGE(BodyShort,sp->BodyPeriodTotal[3],sp->lag3_inOpen,sp->lag3_inHigh,sp->lag3_inLow,sp->lag3_inClose) &&
       fabs(sp->lag2_inClose - sp->lag2_inOpen) < TA_STREAM_CANDLEAVERAGE(BodyShort,sp->BodyPeriodTotal[2],sp->lag2_inOpen,sp->lag2_inHigh,sp->lag2_inLow,sp->lag2_inClose) &&
       fabs(sp->lag1_inClose - sp->lag1_inOpen) < TA_STREAM_CANDLEAVERAGE(BodyShort,sp->BodyPeriodTotal[1],sp->lag1_inOpen,sp->lag1_inHigh,sp->lag1_inLow,sp->lag1_inClose) &&
       fabs(inClose - inOpen) > TA_STREAM_CANDLEAVERAGE(BodyLong,sp->BodyPeriodTotal[0],inOpen,inHigh,inLow,inClose) )
   {
      *outInteger= 100 * ((sp->lag4_inClose >= sp->lag4_inOpen) ? 1 : 0 - 1);
   } else 
   {
      *outInteger= 0;
   }
   /* add the current range and subtract the first range: this is done after the pattern recognition
    * when avgPeriod is not 0, that means "compare with the previous candles" (it excludes the current candle)
    */
   sp->BodyPeriodTotal[4] = sp->BodyPeriodTotal[4] + (TA_STREAM_CANDLERANGE(BodyLong,sp->lag4_inOpen,sp->lag4_inHigh,sp->lag4_inLow,sp->lag4_inClose) - sp->ring_BodyLongTrailingIdx_derived[(sp->ringPos_BodyLongTrailingIdx + sp->ringCap_BodyLongTrailingIdx - sp->ringLag_BodyLongTrailingIdx - 4) % sp->ringCap_BodyLongTrailingIdx]);
   for( totIdx = 3; totIdx >= 1; totIdx -= 1 )
   {
      sp->BodyPeriodTotal[totIdx] = sp->BodyPeriodTotal[totIdx] + (sp->ring_BodyShortTrailingIdx_derived[(sp->ringPos_BodyShortTrailingIdx + sp->ringCap_BodyShortTrailingIdx - totIdx >= sp->ringCap_BodyShortTrailingIdx) ? sp->ringPos_BodyShortTrailingIdx + sp->ringCap_BodyShortTrailingIdx - totIdx - sp->ringCap_BodyShortTrailingIdx : sp->ringPos_BodyShortTrailingIdx + sp->ringCap_BodyShortTrailingIdx - totIdx] - sp->ring_BodyShortTrailingIdx_derived[(sp->ringPos_BodyShortTrailingIdx + sp->ringCap_BodyShortTrailingIdx - sp->ringLag_BodyShortTrailingIdx - totIdx) % sp->ringCap_BodyShortTrailingIdx]);
   }
   sp->BodyPeriodTotal[0] = sp->BodyPeriodTotal[0] + (TA_STREAM_CANDLERANGE(BodyLong,inOpen,inHigh,inLow,inClose) - sp->ring_BodyLongTrailingIdx_derived[(sp->ringPos_BodyLongTrailingIdx + sp->ringCap_BodyLongTrailingIdx - sp->ringLag_BodyLongTrailingIdx) % sp->ringCap_BodyLongTrailingIdx]);
   sp->cur_outInteger = *outInteger;
   sp->lag4_inOpen = sp->lag3_inOpen;
   sp->lag3_inOpen = sp->lag2_inOpen;
   sp->lag2_inOpen = sp->lag1_inOpen;
   sp->lag1_inOpen = inOpen;
   sp->lag4_inHigh = sp->lag3_inHigh;
   sp->lag3_inHigh = sp->lag2_inHigh;
   sp->lag2_inHigh = sp->lag1_inHigh;
   sp->lag1_inHigh = inHigh;
   sp->lag4_inLow = sp->lag3_inLow;
   sp->lag3_inLow = sp->lag2_inLow;
   sp->lag2_inLow = sp->lag1_inLow;
   sp->lag1_inLow = inLow;
   sp->lag4_inClose = sp->lag3_inClose;
   sp->lag3_inClose = sp->lag2_inClose;
   sp->lag2_inClose = sp->lag1_inClose;
   sp->lag1_inClose = inClose;
   sp->ringPos_BodyLongTrailingIdx = sp->ringPos_BodyLongTrailingIdx + 1;
   if( sp->ringPos_BodyLongTrailingIdx >= sp->ringCap_BodyLongTrailingIdx )
   {
      sp->ringPos_BodyLongTrailingIdx = 0;
   }
   sp->ringPos_BodyShortTrailingIdx = sp->ringPos_BodyShortTrailingIdx + 1;
   if( sp->ringPos_BodyShortTrailingIdx >= sp->ringCap_BodyShortTrailingIdx )
   {
      sp->ringPos_BodyShortTrailingIdx = 0;
   }
}

static TA_RetCode TA_CDLRISEFALL3METHODS_OpenImpl( struct TA_CDLRISEFALL3METHODS_Stream **stream, const double inOpen[], const double inHigh[], const double inLow[], const double inClose[], int startIdx, int historyLen, int *outBegIdx, int *outNBElement, int outInteger[], int outStride )
{
   struct TA_CDLRISEFALL3METHODS_Stream *sp;
   int endIdx;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inOpen || !inHigh || !inLow || !inClose || !outInteger ) return TA_BAD_PARAM;
   if( startIdx > historyLen - 1 )
   {
      *outBegIdx = 0;
      *outNBElement = 0;
      return TA_INSUFFICIENT_HISTORY;
   }

   endIdx = historyLen - 1;

   {
      int BodyLong_avgPeriod = TA_Globals->candleSettings[TA_BodyLong].avgPeriod;
      int BodyShort_avgPeriod = TA_Globals->candleSettings[TA_BodyShort].avgPeriod;
      double BodyPeriodTotal[5] = {0};
      int i;
      int outIdx;
      int totIdx;
      int BodyShortTrailingIdx;
      int BodyLongTrailingIdx;
      int lookbackTotal;
      /* Identify the minimum number of price bar needed
       * to calculate at least one output.
       */
      lookbackTotal = TA_CDLRISEFALL3METHODS_Lookback();
      /* Move up the start index if there is not
       * enough initial data.
       */
      if( startIdx < lookbackTotal )
      {
         startIdx = lookbackTotal;
      }
      /* Make sure there is still something to evaluate. */
      if( startIdx > endIdx )
      {
         *outBegIdx= 0;
         *outNBElement= 0;
         return TA_INSUFFICIENT_HISTORY;
      }
      /* Do the calculation using tight loops. */
      /* Add-up the initial period, except for the last value. */
      BodyPeriodTotal[4] = 0;
      BodyPeriodTotal[3] = 0;
      BodyPeriodTotal[2] = 0;
      BodyPeriodTotal[1] = 0;
      BodyPeriodTotal[0] = 0;
      BodyShortTrailingIdx = startIdx - BodyShort_avgPeriod;
      BodyLongTrailingIdx = startIdx - BodyLong_avgPeriod;
      i = BodyShortTrailingIdx;
      while( i < startIdx )
      {
         BodyPeriodTotal[3] = BodyPeriodTotal[3] + TA_CANDLERANGE(BodyShort,i - 3);
         BodyPeriodTotal[2] = BodyPeriodTotal[2] + TA_CANDLERANGE(BodyShort,i - 2);
         BodyPeriodTotal[1] = BodyPeriodTotal[1] + TA_CANDLERANGE(BodyShort,i - 1);
         i += 1;
      }
      i = BodyLongTrailingIdx;
      while( i < startIdx )
      {
         BodyPeriodTotal[4] = BodyPeriodTotal[4] + TA_CANDLERANGE(BodyLong,i - 4);
         BodyPeriodTotal[0] = BodyPeriodTotal[0] + TA_CANDLERANGE(BodyLong,i);
         i += 1;
      }
      i = startIdx;
      /* Proceed with the calculation for the requested range.
       * Must have:
       * - first candle: long white (black) candlestick
       * - then: group of falling (rising) small real body candlesticks (commonly black (white)) that hold within
       *   the prior long candle's range: ideally they should be three but two or more than three are ok too
       * - final candle: long white (black) candle that opens above (below) the previous small candle's close
       *   and closes above (below) the first long candle's close
       * The meaning of "short" and "long" is specified with TA_SetCandleSettings; here only patterns with 3 small candles
       * are considered;
       * outInteger is positive (1 to 100) or negative (-1 to -100)
       */
      outIdx = 0;
      do
      {
         if( ((inClose[i - 4] >= inOpen[i - 4]) ? 1 : 0 - 1) == 0 - ((inClose[i - 3] >= inOpen[i - 3]) ? 1 : 0 - 1) && /* white, 3 black, white  ||  black, 3 white, black */
             ((inClose[i - 3] >= inOpen[i - 3]) ? 1 : 0 - 1) == ((inClose[i - 2] >= inOpen[i - 2]) ? 1 : 0 - 1) &&
             ((inClose[i - 2] >= inOpen[i - 2]) ? 1 : 0 - 1) == ((inClose[i - 1] >= inOpen[i - 1]) ? 1 : 0 - 1) &&
             ((inClose[i - 1] >= inOpen[i - 1]) ? 1 : 0 - 1) == 0 - ((inClose[i] >= inOpen[i]) ? 1 : 0 - 1) &&
             min(inOpen[i - 3],inClose[i - 3]) < inHigh[i - 4] && /* 2nd to 4th hold within 1st: a part of the real body must be within 1st range */
             max(inOpen[i - 3],inClose[i - 3]) > inLow[i - 4] &&
             min(inOpen[i - 2],inClose[i - 2]) < inHigh[i - 4] &&
             max(inOpen[i - 2],inClose[i - 2]) > inLow[i - 4] &&
             min(inOpen[i - 1],inClose[i - 1]) < inHigh[i - 4] &&
             max(inOpen[i - 1],inClose[i - 1]) > inLow[i - 4] &&
             inClose[i - 2] * ((inClose[i - 4] >= inOpen[i - 4]) ? 1 : 0 - 1) < inClose[i - 3] * ((inClose[i - 4] >= inOpen[i - 4]) ? 1 : 0 - 1) && /* 2nd to 4th are falling (rising) */
             inClose[i - 1] * ((inClose[i - 4] >= inOpen[i - 4]) ? 1 : 0 - 1) < inClose[i - 2] * ((inClose[i - 4] >= inOpen[i - 4]) ? 1 : 0 - 1) &&
             inOpen[i] * ((inClose[i - 4] >= inOpen[i - 4]) ? 1 : 0 - 1) > inClose[i - 1] * ((inClose[i - 4] >= inOpen[i - 4]) ? 1 : 0 - 1) && /* 5th opens above (below) the prior close */
             inClose[i] * ((inClose[i - 4] >= inOpen[i - 4]) ? 1 : 0 - 1) > inClose[i - 4] * ((inClose[i - 4] >= inOpen[i - 4]) ? 1 : 0 - 1) && /* 5th closes above (below) the 1st close */
             fabs(inClose[i - 4] - inOpen[i - 4]) > TA_CANDLEAVERAGE(BodyLong,BodyPeriodTotal[4],i - 4) && /* 1st long, then 3 small, 5th long */
             fabs(inClose[i - 3] - inOpen[i - 3]) < TA_CANDLEAVERAGE(BodyShort,BodyPeriodTotal[3],i - 3) &&
             fabs(inClose[i - 2] - inOpen[i - 2]) < TA_CANDLEAVERAGE(BodyShort,BodyPeriodTotal[2],i - 2) &&
             fabs(inClose[i - 1] - inOpen[i - 1]) < TA_CANDLEAVERAGE(BodyShort,BodyPeriodTotal[1],i - 1) &&
             fabs(inClose[i] - inOpen[i]) > TA_CANDLEAVERAGE(BodyLong,BodyPeriodTotal[0],i) )
         {
            outInteger[outIdx++ * outStride] = 100 * ((inClose[i - 4] >= inOpen[i - 4]) ? 1 : 0 - 1);
         } else 
         {
            outInteger[outIdx++ * outStride] = 0;
         }
         /* add the current range and subtract the first range: this is done after the pattern recognition
          * when avgPeriod is not 0, that means "compare with the previous candles" (it excludes the current candle)
          */
         BodyPeriodTotal[4] = BodyPeriodTotal[4] + (TA_CANDLERANGE(BodyLong,i - 4) - TA_CANDLERANGE(BodyLong,BodyLongTrailingIdx - 4));
         for( totIdx = 3; totIdx >= 1; totIdx -= 1 )
         {
            BodyPeriodTotal[totIdx] = BodyPeriodTotal[totIdx] + (TA_CANDLERANGE(BodyShort,i - totIdx) - TA_CANDLERANGE(BodyShort,BodyShortTrailingIdx - totIdx));
         }
         BodyPeriodTotal[0] = BodyPeriodTotal[0] + (TA_CANDLERANGE(BodyLong,i) - TA_CANDLERANGE(BodyLong,BodyLongTrailingIdx));
         i += 1;
         BodyShortTrailingIdx += 1;
         BodyLongTrailingIdx += 1;
      } while( i <= endIdx );
      /* All done. Indicate the output limits and return. */
      *outNBElement= outIdx;
      *outBegIdx= startIdx;

      /* Capture the live batch state into the handle. */
      sp = (struct TA_CDLRISEFALL3METHODS_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) { return TA_ALLOC_ERR; }
      memset( sp, 0, sizeof(*sp) );
      memcpy( sp->BodyPeriodTotal, BodyPeriodTotal, sizeof( sp->BodyPeriodTotal ) );
      sp->ringLag_BodyLongTrailingIdx = (int)(i - BodyLongTrailingIdx);
      sp->ringCap_BodyLongTrailingIdx = sp->ringLag_BodyLongTrailingIdx + 5;
      if( sp->ringLag_BodyLongTrailingIdx < 0 || sp->ringCap_BodyLongTrailingIdx > historyLen ) { TA_CDLRISEFALL3METHODS_ReleaseImpl( sp ); return TA_INTERNAL_ERROR(287); }
      { size_t allocN = (size_t)(sp->ringCap_BodyLongTrailingIdx > 0 ? sp->ringCap_BodyLongTrailingIdx : 1);
        sp->ring_BodyLongTrailingIdx_derived = (double *)TA_Malloc( sizeof(double) * allocN );
        if( !sp->ring_BodyLongTrailingIdx_derived ) { TA_CDLRISEFALL3METHODS_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
        { int fillJ;
          for( fillJ = historyLen - sp->ringCap_BodyLongTrailingIdx; fillJ < historyLen; fillJ++ )
             sp->ring_BodyLongTrailingIdx_derived[fillJ % sp->ringCap_BodyLongTrailingIdx] = TA_STREAM_CANDLERANGE(BodyLong,inOpen[fillJ],inHigh[fillJ],inLow[fillJ],inClose[fillJ]);
        }
      }
      sp->ringPos_BodyLongTrailingIdx = historyLen % sp->ringCap_BodyLongTrailingIdx;
      sp->ringLag_BodyShortTrailingIdx = (int)(i - BodyShortTrailingIdx);
      sp->ringCap_BodyShortTrailingIdx = sp->ringLag_BodyShortTrailingIdx + 4;
      if( sp->ringLag_BodyShortTrailingIdx < 0 || sp->ringCap_BodyShortTrailingIdx > historyLen ) { TA_CDLRISEFALL3METHODS_ReleaseImpl( sp ); return TA_INTERNAL_ERROR(288); }
      { size_t allocN = (size_t)(sp->ringCap_BodyShortTrailingIdx > 0 ? sp->ringCap_BodyShortTrailingIdx : 1);
        sp->ring_BodyShortTrailingIdx_derived = (double *)TA_Malloc( sizeof(double) * allocN );
        if( !sp->ring_BodyShortTrailingIdx_derived ) { TA_CDLRISEFALL3METHODS_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
        { int fillJ;
          for( fillJ = historyLen - sp->ringCap_BodyShortTrailingIdx; fillJ < historyLen; fillJ++ )
             sp->ring_BodyShortTrailingIdx_derived[fillJ % sp->ringCap_BodyShortTrailingIdx] = TA_STREAM_CANDLERANGE(BodyShort,inOpen[fillJ],inHigh[fillJ],inLow[fillJ],inClose[fillJ]);
        }
      }
      sp->ringPos_BodyShortTrailingIdx = historyLen % sp->ringCap_BodyShortTrailingIdx;
      sp->lag1_inOpen = inOpen[historyLen - 1];
      sp->lag2_inOpen = inOpen[historyLen - 2];
      sp->lag3_inOpen = inOpen[historyLen - 3];
      sp->lag4_inOpen = inOpen[historyLen - 4];
      sp->lag1_inHigh = inHigh[historyLen - 1];
      sp->lag2_inHigh = inHigh[historyLen - 2];
      sp->lag3_inHigh = inHigh[historyLen - 3];
      sp->lag4_inHigh = inHigh[historyLen - 4];
      sp->lag1_inLow = inLow[historyLen - 1];
      sp->lag2_inLow = inLow[historyLen - 2];
      sp->lag3_inLow = inLow[historyLen - 3];
      sp->lag4_inLow = inLow[historyLen - 4];
      sp->lag1_inClose = inClose[historyLen - 1];
      sp->lag2_inClose = inClose[historyLen - 2];
      sp->lag3_inClose = inClose[historyLen - 3];
      sp->lag4_inClose = inClose[historyLen - 4];
      sp->outRangeBegIdx = *outBegIdx;
      sp->outRangeCount = *outNBElement;
      sp->cur_outInteger = outInteger[(*outNBElement - 1) * outStride];
      *stream = sp;
      return TA_SUCCESS;
   }
}

/* Private function, not in public API. */
TA_RetCode TA_CDLRISEFALL3METHODS_OpenInternal( struct TA_CDLRISEFALL3METHODS_Stream **stream, const double inOpen[], const double inHigh[], const double inLow[], const double inClose[], int startIdx, int historyLen, int *outInteger )
{
   TA_RetCode retCode;
   int dummyBegIdx = 0;
   int dummyNBElement = 0;
   int sink_outInteger = 0;
   retCode = TA_CDLRISEFALL3METHODS_OpenImpl( stream, inOpen, inHigh, inLow, inClose, startIdx, historyLen, &dummyBegIdx, &dummyNBElement, &sink_outInteger, 0 );
   if( retCode == TA_SUCCESS )
   {
      *outInteger = sink_outInteger;
   }
   return retCode;
}

TA_LIB_API TA_RetCode TA_CDLRISEFALL3METHODS_Open( TA_CDLRISEFALL3METHODS_Stream **stream, const double inOpen[], const double inHigh[], const double inLow[], const double inClose[], int historyLen, int *outInteger )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inOpen || !inHigh || !inLow || !inClose || !outInteger ) return TA_BAD_PARAM;
   return TA_CDLRISEFALL3METHODS_OpenInternal( stream, inOpen, inHigh, inLow, inClose, 0, historyLen, outInteger );
}

TA_LIB_API TA_RetCode TA_CDLRISEFALL3METHODS_OpenAndFill( TA_CDLRISEFALL3METHODS_Stream **stream, const double inOpen[], const double inHigh[], const double inLow[], const double inClose[], int historyLen, int *outBegIdx, int *outNBElement, int outInteger[] )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inOpen || !inHigh || !inLow || !inClose || !outBegIdx || !outNBElement || !outInteger ) return TA_BAD_PARAM;
   if( (const void *)outInteger == (const void *)inOpen || (const void *)outInteger == (const void *)inHigh || (const void *)outInteger == (const void *)inLow || (const void *)outInteger == (const void *)inClose ) return TA_BAD_PARAM;
   return TA_CDLRISEFALL3METHODS_OpenAndFillInternal( stream, inOpen, inHigh, inLow, inClose, 0, historyLen, outBegIdx, outNBElement, outInteger );
}

/* Private function, not in public API. */
TA_RetCode TA_CDLRISEFALL3METHODS_OpenAndFillInternal( struct TA_CDLRISEFALL3METHODS_Stream **stream, const double inOpen[], const double inHigh[], const double inLow[], const double inClose[], int startIdx, int historyLen, int *outBegIdx, int *outNBElement, int outInteger[] )
{
   return TA_CDLRISEFALL3METHODS_OpenImpl( stream, inOpen, inHigh, inLow, inClose, startIdx, historyLen, outBegIdx, outNBElement, outInteger, 1 );
}

TA_LIB_API TA_RetCode TA_CDLRISEFALL3METHODS_Update( TA_CDLRISEFALL3METHODS_Stream *stream, double inOpen, double inHigh, double inLow, double inClose, int *outInteger )
{
   if( !stream || !outInteger ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inOpen ) || !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) || !TA_IS_FINITE( inClose ) )
   {
      if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
      return TA_BAD_PARAM;
   }
   TA_CDLRISEFALL3METHODS_StepImpl( stream, inOpen, inHigh, inLow, inClose, outInteger );
   if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_CDLRISEFALL3METHODS_Peek( const TA_CDLRISEFALL3METHODS_Stream *stream, double inOpen, double inHigh, double inLow, double inClose, int *outInteger )
{
   const struct TA_CDLRISEFALL3METHODS_Stream *sp = stream;

   if( !stream || !outInteger ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inOpen ) || !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) || !TA_IS_FINITE( inClose ) ) return TA_BAD_PARAM;
   if( ((sp->lag4_inClose >= sp->lag4_inOpen) ? 1 : 0 - 1) == 0 - ((sp->lag3_inClose >= sp->lag3_inOpen) ? 1 : 0 - 1) && /* white, 3 black, white  ||  black, 3 white, black */
       ((sp->lag3_inClose >= sp->lag3_inOpen) ? 1 : 0 - 1) == ((sp->lag2_inClose >= sp->lag2_inOpen) ? 1 : 0 - 1) &&
       ((sp->lag2_inClose >= sp->lag2_inOpen) ? 1 : 0 - 1) == ((sp->lag1_inClose >= sp->lag1_inOpen) ? 1 : 0 - 1) &&
       ((sp->lag1_inClose >= sp->lag1_inOpen) ? 1 : 0 - 1) == 0 - ((inClose >= inOpen) ? 1 : 0 - 1) &&
       min(sp->lag3_inOpen,sp->lag3_inClose) < sp->lag4_inHigh && /* 2nd to 4th hold within 1st: a part of the real body must be within 1st range */
       max(sp->lag3_inOpen,sp->lag3_inClose) > sp->lag4_inLow &&
       min(sp->lag2_inOpen,sp->lag2_inClose) < sp->lag4_inHigh &&
       max(sp->lag2_inOpen,sp->lag2_inClose) > sp->lag4_inLow &&
       min(sp->lag1_inOpen,sp->lag1_inClose) < sp->lag4_inHigh &&
       max(sp->lag1_inOpen,sp->lag1_inClose) > sp->lag4_inLow &&
       sp->lag2_inClose * ((sp->lag4_inClose >= sp->lag4_inOpen) ? 1 : 0 - 1) < sp->lag3_inClose * ((sp->lag4_inClose >= sp->lag4_inOpen) ? 1 : 0 - 1) && /* 2nd to 4th are falling (rising) */
       sp->lag1_inClose * ((sp->lag4_inClose >= sp->lag4_inOpen) ? 1 : 0 - 1) < sp->lag2_inClose * ((sp->lag4_inClose >= sp->lag4_inOpen) ? 1 : 0 - 1) &&
       inOpen * ((sp->lag4_inClose >= sp->lag4_inOpen) ? 1 : 0 - 1) > sp->lag1_inClose * ((sp->lag4_inClose >= sp->lag4_inOpen) ? 1 : 0 - 1) && /* 5th opens above (below) the prior close */
       inClose * ((sp->lag4_inClose >= sp->lag4_inOpen) ? 1 : 0 - 1) > sp->lag4_inClose * ((sp->lag4_inClose >= sp->lag4_inOpen) ? 1 : 0 - 1) && /* 5th closes above (below) the 1st close */
       fabs(sp->lag4_inClose - sp->lag4_inOpen) > TA_STREAM_CANDLEAVERAGE(BodyLong,sp->BodyPeriodTotal[4],sp->lag4_inOpen,sp->lag4_inHigh,sp->lag4_inLow,sp->lag4_inClose) && /* 1st long, then 3 small, 5th long */
       fabs(sp->lag3_inClose - sp->lag3_inOpen) < TA_STREAM_CANDLEAVERAGE(BodyShort,sp->BodyPeriodTotal[3],sp->lag3_inOpen,sp->lag3_inHigh,sp->lag3_inLow,sp->lag3_inClose) &&
       fabs(sp->lag2_inClose - sp->lag2_inOpen) < TA_STREAM_CANDLEAVERAGE(BodyShort,sp->BodyPeriodTotal[2],sp->lag2_inOpen,sp->lag2_inHigh,sp->lag2_inLow,sp->lag2_inClose) &&
       fabs(sp->lag1_inClose - sp->lag1_inOpen) < TA_STREAM_CANDLEAVERAGE(BodyShort,sp->BodyPeriodTotal[1],sp->lag1_inOpen,sp->lag1_inHigh,sp->lag1_inLow,sp->lag1_inClose) &&
       fabs(inClose - inOpen) > TA_STREAM_CANDLEAVERAGE(BodyLong,sp->BodyPeriodTotal[0],inOpen,inHigh,inLow,inClose) )
   {
      *outInteger= 100 * ((sp->lag4_inClose >= sp->lag4_inOpen) ? 1 : 0 - 1);
   } else 
   {
      *outInteger= 0;
   }
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_CDLRISEFALL3METHODS_UpdateAndFill( TA_CDLRISEFALL3METHODS_Stream *stream, const double inOpen[], const double inHigh[], const double inLow[], const double inClose[], int barCount, int outInteger[] )
{
   int i;

   if( !stream || !inOpen || !inHigh || !inLow || !inClose || !outInteger ) return TA_BAD_PARAM;
   if( barCount < 0 ) return TA_BAD_PARAM;
   if( (const void *)outInteger == (const void *)inOpen || (const void *)outInteger == (const void *)inHigh || (const void *)outInteger == (const void *)inLow || (const void *)outInteger == (const void *)inClose ) return TA_BAD_PARAM;
   for( i = 0; i < barCount; i++ )
   {
      if( !TA_IS_FINITE( inOpen[i] ) || !TA_IS_FINITE( inHigh[i] ) || !TA_IS_FINITE( inLow[i] ) || !TA_IS_FINITE( inClose[i] ) )
      {
         if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
         return TA_BAD_PARAM;
      }
      TA_CDLRISEFALL3METHODS_StepImpl( stream, inOpen[i], inHigh[i], inLow[i], inClose[i], &outInteger[i] );
      if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   }
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_CDLRISEFALL3METHODS_Close( TA_CDLRISEFALL3METHODS_Stream *stream )
{
   TA_CDLRISEFALL3METHODS_ReleaseImpl( stream );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_CDLRISEFALL3METHODS_Value( const TA_CDLRISEFALL3METHODS_Stream *stream, int *outInteger )
{
   if( !stream || !outInteger ) return TA_BAD_PARAM;
   *outInteger = stream->cur_outInteger;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_CDLRISEFALL3METHODS_Clone( const TA_CDLRISEFALL3METHODS_Stream *stream, TA_CDLRISEFALL3METHODS_Stream **clone )
{
   struct TA_CDLRISEFALL3METHODS_Stream *sp;

   if( !clone ) return TA_BAD_PARAM;
   *clone = NULL;
   if( !stream ) return TA_BAD_PARAM;
   sp = (struct TA_CDLRISEFALL3METHODS_Stream *)TA_Malloc( sizeof(*sp) );
   if( !sp ) return TA_ALLOC_ERR;
   *sp = *stream;
   sp->ring_BodyLongTrailingIdx_derived = NULL;
   sp->ring_BodyShortTrailingIdx_derived = NULL;
   if( stream->ring_BodyLongTrailingIdx_derived )
   { size_t copyN = (size_t)(sp->ringCap_BodyLongTrailingIdx > 0 ? sp->ringCap_BodyLongTrailingIdx : 1);
     sp->ring_BodyLongTrailingIdx_derived = (double *)TA_Malloc( sizeof(double) * copyN );
     if( !sp->ring_BodyLongTrailingIdx_derived ) { TA_CDLRISEFALL3METHODS_Close( sp ); return TA_ALLOC_ERR; }
     memcpy( sp->ring_BodyLongTrailingIdx_derived, stream->ring_BodyLongTrailingIdx_derived, sizeof(double) * copyN ); }
   if( stream->ring_BodyShortTrailingIdx_derived )
   { size_t copyN = (size_t)(sp->ringCap_BodyShortTrailingIdx > 0 ? sp->ringCap_BodyShortTrailingIdx : 1);
     sp->ring_BodyShortTrailingIdx_derived = (double *)TA_Malloc( sizeof(double) * copyN );
     if( !sp->ring_BodyShortTrailingIdx_derived ) { TA_CDLRISEFALL3METHODS_Close( sp ); return TA_ALLOC_ERR; }
     memcpy( sp->ring_BodyShortTrailingIdx_derived, stream->ring_BodyShortTrailingIdx_derived, sizeof(double) * copyN ); }
   *clone = sp;
   return TA_SUCCESS;
}

