/* TA-LIB Copyright (c) 1999-2026, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_stream_private.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  MF       Mario Fortier
 *  CC       Claude Code (AI assistant)
 *
 * Change history:
 *
 *  MMDDYY BY     Description
 *  -------------------------------------------------------------------
 *  072126 MF,CC  First version (issue #134).
 */

TA_LIB_API int TA_CMF_Lookback( int optInTimePeriod )
{
   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 20;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return -1;
   return optInTimePeriod - 1;
}

TA_LIB_API TA_RetCode TA_CMF( int    startIdx,
                              int    endIdx,
                              const double inHigh[],
                              const double inLow[],
                              const double inClose[],
                              const double inVolume[],
                              int optInTimePeriod,
                              int          *outBegIdx,
                              int          *outNBElement,
                              double        outReal[] )
{
   double sumMFV;
   double sumVol;
   double high;
   double low;
   double close;
   double tmp;
   double mfv;
   int lookbackTotal;
   int outIdx;
   int i;
   int today;
   double local_mfv_flow[50];
   double *mfv_flow = &local_mfv_flow[0];
   double local_mfv_volume[50];
   double *mfv_volume = &local_mfv_volume[0];
   int mfv_Idx;
   int maxIdx_mfv;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 20;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !inClose )
      return TA_BAD_PARAM;
   if( !inVolume )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   /* Both the per-bar money flow volume and the volume that produced it are
    * carried in the circular buffer. Keeping the volume here rather than
    * re-reading inVolume[] at the trailing index is what makes outReal safe to
    * alias any input: once a bar has been consumed it is never read again.
    */
   /* Id, Type, Static Size */
   *outBegIdx= 0;
   *outNBElement= 0;
   /* Identify the minimum number of price bar needed
    * to calculate at least one output.
    */
   lookbackTotal = optInTimePeriod - 1;
   /* Move up the start index if there is not
    * enough initial data.
    */
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   /* Make sure there is still something to evaluate. */
   if( startIdx > endIdx )
   {
      return TA_SUCCESS;
   }
   if( optInTimePeriod < 1 ) return TA_INTERNAL_ERROR(314);
   if( (int)optInTimePeriod > (int)(sizeof(local_mfv_flow)/sizeof(double)) )
   {
      mfv_flow = TA_Malloc( sizeof(double)*optInTimePeriod );
      if( !mfv_flow )
      {
         return TA_ALLOC_ERR;
      }
      mfv_volume = TA_Malloc( sizeof(double)*optInTimePeriod );
      if( !mfv_volume )
      {
         TA_Free( mfv_flow );
         return TA_ALLOC_ERR;
      }
   }
   else
   {
      mfv_flow = &local_mfv_flow[0];
      mfv_volume = &local_mfv_volume[0];
   }
   maxIdx_mfv = (optInTimePeriod-1);
   mfv_Idx = 0;
   outIdx = 0;
   /* Accumulate the money flow volume and the volume over the first
    * complete window, filling the circular buffer as we go.
    *
    * The per-bar multiplier is written exactly as in ta_AD.c so that the
    * Chaikin money flow volume has one definition in the library.
    */
   today = startIdx - lookbackTotal;
   sumMFV = 0.0;
   sumVol = 0.0;
   for( i = optInTimePeriod; i > 0; i -= 1 )
   {
      high = inHigh[today];
      low = inLow[today];
      close = inClose[today];
      tmp = high - low;
      if( tmp > 0.0 )
      {
         mfv = (close - low - (high - close)) / tmp * inVolume[today];
      } else 
      {
         mfv = 0.0;
      }
      mfv_flow[mfv_Idx] = mfv;
      mfv_volume[mfv_Idx] = inVolume[today];
      sumMFV += mfv;
      sumVol += inVolume[today];
      today += 1;
      mfv_Idx++;
      if( mfv_Idx > maxIdx_mfv ) mfv_Idx = 0;
   }
   /* The first full window is complete: emit its output for startIdx here,
    * then slide the window over the remaining bars below.
    *
    * A window whose volume is entirely zero has no money flow to distribute;
    * report 0.0 rather than propagating a division by zero (issue #112).
    */
   if( sumVol > 0.0 )
   {
      outReal[outIdx++] = sumMFV / sumVol;
   } else 
   {
      outReal[outIdx++] = 0.0;
   }
   /* Now continue processing the remaining bars. */
   while( today <= endIdx )
   {
      sumMFV -= mfv_flow[mfv_Idx];
      sumVol -= mfv_volume[mfv_Idx];
      high = inHigh[today];
      low = inLow[today];
      close = inClose[today];
      tmp = high - low;
      if( tmp > 0.0 )
      {
         mfv = (close - low - (high - close)) / tmp * inVolume[today];
      } else 
      {
         mfv = 0.0;
      }
      mfv_flow[mfv_Idx] = mfv;
      mfv_volume[mfv_Idx] = inVolume[today];
      sumMFV += mfv;
      sumVol += inVolume[today];
      today += 1;
      if( sumVol > 0.0 )
      {
         outReal[outIdx++] = sumMFV / sumVol;
      } else 
      {
         outReal[outIdx++] = 0.0;
      }
      mfv_Idx++;
      if( mfv_Idx > maxIdx_mfv ) mfv_Idx = 0;
   }
   if( mfv_flow != &local_mfv_flow[0] ) { TA_Free( mfv_flow ); mfv_flow = &local_mfv_flow[0]; }
   if( mfv_volume != &local_mfv_volume[0] ) { TA_Free( mfv_volume ); mfv_volume = &local_mfv_volume[0]; }
   *outBegIdx= startIdx;
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

TA_RetCode TA_S_CMF( int    startIdx,
                     int    endIdx,
                     const float inHigh[],
                     const float inLow[],
                     const float inClose[],
                     const float inVolume[],
                     int optInTimePeriod,
                     int          *outBegIdx,
                     int          *outNBElement,
                     double        outReal[] )
{
   double sumMFV;
   double sumVol;
   double high;
   double low;
   double close;
   double tmp;
   double mfv;
   int lookbackTotal;
   int outIdx;
   int i;
   int today;
   double local_mfv_flow[50];
   double *mfv_flow = &local_mfv_flow[0];
   double local_mfv_volume[50];
   double *mfv_volume = &local_mfv_volume[0];
   int mfv_Idx;
   int maxIdx_mfv;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 20;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !inClose )
      return TA_BAD_PARAM;
   if( !inVolume )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   *outBegIdx= 0;
   *outNBElement= 0;
   lookbackTotal = optInTimePeriod - 1;
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   if( startIdx > endIdx )
   {
      return TA_SUCCESS;
   }
   if( optInTimePeriod < 1 ) return TA_INTERNAL_ERROR(314);
   if( (int)optInTimePeriod > (int)(sizeof(local_mfv_flow)/sizeof(double)) )
   {
      mfv_flow = TA_Malloc( sizeof(double)*optInTimePeriod );
      if( !mfv_flow )
      {
         return TA_ALLOC_ERR;
      }
      mfv_volume = TA_Malloc( sizeof(double)*optInTimePeriod );
      if( !mfv_volume )
      {
         TA_Free( mfv_flow );
         return TA_ALLOC_ERR;
      }
   }
   else
   {
      mfv_flow = &local_mfv_flow[0];
      mfv_volume = &local_mfv_volume[0];
   }
   maxIdx_mfv = (optInTimePeriod-1);
   mfv_Idx = 0;
   outIdx = 0;
   today = startIdx - lookbackTotal;
   sumMFV = 0.0;
   sumVol = 0.0;
   for( i = optInTimePeriod; i > 0; i -= 1 )
   {
      high = (double)inHigh[today];
      low = (double)inLow[today];
      close = (double)inClose[today];
      tmp = high - low;
      if( tmp > 0.0 )
      {
         mfv = (close - low - (high - close)) / tmp * (double)inVolume[today];
      } else 
      {
         mfv = 0.0;
      }
      mfv_flow[mfv_Idx] = mfv;
      mfv_volume[mfv_Idx] = (double)inVolume[today];
      sumMFV += mfv;
      sumVol += (double)inVolume[today];
      today += 1;
      mfv_Idx++;
      if( mfv_Idx > maxIdx_mfv ) mfv_Idx = 0;
   }
   if( sumVol > 0.0 )
   {
      outReal[outIdx++] = sumMFV / sumVol;
   } else 
   {
      outReal[outIdx++] = 0.0;
   }
   while( today <= endIdx )
   {
      sumMFV -= mfv_flow[mfv_Idx];
      sumVol -= mfv_volume[mfv_Idx];
      high = (double)inHigh[today];
      low = (double)inLow[today];
      close = (double)inClose[today];
      tmp = high - low;
      if( tmp > 0.0 )
      {
         mfv = (close - low - (high - close)) / tmp * (double)inVolume[today];
      } else 
      {
         mfv = 0.0;
      }
      mfv_flow[mfv_Idx] = mfv;
      mfv_volume[mfv_Idx] = (double)inVolume[today];
      sumMFV += mfv;
      sumVol += (double)inVolume[today];
      today += 1;
      if( sumVol > 0.0 )
      {
         outReal[outIdx++] = sumMFV / sumVol;
      } else 
      {
         outReal[outIdx++] = 0.0;
      }
      mfv_Idx++;
      if( mfv_Idx > maxIdx_mfv ) mfv_Idx = 0;
   }
   if( mfv_flow != &local_mfv_flow[0] ) { TA_Free( mfv_flow ); mfv_flow = &local_mfv_flow[0]; }
   if( mfv_volume != &local_mfv_volume[0] ) { TA_Free( mfv_volume ); mfv_volume = &local_mfv_volume[0]; }
   *outBegIdx= startIdx;
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

/**** Streaming API *****/

struct TA_CMF_Stream {
   /* The bars this handle has an output for (see TA_StreamOutRange).
    * Kept first, and in this order, in every stream struct. */
   int outRangeBegIdx;
   int outRangeCount;
   /* The value(s) at the last bar the stream counted (see TA_CMF_Value). */
   double cur_outReal;
   int optInTimePeriod;
   double sumMFV;
   double sumVol;
   int mfv_Idx;
   int maxIdx_mfv;
   int cbSize_mfv;
   double *cb_mfv_flow;
   double *cb_mfv_volume;
};

/* Private function, not in public API. */
static void TA_CMF_ReleaseImpl( struct TA_CMF_Stream *sp )
{
   if( !sp ) return;
   if( sp->cb_mfv_flow ) TA_Free( sp->cb_mfv_flow );
   if( sp->cb_mfv_volume ) TA_Free( sp->cb_mfv_volume );
   TA_Free( sp );
}

/* Private function, not in public API. */
static void TA_CMF_StepImpl( struct TA_CMF_Stream *sp, double inHigh, double inLow, double inClose, double inVolume, double *outReal )
{
   double high;
   double low;
   double close;
   double tmp;
   double mfv;
   double sumMFV;
   double sumVol;

   sumMFV = sp->sumMFV;
   sumVol = sp->sumVol;
   sumMFV -= sp->cb_mfv_flow[sp->mfv_Idx];
   sumVol -= sp->cb_mfv_volume[sp->mfv_Idx];
   high = inHigh;
   low = inLow;
   close = inClose;
   tmp = high - low;
   if( tmp > 0.0 )
   {
      mfv = (close - low - (high - close)) / tmp * inVolume;
   } else 
   {
      mfv = 0.0;
   }
   sp->cb_mfv_flow[sp->mfv_Idx] = mfv;
   sp->cb_mfv_volume[sp->mfv_Idx] = inVolume;
   sumMFV += mfv;
   sumVol += inVolume;
   if( sumVol > 0.0 )
   {
      *outReal= sumMFV / sumVol;
   } else 
   {
      *outReal= 0.0;
   }
   sp->mfv_Idx = sp->mfv_Idx + 1;
   if( sp->mfv_Idx > sp->maxIdx_mfv )
   {
      sp->mfv_Idx = 0;
   }
   sp->cur_outReal = *outReal;
   sp->sumMFV = sumMFV;
   sp->sumVol = sumVol;
}

static TA_RetCode TA_CMF_OpenImpl( struct TA_CMF_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], const double inVolume[], int startIdx, int historyLen, int optInTimePeriod, int *outBegIdx, int *outNBElement, double outReal[], int outStride )
{
   struct TA_CMF_Stream *sp;
   double local_mfv_flow[50];
   double *mfv_flow;
   double local_mfv_volume[50];
   double *mfv_volume;
   int mfv_Idx;
   int maxIdx_mfv;
   int endIdx;
   int dummyBegIdx;
   int dummyNBElement;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !inClose || !inVolume || !outReal ) return TA_BAD_PARAM;
   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 20;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( startIdx > historyLen - 1 )
   {
      *outBegIdx = 0;
      *outNBElement = 0;
      return TA_INSUFFICIENT_HISTORY;
   }

   endIdx = historyLen - 1;
   dummyBegIdx = 0;
   dummyNBElement = 0;
   (void)startIdx; (void)dummyBegIdx; (void)dummyNBElement;

   {
      double sumMFV = 0.0;
      double sumVol = 0.0;
      double high;
      double low;
      double close;
      double tmp;
      double mfv;
      int lookbackTotal;
      int outIdx;
      int i;
      int today;
      /* Both the per-bar money flow volume and the volume that produced it are
       * carried in the circular buffer. Keeping the volume here rather than
       * re-reading inVolume[] at the trailing index is what makes outReal safe to
       * alias any input: once a bar has been consumed it is never read again.
       */
      /* Id, Type, Static Size */
      *outBegIdx= 0;
      *outNBElement= 0;
      /* Identify the minimum number of price bar needed
       * to calculate at least one output.
       */
      lookbackTotal = optInTimePeriod - 1;
      /* Move up the start index if there is not
       * enough initial data.
       */
      if( startIdx < lookbackTotal )
      {
         startIdx = lookbackTotal;
      }
      /* Make sure there is still something to evaluate. */
      if( startIdx > endIdx )
      {
         return TA_INSUFFICIENT_HISTORY;
      }
      if( optInTimePeriod < 1 ) return TA_INTERNAL_ERROR(314);
      if( (int)optInTimePeriod > (int)(sizeof(local_mfv_flow)/sizeof(double)) )
      {
         mfv_flow = TA_Malloc( sizeof(double)*optInTimePeriod );
         if( !mfv_flow )
         {
            return TA_ALLOC_ERR;
         }
         mfv_volume = TA_Malloc( sizeof(double)*optInTimePeriod );
         if( !mfv_volume )
         {
            TA_Free( mfv_flow );
            return TA_ALLOC_ERR;
         }
      }
      else
      {
         mfv_flow = &local_mfv_flow[0];
         mfv_volume = &local_mfv_volume[0];
      }
      maxIdx_mfv = (optInTimePeriod-1);
      mfv_Idx = 0;
      outIdx = 0;
      /* Accumulate the money flow volume and the volume over the first
       * complete window, filling the circular buffer as we go.
       *
       * The per-bar multiplier is written exactly as in ta_AD.c so that the
       * Chaikin money flow volume has one definition in the library.
       */
      today = startIdx - lookbackTotal;
      sumMFV = 0.0;
      sumVol = 0.0;
      for( i = optInTimePeriod; i > 0; i -= 1 )
      {
         high = inHigh[today];
         low = inLow[today];
         close = inClose[today];
         tmp = high - low;
         if( tmp > 0.0 )
         {
            mfv = (close - low - (high - close)) / tmp * inVolume[today];
         } else 
         {
            mfv = 0.0;
         }
         mfv_flow[mfv_Idx] = mfv;
         mfv_volume[mfv_Idx] = inVolume[today];
         sumMFV += mfv;
         sumVol += inVolume[today];
         today += 1;
         mfv_Idx++;
         if( mfv_Idx > maxIdx_mfv ) mfv_Idx = 0;
      }
      /* The first full window is complete: emit its output for startIdx here,
       * then slide the window over the remaining bars below.
       *
       * A window whose volume is entirely zero has no money flow to distribute;
       * report 0.0 rather than propagating a division by zero (issue #112).
       */
      if( sumVol > 0.0 )
      {
         outReal[outIdx++ * outStride] = sumMFV / sumVol;
      } else 
      {
         outReal[outIdx++ * outStride] = 0.0;
      }
      /* Now continue processing the remaining bars. */
      while( today <= endIdx )
      {
         sumMFV -= mfv_flow[mfv_Idx];
         sumVol -= mfv_volume[mfv_Idx];
         high = inHigh[today];
         low = inLow[today];
         close = inClose[today];
         tmp = high - low;
         if( tmp > 0.0 )
         {
            mfv = (close - low - (high - close)) / tmp * inVolume[today];
         } else 
         {
            mfv = 0.0;
         }
         mfv_flow[mfv_Idx] = mfv;
         mfv_volume[mfv_Idx] = inVolume[today];
         sumMFV += mfv;
         sumVol += inVolume[today];
         today += 1;
         if( sumVol > 0.0 )
         {
            outReal[outIdx++ * outStride] = sumMFV / sumVol;
         } else 
         {
            outReal[outIdx++ * outStride] = 0.0;
         }
         mfv_Idx++;
         if( mfv_Idx > maxIdx_mfv ) mfv_Idx = 0;
      }
      *outBegIdx= startIdx;
      *outNBElement= outIdx;

      /* Capture the live batch state into the handle. */
      sp = (struct TA_CMF_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) { if( mfv_flow != &local_mfv_flow[0] ) TA_Free( mfv_flow ); if( mfv_volume != &local_mfv_volume[0] ) TA_Free( mfv_volume ); return TA_ALLOC_ERR; }
      memset( sp, 0, sizeof(*sp) );
      sp->optInTimePeriod = optInTimePeriod;
      sp->sumMFV = sumMFV;
      sp->sumVol = sumVol;
      sp->mfv_Idx = mfv_Idx;
      sp->maxIdx_mfv = maxIdx_mfv;
      sp->cbSize_mfv = maxIdx_mfv + 1;
      if( sp->cbSize_mfv < 1 || sp->cbSize_mfv > historyLen + 1 ) { if( mfv_flow != &local_mfv_flow[0] ) TA_Free( mfv_flow ); if( mfv_volume != &local_mfv_volume[0] ) TA_Free( mfv_volume ); TA_CMF_ReleaseImpl( sp ); return TA_INTERNAL_ERROR(315); }
      sp->cb_mfv_flow = (double *)TA_Malloc( sizeof(double) * (size_t)sp->cbSize_mfv );
      if( !sp->cb_mfv_flow ) { if( mfv_flow != &local_mfv_flow[0] ) TA_Free( mfv_flow ); if( mfv_volume != &local_mfv_volume[0] ) TA_Free( mfv_volume ); TA_CMF_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
      memcpy( sp->cb_mfv_flow, mfv_flow, sizeof(double) * (size_t)sp->cbSize_mfv );
      sp->cb_mfv_volume = (double *)TA_Malloc( sizeof(double) * (size_t)sp->cbSize_mfv );
      if( !sp->cb_mfv_volume ) { if( mfv_flow != &local_mfv_flow[0] ) TA_Free( mfv_flow ); if( mfv_volume != &local_mfv_volume[0] ) TA_Free( mfv_volume ); TA_CMF_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
      memcpy( sp->cb_mfv_volume, mfv_volume, sizeof(double) * (size_t)sp->cbSize_mfv );
      if( mfv_flow != &local_mfv_flow[0] ) TA_Free( mfv_flow ); if( mfv_volume != &local_mfv_volume[0] ) TA_Free( mfv_volume ); 
      sp->outRangeBegIdx = *outBegIdx;
      sp->outRangeCount = *outNBElement;
      sp->cur_outReal = outReal[(*outNBElement - 1) * outStride];
      *stream = sp;
      return TA_SUCCESS;
   }
}

/* Private function, not in public API. */
TA_RetCode TA_CMF_OpenInternal( struct TA_CMF_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], const double inVolume[], int startIdx, int historyLen, int optInTimePeriod, double *outReal )
{
   TA_RetCode retCode;
   int dummyBegIdx = 0;
   int dummyNBElement = 0;
   double sink_outReal = 0.0;
   retCode = TA_CMF_OpenImpl( stream, inHigh, inLow, inClose, inVolume, startIdx, historyLen, optInTimePeriod, &dummyBegIdx, &dummyNBElement, &sink_outReal, 0 );
   if( retCode == TA_SUCCESS )
   {
      *outReal = sink_outReal;
   }
   return retCode;
}

TA_LIB_API TA_RetCode TA_CMF_Open( TA_CMF_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], const double inVolume[], int historyLen, int optInTimePeriod, double *outReal )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !inClose || !inVolume || !outReal ) return TA_BAD_PARAM;
   return TA_CMF_OpenInternal( stream, inHigh, inLow, inClose, inVolume, 0, historyLen, optInTimePeriod, outReal );
}

TA_LIB_API TA_RetCode TA_CMF_OpenAndFill( TA_CMF_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], const double inVolume[], int historyLen, int optInTimePeriod, int *outBegIdx, int *outNBElement, double outReal[] )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !inClose || !inVolume || !outBegIdx || !outNBElement || !outReal ) return TA_BAD_PARAM;
   if( (const void *)outReal == (const void *)inHigh || (const void *)outReal == (const void *)inLow || (const void *)outReal == (const void *)inClose || (const void *)outReal == (const void *)inVolume ) return TA_BAD_PARAM;
   return TA_CMF_OpenAndFillInternal( stream, inHigh, inLow, inClose, inVolume, 0, historyLen, optInTimePeriod, outBegIdx, outNBElement, outReal );
}

/* Private function, not in public API. */
TA_RetCode TA_CMF_OpenAndFillInternal( struct TA_CMF_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], const double inVolume[], int startIdx, int historyLen, int optInTimePeriod, int *outBegIdx, int *outNBElement, double outReal[] )
{
   return TA_CMF_OpenImpl( stream, inHigh, inLow, inClose, inVolume, startIdx, historyLen, optInTimePeriod, outBegIdx, outNBElement, outReal, 1 );
}

TA_LIB_API TA_RetCode TA_CMF_Update( TA_CMF_Stream *stream, double inHigh, double inLow, double inClose, double inVolume, double *outReal )
{
   if( !stream || !outReal ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) || !TA_IS_FINITE( inClose ) || !TA_IS_FINITE( inVolume ) )
   {
      if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
      return TA_BAD_PARAM;
   }
   TA_CMF_StepImpl( stream, inHigh, inLow, inClose, inVolume, outReal );
   if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_CMF_Peek( const TA_CMF_Stream *stream, double inHigh, double inLow, double inClose, double inVolume, double *outReal )
{
   struct TA_CMF_Stream scratch;
   struct TA_CMF_Stream *sp = &scratch;
   double high;
   double low;
   double close;
   double tmp;
   double mfv;
   double sumMFV;
   double sumVol;

   if( !stream || !outReal ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) || !TA_IS_FINITE( inClose ) || !TA_IS_FINITE( inVolume ) ) return TA_BAD_PARAM;
   scratch = *stream;
   sumMFV = sp->sumMFV;
   sumVol = sp->sumVol;
   sumMFV -= sp->cb_mfv_flow[sp->mfv_Idx];
   sumVol -= sp->cb_mfv_volume[sp->mfv_Idx];
   high = inHigh;
   low = inLow;
   close = inClose;
   tmp = high - low;
   if( tmp > 0.0 )
   {
      mfv = (close - low - (high - close)) / tmp * inVolume;
   } else 
   {
      mfv = 0.0;
   }
   sumMFV += mfv;
   sumVol += inVolume;
   if( sumVol > 0.0 )
   {
      *outReal= sumMFV / sumVol;
   } else 
   {
      *outReal= 0.0;
   }
   sp->mfv_Idx = sp->mfv_Idx + 1;
   if( sp->mfv_Idx > sp->maxIdx_mfv )
   {
      sp->mfv_Idx = 0;
   }
   sp->cur_outReal = *outReal;
   sp->sumMFV = sumMFV;
   sp->sumVol = sumVol;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_CMF_UpdateAndFill( TA_CMF_Stream *stream, const double inHigh[], const double inLow[], const double inClose[], const double inVolume[], int barCount, double outReal[] )
{
   int i;

   if( !stream || !inHigh || !inLow || !inClose || !inVolume || !outReal ) return TA_BAD_PARAM;
   if( barCount < 0 ) return TA_BAD_PARAM;
   if( (const void *)outReal == (const void *)inHigh || (const void *)outReal == (const void *)inLow || (const void *)outReal == (const void *)inClose || (const void *)outReal == (const void *)inVolume ) return TA_BAD_PARAM;
   for( i = 0; i < barCount; i++ )
   {
      if( !TA_IS_FINITE( inHigh[i] ) || !TA_IS_FINITE( inLow[i] ) || !TA_IS_FINITE( inClose[i] ) || !TA_IS_FINITE( inVolume[i] ) )
      {
         if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
         return TA_BAD_PARAM;
      }
      TA_CMF_StepImpl( stream, inHigh[i], inLow[i], inClose[i], inVolume[i], &outReal[i] );
      if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   }
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_CMF_Close( TA_CMF_Stream *stream )
{
   TA_CMF_ReleaseImpl( stream );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_CMF_Value( const TA_CMF_Stream *stream, double *outReal )
{
   if( !stream || !outReal ) return TA_BAD_PARAM;
   *outReal = stream->cur_outReal;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_CMF_Clone( const TA_CMF_Stream *stream, TA_CMF_Stream **clone )
{
   struct TA_CMF_Stream *sp;

   if( !clone ) return TA_BAD_PARAM;
   *clone = NULL;
   if( !stream ) return TA_BAD_PARAM;
   sp = (struct TA_CMF_Stream *)TA_Malloc( sizeof(*sp) );
   if( !sp ) return TA_ALLOC_ERR;
   *sp = *stream;
   sp->cb_mfv_flow = NULL;
   sp->cb_mfv_volume = NULL;
   if( stream->cb_mfv_flow )
   { size_t copyN = (size_t)(sp->cbSize_mfv);
     sp->cb_mfv_flow = (double *)TA_Malloc( sizeof(double) * copyN );
     if( !sp->cb_mfv_flow ) { TA_CMF_Close( sp ); return TA_ALLOC_ERR; }
     memcpy( sp->cb_mfv_flow, stream->cb_mfv_flow, sizeof(double) * copyN ); }
   if( stream->cb_mfv_volume )
   { size_t copyN = (size_t)(sp->cbSize_mfv);
     sp->cb_mfv_volume = (double *)TA_Malloc( sizeof(double) * copyN );
     if( !sp->cb_mfv_volume ) { TA_CMF_Close( sp ); return TA_ALLOC_ERR; }
     memcpy( sp->cb_mfv_volume, stream->cb_mfv_volume, sizeof(double) * copyN ); }
   *clone = sp;
   return TA_SUCCESS;
}

