/* TA-LIB Copyright (c) 1999-2026, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_stream_private.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  MF       Mario Fortier
 *  KL       Kevin Lin (@kevinlincg)
 *  CC       Claude Code (AI assistant)
 *
 * Change history:
 *
 *  MMDDYY BY     Description
 *  -------------------------------------------------------------------
 *  093026 KL,CC  Creation (#477).
 */

TA_LIB_API int TA_CKSP_Lookback( int optInTimePeriod, double optInMultiplier, int optInStopPeriod )
{
   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 10;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return -1;
   if( optInMultiplier == TA_REAL_DEFAULT )
      optInMultiplier = 1;
   else if( !(optInMultiplier >= 0e0 && optInMultiplier <= TA_REAL_MAX) )
      return -1;
   if( (int)optInStopPeriod == TA_INTEGER_DEFAULT )
      optInStopPeriod = 9;
   else if( (int)optInStopPeriod < 1 || (int)optInStopPeriod > 100000 )
      return -1;
   /* Two stages. The first needs the Average True Range at its bar and the
    * extreme of the p bars ending there; atr_lookback(p) is p + unst, which is
    * never below max_lookback(p) = p - 1, so it covers both. The second adds
    * the q - 1 earlier first-stage bars its own window reads.
    *
    * The ATR term is written as the callee's lookback and never restated, which
    * is what makes CKSP inherit TA_FUNC_UNST_ATR rather than own an unstable
    * period of its own (supertrend.c:16-25).
    */
   return TA_ATR_Lookback(optInTimePeriod) + (optInStopPeriod - 1);
}

TA_FMA_MULTIVERSION
TA_LIB_API TA_RetCode TA_CKSP( int    startIdx,
                               int    endIdx,
                               const double inHigh[],
                               const double inLow[],
                               const double inClose[],
                               int optInTimePeriod,
                               double optInMultiplier,
                               int optInStopPeriod,
                               int          *outBegIdx,
                               int          *outNBElement,
                               double        outHighStop[],
                               double        outLowStop[] )
{
   int i;
   int jh;
   int jl;
   int kh;
   int kl;
   int today;
   int outIdx;
   int lookbackTotal;
   int stageOneIdx;
   double prevATR;
   double periodTotal;
   double wAlpha;
   double wBeta;
   double val2;
   double val3;
   double greatest;
   double tempCY;
   double tempLT;
   double tempHT;
   double hh;
   double ll;
   double best;
   double local_hRing[50];
   double *hRing = &local_hRing[0];
   int hRing_Idx;
   int maxIdx_hRing;
   double local_lRing[50];
   double *lRing = &local_lRing[0];
   int lRing_Idx;
   int maxIdx_lRing;
   double local_fhRing[50];
   double *fhRing = &local_fhRing[0];
   int fhRing_Idx;
   int maxIdx_fhRing;
   double local_flRing[50];
   double *flRing = &local_flRing[0];
   int flRing_Idx;
   int maxIdx_flRing;

   if( (startIdx < 0) || (startIdx > TA_INDEX_MAX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_INDEX_MAX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 10;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( optInMultiplier == TA_REAL_DEFAULT )
      optInMultiplier = 1;
   else if( !(optInMultiplier >= 0e0 && optInMultiplier <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( (int)optInStopPeriod == TA_INTEGER_DEFAULT )
      optInStopPeriod = 9;
   else if( (int)optInStopPeriod < 1 || (int)optInStopPeriod > 100000 )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !inClose )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outHighStop )
      return TA_BAD_PARAM;
   if( !outLowStop )
      return TA_BAD_PARAM;
   if( outHighStop == outLowStop )
      return TA_BAD_PARAM;

   /* Four windows, all carried as rings and all walked oldest-first, the
    * cci.c:112-117 shape: an index that wrapped would be one more thing the
    * stream derivation has to prove, and the walk is the same values either
    * way.
    */
   *outBegIdx= 0;
   *outNBElement= 0;
   lookbackTotal = TA_CKSP_Lookback(optInTimePeriod,optInMultiplier,optInStopPeriod);
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   if( startIdx > endIdx )
   {
      return TA_SUCCESS;
   }
   if( optInTimePeriod < 1 ) return TA_INTERNAL_ERROR(462);
   if( (int)optInTimePeriod > (int)(sizeof(local_hRing)/sizeof(double)) )
   {
      hRing = TA_Malloc( sizeof(double)*optInTimePeriod );
      if( !hRing )
      {
         return TA_ALLOC_ERR;
      }
   }
   else
   {
      hRing = &local_hRing[0];
   }
   maxIdx_hRing = (optInTimePeriod-1);
   hRing_Idx = 0;
   if( optInTimePeriod < 1 ) return TA_INTERNAL_ERROR(463);
   if( (int)optInTimePeriod > (int)(sizeof(local_lRing)/sizeof(double)) )
   {
      lRing = TA_Malloc( sizeof(double)*optInTimePeriod );
      if( !lRing )
      {
         if( hRing != &local_hRing[0] ) TA_Free( hRing );
         return TA_ALLOC_ERR;
      }
   }
   else
   {
      lRing = &local_lRing[0];
   }
   maxIdx_lRing = (optInTimePeriod-1);
   lRing_Idx = 0;
   if( optInStopPeriod < 1 ) return TA_INTERNAL_ERROR(464);
   if( (int)optInStopPeriod > (int)(sizeof(local_fhRing)/sizeof(double)) )
   {
      fhRing = TA_Malloc( sizeof(double)*optInStopPeriod );
      if( !fhRing )
      {
         if( hRing != &local_hRing[0] ) TA_Free( hRing );
         if( lRing != &local_lRing[0] ) TA_Free( lRing );
         return TA_ALLOC_ERR;
      }
   }
   else
   {
      fhRing = &local_fhRing[0];
   }
   maxIdx_fhRing = (optInStopPeriod-1);
   fhRing_Idx = 0;
   if( optInStopPeriod < 1 ) return TA_INTERNAL_ERROR(465);
   if( (int)optInStopPeriod > (int)(sizeof(local_flRing)/sizeof(double)) )
   {
      flRing = TA_Malloc( sizeof(double)*optInStopPeriod );
      if( !flRing )
      {
         if( hRing != &local_hRing[0] ) TA_Free( hRing );
         if( lRing != &local_lRing[0] ) TA_Free( lRing );
         if( fhRing != &local_fhRing[0] ) TA_Free( fhRing );
         return TA_ALLOC_ERR;
      }
   }
   else
   {
      flRing = &local_flRing[0];
   }
   maxIdx_flRing = (optInStopPeriod-1);
   flRing_Idx = 0;
   /* The first stage is entered q-1 bars before the first output, because the
    * second stage's window reaches that far back. Each leg is anchored on its
    * own bar rather than on the caller's startIdx (the kc.c:73-77 rule): the
    * Average True Range is seeded as if TA_ATR had been entered here, and the
    * extremes are the p-windows ending on these same bars.
    */
   stageOneIdx = startIdx - (optInStopPeriod - 1);
   /* The Average True Range, carried inline rather than taken from a call: the
    * two stages advance together one bar at a time and a whole-range buffer
    * between them would not stream (supertrend.c:47-50).
    *
    * The arithmetic order is the bit-exactness contract with TA_ATR and is not
    * to be reordered: the range first, then the two previous-close distances in
    * that order; the seed summed from 0.0 over the first optInTimePeriod True
    * Ranges and divided once; wBeta rounded first and wAlpha derived from it.
    */
   wBeta = (double)(optInTimePeriod - 1) / (double)optInTimePeriod;
   wAlpha = 1.0 - wBeta;
   today = stageOneIdx - TA_ATR_Lookback(optInTimePeriod) + 1;
   periodTotal = 0.0;
   i = optInTimePeriod;
   while( i-- > 0 )
   {
      tempLT = inLow[today];
      tempHT = inHigh[today];
      tempCY = inClose[today - 1];
      greatest = tempHT - tempLT;
      val2 = fabs(tempCY - tempHT);
      if( val2 > greatest )
      {
         greatest = val2;
      }
      val3 = fabs(tempCY - tempLT);
      if( val3 > greatest )
      {
         greatest = val3;
      }
      periodTotal += greatest;
      today += 1;
   }
   prevATR = periodTotal / optInTimePeriod;
   /* Skip the Average True Range's unstable period. The count comes from the
    * lookback rather than from the setting, so the two cannot disagree.
    */
   i = TA_ATR_Lookback(optInTimePeriod) - optInTimePeriod;
   while( i != 0 )
   {
      tempLT = inLow[today];
      tempHT = inHigh[today];
      tempCY = inClose[today - 1];
      greatest = tempHT - tempLT;
      val2 = fabs(tempCY - tempHT);
      if( val2 > greatest )
      {
         greatest = val2;
      }
      val3 = fabs(tempCY - tempLT);
      if( val3 > greatest )
      {
         greatest = val3;
      }
      prevATR = fma(wBeta, prevATR, wAlpha * greatest);
      today += 1;
      i -= 1;
   }
   /* `today` is now stageOneIdx and prevATR is the Average True Range of the
    * bar before it. Seed the price rings with the p-1 bars the first extreme
    * window needs behind that bar.
    */
   i = stageOneIdx - optInTimePeriod + 1;
   while( i < stageOneIdx )
   {
      hRing[hRing_Idx] = inHigh[i];
      lRing[lRing_Idx] = inLow[i];
      i += 1;
      hRing_Idx++;
      if( hRing_Idx > maxIdx_hRing ) hRing_Idx = 0;
      lRing_Idx++;
      if( lRing_Idx > maxIdx_lRing ) lRing_Idx = 0;
   }
   /* The prologue leaves prevATR as the Average True Range of stageOneIdx and
    * `today` one past it, so that bar is finished here rather than in the loop:
    * entering the loop with it would apply a second Wilder update and shift the
    * whole series one bar early. supertrend.c takes the same step for the same
    * reason.
    */
   today = stageOneIdx;
   hRing[hRing_Idx] = inHigh[today];
   lRing[lRing_Idx] = inLow[today];
   hh = hRing[hRing_Idx];
   for( jh = hRing_Idx + 1; jh < optInTimePeriod; jh += 1 )
   {
      best = hRing[jh];
      if( best > hh )
      {
         hh = best;
      }
   }
   for( jh = 0; jh < hRing_Idx; jh += 1 )
   {
      best = hRing[jh];
      if( best > hh )
      {
         hh = best;
      }
   }
   ll = lRing[lRing_Idx];
   for( jl = lRing_Idx + 1; jl < optInTimePeriod; jl += 1 )
   {
      best = lRing[jl];
      if( best < ll )
      {
         ll = best;
      }
   }
   for( jl = 0; jl < lRing_Idx; jl += 1 )
   {
      best = lRing[jl];
      if( best < ll )
      {
         ll = best;
      }
   }
   fhRing[fhRing_Idx] = hh - optInMultiplier * prevATR;
   flRing[flRing_Idx] = ll + optInMultiplier * prevATR;
   outIdx = 0;
   if( today >= startIdx )
   {
      outHighStop[outIdx] = fhRing[fhRing_Idx];
      outLowStop[outIdx] = flRing[flRing_Idx];
      outIdx = outIdx + 1;
   }
   today += 1;
   hRing_Idx++;
   if( hRing_Idx > maxIdx_hRing ) hRing_Idx = 0;
   lRing_Idx++;
   if( lRing_Idx > maxIdx_lRing ) lRing_Idx = 0;
   fhRing_Idx++;
   if( fhRing_Idx > maxIdx_fhRing ) fhRing_Idx = 0;
   flRing_Idx++;
   if( flRing_Idx > maxIdx_flRing ) flRing_Idx = 0;
   while( today <= endIdx )
   {
      tempLT = inLow[today];
      tempHT = inHigh[today];
      tempCY = inClose[today - 1];
      greatest = tempHT - tempLT;
      val2 = fabs(tempCY - tempHT);
      if( val2 > greatest )
      {
         greatest = val2;
      }
      val3 = fabs(tempCY - tempLT);
      if( val3 > greatest )
      {
         greatest = val3;
      }
      prevATR = fma(wBeta, prevATR, wAlpha * greatest);
      hRing[hRing_Idx] = tempHT;
      lRing[lRing_Idx] = tempLT;
      /* The extremes of the p bars ending here. The newest sits at the ring's
       * own index, so the oldest is the slot after it and the walk is two
       * straight runs.
       */
      hh = hRing[hRing_Idx];
      for( jh = hRing_Idx + 1; jh < optInTimePeriod; jh += 1 )
      {
         best = hRing[jh];
         if( best > hh )
         {
            hh = best;
         }
      }
      for( jh = 0; jh < hRing_Idx; jh += 1 )
      {
         best = hRing[jh];
         if( best > hh )
         {
            hh = best;
         }
      }
      ll = lRing[lRing_Idx];
      for( jl = lRing_Idx + 1; jl < optInTimePeriod; jl += 1 )
      {
         best = lRing[jl];
         if( best < ll )
         {
            ll = best;
         }
      }
      for( jl = 0; jl < lRing_Idx; jl += 1 )
      {
         best = lRing[jl];
         if( best < ll )
         {
            ll = best;
         }
      }
      fhRing[fhRing_Idx] = hh - optInMultiplier * prevATR;
      flRing[flRing_Idx] = ll + optInMultiplier * prevATR;
      if( today >= startIdx )
      {
         /* The second stage, over the q first-stage bars ending here. At q = 1
          * both runs are empty and the value is the bar's own, which is the
          * Chandelier Exit form.
          */
         hh = fhRing[fhRing_Idx];
         for( kh = fhRing_Idx + 1; kh < optInStopPeriod; kh += 1 )
         {
            best = fhRing[kh];
            if( best > hh )
            {
               hh = best;
            }
         }
         for( kh = 0; kh < fhRing_Idx; kh += 1 )
         {
            best = fhRing[kh];
            if( best > hh )
            {
               hh = best;
            }
         }
         ll = flRing[flRing_Idx];
         for( kl = flRing_Idx + 1; kl < optInStopPeriod; kl += 1 )
         {
            best = flRing[kl];
            if( best < ll )
            {
               ll = best;
            }
         }
         for( kl = 0; kl < flRing_Idx; kl += 1 )
         {
            best = flRing[kl];
            if( best < ll )
            {
               ll = best;
            }
         }
         outHighStop[outIdx] = hh;
         outLowStop[outIdx] = ll;
         outIdx = outIdx + 1;
      }
      today += 1;
      hRing_Idx++;
      if( hRing_Idx > maxIdx_hRing ) hRing_Idx = 0;
      lRing_Idx++;
      if( lRing_Idx > maxIdx_lRing ) lRing_Idx = 0;
      fhRing_Idx++;
      if( fhRing_Idx > maxIdx_fhRing ) fhRing_Idx = 0;
      flRing_Idx++;
      if( flRing_Idx > maxIdx_flRing ) flRing_Idx = 0;
   }
   if( flRing != &local_flRing[0] ) { TA_Free( flRing ); flRing = &local_flRing[0]; }
   if( fhRing != &local_fhRing[0] ) { TA_Free( fhRing ); fhRing = &local_fhRing[0]; }
   if( lRing != &local_lRing[0] ) { TA_Free( lRing ); lRing = &local_lRing[0]; }
   if( hRing != &local_hRing[0] ) { TA_Free( hRing ); hRing = &local_hRing[0]; }
   *outNBElement= outIdx;
   *outBegIdx= startIdx;
   return TA_SUCCESS;
}

TA_FMA_MULTIVERSION
TA_RetCode TA_S_CKSP( int    startIdx,
                      int    endIdx,
                      const float inHigh[],
                      const float inLow[],
                      const float inClose[],
                      int optInTimePeriod,
                      double optInMultiplier,
                      int optInStopPeriod,
                      int          *outBegIdx,
                      int          *outNBElement,
                      double        outHighStop[],
                      double        outLowStop[] )
{
   int i;
   int jh;
   int jl;
   int kh;
   int kl;
   int today;
   int outIdx;
   int lookbackTotal;
   int stageOneIdx;
   double prevATR;
   double periodTotal;
   double wAlpha;
   double wBeta;
   double val2;
   double val3;
   double greatest;
   double tempCY;
   double tempLT;
   double tempHT;
   double hh;
   double ll;
   double best;
   double local_hRing[50];
   double *hRing = &local_hRing[0];
   int hRing_Idx;
   int maxIdx_hRing;
   double local_lRing[50];
   double *lRing = &local_lRing[0];
   int lRing_Idx;
   int maxIdx_lRing;
   double local_fhRing[50];
   double *fhRing = &local_fhRing[0];
   int fhRing_Idx;
   int maxIdx_fhRing;
   double local_flRing[50];
   double *flRing = &local_flRing[0];
   int flRing_Idx;
   int maxIdx_flRing;

   if( (startIdx < 0) || (startIdx > TA_INDEX_MAX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_INDEX_MAX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 10;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( optInMultiplier == TA_REAL_DEFAULT )
      optInMultiplier = 1;
   else if( !(optInMultiplier >= 0e0 && optInMultiplier <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( (int)optInStopPeriod == TA_INTEGER_DEFAULT )
      optInStopPeriod = 9;
   else if( (int)optInStopPeriod < 1 || (int)optInStopPeriod > 100000 )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !inClose )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outHighStop )
      return TA_BAD_PARAM;
   if( !outLowStop )
      return TA_BAD_PARAM;
   if( outHighStop == outLowStop )
      return TA_BAD_PARAM;

   *outBegIdx= 0;
   *outNBElement= 0;
   lookbackTotal = TA_CKSP_Lookback(optInTimePeriod,optInMultiplier,optInStopPeriod);
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   if( startIdx > endIdx )
   {
      return TA_SUCCESS;
   }
   if( optInTimePeriod < 1 ) return TA_INTERNAL_ERROR(462);
   if( (int)optInTimePeriod > (int)(sizeof(local_hRing)/sizeof(double)) )
   {
      hRing = TA_Malloc( sizeof(double)*optInTimePeriod );
      if( !hRing )
      {
         return TA_ALLOC_ERR;
      }
   }
   else
   {
      hRing = &local_hRing[0];
   }
   maxIdx_hRing = (optInTimePeriod-1);
   hRing_Idx = 0;
   if( optInTimePeriod < 1 ) return TA_INTERNAL_ERROR(463);
   if( (int)optInTimePeriod > (int)(sizeof(local_lRing)/sizeof(double)) )
   {
      lRing = TA_Malloc( sizeof(double)*optInTimePeriod );
      if( !lRing )
      {
         if( hRing != &local_hRing[0] ) TA_Free( hRing );
         return TA_ALLOC_ERR;
      }
   }
   else
   {
      lRing = &local_lRing[0];
   }
   maxIdx_lRing = (optInTimePeriod-1);
   lRing_Idx = 0;
   if( optInStopPeriod < 1 ) return TA_INTERNAL_ERROR(464);
   if( (int)optInStopPeriod > (int)(sizeof(local_fhRing)/sizeof(double)) )
   {
      fhRing = TA_Malloc( sizeof(double)*optInStopPeriod );
      if( !fhRing )
      {
         if( hRing != &local_hRing[0] ) TA_Free( hRing );
         if( lRing != &local_lRing[0] ) TA_Free( lRing );
         return TA_ALLOC_ERR;
      }
   }
   else
   {
      fhRing = &local_fhRing[0];
   }
   maxIdx_fhRing = (optInStopPeriod-1);
   fhRing_Idx = 0;
   if( optInStopPeriod < 1 ) return TA_INTERNAL_ERROR(465);
   if( (int)optInStopPeriod > (int)(sizeof(local_flRing)/sizeof(double)) )
   {
      flRing = TA_Malloc( sizeof(double)*optInStopPeriod );
      if( !flRing )
      {
         if( hRing != &local_hRing[0] ) TA_Free( hRing );
         if( lRing != &local_lRing[0] ) TA_Free( lRing );
         if( fhRing != &local_fhRing[0] ) TA_Free( fhRing );
         return TA_ALLOC_ERR;
      }
   }
   else
   {
      flRing = &local_flRing[0];
   }
   maxIdx_flRing = (optInStopPeriod-1);
   flRing_Idx = 0;
   stageOneIdx = startIdx - (optInStopPeriod - 1);
   wBeta = (double)(optInTimePeriod - 1) / (double)optInTimePeriod;
   wAlpha = 1.0 - wBeta;
   today = stageOneIdx - TA_ATR_Lookback(optInTimePeriod) + 1;
   periodTotal = 0.0;
   i = optInTimePeriod;
   while( i-- > 0 )
   {
      tempLT = (double)inLow[today];
      tempHT = (double)inHigh[today];
      tempCY = (double)inClose[today - 1];
      greatest = tempHT - tempLT;
      val2 = fabs(tempCY - tempHT);
      if( val2 > greatest )
      {
         greatest = val2;
      }
      val3 = fabs(tempCY - tempLT);
      if( val3 > greatest )
      {
         greatest = val3;
      }
      periodTotal += greatest;
      today += 1;
   }
   prevATR = periodTotal / optInTimePeriod;
   i = TA_ATR_Lookback(optInTimePeriod) - optInTimePeriod;
   while( i != 0 )
   {
      tempLT = (double)inLow[today];
      tempHT = (double)inHigh[today];
      tempCY = (double)inClose[today - 1];
      greatest = tempHT - tempLT;
      val2 = fabs(tempCY - tempHT);
      if( val2 > greatest )
      {
         greatest = val2;
      }
      val3 = fabs(tempCY - tempLT);
      if( val3 > greatest )
      {
         greatest = val3;
      }
      prevATR = fma(wBeta, prevATR, wAlpha * greatest);
      today += 1;
      i -= 1;
   }
   i = stageOneIdx - optInTimePeriod + 1;
   while( i < stageOneIdx )
   {
      hRing[hRing_Idx] = (double)inHigh[i];
      lRing[lRing_Idx] = (double)inLow[i];
      i += 1;
      hRing_Idx++;
      if( hRing_Idx > maxIdx_hRing ) hRing_Idx = 0;
      lRing_Idx++;
      if( lRing_Idx > maxIdx_lRing ) lRing_Idx = 0;
   }
   today = stageOneIdx;
   hRing[hRing_Idx] = (double)inHigh[today];
   lRing[lRing_Idx] = (double)inLow[today];
   hh = hRing[hRing_Idx];
   for( jh = hRing_Idx + 1; jh < optInTimePeriod; jh += 1 )
   {
      best = hRing[jh];
      if( best > hh )
      {
         hh = best;
      }
   }
   for( jh = 0; jh < hRing_Idx; jh += 1 )
   {
      best = hRing[jh];
      if( best > hh )
      {
         hh = best;
      }
   }
   ll = lRing[lRing_Idx];
   for( jl = lRing_Idx + 1; jl < optInTimePeriod; jl += 1 )
   {
      best = lRing[jl];
      if( best < ll )
      {
         ll = best;
      }
   }
   for( jl = 0; jl < lRing_Idx; jl += 1 )
   {
      best = lRing[jl];
      if( best < ll )
      {
         ll = best;
      }
   }
   fhRing[fhRing_Idx] = hh - optInMultiplier * prevATR;
   flRing[flRing_Idx] = ll + optInMultiplier * prevATR;
   outIdx = 0;
   if( today >= startIdx )
   {
      outHighStop[outIdx] = fhRing[fhRing_Idx];
      outLowStop[outIdx] = flRing[flRing_Idx];
      outIdx = outIdx + 1;
   }
   today += 1;
   hRing_Idx++;
   if( hRing_Idx > maxIdx_hRing ) hRing_Idx = 0;
   lRing_Idx++;
   if( lRing_Idx > maxIdx_lRing ) lRing_Idx = 0;
   fhRing_Idx++;
   if( fhRing_Idx > maxIdx_fhRing ) fhRing_Idx = 0;
   flRing_Idx++;
   if( flRing_Idx > maxIdx_flRing ) flRing_Idx = 0;
   while( today <= endIdx )
   {
      tempLT = (double)inLow[today];
      tempHT = (double)inHigh[today];
      tempCY = (double)inClose[today - 1];
      greatest = tempHT - tempLT;
      val2 = fabs(tempCY - tempHT);
      if( val2 > greatest )
      {
         greatest = val2;
      }
      val3 = fabs(tempCY - tempLT);
      if( val3 > greatest )
      {
         greatest = val3;
      }
      prevATR = fma(wBeta, prevATR, wAlpha * greatest);
      hRing[hRing_Idx] = tempHT;
      lRing[lRing_Idx] = tempLT;
      hh = hRing[hRing_Idx];
      for( jh = hRing_Idx + 1; jh < optInTimePeriod; jh += 1 )
      {
         best = hRing[jh];
         if( best > hh )
         {
            hh = best;
         }
      }
      for( jh = 0; jh < hRing_Idx; jh += 1 )
      {
         best = hRing[jh];
         if( best > hh )
         {
            hh = best;
         }
      }
      ll = lRing[lRing_Idx];
      for( jl = lRing_Idx + 1; jl < optInTimePeriod; jl += 1 )
      {
         best = lRing[jl];
         if( best < ll )
         {
            ll = best;
         }
      }
      for( jl = 0; jl < lRing_Idx; jl += 1 )
      {
         best = lRing[jl];
         if( best < ll )
         {
            ll = best;
         }
      }
      fhRing[fhRing_Idx] = hh - optInMultiplier * prevATR;
      flRing[flRing_Idx] = ll + optInMultiplier * prevATR;
      if( today >= startIdx )
      {
         hh = fhRing[fhRing_Idx];
         for( kh = fhRing_Idx + 1; kh < optInStopPeriod; kh += 1 )
         {
            best = fhRing[kh];
            if( best > hh )
            {
               hh = best;
            }
         }
         for( kh = 0; kh < fhRing_Idx; kh += 1 )
         {
            best = fhRing[kh];
            if( best > hh )
            {
               hh = best;
            }
         }
         ll = flRing[flRing_Idx];
         for( kl = flRing_Idx + 1; kl < optInStopPeriod; kl += 1 )
         {
            best = flRing[kl];
            if( best < ll )
            {
               ll = best;
            }
         }
         for( kl = 0; kl < flRing_Idx; kl += 1 )
         {
            best = flRing[kl];
            if( best < ll )
            {
               ll = best;
            }
         }
         outHighStop[outIdx] = hh;
         outLowStop[outIdx] = ll;
         outIdx = outIdx + 1;
      }
      today += 1;
      hRing_Idx++;
      if( hRing_Idx > maxIdx_hRing ) hRing_Idx = 0;
      lRing_Idx++;
      if( lRing_Idx > maxIdx_lRing ) lRing_Idx = 0;
      fhRing_Idx++;
      if( fhRing_Idx > maxIdx_fhRing ) fhRing_Idx = 0;
      flRing_Idx++;
      if( flRing_Idx > maxIdx_flRing ) flRing_Idx = 0;
   }
   if( flRing != &local_flRing[0] ) { TA_Free( flRing ); flRing = &local_flRing[0]; }
   if( fhRing != &local_fhRing[0] ) { TA_Free( fhRing ); fhRing = &local_fhRing[0]; }
   if( lRing != &local_lRing[0] ) { TA_Free( lRing ); lRing = &local_lRing[0]; }
   if( hRing != &local_hRing[0] ) { TA_Free( hRing ); hRing = &local_hRing[0]; }
   *outNBElement= outIdx;
   *outBegIdx= startIdx;
   return TA_SUCCESS;
}

/**** Streaming API *****/

struct TA_CKSP_Stream {
   /* The bars this handle has an output for (see TA_CKSP_OutRange). */
   int outRangeBegIdx;
   int outRangeCount;
   /* The value(s) at the last bar the stream counted (see TA_CKSP_Value). */
   double cur_outHighStop;
   double cur_outLowStop;
   int optInTimePeriod;
   double optInMultiplier;
   int optInStopPeriod;
   double prevATR;
   double pad_0;
   double wAlpha;
   double wBeta;
   int hRing_Idx;
   int lRing_Idx;
   int fhRing_Idx;
   int flRing_Idx;
   int maxIdx_hRing;
   int maxIdx_lRing;
   int maxIdx_fhRing;
   int maxIdx_flRing;
   double lag1_inClose;
   int cbSize_hRing;
   double *cb_hRing;
   int cbSize_lRing;
   double *cb_lRing;
   int cbSize_fhRing;
   double *cb_fhRing;
   int cbSize_flRing;
   double *cb_flRing;
};

/* Private function, not in public API. */
static void TA_CKSP_ReleaseImpl( struct TA_CKSP_Stream *sp )
{
   if( !sp ) return;
   if( sp->cb_hRing ) TA_Free( sp->cb_hRing );
   if( sp->cb_lRing ) TA_Free( sp->cb_lRing );
   if( sp->cb_fhRing ) TA_Free( sp->cb_fhRing );
   if( sp->cb_flRing ) TA_Free( sp->cb_flRing );
   TA_Free( sp );
}

/* Private function, not in public API. */
static TA_FMA_STEP_INLINE void TA_CKSP_StepImpl( struct TA_CKSP_Stream *sp, double inHigh, double inLow, double inClose, double *outHighStop, double *outLowStop )
{
   int jh;
   int jl;
   int kh;
   int kl;
   double val2;
   double val3;
   double greatest;
   double tempCY;
   double tempLT;
   double tempHT;
   double hh;
   double ll;
   double best;
   double prevATR;

   prevATR = sp->prevATR;
   tempLT = inLow;
   tempHT = inHigh;
   tempCY = sp->lag1_inClose;
   greatest = tempHT - tempLT;
   val2 = fabs(tempCY - tempHT);
   if( val2 > greatest )
   {
      greatest = val2;
   }
   val3 = fabs(tempCY - tempLT);
   if( val3 > greatest )
   {
      greatest = val3;
   }
   prevATR = fma(sp->wBeta, prevATR, sp->wAlpha * greatest);
   sp->cb_hRing[sp->hRing_Idx] = tempHT;
   sp->cb_lRing[sp->lRing_Idx] = tempLT;
   /* The extremes of the p bars ending here. The newest sits at the ring's
    * own index, so the oldest is the slot after it and the walk is two
    * straight runs.
    */
   hh = sp->cb_hRing[sp->hRing_Idx];
   for( jh = sp->hRing_Idx + 1; jh < sp->optInTimePeriod; jh += 1 )
   {
      best = sp->cb_hRing[jh];
      if( best > hh )
      {
         hh = best;
      }
   }
   for( jh = 0; jh < sp->hRing_Idx; jh += 1 )
   {
      best = sp->cb_hRing[jh];
      if( best > hh )
      {
         hh = best;
      }
   }
   ll = sp->cb_lRing[sp->lRing_Idx];
   for( jl = sp->lRing_Idx + 1; jl < sp->optInTimePeriod; jl += 1 )
   {
      best = sp->cb_lRing[jl];
      if( best < ll )
      {
         ll = best;
      }
   }
   for( jl = 0; jl < sp->lRing_Idx; jl += 1 )
   {
      best = sp->cb_lRing[jl];
      if( best < ll )
      {
         ll = best;
      }
   }
   sp->cb_fhRing[sp->fhRing_Idx] = hh - sp->optInMultiplier * prevATR;
   sp->cb_flRing[sp->flRing_Idx] = ll + sp->optInMultiplier * prevATR;
   /* The second stage, over the q first-stage bars ending here. At q = 1
    * both runs are empty and the value is the bar's own, which is the
    * Chandelier Exit form.
    */
   hh = sp->cb_fhRing[sp->fhRing_Idx];
   for( kh = sp->fhRing_Idx + 1; kh < sp->optInStopPeriod; kh += 1 )
   {
      best = sp->cb_fhRing[kh];
      if( best > hh )
      {
         hh = best;
      }
   }
   for( kh = 0; kh < sp->fhRing_Idx; kh += 1 )
   {
      best = sp->cb_fhRing[kh];
      if( best > hh )
      {
         hh = best;
      }
   }
   ll = sp->cb_flRing[sp->flRing_Idx];
   for( kl = sp->flRing_Idx + 1; kl < sp->optInStopPeriod; kl += 1 )
   {
      best = sp->cb_flRing[kl];
      if( best < ll )
      {
         ll = best;
      }
   }
   for( kl = 0; kl < sp->flRing_Idx; kl += 1 )
   {
      best = sp->cb_flRing[kl];
      if( best < ll )
      {
         ll = best;
      }
   }
   *outHighStop= hh;
   *outLowStop= ll;
   sp->hRing_Idx = sp->hRing_Idx + 1;
   if( sp->hRing_Idx > sp->maxIdx_hRing )
   {
      sp->hRing_Idx = 0;
   }
   sp->lRing_Idx = sp->lRing_Idx + 1;
   if( sp->lRing_Idx > sp->maxIdx_lRing )
   {
      sp->lRing_Idx = 0;
   }
   sp->fhRing_Idx = sp->fhRing_Idx + 1;
   if( sp->fhRing_Idx > sp->maxIdx_fhRing )
   {
      sp->fhRing_Idx = 0;
   }
   sp->flRing_Idx = sp->flRing_Idx + 1;
   if( sp->flRing_Idx > sp->maxIdx_flRing )
   {
      sp->flRing_Idx = 0;
   }
   sp->cur_outHighStop = *outHighStop;
   sp->cur_outLowStop = *outLowStop;
   sp->lag1_inClose = inClose;
   sp->prevATR = prevATR;
}

static TA_RetCode TA_CKSP_OpenImpl( struct TA_CKSP_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], int startIdx, int historyLen, int optInTimePeriod, double optInMultiplier, int optInStopPeriod, int *outBegIdx, int *outNBElement, double outHighStop[], double outLowStop[], int outStride )
{
   struct TA_CKSP_Stream *sp;
   double local_hRing[50];
   double *hRing;
   int hRing_Idx;
   int maxIdx_hRing;
   double local_lRing[50];
   double *lRing;
   int lRing_Idx;
   int maxIdx_lRing;
   double local_fhRing[50];
   double *fhRing;
   int fhRing_Idx;
   int maxIdx_fhRing;
   double local_flRing[50];
   double *flRing;
   int flRing_Idx;
   int maxIdx_flRing;
   int endIdx;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_INDEX_MAX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !inClose || !outHighStop || !outLowStop ) return TA_BAD_PARAM;
   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 10;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( optInMultiplier == TA_REAL_DEFAULT )
      optInMultiplier = 1;
   else if( !(optInMultiplier >= 0e0 && optInMultiplier <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( (int)optInStopPeriod == TA_INTEGER_DEFAULT )
      optInStopPeriod = 9;
   else if( (int)optInStopPeriod < 1 || (int)optInStopPeriod > 100000 )
      return TA_BAD_PARAM;
   if( startIdx > historyLen - 1 )
   {
      *outBegIdx = 0;
      *outNBElement = 0;
      return TA_INSUFFICIENT_HISTORY;
   }

   endIdx = historyLen - 1;

   {
      int i;
      int jh;
      int jl;
      int kh;
      int kl;
      int today;
      int outIdx;
      int lookbackTotal;
      int stageOneIdx;
      double prevATR = 0.0;
      double periodTotal;
      double wAlpha = 0.0;
      double wBeta = 0.0;
      double val2;
      double val3;
      double greatest;
      double tempCY;
      double tempLT;
      double tempHT;
      double hh;
      double ll;
      double best;
      /* Four windows, all carried as rings and all walked oldest-first, the
       * cci.c:112-117 shape: an index that wrapped would be one more thing the
       * stream derivation has to prove, and the walk is the same values either
       * way.
       */
      *outBegIdx= 0;
      *outNBElement= 0;
      lookbackTotal = TA_CKSP_Lookback(optInTimePeriod,optInMultiplier,optInStopPeriod);
      if( startIdx < lookbackTotal )
      {
         startIdx = lookbackTotal;
      }
      if( startIdx > endIdx )
      {
         return TA_INSUFFICIENT_HISTORY;
      }
      if( optInTimePeriod < 1 ) return TA_INTERNAL_ERROR(462);
      if( (int)optInTimePeriod > (int)(sizeof(local_hRing)/sizeof(double)) )
      {
         hRing = TA_Malloc( sizeof(double)*optInTimePeriod );
         if( !hRing )
         {
            return TA_ALLOC_ERR;
         }
      }
      else
      {
         hRing = &local_hRing[0];
      }
      maxIdx_hRing = (optInTimePeriod-1);
      hRing_Idx = 0;
      if( optInTimePeriod < 1 ) return TA_INTERNAL_ERROR(463);
      if( (int)optInTimePeriod > (int)(sizeof(local_lRing)/sizeof(double)) )
      {
         lRing = TA_Malloc( sizeof(double)*optInTimePeriod );
         if( !lRing )
         {
            if( hRing != &local_hRing[0] ) TA_Free( hRing );
            return TA_ALLOC_ERR;
         }
      }
      else
      {
         lRing = &local_lRing[0];
      }
      maxIdx_lRing = (optInTimePeriod-1);
      lRing_Idx = 0;
      if( optInStopPeriod < 1 ) return TA_INTERNAL_ERROR(464);
      if( (int)optInStopPeriod > (int)(sizeof(local_fhRing)/sizeof(double)) )
      {
         fhRing = TA_Malloc( sizeof(double)*optInStopPeriod );
         if( !fhRing )
         {
            if( hRing != &local_hRing[0] ) TA_Free( hRing );
            if( lRing != &local_lRing[0] ) TA_Free( lRing );
            return TA_ALLOC_ERR;
         }
      }
      else
      {
         fhRing = &local_fhRing[0];
      }
      maxIdx_fhRing = (optInStopPeriod-1);
      fhRing_Idx = 0;
      if( optInStopPeriod < 1 ) return TA_INTERNAL_ERROR(465);
      if( (int)optInStopPeriod > (int)(sizeof(local_flRing)/sizeof(double)) )
      {
         flRing = TA_Malloc( sizeof(double)*optInStopPeriod );
         if( !flRing )
         {
            if( hRing != &local_hRing[0] ) TA_Free( hRing );
            if( lRing != &local_lRing[0] ) TA_Free( lRing );
            if( fhRing != &local_fhRing[0] ) TA_Free( fhRing );
            return TA_ALLOC_ERR;
         }
      }
      else
      {
         flRing = &local_flRing[0];
      }
      maxIdx_flRing = (optInStopPeriod-1);
      flRing_Idx = 0;
      /* The first stage is entered q-1 bars before the first output, because the
       * second stage's window reaches that far back. Each leg is anchored on its
       * own bar rather than on the caller's startIdx (the kc.c:73-77 rule): the
       * Average True Range is seeded as if TA_ATR had been entered here, and the
       * extremes are the p-windows ending on these same bars.
       */
      stageOneIdx = startIdx - (optInStopPeriod - 1);
      /* The Average True Range, carried inline rather than taken from a call: the
       * two stages advance together one bar at a time and a whole-range buffer
       * between them would not stream (supertrend.c:47-50).
       *
       * The arithmetic order is the bit-exactness contract with TA_ATR and is not
       * to be reordered: the range first, then the two previous-close distances in
       * that order; the seed summed from 0.0 over the first optInTimePeriod True
       * Ranges and divided once; wBeta rounded first and wAlpha derived from it.
       */
      wBeta = (double)(optInTimePeriod - 1) / (double)optInTimePeriod;
      wAlpha = 1.0 - wBeta;
      today = stageOneIdx - TA_ATR_Lookback(optInTimePeriod) + 1;
      periodTotal = 0.0;
      i = optInTimePeriod;
      while( i-- > 0 )
      {
         tempLT = inLow[today];
         tempHT = inHigh[today];
         tempCY = inClose[today - 1];
         greatest = tempHT - tempLT;
         val2 = fabs(tempCY - tempHT);
         if( val2 > greatest )
         {
            greatest = val2;
         }
         val3 = fabs(tempCY - tempLT);
         if( val3 > greatest )
         {
            greatest = val3;
         }
         periodTotal += greatest;
         today += 1;
      }
      prevATR = periodTotal / optInTimePeriod;
      /* Skip the Average True Range's unstable period. The count comes from the
       * lookback rather than from the setting, so the two cannot disagree.
       */
      i = TA_ATR_Lookback(optInTimePeriod) - optInTimePeriod;
      while( i != 0 )
      {
         tempLT = inLow[today];
         tempHT = inHigh[today];
         tempCY = inClose[today - 1];
         greatest = tempHT - tempLT;
         val2 = fabs(tempCY - tempHT);
         if( val2 > greatest )
         {
            greatest = val2;
         }
         val3 = fabs(tempCY - tempLT);
         if( val3 > greatest )
         {
            greatest = val3;
         }
         prevATR = fma(wBeta, prevATR, wAlpha * greatest);
         today += 1;
         i -= 1;
      }
      /* `today` is now stageOneIdx and prevATR is the Average True Range of the
       * bar before it. Seed the price rings with the p-1 bars the first extreme
       * window needs behind that bar.
       */
      i = stageOneIdx - optInTimePeriod + 1;
      while( i < stageOneIdx )
      {
         hRing[hRing_Idx] = inHigh[i];
         lRing[lRing_Idx] = inLow[i];
         i += 1;
         hRing_Idx++;
         if( hRing_Idx > maxIdx_hRing ) hRing_Idx = 0;
         lRing_Idx++;
         if( lRing_Idx > maxIdx_lRing ) lRing_Idx = 0;
      }
      /* The prologue leaves prevATR as the Average True Range of stageOneIdx and
       * `today` one past it, so that bar is finished here rather than in the loop:
       * entering the loop with it would apply a second Wilder update and shift the
       * whole series one bar early. supertrend.c takes the same step for the same
       * reason.
       */
      today = stageOneIdx;
      hRing[hRing_Idx] = inHigh[today];
      lRing[lRing_Idx] = inLow[today];
      hh = hRing[hRing_Idx];
      for( jh = hRing_Idx + 1; jh < optInTimePeriod; jh += 1 )
      {
         best = hRing[jh];
         if( best > hh )
         {
            hh = best;
         }
      }
      for( jh = 0; jh < hRing_Idx; jh += 1 )
      {
         best = hRing[jh];
         if( best > hh )
         {
            hh = best;
         }
      }
      ll = lRing[lRing_Idx];
      for( jl = lRing_Idx + 1; jl < optInTimePeriod; jl += 1 )
      {
         best = lRing[jl];
         if( best < ll )
         {
            ll = best;
         }
      }
      for( jl = 0; jl < lRing_Idx; jl += 1 )
      {
         best = lRing[jl];
         if( best < ll )
         {
            ll = best;
         }
      }
      fhRing[fhRing_Idx] = hh - optInMultiplier * prevATR;
      flRing[flRing_Idx] = ll + optInMultiplier * prevATR;
      outIdx = 0;
      if( today >= startIdx )
      {
         outHighStop[outIdx * outStride] = fhRing[fhRing_Idx];
         outLowStop[outIdx * outStride] = flRing[flRing_Idx];
         outIdx = outIdx + 1;
      }
      today += 1;
      hRing_Idx++;
      if( hRing_Idx > maxIdx_hRing ) hRing_Idx = 0;
      lRing_Idx++;
      if( lRing_Idx > maxIdx_lRing ) lRing_Idx = 0;
      fhRing_Idx++;
      if( fhRing_Idx > maxIdx_fhRing ) fhRing_Idx = 0;
      flRing_Idx++;
      if( flRing_Idx > maxIdx_flRing ) flRing_Idx = 0;
      while( today <= endIdx )
      {
         tempLT = inLow[today];
         tempHT = inHigh[today];
         tempCY = inClose[today - 1];
         greatest = tempHT - tempLT;
         val2 = fabs(tempCY - tempHT);
         if( val2 > greatest )
         {
            greatest = val2;
         }
         val3 = fabs(tempCY - tempLT);
         if( val3 > greatest )
         {
            greatest = val3;
         }
         prevATR = fma(wBeta, prevATR, wAlpha * greatest);
         hRing[hRing_Idx] = tempHT;
         lRing[lRing_Idx] = tempLT;
         /* The extremes of the p bars ending here. The newest sits at the ring's
          * own index, so the oldest is the slot after it and the walk is two
          * straight runs.
          */
         hh = hRing[hRing_Idx];
         for( jh = hRing_Idx + 1; jh < optInTimePeriod; jh += 1 )
         {
            best = hRing[jh];
            if( best > hh )
            {
               hh = best;
            }
         }
         for( jh = 0; jh < hRing_Idx; jh += 1 )
         {
            best = hRing[jh];
            if( best > hh )
            {
               hh = best;
            }
         }
         ll = lRing[lRing_Idx];
         for( jl = lRing_Idx + 1; jl < optInTimePeriod; jl += 1 )
         {
            best = lRing[jl];
            if( best < ll )
            {
               ll = best;
            }
         }
         for( jl = 0; jl < lRing_Idx; jl += 1 )
         {
            best = lRing[jl];
            if( best < ll )
            {
               ll = best;
            }
         }
         fhRing[fhRing_Idx] = hh - optInMultiplier * prevATR;
         flRing[flRing_Idx] = ll + optInMultiplier * prevATR;
         if( today >= startIdx )
         {
            /* The second stage, over the q first-stage bars ending here. At q = 1
             * both runs are empty and the value is the bar's own, which is the
             * Chandelier Exit form.
             */
            hh = fhRing[fhRing_Idx];
            for( kh = fhRing_Idx + 1; kh < optInStopPeriod; kh += 1 )
            {
               best = fhRing[kh];
               if( best > hh )
               {
                  hh = best;
               }
            }
            for( kh = 0; kh < fhRing_Idx; kh += 1 )
            {
               best = fhRing[kh];
               if( best > hh )
               {
                  hh = best;
               }
            }
            ll = flRing[flRing_Idx];
            for( kl = flRing_Idx + 1; kl < optInStopPeriod; kl += 1 )
            {
               best = flRing[kl];
               if( best < ll )
               {
                  ll = best;
               }
            }
            for( kl = 0; kl < flRing_Idx; kl += 1 )
            {
               best = flRing[kl];
               if( best < ll )
               {
                  ll = best;
               }
            }
            outHighStop[outIdx * outStride] = hh;
            outLowStop[outIdx * outStride] = ll;
            outIdx = outIdx + 1;
         }
         today += 1;
         hRing_Idx++;
         if( hRing_Idx > maxIdx_hRing ) hRing_Idx = 0;
         lRing_Idx++;
         if( lRing_Idx > maxIdx_lRing ) lRing_Idx = 0;
         fhRing_Idx++;
         if( fhRing_Idx > maxIdx_fhRing ) fhRing_Idx = 0;
         flRing_Idx++;
         if( flRing_Idx > maxIdx_flRing ) flRing_Idx = 0;
      }
      *outNBElement= outIdx;
      *outBegIdx= startIdx;

      /* Capture the live batch state into the handle. */
      sp = (struct TA_CKSP_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) { if( hRing != &local_hRing[0] ) { TA_Free( hRing ); } if( lRing != &local_lRing[0] ) { TA_Free( lRing ); } if( fhRing != &local_fhRing[0] ) { TA_Free( fhRing ); } if( flRing != &local_flRing[0] ) { TA_Free( flRing ); } return TA_ALLOC_ERR; }
      memset( sp, 0, sizeof(*sp) );
      sp->optInTimePeriod = optInTimePeriod;
      sp->optInMultiplier = optInMultiplier;
      sp->optInStopPeriod = optInStopPeriod;
      sp->prevATR = prevATR;
      sp->wAlpha = wAlpha;
      sp->wBeta = wBeta;
      sp->hRing_Idx = hRing_Idx;
      sp->lRing_Idx = lRing_Idx;
      sp->fhRing_Idx = fhRing_Idx;
      sp->flRing_Idx = flRing_Idx;
      sp->maxIdx_hRing = maxIdx_hRing;
      sp->maxIdx_lRing = maxIdx_lRing;
      sp->maxIdx_fhRing = maxIdx_fhRing;
      sp->maxIdx_flRing = maxIdx_flRing;
      sp->lag1_inClose = inClose[historyLen - 1];
      sp->cbSize_hRing = maxIdx_hRing + 1;
      if( sp->cbSize_hRing < 1 || sp->cbSize_hRing > historyLen + 1 ) { if( hRing != &local_hRing[0] ) { TA_Free( hRing ); } if( lRing != &local_lRing[0] ) { TA_Free( lRing ); } if( fhRing != &local_fhRing[0] ) { TA_Free( fhRing ); } if( flRing != &local_flRing[0] ) { TA_Free( flRing ); } TA_CKSP_ReleaseImpl( sp ); return TA_INTERNAL_ERROR(466); }
      sp->cb_hRing = (double *)TA_Malloc( sizeof(double) * (size_t)sp->cbSize_hRing );
      if( !sp->cb_hRing ) { if( hRing != &local_hRing[0] ) { TA_Free( hRing ); } if( lRing != &local_lRing[0] ) { TA_Free( lRing ); } if( fhRing != &local_fhRing[0] ) { TA_Free( fhRing ); } if( flRing != &local_flRing[0] ) { TA_Free( flRing ); } TA_CKSP_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
      memcpy( sp->cb_hRing, hRing, sizeof(double) * (size_t)sp->cbSize_hRing );
      sp->cbSize_lRing = maxIdx_lRing + 1;
      if( sp->cbSize_lRing < 1 || sp->cbSize_lRing > historyLen + 1 ) { if( hRing != &local_hRing[0] ) { TA_Free( hRing ); } if( lRing != &local_lRing[0] ) { TA_Free( lRing ); } if( fhRing != &local_fhRing[0] ) { TA_Free( fhRing ); } if( flRing != &local_flRing[0] ) { TA_Free( flRing ); } TA_CKSP_ReleaseImpl( sp ); return TA_INTERNAL_ERROR(467); }
      sp->cb_lRing = (double *)TA_Malloc( sizeof(double) * (size_t)sp->cbSize_lRing );
      if( !sp->cb_lRing ) { if( hRing != &local_hRing[0] ) { TA_Free( hRing ); } if( lRing != &local_lRing[0] ) { TA_Free( lRing ); } if( fhRing != &local_fhRing[0] ) { TA_Free( fhRing ); } if( flRing != &local_flRing[0] ) { TA_Free( flRing ); } TA_CKSP_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
      memcpy( sp->cb_lRing, lRing, sizeof(double) * (size_t)sp->cbSize_lRing );
      sp->cbSize_fhRing = maxIdx_fhRing + 1;
      if( sp->cbSize_fhRing < 1 || sp->cbSize_fhRing > historyLen + 1 ) { if( hRing != &local_hRing[0] ) { TA_Free( hRing ); } if( lRing != &local_lRing[0] ) { TA_Free( lRing ); } if( fhRing != &local_fhRing[0] ) { TA_Free( fhRing ); } if( flRing != &local_flRing[0] ) { TA_Free( flRing ); } TA_CKSP_ReleaseImpl( sp ); return TA_INTERNAL_ERROR(468); }
      sp->cb_fhRing = (double *)TA_Malloc( sizeof(double) * (size_t)sp->cbSize_fhRing );
      if( !sp->cb_fhRing ) { if( hRing != &local_hRing[0] ) { TA_Free( hRing ); } if( lRing != &local_lRing[0] ) { TA_Free( lRing ); } if( fhRing != &local_fhRing[0] ) { TA_Free( fhRing ); } if( flRing != &local_flRing[0] ) { TA_Free( flRing ); } TA_CKSP_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
      memcpy( sp->cb_fhRing, fhRing, sizeof(double) * (size_t)sp->cbSize_fhRing );
      sp->cbSize_flRing = maxIdx_flRing + 1;
      if( sp->cbSize_flRing < 1 || sp->cbSize_flRing > historyLen + 1 ) { if( hRing != &local_hRing[0] ) { TA_Free( hRing ); } if( lRing != &local_lRing[0] ) { TA_Free( lRing ); } if( fhRing != &local_fhRing[0] ) { TA_Free( fhRing ); } if( flRing != &local_flRing[0] ) { TA_Free( flRing ); } TA_CKSP_ReleaseImpl( sp ); return TA_INTERNAL_ERROR(469); }
      sp->cb_flRing = (double *)TA_Malloc( sizeof(double) * (size_t)sp->cbSize_flRing );
      if( !sp->cb_flRing ) { if( hRing != &local_hRing[0] ) { TA_Free( hRing ); } if( lRing != &local_lRing[0] ) { TA_Free( lRing ); } if( fhRing != &local_fhRing[0] ) { TA_Free( fhRing ); } if( flRing != &local_flRing[0] ) { TA_Free( flRing ); } TA_CKSP_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
      memcpy( sp->cb_flRing, flRing, sizeof(double) * (size_t)sp->cbSize_flRing );
      if( hRing != &local_hRing[0] ) { TA_Free( hRing ); } if( lRing != &local_lRing[0] ) { TA_Free( lRing ); } if( fhRing != &local_fhRing[0] ) { TA_Free( fhRing ); } if( flRing != &local_flRing[0] ) { TA_Free( flRing ); } 
      sp->outRangeBegIdx = *outBegIdx;
      sp->outRangeCount = *outNBElement;
      sp->cur_outHighStop = outHighStop[(*outNBElement - 1) * outStride];
      sp->cur_outLowStop = outLowStop[(*outNBElement - 1) * outStride];
      *stream = sp;
      return TA_SUCCESS;
   }
}

/* Private function, not in public API. */
TA_RetCode TA_CKSP_OpenInternal( struct TA_CKSP_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], int startIdx, int historyLen, int optInTimePeriod, double optInMultiplier, int optInStopPeriod, double *outHighStop, double *outLowStop )
{
   TA_RetCode retCode;
   int dummyBegIdx = 0;
   int dummyNBElement = 0;
   double sink_outHighStop = 0.0;
   double sink_outLowStop = 0.0;
   retCode = TA_CKSP_OpenImpl( stream, inHigh, inLow, inClose, startIdx, historyLen, optInTimePeriod, optInMultiplier, optInStopPeriod, &dummyBegIdx, &dummyNBElement, &sink_outHighStop, &sink_outLowStop, 0 );
   if( retCode == TA_SUCCESS )
   {
      *outHighStop = sink_outHighStop;
      *outLowStop = sink_outLowStop;
   }
   return retCode;
}

TA_LIB_API TA_RetCode TA_CKSP_Open( TA_CKSP_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], int historyLen, int optInTimePeriod, double optInMultiplier, int optInStopPeriod, double *outHighStop, double *outLowStop )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_INDEX_MAX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !inClose || !outHighStop || !outLowStop ) return TA_BAD_PARAM;
   return TA_CKSP_OpenInternal( stream, inHigh, inLow, inClose, 0, historyLen, optInTimePeriod, optInMultiplier, optInStopPeriod, outHighStop, outLowStop );
}

TA_LIB_API TA_RetCode TA_CKSP_OpenAndFill( TA_CKSP_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], int historyLen, int optInTimePeriod, double optInMultiplier, int optInStopPeriod, int *outBegIdx, int *outNBElement, double outHighStop[], double outLowStop[] )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_INDEX_MAX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !inClose || !outBegIdx || !outNBElement || !outHighStop || !outLowStop ) return TA_BAD_PARAM;
   if( (const void *)outHighStop == (const void *)inHigh || (const void *)outHighStop == (const void *)inLow || (const void *)outHighStop == (const void *)inClose || (const void *)outLowStop == (const void *)inHigh || (const void *)outLowStop == (const void *)inLow || (const void *)outLowStop == (const void *)inClose || (const void *)outHighStop == (const void *)outLowStop ) return TA_BAD_PARAM;
   return TA_CKSP_OpenAndFillInternal( stream, inHigh, inLow, inClose, 0, historyLen, optInTimePeriod, optInMultiplier, optInStopPeriod, outBegIdx, outNBElement, outHighStop, outLowStop );
}

/* Private function, not in public API. */
TA_RetCode TA_CKSP_OpenAndFillInternal( struct TA_CKSP_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], int startIdx, int historyLen, int optInTimePeriod, double optInMultiplier, int optInStopPeriod, int *outBegIdx, int *outNBElement, double outHighStop[], double outLowStop[] )
{
   return TA_CKSP_OpenImpl( stream, inHigh, inLow, inClose, startIdx, historyLen, optInTimePeriod, optInMultiplier, optInStopPeriod, outBegIdx, outNBElement, outHighStop, outLowStop, 1 );
}

TA_FMA_MULTIVERSION
TA_LIB_API TA_RetCode TA_CKSP_Update( TA_CKSP_Stream *stream, double inHigh, double inLow, double inClose, double *outHighStop, double *outLowStop )
{
   if( !stream ) return TA_BAD_PARAM;
   if( stream->outRangeBegIdx + stream->outRangeCount > TA_INDEX_MAX )
      return TA_OUT_OF_RANGE_END_INDEX;
   if( !outHighStop || !outLowStop ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) || !TA_IS_FINITE( inClose ) ) return TA_BAD_PARAM;
   TA_CKSP_StepImpl( stream, inHigh, inLow, inClose, outHighStop, outLowStop );
   stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_FMA_MULTIVERSION
TA_LIB_API TA_RetCode TA_CKSP_Peek( const TA_CKSP_Stream *stream, double inHigh, double inLow, double inClose, double *outHighStop, double *outLowStop )
{
   const struct TA_CKSP_Stream *sp = stream;
   int jh;
   int jl;
   int kh;
   int kl;
   double val2;
   double val3;
   double greatest;
   double tempCY;
   double tempLT;
   double tempHT;
   double hh;
   double ll;
   double best;
   double prevATR;
   double *cb_fhRing;
   double *cb_flRing;
   double *cb_hRing;
   double *cb_lRing;
   int pkSlot0 = -1;
   double pkVal0 = 0.0;
   int pkSlot1 = -1;
   double pkVal1 = 0.0;
   int pkSlot2 = -1;
   double pkVal2 = 0.0;
   int pkSlot3 = -1;
   double pkVal3 = 0.0;

   if( !stream || !outHighStop || !outLowStop ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) || !TA_IS_FINITE( inClose ) ) return TA_BAD_PARAM;
   prevATR = sp->prevATR;
   cb_fhRing = sp->cb_fhRing;
   cb_flRing = sp->cb_flRing;
   cb_hRing = sp->cb_hRing;
   cb_lRing = sp->cb_lRing;
   tempLT = inLow;
   tempHT = inHigh;
   tempCY = sp->lag1_inClose;
   greatest = tempHT - tempLT;
   val2 = fabs(tempCY - tempHT);
   if( val2 > greatest )
   {
      greatest = val2;
   }
   val3 = fabs(tempCY - tempLT);
   if( val3 > greatest )
   {
      greatest = val3;
   }
   prevATR = fma(sp->wBeta, prevATR, sp->wAlpha * greatest);
   pkSlot0 = sp->hRing_Idx;
   pkVal0 = tempHT;
   pkSlot1 = sp->lRing_Idx;
   pkVal1 = tempLT;
   /* The extremes of the p bars ending here. The newest sits at the ring's
    * own index, so the oldest is the slot after it and the walk is two
    * straight runs.
    */
   hh = (sp->hRing_Idx != pkSlot0) ? cb_hRing[sp->hRing_Idx] : pkVal0;
   for( jh = sp->hRing_Idx + 1; jh < sp->optInTimePeriod; jh += 1 )
   {
      best = cb_hRing[jh];
      if( best > hh )
      {
         hh = best;
      }
   }
   for( jh = 0; jh < sp->hRing_Idx; jh += 1 )
   {
      best = cb_hRing[jh];
      if( best > hh )
      {
         hh = best;
      }
   }
   ll = (sp->lRing_Idx != pkSlot1) ? cb_lRing[sp->lRing_Idx] : pkVal1;
   for( jl = sp->lRing_Idx + 1; jl < sp->optInTimePeriod; jl += 1 )
   {
      best = cb_lRing[jl];
      if( best < ll )
      {
         ll = best;
      }
   }
   for( jl = 0; jl < sp->lRing_Idx; jl += 1 )
   {
      best = cb_lRing[jl];
      if( best < ll )
      {
         ll = best;
      }
   }
   pkSlot2 = sp->fhRing_Idx;
   pkVal2 = hh - sp->optInMultiplier * prevATR;
   pkSlot3 = sp->flRing_Idx;
   pkVal3 = ll + sp->optInMultiplier * prevATR;
   /* The second stage, over the q first-stage bars ending here. At q = 1
    * both runs are empty and the value is the bar's own, which is the
    * Chandelier Exit form.
    */
   hh = (sp->fhRing_Idx != pkSlot2) ? cb_fhRing[sp->fhRing_Idx] : pkVal2;
   for( kh = sp->fhRing_Idx + 1; kh < sp->optInStopPeriod; kh += 1 )
   {
      best = cb_fhRing[kh];
      if( best > hh )
      {
         hh = best;
      }
   }
   for( kh = 0; kh < sp->fhRing_Idx; kh += 1 )
   {
      best = cb_fhRing[kh];
      if( best > hh )
      {
         hh = best;
      }
   }
   ll = (sp->flRing_Idx != pkSlot3) ? cb_flRing[sp->flRing_Idx] : pkVal3;
   for( kl = sp->flRing_Idx + 1; kl < sp->optInStopPeriod; kl += 1 )
   {
      best = cb_flRing[kl];
      if( best < ll )
      {
         ll = best;
      }
   }
   for( kl = 0; kl < sp->flRing_Idx; kl += 1 )
   {
      best = cb_flRing[kl];
      if( best < ll )
      {
         ll = best;
      }
   }
   *outHighStop= hh;
   *outLowStop= ll;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_CKSP_Close( TA_CKSP_Stream *stream )
{
   TA_CKSP_ReleaseImpl( stream );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_CKSP_Value( const TA_CKSP_Stream *stream, double *outHighStop, double *outLowStop )
{
   if( !stream || !outHighStop || !outLowStop ) return TA_BAD_PARAM;
   *outHighStop = stream->cur_outHighStop;
   *outLowStop = stream->cur_outLowStop;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_CKSP_OutRange( const TA_CKSP_Stream *stream, int *outBegIdx, int *outNBElement )
{
   if( !stream || !outBegIdx || !outNBElement ) return TA_BAD_PARAM;
   *outBegIdx = stream->outRangeBegIdx;
   *outNBElement = stream->outRangeCount;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_CKSP_Advance( TA_CKSP_Stream *stream )
{
   if( !stream ) return TA_BAD_PARAM;
   if( stream->outRangeBegIdx + stream->outRangeCount > TA_INDEX_MAX )
      return TA_OUT_OF_RANGE_END_INDEX;
   stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_CKSP_Clone( const TA_CKSP_Stream *stream, TA_CKSP_Stream **clone )
{
   struct TA_CKSP_Stream *sp;

   if( !clone ) return TA_BAD_PARAM;
   *clone = NULL;
   if( !stream ) return TA_BAD_PARAM;
   sp = (struct TA_CKSP_Stream *)TA_Malloc( sizeof(*sp) );
   if( !sp ) return TA_ALLOC_ERR;
   *sp = *stream;
   sp->cb_hRing = NULL;
   sp->cb_lRing = NULL;
   sp->cb_fhRing = NULL;
   sp->cb_flRing = NULL;
   if( stream->cb_hRing )
   { size_t copyN = (size_t)(sp->cbSize_hRing);
     sp->cb_hRing = (double *)TA_Malloc( sizeof(double) * copyN );
     if( !sp->cb_hRing ) { TA_CKSP_Close( sp ); return TA_ALLOC_ERR; }
     memcpy( sp->cb_hRing, stream->cb_hRing, sizeof(double) * copyN ); }
   if( stream->cb_lRing )
   { size_t copyN = (size_t)(sp->cbSize_lRing);
     sp->cb_lRing = (double *)TA_Malloc( sizeof(double) * copyN );
     if( !sp->cb_lRing ) { TA_CKSP_Close( sp ); return TA_ALLOC_ERR; }
     memcpy( sp->cb_lRing, stream->cb_lRing, sizeof(double) * copyN ); }
   if( stream->cb_fhRing )
   { size_t copyN = (size_t)(sp->cbSize_fhRing);
     sp->cb_fhRing = (double *)TA_Malloc( sizeof(double) * copyN );
     if( !sp->cb_fhRing ) { TA_CKSP_Close( sp ); return TA_ALLOC_ERR; }
     memcpy( sp->cb_fhRing, stream->cb_fhRing, sizeof(double) * copyN ); }
   if( stream->cb_flRing )
   { size_t copyN = (size_t)(sp->cbSize_flRing);
     sp->cb_flRing = (double *)TA_Malloc( sizeof(double) * copyN );
     if( !sp->cb_flRing ) { TA_CKSP_Close( sp ); return TA_ALLOC_ERR; }
     memcpy( sp->cb_flRing, stream->cb_flRing, sizeof(double) * copyN ); }
   *clone = sp;
   return TA_SUCCESS;
}

