/* TA-LIB Copyright (c) 1999-2026, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_stream_private.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  AC       Angelo Ciceri
 *
 *
 * Change history:
 *
 *  MMDDYY BY   Description
 *  -------------------------------------------------------------------
 *  120904 AC   Creation
 */

TA_LIB_API int TA_CDLDARKCLOUDCOVER_Lookback( double optInPenetration )
{
   int BodyLong_rangeType = TA_Globals->candleSettings[TA_BodyLong].rangeType;
   int BodyLong_avgPeriod = TA_Globals->candleSettings[TA_BodyLong].avgPeriod;
   double BodyLong_factor = TA_Globals->candleSettings[TA_BodyLong].factor;
   if( optInPenetration == TA_REAL_DEFAULT )
      optInPenetration = 0.5;
   else if( !(optInPenetration >= 0e0 && optInPenetration <= TA_REAL_MAX) )
      return -1;
   return BodyLong_avgPeriod + 1;
}

TA_LIB_API TA_RetCode TA_CDLDARKCLOUDCOVER( int    startIdx,
                                            int    endIdx,
                                            const double inOpen[],
                                            const double inHigh[],
                                            const double inLow[],
                                            const double inClose[],
                                            double optInPenetration,
                                            int          *outBegIdx,
                                            int          *outNBElement,
                                            int        outInteger[] )
{
   double BodyLongPeriodTotal;
   int i;
   int outIdx;
   int BodyLongTrailingIdx;
   int lookbackTotal;
   int BodyLong_rangeType = TA_Globals->candleSettings[TA_BodyLong].rangeType;
   int BodyLong_avgPeriod = TA_Globals->candleSettings[TA_BodyLong].avgPeriod;
   double BodyLong_factor = TA_Globals->candleSettings[TA_BodyLong].factor;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( optInPenetration == TA_REAL_DEFAULT )
      optInPenetration = 0.5;
   else if( !(optInPenetration >= 0e0 && optInPenetration <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( !inOpen )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !inClose )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outInteger )
      return TA_BAD_PARAM;

   /* Identify the minimum number of price bar needed
    * to calculate at least one output.
    */
   lookbackTotal = TA_CDLDARKCLOUDCOVER_Lookback(optInPenetration);
   /* Move up the start index if there is not
    * enough initial data.
    */
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   /* Make sure there is still something to evaluate. */
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   /* Do the calculation using tight loops. */
   /* Add-up the initial period, except for the last value. */
   BodyLongPeriodTotal = 0;
   BodyLongTrailingIdx = startIdx - BodyLong_avgPeriod;
   i = BodyLongTrailingIdx;
   while( i < startIdx )
   {
      BodyLongPeriodTotal += TA_CANDLERANGE(BodyLong,i - 1);
      i += 1;
   }
   i = startIdx;
   /* Proceed with the calculation for the requested range.
    * Must have:
    * - first candle: long white candle
    * - second candle: black candle that opens above previous day high and closes within previous day real body;
    * Greg Morris wants the close to be below the midpoint of the previous real body
    * The meaning of "long" is specified with TA_SetCandleSettings, the penetration of the first real body is specified
    * with optInPenetration
    * outInteger is negative (-1 to -100): dark cloud cover is always bearish
    * the user should consider that a dark cloud cover is significant when it appears in an uptrend, while
    * this function does not consider it
    */
   outIdx = 0;
   do
   {
      if( ((inClose[i - 1] >= inOpen[i - 1]) ? 1 : 0 - 1) == 1 && /* 1st: white */
          fabs(inClose[i - 1] - inOpen[i - 1]) > TA_CANDLEAVERAGE(BodyLong,BodyLongPeriodTotal,i - 1) && /* long */
          ((inClose[i] >= inOpen[i]) ? 1 : 0 - 1) == 0 - 1 &&     /* 2nd: black */
          inOpen[i] > inHigh[i - 1] &&                            /* open above prior high */
          inClose[i] > inOpen[i - 1] &&                           /* close within prior body */
          inClose[i] < inClose[i - 1] - fabs(inClose[i - 1] - inOpen[i - 1]) * optInPenetration )
      {
         outInteger[outIdx++] = 0 - 100;
      } else 
      {
         outInteger[outIdx++] = 0;
      }
      /* add the current range and subtract the first range: this is done after the pattern recognition
       * when avgPeriod is not 0, that means "compare with the previous candles" (it excludes the current candle)
       */
      BodyLongPeriodTotal += TA_CANDLERANGE(BodyLong,i - 1) - TA_CANDLERANGE(BodyLong,BodyLongTrailingIdx - 1);
      i += 1;
      BodyLongTrailingIdx += 1;
   } while( i <= endIdx );
   /* All done. Indicate the output limits and return. */
   *outNBElement= outIdx;
   *outBegIdx= startIdx;
   return TA_SUCCESS;
}

TA_RetCode TA_S_CDLDARKCLOUDCOVER( int    startIdx,
                                   int    endIdx,
                                   const float inOpen[],
                                   const float inHigh[],
                                   const float inLow[],
                                   const float inClose[],
                                   double optInPenetration,
                                   int          *outBegIdx,
                                   int          *outNBElement,
                                   int        outInteger[] )
{
   double BodyLongPeriodTotal;
   int i;
   int outIdx;
   int BodyLongTrailingIdx;
   int lookbackTotal;
   int BodyLong_rangeType = TA_Globals->candleSettings[TA_BodyLong].rangeType;
   int BodyLong_avgPeriod = TA_Globals->candleSettings[TA_BodyLong].avgPeriod;
   double BodyLong_factor = TA_Globals->candleSettings[TA_BodyLong].factor;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( optInPenetration == TA_REAL_DEFAULT )
      optInPenetration = 0.5;
   else if( !(optInPenetration >= 0e0 && optInPenetration <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( !inOpen )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !inClose )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outInteger )
      return TA_BAD_PARAM;

   lookbackTotal = TA_CDLDARKCLOUDCOVER_Lookback(optInPenetration);
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   BodyLongPeriodTotal = 0;
   BodyLongTrailingIdx = startIdx - BodyLong_avgPeriod;
   i = BodyLongTrailingIdx;
   while( i < startIdx )
   {
      BodyLongPeriodTotal += TA_CANDLERANGE(BodyLong,i - 1);
      i += 1;
   }
   i = startIdx;
   outIdx = 0;
   do
   {
      if( (((double)inClose[i - 1] >= (double)inOpen[i - 1]) ? 1 : 0 - 1) == 1 && fabs((double)inClose[i - 1] - (double)inOpen[i - 1]) > TA_CANDLEAVERAGE(BodyLong,BodyLongPeriodTotal,i - 1) && (((double)inClose[i] >= (double)inOpen[i]) ? 1 : 0 - 1) == 0 - 1 && (double)inOpen[i] > (double)inHigh[i - 1] && (double)inClose[i] > (double)inOpen[i - 1] && (double)inClose[i] < (double)inClose[i - 1] - fabs((double)inClose[i - 1] - (double)inOpen[i - 1]) * optInPenetration )
      {
         outInteger[outIdx++] = 0 - 100;
      } else 
      {
         outInteger[outIdx++] = 0;
      }
      BodyLongPeriodTotal += TA_CANDLERANGE(BodyLong,i - 1) - TA_CANDLERANGE(BodyLong,BodyLongTrailingIdx - 1);
      i += 1;
      BodyLongTrailingIdx += 1;
   } while( i <= endIdx );
   *outNBElement= outIdx;
   *outBegIdx= startIdx;
   return TA_SUCCESS;
}

/**** Streaming API *****/

struct TA_CDLDARKCLOUDCOVER_Stream {
   /* The bars this handle has an output for (see TA_StreamOutRange).
    * Kept first, and in this order, in every stream struct. */
   int outRangeBegIdx;
   int outRangeCount;
   /* The value(s) at the last bar the stream counted (see TA_CDLDARKCLOUDCOVER_Value). */
   int cur_outInteger;
   double optInPenetration;
   double BodyLongPeriodTotal;
   double lag1_inOpen;
   double lag1_inHigh;
   double lag1_inLow;
   double lag1_inClose;
   int ringPos_BodyLongTrailingIdx;
   int ringCap_BodyLongTrailingIdx;
   int ringLag_BodyLongTrailingIdx;
   double *ring_BodyLongTrailingIdx_derived;
};

/* Private function, not in public API. */
static void TA_CDLDARKCLOUDCOVER_ReleaseImpl( struct TA_CDLDARKCLOUDCOVER_Stream *sp )
{
   if( !sp ) return;
   if( sp->ring_BodyLongTrailingIdx_derived ) TA_Free( sp->ring_BodyLongTrailingIdx_derived );
   TA_Free( sp );
}

/* Private function, not in public API. */
static void TA_CDLDARKCLOUDCOVER_StepImpl( struct TA_CDLDARKCLOUDCOVER_Stream *sp, double inOpen, double inHigh, double inLow, double inClose, int *outInteger )
{
   sp->ring_BodyLongTrailingIdx_derived[sp->ringPos_BodyLongTrailingIdx] = TA_STREAM_CANDLERANGE(BodyLong,inOpen,inHigh,inLow,inClose);
   if( ((sp->lag1_inClose >= sp->lag1_inOpen) ? 1 : 0 - 1) == 1 && /* 1st: white */
       fabs(sp->lag1_inClose - sp->lag1_inOpen) > TA_STREAM_CANDLEAVERAGE(BodyLong,sp->BodyLongPeriodTotal,sp->lag1_inOpen,sp->lag1_inHigh,sp->lag1_inLow,sp->lag1_inClose) && /* long */
       ((inClose >= inOpen) ? 1 : 0 - 1) == 0 - 1 &&               /* 2nd: black */
       inOpen > sp->lag1_inHigh &&                                 /* open above prior high */
       inClose > sp->lag1_inOpen &&                                /* close within prior body */
       inClose < sp->lag1_inClose - fabs(sp->lag1_inClose - sp->lag1_inOpen) * sp->optInPenetration )
   {
      *outInteger= 0 - 100;
   } else 
   {
      *outInteger= 0;
   }
   /* add the current range and subtract the first range: this is done after the pattern recognition
    * when avgPeriod is not 0, that means "compare with the previous candles" (it excludes the current candle)
    */
   sp->BodyLongPeriodTotal += TA_STREAM_CANDLERANGE(BodyLong,sp->lag1_inOpen,sp->lag1_inHigh,sp->lag1_inLow,sp->lag1_inClose) - sp->ring_BodyLongTrailingIdx_derived[(sp->ringPos_BodyLongTrailingIdx + sp->ringCap_BodyLongTrailingIdx - sp->ringLag_BodyLongTrailingIdx - 1) % sp->ringCap_BodyLongTrailingIdx];
   sp->cur_outInteger = *outInteger;
   sp->lag1_inOpen = inOpen;
   sp->lag1_inHigh = inHigh;
   sp->lag1_inLow = inLow;
   sp->lag1_inClose = inClose;
   sp->ringPos_BodyLongTrailingIdx = sp->ringPos_BodyLongTrailingIdx + 1;
   if( sp->ringPos_BodyLongTrailingIdx >= sp->ringCap_BodyLongTrailingIdx )
   {
      sp->ringPos_BodyLongTrailingIdx = 0;
   }
}

static TA_RetCode TA_CDLDARKCLOUDCOVER_OpenImpl( struct TA_CDLDARKCLOUDCOVER_Stream **stream, const double inOpen[], const double inHigh[], const double inLow[], const double inClose[], int startIdx, int historyLen, double optInPenetration, int *outBegIdx, int *outNBElement, int outInteger[], int outStride )
{
   struct TA_CDLDARKCLOUDCOVER_Stream *sp;
   int endIdx;
   int dummyBegIdx;
   int dummyNBElement;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inOpen || !inHigh || !inLow || !inClose || !outInteger ) return TA_BAD_PARAM;
   if( optInPenetration == TA_REAL_DEFAULT )
      optInPenetration = 0.5;
   else if( !(optInPenetration >= 0e0 && optInPenetration <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( startIdx > historyLen - 1 )
   {
      *outBegIdx = 0;
      *outNBElement = 0;
      return TA_INSUFFICIENT_HISTORY;
   }

   endIdx = historyLen - 1;
   dummyBegIdx = 0;
   dummyNBElement = 0;
   (void)startIdx; (void)dummyBegIdx; (void)dummyNBElement;

   {
      int BodyLong_avgPeriod = TA_Globals->candleSettings[TA_BodyLong].avgPeriod;
      double BodyLongPeriodTotal = 0.0;
      int i;
      int outIdx;
      int BodyLongTrailingIdx;
      int lookbackTotal;
      /* Identify the minimum number of price bar needed
       * to calculate at least one output.
       */
      lookbackTotal = TA_CDLDARKCLOUDCOVER_Lookback(optInPenetration);
      /* Move up the start index if there is not
       * enough initial data.
       */
      if( startIdx < lookbackTotal )
      {
         startIdx = lookbackTotal;
      }
      /* Make sure there is still something to evaluate. */
      if( startIdx > endIdx )
      {
         *outBegIdx= 0;
         *outNBElement= 0;
         return TA_INSUFFICIENT_HISTORY;
      }
      /* Do the calculation using tight loops. */
      /* Add-up the initial period, except for the last value. */
      BodyLongPeriodTotal = 0;
      BodyLongTrailingIdx = startIdx - BodyLong_avgPeriod;
      i = BodyLongTrailingIdx;
      while( i < startIdx )
      {
         BodyLongPeriodTotal += TA_CANDLERANGE(BodyLong,i - 1);
         i += 1;
      }
      i = startIdx;
      /* Proceed with the calculation for the requested range.
       * Must have:
       * - first candle: long white candle
       * - second candle: black candle that opens above previous day high and closes within previous day real body;
       * Greg Morris wants the close to be below the midpoint of the previous real body
       * The meaning of "long" is specified with TA_SetCandleSettings, the penetration of the first real body is specified
       * with optInPenetration
       * outInteger is negative (-1 to -100): dark cloud cover is always bearish
       * the user should consider that a dark cloud cover is significant when it appears in an uptrend, while
       * this function does not consider it
       */
      outIdx = 0;
      do
      {
         if( ((inClose[i - 1] >= inOpen[i - 1]) ? 1 : 0 - 1) == 1 && /* 1st: white */
             fabs(inClose[i - 1] - inOpen[i - 1]) > TA_CANDLEAVERAGE(BodyLong,BodyLongPeriodTotal,i - 1) && /* long */
             ((inClose[i] >= inOpen[i]) ? 1 : 0 - 1) == 0 - 1 &&     /* 2nd: black */
             inOpen[i] > inHigh[i - 1] &&                            /* open above prior high */
             inClose[i] > inOpen[i - 1] &&                           /* close within prior body */
             inClose[i] < inClose[i - 1] - fabs(inClose[i - 1] - inOpen[i - 1]) * optInPenetration )
         {
            outInteger[outIdx++ * outStride] = 0 - 100;
         } else 
         {
            outInteger[outIdx++ * outStride] = 0;
         }
         /* add the current range and subtract the first range: this is done after the pattern recognition
          * when avgPeriod is not 0, that means "compare with the previous candles" (it excludes the current candle)
          */
         BodyLongPeriodTotal += TA_CANDLERANGE(BodyLong,i - 1) - TA_CANDLERANGE(BodyLong,BodyLongTrailingIdx - 1);
         i += 1;
         BodyLongTrailingIdx += 1;
      } while( i <= endIdx );
      /* All done. Indicate the output limits and return. */
      *outNBElement= outIdx;
      *outBegIdx= startIdx;

      /* Capture the live batch state into the handle. */
      sp = (struct TA_CDLDARKCLOUDCOVER_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) { return TA_ALLOC_ERR; }
      memset( sp, 0, sizeof(*sp) );
      sp->optInPenetration = optInPenetration;
      sp->BodyLongPeriodTotal = BodyLongPeriodTotal;
      sp->ringLag_BodyLongTrailingIdx = (int)(i - BodyLongTrailingIdx);
      sp->ringCap_BodyLongTrailingIdx = sp->ringLag_BodyLongTrailingIdx + 2;
      if( sp->ringLag_BodyLongTrailingIdx < 0 || sp->ringCap_BodyLongTrailingIdx > historyLen ) { TA_CDLDARKCLOUDCOVER_ReleaseImpl( sp ); return TA_INTERNAL_ERROR(223); }
      { size_t allocN = (size_t)(sp->ringCap_BodyLongTrailingIdx > 0 ? sp->ringCap_BodyLongTrailingIdx : 1);
        sp->ring_BodyLongTrailingIdx_derived = (double *)TA_Malloc( sizeof(double) * allocN );
        if( !sp->ring_BodyLongTrailingIdx_derived ) { TA_CDLDARKCLOUDCOVER_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
        { int fillJ;
          for( fillJ = historyLen - sp->ringCap_BodyLongTrailingIdx; fillJ < historyLen; fillJ++ )
             sp->ring_BodyLongTrailingIdx_derived[fillJ % sp->ringCap_BodyLongTrailingIdx] = TA_STREAM_CANDLERANGE(BodyLong,inOpen[fillJ],inHigh[fillJ],inLow[fillJ],inClose[fillJ]);
        }
      }
      sp->ringPos_BodyLongTrailingIdx = historyLen % sp->ringCap_BodyLongTrailingIdx;
      sp->lag1_inOpen = inOpen[historyLen - 1];
      sp->lag1_inHigh = inHigh[historyLen - 1];
      sp->lag1_inLow = inLow[historyLen - 1];
      sp->lag1_inClose = inClose[historyLen - 1];
      sp->outRangeBegIdx = *outBegIdx;
      sp->outRangeCount = *outNBElement;
      sp->cur_outInteger = outInteger[(*outNBElement - 1) * outStride];
      *stream = sp;
      return TA_SUCCESS;
   }
}

/* Private function, not in public API. */
TA_RetCode TA_CDLDARKCLOUDCOVER_OpenInternal( struct TA_CDLDARKCLOUDCOVER_Stream **stream, const double inOpen[], const double inHigh[], const double inLow[], const double inClose[], int startIdx, int historyLen, double optInPenetration, int *outInteger )
{
   TA_RetCode retCode;
   int dummyBegIdx = 0;
   int dummyNBElement = 0;
   int sink_outInteger = 0;
   retCode = TA_CDLDARKCLOUDCOVER_OpenImpl( stream, inOpen, inHigh, inLow, inClose, startIdx, historyLen, optInPenetration, &dummyBegIdx, &dummyNBElement, &sink_outInteger, 0 );
   if( retCode == TA_SUCCESS )
   {
      *outInteger = sink_outInteger;
   }
   return retCode;
}

TA_LIB_API TA_RetCode TA_CDLDARKCLOUDCOVER_Open( TA_CDLDARKCLOUDCOVER_Stream **stream, const double inOpen[], const double inHigh[], const double inLow[], const double inClose[], int historyLen, double optInPenetration, int *outInteger )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inOpen || !inHigh || !inLow || !inClose || !outInteger ) return TA_BAD_PARAM;
   return TA_CDLDARKCLOUDCOVER_OpenInternal( stream, inOpen, inHigh, inLow, inClose, 0, historyLen, optInPenetration, outInteger );
}

TA_LIB_API TA_RetCode TA_CDLDARKCLOUDCOVER_OpenAndFill( TA_CDLDARKCLOUDCOVER_Stream **stream, const double inOpen[], const double inHigh[], const double inLow[], const double inClose[], int historyLen, double optInPenetration, int *outBegIdx, int *outNBElement, int outInteger[] )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inOpen || !inHigh || !inLow || !inClose || !outBegIdx || !outNBElement || !outInteger ) return TA_BAD_PARAM;
   if( (const void *)outInteger == (const void *)inOpen || (const void *)outInteger == (const void *)inHigh || (const void *)outInteger == (const void *)inLow || (const void *)outInteger == (const void *)inClose ) return TA_BAD_PARAM;
   return TA_CDLDARKCLOUDCOVER_OpenAndFillInternal( stream, inOpen, inHigh, inLow, inClose, 0, historyLen, optInPenetration, outBegIdx, outNBElement, outInteger );
}

/* Private function, not in public API. */
TA_RetCode TA_CDLDARKCLOUDCOVER_OpenAndFillInternal( struct TA_CDLDARKCLOUDCOVER_Stream **stream, const double inOpen[], const double inHigh[], const double inLow[], const double inClose[], int startIdx, int historyLen, double optInPenetration, int *outBegIdx, int *outNBElement, int outInteger[] )
{
   return TA_CDLDARKCLOUDCOVER_OpenImpl( stream, inOpen, inHigh, inLow, inClose, startIdx, historyLen, optInPenetration, outBegIdx, outNBElement, outInteger, 1 );
}

TA_LIB_API TA_RetCode TA_CDLDARKCLOUDCOVER_Update( TA_CDLDARKCLOUDCOVER_Stream *stream, double inOpen, double inHigh, double inLow, double inClose, int *outInteger )
{
   if( !stream || !outInteger ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inOpen ) || !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) || !TA_IS_FINITE( inClose ) )
   {
      if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
      return TA_BAD_PARAM;
   }
   TA_CDLDARKCLOUDCOVER_StepImpl( stream, inOpen, inHigh, inLow, inClose, outInteger );
   if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_CDLDARKCLOUDCOVER_Peek( const TA_CDLDARKCLOUDCOVER_Stream *stream, double inOpen, double inHigh, double inLow, double inClose, int *outInteger )
{
   struct TA_CDLDARKCLOUDCOVER_Stream scratch;
   struct TA_CDLDARKCLOUDCOVER_Stream *sp = &scratch;
   int pkSlot0 = -1;
   double pkVal0 = 0.0;

   if( !stream || !outInteger ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inOpen ) || !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) || !TA_IS_FINITE( inClose ) ) return TA_BAD_PARAM;
   scratch = *stream;
   pkSlot0 = sp->ringPos_BodyLongTrailingIdx;
   pkVal0 = TA_STREAM_CANDLERANGE(BodyLong,inOpen,inHigh,inLow,inClose);
   if( ((sp->lag1_inClose >= sp->lag1_inOpen) ? 1 : 0 - 1) == 1 && /* 1st: white */
       fabs(sp->lag1_inClose - sp->lag1_inOpen) > TA_STREAM_CANDLEAVERAGE(BodyLong,sp->BodyLongPeriodTotal,sp->lag1_inOpen,sp->lag1_inHigh,sp->lag1_inLow,sp->lag1_inClose) && /* long */
       ((inClose >= inOpen) ? 1 : 0 - 1) == 0 - 1 &&               /* 2nd: black */
       inOpen > sp->lag1_inHigh &&                                 /* open above prior high */
       inClose > sp->lag1_inOpen &&                                /* close within prior body */
       inClose < sp->lag1_inClose - fabs(sp->lag1_inClose - sp->lag1_inOpen) * sp->optInPenetration )
   {
      *outInteger= 0 - 100;
   } else 
   {
      *outInteger= 0;
   }
   /* add the current range and subtract the first range: this is done after the pattern recognition
    * when avgPeriod is not 0, that means "compare with the previous candles" (it excludes the current candle)
    */
   sp->BodyLongPeriodTotal += TA_STREAM_CANDLERANGE(BodyLong,sp->lag1_inOpen,sp->lag1_inHigh,sp->lag1_inLow,sp->lag1_inClose) - (((sp->ringPos_BodyLongTrailingIdx + sp->ringCap_BodyLongTrailingIdx - sp->ringLag_BodyLongTrailingIdx - 1) % sp->ringCap_BodyLongTrailingIdx != pkSlot0) ? sp->ring_BodyLongTrailingIdx_derived[(sp->ringPos_BodyLongTrailingIdx + sp->ringCap_BodyLongTrailingIdx - sp->ringLag_BodyLongTrailingIdx - 1) % sp->ringCap_BodyLongTrailingIdx] : pkVal0);
   sp->cur_outInteger = *outInteger;
   sp->lag1_inOpen = inOpen;
   sp->lag1_inHigh = inHigh;
   sp->lag1_inLow = inLow;
   sp->lag1_inClose = inClose;
   sp->ringPos_BodyLongTrailingIdx = sp->ringPos_BodyLongTrailingIdx + 1;
   if( sp->ringPos_BodyLongTrailingIdx >= sp->ringCap_BodyLongTrailingIdx )
   {
      sp->ringPos_BodyLongTrailingIdx = 0;
   }
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_CDLDARKCLOUDCOVER_UpdateAndFill( TA_CDLDARKCLOUDCOVER_Stream *stream, const double inOpen[], const double inHigh[], const double inLow[], const double inClose[], int barCount, int outInteger[] )
{
   int i;

   if( !stream || !inOpen || !inHigh || !inLow || !inClose || !outInteger ) return TA_BAD_PARAM;
   if( barCount < 0 ) return TA_BAD_PARAM;
   if( (const void *)outInteger == (const void *)inOpen || (const void *)outInteger == (const void *)inHigh || (const void *)outInteger == (const void *)inLow || (const void *)outInteger == (const void *)inClose ) return TA_BAD_PARAM;
   for( i = 0; i < barCount; i++ )
   {
      if( !TA_IS_FINITE( inOpen[i] ) || !TA_IS_FINITE( inHigh[i] ) || !TA_IS_FINITE( inLow[i] ) || !TA_IS_FINITE( inClose[i] ) )
      {
         if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
         return TA_BAD_PARAM;
      }
      TA_CDLDARKCLOUDCOVER_StepImpl( stream, inOpen[i], inHigh[i], inLow[i], inClose[i], &outInteger[i] );
      if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   }
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_CDLDARKCLOUDCOVER_Close( TA_CDLDARKCLOUDCOVER_Stream *stream )
{
   TA_CDLDARKCLOUDCOVER_ReleaseImpl( stream );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_CDLDARKCLOUDCOVER_Value( const TA_CDLDARKCLOUDCOVER_Stream *stream, int *outInteger )
{
   if( !stream || !outInteger ) return TA_BAD_PARAM;
   *outInteger = stream->cur_outInteger;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_CDLDARKCLOUDCOVER_Clone( const TA_CDLDARKCLOUDCOVER_Stream *stream, TA_CDLDARKCLOUDCOVER_Stream **clone )
{
   struct TA_CDLDARKCLOUDCOVER_Stream *sp;

   if( !clone ) return TA_BAD_PARAM;
   *clone = NULL;
   if( !stream ) return TA_BAD_PARAM;
   sp = (struct TA_CDLDARKCLOUDCOVER_Stream *)TA_Malloc( sizeof(*sp) );
   if( !sp ) return TA_ALLOC_ERR;
   *sp = *stream;
   sp->ring_BodyLongTrailingIdx_derived = NULL;
   if( stream->ring_BodyLongTrailingIdx_derived )
   { size_t copyN = (size_t)(sp->ringCap_BodyLongTrailingIdx > 0 ? sp->ringCap_BodyLongTrailingIdx : 1);
     sp->ring_BodyLongTrailingIdx_derived = (double *)TA_Malloc( sizeof(double) * copyN );
     if( !sp->ring_BodyLongTrailingIdx_derived ) { TA_CDLDARKCLOUDCOVER_Close( sp ); return TA_ALLOC_ERR; }
     memcpy( sp->ring_BodyLongTrailingIdx_derived, stream->ring_BodyLongTrailingIdx_derived, sizeof(double) * copyN ); }
   *clone = sp;
   return TA_SUCCESS;
}

