/* TA-LIB Copyright (c) 1999-2026, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_stream_private.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  MF       Mario Fortier
 *  KL       Kevin Lin (@kevinlincg)
 *  CC       Claude Code (AI assistant)
 *
 * Change history:
 *
 *  MMDDYY BY     Description
 *  -------------------------------------------------------------------
 *  100626 KL,CC  Creation (#485).
 */

TA_NOINLINE TA_LIB_API int TA_FISHER_Lookback( int optInTimePeriod )
{
   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 10;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return -1;
   /* The channel needs its own n-1 bars before it has a value. On top of that
    * the two recursions carry a seed that decays rather than ending.
    *
    * The count is DERIVED rather than sampled. The seed reaches the output
    * through the smoothing pole alone -- 0.67 per bar, the same whatever the
    * period, so unlike EMA's this count does not grow with n. Two factors sit
    * between that pole and the output: the transform's derivative 1/(1-v^2),
    * which the clamp caps at 1/(1-0.999^2) = 500 and which is the only reason
    * this is finite at all, and the convolution with the transform's own 0.5
    * pole, worth 1/(0.67-0.5) = 5.9. So the seed's weight is under e^-K once
    *
    *     n >= (K + ln(500*5.9)) / ln(1/0.67) = (K + 8.0) / 0.4005
    *
    * which is 44.9 bars at K = 10 and 67.4 at K = 19. The form below is 2.5
    * bars per e-fold with those 9 e-folds of gain folded in: 48 and 70.
    *
    * A sampled worst case was NOT used. Over 400 input patterns and 22 seeds
    * it reads 33 and 58, and it kept climbing as the sample grew -- 30 and 54
    * at a tenth of it -- which is what a sampled maximum does when it is not
    * a bound.
    */
   return optInTimePeriod - 1 + TA_GLOBALS_UNSTABLE(TA_FUNC_UNST_FISHER,Fisher,(5 * (10 + 9) + 1) / 2,(5 * (19 + 9) + 1) / 2);
}

TA_LIB_API int TA_FISHER_DisplayShift( int optInTimePeriod, int outputIdx )
{
   if( TA_FISHER_Lookback( optInTimePeriod ) < 0 )
      return INT_MIN;
   if( outputIdx < 0 || outputIdx >= 2 )
      return INT_MIN;
   return 0;
}

TA_FMA_MULTIVERSION
TA_LIB_API TA_RetCode TA_FISHER( int    startIdx,
                                 int    endIdx,
                                 const double inHigh[],
                                 const double inLow[],
                                 int optInTimePeriod,
                                 int          *outBegIdx,
                                 int          *outNBElement,
                                 double        outFisher[],
                                 double        outTrigger[] )
{
   double price;
   double highest;
   double lowest;
   double ratio;
   double smoothed;
   double fish;
   double prevFish;
   double tempReal;
   double tempHigh;
   double tempLow;
   int outIdx;
   int lookbackTotal;
   int unstablePeriod;
   int nbInitialElementNeeded;
   int today;
   int trailingIdx;
   int highestIdx;
   int lowestIdx;
   int i;

   if( (startIdx < 0) || (startIdx > TA_INDEX_MAX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_INDEX_MAX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 10;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outFisher )
      return TA_BAD_PARAM;
   if( !outTrigger )
      return TA_BAD_PARAM;
   if( outFisher == outTrigger )
      return TA_BAD_PARAM;

   nbInitialElementNeeded = TA_FISHER_Lookback(optInTimePeriod);
   if( startIdx < nbInitialElementNeeded )
   {
      startIdx = nbInitialElementNeeded;
   }
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   lookbackTotal = optInTimePeriod - 1;
   unstablePeriod = nbInitialElementNeeded - lookbackTotal;
   /* John F. Ehlers, "Using The Fisher Transform", Stocks & Commodities
    * V.20:11 (November 2002), pp.40-42, the EasyLanguage listing in Figure 4.
    *
    * The bar's midpoint is located in its rolling n-bar channel, rescaled to
    * (-1, +1), smoothed, clamped, and passed through atanh. What the
    * transform buys is the tail: a channel position is close to uniformly
    * distributed, and the Fisher transform of a uniform variable is close to
    * normal, so an extreme reading is rare rather than routine and a turn is
    * a sharp corner rather than a drift.
    *
    * Both recursions start from the author's zero seed and decay at their own
    * coefficient -- 0.67 for the smoothing, 0.5 for the transform -- so the
    * first bars carry the seed rather than the series. That is what the
    * unstable period discards.
    */
   smoothed = 0.0;
   prevFish = 0.0;
   today = startIdx - unstablePeriod;
   trailingIdx = today - lookbackTotal;
   highestIdx = -1;
   highest = 0.0;
   lowestIdx = -1;
   lowest = 0.0;
   outIdx = 0;
   while( today <= endIdx )
   {
      /* The channel, over the midpoints rather than over the highs and the
       * lows separately: this indicator reads one series, which happens to be
       * (H+L)/2, so both extremes come from that same series. STOCH's shape,
       * with the midpoint recomputed on the rare rescan rather than held in a
       * buffer the caller would have to own.
       */
      price = (inHigh[today] + inLow[today]) / 2.0;
      if( highestIdx < trailingIdx )
      {
         highestIdx = trailingIdx;
         tempHigh = inHigh[highestIdx];
         tempLow = inLow[highestIdx];
         highest = (tempHigh + tempLow) / 2.0;
         i = highestIdx;
         while( ++i <= today )
         {
            tempHigh = inHigh[i];
            tempLow = inLow[i];
            tempReal = (tempHigh + tempLow) / 2.0;
            if( tempReal > highest )
            {
               highestIdx = i;
               highest = tempReal;
            }
         }
      } else if( price >= highest )
      {
         highestIdx = today;
         highest = price;
      }
      if( lowestIdx < trailingIdx )
      {
         lowestIdx = trailingIdx;
         tempHigh = inHigh[lowestIdx];
         tempLow = inLow[lowestIdx];
         lowest = (tempHigh + tempLow) / 2.0;
         i = lowestIdx;
         while( ++i <= today )
         {
            tempHigh = inHigh[i];
            tempLow = inLow[i];
            tempReal = (tempHigh + tempLow) / 2.0;
            if( tempReal < lowest )
            {
               lowestIdx = i;
               lowest = tempReal;
            }
         }
      } else if( price <= lowest )
      {
         lowestIdx = today;
         lowest = price;
      }
      /* A flat window answers the neutral position rather than dividing by
       * its own zero range. The band is the range against its own two
       * extremes, STOCH's test: a fixed constant answers "flat" for every
       * window of an instrument quoted below it (#253), and an exact test
       * divides a machine-flat window into noise (#107). At 0.5 the bar
       * contributes nothing and both recursions decay on their own
       * coefficients.
       */
      tempReal = highest - lowest;
      if( !TA_IS_ZERO_SCALED(tempReal, fabs(highest) + fabs(lowest)) )
      {
         ratio = (price - lowest) / tempReal;
      } else 
      {
         ratio = 0.5;
      }
      /* The listing's .33*2*(r-.5) + .67*Value1[1]. */
      smoothed = fma(0.67, smoothed, 0.33 * 2.0 * (ratio - 0.5));
      /* The clamp is what keeps atanh finite, and the CLAMPED smoothed is what
       * the next bar's smoothing reads -- the listing assigns it back to
       * Value1 rather than holding it for the transform alone.
       */
      if( smoothed > 0.99 )
      {
         smoothed = 0.999;
      }
      if( smoothed < -0.99 )
      {
         smoothed = -0.999;
      }
      fish = fma(0.5, log((1.0 + smoothed) / (1.0 - smoothed)), 0.5 * prevFish);
      if( today >= startIdx )
      {
         outFisher[outIdx] = fish;
         /* The author's second plot is Fish[1]: the previous bar's smoothed,
          * which at the first output bar is the zero seed when no unstable
          * period was discarded, and the computed smoothed of the bar before it
          * when one was.
          */
         outTrigger[outIdx] = prevFish;
         outIdx = outIdx + 1;
      }
      prevFish = fish;
      trailingIdx += 1;
      today += 1;
   }
   *outNBElement= outIdx;
   *outBegIdx= startIdx;
   return TA_SUCCESS;
}

TA_FMA_MULTIVERSION
TA_RetCode TA_S_FISHER( int    startIdx,
                        int    endIdx,
                        const float inHigh[],
                        const float inLow[],
                        int optInTimePeriod,
                        int          *outBegIdx,
                        int          *outNBElement,
                        double        outFisher[],
                        double        outTrigger[] )
{
   double price;
   double highest;
   double lowest;
   double ratio;
   double smoothed;
   double fish;
   double prevFish;
   double tempReal;
   double tempHigh;
   double tempLow;
   int outIdx;
   int lookbackTotal;
   int unstablePeriod;
   int nbInitialElementNeeded;
   int today;
   int trailingIdx;
   int highestIdx;
   int lowestIdx;
   int i;

   if( (startIdx < 0) || (startIdx > TA_INDEX_MAX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_INDEX_MAX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 10;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outFisher )
      return TA_BAD_PARAM;
   if( !outTrigger )
      return TA_BAD_PARAM;
   if( outFisher == outTrigger )
      return TA_BAD_PARAM;

   nbInitialElementNeeded = TA_FISHER_Lookback(optInTimePeriod);
   if( startIdx < nbInitialElementNeeded )
   {
      startIdx = nbInitialElementNeeded;
   }
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   lookbackTotal = optInTimePeriod - 1;
   unstablePeriod = nbInitialElementNeeded - lookbackTotal;
   smoothed = 0.0;
   prevFish = 0.0;
   today = startIdx - unstablePeriod;
   trailingIdx = today - lookbackTotal;
   highestIdx = -1;
   highest = 0.0;
   lowestIdx = -1;
   lowest = 0.0;
   outIdx = 0;
   while( today <= endIdx )
   {
      price = ((double)inHigh[today] + (double)inLow[today]) / 2.0;
      if( highestIdx < trailingIdx )
      {
         highestIdx = trailingIdx;
         tempHigh = (double)inHigh[highestIdx];
         tempLow = (double)inLow[highestIdx];
         highest = (tempHigh + tempLow) / 2.0;
         i = highestIdx;
         while( ++i <= today )
         {
            tempHigh = (double)inHigh[i];
            tempLow = (double)inLow[i];
            tempReal = (tempHigh + tempLow) / 2.0;
            if( tempReal > highest )
            {
               highestIdx = i;
               highest = tempReal;
            }
         }
      } else if( price >= highest )
      {
         highestIdx = today;
         highest = price;
      }
      if( lowestIdx < trailingIdx )
      {
         lowestIdx = trailingIdx;
         tempHigh = (double)inHigh[lowestIdx];
         tempLow = (double)inLow[lowestIdx];
         lowest = (tempHigh + tempLow) / 2.0;
         i = lowestIdx;
         while( ++i <= today )
         {
            tempHigh = (double)inHigh[i];
            tempLow = (double)inLow[i];
            tempReal = (tempHigh + tempLow) / 2.0;
            if( tempReal < lowest )
            {
               lowestIdx = i;
               lowest = tempReal;
            }
         }
      } else if( price <= lowest )
      {
         lowestIdx = today;
         lowest = price;
      }
      tempReal = highest - lowest;
      if( !TA_IS_ZERO_SCALED(tempReal, fabs(highest) + fabs(lowest)) )
      {
         ratio = (price - lowest) / tempReal;
      } else 
      {
         ratio = 0.5;
      }
      smoothed = fma(0.67, smoothed, 0.33 * 2.0 * (ratio - 0.5));
      if( smoothed > 0.99 )
      {
         smoothed = 0.999;
      }
      if( smoothed < -0.99 )
      {
         smoothed = -0.999;
      }
      fish = fma(0.5, log((1.0 + smoothed) / (1.0 - smoothed)), 0.5 * prevFish);
      if( today >= startIdx )
      {
         outFisher[outIdx] = fish;
         outTrigger[outIdx] = prevFish;
         outIdx = outIdx + 1;
      }
      prevFish = fish;
      trailingIdx += 1;
      today += 1;
   }
   *outNBElement= outIdx;
   *outBegIdx= startIdx;
   return TA_SUCCESS;
}

/**** Streaming API *****/

struct TA_FISHER_Stream {
   /* The bars this handle has an output for (see TA_FISHER_OutRange). */
   int outRangeBegIdx;
   int outRangeCount;
   /* The value(s) at the last bar the stream counted (see TA_FISHER_Value). */
   double cur_outFisher;
   double cur_outTrigger;
   int optInTimePeriod;
   double highest;
   double lowest;
   double smoothed;
   double prevFish;
   int trailingIdx;
   int highestIdx;
   int lowestIdx;
   int i;
   int today;
   int xCap;
   int xPhys;
   int xMask;
   double *x_inHigh;
   double *x_inLow;
};

/* Private function, not in public API. */
static void TA_FISHER_ReleaseImpl( struct TA_FISHER_Stream *sp )
{
   if( !sp ) return;
   if( sp->x_inHigh ) TA_Free( sp->x_inHigh );
   if( sp->x_inLow ) TA_Free( sp->x_inLow );
   TA_Free( sp );
}

/* Private function, not in public API. */
static TA_FMA_STEP_INLINE void TA_FISHER_StepImpl( struct TA_FISHER_Stream *sp, double inHigh, double inLow, double *outFisher, double *outTrigger )
{
   double price;
   double ratio;
   double fish;
   double tempReal;
   double tempHigh;
   double tempLow;

   sp->x_inHigh[sp->today & sp->xMask] = inHigh;
   sp->x_inLow[sp->today & sp->xMask] = inLow;
   /* The channel, over the midpoints rather than over the highs and the
    * lows separately: this indicator reads one series, which happens to be
    * (H+L)/2, so both extremes come from that same series. STOCH's shape,
    * with the midpoint recomputed on the rare rescan rather than held in a
    * buffer the caller would have to own.
    */
   price = (sp->x_inHigh[sp->today & sp->xMask] + sp->x_inLow[sp->today & sp->xMask]) / 2.0;
   if( sp->highestIdx < sp->trailingIdx )
   {
      sp->highestIdx = sp->trailingIdx;
      tempHigh = sp->x_inHigh[sp->highestIdx & sp->xMask];
      tempLow = sp->x_inLow[sp->highestIdx & sp->xMask];
      sp->highest = (tempHigh + tempLow) / 2.0;
      sp->i = sp->highestIdx;
      while( ++sp->i <= sp->today )
      {
         tempHigh = sp->x_inHigh[sp->i & sp->xMask];
         tempLow = sp->x_inLow[sp->i & sp->xMask];
         tempReal = (tempHigh + tempLow) / 2.0;
         if( tempReal > sp->highest )
         {
            sp->highestIdx = sp->i;
            sp->highest = tempReal;
         }
      }
   } else if( price >= sp->highest )
   {
      sp->highestIdx = sp->today;
      sp->highest = price;
   }
   if( sp->lowestIdx < sp->trailingIdx )
   {
      sp->lowestIdx = sp->trailingIdx;
      tempHigh = sp->x_inHigh[sp->lowestIdx & sp->xMask];
      tempLow = sp->x_inLow[sp->lowestIdx & sp->xMask];
      sp->lowest = (tempHigh + tempLow) / 2.0;
      sp->i = sp->lowestIdx;
      while( ++sp->i <= sp->today )
      {
         tempHigh = sp->x_inHigh[sp->i & sp->xMask];
         tempLow = sp->x_inLow[sp->i & sp->xMask];
         tempReal = (tempHigh + tempLow) / 2.0;
         if( tempReal < sp->lowest )
         {
            sp->lowestIdx = sp->i;
            sp->lowest = tempReal;
         }
      }
   } else if( price <= sp->lowest )
   {
      sp->lowestIdx = sp->today;
      sp->lowest = price;
   }
   /* A flat window answers the neutral position rather than dividing by
    * its own zero range. The band is the range against its own two
    * extremes, STOCH's test: a fixed constant answers "flat" for every
    * window of an instrument quoted below it (#253), and an exact test
    * divides a machine-flat window into noise (#107). At 0.5 the bar
    * contributes nothing and both recursions decay on their own
    * coefficients.
    */
   tempReal = sp->highest - sp->lowest;
   if( !TA_IS_ZERO_SCALED(tempReal, fabs(sp->highest) + fabs(sp->lowest)) )
   {
      ratio = (price - sp->lowest) / tempReal;
   } else 
   {
      ratio = 0.5;
   }
   /* The listing's .33*2*(r-.5) + .67*Value1[1]. */
   sp->smoothed = fma(0.67, sp->smoothed, 0.33 * 2.0 * (ratio - 0.5));
   /* The clamp is what keeps atanh finite, and the CLAMPED smoothed is what
    * the next bar's smoothing reads -- the listing assigns it back to
    * Value1 rather than holding it for the transform alone.
    */
   if( sp->smoothed > 0.99 )
   {
      sp->smoothed = 0.999;
   }
   if( sp->smoothed < -0.99 )
   {
      sp->smoothed = -0.999;
   }
   fish = fma(0.5, log((1.0 + sp->smoothed) / (1.0 - sp->smoothed)), 0.5 * sp->prevFish);
   *outFisher= fish;
   /* The author's second plot is Fish[1]: the previous bar's smoothed,
    * which at the first output bar is the zero seed when no unstable
    * period was discarded, and the computed smoothed of the bar before it
    * when one was.
    */
   *outTrigger= sp->prevFish;
   sp->prevFish = fish;
   sp->trailingIdx += 1;
   sp->today += 1;
   sp->cur_outFisher = *outFisher;
   sp->cur_outTrigger = *outTrigger;
}

static TA_FMA_STEP_INLINE TA_RetCode TA_FISHER_OpenImpl( struct TA_FISHER_Stream **stream, const double inHigh[], const double inLow[], int startIdx, int historyLen, int optInTimePeriod, int *outBegIdx, int *outNBElement, double outFisher[], double outTrigger[], int outStride )
{
   struct TA_FISHER_Stream *sp;
   int endIdx;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_INDEX_MAX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !outFisher || !outTrigger ) return TA_BAD_PARAM;
   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 10;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( startIdx > historyLen - 1 )
   {
      *outBegIdx = 0;
      *outNBElement = 0;
      return TA_INSUFFICIENT_HISTORY;
   }

   endIdx = historyLen - 1;

   {
      double price;
      double highest = 0.0;
      double lowest = 0.0;
      double ratio;
      double smoothed = 0.0;
      double fish;
      double prevFish = 0.0;
      double tempReal;
      double tempHigh;
      double tempLow;
      int outIdx;
      int lookbackTotal;
      int unstablePeriod;
      int nbInitialElementNeeded;
      int today = 0;
      int trailingIdx = 0;
      int highestIdx = 0;
      int lowestIdx = 0;
      int i = 0;
      nbInitialElementNeeded = TA_FISHER_Lookback(optInTimePeriod);
      if( startIdx < nbInitialElementNeeded )
      {
         startIdx = nbInitialElementNeeded;
      }
      if( startIdx > endIdx )
      {
         *outBegIdx= 0;
         *outNBElement= 0;
         return TA_INSUFFICIENT_HISTORY;
      }
      lookbackTotal = optInTimePeriod - 1;
      unstablePeriod = nbInitialElementNeeded - lookbackTotal;
      /* John F. Ehlers, "Using The Fisher Transform", Stocks & Commodities
       * V.20:11 (November 2002), pp.40-42, the EasyLanguage listing in Figure 4.
       *
       * The bar's midpoint is located in its rolling n-bar channel, rescaled to
       * (-1, +1), smoothed, clamped, and passed through atanh. What the
       * transform buys is the tail: a channel position is close to uniformly
       * distributed, and the Fisher transform of a uniform variable is close to
       * normal, so an extreme reading is rare rather than routine and a turn is
       * a sharp corner rather than a drift.
       *
       * Both recursions start from the author's zero seed and decay at their own
       * coefficient -- 0.67 for the smoothing, 0.5 for the transform -- so the
       * first bars carry the seed rather than the series. That is what the
       * unstable period discards.
       */
      smoothed = 0.0;
      prevFish = 0.0;
      today = startIdx - unstablePeriod;
      trailingIdx = today - lookbackTotal;
      highestIdx = -1;
      highest = 0.0;
      lowestIdx = -1;
      lowest = 0.0;
      outIdx = 0;
      while( today <= endIdx )
      {
         /* The channel, over the midpoints rather than over the highs and the
          * lows separately: this indicator reads one series, which happens to be
          * (H+L)/2, so both extremes come from that same series. STOCH's shape,
          * with the midpoint recomputed on the rare rescan rather than held in a
          * buffer the caller would have to own.
          */
         price = (inHigh[today] + inLow[today]) / 2.0;
         if( highestIdx < trailingIdx )
         {
            highestIdx = trailingIdx;
            tempHigh = inHigh[highestIdx];
            tempLow = inLow[highestIdx];
            highest = (tempHigh + tempLow) / 2.0;
            i = highestIdx;
            while( ++i <= today )
            {
               tempHigh = inHigh[i];
               tempLow = inLow[i];
               tempReal = (tempHigh + tempLow) / 2.0;
               if( tempReal > highest )
               {
                  highestIdx = i;
                  highest = tempReal;
               }
            }
         } else if( price >= highest )
         {
            highestIdx = today;
            highest = price;
         }
         if( lowestIdx < trailingIdx )
         {
            lowestIdx = trailingIdx;
            tempHigh = inHigh[lowestIdx];
            tempLow = inLow[lowestIdx];
            lowest = (tempHigh + tempLow) / 2.0;
            i = lowestIdx;
            while( ++i <= today )
            {
               tempHigh = inHigh[i];
               tempLow = inLow[i];
               tempReal = (tempHigh + tempLow) / 2.0;
               if( tempReal < lowest )
               {
                  lowestIdx = i;
                  lowest = tempReal;
               }
            }
         } else if( price <= lowest )
         {
            lowestIdx = today;
            lowest = price;
         }
         /* A flat window answers the neutral position rather than dividing by
          * its own zero range. The band is the range against its own two
          * extremes, STOCH's test: a fixed constant answers "flat" for every
          * window of an instrument quoted below it (#253), and an exact test
          * divides a machine-flat window into noise (#107). At 0.5 the bar
          * contributes nothing and both recursions decay on their own
          * coefficients.
          */
         tempReal = highest - lowest;
         if( !TA_IS_ZERO_SCALED(tempReal, fabs(highest) + fabs(lowest)) )
         {
            ratio = (price - lowest) / tempReal;
         } else 
         {
            ratio = 0.5;
         }
         /* The listing's .33*2*(r-.5) + .67*Value1[1]. */
         smoothed = fma(0.67, smoothed, 0.33 * 2.0 * (ratio - 0.5));
         /* The clamp is what keeps atanh finite, and the CLAMPED smoothed is what
          * the next bar's smoothing reads -- the listing assigns it back to
          * Value1 rather than holding it for the transform alone.
          */
         if( smoothed > 0.99 )
         {
            smoothed = 0.999;
         }
         if( smoothed < -0.99 )
         {
            smoothed = -0.999;
         }
         fish = fma(0.5, log((1.0 + smoothed) / (1.0 - smoothed)), 0.5 * prevFish);
         if( today >= startIdx )
         {
            outFisher[outIdx * outStride] = fish;
            /* The author's second plot is Fish[1]: the previous bar's smoothed,
             * which at the first output bar is the zero seed when no unstable
             * period was discarded, and the computed smoothed of the bar before it
             * when one was.
             */
            outTrigger[outIdx * outStride] = prevFish;
            outIdx = outIdx + 1;
         }
         prevFish = fish;
         trailingIdx += 1;
         today += 1;
      }
      *outNBElement= outIdx;
      *outBegIdx= startIdx;

      /* Capture the live batch state into the handle. */
      sp = (struct TA_FISHER_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) { return TA_ALLOC_ERR; }
      memset( sp, 0, sizeof(*sp) );
      sp->optInTimePeriod = optInTimePeriod;
      sp->highest = highest;
      sp->lowest = lowest;
      sp->smoothed = smoothed;
      sp->prevFish = prevFish;
      sp->trailingIdx = trailingIdx;
      sp->highestIdx = highestIdx;
      sp->lowestIdx = lowestIdx;
      sp->i = i;
      sp->today = today;
      sp->xCap = (int)(today - trailingIdx) + 1;
      if( sp->xCap < 1 || sp->xCap > historyLen ) { TA_FISHER_ReleaseImpl( sp ); return TA_INTERNAL_ERROR(485); }
      sp->xPhys = 1;
      while( sp->xPhys < sp->xCap ) sp->xPhys <<= 1;
      sp->xMask = sp->xPhys - 1;
      sp->x_inHigh = (double *)TA_Malloc( sizeof(double) * (size_t)sp->xPhys );
      if( !sp->x_inHigh ) { TA_FISHER_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
      sp->x_inLow = (double *)TA_Malloc( sizeof(double) * (size_t)sp->xPhys );
      if( !sp->x_inLow ) { TA_FISHER_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
      { int fillJ;
        for( fillJ = historyLen - sp->xCap; fillJ < historyLen; fillJ++ )
        {
           sp->x_inHigh[fillJ & sp->xMask] = inHigh[fillJ];
           sp->x_inLow[fillJ & sp->xMask] = inLow[fillJ];
        }
      }
      sp->outRangeBegIdx = *outBegIdx;
      sp->outRangeCount = *outNBElement;
      sp->cur_outFisher = outFisher[(*outNBElement - 1) * outStride];
      sp->cur_outTrigger = outTrigger[(*outNBElement - 1) * outStride];
      *stream = sp;
      return TA_SUCCESS;
   }
}

TA_FMA_OPEN_CLONE static TA_RetCode TA_FISHER_OpenImplFma( struct TA_FISHER_Stream **stream, const double inHigh[], const double inLow[], int startIdx, int historyLen, int optInTimePeriod, int *outBegIdx, int *outNBElement, double outFisher[], double outTrigger[], int outStride )
{
   return TA_FISHER_OpenImpl( stream, inHigh, inLow, startIdx, historyLen, optInTimePeriod, outBegIdx, outNBElement, outFisher, outTrigger, outStride );
}

TA_FMA_OPEN_PLAIN static TA_RetCode TA_FISHER_OpenImplPlain( struct TA_FISHER_Stream **stream, const double inHigh[], const double inLow[], int startIdx, int historyLen, int optInTimePeriod, int *outBegIdx, int *outNBElement, double outFisher[], double outTrigger[], int outStride )
{
   return TA_FISHER_OpenImpl( stream, inHigh, inLow, startIdx, historyLen, optInTimePeriod, outBegIdx, outNBElement, outFisher, outTrigger, outStride );
}

/* Private function, not in public API. */
TA_RetCode TA_FISHER_OpenInternal( struct TA_FISHER_Stream **stream, const double inHigh[], const double inLow[], int startIdx, int historyLen, int optInTimePeriod, double *outFisher, double *outTrigger )
{
   TA_RetCode retCode;
   int dummyBegIdx = 0;
   int dummyNBElement = 0;
   double sink_outFisher = 0.0;
   double sink_outTrigger = 0.0;
   retCode = TA_FMA_AVAILABLE ? TA_FISHER_OpenImplFma( stream, inHigh, inLow, startIdx, historyLen, optInTimePeriod, &dummyBegIdx, &dummyNBElement, &sink_outFisher, &sink_outTrigger, 0 ) : TA_FISHER_OpenImplPlain( stream, inHigh, inLow, startIdx, historyLen, optInTimePeriod, &dummyBegIdx, &dummyNBElement, &sink_outFisher, &sink_outTrigger, 0 );
   if( retCode == TA_SUCCESS )
   {
      *outFisher = sink_outFisher;
      *outTrigger = sink_outTrigger;
   }
   return retCode;
}

TA_LIB_API TA_RetCode TA_FISHER_Open( TA_FISHER_Stream **stream, const double inHigh[], const double inLow[], int historyLen, int optInTimePeriod, double *outFisher, double *outTrigger )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_INDEX_MAX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !outFisher || !outTrigger ) return TA_BAD_PARAM;
   return TA_FISHER_OpenInternal( stream, inHigh, inLow, 0, historyLen, optInTimePeriod, outFisher, outTrigger );
}

TA_LIB_API TA_RetCode TA_FISHER_OpenAndFill( TA_FISHER_Stream **stream, const double inHigh[], const double inLow[], int historyLen, int optInTimePeriod, int *outBegIdx, int *outNBElement, double outFisher[], double outTrigger[] )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_INDEX_MAX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !outBegIdx || !outNBElement || !outFisher || !outTrigger ) return TA_BAD_PARAM;
   if( (const void *)outFisher == (const void *)inHigh || (const void *)outFisher == (const void *)inLow || (const void *)outTrigger == (const void *)inHigh || (const void *)outTrigger == (const void *)inLow || (const void *)outFisher == (const void *)outTrigger ) return TA_BAD_PARAM;
   return TA_FISHER_OpenAndFillInternal( stream, inHigh, inLow, 0, historyLen, optInTimePeriod, outBegIdx, outNBElement, outFisher, outTrigger );
}

/* Private function, not in public API. */
TA_RetCode TA_FISHER_OpenAndFillInternal( struct TA_FISHER_Stream **stream, const double inHigh[], const double inLow[], int startIdx, int historyLen, int optInTimePeriod, int *outBegIdx, int *outNBElement, double outFisher[], double outTrigger[] )
{
   return TA_FMA_AVAILABLE ? TA_FISHER_OpenImplFma( stream, inHigh, inLow, startIdx, historyLen, optInTimePeriod, outBegIdx, outNBElement, outFisher, outTrigger, 1 ) : TA_FISHER_OpenImplPlain( stream, inHigh, inLow, startIdx, historyLen, optInTimePeriod, outBegIdx, outNBElement, outFisher, outTrigger, 1 );
}

TA_FMA_MULTIVERSION
TA_LIB_API TA_RetCode TA_FISHER_Update( TA_FISHER_Stream *stream, double inHigh, double inLow, double *outFisher, double *outTrigger )
{
   if( !stream ) return TA_BAD_PARAM;
   if( stream->outRangeBegIdx + stream->outRangeCount > TA_INDEX_MAX )
      return TA_OUT_OF_RANGE_END_INDEX;
   if( !outFisher || !outTrigger ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) ) return TA_BAD_PARAM;
   TA_FISHER_StepImpl( stream, inHigh, inLow, outFisher, outTrigger );
   stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_FMA_MULTIVERSION
TA_LIB_API TA_RetCode TA_FISHER_Peek( const TA_FISHER_Stream *stream, double inHigh, double inLow, double *outFisher, double *outTrigger )
{
   const struct TA_FISHER_Stream *sp = stream;
   double price;
   double ratio;
   double fish;
   double tempReal;
   double tempHigh;
   double tempLow;
   double highest;
   int highestIdx;
   int i;
   double lowest;
   int lowestIdx;
   double smoothed;
   double *x_inHigh;
   double *x_inLow;
   int pkSlot0 = -1;
   double pkVal0 = 0.0;
   int pkSlot1 = -1;
   double pkVal1 = 0.0;

   if( !stream || !outFisher || !outTrigger ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) ) return TA_BAD_PARAM;
   highest = sp->highest;
   highestIdx = sp->highestIdx;
   i = sp->i;
   lowest = sp->lowest;
   lowestIdx = sp->lowestIdx;
   smoothed = sp->smoothed;
   x_inHigh = sp->x_inHigh;
   x_inLow = sp->x_inLow;
   pkSlot0 = sp->today & sp->xMask;
   pkVal0 = inHigh;
   pkSlot1 = sp->today & sp->xMask;
   pkVal1 = inLow;
   /* The channel, over the midpoints rather than over the highs and the
    * lows separately: this indicator reads one series, which happens to be
    * (H+L)/2, so both extremes come from that same series. STOCH's shape,
    * with the midpoint recomputed on the rare rescan rather than held in a
    * buffer the caller would have to own.
    */
   price = ((((sp->today & sp->xMask) != pkSlot0) ? x_inHigh[sp->today & sp->xMask] : pkVal0) + (((sp->today & sp->xMask) != pkSlot1) ? x_inLow[sp->today & sp->xMask] : pkVal1)) / 2.0;
   if( highestIdx < sp->trailingIdx )
   {
      highestIdx = sp->trailingIdx;
      tempHigh = ((highestIdx & sp->xMask) != pkSlot0) ? x_inHigh[highestIdx & sp->xMask] : pkVal0;
      tempLow = ((highestIdx & sp->xMask) != pkSlot1) ? x_inLow[highestIdx & sp->xMask] : pkVal1;
      highest = (tempHigh + tempLow) / 2.0;
      i = highestIdx;
      while( ++i <= sp->today )
      {
         tempHigh = ((i & sp->xMask) != pkSlot0) ? x_inHigh[i & sp->xMask] : pkVal0;
         tempLow = ((i & sp->xMask) != pkSlot1) ? x_inLow[i & sp->xMask] : pkVal1;
         tempReal = (tempHigh + tempLow) / 2.0;
         if( tempReal > highest )
         {
            highestIdx = i;
            highest = tempReal;
         }
      }
   } else if( price >= highest )
   {
      highestIdx = sp->today;
      highest = price;
   }
   if( lowestIdx < sp->trailingIdx )
   {
      lowestIdx = sp->trailingIdx;
      tempHigh = ((lowestIdx & sp->xMask) != pkSlot0) ? x_inHigh[lowestIdx & sp->xMask] : pkVal0;
      tempLow = ((lowestIdx & sp->xMask) != pkSlot1) ? x_inLow[lowestIdx & sp->xMask] : pkVal1;
      lowest = (tempHigh + tempLow) / 2.0;
      i = lowestIdx;
      while( ++i <= sp->today )
      {
         tempHigh = ((i & sp->xMask) != pkSlot0) ? x_inHigh[i & sp->xMask] : pkVal0;
         tempLow = ((i & sp->xMask) != pkSlot1) ? x_inLow[i & sp->xMask] : pkVal1;
         tempReal = (tempHigh + tempLow) / 2.0;
         if( tempReal < lowest )
         {
            lowestIdx = i;
            lowest = tempReal;
         }
      }
   } else if( price <= lowest )
   {
      lowestIdx = sp->today;
      lowest = price;
   }
   /* A flat window answers the neutral position rather than dividing by
    * its own zero range. The band is the range against its own two
    * extremes, STOCH's test: a fixed constant answers "flat" for every
    * window of an instrument quoted below it (#253), and an exact test
    * divides a machine-flat window into noise (#107). At 0.5 the bar
    * contributes nothing and both recursions decay on their own
    * coefficients.
    */
   tempReal = highest - lowest;
   if( !TA_IS_ZERO_SCALED(tempReal, fabs(highest) + fabs(lowest)) )
   {
      ratio = (price - lowest) / tempReal;
   } else 
   {
      ratio = 0.5;
   }
   /* The listing's .33*2*(r-.5) + .67*Value1[1]. */
   smoothed = fma(0.67, smoothed, 0.33 * 2.0 * (ratio - 0.5));
   /* The clamp is what keeps atanh finite, and the CLAMPED smoothed is what
    * the next bar's smoothing reads -- the listing assigns it back to
    * Value1 rather than holding it for the transform alone.
    */
   if( smoothed > 0.99 )
   {
      smoothed = 0.999;
   }
   if( smoothed < -0.99 )
   {
      smoothed = -0.999;
   }
   fish = fma(0.5, log((1.0 + smoothed) / (1.0 - smoothed)), 0.5 * sp->prevFish);
   *outFisher= fish;
   /* The author's second plot is Fish[1]: the previous bar's smoothed,
    * which at the first output bar is the zero seed when no unstable
    * period was discarded, and the computed smoothed of the bar before it
    * when one was.
    */
   *outTrigger= sp->prevFish;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_FISHER_Close( TA_FISHER_Stream *stream )
{
   TA_FISHER_ReleaseImpl( stream );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_FISHER_Value( const TA_FISHER_Stream *stream, double *outFisher, double *outTrigger )
{
   if( !stream || !outFisher || !outTrigger ) return TA_BAD_PARAM;
   *outFisher = stream->cur_outFisher;
   *outTrigger = stream->cur_outTrigger;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_FISHER_OutRange( const TA_FISHER_Stream *stream, int *outBegIdx, int *outNBElement )
{
   if( !stream || !outBegIdx || !outNBElement ) return TA_BAD_PARAM;
   *outBegIdx = stream->outRangeBegIdx;
   *outNBElement = stream->outRangeCount;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_FISHER_Advance( TA_FISHER_Stream *stream )
{
   if( !stream ) return TA_BAD_PARAM;
   if( stream->outRangeBegIdx + stream->outRangeCount > TA_INDEX_MAX )
      return TA_OUT_OF_RANGE_END_INDEX;
   stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_FISHER_Clone( const TA_FISHER_Stream *stream, TA_FISHER_Stream **clone )
{
   struct TA_FISHER_Stream *sp;

   if( !clone ) return TA_BAD_PARAM;
   *clone = NULL;
   if( !stream ) return TA_BAD_PARAM;
   sp = (struct TA_FISHER_Stream *)TA_Malloc( sizeof(*sp) );
   if( !sp ) return TA_ALLOC_ERR;
   *sp = *stream;
   sp->x_inHigh = NULL;
   sp->x_inLow = NULL;
   if( stream->x_inHigh )
   { size_t copyN = (size_t)(sp->xPhys);
     sp->x_inHigh = (double *)TA_Malloc( sizeof(double) * copyN );
     if( !sp->x_inHigh ) { TA_FISHER_Close( sp ); return TA_ALLOC_ERR; }
     memcpy( sp->x_inHigh, stream->x_inHigh, sizeof(double) * copyN ); }
   if( stream->x_inLow )
   { size_t copyN = (size_t)(sp->xPhys);
     sp->x_inLow = (double *)TA_Malloc( sizeof(double) * copyN );
     if( !sp->x_inLow ) { TA_FISHER_Close( sp ); return TA_ALLOC_ERR; }
     memcpy( sp->x_inLow, stream->x_inLow, sizeof(double) * copyN ); }
   *clone = sp;
   return TA_SUCCESS;
}

