/* TA-LIB Copyright (c) 1999-2026, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_stream_private.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  MF       Mario Fortier
 *  CC       Claude Code (AI assistant)
 *
 * Change history:
 *
 *  MMDDYY BY     Description
 *  -------------------------------------------------------------------
 *  090526 MF,CC  Initial version (#371).
 */

TA_LIB_API int TA_FRACTAL_Lookback( int optInLeftBars, int optInRightBars )
{
   if( (int)optInLeftBars == TA_INTEGER_DEFAULT )
      optInLeftBars = 2;
   else if( (int)optInLeftBars < 1 || (int)optInLeftBars > 100000 )
      return -1;
   if( (int)optInRightBars == TA_INTEGER_DEFAULT )
      optInRightBars = 2;
   else if( (int)optInRightBars < 1 || (int)optInRightBars > 100000 )
      return -1;
   return optInLeftBars + optInRightBars;
}

TA_LIB_API TA_RetCode TA_FRACTAL( int    startIdx,
                                  int    endIdx,
                                  const double inHigh[],
                                  const double inLow[],
                                  int optInLeftBars,
                                  int optInRightBars,
                                  int          *outBegIdx,
                                  int          *outNBElement,
                                  int        outSwingHigh[],
                                  int        outSwingLow[] )
{
   int today;
   int outIdx;
   int lookbackTotal;
   int i;
   double pivotHigh;
   double pivotLow;
   double otherHigh;
   double otherLow;
   double tempHigh;
   double tempLow;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInLeftBars == TA_INTEGER_DEFAULT )
      optInLeftBars = 2;
   else if( (int)optInLeftBars < 1 || (int)optInLeftBars > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInRightBars == TA_INTEGER_DEFAULT )
      optInRightBars = 2;
   else if( (int)optInRightBars < 1 || (int)optInRightBars > 100000 )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outSwingHigh )
      return TA_BAD_PARAM;
   if( !outSwingLow )
      return TA_BAD_PARAM;
   if( outSwingHigh == outSwingLow )
      return TA_BAD_PARAM;

   *outBegIdx= 0;
   *outNBElement= 0;
   lookbackTotal = TA_FRACTAL_Lookback(optInLeftBars,optInRightBars);
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   /* Make sure there is still something to evaluate. */
   if( startIdx > endIdx )
   {
      return TA_SUCCESS;
   }
   outIdx = 0;
   today = startIdx;
   while( today <= endIdx )
   {
      pivotHigh = 0.0;
      pivotLow = 0.0;
      otherHigh = 0.0;
      otherLow = 0.0;
      for( i = optInLeftBars + optInRightBars; i >= 0; i -= 1 )
      {
         tempHigh = inHigh[today - i];
         tempLow = inLow[today - i];
         if( i == optInRightBars )
         {
            pivotHigh = tempHigh;
            pivotLow = tempLow;
         } else if( i == optInLeftBars + optInRightBars )
         {
            /* optInLeftBars is at least 1, so the oldest bar of the window is
             * never the pivot and always seeds the rest-of-window extrema.
             */
            otherHigh = tempHigh;
            otherLow = tempLow;
         } else 
         {
            if( tempHigh > otherHigh )
            {
               otherHigh = tempHigh;
            }
            if( tempLow < otherLow )
            {
               otherLow = tempLow;
            }
         }
      }
      if( pivotHigh > otherHigh )
      {
         outSwingHigh[outIdx] = 100;
      } else 
      {
         outSwingHigh[outIdx] = 0;
      }
      if( pivotLow < otherLow )
      {
         outSwingLow[outIdx] = 100;
      } else 
      {
         outSwingLow[outIdx] = 0;
      }
      outIdx += 1;
      today += 1;
   }
   *outBegIdx= startIdx;
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

TA_RetCode TA_S_FRACTAL( int    startIdx,
                         int    endIdx,
                         const float inHigh[],
                         const float inLow[],
                         int optInLeftBars,
                         int optInRightBars,
                         int          *outBegIdx,
                         int          *outNBElement,
                         int        outSwingHigh[],
                         int        outSwingLow[] )
{
   int today;
   int outIdx;
   int lookbackTotal;
   int i;
   double pivotHigh;
   double pivotLow;
   double otherHigh;
   double otherLow;
   double tempHigh;
   double tempLow;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInLeftBars == TA_INTEGER_DEFAULT )
      optInLeftBars = 2;
   else if( (int)optInLeftBars < 1 || (int)optInLeftBars > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInRightBars == TA_INTEGER_DEFAULT )
      optInRightBars = 2;
   else if( (int)optInRightBars < 1 || (int)optInRightBars > 100000 )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outSwingHigh )
      return TA_BAD_PARAM;
   if( !outSwingLow )
      return TA_BAD_PARAM;
   if( outSwingHigh == outSwingLow )
      return TA_BAD_PARAM;

   *outBegIdx= 0;
   *outNBElement= 0;
   lookbackTotal = TA_FRACTAL_Lookback(optInLeftBars,optInRightBars);
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   if( startIdx > endIdx )
   {
      return TA_SUCCESS;
   }
   outIdx = 0;
   today = startIdx;
   while( today <= endIdx )
   {
      pivotHigh = 0.0;
      pivotLow = 0.0;
      otherHigh = 0.0;
      otherLow = 0.0;
      for( i = optInLeftBars + optInRightBars; i >= 0; i -= 1 )
      {
         tempHigh = (double)inHigh[today - i];
         tempLow = (double)inLow[today - i];
         if( i == optInRightBars )
         {
            pivotHigh = tempHigh;
            pivotLow = tempLow;
         } else if( i == optInLeftBars + optInRightBars )
         {
            otherHigh = tempHigh;
            otherLow = tempLow;
         } else 
         {
            if( tempHigh > otherHigh )
            {
               otherHigh = tempHigh;
            }
            if( tempLow < otherLow )
            {
               otherLow = tempLow;
            }
         }
      }
      if( pivotHigh > otherHigh )
      {
         outSwingHigh[outIdx] = 100;
      } else 
      {
         outSwingHigh[outIdx] = 0;
      }
      if( pivotLow < otherLow )
      {
         outSwingLow[outIdx] = 100;
      } else 
      {
         outSwingLow[outIdx] = 0;
      }
      outIdx += 1;
      today += 1;
   }
   *outBegIdx= startIdx;
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

/**** Streaming API *****/

struct TA_FRACTAL_Stream {
   /* The bars this handle has an output for (see TA_FRACTAL_OutRange). */
   int outRangeBegIdx;
   int outRangeCount;
   /* The value(s) at the last bar the stream counted (see TA_FRACTAL_Value). */
   int cur_outSwingHigh;
   int cur_outSwingLow;
   int optInLeftBars;
   int optInRightBars;
   int winPos_i;
   int winCap_i;
   double *win_i_inHigh;
   double *win_i_inLow;
};

/* Private function, not in public API. */
static void TA_FRACTAL_ReleaseImpl( struct TA_FRACTAL_Stream *sp )
{
   if( !sp ) return;
   if( sp->win_i_inHigh ) TA_Free( sp->win_i_inHigh );
   if( sp->win_i_inLow ) TA_Free( sp->win_i_inLow );
   TA_Free( sp );
}

/* Private function, not in public API. */
static void TA_FRACTAL_StepImpl( struct TA_FRACTAL_Stream *sp, double inHigh, double inLow, int *outSwingHigh, int *outSwingLow )
{
   int i;
   double pivotHigh;
   double pivotLow;
   double otherHigh;
   double otherLow;
   double tempHigh;
   double tempLow;

   sp->win_i_inHigh[sp->winPos_i] = inHigh;
   sp->win_i_inLow[sp->winPos_i] = inLow;
   pivotHigh = 0.0;
   pivotLow = 0.0;
   otherHigh = 0.0;
   otherLow = 0.0;
   for( i = sp->optInLeftBars + sp->optInRightBars; i >= 0; i -= 1 )
   {
      tempHigh = sp->win_i_inHigh[(sp->winPos_i + sp->winCap_i - i >= sp->winCap_i) ? sp->winPos_i + sp->winCap_i - i - sp->winCap_i : sp->winPos_i + sp->winCap_i - i];
      tempLow = sp->win_i_inLow[(sp->winPos_i + sp->winCap_i - i >= sp->winCap_i) ? sp->winPos_i + sp->winCap_i - i - sp->winCap_i : sp->winPos_i + sp->winCap_i - i];
      if( i == sp->optInRightBars )
      {
         pivotHigh = tempHigh;
         pivotLow = tempLow;
      } else if( i == sp->optInLeftBars + sp->optInRightBars )
      {
         /* optInLeftBars is at least 1, so the oldest bar of the window is
          * never the pivot and always seeds the rest-of-window extrema.
          */
         otherHigh = tempHigh;
         otherLow = tempLow;
      } else 
      {
         if( tempHigh > otherHigh )
         {
            otherHigh = tempHigh;
         }
         if( tempLow < otherLow )
         {
            otherLow = tempLow;
         }
      }
   }
   if( pivotHigh > otherHigh )
   {
      *outSwingHigh= 100;
   } else 
   {
      *outSwingHigh= 0;
   }
   if( pivotLow < otherLow )
   {
      *outSwingLow= 100;
   } else 
   {
      *outSwingLow= 0;
   }
   sp->cur_outSwingHigh = *outSwingHigh;
   sp->cur_outSwingLow = *outSwingLow;
   sp->winPos_i = sp->winPos_i + 1;
   if( sp->winPos_i >= sp->winCap_i )
   {
      sp->winPos_i = 0;
   }
}

static TA_RetCode TA_FRACTAL_OpenImpl( struct TA_FRACTAL_Stream **stream, const double inHigh[], const double inLow[], int startIdx, int historyLen, int optInLeftBars, int optInRightBars, int *outBegIdx, int *outNBElement, int outSwingHigh[], int outSwingLow[], int outStride )
{
   struct TA_FRACTAL_Stream *sp;
   int endIdx;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !outSwingHigh || !outSwingLow ) return TA_BAD_PARAM;
   if( (int)optInLeftBars == TA_INTEGER_DEFAULT )
      optInLeftBars = 2;
   else if( (int)optInLeftBars < 1 || (int)optInLeftBars > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInRightBars == TA_INTEGER_DEFAULT )
      optInRightBars = 2;
   else if( (int)optInRightBars < 1 || (int)optInRightBars > 100000 )
      return TA_BAD_PARAM;
   if( startIdx > historyLen - 1 )
   {
      *outBegIdx = 0;
      *outNBElement = 0;
      return TA_INSUFFICIENT_HISTORY;
   }

   endIdx = historyLen - 1;

   {
      int today;
      int outIdx;
      int lookbackTotal;
      int i;
      double pivotHigh;
      double pivotLow;
      double otherHigh;
      double otherLow;
      double tempHigh;
      double tempLow;
      *outBegIdx= 0;
      *outNBElement= 0;
      lookbackTotal = TA_FRACTAL_Lookback(optInLeftBars,optInRightBars);
      if( startIdx < lookbackTotal )
      {
         startIdx = lookbackTotal;
      }
      /* Make sure there is still something to evaluate. */
      if( startIdx > endIdx )
      {
         return TA_INSUFFICIENT_HISTORY;
      }
      outIdx = 0;
      today = startIdx;
      while( today <= endIdx )
      {
         pivotHigh = 0.0;
         pivotLow = 0.0;
         otherHigh = 0.0;
         otherLow = 0.0;
         for( i = optInLeftBars + optInRightBars; i >= 0; i -= 1 )
         {
            tempHigh = inHigh[today - i];
            tempLow = inLow[today - i];
            if( i == optInRightBars )
            {
               pivotHigh = tempHigh;
               pivotLow = tempLow;
            } else if( i == optInLeftBars + optInRightBars )
            {
               /* optInLeftBars is at least 1, so the oldest bar of the window is
                * never the pivot and always seeds the rest-of-window extrema.
                */
               otherHigh = tempHigh;
               otherLow = tempLow;
            } else 
            {
               if( tempHigh > otherHigh )
               {
                  otherHigh = tempHigh;
               }
               if( tempLow < otherLow )
               {
                  otherLow = tempLow;
               }
            }
         }
         if( pivotHigh > otherHigh )
         {
            outSwingHigh[outIdx * outStride] = 100;
         } else 
         {
            outSwingHigh[outIdx * outStride] = 0;
         }
         if( pivotLow < otherLow )
         {
            outSwingLow[outIdx * outStride] = 100;
         } else 
         {
            outSwingLow[outIdx * outStride] = 0;
         }
         outIdx += 1;
         today += 1;
      }
      *outBegIdx= startIdx;
      *outNBElement= outIdx;

      /* Capture the live batch state into the handle. */
      sp = (struct TA_FRACTAL_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) { return TA_ALLOC_ERR; }
      memset( sp, 0, sizeof(*sp) );
      sp->optInLeftBars = optInLeftBars;
      sp->optInRightBars = optInRightBars;
      sp->winCap_i = (int)(optInLeftBars + optInRightBars + 1);
      if( sp->winCap_i < 1 || sp->winCap_i > historyLen ) { TA_FRACTAL_ReleaseImpl( sp ); return TA_INTERNAL_ERROR(427); }
      sp->win_i_inHigh = (double *)TA_Malloc( sizeof(double) * (size_t)sp->winCap_i );
      if( !sp->win_i_inHigh ) { TA_FRACTAL_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
      memcpy( sp->win_i_inHigh, inHigh + (historyLen - sp->winCap_i), sizeof(double) * (size_t)sp->winCap_i );
      sp->win_i_inLow = (double *)TA_Malloc( sizeof(double) * (size_t)sp->winCap_i );
      if( !sp->win_i_inLow ) { TA_FRACTAL_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
      memcpy( sp->win_i_inLow, inLow + (historyLen - sp->winCap_i), sizeof(double) * (size_t)sp->winCap_i );
      sp->winPos_i = 0;
      sp->outRangeBegIdx = *outBegIdx;
      sp->outRangeCount = *outNBElement;
      sp->cur_outSwingHigh = outSwingHigh[(*outNBElement - 1) * outStride];
      sp->cur_outSwingLow = outSwingLow[(*outNBElement - 1) * outStride];
      *stream = sp;
      return TA_SUCCESS;
   }
}

/* Private function, not in public API. */
TA_RetCode TA_FRACTAL_OpenInternal( struct TA_FRACTAL_Stream **stream, const double inHigh[], const double inLow[], int startIdx, int historyLen, int optInLeftBars, int optInRightBars, int *outSwingHigh, int *outSwingLow )
{
   TA_RetCode retCode;
   int dummyBegIdx = 0;
   int dummyNBElement = 0;
   int sink_outSwingHigh = 0;
   int sink_outSwingLow = 0;
   retCode = TA_FRACTAL_OpenImpl( stream, inHigh, inLow, startIdx, historyLen, optInLeftBars, optInRightBars, &dummyBegIdx, &dummyNBElement, &sink_outSwingHigh, &sink_outSwingLow, 0 );
   if( retCode == TA_SUCCESS )
   {
      *outSwingHigh = sink_outSwingHigh;
      *outSwingLow = sink_outSwingLow;
   }
   return retCode;
}

TA_LIB_API TA_RetCode TA_FRACTAL_Open( TA_FRACTAL_Stream **stream, const double inHigh[], const double inLow[], int historyLen, int optInLeftBars, int optInRightBars, int *outSwingHigh, int *outSwingLow )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !outSwingHigh || !outSwingLow ) return TA_BAD_PARAM;
   return TA_FRACTAL_OpenInternal( stream, inHigh, inLow, 0, historyLen, optInLeftBars, optInRightBars, outSwingHigh, outSwingLow );
}

TA_LIB_API TA_RetCode TA_FRACTAL_OpenAndFill( TA_FRACTAL_Stream **stream, const double inHigh[], const double inLow[], int historyLen, int optInLeftBars, int optInRightBars, int *outBegIdx, int *outNBElement, int outSwingHigh[], int outSwingLow[] )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !outBegIdx || !outNBElement || !outSwingHigh || !outSwingLow ) return TA_BAD_PARAM;
   if( (const void *)outSwingHigh == (const void *)inHigh || (const void *)outSwingHigh == (const void *)inLow || (const void *)outSwingLow == (const void *)inHigh || (const void *)outSwingLow == (const void *)inLow || (const void *)outSwingHigh == (const void *)outSwingLow ) return TA_BAD_PARAM;
   return TA_FRACTAL_OpenAndFillInternal( stream, inHigh, inLow, 0, historyLen, optInLeftBars, optInRightBars, outBegIdx, outNBElement, outSwingHigh, outSwingLow );
}

/* Private function, not in public API. */
TA_RetCode TA_FRACTAL_OpenAndFillInternal( struct TA_FRACTAL_Stream **stream, const double inHigh[], const double inLow[], int startIdx, int historyLen, int optInLeftBars, int optInRightBars, int *outBegIdx, int *outNBElement, int outSwingHigh[], int outSwingLow[] )
{
   return TA_FRACTAL_OpenImpl( stream, inHigh, inLow, startIdx, historyLen, optInLeftBars, optInRightBars, outBegIdx, outNBElement, outSwingHigh, outSwingLow, 1 );
}

TA_LIB_API TA_RetCode TA_FRACTAL_Update( TA_FRACTAL_Stream *stream, double inHigh, double inLow, int *outSwingHigh, int *outSwingLow )
{
   if( !stream || !outSwingHigh || !outSwingLow ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) ) return TA_BAD_PARAM;
   TA_FRACTAL_StepImpl( stream, inHigh, inLow, outSwingHigh, outSwingLow );
   if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_FRACTAL_Peek( const TA_FRACTAL_Stream *stream, double inHigh, double inLow, int *outSwingHigh, int *outSwingLow )
{
   const struct TA_FRACTAL_Stream *sp = stream;
   int i;
   double pivotHigh;
   double pivotLow;
   double otherHigh;
   double otherLow;
   double tempHigh;
   double tempLow;
   double *win_i_inHigh;
   double *win_i_inLow;
   int pkSlot0 = -1;
   double pkVal0 = 0.0;
   int pkSlot1 = -1;
   double pkVal1 = 0.0;

   if( !stream || !outSwingHigh || !outSwingLow ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) ) return TA_BAD_PARAM;
   win_i_inHigh = sp->win_i_inHigh;
   win_i_inLow = sp->win_i_inLow;
   pkSlot0 = sp->winPos_i;
   pkVal0 = inHigh;
   pkSlot1 = sp->winPos_i;
   pkVal1 = inLow;
   pivotHigh = 0.0;
   pivotLow = 0.0;
   otherHigh = 0.0;
   otherLow = 0.0;
   for( i = sp->optInLeftBars + sp->optInRightBars; i >= 0; i -= 1 )
   {
      tempHigh = (((sp->winPos_i + sp->winCap_i - i >= sp->winCap_i) ? sp->winPos_i + sp->winCap_i - i - sp->winCap_i : sp->winPos_i + sp->winCap_i - i) != pkSlot0) ? win_i_inHigh[(sp->winPos_i + sp->winCap_i - i >= sp->winCap_i) ? sp->winPos_i + sp->winCap_i - i - sp->winCap_i : sp->winPos_i + sp->winCap_i - i] : pkVal0;
      tempLow = (((sp->winPos_i + sp->winCap_i - i >= sp->winCap_i) ? sp->winPos_i + sp->winCap_i - i - sp->winCap_i : sp->winPos_i + sp->winCap_i - i) != pkSlot1) ? win_i_inLow[(sp->winPos_i + sp->winCap_i - i >= sp->winCap_i) ? sp->winPos_i + sp->winCap_i - i - sp->winCap_i : sp->winPos_i + sp->winCap_i - i] : pkVal1;
      if( i == sp->optInRightBars )
      {
         pivotHigh = tempHigh;
         pivotLow = tempLow;
      } else if( i == sp->optInLeftBars + sp->optInRightBars )
      {
         /* optInLeftBars is at least 1, so the oldest bar of the window is
          * never the pivot and always seeds the rest-of-window extrema.
          */
         otherHigh = tempHigh;
         otherLow = tempLow;
      } else 
      {
         if( tempHigh > otherHigh )
         {
            otherHigh = tempHigh;
         }
         if( tempLow < otherLow )
         {
            otherLow = tempLow;
         }
      }
   }
   if( pivotHigh > otherHigh )
   {
      *outSwingHigh= 100;
   } else 
   {
      *outSwingHigh= 0;
   }
   if( pivotLow < otherLow )
   {
      *outSwingLow= 100;
   } else 
   {
      *outSwingLow= 0;
   }
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_FRACTAL_Close( TA_FRACTAL_Stream *stream )
{
   TA_FRACTAL_ReleaseImpl( stream );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_FRACTAL_Value( const TA_FRACTAL_Stream *stream, int *outSwingHigh, int *outSwingLow )
{
   if( !stream || !outSwingHigh || !outSwingLow ) return TA_BAD_PARAM;
   *outSwingHigh = stream->cur_outSwingHigh;
   *outSwingLow = stream->cur_outSwingLow;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_FRACTAL_OutRange( const TA_FRACTAL_Stream *stream, int *outBegIdx, int *outNBElement )
{
   if( !stream || !outBegIdx || !outNBElement ) return TA_BAD_PARAM;
   *outBegIdx = stream->outRangeBegIdx;
   *outNBElement = stream->outRangeCount;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_FRACTAL_Advance( TA_FRACTAL_Stream *stream )
{
   if( !stream ) return TA_BAD_PARAM;
   if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_FRACTAL_Clone( const TA_FRACTAL_Stream *stream, TA_FRACTAL_Stream **clone )
{
   struct TA_FRACTAL_Stream *sp;

   if( !clone ) return TA_BAD_PARAM;
   *clone = NULL;
   if( !stream ) return TA_BAD_PARAM;
   sp = (struct TA_FRACTAL_Stream *)TA_Malloc( sizeof(*sp) );
   if( !sp ) return TA_ALLOC_ERR;
   *sp = *stream;
   sp->win_i_inHigh = NULL;
   sp->win_i_inLow = NULL;
   if( stream->win_i_inHigh )
   { size_t copyN = (size_t)(sp->winCap_i);
     sp->win_i_inHigh = (double *)TA_Malloc( sizeof(double) * copyN );
     if( !sp->win_i_inHigh ) { TA_FRACTAL_Close( sp ); return TA_ALLOC_ERR; }
     memcpy( sp->win_i_inHigh, stream->win_i_inHigh, sizeof(double) * copyN ); }
   if( stream->win_i_inLow )
   { size_t copyN = (size_t)(sp->winCap_i);
     sp->win_i_inLow = (double *)TA_Malloc( sizeof(double) * copyN );
     if( !sp->win_i_inLow ) { TA_FRACTAL_Close( sp ); return TA_ALLOC_ERR; }
     memcpy( sp->win_i_inLow, stream->win_i_inLow, sizeof(double) * copyN ); }
   *clone = sp;
   return TA_SUCCESS;
}

