/* TA-LIB Copyright (c) 1999-2026, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_stream_private.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  MF       Mario Fortier
 *  CC       Claude Code (AI assistant)
 *
 * Change history:
 *
 *  MMDDYY BY     Description
 *  -------------------------------------------------------------------
 *  090426 MF,CC  First version (issue #365).
 */

TA_LIB_API int TA_KDJ_Lookback( int optInFastK_Period, int optInSlowK_Period, TA_MAType optInSlowK_MAType, int optInSlowD_Period, TA_MAType optInSlowD_MAType )
{
   if( (int)optInFastK_Period == TA_INTEGER_DEFAULT )
      optInFastK_Period = 9;
   else if( (int)optInFastK_Period < 1 || (int)optInFastK_Period > 100000 )
      return -1;
   if( (int)optInSlowK_Period == TA_INTEGER_DEFAULT )
      optInSlowK_Period = 3;
   else if( (int)optInSlowK_Period < 1 || (int)optInSlowK_Period > 100000 )
      return -1;
   if( (int)optInSlowK_MAType == TA_INTEGER_DEFAULT || optInSlowK_MAType == TA_MAType_DEFAULT )
      optInSlowK_MAType = 13;
   else if( (int)optInSlowK_MAType < TA_MATYPE_MIN || (int)optInSlowK_MAType > TA_MATYPE_MAX )
      return -1;
   if( (int)optInSlowD_Period == TA_INTEGER_DEFAULT )
      optInSlowD_Period = 3;
   else if( (int)optInSlowD_Period < 1 || (int)optInSlowD_Period > 100000 )
      return -1;
   if( (int)optInSlowD_MAType == TA_INTEGER_DEFAULT || optInSlowD_MAType == TA_MAType_DEFAULT )
      optInSlowD_MAType = 13;
   else if( (int)optInSlowD_MAType < TA_MATYPE_MIN || (int)optInSlowD_MAType > TA_MATYPE_MAX )
      return -1;
   return TA_STOCH_Lookback(optInFastK_Period,optInSlowK_Period,optInSlowK_MAType,optInSlowD_Period,optInSlowD_MAType);
}

TA_LIB_API TA_RetCode TA_KDJ( int    startIdx,
                              int    endIdx,
                              const double inHigh[],
                              const double inLow[],
                              const double inClose[],
                              int optInFastK_Period,
                              int optInSlowK_Period,
                              TA_MAType optInSlowK_MAType,
                              int optInSlowD_Period,
                              TA_MAType optInSlowD_MAType,
                              int          *outBegIdx,
                              int          *outNBElement,
                              double        outK[],
                              double        outD[],
                              double        outJ[] )
{
   TA_RetCode retCode;
   int i;
   int lookbackTotal;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInFastK_Period == TA_INTEGER_DEFAULT )
      optInFastK_Period = 9;
   else if( (int)optInFastK_Period < 1 || (int)optInFastK_Period > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInSlowK_Period == TA_INTEGER_DEFAULT )
      optInSlowK_Period = 3;
   else if( (int)optInSlowK_Period < 1 || (int)optInSlowK_Period > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInSlowK_MAType == TA_INTEGER_DEFAULT || optInSlowK_MAType == TA_MAType_DEFAULT )
      optInSlowK_MAType = 13;
   else if( (int)optInSlowK_MAType < TA_MATYPE_MIN || (int)optInSlowK_MAType > TA_MATYPE_MAX )
      return TA_BAD_PARAM;
   if( (int)optInSlowD_Period == TA_INTEGER_DEFAULT )
      optInSlowD_Period = 3;
   else if( (int)optInSlowD_Period < 1 || (int)optInSlowD_Period > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInSlowD_MAType == TA_INTEGER_DEFAULT || optInSlowD_MAType == TA_MAType_DEFAULT )
      optInSlowD_MAType = 13;
   else if( (int)optInSlowD_MAType < TA_MATYPE_MIN || (int)optInSlowD_MAType > TA_MATYPE_MAX )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !inClose )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outK )
      return TA_BAD_PARAM;
   if( !outD )
      return TA_BAD_PARAM;
   if( !outJ )
      return TA_BAD_PARAM;
   if( outK == outD || outK == outJ || outD == outJ )
      return TA_BAD_PARAM;

   lookbackTotal = TA_KDJ_Lookback(optInFastK_Period,optInSlowK_Period,optInSlowK_MAType,optInSlowD_Period,optInSlowD_MAType);
   /* Nothing to produce: the range is shorter than the lookback. Answering here
    * keeps the sub-call out of the phantom-I/O sweep's zero-length range, where
    * its own argument check would reject before any array is touched.
    */
   if( lookbackTotal > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   retCode = TA_STOCH(startIdx,endIdx,inHigh,inLow,inClose,optInFastK_Period,optInSlowK_Period,optInSlowK_MAType,optInSlowD_Period,optInSlowD_MAType,outBegIdx,outNBElement,outK,outD);
   if( retCode != TA_SUCCESS || (int)*outNBElement == 0 )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return retCode;
   }
   /* Keep this one Sub expression: spelling it as an Add of a negated term
    * would arm the multiply-add fusion and move the last bits of J.
    */
   for( i = 0; i < (int)*outNBElement; i += 1 )
   {
      outJ[i] = 3.0 * outK[i] - 2.0 * outD[i];
   }
   return TA_SUCCESS;
}

TA_RetCode TA_S_KDJ( int    startIdx,
                     int    endIdx,
                     const float inHigh[],
                     const float inLow[],
                     const float inClose[],
                     int optInFastK_Period,
                     int optInSlowK_Period,
                     TA_MAType optInSlowK_MAType,
                     int optInSlowD_Period,
                     TA_MAType optInSlowD_MAType,
                     int          *outBegIdx,
                     int          *outNBElement,
                     double        outK[],
                     double        outD[],
                     double        outJ[] )
{
   TA_RetCode retCode;
   int i;
   int lookbackTotal;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInFastK_Period == TA_INTEGER_DEFAULT )
      optInFastK_Period = 9;
   else if( (int)optInFastK_Period < 1 || (int)optInFastK_Period > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInSlowK_Period == TA_INTEGER_DEFAULT )
      optInSlowK_Period = 3;
   else if( (int)optInSlowK_Period < 1 || (int)optInSlowK_Period > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInSlowK_MAType == TA_INTEGER_DEFAULT || optInSlowK_MAType == TA_MAType_DEFAULT )
      optInSlowK_MAType = 13;
   else if( (int)optInSlowK_MAType < TA_MATYPE_MIN || (int)optInSlowK_MAType > TA_MATYPE_MAX )
      return TA_BAD_PARAM;
   if( (int)optInSlowD_Period == TA_INTEGER_DEFAULT )
      optInSlowD_Period = 3;
   else if( (int)optInSlowD_Period < 1 || (int)optInSlowD_Period > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInSlowD_MAType == TA_INTEGER_DEFAULT || optInSlowD_MAType == TA_MAType_DEFAULT )
      optInSlowD_MAType = 13;
   else if( (int)optInSlowD_MAType < TA_MATYPE_MIN || (int)optInSlowD_MAType > TA_MATYPE_MAX )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !inClose )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outK )
      return TA_BAD_PARAM;
   if( !outD )
      return TA_BAD_PARAM;
   if( !outJ )
      return TA_BAD_PARAM;
   if( outK == outD || outK == outJ || outD == outJ )
      return TA_BAD_PARAM;

   lookbackTotal = TA_KDJ_Lookback(optInFastK_Period,optInSlowK_Period,optInSlowK_MAType,optInSlowD_Period,optInSlowD_MAType);
   if( lookbackTotal > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   retCode = TA_S_STOCH(startIdx,endIdx,inHigh,inLow,inClose,optInFastK_Period,optInSlowK_Period,optInSlowK_MAType,optInSlowD_Period,optInSlowD_MAType,outBegIdx,outNBElement,outK,outD);
   if( retCode != TA_SUCCESS || (int)*outNBElement == 0 )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return retCode;
   }
   for( i = 0; i < (int)*outNBElement; i += 1 )
   {
      outJ[i] = 3.0 * outK[i] - 2.0 * outD[i];
   }
   return TA_SUCCESS;
}

/**** Streaming API *****/

struct TA_KDJ_Stream {
   /* The bars this handle has an output for (see TA_KDJ_OutRange). */
   int outRangeBegIdx;
   int outRangeCount;
   /* The value(s) at the last bar the stream counted (see TA_KDJ_Value). */
   double cur_outK;
   double cur_outD;
   double cur_outJ;
   int optInFastK_Period;
   int optInSlowK_Period;
   TA_MAType optInSlowK_MAType;
   int optInSlowD_Period;
   TA_MAType optInSlowD_MAType;
   TA_STOCH_Stream *sub0;
};

/* Private function, not in public API. */
static TA_RetCode TA_KDJ_StepImpl( struct TA_KDJ_Stream *sp, double inHigh, double inLow, double inClose, double *outK, double *outD, double *outJ )
{
   double cur_outK = 0.0;
   double cur_outD = 0.0;
   double cur_outJ = 0.0;


   /* Pipeline the new bar through the sub-streams (batch tail order). */
   {
      TA_RetCode subRc = TA_STOCH_Update( sp->sub0, inHigh, inLow, inClose, &cur_outK, &cur_outD );
      if( subRc != TA_SUCCESS ) return subRc;
   }
   /* Combine map (batch tail, per bar). */
   cur_outJ = 3.0 * cur_outK - 2.0 * cur_outD;
   *outK = cur_outK;
   *outD = cur_outD;
   *outJ = cur_outJ;
   return TA_SUCCESS;
}

static TA_RetCode TA_KDJ_OpenImpl( struct TA_KDJ_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], int startIdx, int historyLen, int optInFastK_Period, int optInSlowK_Period, TA_MAType optInSlowK_MAType, int optInSlowD_Period, TA_MAType optInSlowD_MAType, int *outBegIdx, int *outNBElement, double outK[], double outD[], double outJ[], int outStride )
{
   struct TA_KDJ_Stream *sp;
   int endIdx;
   int dummyBegIdx;
   int dummyNBElement;
   TA_RetCode subRc;
   double *sc_outK;
   double *sc_outD;
   double *sc_outJ;
   TA_STOCH_Stream *sub0;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !inClose || !outK || !outD || !outJ ) return TA_BAD_PARAM;
   if( (int)optInFastK_Period == TA_INTEGER_DEFAULT )
      optInFastK_Period = 9;
   else if( (int)optInFastK_Period < 1 || (int)optInFastK_Period > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInSlowK_Period == TA_INTEGER_DEFAULT )
      optInSlowK_Period = 3;
   else if( (int)optInSlowK_Period < 1 || (int)optInSlowK_Period > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInSlowK_MAType == TA_INTEGER_DEFAULT || optInSlowK_MAType == TA_MAType_DEFAULT )
      optInSlowK_MAType = 13;
   else if( (int)optInSlowK_MAType < TA_MATYPE_MIN || (int)optInSlowK_MAType > TA_MATYPE_MAX )
      return TA_BAD_PARAM;
   if( (int)optInSlowD_Period == TA_INTEGER_DEFAULT )
      optInSlowD_Period = 3;
   else if( (int)optInSlowD_Period < 1 || (int)optInSlowD_Period > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInSlowD_MAType == TA_INTEGER_DEFAULT || optInSlowD_MAType == TA_MAType_DEFAULT )
      optInSlowD_MAType = 13;
   else if( (int)optInSlowD_MAType < TA_MATYPE_MIN || (int)optInSlowD_MAType > TA_MATYPE_MAX )
      return TA_BAD_PARAM;
   if( startIdx > historyLen - 1 )
   {
      *outBegIdx = 0;
      *outNBElement = 0;
      return TA_INSUFFICIENT_HISTORY;
   }

   endIdx = historyLen - 1;
   dummyBegIdx = 0;
   dummyNBElement = 0;
   subRc = TA_SUCCESS;
   sub0 = NULL;
   if( outStride ) sc_outK = outK;
   else
   {
      sc_outK = (double *)TA_Malloc( sizeof(double) * (size_t)historyLen );
      if( !sc_outK ) { return TA_ALLOC_ERR; }
   }
   if( outStride ) sc_outD = outD;
   else
   {
      sc_outD = (double *)TA_Malloc( sizeof(double) * (size_t)historyLen );
      if( !sc_outD ) { TA_Free( sc_outK ); return TA_ALLOC_ERR; }
   }
   if( outStride ) sc_outJ = outJ;
   else
   {
      sc_outJ = (double *)TA_Malloc( sizeof(double) * (size_t)historyLen );
      if( !sc_outJ ) { TA_Free( sc_outK ); TA_Free( sc_outD ); return TA_ALLOC_ERR; }
   }

   {
      TA_RetCode retCode;
      int i;
      int lookbackTotal;
      lookbackTotal = TA_KDJ_Lookback(optInFastK_Period,optInSlowK_Period,optInSlowK_MAType,optInSlowD_Period,optInSlowD_MAType);
      /* Nothing to produce: the range is shorter than the lookback. Answering here
       * keeps the sub-call out of the phantom-I/O sweep's zero-length range, where
       * its own argument check would reject before any array is touched.
       */
      if( lookbackTotal > endIdx )
      {
         dummyBegIdx = 0;
         dummyNBElement = 0;
         TA_STOCH_Close( sub0 ); if( !outStride ) TA_Free( sc_outK ); if( !outStride ) TA_Free( sc_outD ); if( !outStride ) TA_Free( sc_outJ );
         return TA_INSUFFICIENT_HISTORY;
      }
      /* Sub-stream 0: stoch over `inHigh, inLow, inClose`, warmed from bar 0 up to the
       * sub-call's own startIdx (the seeding point). */
      {
         subRc = TA_STOCH_OpenAndFillInternal( &sub0, inHigh, inLow, inClose, (startIdx), (endIdx) + 1, optInFastK_Period, optInSlowK_Period, optInSlowK_MAType, optInSlowD_Period, optInSlowD_MAType, &dummyBegIdx, &dummyNBElement, sc_outK, sc_outD );
         if( subRc != TA_SUCCESS )
         {
            TA_STOCH_Close( sub0 ); if( !outStride ) TA_Free( sc_outK ); if( !outStride ) TA_Free( sc_outD ); if( !outStride ) TA_Free( sc_outJ );
            return subRc;
         }
      }
      retCode = subRc;
      if( retCode != TA_SUCCESS || (int)dummyNBElement == 0 )
      {
         dummyBegIdx = 0;
         dummyNBElement = 0;
         TA_STOCH_Close( sub0 ); if( !outStride ) TA_Free( sc_outK ); if( !outStride ) TA_Free( sc_outD ); if( !outStride ) TA_Free( sc_outJ );
         return retCode;
      }
      /* Keep this one Sub expression: spelling it as an Add of a negated term
       * would arm the multiply-add fusion and move the last bits of J.
       */
      for( i = 0; i < (int)dummyNBElement; i += 1 )
      {
         sc_outJ[i] = 3.0 * sc_outK[i] - 2.0 * sc_outD[i];
      }

      /* Capture the live producer state + sub handles. */
      if( dummyNBElement < 1 ) { TA_STOCH_Close( sub0 ); if( !outStride ) TA_Free( sc_outK ); if( !outStride ) TA_Free( sc_outD ); if( !outStride ) TA_Free( sc_outJ ); return TA_INSUFFICIENT_HISTORY; }
      sp = (struct TA_KDJ_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) { TA_STOCH_Close( sub0 ); if( !outStride ) TA_Free( sc_outK ); if( !outStride ) TA_Free( sc_outD ); if( !outStride ) TA_Free( sc_outJ ); return TA_ALLOC_ERR; }
      memset( sp, 0, sizeof(*sp) );
      sp->optInFastK_Period = optInFastK_Period;
      sp->optInSlowK_Period = optInSlowK_Period;
      sp->optInSlowK_MAType = optInSlowK_MAType;
      sp->optInSlowD_Period = optInSlowD_Period;
      sp->optInSlowD_MAType = optInSlowD_MAType;
      sp->sub0 = sub0;
      *outBegIdx = dummyBegIdx;
      *outNBElement = dummyNBElement;
      if( !outStride ) outK[0] = sc_outK[dummyNBElement - 1];
      if( !outStride ) outD[0] = sc_outD[dummyNBElement - 1];
      if( !outStride ) outJ[0] = sc_outJ[dummyNBElement - 1];
      if( !outStride ) TA_Free( sc_outK );
      if( !outStride ) TA_Free( sc_outD );
      if( !outStride ) TA_Free( sc_outJ );
      sp->outRangeBegIdx = *outBegIdx;
      sp->outRangeCount = *outNBElement;
      sp->cur_outK = outK[(*outNBElement - 1) * outStride];
      sp->cur_outD = outD[(*outNBElement - 1) * outStride];
      sp->cur_outJ = outJ[(*outNBElement - 1) * outStride];
      *stream = sp;
      return TA_SUCCESS;
   }
}

/* Private function, not in public API. */
TA_RetCode TA_KDJ_OpenInternal( struct TA_KDJ_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], int startIdx, int historyLen, int optInFastK_Period, int optInSlowK_Period, TA_MAType optInSlowK_MAType, int optInSlowD_Period, TA_MAType optInSlowD_MAType, double *outK, double *outD, double *outJ )
{
   TA_RetCode retCode;
   int dummyBegIdx = 0;
   int dummyNBElement = 0;
   double sink_outK = 0.0;
   double sink_outD = 0.0;
   double sink_outJ = 0.0;
   retCode = TA_KDJ_OpenImpl( stream, inHigh, inLow, inClose, startIdx, historyLen, optInFastK_Period, optInSlowK_Period, optInSlowK_MAType, optInSlowD_Period, optInSlowD_MAType, &dummyBegIdx, &dummyNBElement, &sink_outK, &sink_outD, &sink_outJ, 0 );
   if( retCode == TA_SUCCESS )
   {
      *outK = sink_outK;
      *outD = sink_outD;
      *outJ = sink_outJ;
   }
   return retCode;
}

TA_LIB_API TA_RetCode TA_KDJ_Open( TA_KDJ_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], int historyLen, int optInFastK_Period, int optInSlowK_Period, TA_MAType optInSlowK_MAType, int optInSlowD_Period, TA_MAType optInSlowD_MAType, double *outK, double *outD, double *outJ )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !inClose || !outK || !outD || !outJ ) return TA_BAD_PARAM;
   return TA_KDJ_OpenInternal( stream, inHigh, inLow, inClose, 0, historyLen, optInFastK_Period, optInSlowK_Period, optInSlowK_MAType, optInSlowD_Period, optInSlowD_MAType, outK, outD, outJ );
}

TA_LIB_API TA_RetCode TA_KDJ_OpenAndFill( TA_KDJ_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], int historyLen, int optInFastK_Period, int optInSlowK_Period, TA_MAType optInSlowK_MAType, int optInSlowD_Period, TA_MAType optInSlowD_MAType, int *outBegIdx, int *outNBElement, double outK[], double outD[], double outJ[] )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !inClose || !outBegIdx || !outNBElement || !outK || !outD || !outJ ) return TA_BAD_PARAM;
   if( (const void *)outK == (const void *)inHigh || (const void *)outK == (const void *)inLow || (const void *)outK == (const void *)inClose || (const void *)outD == (const void *)inHigh || (const void *)outD == (const void *)inLow || (const void *)outD == (const void *)inClose || (const void *)outJ == (const void *)inHigh || (const void *)outJ == (const void *)inLow || (const void *)outJ == (const void *)inClose || (const void *)outK == (const void *)outD || (const void *)outK == (const void *)outJ || (const void *)outD == (const void *)outJ ) return TA_BAD_PARAM;
   return TA_KDJ_OpenAndFillInternal( stream, inHigh, inLow, inClose, 0, historyLen, optInFastK_Period, optInSlowK_Period, optInSlowK_MAType, optInSlowD_Period, optInSlowD_MAType, outBegIdx, outNBElement, outK, outD, outJ );
}

/* Private function, not in public API. */
TA_RetCode TA_KDJ_OpenAndFillInternal( struct TA_KDJ_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], int startIdx, int historyLen, int optInFastK_Period, int optInSlowK_Period, TA_MAType optInSlowK_MAType, int optInSlowD_Period, TA_MAType optInSlowD_MAType, int *outBegIdx, int *outNBElement, double outK[], double outD[], double outJ[] )
{
   return TA_KDJ_OpenImpl( stream, inHigh, inLow, inClose, startIdx, historyLen, optInFastK_Period, optInSlowK_Period, optInSlowK_MAType, optInSlowD_Period, optInSlowD_MAType, outBegIdx, outNBElement, outK, outD, outJ, 1 );
}

TA_LIB_API TA_RetCode TA_KDJ_Update( TA_KDJ_Stream *stream, double inHigh, double inLow, double inClose, double *outK, double *outD, double *outJ )
{
   TA_RetCode retCode;

   if( !stream || !outK || !outD || !outJ ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) || !TA_IS_FINITE( inClose ) ) return TA_BAD_PARAM;
   retCode = TA_KDJ_StepImpl( stream, inHigh, inLow, inClose, outK, outD, outJ );
   if( retCode != TA_SUCCESS ) return retCode;
   stream->cur_outK = *outK;
   stream->cur_outD = *outD;
   stream->cur_outJ = *outJ;
   if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_KDJ_Peek( const TA_KDJ_Stream *stream, double inHigh, double inLow, double inClose, double *outK, double *outD, double *outJ )
{
   const struct TA_KDJ_Stream *sp = stream;
   double cur_outK = 0.0;
   double cur_outD = 0.0;
   double cur_outJ = 0.0;

   if( !stream || !outK || !outD || !outJ ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) || !TA_IS_FINITE( inClose ) ) return TA_BAD_PARAM;

   /* Pipeline the new bar through the sub-streams (batch tail order). */
   {
      TA_RetCode subRc = TA_STOCH_Peek( (const TA_STOCH_Stream *)sp->sub0, inHigh, inLow, inClose, &cur_outK, &cur_outD );
      if( subRc != TA_SUCCESS ) return subRc;
   }
   /* Combine map (batch tail, per bar). */
   cur_outJ = 3.0 * cur_outK - 2.0 * cur_outD;
   *outK = cur_outK;
   *outD = cur_outD;
   *outJ = cur_outJ;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_KDJ_Close( TA_KDJ_Stream *stream )
{
   if( !stream ) return TA_SUCCESS;
   TA_STOCH_Close( stream->sub0 );
   TA_Free( stream );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_KDJ_Value( const TA_KDJ_Stream *stream, double *outK, double *outD, double *outJ )
{
   if( !stream || !outK || !outD || !outJ ) return TA_BAD_PARAM;
   *outK = stream->cur_outK;
   *outD = stream->cur_outD;
   *outJ = stream->cur_outJ;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_KDJ_OutRange( const TA_KDJ_Stream *stream, int *outBegIdx, int *outNBElement )
{
   if( !stream || !outBegIdx || !outNBElement ) return TA_BAD_PARAM;
   *outBegIdx = stream->outRangeBegIdx;
   *outNBElement = stream->outRangeCount;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_KDJ_Advance( TA_KDJ_Stream *stream )
{
   if( !stream ) return TA_BAD_PARAM;
   if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_KDJ_Clone( const TA_KDJ_Stream *stream, TA_KDJ_Stream **clone )
{
   struct TA_KDJ_Stream *sp;

   if( !clone ) return TA_BAD_PARAM;
   *clone = NULL;
   if( !stream ) return TA_BAD_PARAM;
   sp = (struct TA_KDJ_Stream *)TA_Malloc( sizeof(*sp) );
   if( !sp ) return TA_ALLOC_ERR;
   *sp = *stream;
   sp->sub0 = NULL;
   if( stream->sub0 )
   { TA_RetCode subRc = TA_STOCH_Clone( stream->sub0, &sp->sub0 );
     if( subRc != TA_SUCCESS ) { TA_KDJ_Close( sp ); return subRc; } }
   *clone = sp;
   return TA_SUCCESS;
}

