/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_unguarded.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  MF       Mario Fortier
 *  CC       Claude Code (AI assistant)
 *
 * Change history:
 *
 *  MMDDYY BY     Description
 *  -------------------------------------------------------------------
 *  112400 MF     Template creation.
 *  052603 MF     Adapt code to compile with .NET Managed C++
 *  071126 MF,CC  Inline the fixed-26/12 MACD lockstep pass (was a
 *                delegation to macd(...,0,0,...)); bit-exact, streamable.
 */

TA_LIB_API int TA_MACDFIX_Lookback( int optInSignalPeriod )
{
   if( (int)optInSignalPeriod == (int)0x80000000 )
      optInSignalPeriod = 9;
   else if( (int)optInSignalPeriod < 1 || (int)optInSignalPeriod > 100000 )
      return -1;
   /* The lookback is driven by the signal line output.
    *
    * (must also account for the initial data consume
    *  by the fix 26 period EMA).
    */
   return TA_EMA_Lookback(26) + TA_EMA_Lookback(optInSignalPeriod);
}

TA_LIB_API TA_RetCode TA_MACDFIX( int    startIdx,
                                  int    endIdx,
                                  const double inReal[],
                                  int optInSignalPeriod,
                                  int          *outBegIdx,
                                  int          *outNBElement,
                                  double        outMACD[],
                                  double        outMACDSignal[],
                                  double        outMACDHist[] )
{
   double prevFast;
   double prevSlow;
   double prevSignal;
   double macdValue;
   double tempReal;
   double slowK;
   double fastK;
   double signalK;
   int i;
   int today;
   int outIdx;
   int lookbackTotal;
   int lookbackSignal;
   int optInFastPeriod;
   int optInSlowPeriod;

   if( startIdx < 0 )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( !inReal )
      return TA_BAD_PARAM;
   if( (int)optInSignalPeriod == (int)0x80000000 )
      optInSignalPeriod = 9;
   else if( (int)optInSignalPeriod < 1 || (int)optInSignalPeriod > 100000 )
      return TA_BAD_PARAM;
   if( !outMACD )
      return TA_BAD_PARAM;
   if( !outMACDSignal )
      return TA_BAD_PARAM;
   if( !outMACDHist )
      return TA_BAD_PARAM;
   if( outMACD == outMACDSignal || outMACD == outMACDHist || outMACDSignal == outMACDHist )
      return TA_BAD_PARAM;

   optInFastPeriod = 12;
   optInSlowPeriod = 26;
   /* MACDFIX is the fixed 26/12 MACD: the fast/slow periods and their
    * smoothing factors are hardcoded (the general MACD selects these
    * exact values when its fast/slow period arguments are 0). Only the
    * signal period is caller-provided.
    *    Fix 12 -> fastK = 0.15
    *    Fix 26 -> slowK = 0.075
    */
   fastK = 0.15;
   slowK = 0.075;
   signalK = 2.0 / (double)(optInSignalPeriod + 1);
   lookbackSignal = TA_EMA_Lookback(optInSignalPeriod);
   /* Move up the start index if there is not
    * enough initial data.
    */
   lookbackTotal = lookbackSignal;
   lookbackTotal += TA_EMA_Lookback(26);
   /* fixed slow period */
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   /* Make sure there is still something to evaluate. */
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   /* Everything is computed in a single lockstep pass: each bar
    * advances the fast and slow EMA (two independent recursions),
    * their difference is the MACD line, and each MACD-line value
    * is immediately fed into the signal EMA. No temporary buffers.
    *
    * The arithmetic order below is the bit-exactness contract
    * (do not reorder or fuse operations):
    *  - EMA recursion: ((x-prev)*k)+prev.
    *  - Default compatibility: each EMA is seeded with the sum of
    *    its first 'period' inputs, accumulated from 0.0 in input
    *    order, divided by the period. The fast and slow seed
    *    windows end on the same bar. The signal EMA is seeded the
    *    same way from the first 'signal period' MACD-line values.
    *  - Metastock compatibility: the fast and slow EMA are seeded
    *    from inReal[0], the signal EMA from the first MACD-line
    *    value.
    * Output alignment is identical for all compatibility modes;
    * only the seed values differ.
    *
    * In-place (an output == inReal) is supported: outputs at
    * [outIdx] are written only after inReal[startIdx+outIdx] was
    * read.
    */
   if( TA_GLOBALS_COMPATIBILITY == ENUM_VALUE(Compatibility,TA_COMPATIBILITY_DEFAULT,Default) )
   {
      /* Seed each price EMA with a simple average of its first
       * 'period' price bars. The fast window is the tail of the
       * slow window: consume the leading slow-only bars first,
       * then accumulate both over the shared bars.
       */
      today = startIdx - lookbackTotal;
      tempReal = 0.0;
      i = optInSlowPeriod - optInFastPeriod;
      while( i-- > 0 )
      {
         tempReal += inReal[today++];
      }
      prevFast = 0.0;
      i = optInFastPeriod;
      while( i-- > 0 )
      {
         prevFast += inReal[today];
         tempReal += inReal[today++];
      }
      prevSlow = tempReal / optInSlowPeriod;
      prevFast = prevFast / optInFastPeriod;
      /* Advance both EMA through their unstable period, up to the
       * first MACD-line bar.
       */
      while( today <= startIdx - lookbackSignal )
      {
         tempReal = inReal[today++];
         prevFast = (tempReal - prevFast) * fastK + prevFast;
         prevSlow = (tempReal - prevSlow) * slowK + prevSlow;
      }
      macdValue = prevFast - prevSlow;
      /* Seed the signal EMA with a simple average of the first
       * 'signal period' MACD-line values, accumulated as they are
       * produced.
       */
      prevSignal = 0.0;
      prevSignal += macdValue;
      i = optInSignalPeriod - 1;
      while( i-- > 0 )
      {
         tempReal = inReal[today++];
         prevFast = (tempReal - prevFast) * fastK + prevFast;
         prevSlow = (tempReal - prevSlow) * slowK + prevSlow;
         macdValue = prevFast - prevSlow;
         prevSignal += macdValue;
      }
      prevSignal = prevSignal / optInSignalPeriod;
   } else 
   {
      /* Metastock/Tradestation: seed the fast and slow EMA with
       * inReal[0], advance them in lockstep up to the first
       * MACD-line bar, then seed the signal EMA with the first
       * MACD-line value.
       */
      prevFast = inReal[0];
      prevSlow = inReal[0];
      today = 1;
      while( today <= startIdx - lookbackSignal )
      {
         tempReal = inReal[today++];
         prevFast = (tempReal - prevFast) * fastK + prevFast;
         prevSlow = (tempReal - prevSlow) * slowK + prevSlow;
      }
      macdValue = prevFast - prevSlow;
      prevSignal = macdValue;
   }
   /* Advance everything in lockstep through the unstable period
    * of the signal EMA, up to the first output bar.
    */
   while( today <= startIdx )
   {
      tempReal = inReal[today++];
      prevFast = (tempReal - prevFast) * fastK + prevFast;
      prevSlow = (tempReal - prevSlow) * slowK + prevSlow;
      macdValue = prevFast - prevSlow;
      prevSignal = (macdValue - prevSignal) * signalK + prevSignal;
   }
   /* Stable zone: keep advancing in lockstep and write the three
    * outputs.
    */
   outMACD[0] = macdValue;
   outMACDSignal[0] = prevSignal;
   outMACDHist[0] = macdValue - prevSignal;
   outIdx = 1;
   while( today <= endIdx )
   {
      tempReal = inReal[today++];
      prevFast = (tempReal - prevFast) * fastK + prevFast;
      prevSlow = (tempReal - prevSlow) * slowK + prevSlow;
      macdValue = prevFast - prevSlow;
      prevSignal = (macdValue - prevSignal) * signalK + prevSignal;
      outMACD[outIdx] = macdValue;
      outMACDSignal[outIdx] = prevSignal;
      outMACDHist[outIdx] = macdValue - prevSignal;
      outIdx += 1;
   }
   /* All done! Indicate the output limits and return success. */
   *outBegIdx= startIdx;
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_MACDFIX_Unguarded( int    startIdx,
                                            int    endIdx,
                                            const double inReal[],
                                            int optInSignalPeriod,
                                            int          *outBegIdx,
                                            int          *outNBElement,
                                            double        outMACD[],
                                            double        outMACDSignal[],
                                            double        outMACDHist[] )
{
   double prevFast;
   double prevSlow;
   double prevSignal;
   double macdValue;
   double tempReal;
   double slowK;
   double fastK;
   double signalK;
   int i;
   int today;
   int outIdx;
   int lookbackTotal;
   int lookbackSignal;
   int optInFastPeriod;
   int optInSlowPeriod;

   optInFastPeriod = 12;
   optInSlowPeriod = 26;
   fastK = 0.15;
   slowK = 0.075;
   signalK = 2.0 / (double)(optInSignalPeriod + 1);
   lookbackSignal = TA_EMA_Lookback(optInSignalPeriod);
   lookbackTotal = lookbackSignal;
   lookbackTotal += TA_EMA_Lookback(26);
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   if( TA_GLOBALS_COMPATIBILITY == ENUM_VALUE(Compatibility,TA_COMPATIBILITY_DEFAULT,Default) )
   {
      today = startIdx - lookbackTotal;
      tempReal = 0.0;
      i = optInSlowPeriod - optInFastPeriod;
      while( i-- > 0 )
      {
         tempReal += inReal[today++];
      }
      prevFast = 0.0;
      i = optInFastPeriod;
      while( i-- > 0 )
      {
         prevFast += inReal[today];
         tempReal += inReal[today++];
      }
      prevSlow = tempReal / optInSlowPeriod;
      prevFast = prevFast / optInFastPeriod;
      while( today <= startIdx - lookbackSignal )
      {
         tempReal = inReal[today++];
         prevFast = (tempReal - prevFast) * fastK + prevFast;
         prevSlow = (tempReal - prevSlow) * slowK + prevSlow;
      }
      macdValue = prevFast - prevSlow;
      prevSignal = 0.0;
      prevSignal += macdValue;
      i = optInSignalPeriod - 1;
      while( i-- > 0 )
      {
         tempReal = inReal[today++];
         prevFast = (tempReal - prevFast) * fastK + prevFast;
         prevSlow = (tempReal - prevSlow) * slowK + prevSlow;
         macdValue = prevFast - prevSlow;
         prevSignal += macdValue;
      }
      prevSignal = prevSignal / optInSignalPeriod;
   } else 
   {
      prevFast = inReal[0];
      prevSlow = inReal[0];
      today = 1;
      while( today <= startIdx - lookbackSignal )
      {
         tempReal = inReal[today++];
         prevFast = (tempReal - prevFast) * fastK + prevFast;
         prevSlow = (tempReal - prevSlow) * slowK + prevSlow;
      }
      macdValue = prevFast - prevSlow;
      prevSignal = macdValue;
   }
   while( today <= startIdx )
   {
      tempReal = inReal[today++];
      prevFast = (tempReal - prevFast) * fastK + prevFast;
      prevSlow = (tempReal - prevSlow) * slowK + prevSlow;
      macdValue = prevFast - prevSlow;
      prevSignal = (macdValue - prevSignal) * signalK + prevSignal;
   }
   outMACD[0] = macdValue;
   outMACDSignal[0] = prevSignal;
   outMACDHist[0] = macdValue - prevSignal;
   outIdx = 1;
   while( today <= endIdx )
   {
      tempReal = inReal[today++];
      prevFast = (tempReal - prevFast) * fastK + prevFast;
      prevSlow = (tempReal - prevSlow) * slowK + prevSlow;
      macdValue = prevFast - prevSlow;
      prevSignal = (macdValue - prevSignal) * signalK + prevSignal;
      outMACD[outIdx] = macdValue;
      outMACDSignal[outIdx] = prevSignal;
      outMACDHist[outIdx] = macdValue - prevSignal;
      outIdx += 1;
   }
   *outBegIdx= startIdx;
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

TA_RetCode TA_S_MACDFIX( int    startIdx,
                         int    endIdx,
                         const float inReal[],
                         int optInSignalPeriod,
                         int          *outBegIdx,
                         int          *outNBElement,
                         double        outMACD[],
                         double        outMACDSignal[],
                         double        outMACDHist[] )
{
   double prevFast;
   double prevSlow;
   double prevSignal;
   double macdValue;
   double tempReal;
   double slowK;
   double fastK;
   double signalK;
   int i;
   int today;
   int outIdx;
   int lookbackTotal;
   int lookbackSignal;
   int optInFastPeriod;
   int optInSlowPeriod;

   if( startIdx < 0 )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( !inReal )
      return TA_BAD_PARAM;
   if( (int)optInSignalPeriod == (int)0x80000000 )
      optInSignalPeriod = 9;
   else if( (int)optInSignalPeriod < 1 || (int)optInSignalPeriod > 100000 )
      return TA_BAD_PARAM;
   if( !outMACD )
      return TA_BAD_PARAM;
   if( !outMACDSignal )
      return TA_BAD_PARAM;
   if( !outMACDHist )
      return TA_BAD_PARAM;
   if( outMACD == outMACDSignal || outMACD == outMACDHist || outMACDSignal == outMACDHist )
      return TA_BAD_PARAM;

   optInFastPeriod = 12;
   optInSlowPeriod = 26;
   fastK = 0.15;
   slowK = 0.075;
   signalK = 2.0 / (double)(optInSignalPeriod + 1);
   lookbackSignal = TA_EMA_Lookback(optInSignalPeriod);
   lookbackTotal = lookbackSignal;
   lookbackTotal += TA_EMA_Lookback(26);
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   if( TA_GLOBALS_COMPATIBILITY == ENUM_VALUE(Compatibility,TA_COMPATIBILITY_DEFAULT,Default) )
   {
      today = startIdx - lookbackTotal;
      tempReal = 0.0;
      i = optInSlowPeriod - optInFastPeriod;
      while( i-- > 0 )
      {
         tempReal += (double)inReal[today++];
      }
      prevFast = 0.0;
      i = optInFastPeriod;
      while( i-- > 0 )
      {
         prevFast += (double)inReal[today];
         tempReal += (double)inReal[today++];
      }
      prevSlow = tempReal / optInSlowPeriod;
      prevFast = prevFast / optInFastPeriod;
      while( today <= startIdx - lookbackSignal )
      {
         tempReal = (double)inReal[today++];
         prevFast = (tempReal - prevFast) * fastK + prevFast;
         prevSlow = (tempReal - prevSlow) * slowK + prevSlow;
      }
      macdValue = prevFast - prevSlow;
      prevSignal = 0.0;
      prevSignal += macdValue;
      i = optInSignalPeriod - 1;
      while( i-- > 0 )
      {
         tempReal = (double)inReal[today++];
         prevFast = (tempReal - prevFast) * fastK + prevFast;
         prevSlow = (tempReal - prevSlow) * slowK + prevSlow;
         macdValue = prevFast - prevSlow;
         prevSignal += macdValue;
      }
      prevSignal = prevSignal / optInSignalPeriod;
   } else 
   {
      prevFast = (double)inReal[0];
      prevSlow = (double)inReal[0];
      today = 1;
      while( today <= startIdx - lookbackSignal )
      {
         tempReal = (double)inReal[today++];
         prevFast = (tempReal - prevFast) * fastK + prevFast;
         prevSlow = (tempReal - prevSlow) * slowK + prevSlow;
      }
      macdValue = prevFast - prevSlow;
      prevSignal = macdValue;
   }
   while( today <= startIdx )
   {
      tempReal = (double)inReal[today++];
      prevFast = (tempReal - prevFast) * fastK + prevFast;
      prevSlow = (tempReal - prevSlow) * slowK + prevSlow;
      macdValue = prevFast - prevSlow;
      prevSignal = (macdValue - prevSignal) * signalK + prevSignal;
   }
   outMACD[0] = macdValue;
   outMACDSignal[0] = prevSignal;
   outMACDHist[0] = macdValue - prevSignal;
   outIdx = 1;
   while( today <= endIdx )
   {
      tempReal = (double)inReal[today++];
      prevFast = (tempReal - prevFast) * fastK + prevFast;
      prevSlow = (tempReal - prevSlow) * slowK + prevSlow;
      macdValue = prevFast - prevSlow;
      prevSignal = (macdValue - prevSignal) * signalK + prevSignal;
      outMACD[outIdx] = macdValue;
      outMACDSignal[outIdx] = prevSignal;
      outMACDHist[outIdx] = macdValue - prevSignal;
      outIdx += 1;
   }
   *outBegIdx= startIdx;
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

TA_RetCode TA_S_MACDFIX_Unguarded( int    startIdx,
                                   int    endIdx,
                                   const float inReal[],
                                   int optInSignalPeriod,
                                   int          *outBegIdx,
                                   int          *outNBElement,
                                   double        outMACD[],
                                   double        outMACDSignal[],
                                   double        outMACDHist[] )
{
   double prevFast;
   double prevSlow;
   double prevSignal;
   double macdValue;
   double tempReal;
   double slowK;
   double fastK;
   double signalK;
   int i;
   int today;
   int outIdx;
   int lookbackTotal;
   int lookbackSignal;
   int optInFastPeriod;
   int optInSlowPeriod;

   optInFastPeriod = 12;
   optInSlowPeriod = 26;
   fastK = 0.15;
   slowK = 0.075;
   signalK = 2.0 / (double)(optInSignalPeriod + 1);
   lookbackSignal = TA_EMA_Lookback(optInSignalPeriod);
   lookbackTotal = lookbackSignal;
   lookbackTotal += TA_EMA_Lookback(26);
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   if( TA_GLOBALS_COMPATIBILITY == ENUM_VALUE(Compatibility,TA_COMPATIBILITY_DEFAULT,Default) )
   {
      today = startIdx - lookbackTotal;
      tempReal = 0.0;
      i = optInSlowPeriod - optInFastPeriod;
      while( i-- > 0 )
      {
         tempReal += (double)inReal[today++];
      }
      prevFast = 0.0;
      i = optInFastPeriod;
      while( i-- > 0 )
      {
         prevFast += (double)inReal[today];
         tempReal += (double)inReal[today++];
      }
      prevSlow = tempReal / optInSlowPeriod;
      prevFast = prevFast / optInFastPeriod;
      while( today <= startIdx - lookbackSignal )
      {
         tempReal = (double)inReal[today++];
         prevFast = (tempReal - prevFast) * fastK + prevFast;
         prevSlow = (tempReal - prevSlow) * slowK + prevSlow;
      }
      macdValue = prevFast - prevSlow;
      prevSignal = 0.0;
      prevSignal += macdValue;
      i = optInSignalPeriod - 1;
      while( i-- > 0 )
      {
         tempReal = (double)inReal[today++];
         prevFast = (tempReal - prevFast) * fastK + prevFast;
         prevSlow = (tempReal - prevSlow) * slowK + prevSlow;
         macdValue = prevFast - prevSlow;
         prevSignal += macdValue;
      }
      prevSignal = prevSignal / optInSignalPeriod;
   } else 
   {
      prevFast = (double)inReal[0];
      prevSlow = (double)inReal[0];
      today = 1;
      while( today <= startIdx - lookbackSignal )
      {
         tempReal = (double)inReal[today++];
         prevFast = (tempReal - prevFast) * fastK + prevFast;
         prevSlow = (tempReal - prevSlow) * slowK + prevSlow;
      }
      macdValue = prevFast - prevSlow;
      prevSignal = macdValue;
   }
   while( today <= startIdx )
   {
      tempReal = (double)inReal[today++];
      prevFast = (tempReal - prevFast) * fastK + prevFast;
      prevSlow = (tempReal - prevSlow) * slowK + prevSlow;
      macdValue = prevFast - prevSlow;
      prevSignal = (macdValue - prevSignal) * signalK + prevSignal;
   }
   outMACD[0] = macdValue;
   outMACDSignal[0] = prevSignal;
   outMACDHist[0] = macdValue - prevSignal;
   outIdx = 1;
   while( today <= endIdx )
   {
      tempReal = (double)inReal[today++];
      prevFast = (tempReal - prevFast) * fastK + prevFast;
      prevSlow = (tempReal - prevSlow) * slowK + prevSlow;
      macdValue = prevFast - prevSlow;
      prevSignal = (macdValue - prevSignal) * signalK + prevSignal;
      outMACD[outIdx] = macdValue;
      outMACDSignal[outIdx] = prevSignal;
      outMACDHist[outIdx] = macdValue - prevSignal;
      outIdx += 1;
   }
   *outBegIdx= startIdx;
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

/**** Streaming API *****/

struct TA_MACDFIX_Stream {
   int optInSignalPeriod;
   double prevFast;
   double prevSlow;
   double prevSignal;
   double slowK;
   double fastK;
   double signalK;
};

static void TA_MACDFIX_StreamStep( struct TA_MACDFIX_Stream *sp, double inReal, double *outMACD, double *outMACDSignal, double *outMACDHist )
{
   double macdValue;
   double tempReal;

   tempReal = inReal;
   sp->prevFast = (tempReal - sp->prevFast) * sp->fastK + sp->prevFast;
   sp->prevSlow = (tempReal - sp->prevSlow) * sp->slowK + sp->prevSlow;
   macdValue = sp->prevFast - sp->prevSlow;
   sp->prevSignal = (macdValue - sp->prevSignal) * sp->signalK + sp->prevSignal;
   *outMACD= macdValue;
   *outMACDSignal= sp->prevSignal;
   *outMACDHist= macdValue - sp->prevSignal;
}

TA_RetCode TA_MACDFIX_OpenInternal( int optInSignalPeriod, const double inReal[], int startIdx, int historyLen, struct TA_MACDFIX_Stream **stream, double *outMACD, double *outMACDSignal, double *outMACDHist )
{
   struct TA_MACDFIX_Stream *sp;
   int endIdx;
   int dummyBegIdx;
   int dummyNBElement;
   double lastValue_outMACD;
   double lastValue_outMACDSignal;
   double lastValue_outMACDHist;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( !inReal || !outMACD || !outMACDSignal || !outMACDHist ) return TA_BAD_PARAM;
   if( historyLen < 1 ) return TA_BAD_PARAM;
   if( (int)optInSignalPeriod == (int)0x80000000 )
      optInSignalPeriod = 9;
   else if( (int)optInSignalPeriod < 1 || (int)optInSignalPeriod > 100000 )
      return TA_BAD_PARAM;

   endIdx = historyLen - 1;
   dummyBegIdx = 0;
   dummyNBElement = 0;
   lastValue_outMACD = 0.0;
   lastValue_outMACDSignal = 0.0;
   lastValue_outMACDHist = 0.0;
   (void)startIdx; (void)dummyBegIdx; (void)dummyNBElement;

   {
      double prevFast = 0.0;
      double prevSlow = 0.0;
      double prevSignal = 0.0;
      double macdValue;
      double tempReal;
      double slowK = 0.0;
      double fastK = 0.0;
      double signalK = 0.0;
      int i;
      int today;
      int outIdx;
      int lookbackTotal;
      int lookbackSignal;
      /* MACDFIX is the fixed 26/12 MACD: the fast/slow periods and their
       * smoothing factors are hardcoded (the general MACD selects these
       * exact values when its fast/slow period arguments are 0). Only the
       * signal period is caller-provided.
       *    Fix 12 -> fastK = 0.15
       *    Fix 26 -> slowK = 0.075
       */
      int optInFastPeriod = 12;
      int optInSlowPeriod = 26;
      fastK = 0.15;
      slowK = 0.075;
      signalK = 2.0 / (double)(optInSignalPeriod + 1);
      lookbackSignal = TA_EMA_Lookback(optInSignalPeriod);
      /* Move up the start index if there is not
       * enough initial data.
       */
      lookbackTotal = lookbackSignal;
      lookbackTotal += TA_EMA_Lookback(26);
      /* fixed slow period */
      if( startIdx < lookbackTotal )
      {
         startIdx = lookbackTotal;
      }
      /* Make sure there is still something to evaluate. */
      if( startIdx > endIdx )
      {
         dummyBegIdx = 0;
         dummyNBElement = 0;
         return TA_BAD_PARAM;
      }
      /* Everything is computed in a single lockstep pass: each bar
       * advances the fast and slow EMA (two independent recursions),
       * their difference is the MACD line, and each MACD-line value
       * is immediately fed into the signal EMA. No temporary buffers.
       *
       * The arithmetic order below is the bit-exactness contract
       * (do not reorder or fuse operations):
       *  - EMA recursion: ((x-prev)*k)+prev.
       *  - Default compatibility: each EMA is seeded with the sum of
       *    its first 'period' inputs, accumulated from 0.0 in input
       *    order, divided by the period. The fast and slow seed
       *    windows end on the same bar. The signal EMA is seeded the
       *    same way from the first 'signal period' MACD-line values.
       *  - Metastock compatibility: the fast and slow EMA are seeded
       *    from inReal[0], the signal EMA from the first MACD-line
       *    value.
       * Output alignment is identical for all compatibility modes;
       * only the seed values differ.
       *
       * In-place (an output == inReal) is supported: outputs at
       * [outIdx] are written only after inReal[startIdx+outIdx] was
       * read.
       */
      if( TA_GLOBALS_COMPATIBILITY == ENUM_VALUE(Compatibility,TA_COMPATIBILITY_DEFAULT,Default) )
      {
         /* Seed each price EMA with a simple average of its first
          * 'period' price bars. The fast window is the tail of the
          * slow window: consume the leading slow-only bars first,
          * then accumulate both over the shared bars.
          */
         today = startIdx - lookbackTotal;
         tempReal = 0.0;
         i = optInSlowPeriod - optInFastPeriod;
         while( i-- > 0 )
         {
            tempReal += inReal[today++];
         }
         prevFast = 0.0;
         i = optInFastPeriod;
         while( i-- > 0 )
         {
            prevFast += inReal[today];
            tempReal += inReal[today++];
         }
         prevSlow = tempReal / optInSlowPeriod;
         prevFast = prevFast / optInFastPeriod;
         /* Advance both EMA through their unstable period, up to the
          * first MACD-line bar.
          */
         while( today <= startIdx - lookbackSignal )
         {
            tempReal = inReal[today++];
            prevFast = (tempReal - prevFast) * fastK + prevFast;
            prevSlow = (tempReal - prevSlow) * slowK + prevSlow;
         }
         macdValue = prevFast - prevSlow;
         /* Seed the signal EMA with a simple average of the first
          * 'signal period' MACD-line values, accumulated as they are
          * produced.
          */
         prevSignal = 0.0;
         prevSignal += macdValue;
         i = optInSignalPeriod - 1;
         while( i-- > 0 )
         {
            tempReal = inReal[today++];
            prevFast = (tempReal - prevFast) * fastK + prevFast;
            prevSlow = (tempReal - prevSlow) * slowK + prevSlow;
            macdValue = prevFast - prevSlow;
            prevSignal += macdValue;
         }
         prevSignal = prevSignal / optInSignalPeriod;
      } else 
      {
         /* Metastock/Tradestation: seed the fast and slow EMA with
          * inReal[0], advance them in lockstep up to the first
          * MACD-line bar, then seed the signal EMA with the first
          * MACD-line value.
          */
         prevFast = inReal[0];
         prevSlow = inReal[0];
         today = 1;
         while( today <= startIdx - lookbackSignal )
         {
            tempReal = inReal[today++];
            prevFast = (tempReal - prevFast) * fastK + prevFast;
            prevSlow = (tempReal - prevSlow) * slowK + prevSlow;
         }
         macdValue = prevFast - prevSlow;
         prevSignal = macdValue;
      }
      /* Advance everything in lockstep through the unstable period
       * of the signal EMA, up to the first output bar.
       */
      while( today <= startIdx )
      {
         tempReal = inReal[today++];
         prevFast = (tempReal - prevFast) * fastK + prevFast;
         prevSlow = (tempReal - prevSlow) * slowK + prevSlow;
         macdValue = prevFast - prevSlow;
         prevSignal = (macdValue - prevSignal) * signalK + prevSignal;
      }
      /* Stable zone: keep advancing in lockstep and write the three
       * outputs.
       */
      lastValue_outMACD = macdValue;
      lastValue_outMACDSignal = prevSignal;
      lastValue_outMACDHist = macdValue - prevSignal;
      outIdx = 1;
      while( today <= endIdx )
      {
         tempReal = inReal[today++];
         prevFast = (tempReal - prevFast) * fastK + prevFast;
         prevSlow = (tempReal - prevSlow) * slowK + prevSlow;
         macdValue = prevFast - prevSlow;
         prevSignal = (macdValue - prevSignal) * signalK + prevSignal;
         lastValue_outMACD = macdValue;
         lastValue_outMACDSignal = prevSignal;
         lastValue_outMACDHist = macdValue - prevSignal;
         outIdx += 1;
      }
      /* All done! Indicate the output limits and return success. */
      dummyBegIdx = startIdx;
      dummyNBElement = outIdx;

      /* Capture the live batch state into the handle. */
      sp = (struct TA_MACDFIX_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) { return TA_ALLOC_ERR; }
      memset( sp, 0, sizeof(*sp) );
      sp->optInSignalPeriod = optInSignalPeriod;
      sp->prevFast = prevFast;
      sp->prevSlow = prevSlow;
      sp->prevSignal = prevSignal;
      sp->slowK = slowK;
      sp->fastK = fastK;
      sp->signalK = signalK;
      *outMACD = lastValue_outMACD;
      *outMACDSignal = lastValue_outMACDSignal;
      *outMACDHist = lastValue_outMACDHist;
      *stream = sp;
      return TA_SUCCESS;
   }
}

TA_LIB_API TA_RetCode TA_MACDFIX_Open( int optInSignalPeriod, const double inReal[], int historyLen, TA_MACDFIX_Stream **stream, double *outMACD, double *outMACDSignal, double *outMACDHist )
{
   return TA_MACDFIX_OpenInternal( optInSignalPeriod, inReal, 0, historyLen, stream, outMACD, outMACDSignal, outMACDHist );
}

TA_LIB_API TA_RetCode TA_MACDFIX_Update( TA_MACDFIX_Stream *stream, double inReal, double *outMACD, double *outMACDSignal, double *outMACDHist )
{
   if( !stream || !outMACD || !outMACDSignal || !outMACDHist ) return TA_BAD_PARAM;
   TA_MACDFIX_StreamStep( stream, inReal, outMACD, outMACDSignal, outMACDHist );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_MACDFIX_Peek( const TA_MACDFIX_Stream *stream, double inReal, double *outMACD, double *outMACDSignal, double *outMACDHist )
{
   struct TA_MACDFIX_Stream scratch;

   if( !stream || !outMACD || !outMACDSignal || !outMACDHist ) return TA_BAD_PARAM;
   scratch = *stream;
   TA_MACDFIX_StreamStep( &scratch, inReal, outMACD, outMACDSignal, outMACDHist );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_MACDFIX_Close( TA_MACDFIX_Stream *stream )
{
   if( stream ) TA_Free( stream );
   return TA_SUCCESS;
}

