/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_unguarded.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  MF       Mario Fortier
 *  CC       Claude Code (AI assistant)
 *
 * Change history:
 *
 *  MMDDYY BY     Description
 *  -------------------------------------------------------------------
 *  010802 MF     Template creation.
 *  052603 MF     Adapt code to compile with .NET Managed C++
 *  070226 MF,CC  Speed optimization: cache the highest/lowest index
 *                instead of rescanning the window on every bar (same
 *                approach as MIN/MAX/MINMAX).
 */

TA_LIB_API int TA_MIDPOINT_Lookback( int optInTimePeriod )
{
   if( (int)optInTimePeriod == (int)0x80000000 )
      optInTimePeriod = 14;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return -1;
   return optInTimePeriod - 1;
}

TA_LIB_API TA_RetCode TA_MIDPOINT( int    startIdx,
                                   int    endIdx,
                                   const double inReal[],
                                   int optInTimePeriod,
                                   int          *outBegIdx,
                                   int          *outNBElement,
                                   double        outReal[] )
{
   double lowest;
   double highest;
   double tmpLow;
   double tmpHigh;
   int outIdx;
   int nbInitialElementNeeded;
   int trailingIdx;
   int lowestIdx;
   int highestIdx;
   int today;
   int i;

   if( startIdx < 0 )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( !inReal )
      return TA_BAD_PARAM;
   if( (int)optInTimePeriod == (int)0x80000000 )
      optInTimePeriod = 14;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   /* Find the highest and lowest value of a timeserie
    * over the period.
    *      MIDPOINT = (Highest Value + Lowest Value)/2
    *
    * See MIDPRICE if the input is a price bar with a
    * high and low timeserie.
    */
   /* Identify the minimum number of price bar needed
    * to identify at least one output over the specified
    * period.
    */
   nbInitialElementNeeded = optInTimePeriod - 1;
   /* Move up the start index if there is not
    * enough initial data.
    */
   if( startIdx < nbInitialElementNeeded )
   {
      startIdx = nbInitialElementNeeded;
   }
   /* Make sure there is still something to evaluate. */
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   /* Proceed with the calculation for the requested range.
    * Note that this algorithm allows the input and
    * output to be the same buffer.
    *
    * The highest/lowest of the window is cached with its
    * index; a rescan of the window is needed only when the
    * cached extremum drops out of the window (amortized O(1)
    * per bar instead of O(period)).
    */
   outIdx = 0;
   today = startIdx;
   trailingIdx = startIdx - nbInitialElementNeeded;
   highestIdx = 0 - 1;
   highest = 0.0;
   lowestIdx = 0 - 1;
   lowest = 0.0;
   while( today <= endIdx )
   {
      tmpHigh = inReal[today];
      tmpLow = tmpHigh;
      if( highestIdx < trailingIdx )
      {
         highestIdx = trailingIdx;
         highest = inReal[highestIdx];
         i = highestIdx;
         while( ++i <= today )
         {
            tmpHigh = inReal[i];
            if( tmpHigh > highest )
            {
               highestIdx = i;
               highest = tmpHigh;
            }
         }
      } else if( tmpHigh >= highest )
      {
         highestIdx = today;
         highest = tmpHigh;
      }
      if( lowestIdx < trailingIdx )
      {
         lowestIdx = trailingIdx;
         lowest = inReal[lowestIdx];
         i = lowestIdx;
         while( ++i <= today )
         {
            tmpLow = inReal[i];
            if( tmpLow < lowest )
            {
               lowestIdx = i;
               lowest = tmpLow;
            }
         }
      } else if( tmpLow <= lowest )
      {
         lowestIdx = today;
         lowest = tmpLow;
      }
      outReal[outIdx++] = (highest + lowest) / 2.0;
      trailingIdx += 1;
      today += 1;
   }
   /* Keep the outBegIdx relative to the
    * caller input before returning.
    */
   *outBegIdx= startIdx;
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_MIDPOINT_Unguarded( int    startIdx,
                                             int    endIdx,
                                             const double inReal[],
                                             int optInTimePeriod,
                                             int          *outBegIdx,
                                             int          *outNBElement,
                                             double        outReal[] )
{
   double lowest;
   double highest;
   double tmpLow;
   double tmpHigh;
   int outIdx;
   int nbInitialElementNeeded;
   int trailingIdx;
   int lowestIdx;
   int highestIdx;
   int today;
   int i;

   nbInitialElementNeeded = optInTimePeriod - 1;
   if( startIdx < nbInitialElementNeeded )
   {
      startIdx = nbInitialElementNeeded;
   }
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   outIdx = 0;
   today = startIdx;
   trailingIdx = startIdx - nbInitialElementNeeded;
   highestIdx = 0 - 1;
   highest = 0.0;
   lowestIdx = 0 - 1;
   lowest = 0.0;
   while( today <= endIdx )
   {
      tmpHigh = inReal[today];
      tmpLow = tmpHigh;
      if( highestIdx < trailingIdx )
      {
         highestIdx = trailingIdx;
         highest = inReal[highestIdx];
         i = highestIdx;
         while( ++i <= today )
         {
            tmpHigh = inReal[i];
            if( tmpHigh > highest )
            {
               highestIdx = i;
               highest = tmpHigh;
            }
         }
      } else if( tmpHigh >= highest )
      {
         highestIdx = today;
         highest = tmpHigh;
      }
      if( lowestIdx < trailingIdx )
      {
         lowestIdx = trailingIdx;
         lowest = inReal[lowestIdx];
         i = lowestIdx;
         while( ++i <= today )
         {
            tmpLow = inReal[i];
            if( tmpLow < lowest )
            {
               lowestIdx = i;
               lowest = tmpLow;
            }
         }
      } else if( tmpLow <= lowest )
      {
         lowestIdx = today;
         lowest = tmpLow;
      }
      outReal[outIdx++] = (highest + lowest) / 2.0;
      trailingIdx += 1;
      today += 1;
   }
   *outBegIdx= startIdx;
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

TA_RetCode TA_S_MIDPOINT( int    startIdx,
                          int    endIdx,
                          const float inReal[],
                          int optInTimePeriod,
                          int          *outBegIdx,
                          int          *outNBElement,
                          double        outReal[] )
{
   double lowest;
   double highest;
   double tmpLow;
   double tmpHigh;
   int outIdx;
   int nbInitialElementNeeded;
   int trailingIdx;
   int lowestIdx;
   int highestIdx;
   int today;
   int i;

   if( startIdx < 0 )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( !inReal )
      return TA_BAD_PARAM;
   if( (int)optInTimePeriod == (int)0x80000000 )
      optInTimePeriod = 14;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   nbInitialElementNeeded = optInTimePeriod - 1;
   if( startIdx < nbInitialElementNeeded )
   {
      startIdx = nbInitialElementNeeded;
   }
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   outIdx = 0;
   today = startIdx;
   trailingIdx = startIdx - nbInitialElementNeeded;
   highestIdx = 0 - 1;
   highest = 0.0;
   lowestIdx = 0 - 1;
   lowest = 0.0;
   while( today <= endIdx )
   {
      tmpHigh = (double)inReal[today];
      tmpLow = tmpHigh;
      if( highestIdx < trailingIdx )
      {
         highestIdx = trailingIdx;
         highest = (double)inReal[highestIdx];
         i = highestIdx;
         while( ++i <= today )
         {
            tmpHigh = (double)inReal[i];
            if( tmpHigh > highest )
            {
               highestIdx = i;
               highest = tmpHigh;
            }
         }
      } else if( tmpHigh >= highest )
      {
         highestIdx = today;
         highest = tmpHigh;
      }
      if( lowestIdx < trailingIdx )
      {
         lowestIdx = trailingIdx;
         lowest = (double)inReal[lowestIdx];
         i = lowestIdx;
         while( ++i <= today )
         {
            tmpLow = (double)inReal[i];
            if( tmpLow < lowest )
            {
               lowestIdx = i;
               lowest = tmpLow;
            }
         }
      } else if( tmpLow <= lowest )
      {
         lowestIdx = today;
         lowest = tmpLow;
      }
      outReal[outIdx++] = (highest + lowest) / 2.0;
      trailingIdx += 1;
      today += 1;
   }
   *outBegIdx= startIdx;
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

TA_RetCode TA_S_MIDPOINT_Unguarded( int    startIdx,
                                    int    endIdx,
                                    const float inReal[],
                                    int optInTimePeriod,
                                    int          *outBegIdx,
                                    int          *outNBElement,
                                    double        outReal[] )
{
   double lowest;
   double highest;
   double tmpLow;
   double tmpHigh;
   int outIdx;
   int nbInitialElementNeeded;
   int trailingIdx;
   int lowestIdx;
   int highestIdx;
   int today;
   int i;

   nbInitialElementNeeded = optInTimePeriod - 1;
   if( startIdx < nbInitialElementNeeded )
   {
      startIdx = nbInitialElementNeeded;
   }
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   outIdx = 0;
   today = startIdx;
   trailingIdx = startIdx - nbInitialElementNeeded;
   highestIdx = 0 - 1;
   highest = 0.0;
   lowestIdx = 0 - 1;
   lowest = 0.0;
   while( today <= endIdx )
   {
      tmpHigh = (double)inReal[today];
      tmpLow = tmpHigh;
      if( highestIdx < trailingIdx )
      {
         highestIdx = trailingIdx;
         highest = (double)inReal[highestIdx];
         i = highestIdx;
         while( ++i <= today )
         {
            tmpHigh = (double)inReal[i];
            if( tmpHigh > highest )
            {
               highestIdx = i;
               highest = tmpHigh;
            }
         }
      } else if( tmpHigh >= highest )
      {
         highestIdx = today;
         highest = tmpHigh;
      }
      if( lowestIdx < trailingIdx )
      {
         lowestIdx = trailingIdx;
         lowest = (double)inReal[lowestIdx];
         i = lowestIdx;
         while( ++i <= today )
         {
            tmpLow = (double)inReal[i];
            if( tmpLow < lowest )
            {
               lowestIdx = i;
               lowest = tmpLow;
            }
         }
      } else if( tmpLow <= lowest )
      {
         lowestIdx = today;
         lowest = tmpLow;
      }
      outReal[outIdx++] = (highest + lowest) / 2.0;
      trailingIdx += 1;
      today += 1;
   }
   *outBegIdx= startIdx;
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

/**** Streaming API *****/

struct TA_MIDPOINT_Stream {
   int optInTimePeriod;
   double lowest;
   double highest;
   double tmpLow;
   double tmpHigh;
   int trailingIdx;
   int lowestIdx;
   int highestIdx;
   int i;
   int today;
   int xCap;
   double *x_inReal;
   double *xMirror_inReal;
};

/* Private function, not in public API. */
static void TA_MIDPOINT_ReleaseInternal( struct TA_MIDPOINT_Stream *sp )
{
   if( !sp ) return;
   if( sp->x_inReal ) TA_Free( sp->x_inReal );
   if( sp->xMirror_inReal ) TA_Free( sp->xMirror_inReal );
   TA_Free( sp );
}

/* Private function, not in public API. */
static void TA_MIDPOINT_StepInternal( struct TA_MIDPOINT_Stream *sp, double inReal, double *outReal )
{
   if( sp->today >= 1073741824 )
   {
      int rebaseShift = ( sp->trailingIdx / sp->xCap ) * sp->xCap;
      sp->today -= rebaseShift;
      sp->trailingIdx -= rebaseShift;
      sp->highestIdx -= rebaseShift;
      sp->i -= rebaseShift;
      sp->lowestIdx -= rebaseShift;
   }
   sp->x_inReal[sp->today % sp->xCap] = inReal;
   sp->tmpHigh = sp->x_inReal[sp->today % sp->xCap];
   sp->tmpLow = sp->tmpHigh;
   if( sp->highestIdx < sp->trailingIdx )
   {
      sp->highestIdx = sp->trailingIdx;
      sp->highest = sp->x_inReal[sp->highestIdx % sp->xCap];
      sp->i = sp->highestIdx;
      while( ++sp->i <= sp->today )
      {
         sp->tmpHigh = sp->x_inReal[sp->i % sp->xCap];
         if( sp->tmpHigh > sp->highest )
         {
            sp->highestIdx = sp->i;
            sp->highest = sp->tmpHigh;
         }
      }
   } else if( sp->tmpHigh >= sp->highest )
   {
      sp->highestIdx = sp->today;
      sp->highest = sp->tmpHigh;
   }
   if( sp->lowestIdx < sp->trailingIdx )
   {
      sp->lowestIdx = sp->trailingIdx;
      sp->lowest = sp->x_inReal[sp->lowestIdx % sp->xCap];
      sp->i = sp->lowestIdx;
      while( ++sp->i <= sp->today )
      {
         sp->tmpLow = sp->x_inReal[sp->i % sp->xCap];
         if( sp->tmpLow < sp->lowest )
         {
            sp->lowestIdx = sp->i;
            sp->lowest = sp->tmpLow;
         }
      }
   } else if( sp->tmpLow <= sp->lowest )
   {
      sp->lowestIdx = sp->today;
      sp->lowest = sp->tmpLow;
   }
   *outReal= (sp->highest + sp->lowest) / 2.0;
   sp->trailingIdx += 1;
   sp->today += 1;
}

/* Private function, not in public API. */
TA_RetCode TA_MIDPOINT_OpenInternal( struct TA_MIDPOINT_Stream **stream, const double inReal[], int startIdx, int historyLen, int optInTimePeriod, double *outReal )
{
   struct TA_MIDPOINT_Stream *sp;
   int endIdx;
   int dummyBegIdx;
   int dummyNBElement;
   double lastValue_outReal;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( !inReal || !outReal ) return TA_BAD_PARAM;
   if( historyLen < 1 ) return TA_BAD_PARAM;
   if( (int)optInTimePeriod == (int)0x80000000 )
      optInTimePeriod = 14;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;

   endIdx = historyLen - 1;
   dummyBegIdx = 0;
   dummyNBElement = 0;
   lastValue_outReal = 0.0;
   (void)startIdx; (void)dummyBegIdx; (void)dummyNBElement;

   {
      double lowest = 0.0;
      double highest = 0.0;
      double tmpLow = 0.0;
      double tmpHigh = 0.0;
      int outIdx;
      int nbInitialElementNeeded;
      int trailingIdx = 0;
      int lowestIdx = 0;
      int highestIdx = 0;
      int today = 0;
      int i = 0;
      /* Find the highest and lowest value of a timeserie
       * over the period.
       *      MIDPOINT = (Highest Value + Lowest Value)/2
       *
       * See MIDPRICE if the input is a price bar with a
       * high and low timeserie.
       */
      /* Identify the minimum number of price bar needed
       * to identify at least one output over the specified
       * period.
       */
      nbInitialElementNeeded = optInTimePeriod - 1;
      /* Move up the start index if there is not
       * enough initial data.
       */
      if( startIdx < nbInitialElementNeeded )
      {
         startIdx = nbInitialElementNeeded;
      }
      /* Make sure there is still something to evaluate. */
      if( startIdx > endIdx )
      {
         dummyBegIdx = 0;
         dummyNBElement = 0;
         return TA_BAD_PARAM;
      }
      /* Proceed with the calculation for the requested range.
       * Note that this algorithm allows the input and
       * output to be the same buffer.
       *
       * The highest/lowest of the window is cached with its
       * index; a rescan of the window is needed only when the
       * cached extremum drops out of the window (amortized O(1)
       * per bar instead of O(period)).
       */
      outIdx = 0;
      today = startIdx;
      trailingIdx = startIdx - nbInitialElementNeeded;
      highestIdx = 0 - 1;
      highest = 0.0;
      lowestIdx = 0 - 1;
      lowest = 0.0;
      while( today <= endIdx )
      {
         tmpHigh = inReal[today];
         tmpLow = tmpHigh;
         if( highestIdx < trailingIdx )
         {
            highestIdx = trailingIdx;
            highest = inReal[highestIdx];
            i = highestIdx;
            while( ++i <= today )
            {
               tmpHigh = inReal[i];
               if( tmpHigh > highest )
               {
                  highestIdx = i;
                  highest = tmpHigh;
               }
            }
         } else if( tmpHigh >= highest )
         {
            highestIdx = today;
            highest = tmpHigh;
         }
         if( lowestIdx < trailingIdx )
         {
            lowestIdx = trailingIdx;
            lowest = inReal[lowestIdx];
            i = lowestIdx;
            while( ++i <= today )
            {
               tmpLow = inReal[i];
               if( tmpLow < lowest )
               {
                  lowestIdx = i;
                  lowest = tmpLow;
               }
            }
         } else if( tmpLow <= lowest )
         {
            lowestIdx = today;
            lowest = tmpLow;
         }
         lastValue_outReal = (highest + lowest) / 2.0;
         trailingIdx += 1;
         today += 1;
      }
      /* Keep the outBegIdx relative to the
       * caller input before returning.
       */
      dummyBegIdx = startIdx;
      dummyNBElement = outIdx;

      /* Capture the live batch state into the handle. */
      sp = (struct TA_MIDPOINT_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) { return TA_ALLOC_ERR; }
      memset( sp, 0, sizeof(*sp) );
      sp->optInTimePeriod = optInTimePeriod;
      sp->lowest = lowest;
      sp->highest = highest;
      sp->tmpLow = tmpLow;
      sp->tmpHigh = tmpHigh;
      sp->trailingIdx = trailingIdx;
      sp->lowestIdx = lowestIdx;
      sp->highestIdx = highestIdx;
      sp->i = i;
      sp->today = today;
      sp->xCap = (int)(today - trailingIdx) + 1;
      if( sp->xCap < 1 || sp->xCap > historyLen ) { TA_MIDPOINT_ReleaseInternal( sp ); return TA_INTERNAL_ERROR; }
      sp->x_inReal = (double *)TA_Malloc( sizeof(double) * (size_t)sp->xCap );
      if( !sp->x_inReal ) { TA_MIDPOINT_ReleaseInternal( sp ); return TA_ALLOC_ERR; }
      sp->xMirror_inReal = (double *)TA_Malloc( sizeof(double) * (size_t)sp->xCap );
      if( !sp->xMirror_inReal ) { TA_MIDPOINT_ReleaseInternal( sp ); return TA_ALLOC_ERR; }
      { int fillJ;
        for( fillJ = historyLen - sp->xCap; fillJ < historyLen; fillJ++ )
        {
           sp->x_inReal[fillJ % sp->xCap] = inReal[fillJ];
        }
      }
      *outReal = lastValue_outReal;
      *stream = sp;
      return TA_SUCCESS;
   }
}

TA_LIB_API TA_RetCode TA_MIDPOINT_Open( TA_MIDPOINT_Stream **stream, const double inReal[], int historyLen, int optInTimePeriod, double *outReal )
{
   return TA_MIDPOINT_OpenInternal( stream, inReal, 0, historyLen, optInTimePeriod, outReal );
}

TA_LIB_API TA_RetCode TA_MIDPOINT_OpenAndFill( TA_MIDPOINT_Stream **stream, const double inReal[], int historyLen, int optInTimePeriod, int *outBegIdx, int *outNBElement, double outReal[] )
{
   struct TA_MIDPOINT_Stream *sp;
   int endIdx;
   int startIdx;
   int dummyBegIdx;
   int dummyNBElement;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( !inReal || !outReal || !outBegIdx || !outNBElement ) return TA_BAD_PARAM;
   if( historyLen < 1 ) return TA_BAD_PARAM;
   if( (const void *)outReal == (const void *)inReal ) return TA_BAD_PARAM;
   if( (int)optInTimePeriod == (int)0x80000000 )
      optInTimePeriod = 14;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;

   endIdx = historyLen - 1;
   startIdx = 0;
   dummyBegIdx = 0;
   dummyNBElement = 0;
   (void)startIdx; (void)dummyBegIdx; (void)dummyNBElement;

   {
      double lowest = 0.0;
      double highest = 0.0;
      double tmpLow = 0.0;
      double tmpHigh = 0.0;
      int outIdx;
      int nbInitialElementNeeded;
      int trailingIdx = 0;
      int lowestIdx = 0;
      int highestIdx = 0;
      int today = 0;
      int i = 0;
      /* Find the highest and lowest value of a timeserie
       * over the period.
       *      MIDPOINT = (Highest Value + Lowest Value)/2
       *
       * See MIDPRICE if the input is a price bar with a
       * high and low timeserie.
       */
      /* Identify the minimum number of price bar needed
       * to identify at least one output over the specified
       * period.
       */
      nbInitialElementNeeded = optInTimePeriod - 1;
      /* Move up the start index if there is not
       * enough initial data.
       */
      if( startIdx < nbInitialElementNeeded )
      {
         startIdx = nbInitialElementNeeded;
      }
      /* Make sure there is still something to evaluate. */
      if( startIdx > endIdx )
      {
         *outBegIdx= 0;
         *outNBElement= 0;
         return TA_BAD_PARAM;
      }
      /* Proceed with the calculation for the requested range.
       * Note that this algorithm allows the input and
       * output to be the same buffer.
       *
       * The highest/lowest of the window is cached with its
       * index; a rescan of the window is needed only when the
       * cached extremum drops out of the window (amortized O(1)
       * per bar instead of O(period)).
       */
      outIdx = 0;
      today = startIdx;
      trailingIdx = startIdx - nbInitialElementNeeded;
      highestIdx = 0 - 1;
      highest = 0.0;
      lowestIdx = 0 - 1;
      lowest = 0.0;
      while( today <= endIdx )
      {
         tmpHigh = inReal[today];
         tmpLow = tmpHigh;
         if( highestIdx < trailingIdx )
         {
            highestIdx = trailingIdx;
            highest = inReal[highestIdx];
            i = highestIdx;
            while( ++i <= today )
            {
               tmpHigh = inReal[i];
               if( tmpHigh > highest )
               {
                  highestIdx = i;
                  highest = tmpHigh;
               }
            }
         } else if( tmpHigh >= highest )
         {
            highestIdx = today;
            highest = tmpHigh;
         }
         if( lowestIdx < trailingIdx )
         {
            lowestIdx = trailingIdx;
            lowest = inReal[lowestIdx];
            i = lowestIdx;
            while( ++i <= today )
            {
               tmpLow = inReal[i];
               if( tmpLow < lowest )
               {
                  lowestIdx = i;
                  lowest = tmpLow;
               }
            }
         } else if( tmpLow <= lowest )
         {
            lowestIdx = today;
            lowest = tmpLow;
         }
         outReal[outIdx++] = (highest + lowest) / 2.0;
         trailingIdx += 1;
         today += 1;
      }
      /* Keep the outBegIdx relative to the
       * caller input before returning.
       */
      *outBegIdx= startIdx;
      *outNBElement= outIdx;

      /* Capture the live batch state into the handle. */
      sp = (struct TA_MIDPOINT_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) { return TA_ALLOC_ERR; }
      memset( sp, 0, sizeof(*sp) );
      sp->optInTimePeriod = optInTimePeriod;
      sp->lowest = lowest;
      sp->highest = highest;
      sp->tmpLow = tmpLow;
      sp->tmpHigh = tmpHigh;
      sp->trailingIdx = trailingIdx;
      sp->lowestIdx = lowestIdx;
      sp->highestIdx = highestIdx;
      sp->i = i;
      sp->today = today;
      sp->xCap = (int)(today - trailingIdx) + 1;
      if( sp->xCap < 1 || sp->xCap > historyLen ) { TA_MIDPOINT_ReleaseInternal( sp ); return TA_INTERNAL_ERROR; }
      sp->x_inReal = (double *)TA_Malloc( sizeof(double) * (size_t)sp->xCap );
      if( !sp->x_inReal ) { TA_MIDPOINT_ReleaseInternal( sp ); return TA_ALLOC_ERR; }
      sp->xMirror_inReal = (double *)TA_Malloc( sizeof(double) * (size_t)sp->xCap );
      if( !sp->xMirror_inReal ) { TA_MIDPOINT_ReleaseInternal( sp ); return TA_ALLOC_ERR; }
      { int fillJ;
        for( fillJ = historyLen - sp->xCap; fillJ < historyLen; fillJ++ )
        {
           sp->x_inReal[fillJ % sp->xCap] = inReal[fillJ];
        }
      }
      *stream = sp;
      return TA_SUCCESS;
   }
}

TA_LIB_API TA_RetCode TA_MIDPOINT_Update( TA_MIDPOINT_Stream *stream, double inReal, double *outReal )
{
   if( !stream || !outReal ) return TA_BAD_PARAM;
   TA_MIDPOINT_StepInternal( stream, inReal, outReal );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_MIDPOINT_Peek( const TA_MIDPOINT_Stream *stream, double inReal, double *outReal )
{
   struct TA_MIDPOINT_Stream scratch;

   if( !stream || !outReal ) return TA_BAD_PARAM;
   scratch = *stream;
   scratch.x_inReal = stream->xMirror_inReal;
   memcpy( scratch.x_inReal, stream->x_inReal, sizeof(double) * (size_t)stream->xCap );
   TA_MIDPOINT_StepInternal( &scratch, inReal, outReal );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_MIDPOINT_Close( TA_MIDPOINT_Stream *stream )
{
   TA_MIDPOINT_ReleaseInternal( stream );
   return TA_SUCCESS;
}

