/* TA-LIB Copyright (c) 1999-2026, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_stream_private.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  KL       Kevin Lin (@kevinlincg)
 *
 * Change history:
 *
 *  MMDDYY BY   Description
 *  -------------------------------------------------------------------
 *  081226 KL   Initial version.
 */

TA_LIB_API int TA_MARKETFI_Lookback( void )
{
   /* Each output depends only on its own bar, so nothing is consumed
    * before the first one can be produced.
    */
   return 0;
}

TA_LIB_API TA_RetCode TA_MARKETFI( int    startIdx,
                                   int    endIdx,
                                   const double inHigh[],
                                   const double inLow[],
                                   const double inVolume[],
                                   int          *outBegIdx,
                                   int          *outNBElement,
                                   double        outReal[] )
{
   int outIdx;
   int i;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !inVolume )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   /* Bill Williams' Market Facilitation Index: the price range a bar
    * travelled per unit of volume traded, i.e. how much movement the
    * market "facilitated" per tick.
    *
    *      MARKETFI = ( High - Low ) / Volume
    *
    * Stateless and per-bar: no seeding, no smoothing, no accumulator and
    * no unstable period, so the output for a bar never depends on where
    * the caller started the range.
    *
    * Retail material often abbreviates this "MFI" or "BW MFI". TA_MFI is
    * already the Money Flow Index, so this carries the name Tulip and
    * pandas-ta-classic use.
    */
   outIdx = 0;
   for( i = startIdx; i <= endIdx; i += 1 )
   {
      /* A zero-volume bar would divide by zero. Neither reference guards
       * it -- they emit +/-Inf, or NaN when the range is zero too -- but
       * issue #112 settled that a successful call never emits NaN or Inf,
       * so an untraded bar facilitated no movement and reports 0.
       *
       * The comparison is an exact != 0.0 rather than TA_IS_ZERO, whose
       * 1e-14 band is an absolute threshold and meaningless against an
       * unbounded volume scale. Same reasoning as the prevClose guard in
       * ta_codegen/input/nvi/nvi.c.
       */
      if( inVolume[i] != 0.0 )
      {
         outReal[outIdx++] = (inHigh[i] - inLow[i]) / inVolume[i];
      } else 
      {
         outReal[outIdx++] = 0.0;
      }
   }
   *outBegIdx= startIdx;
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

TA_RetCode TA_S_MARKETFI( int    startIdx,
                          int    endIdx,
                          const float inHigh[],
                          const float inLow[],
                          const float inVolume[],
                          int          *outBegIdx,
                          int          *outNBElement,
                          double        outReal[] )
{
   int outIdx;
   int i;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !inVolume )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   outIdx = 0;
   for( i = startIdx; i <= endIdx; i += 1 )
   {
      if( (double)inVolume[i] != 0.0 )
      {
         outReal[outIdx++] = ((double)inHigh[i] - (double)inLow[i]) / (double)inVolume[i];
      } else 
      {
         outReal[outIdx++] = 0.0;
      }
   }
   *outBegIdx= startIdx;
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

/**** Streaming API *****/

struct TA_MARKETFI_Stream {
   /* The bars this handle has an output for (see TA_MARKETFI_OutRange). */
   int outRangeBegIdx;
   int outRangeCount;
   /* The value(s) at the last bar the stream counted (see TA_MARKETFI_Value). */
   double cur_outReal;
};

/* Private function, not in public API. */
static void TA_MARKETFI_StepImpl( struct TA_MARKETFI_Stream *sp, double inHigh, double inLow, double inVolume, double *outReal )
{
   /* A zero-volume bar would divide by zero. Neither reference guards
    * it -- they emit +/-Inf, or NaN when the range is zero too -- but
    * issue #112 settled that a successful call never emits NaN or Inf,
    * so an untraded bar facilitated no movement and reports 0.
    *
    * The comparison is an exact != 0.0 rather than TA_IS_ZERO, whose
    * 1e-14 band is an absolute threshold and meaningless against an
    * unbounded volume scale. Same reasoning as the prevClose guard in
    * ta_codegen/input/nvi/nvi.c.
    */
   if( inVolume != 0.0 )
   {
      *outReal= (inHigh - inLow) / inVolume;
   } else 
   {
      *outReal= 0.0;
   }
   sp->cur_outReal = *outReal;
}

static TA_RetCode TA_MARKETFI_OpenImpl( struct TA_MARKETFI_Stream **stream, const double inHigh[], const double inLow[], const double inVolume[], int startIdx, int historyLen, int *outBegIdx, int *outNBElement, double outReal[], int outStride )
{
   struct TA_MARKETFI_Stream *sp;
   int endIdx;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !inVolume || !outReal ) return TA_BAD_PARAM;
   if( startIdx > historyLen - 1 )
   {
      *outBegIdx = 0;
      *outNBElement = 0;
      return TA_INSUFFICIENT_HISTORY;
   }

   endIdx = historyLen - 1;

   {
      int outIdx;
      int i;
      /* Bill Williams' Market Facilitation Index: the price range a bar
       * travelled per unit of volume traded, i.e. how much movement the
       * market "facilitated" per tick.
       *
       *      MARKETFI = ( High - Low ) / Volume
       *
       * Stateless and per-bar: no seeding, no smoothing, no accumulator and
       * no unstable period, so the output for a bar never depends on where
       * the caller started the range.
       *
       * Retail material often abbreviates this "MFI" or "BW MFI". TA_MFI is
       * already the Money Flow Index, so this carries the name Tulip and
       * pandas-ta-classic use.
       */
      outIdx = 0;
      for( i = startIdx; i <= endIdx; i += 1 )
      {
         /* A zero-volume bar would divide by zero. Neither reference guards
          * it -- they emit +/-Inf, or NaN when the range is zero too -- but
          * issue #112 settled that a successful call never emits NaN or Inf,
          * so an untraded bar facilitated no movement and reports 0.
          *
          * The comparison is an exact != 0.0 rather than TA_IS_ZERO, whose
          * 1e-14 band is an absolute threshold and meaningless against an
          * unbounded volume scale. Same reasoning as the prevClose guard in
          * ta_codegen/input/nvi/nvi.c.
          */
         if( inVolume[i] != 0.0 )
         {
            outReal[outIdx++ * outStride] = (inHigh[i] - inLow[i]) / inVolume[i];
         } else 
         {
            outReal[outIdx++ * outStride] = 0.0;
         }
      }
      *outBegIdx= startIdx;
      *outNBElement= outIdx;

      /* Capture the live batch state into the handle. */
      sp = (struct TA_MARKETFI_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) { return TA_ALLOC_ERR; }
      memset( sp, 0, sizeof(*sp) );
      sp->outRangeBegIdx = *outBegIdx;
      sp->outRangeCount = *outNBElement;
      sp->cur_outReal = outReal[(*outNBElement - 1) * outStride];
      *stream = sp;
      return TA_SUCCESS;
   }
}

/* Private function, not in public API. */
TA_RetCode TA_MARKETFI_OpenInternal( struct TA_MARKETFI_Stream **stream, const double inHigh[], const double inLow[], const double inVolume[], int startIdx, int historyLen, double *outReal )
{
   TA_RetCode retCode;
   int dummyBegIdx = 0;
   int dummyNBElement = 0;
   double sink_outReal = 0.0;
   retCode = TA_MARKETFI_OpenImpl( stream, inHigh, inLow, inVolume, startIdx, historyLen, &dummyBegIdx, &dummyNBElement, &sink_outReal, 0 );
   if( retCode == TA_SUCCESS )
   {
      *outReal = sink_outReal;
   }
   return retCode;
}

TA_LIB_API TA_RetCode TA_MARKETFI_Open( TA_MARKETFI_Stream **stream, const double inHigh[], const double inLow[], const double inVolume[], int historyLen, double *outReal )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !inVolume || !outReal ) return TA_BAD_PARAM;
   return TA_MARKETFI_OpenInternal( stream, inHigh, inLow, inVolume, 0, historyLen, outReal );
}

TA_LIB_API TA_RetCode TA_MARKETFI_OpenAndFill( TA_MARKETFI_Stream **stream, const double inHigh[], const double inLow[], const double inVolume[], int historyLen, int *outBegIdx, int *outNBElement, double outReal[] )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !inVolume || !outBegIdx || !outNBElement || !outReal ) return TA_BAD_PARAM;
   if( (const void *)outReal == (const void *)inHigh || (const void *)outReal == (const void *)inLow || (const void *)outReal == (const void *)inVolume ) return TA_BAD_PARAM;
   return TA_MARKETFI_OpenAndFillInternal( stream, inHigh, inLow, inVolume, 0, historyLen, outBegIdx, outNBElement, outReal );
}

/* Private function, not in public API. */
TA_RetCode TA_MARKETFI_OpenAndFillInternal( struct TA_MARKETFI_Stream **stream, const double inHigh[], const double inLow[], const double inVolume[], int startIdx, int historyLen, int *outBegIdx, int *outNBElement, double outReal[] )
{
   return TA_MARKETFI_OpenImpl( stream, inHigh, inLow, inVolume, startIdx, historyLen, outBegIdx, outNBElement, outReal, 1 );
}

TA_LIB_API TA_RetCode TA_MARKETFI_Update( TA_MARKETFI_Stream *stream, double inHigh, double inLow, double inVolume, double *outReal )
{
   if( !stream || !outReal ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) || !TA_IS_FINITE( inVolume ) ) return TA_BAD_PARAM;
   TA_MARKETFI_StepImpl( stream, inHigh, inLow, inVolume, outReal );
   if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_MARKETFI_Peek( const TA_MARKETFI_Stream *stream, double inHigh, double inLow, double inVolume, double *outReal )
{
   if( !stream || !outReal ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) || !TA_IS_FINITE( inVolume ) ) return TA_BAD_PARAM;
   /* A zero-volume bar would divide by zero. Neither reference guards
    * it -- they emit +/-Inf, or NaN when the range is zero too -- but
    * issue #112 settled that a successful call never emits NaN or Inf,
    * so an untraded bar facilitated no movement and reports 0.
    *
    * The comparison is an exact != 0.0 rather than TA_IS_ZERO, whose
    * 1e-14 band is an absolute threshold and meaningless against an
    * unbounded volume scale. Same reasoning as the prevClose guard in
    * ta_codegen/input/nvi/nvi.c.
    */
   if( inVolume != 0.0 )
   {
      *outReal= (inHigh - inLow) / inVolume;
   } else 
   {
      *outReal= 0.0;
   }
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_MARKETFI_Close( TA_MARKETFI_Stream *stream )
{
   if( stream ) TA_Free( stream );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_MARKETFI_Value( const TA_MARKETFI_Stream *stream, double *outReal )
{
   if( !stream || !outReal ) return TA_BAD_PARAM;
   *outReal = stream->cur_outReal;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_MARKETFI_OutRange( const TA_MARKETFI_Stream *stream, int *outBegIdx, int *outNBElement )
{
   if( !stream || !outBegIdx || !outNBElement ) return TA_BAD_PARAM;
   *outBegIdx = stream->outRangeBegIdx;
   *outNBElement = stream->outRangeCount;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_MARKETFI_Advance( TA_MARKETFI_Stream *stream )
{
   if( !stream ) return TA_BAD_PARAM;
   if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_MARKETFI_Clone( const TA_MARKETFI_Stream *stream, TA_MARKETFI_Stream **clone )
{
   struct TA_MARKETFI_Stream *sp;

   if( !clone ) return TA_BAD_PARAM;
   *clone = NULL;
   if( !stream ) return TA_BAD_PARAM;
   sp = (struct TA_MARKETFI_Stream *)TA_Malloc( sizeof(*sp) );
   if( !sp ) return TA_ALLOC_ERR;
   *sp = *stream;
   *clone = sp;
   return TA_SUCCESS;
}

