/* TA-LIB Copyright (c) 1999-2026, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_stream_private.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  MF       Mario Fortier
 *
 *
 * Change history:
 *
 *  MMDDYY BY   Description
 *  -------------------------------------------------------------------
 *  112400 MF   Template creation.
 *  022203 MF   Add MAMA
 *  040503 MF   Add T3
 *  052603 MF   Adapt code to compile with .NET Managed C++
 *  111603 MF   Allow period of 1. Just copy input into output.
 *  060907 MF   Use TA_SMA/TA_EMA instead of internal implementation.
 *  072226 MF,CC Add HMA (issue #139).
 *  072426 MF,CC TA_MAType_DISABLED: period-independent identity copy (issue #93).
 *  090426 MF,CC Add ZLEMA (issue #347).
 *  090426 MF,CC Add RMA (issue #348).
 */

TA_LIB_API int TA_MA_Lookback( int optInTimePeriod, TA_MAType optInMAType )
{
   int retValue;
   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 30;
   else if( (int)optInTimePeriod < 1 || (int)optInTimePeriod > 100000 )
      return -1;
   if( (int)optInMAType == TA_INTEGER_DEFAULT || optInMAType == TA_MAType_DEFAULT )
      optInMAType = 0;
   else if( (int)optInMAType < TA_MATYPE_MIN || (int)optInMAType > TA_MATYPE_MAX )
      return -1;
   if( optInTimePeriod <= 1 || optInMAType == TA_MAType_DISABLED )
   {
      return 0;
   }
   switch( optInMAType )
   {
   case TA_MAType_SMA:
      retValue = TA_SMA_Lookback(optInTimePeriod);
      break;
   case TA_MAType_EMA:
      retValue = TA_EMA_Lookback(optInTimePeriod);
      break;
   case TA_MAType_WMA:
      retValue = TA_WMA_Lookback(optInTimePeriod);
      break;
   case TA_MAType_DEMA:
      retValue = TA_DEMA_Lookback(optInTimePeriod);
      break;
   case TA_MAType_TEMA:
      retValue = TA_TEMA_Lookback(optInTimePeriod);
      break;
   case TA_MAType_TRIMA:
      retValue = TA_TRIMA_Lookback(optInTimePeriod);
      break;
   case TA_MAType_KAMA:
      retValue = TA_KAMA_Lookback(optInTimePeriod);
      break;
   case TA_MAType_MAMA:
      retValue = TA_MAMA_Lookback(0.5,0.05);
      break;
   case TA_MAType_T3:
      retValue = TA_T3_Lookback(optInTimePeriod,0.7);
      break;
   case TA_MAType_HMA:
      retValue = TA_HMA_Lookback(optInTimePeriod);
      break;
   case TA_MAType_ZLEMA:
      retValue = TA_ZLEMA_Lookback(optInTimePeriod);
      break;
   case TA_MAType_RMA:
      retValue = TA_RMA_Lookback(optInTimePeriod);
      break;
   default:
      retValue = 0;
      break;
   }
   return retValue;
}

TA_LIB_API TA_RetCode TA_MA( int    startIdx,
                             int    endIdx,
                             const double inReal[],
                             int optInTimePeriod,
                             TA_MAType optInMAType,
                             int          *outBegIdx,
                             int          *outNBElement,
                             double        outReal[] )
{
   TA_RetCode retCode;
   int nbElement;
   int outIdx;
   int todayIdx;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 30;
   else if( (int)optInTimePeriod < 1 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInMAType == TA_INTEGER_DEFAULT || optInMAType == TA_MAType_DEFAULT )
      optInMAType = 0;
   else if( (int)optInMAType < TA_MATYPE_MIN || (int)optInMAType > TA_MATYPE_MAX )
      return TA_BAD_PARAM;
   if( !inReal )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   /* Nothing to produce: the range is shorter than the lookback. Answer here
    * rather than forwarding.
    *
    * The VALUE is the same either way: ma_lookback returns exactly the lookback
    * the arm's callee computes for itself, from the same arguments the arm
    * passes it, and every callee clamps startIdx to that lookback and yields
    * 0,0 without reading. What changes is whose frame answers, and that is
    * visible to one caller only - the zero-length no-I/O probe. It hands the
    * body empty arrays on this range to check that nothing is read; forwarding
    * makes the callee's PUBLIC input bound (endIdx + 1 elements, no
    * sub-lookback escape) answer TA_BAD_PARAM before any array is reached, so
    * the probe cannot tell "read nothing" from "never ran". ma was the last
    * core withheld from that sweep for exactly this reason; apo, bbands, ppo,
    * pvo and stddev already carried this guard. No legitimate caller is
    * affected: ma's own public tier already requires endIdx + 1 input elements,
    * and on this range the callee's OUTPUT bound is 0, so a caller sizing by
    * the published formula was never rejected by it.
    *
    * It cannot mask a TA_BAD_PARAM. An optInMAType outside the enum is refused
    * by the generated entry point above this guard. An in-range member with no
    * arm here would reach ma_lookback's own default and get 0, and 0 > endIdx
    * is false for every endIdx the entry point admits, so control still reaches
    * the switch and still answers TA_BAD_PARAM. The identity path below is out
    * of the guard's reach for the same reason - its lookback is 0.
    */
   if( TA_MA_Lookback(optInTimePeriod,optInMAType) > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   /* No-smoothing identity: period 1 (every MA type) or the explicit
    * TA_MAType_DISABLED (any period, issue #93). One copy path, lookback 0.
    */
   if( optInTimePeriod == 1 || optInMAType == TA_MAType_DISABLED )
   {
      nbElement = endIdx - startIdx + 1;
      *outNBElement= nbElement;
      for( todayIdx = startIdx, outIdx = 0; outIdx < nbElement; outIdx += 1, todayIdx += 1 )
      {
         outReal[outIdx] = inReal[todayIdx];
      }
      *outBegIdx= startIdx;
      return TA_SUCCESS;
   }
   /* Simply forward the job to the corresponding TA function. */
   switch( optInMAType )
   {
   case TA_MAType_SMA:
      retCode = TA_SMA(startIdx,endIdx,inReal,optInTimePeriod,outBegIdx,outNBElement,outReal);
      break;
   case TA_MAType_EMA:
      retCode = TA_EMA(startIdx,endIdx,inReal,optInTimePeriod,outBegIdx,outNBElement,outReal);
      break;
   case TA_MAType_WMA:
      retCode = TA_WMA(startIdx,endIdx,inReal,optInTimePeriod,outBegIdx,outNBElement,outReal);
      break;
   case TA_MAType_DEMA:
      retCode = TA_DEMA(startIdx,endIdx,inReal,optInTimePeriod,outBegIdx,outNBElement,outReal);
      break;
   case TA_MAType_TEMA:
      retCode = TA_TEMA(startIdx,endIdx,inReal,optInTimePeriod,outBegIdx,outNBElement,outReal);
      break;
   case TA_MAType_TRIMA:
      retCode = TA_TRIMA(startIdx,endIdx,inReal,optInTimePeriod,outBegIdx,outNBElement,outReal);
      break;
   case TA_MAType_KAMA:
      retCode = TA_KAMA(startIdx,endIdx,inReal,optInTimePeriod,outBegIdx,outNBElement,outReal);
      break;
   case TA_MAType_MAMA:
      /* The optInTimePeriod is ignored. FAMA is a nullable output
       * (issue #125): pass NULL to compute only the MAMA line into outReal.
       */
      retCode = TA_MAMA(startIdx,endIdx,inReal,0.5,0.05,outBegIdx,outNBElement,outReal,NULL);
      break;
   case TA_MAType_T3:
      retCode = TA_T3(startIdx,endIdx,inReal,optInTimePeriod,0.7,outBegIdx,outNBElement,outReal);
      break;
   case TA_MAType_HMA:
      retCode = TA_HMA(startIdx,endIdx,inReal,optInTimePeriod,outBegIdx,outNBElement,outReal);
      break;
   case TA_MAType_ZLEMA:
      retCode = TA_ZLEMA(startIdx,endIdx,inReal,optInTimePeriod,outBegIdx,outNBElement,outReal);
      break;
   case TA_MAType_RMA:
      retCode = TA_RMA(startIdx,endIdx,inReal,optInTimePeriod,outBegIdx,outNBElement,outReal);
      break;
   default:
      retCode = TA_BAD_PARAM;
      break;
   }
   return retCode;
}

TA_RetCode TA_S_MA( int    startIdx,
                    int    endIdx,
                    const float inReal[],
                    int optInTimePeriod,
                    TA_MAType optInMAType,
                    int          *outBegIdx,
                    int          *outNBElement,
                    double        outReal[] )
{
   TA_RetCode retCode;
   int nbElement;
   int outIdx;
   int todayIdx;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 30;
   else if( (int)optInTimePeriod < 1 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInMAType == TA_INTEGER_DEFAULT || optInMAType == TA_MAType_DEFAULT )
      optInMAType = 0;
   else if( (int)optInMAType < TA_MATYPE_MIN || (int)optInMAType > TA_MATYPE_MAX )
      return TA_BAD_PARAM;
   if( !inReal )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   if( TA_MA_Lookback(optInTimePeriod,optInMAType) > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   if( optInTimePeriod == 1 || optInMAType == TA_MAType_DISABLED )
   {
      nbElement = endIdx - startIdx + 1;
      *outNBElement= nbElement;
      for( todayIdx = startIdx, outIdx = 0; outIdx < nbElement; outIdx += 1, todayIdx += 1 )
      {
         outReal[outIdx] = (double)inReal[todayIdx];
      }
      *outBegIdx= startIdx;
      return TA_SUCCESS;
   }
   switch( optInMAType )
   {
   case TA_MAType_SMA:
      retCode = TA_S_SMA(startIdx,endIdx,inReal,optInTimePeriod,outBegIdx,outNBElement,outReal);
      break;
   case TA_MAType_EMA:
      retCode = TA_S_EMA(startIdx,endIdx,inReal,optInTimePeriod,outBegIdx,outNBElement,outReal);
      break;
   case TA_MAType_WMA:
      retCode = TA_S_WMA(startIdx,endIdx,inReal,optInTimePeriod,outBegIdx,outNBElement,outReal);
      break;
   case TA_MAType_DEMA:
      retCode = TA_S_DEMA(startIdx,endIdx,inReal,optInTimePeriod,outBegIdx,outNBElement,outReal);
      break;
   case TA_MAType_TEMA:
      retCode = TA_S_TEMA(startIdx,endIdx,inReal,optInTimePeriod,outBegIdx,outNBElement,outReal);
      break;
   case TA_MAType_TRIMA:
      retCode = TA_S_TRIMA(startIdx,endIdx,inReal,optInTimePeriod,outBegIdx,outNBElement,outReal);
      break;
   case TA_MAType_KAMA:
      retCode = TA_S_KAMA(startIdx,endIdx,inReal,optInTimePeriod,outBegIdx,outNBElement,outReal);
      break;
   case TA_MAType_MAMA:
      retCode = TA_S_MAMA(startIdx,endIdx,inReal,0.5,0.05,outBegIdx,outNBElement,outReal,NULL);
      break;
   case TA_MAType_T3:
      retCode = TA_S_T3(startIdx,endIdx,inReal,optInTimePeriod,0.7,outBegIdx,outNBElement,outReal);
      break;
   case TA_MAType_HMA:
      retCode = TA_S_HMA(startIdx,endIdx,inReal,optInTimePeriod,outBegIdx,outNBElement,outReal);
      break;
   case TA_MAType_ZLEMA:
      retCode = TA_S_ZLEMA(startIdx,endIdx,inReal,optInTimePeriod,outBegIdx,outNBElement,outReal);
      break;
   case TA_MAType_RMA:
      retCode = TA_S_RMA(startIdx,endIdx,inReal,optInTimePeriod,outBegIdx,outNBElement,outReal);
      break;
   default:
      retCode = TA_BAD_PARAM;
      break;
   }
   return retCode;
}

/**** Streaming API *****/

struct TA_MA_Stream {
   /* The bars this handle has an output for (see TA_MA_OutRange). */
   int outRangeBegIdx;
   int outRangeCount;
   /* The value(s) at the last bar the stream counted (see TA_MA_Value). */
   double cur_outReal;
   int optInTimePeriod;
   TA_MAType optInMAType;
   /* Sub-stream handle, tagged by optInMAType; NULL on the identity path. */
   void *sub;
};

/* Private function, not in public API. */
TA_RetCode TA_MA_OpenInternal( struct TA_MA_Stream **stream, const double inReal[], int startIdx, int historyLen, int optInTimePeriod, TA_MAType optInMAType, double *outReal )
{
   struct TA_MA_Stream *sp;
   TA_RetCode retCode;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inReal || !outReal ) return TA_BAD_PARAM;
   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 30;
   else if( (int)optInTimePeriod < 1 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInMAType == TA_INTEGER_DEFAULT || optInMAType == TA_MAType_DEFAULT )
      optInMAType = 0;
   else if( (int)optInMAType < TA_MATYPE_MIN || (int)optInMAType > TA_MATYPE_MAX )
      return TA_BAD_PARAM;

   sp = (struct TA_MA_Stream *)TA_Malloc( sizeof(*sp) );
   if( !sp ) return TA_ALLOC_ERR;
   memset( sp, 0, sizeof(*sp) );
   sp->optInTimePeriod = optInTimePeriod;
   sp->optInMAType = optInMAType;

   if( optInTimePeriod == 1 || optInMAType == TA_MAType_DISABLED )
   {
      int fillLb = TA_MA_Lookback( optInTimePeriod, optInMAType );
      if( startIdx > fillLb ) fillLb = startIdx;
      if( historyLen < fillLb + 1 ) { TA_Free( sp ); return TA_INSUFFICIENT_HISTORY; }
      *outReal = inReal[historyLen - 1];
      sp->outRangeBegIdx = fillLb;
      sp->outRangeCount = historyLen - fillLb;
      sp->cur_outReal = inReal[historyLen - 1];
      *stream = sp;
      return TA_SUCCESS;
   }

   retCode = TA_BAD_PARAM;
   switch( optInMAType )
   {
   case TA_MAType_SMA:
      {
         TA_SMA_Stream *sub = NULL;
         retCode = TA_SMA_OpenInternal( &sub, inReal, startIdx, historyLen, optInTimePeriod, outReal );
         sp->sub = sub;
         if( retCode == TA_SUCCESS )
            TA_SMA_OutRange( sub, &sp->outRangeBegIdx, &sp->outRangeCount );
      }
      break;
   case TA_MAType_EMA:
      {
         TA_EMA_Stream *sub = NULL;
         retCode = TA_EMA_OpenInternal( &sub, inReal, startIdx, historyLen, optInTimePeriod, outReal );
         sp->sub = sub;
         if( retCode == TA_SUCCESS )
            TA_EMA_OutRange( sub, &sp->outRangeBegIdx, &sp->outRangeCount );
      }
      break;
   case TA_MAType_WMA:
      {
         TA_WMA_Stream *sub = NULL;
         retCode = TA_WMA_OpenInternal( &sub, inReal, startIdx, historyLen, optInTimePeriod, outReal );
         sp->sub = sub;
         if( retCode == TA_SUCCESS )
            TA_WMA_OutRange( sub, &sp->outRangeBegIdx, &sp->outRangeCount );
      }
      break;
   case TA_MAType_DEMA:
      {
         TA_DEMA_Stream *sub = NULL;
         retCode = TA_DEMA_OpenInternal( &sub, inReal, startIdx, historyLen, optInTimePeriod, outReal );
         sp->sub = sub;
         if( retCode == TA_SUCCESS )
            TA_DEMA_OutRange( sub, &sp->outRangeBegIdx, &sp->outRangeCount );
      }
      break;
   case TA_MAType_TEMA:
      {
         TA_TEMA_Stream *sub = NULL;
         retCode = TA_TEMA_OpenInternal( &sub, inReal, startIdx, historyLen, optInTimePeriod, outReal );
         sp->sub = sub;
         if( retCode == TA_SUCCESS )
            TA_TEMA_OutRange( sub, &sp->outRangeBegIdx, &sp->outRangeCount );
      }
      break;
   case TA_MAType_TRIMA:
      {
         TA_TRIMA_Stream *sub = NULL;
         retCode = TA_TRIMA_OpenInternal( &sub, inReal, startIdx, historyLen, optInTimePeriod, outReal );
         sp->sub = sub;
         if( retCode == TA_SUCCESS )
            TA_TRIMA_OutRange( sub, &sp->outRangeBegIdx, &sp->outRangeCount );
      }
      break;
   case TA_MAType_KAMA:
      {
         TA_KAMA_Stream *sub = NULL;
         retCode = TA_KAMA_OpenInternal( &sub, inReal, startIdx, historyLen, optInTimePeriod, outReal );
         sp->sub = sub;
         if( retCode == TA_SUCCESS )
            TA_KAMA_OutRange( sub, &sp->outRangeBegIdx, &sp->outRangeCount );
      }
      break;
   case TA_MAType_MAMA:
      {
         TA_MAMA_Stream *sub = NULL;
         retCode = TA_MAMA_OpenInternal( &sub, inReal, startIdx, historyLen, 0.5, 0.05, outReal, NULL );
         sp->sub = sub;
         if( retCode == TA_SUCCESS )
            TA_MAMA_OutRange( sub, &sp->outRangeBegIdx, &sp->outRangeCount );
      }
      break;
   case TA_MAType_T3:
      {
         TA_T3_Stream *sub = NULL;
         retCode = TA_T3_OpenInternal( &sub, inReal, startIdx, historyLen, optInTimePeriod, 0.7, outReal );
         sp->sub = sub;
         if( retCode == TA_SUCCESS )
            TA_T3_OutRange( sub, &sp->outRangeBegIdx, &sp->outRangeCount );
      }
      break;
   case TA_MAType_HMA:
      {
         TA_HMA_Stream *sub = NULL;
         retCode = TA_HMA_OpenInternal( &sub, inReal, startIdx, historyLen, optInTimePeriod, outReal );
         sp->sub = sub;
         if( retCode == TA_SUCCESS )
            TA_HMA_OutRange( sub, &sp->outRangeBegIdx, &sp->outRangeCount );
      }
      break;
   case TA_MAType_ZLEMA:
      {
         TA_ZLEMA_Stream *sub = NULL;
         retCode = TA_ZLEMA_OpenInternal( &sub, inReal, startIdx, historyLen, optInTimePeriod, outReal );
         sp->sub = sub;
         if( retCode == TA_SUCCESS )
            TA_ZLEMA_OutRange( sub, &sp->outRangeBegIdx, &sp->outRangeCount );
      }
      break;
   case TA_MAType_RMA:
      {
         TA_RMA_Stream *sub = NULL;
         retCode = TA_RMA_OpenInternal( &sub, inReal, startIdx, historyLen, optInTimePeriod, outReal );
         sp->sub = sub;
         if( retCode == TA_SUCCESS )
            TA_RMA_OutRange( sub, &sp->outRangeBegIdx, &sp->outRangeCount );
      }
      break;
   default:
      retCode = TA_BAD_PARAM;
      break;
   }

   if( retCode != TA_SUCCESS )
   {
      TA_Free( sp );
      return retCode;
   }
   sp->cur_outReal = *outReal;
   *stream = sp;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_MA_Open( TA_MA_Stream **stream, const double inReal[], int historyLen, int optInTimePeriod, TA_MAType optInMAType, double *outReal )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inReal || !outReal ) return TA_BAD_PARAM;
   return TA_MA_OpenInternal( stream, inReal, 0, historyLen, optInTimePeriod, optInMAType, outReal );
}

TA_LIB_API TA_RetCode TA_MA_OpenAndFill( TA_MA_Stream **stream, const double inReal[], int historyLen, int optInTimePeriod, TA_MAType optInMAType, int *outBegIdx, int *outNBElement, double outReal[] )
{
   struct TA_MA_Stream *sp;
   TA_RetCode retCode;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inReal || !outBegIdx || !outNBElement || !outReal ) return TA_BAD_PARAM;
   if( (const void *)outReal == (const void *)inReal ) return TA_BAD_PARAM;
   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 30;
   else if( (int)optInTimePeriod < 1 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInMAType == TA_INTEGER_DEFAULT || optInMAType == TA_MAType_DEFAULT )
      optInMAType = 0;
   else if( (int)optInMAType < TA_MATYPE_MIN || (int)optInMAType > TA_MATYPE_MAX )
      return TA_BAD_PARAM;

   sp = (struct TA_MA_Stream *)TA_Malloc( sizeof(*sp) );
   if( !sp ) return TA_ALLOC_ERR;
   memset( sp, 0, sizeof(*sp) );
   sp->optInTimePeriod = optInTimePeriod;
   sp->optInMAType = optInMAType;

   if( optInTimePeriod == 1 || optInMAType == TA_MAType_DISABLED )
   {
      int fillLb = TA_MA_Lookback( optInTimePeriod, optInMAType );
      if( historyLen < fillLb + 1 ) { TA_Free( sp ); return TA_INSUFFICIENT_HISTORY; }
      {
         int fillIdx;
         *outBegIdx = fillLb;
         *outNBElement = historyLen - fillLb;
         for( fillIdx = 0; fillIdx < historyLen - fillLb; fillIdx++ )
         {
            outReal[fillIdx] = inReal[fillLb + fillIdx];
         }
      }
      sp->outRangeBegIdx = *outBegIdx;
      sp->outRangeCount = *outNBElement;
      sp->cur_outReal = inReal[historyLen - 1];
      *stream = sp;
      return TA_SUCCESS;
   }

   retCode = TA_BAD_PARAM;
   switch( optInMAType )
   {
   case TA_MAType_SMA:
      {
         TA_SMA_Stream *sub = NULL;
         retCode = TA_SMA_OpenAndFill( &sub, inReal, historyLen, optInTimePeriod, outBegIdx, outNBElement, outReal );
         sp->sub = sub;
      }
      break;
   case TA_MAType_EMA:
      {
         TA_EMA_Stream *sub = NULL;
         retCode = TA_EMA_OpenAndFill( &sub, inReal, historyLen, optInTimePeriod, outBegIdx, outNBElement, outReal );
         sp->sub = sub;
      }
      break;
   case TA_MAType_WMA:
      {
         TA_WMA_Stream *sub = NULL;
         retCode = TA_WMA_OpenAndFill( &sub, inReal, historyLen, optInTimePeriod, outBegIdx, outNBElement, outReal );
         sp->sub = sub;
      }
      break;
   case TA_MAType_DEMA:
      {
         TA_DEMA_Stream *sub = NULL;
         retCode = TA_DEMA_OpenAndFill( &sub, inReal, historyLen, optInTimePeriod, outBegIdx, outNBElement, outReal );
         sp->sub = sub;
      }
      break;
   case TA_MAType_TEMA:
      {
         TA_TEMA_Stream *sub = NULL;
         retCode = TA_TEMA_OpenAndFill( &sub, inReal, historyLen, optInTimePeriod, outBegIdx, outNBElement, outReal );
         sp->sub = sub;
      }
      break;
   case TA_MAType_TRIMA:
      {
         TA_TRIMA_Stream *sub = NULL;
         retCode = TA_TRIMA_OpenAndFill( &sub, inReal, historyLen, optInTimePeriod, outBegIdx, outNBElement, outReal );
         sp->sub = sub;
      }
      break;
   case TA_MAType_KAMA:
      {
         TA_KAMA_Stream *sub = NULL;
         retCode = TA_KAMA_OpenAndFill( &sub, inReal, historyLen, optInTimePeriod, outBegIdx, outNBElement, outReal );
         sp->sub = sub;
      }
      break;
   case TA_MAType_MAMA:
      {
         TA_MAMA_Stream *sub = NULL;
         retCode = TA_MAMA_OpenAndFill( &sub, inReal, historyLen, 0.5, 0.05, outBegIdx, outNBElement, outReal, NULL );
         sp->sub = sub;
      }
      break;
   case TA_MAType_T3:
      {
         TA_T3_Stream *sub = NULL;
         retCode = TA_T3_OpenAndFill( &sub, inReal, historyLen, optInTimePeriod, 0.7, outBegIdx, outNBElement, outReal );
         sp->sub = sub;
      }
      break;
   case TA_MAType_HMA:
      {
         TA_HMA_Stream *sub = NULL;
         retCode = TA_HMA_OpenAndFill( &sub, inReal, historyLen, optInTimePeriod, outBegIdx, outNBElement, outReal );
         sp->sub = sub;
      }
      break;
   case TA_MAType_ZLEMA:
      {
         TA_ZLEMA_Stream *sub = NULL;
         retCode = TA_ZLEMA_OpenAndFill( &sub, inReal, historyLen, optInTimePeriod, outBegIdx, outNBElement, outReal );
         sp->sub = sub;
      }
      break;
   case TA_MAType_RMA:
      {
         TA_RMA_Stream *sub = NULL;
         retCode = TA_RMA_OpenAndFill( &sub, inReal, historyLen, optInTimePeriod, outBegIdx, outNBElement, outReal );
         sp->sub = sub;
      }
      break;
   default:
      retCode = TA_BAD_PARAM;
      break;
   }

   if( retCode != TA_SUCCESS )
   {
      TA_Free( sp );
      return retCode;
   }
   sp->outRangeBegIdx = *outBegIdx;
   sp->outRangeCount = *outNBElement;
   sp->cur_outReal = outReal[*outNBElement - 1];
   *stream = sp;
   return TA_SUCCESS;
}

/* Private function, not in public API. */
TA_RetCode TA_MA_OpenAndFillInternal( struct TA_MA_Stream **stream, const double inReal[], int startIdx, int historyLen, int optInTimePeriod, TA_MAType optInMAType, int *outBegIdx, int *outNBElement, double outReal[] )
{
   struct TA_MA_Stream *sp;
   TA_RetCode retCode;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inReal || !outBegIdx || !outNBElement || !outReal ) return TA_BAD_PARAM;
   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 30;
   else if( (int)optInTimePeriod < 1 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInMAType == TA_INTEGER_DEFAULT || optInMAType == TA_MAType_DEFAULT )
      optInMAType = 0;
   else if( (int)optInMAType < TA_MATYPE_MIN || (int)optInMAType > TA_MATYPE_MAX )
      return TA_BAD_PARAM;

   sp = (struct TA_MA_Stream *)TA_Malloc( sizeof(*sp) );
   if( !sp ) return TA_ALLOC_ERR;
   memset( sp, 0, sizeof(*sp) );
   sp->optInTimePeriod = optInTimePeriod;
   sp->optInMAType = optInMAType;

   if( optInTimePeriod == 1 || optInMAType == TA_MAType_DISABLED )
   {
      int fillLb = TA_MA_Lookback( optInTimePeriod, optInMAType );
      if( startIdx > fillLb ) fillLb = startIdx;
      if( historyLen < fillLb + 1 ) { TA_Free( sp ); return TA_INSUFFICIENT_HISTORY; }
      {
         int fillIdx;
         *outBegIdx = fillLb;
         *outNBElement = historyLen - fillLb;
         for( fillIdx = 0; fillIdx < historyLen - fillLb; fillIdx++ )
         {
            outReal[fillIdx] = inReal[fillLb + fillIdx];
         }
      }
      sp->outRangeBegIdx = *outBegIdx;
      sp->outRangeCount = *outNBElement;
      sp->cur_outReal = inReal[historyLen - 1];
      *stream = sp;
      return TA_SUCCESS;
   }

   retCode = TA_BAD_PARAM;
   switch( optInMAType )
   {
   case TA_MAType_SMA:
      {
         TA_SMA_Stream *sub = NULL;
         retCode = TA_SMA_OpenAndFillInternal( &sub, inReal, startIdx, historyLen, optInTimePeriod, outBegIdx, outNBElement, outReal );
         sp->sub = sub;
      }
      break;
   case TA_MAType_EMA:
      {
         TA_EMA_Stream *sub = NULL;
         retCode = TA_EMA_OpenAndFillInternal( &sub, inReal, startIdx, historyLen, optInTimePeriod, outBegIdx, outNBElement, outReal );
         sp->sub = sub;
      }
      break;
   case TA_MAType_WMA:
      {
         TA_WMA_Stream *sub = NULL;
         retCode = TA_WMA_OpenAndFillInternal( &sub, inReal, startIdx, historyLen, optInTimePeriod, outBegIdx, outNBElement, outReal );
         sp->sub = sub;
      }
      break;
   case TA_MAType_DEMA:
      {
         TA_DEMA_Stream *sub = NULL;
         retCode = TA_DEMA_OpenAndFillInternal( &sub, inReal, startIdx, historyLen, optInTimePeriod, outBegIdx, outNBElement, outReal );
         sp->sub = sub;
      }
      break;
   case TA_MAType_TEMA:
      {
         TA_TEMA_Stream *sub = NULL;
         retCode = TA_TEMA_OpenAndFillInternal( &sub, inReal, startIdx, historyLen, optInTimePeriod, outBegIdx, outNBElement, outReal );
         sp->sub = sub;
      }
      break;
   case TA_MAType_TRIMA:
      {
         TA_TRIMA_Stream *sub = NULL;
         retCode = TA_TRIMA_OpenAndFillInternal( &sub, inReal, startIdx, historyLen, optInTimePeriod, outBegIdx, outNBElement, outReal );
         sp->sub = sub;
      }
      break;
   case TA_MAType_KAMA:
      {
         TA_KAMA_Stream *sub = NULL;
         retCode = TA_KAMA_OpenAndFillInternal( &sub, inReal, startIdx, historyLen, optInTimePeriod, outBegIdx, outNBElement, outReal );
         sp->sub = sub;
      }
      break;
   case TA_MAType_MAMA:
      {
         TA_MAMA_Stream *sub = NULL;
         retCode = TA_MAMA_OpenAndFillInternal( &sub, inReal, startIdx, historyLen, 0.5, 0.05, outBegIdx, outNBElement, outReal, NULL );
         sp->sub = sub;
      }
      break;
   case TA_MAType_T3:
      {
         TA_T3_Stream *sub = NULL;
         retCode = TA_T3_OpenAndFillInternal( &sub, inReal, startIdx, historyLen, optInTimePeriod, 0.7, outBegIdx, outNBElement, outReal );
         sp->sub = sub;
      }
      break;
   case TA_MAType_HMA:
      {
         TA_HMA_Stream *sub = NULL;
         retCode = TA_HMA_OpenAndFillInternal( &sub, inReal, startIdx, historyLen, optInTimePeriod, outBegIdx, outNBElement, outReal );
         sp->sub = sub;
      }
      break;
   case TA_MAType_ZLEMA:
      {
         TA_ZLEMA_Stream *sub = NULL;
         retCode = TA_ZLEMA_OpenAndFillInternal( &sub, inReal, startIdx, historyLen, optInTimePeriod, outBegIdx, outNBElement, outReal );
         sp->sub = sub;
      }
      break;
   case TA_MAType_RMA:
      {
         TA_RMA_Stream *sub = NULL;
         retCode = TA_RMA_OpenAndFillInternal( &sub, inReal, startIdx, historyLen, optInTimePeriod, outBegIdx, outNBElement, outReal );
         sp->sub = sub;
      }
      break;
   default:
      retCode = TA_BAD_PARAM;
      break;
   }

   if( retCode != TA_SUCCESS )
   {
      TA_Free( sp );
      return retCode;
   }
   sp->outRangeBegIdx = *outBegIdx;
   sp->outRangeCount = *outNBElement;
   sp->cur_outReal = outReal[*outNBElement - 1];
   *stream = sp;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_MA_Update( TA_MA_Stream *stream, double inReal, double *outReal )
{
   TA_RetCode retCode;

   if( !stream || !outReal ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inReal ) ) return TA_BAD_PARAM;
   if( stream->optInTimePeriod == 1 || stream->optInMAType == TA_MAType_DISABLED )
   {
      *outReal = inReal;
      stream->cur_outReal = *outReal;
      if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
      return TA_SUCCESS;
   }
   switch( stream->optInMAType )
   {
   case TA_MAType_SMA:
      retCode = TA_SMA_Update( (TA_SMA_Stream *)stream->sub, inReal, outReal );
      break;
   case TA_MAType_EMA:
      retCode = TA_EMA_Update( (TA_EMA_Stream *)stream->sub, inReal, outReal );
      break;
   case TA_MAType_WMA:
      retCode = TA_WMA_Update( (TA_WMA_Stream *)stream->sub, inReal, outReal );
      break;
   case TA_MAType_DEMA:
      retCode = TA_DEMA_Update( (TA_DEMA_Stream *)stream->sub, inReal, outReal );
      break;
   case TA_MAType_TEMA:
      retCode = TA_TEMA_Update( (TA_TEMA_Stream *)stream->sub, inReal, outReal );
      break;
   case TA_MAType_TRIMA:
      retCode = TA_TRIMA_Update( (TA_TRIMA_Stream *)stream->sub, inReal, outReal );
      break;
   case TA_MAType_KAMA:
      retCode = TA_KAMA_Update( (TA_KAMA_Stream *)stream->sub, inReal, outReal );
      break;
   case TA_MAType_MAMA:
      retCode = TA_MAMA_Update( (TA_MAMA_Stream *)stream->sub, inReal, outReal, NULL );
      break;
   case TA_MAType_T3:
      retCode = TA_T3_Update( (TA_T3_Stream *)stream->sub, inReal, outReal );
      break;
   case TA_MAType_HMA:
      retCode = TA_HMA_Update( (TA_HMA_Stream *)stream->sub, inReal, outReal );
      break;
   case TA_MAType_ZLEMA:
      retCode = TA_ZLEMA_Update( (TA_ZLEMA_Stream *)stream->sub, inReal, outReal );
      break;
   case TA_MAType_RMA:
      retCode = TA_RMA_Update( (TA_RMA_Stream *)stream->sub, inReal, outReal );
      break;
   default:
      /* Unreachable: Open rejects arms without a sub-stream. */
      return TA_INTERNAL_ERROR(343);
   }
   if( retCode != TA_SUCCESS ) return retCode;
   stream->cur_outReal = *outReal;
   if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_MA_Peek( const TA_MA_Stream *stream, double inReal, double *outReal )
{
   if( !stream || !outReal ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inReal ) ) return TA_BAD_PARAM;
   if( stream->optInTimePeriod == 1 || stream->optInMAType == TA_MAType_DISABLED )
   {
      *outReal = inReal;
      return TA_SUCCESS;
   }
   switch( stream->optInMAType )
   {
   case TA_MAType_SMA:
      return TA_SMA_Peek( (const TA_SMA_Stream *)stream->sub, inReal, outReal );
   case TA_MAType_EMA:
      return TA_EMA_Peek( (const TA_EMA_Stream *)stream->sub, inReal, outReal );
   case TA_MAType_WMA:
      return TA_WMA_Peek( (const TA_WMA_Stream *)stream->sub, inReal, outReal );
   case TA_MAType_DEMA:
      return TA_DEMA_Peek( (const TA_DEMA_Stream *)stream->sub, inReal, outReal );
   case TA_MAType_TEMA:
      return TA_TEMA_Peek( (const TA_TEMA_Stream *)stream->sub, inReal, outReal );
   case TA_MAType_TRIMA:
      return TA_TRIMA_Peek( (const TA_TRIMA_Stream *)stream->sub, inReal, outReal );
   case TA_MAType_KAMA:
      return TA_KAMA_Peek( (const TA_KAMA_Stream *)stream->sub, inReal, outReal );
   case TA_MAType_MAMA:
      return TA_MAMA_Peek( (const TA_MAMA_Stream *)stream->sub, inReal, outReal, NULL );
   case TA_MAType_T3:
      return TA_T3_Peek( (const TA_T3_Stream *)stream->sub, inReal, outReal );
   case TA_MAType_HMA:
      return TA_HMA_Peek( (const TA_HMA_Stream *)stream->sub, inReal, outReal );
   case TA_MAType_ZLEMA:
      return TA_ZLEMA_Peek( (const TA_ZLEMA_Stream *)stream->sub, inReal, outReal );
   case TA_MAType_RMA:
      return TA_RMA_Peek( (const TA_RMA_Stream *)stream->sub, inReal, outReal );
   default:
      /* Unreachable: Open rejects arms without a sub-stream. */
      return TA_INTERNAL_ERROR(344);
   }
}

TA_LIB_API TA_RetCode TA_MA_Close( TA_MA_Stream *stream )
{
   if( !stream ) return TA_SUCCESS;
   switch( stream->optInMAType )
   {
   case TA_MAType_SMA:
      TA_SMA_Close( (TA_SMA_Stream *)stream->sub );
      break;
   case TA_MAType_EMA:
      TA_EMA_Close( (TA_EMA_Stream *)stream->sub );
      break;
   case TA_MAType_WMA:
      TA_WMA_Close( (TA_WMA_Stream *)stream->sub );
      break;
   case TA_MAType_DEMA:
      TA_DEMA_Close( (TA_DEMA_Stream *)stream->sub );
      break;
   case TA_MAType_TEMA:
      TA_TEMA_Close( (TA_TEMA_Stream *)stream->sub );
      break;
   case TA_MAType_TRIMA:
      TA_TRIMA_Close( (TA_TRIMA_Stream *)stream->sub );
      break;
   case TA_MAType_KAMA:
      TA_KAMA_Close( (TA_KAMA_Stream *)stream->sub );
      break;
   case TA_MAType_MAMA:
      TA_MAMA_Close( (TA_MAMA_Stream *)stream->sub );
      break;
   case TA_MAType_T3:
      TA_T3_Close( (TA_T3_Stream *)stream->sub );
      break;
   case TA_MAType_HMA:
      TA_HMA_Close( (TA_HMA_Stream *)stream->sub );
      break;
   case TA_MAType_ZLEMA:
      TA_ZLEMA_Close( (TA_ZLEMA_Stream *)stream->sub );
      break;
   case TA_MAType_RMA:
      TA_RMA_Close( (TA_RMA_Stream *)stream->sub );
      break;
   default:
      break; /* identity-only or rejected arm: no sub-stream */
   }
   TA_Free( stream );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_MA_Value( const TA_MA_Stream *stream, double *outReal )
{
   if( !stream || !outReal ) return TA_BAD_PARAM;
   *outReal = stream->cur_outReal;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_MA_OutRange( const TA_MA_Stream *stream, int *outBegIdx, int *outNBElement )
{
   if( !stream || !outBegIdx || !outNBElement ) return TA_BAD_PARAM;
   *outBegIdx = stream->outRangeBegIdx;
   *outNBElement = stream->outRangeCount;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_MA_Advance( TA_MA_Stream *stream )
{
   if( !stream ) return TA_BAD_PARAM;
   if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_MA_Clone( const TA_MA_Stream *stream, TA_MA_Stream **clone )
{
   struct TA_MA_Stream *sp;

   if( !clone ) return TA_BAD_PARAM;
   *clone = NULL;
   if( !stream ) return TA_BAD_PARAM;
   sp = (struct TA_MA_Stream *)TA_Malloc( sizeof(*sp) );
   if( !sp ) return TA_ALLOC_ERR;
   *sp = *stream;
   sp->sub = NULL;
   if( stream->sub )
   {
      TA_RetCode subRc;
      switch( stream->optInMAType )
      {
      case TA_MAType_SMA:
         {
            TA_SMA_Stream *subClone = NULL;
            subRc = TA_SMA_Clone( (const TA_SMA_Stream *)stream->sub, &subClone );
            sp->sub = subClone;
         }
         break;
      case TA_MAType_EMA:
         {
            TA_EMA_Stream *subClone = NULL;
            subRc = TA_EMA_Clone( (const TA_EMA_Stream *)stream->sub, &subClone );
            sp->sub = subClone;
         }
         break;
      case TA_MAType_WMA:
         {
            TA_WMA_Stream *subClone = NULL;
            subRc = TA_WMA_Clone( (const TA_WMA_Stream *)stream->sub, &subClone );
            sp->sub = subClone;
         }
         break;
      case TA_MAType_DEMA:
         {
            TA_DEMA_Stream *subClone = NULL;
            subRc = TA_DEMA_Clone( (const TA_DEMA_Stream *)stream->sub, &subClone );
            sp->sub = subClone;
         }
         break;
      case TA_MAType_TEMA:
         {
            TA_TEMA_Stream *subClone = NULL;
            subRc = TA_TEMA_Clone( (const TA_TEMA_Stream *)stream->sub, &subClone );
            sp->sub = subClone;
         }
         break;
      case TA_MAType_TRIMA:
         {
            TA_TRIMA_Stream *subClone = NULL;
            subRc = TA_TRIMA_Clone( (const TA_TRIMA_Stream *)stream->sub, &subClone );
            sp->sub = subClone;
         }
         break;
      case TA_MAType_KAMA:
         {
            TA_KAMA_Stream *subClone = NULL;
            subRc = TA_KAMA_Clone( (const TA_KAMA_Stream *)stream->sub, &subClone );
            sp->sub = subClone;
         }
         break;
      case TA_MAType_MAMA:
         {
            TA_MAMA_Stream *subClone = NULL;
            subRc = TA_MAMA_Clone( (const TA_MAMA_Stream *)stream->sub, &subClone );
            sp->sub = subClone;
         }
         break;
      case TA_MAType_T3:
         {
            TA_T3_Stream *subClone = NULL;
            subRc = TA_T3_Clone( (const TA_T3_Stream *)stream->sub, &subClone );
            sp->sub = subClone;
         }
         break;
      case TA_MAType_HMA:
         {
            TA_HMA_Stream *subClone = NULL;
            subRc = TA_HMA_Clone( (const TA_HMA_Stream *)stream->sub, &subClone );
            sp->sub = subClone;
         }
         break;
      case TA_MAType_ZLEMA:
         {
            TA_ZLEMA_Stream *subClone = NULL;
            subRc = TA_ZLEMA_Clone( (const TA_ZLEMA_Stream *)stream->sub, &subClone );
            sp->sub = subClone;
         }
         break;
      case TA_MAType_RMA:
         {
            TA_RMA_Stream *subClone = NULL;
            subRc = TA_RMA_Clone( (const TA_RMA_Stream *)stream->sub, &subClone );
            sp->sub = subClone;
         }
         break;
      default:
         subRc = TA_SUCCESS; /* identity arm: no sub-stream */
         break;
      }
      if( subRc != TA_SUCCESS ) { TA_MA_Close( sp ); return subRc; }
   }
   *clone = sp;
   return TA_SUCCESS;
}

