/* TA-LIB Copyright (c) 1999-2026, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_stream_private.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  KL       Kevin Lin
 *
 * Change history:
 *
 *  MMDDYY BY     Description
 *  -------------------------------------------------------------------
 *  091526 KL     First version (proposal-drafts issue #73).
 */

TA_LIB_API int TA_MEDIAN_Lookback( int optInTimePeriod )
{
   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 30;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return -1;
   return optInTimePeriod - 1;
}

TA_LIB_API TA_RetCode TA_MEDIAN( int    startIdx,
                                 int    endIdx,
                                 const double inReal[],
                                 int optInTimePeriod,
                                 int          *outBegIdx,
                                 int          *outNBElement,
                                 double        outReal[] )
{
   double newValue;
   double oldValue;
   double result;
   double lower;
   double upper;
   int lookbackTotal;
   int outIdx;
   int i;
   int j;
   int pos;
   int nbSorted;
   int lowerIdx;
   int upperIdx;
   double local_ring[30];
   double *ring = &local_ring[0];
   int ring_Idx;
   int maxIdx_ring;
   double local_sorted[30];
   double *sorted = &local_sorted[0];

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 30;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( !inReal )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   /* The window is carried twice: "ring" by age, "sorted" by value. Both are
    * hand-written here as they are in percentile.c, which is the precedent for
    * this shape -- a generator-derived ring does not carry the by-value copy.
    */
   lookbackTotal = optInTimePeriod - 1;
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   if( optInTimePeriod < 1 ) return TA_INTERNAL_ERROR(429);
   if( (int)optInTimePeriod > (int)(sizeof(local_ring)/sizeof(double)) )
   {
      ring = TA_Malloc( sizeof(double)*optInTimePeriod );
      if( !ring )
      {
         return TA_ALLOC_ERR;
      }
   }
   else
   {
      ring = &local_ring[0];
   }
   maxIdx_ring = (optInTimePeriod-1);
   ring_Idx = 0;
   if( optInTimePeriod < 1 ) return TA_INTERNAL_ERROR(430);
   if( (int)optInTimePeriod > (int)(sizeof(local_sorted)/sizeof(double)) )
   {
      sorted = TA_Malloc( sizeof(double)*optInTimePeriod );
      if( !sorted )
      {
         if( ring != &local_ring[0] ) TA_Free( ring );
         return TA_ALLOC_ERR;
      }
   }
   else
   {
      sorted = &local_sorted[0];
   }
   /* The two central ordinals, zero-based over the full window. At odd
    * optInTimePeriod they are the same slot and the average below is the value
    * itself; at even optInTimePeriod they straddle the centre and the mean of
    * the two is the median. Computed once rather than per bar.
    */
   lowerIdx = (optInTimePeriod - 1) / 2;
   upperIdx = optInTimePeriod / 2;
   nbSorted = 0;
   i = startIdx - lookbackTotal;
   while( i < startIdx )
   {
      newValue = inReal[i];
      j = nbSorted;
      while( j > 0 && sorted[j - 1] > newValue )
      {
         sorted[j] = sorted[j - 1];
         j -= 1;
      }
      sorted[j] = newValue;
      nbSorted += 1;
      ring[ring_Idx] = newValue;
      i += 1;
      ring_Idx++;
      if( ring_Idx > maxIdx_ring ) ring_Idx = 0;
   }
   /* Both scratch buffers hold copies and inReal is never read below i, so
    * inReal and outReal may be the same buffer.
    *
    * Every buffer store sits BELOW the output store on purpose (percentile.c):
    * deriving the whole answer read-only above it is what lets the streaming
    * peek frame drop the state update rather than shadow a shift loop.
    */
   outIdx = 0;
   do
   {
      newValue = inReal[i];
      /* `sorted` holds the window's other optInTimePeriod-1 values and `pos` is
       * where the incoming one belongs, so the full window is
       * sorted[0..pos-1], newValue, sorted[pos..]. The k-th of it is read
       * without materialising it.
       */
      pos = 0;
      while( pos < lookbackTotal && sorted[pos] <= newValue )
      {
         pos += 1;
      }
      if( lowerIdx < pos )
      {
         lower = sorted[lowerIdx];
      } else if( lowerIdx == pos )
      {
         lower = newValue;
      } else 
      {
         lower = sorted[lowerIdx - 1];
      }
      if( upperIdx < pos )
      {
         upper = sorted[upperIdx];
      } else if( upperIdx == pos )
      {
         upper = newValue;
      } else 
      {
         upper = sorted[upperIdx - 1];
      }
      /* At odd optInTimePeriod the two ordinals are the same slot, and the
       * branch returns that read untouched. Writing it as (v + v) / 2.0
       * instead would be exact for every value this library is ever handed --
       * doubling moves the exponent with the mantissa untouched and halving
       * moves it back -- but it overflows to +/-inf above DBL_MAX/2, and this
       * function does not declare nan_inf_output. The branch costs nothing:
       * the condition is loop-invariant.
       *
       * At even optInTimePeriod the mean of the two central values is the
       * universal convention (NumPy, R, scipy, Excel). Dividing by 2.0 and
       * multiplying by 0.5 give the same double, so that spelling is not a
       * variant; the sum itself can still overflow on inputs near DBL_MAX,
       * which is exactly what NumPy does with them too.
       */
      if( lowerIdx == upperIdx )
      {
         result = lower;
      } else 
      {
         result = (lower + upper) / 2.0;
      }
      outReal[outIdx] = result;
      outIdx += 1;
      /* Shifting only the strictly greater entries leaves equal values in
       * insertion order, which is age order -- that is what lets the delete
       * below evict the oldest of a run by value alone, with no slot array.
       *
       * The order within a run of equal values is NOT observable at the output,
       * and deliberately so: MEASURED, flipping this scan's `<=` to `<` (which
       * inserts at the front of a run instead of the back) leaves every value
       * bit-identical over 14820 windows on both a 7-distinct-value series and
       * a random walk. Equal members are interchangeable, which is precisely
       * why the removal can identify one by value and needs no identity.
       */
      j = lookbackTotal;
      while( j > pos )
      {
         sorted[j] = sorted[j - 1];
         j -= 1;
      }
      sorted[pos] = newValue;
      ring[ring_Idx] = newValue;
      ring_Idx++;
      if( ring_Idx > maxIdx_ring ) ring_Idx = 0;
      oldValue = ring[ring_Idx];
      j = 0;
      while( j < lookbackTotal && sorted[j] < oldValue )
      {
         j += 1;
      }
      while( j < lookbackTotal )
      {
         sorted[j] = sorted[j + 1];
         j += 1;
      }
      i += 1;
   } while( i <= endIdx );
   *outNBElement= outIdx;
   *outBegIdx= startIdx;
   if( ring != &local_ring[0] ) { TA_Free( ring ); ring = &local_ring[0]; }
   if( sorted != &local_sorted[0] ) { TA_Free( sorted ); sorted = &local_sorted[0]; }
   return TA_SUCCESS;
}

TA_RetCode TA_S_MEDIAN( int    startIdx,
                        int    endIdx,
                        const float inReal[],
                        int optInTimePeriod,
                        int          *outBegIdx,
                        int          *outNBElement,
                        double        outReal[] )
{
   double newValue;
   double oldValue;
   double result;
   double lower;
   double upper;
   int lookbackTotal;
   int outIdx;
   int i;
   int j;
   int pos;
   int nbSorted;
   int lowerIdx;
   int upperIdx;
   double local_ring[30];
   double *ring = &local_ring[0];
   int ring_Idx;
   int maxIdx_ring;
   double local_sorted[30];
   double *sorted = &local_sorted[0];

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 30;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( !inReal )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   lookbackTotal = optInTimePeriod - 1;
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   if( optInTimePeriod < 1 ) return TA_INTERNAL_ERROR(429);
   if( (int)optInTimePeriod > (int)(sizeof(local_ring)/sizeof(double)) )
   {
      ring = TA_Malloc( sizeof(double)*optInTimePeriod );
      if( !ring )
      {
         return TA_ALLOC_ERR;
      }
   }
   else
   {
      ring = &local_ring[0];
   }
   maxIdx_ring = (optInTimePeriod-1);
   ring_Idx = 0;
   if( optInTimePeriod < 1 ) return TA_INTERNAL_ERROR(430);
   if( (int)optInTimePeriod > (int)(sizeof(local_sorted)/sizeof(double)) )
   {
      sorted = TA_Malloc( sizeof(double)*optInTimePeriod );
      if( !sorted )
      {
         if( ring != &local_ring[0] ) TA_Free( ring );
         return TA_ALLOC_ERR;
      }
   }
   else
   {
      sorted = &local_sorted[0];
   }
   lowerIdx = (optInTimePeriod - 1) / 2;
   upperIdx = optInTimePeriod / 2;
   nbSorted = 0;
   i = startIdx - lookbackTotal;
   while( i < startIdx )
   {
      newValue = (double)inReal[i];
      j = nbSorted;
      while( j > 0 && sorted[j - 1] > newValue )
      {
         sorted[j] = sorted[j - 1];
         j -= 1;
      }
      sorted[j] = newValue;
      nbSorted += 1;
      ring[ring_Idx] = newValue;
      i += 1;
      ring_Idx++;
      if( ring_Idx > maxIdx_ring ) ring_Idx = 0;
   }
   outIdx = 0;
   do
   {
      newValue = (double)inReal[i];
      pos = 0;
      while( pos < lookbackTotal && sorted[pos] <= newValue )
      {
         pos += 1;
      }
      if( lowerIdx < pos )
      {
         lower = sorted[lowerIdx];
      } else if( lowerIdx == pos )
      {
         lower = newValue;
      } else 
      {
         lower = sorted[lowerIdx - 1];
      }
      if( upperIdx < pos )
      {
         upper = sorted[upperIdx];
      } else if( upperIdx == pos )
      {
         upper = newValue;
      } else 
      {
         upper = sorted[upperIdx - 1];
      }
      if( lowerIdx == upperIdx )
      {
         result = lower;
      } else 
      {
         result = (lower + upper) / 2.0;
      }
      outReal[outIdx] = result;
      outIdx += 1;
      j = lookbackTotal;
      while( j > pos )
      {
         sorted[j] = sorted[j - 1];
         j -= 1;
      }
      sorted[pos] = newValue;
      ring[ring_Idx] = newValue;
      ring_Idx++;
      if( ring_Idx > maxIdx_ring ) ring_Idx = 0;
      oldValue = ring[ring_Idx];
      j = 0;
      while( j < lookbackTotal && sorted[j] < oldValue )
      {
         j += 1;
      }
      while( j < lookbackTotal )
      {
         sorted[j] = sorted[j + 1];
         j += 1;
      }
      i += 1;
   } while( i <= endIdx );
   *outNBElement= outIdx;
   *outBegIdx= startIdx;
   if( ring != &local_ring[0] ) { TA_Free( ring ); ring = &local_ring[0]; }
   if( sorted != &local_sorted[0] ) { TA_Free( sorted ); sorted = &local_sorted[0]; }
   return TA_SUCCESS;
}

/**** Streaming API *****/

struct TA_MEDIAN_Stream {
   /* The bars this handle has an output for (see TA_MEDIAN_OutRange). */
   int outRangeBegIdx;
   int outRangeCount;
   /* The value(s) at the last bar the stream counted (see TA_MEDIAN_Value). */
   double cur_outReal;
   int optInTimePeriod;
   int lookbackTotal;
   int lowerIdx;
   int upperIdx;
   int ring_Idx;
   int maxIdx_ring;
   int sorted_Idx;
   int maxIdx_sorted;
   int cbSize_ring;
   double *cb_ring;
   int cbSize_sorted;
   double *cb_sorted;
};

/* Private function, not in public API. */
static void TA_MEDIAN_ReleaseImpl( struct TA_MEDIAN_Stream *sp )
{
   if( !sp ) return;
   if( sp->cb_ring ) TA_Free( sp->cb_ring );
   if( sp->cb_sorted ) TA_Free( sp->cb_sorted );
   TA_Free( sp );
}

/* Private function, not in public API. */
static void TA_MEDIAN_StepImpl( struct TA_MEDIAN_Stream *sp, double inReal, double *outReal )
{
   double newValue;
   double oldValue;
   double result;
   double lower;
   double upper;
   int j;
   int pos;

   newValue = inReal;
   /* `sorted` holds the window's other optInTimePeriod-1 values and `pos` is
    * where the incoming one belongs, so the full window is
    * sorted[0..pos-1], newValue, sorted[pos..]. The k-th of it is read
    * without materialising it.
    */
   pos = 0;
   while( pos < sp->lookbackTotal && sp->cb_sorted[pos] <= newValue )
   {
      pos += 1;
   }
   if( sp->lowerIdx < pos )
   {
      lower = sp->cb_sorted[sp->lowerIdx];
   } else if( sp->lowerIdx == pos )
   {
      lower = newValue;
   } else 
   {
      lower = sp->cb_sorted[sp->lowerIdx - 1];
   }
   if( sp->upperIdx < pos )
   {
      upper = sp->cb_sorted[sp->upperIdx];
   } else if( sp->upperIdx == pos )
   {
      upper = newValue;
   } else 
   {
      upper = sp->cb_sorted[sp->upperIdx - 1];
   }
   /* At odd optInTimePeriod the two ordinals are the same slot, and the
    * branch returns that read untouched. Writing it as (v + v) / 2.0
    * instead would be exact for every value this library is ever handed --
    * doubling moves the exponent with the mantissa untouched and halving
    * moves it back -- but it overflows to +/-inf above DBL_MAX/2, and this
    * function does not declare nan_inf_output. The branch costs nothing:
    * the condition is loop-invariant.
    *
    * At even optInTimePeriod the mean of the two central values is the
    * universal convention (NumPy, R, scipy, Excel). Dividing by 2.0 and
    * multiplying by 0.5 give the same double, so that spelling is not a
    * variant; the sum itself can still overflow on inputs near DBL_MAX,
    * which is exactly what NumPy does with them too.
    */
   if( sp->lowerIdx == sp->upperIdx )
   {
      result = lower;
   } else 
   {
      result = (lower + upper) / 2.0;
   }
   *outReal= result;
   /* Shifting only the strictly greater entries leaves equal values in
    * insertion order, which is age order -- that is what lets the delete
    * below evict the oldest of a run by value alone, with no slot array.
    *
    * The order within a run of equal values is NOT observable at the output,
    * and deliberately so: MEASURED, flipping this scan's `<=` to `<` (which
    * inserts at the front of a run instead of the back) leaves every value
    * bit-identical over 14820 windows on both a 7-distinct-value series and
    * a random walk. Equal members are interchangeable, which is precisely
    * why the removal can identify one by value and needs no identity.
    */
   j = sp->lookbackTotal;
   while( j > pos )
   {
      sp->cb_sorted[j] = sp->cb_sorted[j - 1];
      j -= 1;
   }
   sp->cb_sorted[pos] = newValue;
   sp->cb_ring[sp->ring_Idx] = newValue;
   sp->ring_Idx = sp->ring_Idx + 1;
   if( sp->ring_Idx > sp->maxIdx_ring )
   {
      sp->ring_Idx = 0;
   }
   oldValue = sp->cb_ring[sp->ring_Idx];
   j = 0;
   while( j < sp->lookbackTotal && sp->cb_sorted[j] < oldValue )
   {
      j += 1;
   }
   while( j < sp->lookbackTotal )
   {
      sp->cb_sorted[j] = sp->cb_sorted[j + 1];
      j += 1;
   }
   sp->cur_outReal = *outReal;
}

static TA_RetCode TA_MEDIAN_OpenImpl( struct TA_MEDIAN_Stream **stream, const double inReal[], int startIdx, int historyLen, int optInTimePeriod, int *outBegIdx, int *outNBElement, double outReal[], int outStride )
{
   struct TA_MEDIAN_Stream *sp;
   double local_ring[30];
   double *ring;
   int ring_Idx;
   int maxIdx_ring;
   double local_sorted[30];
   double *sorted;
   int sorted_Idx;
   int maxIdx_sorted;
   int endIdx;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inReal || !outReal ) return TA_BAD_PARAM;
   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 30;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( startIdx > historyLen - 1 )
   {
      *outBegIdx = 0;
      *outNBElement = 0;
      return TA_INSUFFICIENT_HISTORY;
   }

   endIdx = historyLen - 1;

   {
      double newValue;
      double oldValue;
      double result;
      double lower;
      double upper;
      int lookbackTotal = 0;
      int outIdx;
      int i;
      int j;
      int pos;
      int nbSorted;
      int lowerIdx = 0;
      int upperIdx = 0;
      /* The window is carried twice: "ring" by age, "sorted" by value. Both are
       * hand-written here as they are in percentile.c, which is the precedent for
       * this shape -- a generator-derived ring does not carry the by-value copy.
       */
      lookbackTotal = optInTimePeriod - 1;
      if( startIdx < lookbackTotal )
      {
         startIdx = lookbackTotal;
      }
      if( startIdx > endIdx )
      {
         *outBegIdx= 0;
         *outNBElement= 0;
         return TA_INSUFFICIENT_HISTORY;
      }
      if( optInTimePeriod < 1 ) return TA_INTERNAL_ERROR(429);
      if( (int)optInTimePeriod > (int)(sizeof(local_ring)/sizeof(double)) )
      {
         ring = TA_Malloc( sizeof(double)*optInTimePeriod );
         if( !ring )
         {
            return TA_ALLOC_ERR;
         }
      }
      else
      {
         ring = &local_ring[0];
      }
      maxIdx_ring = (optInTimePeriod-1);
      ring_Idx = 0;
      if( optInTimePeriod < 1 ) return TA_INTERNAL_ERROR(430);
      if( (int)optInTimePeriod > (int)(sizeof(local_sorted)/sizeof(double)) )
      {
         sorted = TA_Malloc( sizeof(double)*optInTimePeriod );
         if( !sorted )
         {
            if( ring != &local_ring[0] ) TA_Free( ring );
            return TA_ALLOC_ERR;
         }
      }
      else
      {
         sorted = &local_sorted[0];
      }
      maxIdx_sorted = (optInTimePeriod-1);
      sorted_Idx = 0;
      /* The two central ordinals, zero-based over the full window. At odd
       * optInTimePeriod they are the same slot and the average below is the value
       * itself; at even optInTimePeriod they straddle the centre and the mean of
       * the two is the median. Computed once rather than per bar.
       */
      lowerIdx = (optInTimePeriod - 1) / 2;
      upperIdx = optInTimePeriod / 2;
      nbSorted = 0;
      i = startIdx - lookbackTotal;
      while( i < startIdx )
      {
         newValue = inReal[i];
         j = nbSorted;
         while( j > 0 && sorted[j - 1] > newValue )
         {
            sorted[j] = sorted[j - 1];
            j -= 1;
         }
         sorted[j] = newValue;
         nbSorted += 1;
         ring[ring_Idx] = newValue;
         i += 1;
         ring_Idx++;
         if( ring_Idx > maxIdx_ring ) ring_Idx = 0;
      }
      /* Both scratch buffers hold copies and inReal is never read below i, so
       * inReal and outReal may be the same buffer.
       *
       * Every buffer store sits BELOW the output store on purpose (percentile.c):
       * deriving the whole answer read-only above it is what lets the streaming
       * peek frame drop the state update rather than shadow a shift loop.
       */
      outIdx = 0;
      do
      {
         newValue = inReal[i];
         /* `sorted` holds the window's other optInTimePeriod-1 values and `pos` is
          * where the incoming one belongs, so the full window is
          * sorted[0..pos-1], newValue, sorted[pos..]. The k-th of it is read
          * without materialising it.
          */
         pos = 0;
         while( pos < lookbackTotal && sorted[pos] <= newValue )
         {
            pos += 1;
         }
         if( lowerIdx < pos )
         {
            lower = sorted[lowerIdx];
         } else if( lowerIdx == pos )
         {
            lower = newValue;
         } else 
         {
            lower = sorted[lowerIdx - 1];
         }
         if( upperIdx < pos )
         {
            upper = sorted[upperIdx];
         } else if( upperIdx == pos )
         {
            upper = newValue;
         } else 
         {
            upper = sorted[upperIdx - 1];
         }
         /* At odd optInTimePeriod the two ordinals are the same slot, and the
          * branch returns that read untouched. Writing it as (v + v) / 2.0
          * instead would be exact for every value this library is ever handed --
          * doubling moves the exponent with the mantissa untouched and halving
          * moves it back -- but it overflows to +/-inf above DBL_MAX/2, and this
          * function does not declare nan_inf_output. The branch costs nothing:
          * the condition is loop-invariant.
          *
          * At even optInTimePeriod the mean of the two central values is the
          * universal convention (NumPy, R, scipy, Excel). Dividing by 2.0 and
          * multiplying by 0.5 give the same double, so that spelling is not a
          * variant; the sum itself can still overflow on inputs near DBL_MAX,
          * which is exactly what NumPy does with them too.
          */
         if( lowerIdx == upperIdx )
         {
            result = lower;
         } else 
         {
            result = (lower + upper) / 2.0;
         }
         outReal[outIdx * outStride] = result;
         outIdx += 1;
         /* Shifting only the strictly greater entries leaves equal values in
          * insertion order, which is age order -- that is what lets the delete
          * below evict the oldest of a run by value alone, with no slot array.
          *
          * The order within a run of equal values is NOT observable at the output,
          * and deliberately so: MEASURED, flipping this scan's `<=` to `<` (which
          * inserts at the front of a run instead of the back) leaves every value
          * bit-identical over 14820 windows on both a 7-distinct-value series and
          * a random walk. Equal members are interchangeable, which is precisely
          * why the removal can identify one by value and needs no identity.
          */
         j = lookbackTotal;
         while( j > pos )
         {
            sorted[j] = sorted[j - 1];
            j -= 1;
         }
         sorted[pos] = newValue;
         ring[ring_Idx] = newValue;
         ring_Idx++;
         if( ring_Idx > maxIdx_ring ) ring_Idx = 0;
         oldValue = ring[ring_Idx];
         j = 0;
         while( j < lookbackTotal && sorted[j] < oldValue )
         {
            j += 1;
         }
         while( j < lookbackTotal )
         {
            sorted[j] = sorted[j + 1];
            j += 1;
         }
         i += 1;
      } while( i <= endIdx );
      *outNBElement= outIdx;
      *outBegIdx= startIdx;

      /* Capture the live batch state into the handle. */
      sp = (struct TA_MEDIAN_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) { if( ring != &local_ring[0] ) { TA_Free( ring ); } if( sorted != &local_sorted[0] ) { TA_Free( sorted ); } return TA_ALLOC_ERR; }
      memset( sp, 0, sizeof(*sp) );
      sp->optInTimePeriod = optInTimePeriod;
      sp->lookbackTotal = lookbackTotal;
      sp->lowerIdx = lowerIdx;
      sp->upperIdx = upperIdx;
      sp->ring_Idx = ring_Idx;
      sp->maxIdx_ring = maxIdx_ring;
      sp->sorted_Idx = sorted_Idx;
      sp->maxIdx_sorted = maxIdx_sorted;
      sp->cbSize_ring = maxIdx_ring + 1;
      if( sp->cbSize_ring < 1 || sp->cbSize_ring > historyLen + 1 ) { if( ring != &local_ring[0] ) { TA_Free( ring ); } if( sorted != &local_sorted[0] ) { TA_Free( sorted ); } TA_MEDIAN_ReleaseImpl( sp ); return TA_INTERNAL_ERROR(431); }
      sp->cb_ring = (double *)TA_Malloc( sizeof(double) * (size_t)sp->cbSize_ring );
      if( !sp->cb_ring ) { if( ring != &local_ring[0] ) { TA_Free( ring ); } if( sorted != &local_sorted[0] ) { TA_Free( sorted ); } TA_MEDIAN_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
      memcpy( sp->cb_ring, ring, sizeof(double) * (size_t)sp->cbSize_ring );
      sp->cbSize_sorted = maxIdx_sorted + 1;
      if( sp->cbSize_sorted < 1 || sp->cbSize_sorted > historyLen + 1 ) { if( ring != &local_ring[0] ) { TA_Free( ring ); } if( sorted != &local_sorted[0] ) { TA_Free( sorted ); } TA_MEDIAN_ReleaseImpl( sp ); return TA_INTERNAL_ERROR(432); }
      sp->cb_sorted = (double *)TA_Malloc( sizeof(double) * (size_t)sp->cbSize_sorted );
      if( !sp->cb_sorted ) { if( ring != &local_ring[0] ) { TA_Free( ring ); } if( sorted != &local_sorted[0] ) { TA_Free( sorted ); } TA_MEDIAN_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
      memcpy( sp->cb_sorted, sorted, sizeof(double) * (size_t)sp->cbSize_sorted );
      if( ring != &local_ring[0] ) { TA_Free( ring ); } if( sorted != &local_sorted[0] ) { TA_Free( sorted ); } 
      sp->outRangeBegIdx = *outBegIdx;
      sp->outRangeCount = *outNBElement;
      sp->cur_outReal = outReal[(*outNBElement - 1) * outStride];
      *stream = sp;
      return TA_SUCCESS;
   }
}

/* Private function, not in public API. */
TA_RetCode TA_MEDIAN_OpenInternal( struct TA_MEDIAN_Stream **stream, const double inReal[], int startIdx, int historyLen, int optInTimePeriod, double *outReal )
{
   TA_RetCode retCode;
   int dummyBegIdx = 0;
   int dummyNBElement = 0;
   double sink_outReal = 0.0;
   retCode = TA_MEDIAN_OpenImpl( stream, inReal, startIdx, historyLen, optInTimePeriod, &dummyBegIdx, &dummyNBElement, &sink_outReal, 0 );
   if( retCode == TA_SUCCESS )
   {
      *outReal = sink_outReal;
   }
   return retCode;
}

TA_LIB_API TA_RetCode TA_MEDIAN_Open( TA_MEDIAN_Stream **stream, const double inReal[], int historyLen, int optInTimePeriod, double *outReal )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inReal || !outReal ) return TA_BAD_PARAM;
   return TA_MEDIAN_OpenInternal( stream, inReal, 0, historyLen, optInTimePeriod, outReal );
}

TA_LIB_API TA_RetCode TA_MEDIAN_OpenAndFill( TA_MEDIAN_Stream **stream, const double inReal[], int historyLen, int optInTimePeriod, int *outBegIdx, int *outNBElement, double outReal[] )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inReal || !outBegIdx || !outNBElement || !outReal ) return TA_BAD_PARAM;
   if( (const void *)outReal == (const void *)inReal ) return TA_BAD_PARAM;
   return TA_MEDIAN_OpenAndFillInternal( stream, inReal, 0, historyLen, optInTimePeriod, outBegIdx, outNBElement, outReal );
}

/* Private function, not in public API. */
TA_RetCode TA_MEDIAN_OpenAndFillInternal( struct TA_MEDIAN_Stream **stream, const double inReal[], int startIdx, int historyLen, int optInTimePeriod, int *outBegIdx, int *outNBElement, double outReal[] )
{
   return TA_MEDIAN_OpenImpl( stream, inReal, startIdx, historyLen, optInTimePeriod, outBegIdx, outNBElement, outReal, 1 );
}

TA_LIB_API TA_RetCode TA_MEDIAN_Update( TA_MEDIAN_Stream *stream, double inReal, double *outReal )
{
   if( !stream ) return TA_BAD_PARAM;
   if( stream->outRangeBegIdx + stream->outRangeCount > TA_MAX_INDEX )
      return TA_OUT_OF_RANGE_END_INDEX;
   if( !outReal ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inReal ) ) return TA_BAD_PARAM;
   TA_MEDIAN_StepImpl( stream, inReal, outReal );
   stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_MEDIAN_Peek( const TA_MEDIAN_Stream *stream, double inReal, double *outReal )
{
   const struct TA_MEDIAN_Stream *sp = stream;
   double newValue;
   double result;
   double lower;
   double upper;
   int pos;
   double *cb_sorted;

   if( !stream || !outReal ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inReal ) ) return TA_BAD_PARAM;
   cb_sorted = sp->cb_sorted;
   newValue = inReal;
   /* `sorted` holds the window's other optInTimePeriod-1 values and `pos` is
    * where the incoming one belongs, so the full window is
    * sorted[0..pos-1], newValue, sorted[pos..]. The k-th of it is read
    * without materialising it.
    */
   pos = 0;
   while( pos < sp->lookbackTotal && cb_sorted[pos] <= newValue )
   {
      pos += 1;
   }
   if( sp->lowerIdx < pos )
   {
      lower = cb_sorted[sp->lowerIdx];
   } else if( sp->lowerIdx == pos )
   {
      lower = newValue;
   } else 
   {
      lower = cb_sorted[sp->lowerIdx - 1];
   }
   if( sp->upperIdx < pos )
   {
      upper = cb_sorted[sp->upperIdx];
   } else if( sp->upperIdx == pos )
   {
      upper = newValue;
   } else 
   {
      upper = cb_sorted[sp->upperIdx - 1];
   }
   /* At odd optInTimePeriod the two ordinals are the same slot, and the
    * branch returns that read untouched. Writing it as (v + v) / 2.0
    * instead would be exact for every value this library is ever handed --
    * doubling moves the exponent with the mantissa untouched and halving
    * moves it back -- but it overflows to +/-inf above DBL_MAX/2, and this
    * function does not declare nan_inf_output. The branch costs nothing:
    * the condition is loop-invariant.
    *
    * At even optInTimePeriod the mean of the two central values is the
    * universal convention (NumPy, R, scipy, Excel). Dividing by 2.0 and
    * multiplying by 0.5 give the same double, so that spelling is not a
    * variant; the sum itself can still overflow on inputs near DBL_MAX,
    * which is exactly what NumPy does with them too.
    */
   if( sp->lowerIdx == sp->upperIdx )
   {
      result = lower;
   } else 
   {
      result = (lower + upper) / 2.0;
   }
   *outReal= result;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_MEDIAN_Close( TA_MEDIAN_Stream *stream )
{
   TA_MEDIAN_ReleaseImpl( stream );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_MEDIAN_Value( const TA_MEDIAN_Stream *stream, double *outReal )
{
   if( !stream || !outReal ) return TA_BAD_PARAM;
   *outReal = stream->cur_outReal;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_MEDIAN_OutRange( const TA_MEDIAN_Stream *stream, int *outBegIdx, int *outNBElement )
{
   if( !stream || !outBegIdx || !outNBElement ) return TA_BAD_PARAM;
   *outBegIdx = stream->outRangeBegIdx;
   *outNBElement = stream->outRangeCount;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_MEDIAN_Advance( TA_MEDIAN_Stream *stream )
{
   if( !stream ) return TA_BAD_PARAM;
   if( stream->outRangeBegIdx + stream->outRangeCount > TA_MAX_INDEX )
      return TA_OUT_OF_RANGE_END_INDEX;
   stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_MEDIAN_Clone( const TA_MEDIAN_Stream *stream, TA_MEDIAN_Stream **clone )
{
   struct TA_MEDIAN_Stream *sp;

   if( !clone ) return TA_BAD_PARAM;
   *clone = NULL;
   if( !stream ) return TA_BAD_PARAM;
   sp = (struct TA_MEDIAN_Stream *)TA_Malloc( sizeof(*sp) );
   if( !sp ) return TA_ALLOC_ERR;
   *sp = *stream;
   sp->cb_ring = NULL;
   sp->cb_sorted = NULL;
   if( stream->cb_ring )
   { size_t copyN = (size_t)(sp->cbSize_ring);
     sp->cb_ring = (double *)TA_Malloc( sizeof(double) * copyN );
     if( !sp->cb_ring ) { TA_MEDIAN_Close( sp ); return TA_ALLOC_ERR; }
     memcpy( sp->cb_ring, stream->cb_ring, sizeof(double) * copyN ); }
   if( stream->cb_sorted )
   { size_t copyN = (size_t)(sp->cbSize_sorted);
     sp->cb_sorted = (double *)TA_Malloc( sizeof(double) * copyN );
     if( !sp->cb_sorted ) { TA_MEDIAN_Close( sp ); return TA_ALLOC_ERR; }
     memcpy( sp->cb_sorted, stream->cb_sorted, sizeof(double) * copyN ); }
   *clone = sp;
   return TA_SUCCESS;
}

