/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_unguarded.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  MF       Mario Fortier
 *  AC       Angelo Ciceri
 *
 *
 * Change history:
 *
 *  MMDDYY BY   Description
 *  -------------------------------------------------------------------
 *  010802 MF   Template creation.
 *  052603 MF   Adapt code to compile with .NET Managed C++
 *  110206 AC   Change volume and open interest to double
 */

TA_LIB_API int TA_OBV_Lookback( void )
{
   /* This function have no lookback needed. */
   return 0;
}

TA_LIB_API TA_RetCode TA_OBV( int    startIdx,
                              int    endIdx,
                              const double inReal[],
                              const double inVolume[],
                              int          *outBegIdx,
                              int          *outNBElement,
                              double        outReal[] )
{
   int i;
   int outIdx;
   double prevReal;
   double tempReal;
   double prevOBV;

   if( startIdx < 0 )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( !inReal )
      return TA_BAD_PARAM;
   if( !inVolume )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   prevOBV = inVolume[startIdx];
   prevReal = inReal[startIdx];
   outIdx = 0;
   for( i = startIdx; i <= endIdx; i += 1 )
   {
      tempReal = inReal[i];
      if( tempReal > prevReal )
      {
         prevOBV += inVolume[i];
      } else if( tempReal < prevReal )
      {
         prevOBV -= inVolume[i];
      }
      outReal[outIdx++] = prevOBV;
      prevReal = tempReal;
   }
   *outBegIdx= startIdx;
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_OBV_Unguarded( int    startIdx,
                                        int    endIdx,
                                        const double inReal[],
                                        const double inVolume[],
                                        int          *outBegIdx,
                                        int          *outNBElement,
                                        double        outReal[] )
{
   int i;
   int outIdx;
   double prevReal;
   double tempReal;
   double prevOBV;

   prevOBV = inVolume[startIdx];
   prevReal = inReal[startIdx];
   outIdx = 0;
   for( i = startIdx; i <= endIdx; i += 1 )
   {
      tempReal = inReal[i];
      if( tempReal > prevReal )
      {
         prevOBV += inVolume[i];
      } else if( tempReal < prevReal )
      {
         prevOBV -= inVolume[i];
      }
      outReal[outIdx++] = prevOBV;
      prevReal = tempReal;
   }
   *outBegIdx= startIdx;
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

TA_RetCode TA_S_OBV( int    startIdx,
                     int    endIdx,
                     const float inReal[],
                     const float inVolume[],
                     int          *outBegIdx,
                     int          *outNBElement,
                     double        outReal[] )
{
   int i;
   int outIdx;
   double prevReal;
   double tempReal;
   double prevOBV;

   if( startIdx < 0 )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( !inReal )
      return TA_BAD_PARAM;
   if( !inVolume )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   prevOBV = (double)inVolume[startIdx];
   prevReal = (double)inReal[startIdx];
   outIdx = 0;
   for( i = startIdx; i <= endIdx; i += 1 )
   {
      tempReal = (double)inReal[i];
      if( tempReal > prevReal )
      {
         prevOBV += (double)inVolume[i];
      } else if( tempReal < prevReal )
      {
         prevOBV -= (double)inVolume[i];
      }
      outReal[outIdx++] = prevOBV;
      prevReal = tempReal;
   }
   *outBegIdx= startIdx;
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

TA_RetCode TA_S_OBV_Unguarded( int    startIdx,
                               int    endIdx,
                               const float inReal[],
                               const float inVolume[],
                               int          *outBegIdx,
                               int          *outNBElement,
                               double        outReal[] )
{
   int i;
   int outIdx;
   double prevReal;
   double tempReal;
   double prevOBV;

   prevOBV = (double)inVolume[startIdx];
   prevReal = (double)inReal[startIdx];
   outIdx = 0;
   for( i = startIdx; i <= endIdx; i += 1 )
   {
      tempReal = (double)inReal[i];
      if( tempReal > prevReal )
      {
         prevOBV += (double)inVolume[i];
      } else if( tempReal < prevReal )
      {
         prevOBV -= (double)inVolume[i];
      }
      outReal[outIdx++] = prevOBV;
      prevReal = tempReal;
   }
   *outBegIdx= startIdx;
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

