/* TA-LIB Copyright (c) 1999-2026, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_stream_private.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  MF       Mario Fortier
 *  AC       Angelo Ciceri
 *
 *
 * Change history:
 *
 *  MMDDYY BY   Description
 *  -------------------------------------------------------------------
 *  010802 MF   Template creation.
 *  052603 MF   Adapt code to compile with .NET Managed C++
 *  110206 AC   Change volume and open interest to double
 */

TA_LIB_API int TA_OBV_Lookback( void )
{
   /* This function have no lookback needed. */
   return 0;
}

TA_LIB_API TA_RetCode TA_OBV( int    startIdx,
                              int    endIdx,
                              const double inReal[],
                              const double inVolume[],
                              int          *outBegIdx,
                              int          *outNBElement,
                              double        outReal[] )
{
   int i;
   int outIdx;
   double prevReal;
   double tempReal;
   double prevOBV;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( !inReal )
      return TA_BAD_PARAM;
   if( !inVolume )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   prevOBV = inVolume[startIdx];
   prevReal = inReal[startIdx];
   outIdx = 0;
   for( i = startIdx; i <= endIdx; i += 1 )
   {
      tempReal = inReal[i];
      if( tempReal > prevReal )
      {
         prevOBV += inVolume[i];
      } else if( tempReal < prevReal )
      {
         prevOBV -= inVolume[i];
      }
      outReal[outIdx++] = prevOBV;
      prevReal = tempReal;
   }
   *outBegIdx= startIdx;
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

TA_RetCode TA_S_OBV( int    startIdx,
                     int    endIdx,
                     const float inReal[],
                     const float inVolume[],
                     int          *outBegIdx,
                     int          *outNBElement,
                     double        outReal[] )
{
   int i;
   int outIdx;
   double prevReal;
   double tempReal;
   double prevOBV;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( !inReal )
      return TA_BAD_PARAM;
   if( !inVolume )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   prevOBV = (double)inVolume[startIdx];
   prevReal = (double)inReal[startIdx];
   outIdx = 0;
   for( i = startIdx; i <= endIdx; i += 1 )
   {
      tempReal = (double)inReal[i];
      if( tempReal > prevReal )
      {
         prevOBV += (double)inVolume[i];
      } else if( tempReal < prevReal )
      {
         prevOBV -= (double)inVolume[i];
      }
      outReal[outIdx++] = prevOBV;
      prevReal = tempReal;
   }
   *outBegIdx= startIdx;
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

/**** Streaming API *****/

struct TA_OBV_Stream {
   /* The bars this handle has an output for (see TA_OBV_OutRange). */
   int outRangeBegIdx;
   int outRangeCount;
   /* The value(s) at the last bar the stream counted (see TA_OBV_Value). */
   double cur_outReal;
   double prevReal;
   double prevOBV;
};

/* Private function, not in public API. */
static void TA_OBV_StepImpl( struct TA_OBV_Stream *sp, double inReal, double inVolume, double *outReal )
{
   double tempReal;

   tempReal = inReal;
   if( tempReal > sp->prevReal )
   {
      sp->prevOBV += inVolume;
   } else if( tempReal < sp->prevReal )
   {
      sp->prevOBV -= inVolume;
   }
   *outReal= sp->prevOBV;
   sp->prevReal = tempReal;
   sp->cur_outReal = *outReal;
}

static TA_RetCode TA_OBV_OpenImpl( struct TA_OBV_Stream **stream, const double inReal[], const double inVolume[], int startIdx, int historyLen, int *outBegIdx, int *outNBElement, double outReal[], int outStride )
{
   struct TA_OBV_Stream *sp;
   int endIdx;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inReal || !inVolume || !outReal ) return TA_BAD_PARAM;
   if( startIdx > historyLen - 1 )
   {
      *outBegIdx = 0;
      *outNBElement = 0;
      return TA_INSUFFICIENT_HISTORY;
   }

   endIdx = historyLen - 1;

   {
      int i;
      int outIdx;
      double prevReal = 0.0;
      double tempReal;
      double prevOBV = 0.0;
      prevOBV = inVolume[startIdx];
      prevReal = inReal[startIdx];
      outIdx = 0;
      for( i = startIdx; i <= endIdx; i += 1 )
      {
         tempReal = inReal[i];
         if( tempReal > prevReal )
         {
            prevOBV += inVolume[i];
         } else if( tempReal < prevReal )
         {
            prevOBV -= inVolume[i];
         }
         outReal[outIdx++ * outStride] = prevOBV;
         prevReal = tempReal;
      }
      *outBegIdx= startIdx;
      *outNBElement= outIdx;

      /* Capture the live batch state into the handle. */
      sp = (struct TA_OBV_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) { return TA_ALLOC_ERR; }
      memset( sp, 0, sizeof(*sp) );
      sp->prevReal = prevReal;
      sp->prevOBV = prevOBV;
      sp->outRangeBegIdx = *outBegIdx;
      sp->outRangeCount = *outNBElement;
      sp->cur_outReal = outReal[(*outNBElement - 1) * outStride];
      *stream = sp;
      return TA_SUCCESS;
   }
}

/* Private function, not in public API. */
TA_RetCode TA_OBV_OpenInternal( struct TA_OBV_Stream **stream, const double inReal[], const double inVolume[], int startIdx, int historyLen, double *outReal )
{
   TA_RetCode retCode;
   int dummyBegIdx = 0;
   int dummyNBElement = 0;
   double sink_outReal = 0.0;
   retCode = TA_OBV_OpenImpl( stream, inReal, inVolume, startIdx, historyLen, &dummyBegIdx, &dummyNBElement, &sink_outReal, 0 );
   if( retCode == TA_SUCCESS )
   {
      *outReal = sink_outReal;
   }
   return retCode;
}

TA_LIB_API TA_RetCode TA_OBV_Open( TA_OBV_Stream **stream, const double inReal[], const double inVolume[], int historyLen, double *outReal )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inReal || !inVolume || !outReal ) return TA_BAD_PARAM;
   return TA_OBV_OpenInternal( stream, inReal, inVolume, 0, historyLen, outReal );
}

TA_LIB_API TA_RetCode TA_OBV_OpenAndFill( TA_OBV_Stream **stream, const double inReal[], const double inVolume[], int historyLen, int *outBegIdx, int *outNBElement, double outReal[] )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inReal || !inVolume || !outBegIdx || !outNBElement || !outReal ) return TA_BAD_PARAM;
   if( (const void *)outReal == (const void *)inReal || (const void *)outReal == (const void *)inVolume ) return TA_BAD_PARAM;
   return TA_OBV_OpenAndFillInternal( stream, inReal, inVolume, 0, historyLen, outBegIdx, outNBElement, outReal );
}

/* Private function, not in public API. */
TA_RetCode TA_OBV_OpenAndFillInternal( struct TA_OBV_Stream **stream, const double inReal[], const double inVolume[], int startIdx, int historyLen, int *outBegIdx, int *outNBElement, double outReal[] )
{
   return TA_OBV_OpenImpl( stream, inReal, inVolume, startIdx, historyLen, outBegIdx, outNBElement, outReal, 1 );
}

TA_LIB_API TA_RetCode TA_OBV_Update( TA_OBV_Stream *stream, double inReal, double inVolume, double *outReal )
{
   if( !stream || !outReal ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inReal ) || !TA_IS_FINITE( inVolume ) ) return TA_BAD_PARAM;
   TA_OBV_StepImpl( stream, inReal, inVolume, outReal );
   if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_OBV_Peek( const TA_OBV_Stream *stream, double inReal, double inVolume, double *outReal )
{
   const struct TA_OBV_Stream *sp = stream;
   double tempReal;
   double prevOBV;

   if( !stream || !outReal ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inReal ) || !TA_IS_FINITE( inVolume ) ) return TA_BAD_PARAM;
   prevOBV = sp->prevOBV;
   tempReal = inReal;
   if( tempReal > sp->prevReal )
   {
      prevOBV += inVolume;
   } else if( tempReal < sp->prevReal )
   {
      prevOBV -= inVolume;
   }
   *outReal= prevOBV;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_OBV_Close( TA_OBV_Stream *stream )
{
   if( stream ) TA_Free( stream );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_OBV_Value( const TA_OBV_Stream *stream, double *outReal )
{
   if( !stream || !outReal ) return TA_BAD_PARAM;
   *outReal = stream->cur_outReal;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_OBV_OutRange( const TA_OBV_Stream *stream, int *outBegIdx, int *outNBElement )
{
   if( !stream || !outBegIdx || !outNBElement ) return TA_BAD_PARAM;
   *outBegIdx = stream->outRangeBegIdx;
   *outNBElement = stream->outRangeCount;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_OBV_Advance( TA_OBV_Stream *stream )
{
   if( !stream ) return TA_BAD_PARAM;
   if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_OBV_Clone( const TA_OBV_Stream *stream, TA_OBV_Stream **clone )
{
   struct TA_OBV_Stream *sp;

   if( !clone ) return TA_BAD_PARAM;
   *clone = NULL;
   if( !stream ) return TA_BAD_PARAM;
   sp = (struct TA_OBV_Stream *)TA_Malloc( sizeof(*sp) );
   if( !sp ) return TA_ALLOC_ERR;
   *sp = *stream;
   *clone = sp;
   return TA_SUCCESS;
}

