/* TA-LIB Copyright (c) 1999-2026, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_stream_private.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  MF       Mario Fortier
 *  CC       Claude Code (AI assistant)
 *
 * Change history:
 *
 *  MMDDYY BY     Description
 *  -------------------------------------------------------------------
 *  071626 MF,CC  Initial version (#119).
 */

TA_LIB_API int TA_PVO_Lookback( int optInFastPeriod, int optInSlowPeriod, TA_MAType optInMAType )
{
   if( (int)optInFastPeriod == TA_INTEGER_DEFAULT )
      optInFastPeriod = 12;
   else if( (int)optInFastPeriod < 2 || (int)optInFastPeriod > 100000 )
      return -1;
   if( (int)optInSlowPeriod == TA_INTEGER_DEFAULT )
      optInSlowPeriod = 26;
   else if( (int)optInSlowPeriod < 2 || (int)optInSlowPeriod > 100000 )
      return -1;
   if( (int)optInMAType == TA_INTEGER_DEFAULT || optInMAType == TA_MAType_DEFAULT )
      optInMAType = 1;
   else if( (int)optInMAType < TA_MATYPE_MIN || (int)optInMAType > TA_MATYPE_MAX )
      return -1;
   /* Lookback is driven by the slowest MA. */
   return TA_MA_Lookback(max(optInSlowPeriod,optInFastPeriod),optInMAType);
}

TA_LIB_API TA_RetCode TA_PVO( int    startIdx,
                              int    endIdx,
                              const double inVolume[],
                              int optInFastPeriod,
                              int optInSlowPeriod,
                              TA_MAType optInMAType,
                              int          *outBegIdx,
                              int          *outNBElement,
                              double        outReal[] )
{
   double *tempBuffer;
   TA_RetCode retCode;
   double tempReal;
   int tempInteger;
   int fastBeg;
   int fastNb;
   int offset;
   int i;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInFastPeriod == TA_INTEGER_DEFAULT )
      optInFastPeriod = 12;
   else if( (int)optInFastPeriod < 2 || (int)optInFastPeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInSlowPeriod == TA_INTEGER_DEFAULT )
      optInSlowPeriod = 26;
   else if( (int)optInSlowPeriod < 2 || (int)optInSlowPeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInMAType == TA_INTEGER_DEFAULT || optInMAType == TA_MAType_DEFAULT )
      optInMAType = 1;
   else if( (int)optInMAType < TA_MATYPE_MIN || (int)optInMAType > TA_MATYPE_MAX )
      return TA_BAD_PARAM;
   if( !inVolume )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   /* Nothing to produce: the range is shorter than the lookback. Return before
    * touching anything.
    *
    * Without this the fast MA below runs first, and its lookback is SMALLER
    * than pvo's own — so it reads the whole range and computes a result the
    * empty slow MA then discards. Observably identical (the slow MA's own early
    * return already yields 0,0 here), but it is the difference between "a range
    * shorter than the lookback reads nothing" being true of this function and
    * being false: with a caller-supplied inVolume that stops short of endIdx, that
    * discarded work is an out-of-bounds read. Pinned by the zero-length no-I/O
    * probe over every guarded core.
    */
   if( TA_MA_Lookback(max(optInSlowPeriod,optInFastPeriod),optInMAType) > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   /* Allocate an intermediate buffer. */
   tempBuffer = malloc((endIdx - startIdx + 1) * sizeof(double));
   if( !tempBuffer )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_ALLOC_ERR;
   }
   /* Make sure slow is really slower than
    * the fast period! if not, swap...
    */
   if( optInSlowPeriod < optInFastPeriod )
   {
      /* swap */
      tempInteger = optInSlowPeriod;
      optInSlowPeriod = optInFastPeriod;
      optInFastPeriod = tempInteger;
   }
   /* Calculate the fast MA into the tempBuffer. */
   retCode = TA_MA(startIdx,endIdx,inVolume,optInFastPeriod,optInMAType,&fastBeg,&fastNb,tempBuffer);
   if( retCode != TA_SUCCESS )
   {
      free(tempBuffer);
      return retCode;
   }
   /* Calculate the slow MA into the output. */
   retCode = TA_MA(startIdx,endIdx,inVolume,optInSlowPeriod,optInMAType,outBegIdx,outNBElement,outReal);
   if( retCode != TA_SUCCESS )
   {
      free(tempBuffer);
      return retCode;
   }
   /* fastNb - *outNBElement == slowBeg - fastBeg (the fast MA has at least as
    * many outputs), so tempBuffer[i+offset] is the fast MA at the same bar as
    * outReal[i], with a non-negative index. An empty slow MA skips the loop.
    */
   offset = fastNb - *outNBElement;
   /* Calculate ((fast MA)-(slow MA))/(slow MA) in the output. */
   for( i = 0; i < (int)*outNBElement; i += 1 )
   {
      tempReal = outReal[i];
      if( !TA_IS_ZERO(tempReal) )
      {
         outReal[i] = (tempBuffer[i + offset] - tempReal) / tempReal * 100.0;
      } else 
      {
         outReal[i] = 0.0;
      }
   }
   free(tempBuffer);
   return TA_SUCCESS;
}

TA_RetCode TA_S_PVO( int    startIdx,
                     int    endIdx,
                     const float inVolume[],
                     int optInFastPeriod,
                     int optInSlowPeriod,
                     TA_MAType optInMAType,
                     int          *outBegIdx,
                     int          *outNBElement,
                     double        outReal[] )
{
   double *tempBuffer;
   TA_RetCode retCode;
   double tempReal;
   int tempInteger;
   int fastBeg;
   int fastNb;
   int offset;
   int i;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInFastPeriod == TA_INTEGER_DEFAULT )
      optInFastPeriod = 12;
   else if( (int)optInFastPeriod < 2 || (int)optInFastPeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInSlowPeriod == TA_INTEGER_DEFAULT )
      optInSlowPeriod = 26;
   else if( (int)optInSlowPeriod < 2 || (int)optInSlowPeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInMAType == TA_INTEGER_DEFAULT || optInMAType == TA_MAType_DEFAULT )
      optInMAType = 1;
   else if( (int)optInMAType < TA_MATYPE_MIN || (int)optInMAType > TA_MATYPE_MAX )
      return TA_BAD_PARAM;
   if( !inVolume )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   if( TA_MA_Lookback(max(optInSlowPeriod,optInFastPeriod),optInMAType) > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   tempBuffer = malloc((endIdx - startIdx + 1) * sizeof(double));
   if( !tempBuffer )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_ALLOC_ERR;
   }
   if( optInSlowPeriod < optInFastPeriod )
   {
      tempInteger = optInSlowPeriod;
      optInSlowPeriod = optInFastPeriod;
      optInFastPeriod = tempInteger;
   }
   retCode = TA_S_MA(startIdx,endIdx,inVolume,optInFastPeriod,optInMAType,&fastBeg,&fastNb,tempBuffer);
   if( retCode != TA_SUCCESS )
   {
      free(tempBuffer);
      return retCode;
   }
   retCode = TA_S_MA(startIdx,endIdx,inVolume,optInSlowPeriod,optInMAType,outBegIdx,outNBElement,outReal);
   if( retCode != TA_SUCCESS )
   {
      free(tempBuffer);
      return retCode;
   }
   offset = fastNb - *outNBElement;
   for( i = 0; i < (int)*outNBElement; i += 1 )
   {
      tempReal = outReal[i];
      if( !TA_IS_ZERO(tempReal) )
      {
         outReal[i] = (tempBuffer[i + offset] - tempReal) / tempReal * 100.0;
      } else 
      {
         outReal[i] = 0.0;
      }
   }
   free(tempBuffer);
   return TA_SUCCESS;
}

/**** Streaming API *****/

struct TA_PVO_Stream {
   /* The bars this handle has an output for (see TA_StreamOutRange).
    * Kept first, and in this order, in every stream struct. */
   int outRangeBegIdx;
   int outRangeCount;
   /* The value(s) at the last bar the stream counted (see TA_PVO_Value). */
   double cur_outReal;
   int optInFastPeriod;
   int optInSlowPeriod;
   TA_MAType optInMAType;
   TA_MA_Stream *sub0;
   TA_MA_Stream *sub1;
};

/* Private function, not in public API. */
static TA_RetCode TA_PVO_StepImpl( struct TA_PVO_Stream *sp, double inVolume, double *outReal )
{
   double tempReal;
   double cur_tempBuffer = 0.0;
   double cur_outReal = 0.0;


   /* Pipeline the new bar through the sub-streams (batch tail order). */
   {
      TA_RetCode subRc = TA_MA_Update( sp->sub0, inVolume, &cur_tempBuffer );
      if( subRc != TA_SUCCESS ) return subRc;
   }
   {
      TA_RetCode subRc = TA_MA_Update( sp->sub1, inVolume, &cur_outReal );
      if( subRc != TA_SUCCESS ) return subRc;
   }
   /* Combine map (batch tail, per bar). */
   tempReal = cur_outReal;
   if( !TA_IS_ZERO(tempReal) )
   {
      cur_outReal = (cur_tempBuffer - tempReal) / tempReal * 100.0;
   } else 
   {
      cur_outReal = 0.0;
   }
   *outReal = cur_outReal;
   return TA_SUCCESS;
}

static TA_RetCode TA_PVO_OpenImpl( struct TA_PVO_Stream **stream, const double inVolume[], int startIdx, int historyLen, int optInFastPeriod, int optInSlowPeriod, TA_MAType optInMAType, int *outBegIdx, int *outNBElement, double outReal[], int outStride )
{
   struct TA_PVO_Stream *sp;
   int endIdx;
   int dummyBegIdx;
   int dummyNBElement;
   TA_RetCode subRc;
   double subOpenDummy;
   double *sc_outReal;
   TA_MA_Stream *sub0;
   TA_MA_Stream *sub1;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inVolume || !outReal ) return TA_BAD_PARAM;
   if( (int)optInFastPeriod == TA_INTEGER_DEFAULT )
      optInFastPeriod = 12;
   else if( (int)optInFastPeriod < 2 || (int)optInFastPeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInSlowPeriod == TA_INTEGER_DEFAULT )
      optInSlowPeriod = 26;
   else if( (int)optInSlowPeriod < 2 || (int)optInSlowPeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInMAType == TA_INTEGER_DEFAULT || optInMAType == TA_MAType_DEFAULT )
      optInMAType = 1;
   else if( (int)optInMAType < TA_MATYPE_MIN || (int)optInMAType > TA_MATYPE_MAX )
      return TA_BAD_PARAM;
   if( startIdx > historyLen - 1 )
   {
      *outBegIdx = 0;
      *outNBElement = 0;
      return TA_INSUFFICIENT_HISTORY;
   }

   endIdx = historyLen - 1;
   dummyBegIdx = 0;
   dummyNBElement = 0;
   subRc = TA_SUCCESS;
   subOpenDummy = 0.0;
   sub0 = NULL;
   sub1 = NULL;
   (void)startIdx; (void)dummyBegIdx; (void)dummyNBElement; (void)subRc; (void)subOpenDummy;
   if( outStride ) sc_outReal = outReal;
   else
   {
      sc_outReal = (double *)TA_Malloc( sizeof(double) * (size_t)historyLen );
      if( !sc_outReal ) { return TA_ALLOC_ERR; }
   }

   {
      double *tempBuffer;
      TA_RetCode retCode;
      double tempReal;
      int tempInteger;
      int fastBeg;
      int fastNb;
      int offset;
      int i;
      /* Nothing to produce: the range is shorter than the lookback. Return before
       * touching anything.
       *
       * Without this the fast MA below runs first, and its lookback is SMALLER
       * than pvo's own — so it reads the whole range and computes a result the
       * empty slow MA then discards. Observably identical (the slow MA's own early
       * return already yields 0,0 here), but it is the difference between "a range
       * shorter than the lookback reads nothing" being true of this function and
       * being false: with a caller-supplied inVolume that stops short of endIdx, that
       * discarded work is an out-of-bounds read. Pinned by the zero-length no-I/O
       * probe over every guarded core.
       */
      if( TA_MA_Lookback(max(optInSlowPeriod,optInFastPeriod),optInMAType) > endIdx )
      {
         dummyBegIdx = 0;
         dummyNBElement = 0;
         TA_MA_Close( sub0 ); TA_MA_Close( sub1 ); if( !outStride ) TA_Free( sc_outReal );
         return TA_INSUFFICIENT_HISTORY;
      }
      /* Allocate an intermediate buffer. */
      tempBuffer = malloc((endIdx - startIdx + 1) * sizeof(double));
      if( !tempBuffer )
      {
         TA_MA_Close( sub0 ); TA_MA_Close( sub1 ); if( !outStride ) TA_Free( sc_outReal );
         return TA_ALLOC_ERR;
      }
      /* Make sure slow is really slower than
       * the fast period! if not, swap...
       */
      if( optInSlowPeriod < optInFastPeriod )
      {
         /* swap */
         tempInteger = optInSlowPeriod;
         optInSlowPeriod = optInFastPeriod;
         optInFastPeriod = tempInteger;
      }
      /* Calculate the fast MA into the tempBuffer. */
      /* Sub-stream 0: ma over `inVolume`, warmed from bar 0 up to the
       * sub-call's own startIdx (the seeding point). */
      {
         subRc = TA_MA_OpenAndFillInternal( &sub0, inVolume, (startIdx), (endIdx) + 1, optInFastPeriod, optInMAType, &fastBeg, &fastNb, tempBuffer );
         if( subRc != TA_SUCCESS )
         {
            free(tempBuffer);
            TA_MA_Close( sub0 ); TA_MA_Close( sub1 ); if( !outStride ) TA_Free( sc_outReal );
            return subRc;
         }
      }
      retCode = subRc;
      if( retCode != TA_SUCCESS )
      {
         free(tempBuffer);
         TA_MA_Close( sub0 ); TA_MA_Close( sub1 ); if( !outStride ) TA_Free( sc_outReal );
         return retCode;
      }
      /* Calculate the slow MA into the output. */
      /* Sub-stream 1: ma over `inVolume`, warmed from bar 0 up to the
       * sub-call's own startIdx (the seeding point). */
      {
         subRc = TA_MA_OpenAndFillInternal( &sub1, inVolume, (startIdx), (endIdx) + 1, optInSlowPeriod, optInMAType, &dummyBegIdx, &dummyNBElement, sc_outReal );
         if( subRc != TA_SUCCESS )
         {
            free(tempBuffer);
            TA_MA_Close( sub0 ); TA_MA_Close( sub1 ); if( !outStride ) TA_Free( sc_outReal );
            return subRc;
         }
      }
      retCode = subRc;
      if( retCode != TA_SUCCESS )
      {
         free(tempBuffer);
         TA_MA_Close( sub0 ); TA_MA_Close( sub1 ); if( !outStride ) TA_Free( sc_outReal );
         return retCode;
      }
      /* fastNb - *outNBElement == slowBeg - fastBeg (the fast MA has at least as
       * many outputs), so tempBuffer[i+offset] is the fast MA at the same bar as
       * outReal[i], with a non-negative index. An empty slow MA skips the loop.
       */
      offset = fastNb - dummyNBElement;
      /* Calculate ((fast MA)-(slow MA))/(slow MA) in the output. */
      for( i = 0; i < (int)dummyNBElement; i += 1 )
      {
         tempReal = sc_outReal[i];
         if( !TA_IS_ZERO(tempReal) )
         {
            sc_outReal[i] = (tempBuffer[i + offset] - tempReal) / tempReal * 100.0;
         } else 
         {
            sc_outReal[i] = 0.0;
         }
      }
      free(tempBuffer);

      /* Capture the live producer state + sub handles. */
      if( dummyNBElement < 1 ) { TA_MA_Close( sub0 ); TA_MA_Close( sub1 ); if( !outStride ) TA_Free( sc_outReal ); return TA_INSUFFICIENT_HISTORY; }
      sp = (struct TA_PVO_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) { TA_MA_Close( sub0 ); TA_MA_Close( sub1 ); if( !outStride ) TA_Free( sc_outReal ); return TA_ALLOC_ERR; }
      memset( sp, 0, sizeof(*sp) );
      sp->optInFastPeriod = optInFastPeriod;
      sp->optInSlowPeriod = optInSlowPeriod;
      sp->optInMAType = optInMAType;
      sp->sub0 = sub0;
      sp->sub1 = sub1;
      *outBegIdx = dummyBegIdx;
      *outNBElement = dummyNBElement;
      if( !outStride ) outReal[0] = sc_outReal[dummyNBElement - 1];
      if( !outStride ) TA_Free( sc_outReal );
      sp->outRangeBegIdx = *outBegIdx;
      sp->outRangeCount = *outNBElement;
      sp->cur_outReal = outReal[(*outNBElement - 1) * outStride];
      *stream = sp;
      return TA_SUCCESS;
   }
}

/* Private function, not in public API. */
TA_RetCode TA_PVO_OpenInternal( struct TA_PVO_Stream **stream, const double inVolume[], int startIdx, int historyLen, int optInFastPeriod, int optInSlowPeriod, TA_MAType optInMAType, double *outReal )
{
   TA_RetCode retCode;
   int dummyBegIdx = 0;
   int dummyNBElement = 0;
   double sink_outReal = 0.0;
   retCode = TA_PVO_OpenImpl( stream, inVolume, startIdx, historyLen, optInFastPeriod, optInSlowPeriod, optInMAType, &dummyBegIdx, &dummyNBElement, &sink_outReal, 0 );
   if( retCode == TA_SUCCESS )
   {
      *outReal = sink_outReal;
   }
   return retCode;
}

TA_LIB_API TA_RetCode TA_PVO_Open( TA_PVO_Stream **stream, const double inVolume[], int historyLen, int optInFastPeriod, int optInSlowPeriod, TA_MAType optInMAType, double *outReal )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inVolume || !outReal ) return TA_BAD_PARAM;
   return TA_PVO_OpenInternal( stream, inVolume, 0, historyLen, optInFastPeriod, optInSlowPeriod, optInMAType, outReal );
}

TA_LIB_API TA_RetCode TA_PVO_OpenAndFill( TA_PVO_Stream **stream, const double inVolume[], int historyLen, int optInFastPeriod, int optInSlowPeriod, TA_MAType optInMAType, int *outBegIdx, int *outNBElement, double outReal[] )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inVolume || !outBegIdx || !outNBElement || !outReal ) return TA_BAD_PARAM;
   if( (const void *)outReal == (const void *)inVolume ) return TA_BAD_PARAM;
   return TA_PVO_OpenAndFillInternal( stream, inVolume, 0, historyLen, optInFastPeriod, optInSlowPeriod, optInMAType, outBegIdx, outNBElement, outReal );
}

/* Private function, not in public API. */
TA_RetCode TA_PVO_OpenAndFillInternal( struct TA_PVO_Stream **stream, const double inVolume[], int startIdx, int historyLen, int optInFastPeriod, int optInSlowPeriod, TA_MAType optInMAType, int *outBegIdx, int *outNBElement, double outReal[] )
{
   return TA_PVO_OpenImpl( stream, inVolume, startIdx, historyLen, optInFastPeriod, optInSlowPeriod, optInMAType, outBegIdx, outNBElement, outReal, 1 );
}

TA_LIB_API TA_RetCode TA_PVO_Update( TA_PVO_Stream *stream, double inVolume, double *outReal )
{
   TA_RetCode retCode;

   if( !stream || !outReal ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inVolume ) )
   {
      if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
      return TA_BAD_PARAM;
   }
   retCode = TA_PVO_StepImpl( stream, inVolume, outReal );
   if( retCode != TA_SUCCESS ) return retCode;
   stream->cur_outReal = *outReal;
   if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_PVO_Peek( const TA_PVO_Stream *stream, double inVolume, double *outReal )
{
   const struct TA_PVO_Stream *sp = stream;
   double tempReal;
   double cur_tempBuffer = 0.0;
   double cur_outReal = 0.0;

   if( !stream || !outReal ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inVolume ) ) return TA_BAD_PARAM;

   /* Pipeline the new bar through the sub-streams (batch tail order). */
   {
      TA_RetCode subRc = TA_MA_Peek( (const TA_MA_Stream *)sp->sub0, inVolume, &cur_tempBuffer );
      if( subRc != TA_SUCCESS ) return subRc;
   }
   {
      TA_RetCode subRc = TA_MA_Peek( (const TA_MA_Stream *)sp->sub1, inVolume, &cur_outReal );
      if( subRc != TA_SUCCESS ) return subRc;
   }
   /* Combine map (batch tail, per bar). */
   tempReal = cur_outReal;
   if( !TA_IS_ZERO(tempReal) )
   {
      cur_outReal = (cur_tempBuffer - tempReal) / tempReal * 100.0;
   } else 
   {
      cur_outReal = 0.0;
   }
   *outReal = cur_outReal;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_PVO_UpdateAndFill( TA_PVO_Stream *stream, const double inVolume[], int barCount, double outReal[] )
{
   int i;
   TA_RetCode retCode;

   if( !stream || !inVolume || !outReal ) return TA_BAD_PARAM;
   if( barCount < 0 ) return TA_BAD_PARAM;
   if( (const void *)outReal == (const void *)inVolume ) return TA_BAD_PARAM;
   for( i = 0; i < barCount; i++ )
   {
      if( !TA_IS_FINITE( inVolume[i] ) )
      {
         if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
         return TA_BAD_PARAM;
      }
      retCode = TA_PVO_StepImpl( stream, inVolume[i], &outReal[i] );
      if( retCode != TA_SUCCESS ) return retCode;
      stream->cur_outReal = outReal[i];
      if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   }
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_PVO_Close( TA_PVO_Stream *stream )
{
   if( !stream ) return TA_SUCCESS;
   TA_MA_Close( stream->sub0 );
   TA_MA_Close( stream->sub1 );
   TA_Free( stream );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_PVO_Value( const TA_PVO_Stream *stream, double *outReal )
{
   if( !stream || !outReal ) return TA_BAD_PARAM;
   *outReal = stream->cur_outReal;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_PVO_Clone( const TA_PVO_Stream *stream, TA_PVO_Stream **clone )
{
   struct TA_PVO_Stream *sp;

   if( !clone ) return TA_BAD_PARAM;
   *clone = NULL;
   if( !stream ) return TA_BAD_PARAM;
   sp = (struct TA_PVO_Stream *)TA_Malloc( sizeof(*sp) );
   if( !sp ) return TA_ALLOC_ERR;
   *sp = *stream;
   sp->sub0 = NULL;
   sp->sub1 = NULL;
   if( stream->sub0 )
   { TA_RetCode subRc = TA_MA_Clone( stream->sub0, &sp->sub0 );
     if( subRc != TA_SUCCESS ) { TA_PVO_Close( sp ); return subRc; } }
   if( stream->sub1 )
   { TA_RetCode subRc = TA_MA_Clone( stream->sub1, &sp->sub1 );
     if( subRc != TA_SUCCESS ) { TA_PVO_Close( sp ); return subRc; } }
   *clone = sp;
   return TA_SUCCESS;
}

