/* TA-LIB Copyright (c) 1999-2026, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_stream_private.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  MF       Mario Fortier
 *  KL       Kevin Lin (@kevinlincg)
 *  CC       Claude Code (AI assistant)
 *
 * Change history:
 *
 *  MMDDYY BY     Description
 *  -------------------------------------------------------------------
 *  100526 KL,CC  Creation (#483).
 */

TA_LIB_API int TA_ROGERSSATCHELL_Lookback( int optInTimePeriod, double optInAnnualization )
{
   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 10;
   else if( (int)optInTimePeriod < 1 || (int)optInTimePeriod > 100000 )
      return -1;
   if( optInAnnualization == TA_REAL_DEFAULT )
      optInAnnualization = 252;
   else if( !(optInAnnualization >= 0e0 && optInAnnualization <= TA_REAL_MAX) )
      return -1;
   /* The window's lookback and nothing else: there is no callee, and a term
    * reads only its own bar -- no previous close -- so no bar is consumed to
    * form it. Same as sum_lookback (sum/sum.c:16-19) and var_lookback
    * (var/var.c:21-26), and one less than an estimator that differences
    * against C[i-1]. optInAnnualization scales the output and cannot move the
    * first bar, as optInNbDev cannot in var.c:23.
    */
   return optInTimePeriod - 1;
}

TA_LIB_API int TA_ROGERSSATCHELL_DisplayShift( int optInTimePeriod, double optInAnnualization, int outputIdx )
{
   if( TA_ROGERSSATCHELL_Lookback( optInTimePeriod, optInAnnualization ) < 0 )
      return INT_MIN;
   if( outputIdx < 0 || outputIdx >= 1 )
      return INT_MIN;
   return 0;
}

TA_LIB_API TA_RetCode TA_ROGERSSATCHELL( int    startIdx,
                                         int    endIdx,
                                         const double inOpen[],
                                         const double inHigh[],
                                         const double inLow[],
                                         const double inClose[],
                                         int optInTimePeriod,
                                         double optInAnnualization,
                                         int          *outBegIdx,
                                         int          *outNBElement,
                                         double        outReal[] )
{
   double o;
   double h;
   double l;
   double c;
   double p1;
   double p2;
   double term;
   double periodTotal;
   double windowTotal;
   double peakTotal;
   double sqrtA;
   int i;
   int j;
   int outIdx;
   int trailingIdx;
   int windowStart;
   int nbInitialElementNeeded;
   int barsSinceRebuild;

   if( (startIdx < 0) || (startIdx > TA_INDEX_MAX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_INDEX_MAX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 10;
   else if( (int)optInTimePeriod < 1 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( optInAnnualization == TA_REAL_DEFAULT )
      optInAnnualization = 252;
   else if( !(optInAnnualization >= 0e0 && optInAnnualization <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( !inOpen )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !inClose )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   nbInitialElementNeeded = optInTimePeriod - 1;
   if( startIdx < nbInitialElementNeeded )
   {
      startIdx = nbInitialElementNeeded;
   }
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   /* Rogers and Satchell, The Annals of Applied Probability 1(4):504-512 (1991),
    * eq. (2) on p.505: with the log price measured from the bar's open,
    * S1 = ln(H/O), I1 = ln(L/O) and X1 = ln(C/O), one bar's unbiased estimate
    * of its variance is S1(S1 - X1) + I1(I1 - X1), which is ln(H/C)ln(H/O) +
    * ln(L/C)ln(L/O). Eq. (3) is what sets this estimator apart: that
    * expectation is sigma^2 whatever the drift, so a bar that opens at its low
    * and closes at its high -- all drift, no dispersion -- reads exactly zero,
    * where a range-only estimator reads volatility.
    *
    * The paper stops there. The window mean, the root and the annual scale are
    * the convention of every implementation of it, not the authors'.
    */
   /* Once, so that optInAnnualization = 1.0 is an exact identity rather than a
    * multiply by a rounded 1.0, and so the per-bar and annualised outputs
    * differ by exactly this factor.
    */
   sqrtA = sqrt(optInAnnualization);
   trailingIdx = startIdx - nbInitialElementNeeded;
   periodTotal = 0.0;
   for( j = trailingIdx; j < startIdx; j += 1 )
   {
      /* The two products are SEPARATE statements on purpose. Written as one
       * expression the generator's FMA detector fuses the first product into
       * the add (backends/fma.rs:406-433; a log call counts as a float factor
       * at :252-285), which moves 159 of 243 outputs on the corpus at n = 10
       * and buys nothing measurable. VWMA splits its product for the same
       * reason (vwma/vwma.c:78-81).
       *
       * The guard is the whole bar, tested exactly rather than against a fixed
       * band (#253): a bar with any price at or below zero contributes a 0.0
       * term and still counts toward the window's n. Zeroing only the products
       * that touch the bad price has no implementation behind it, and dropping
       * the bar from the window makes n data-dependent.
       */
      o = inOpen[j];
      h = inHigh[j];
      l = inLow[j];
      c = inClose[j];
      if( o > 0.0 && h > 0.0 && l > 0.0 && c > 0.0 )
      {
         p1 = log(h / c) * log(h / o);
         p2 = log(l / c) * log(l / o);
         term = p1 + p2;
      } else 
      {
         term = 0.0;
      }
      periodTotal += term;
   }
   /* outReal may be any of the four input arrays: the output written on a bar
    * lands at or before the window's own trailing index, so every input slot
    * this loop still reads is one no write has reached yet.
    */
   i = startIdx;
   outIdx = 0;
   barsSinceRebuild = 32 * optInTimePeriod;
   peakTotal = periodTotal;
   do
   {
      o = inOpen[i];
      h = inHigh[i];
      l = inLow[i];
      c = inClose[i];
      if( o > 0.0 && h > 0.0 && l > 0.0 && c > 0.0 )
      {
         p1 = log(h / c) * log(h / o);
         p2 = log(l / c) * log(l / o);
         term = p1 + p2;
      } else 
      {
         term = 0.0;
      }
      periodTotal += term;
      peakTotal = (periodTotal > peakTotal) ? periodTotal : peakTotal;
      /* The sum this bar's output is taken from, before the trailing term is
       * removed for the next one.
       */
      windowTotal = periodTotal;
      o = inOpen[trailingIdx];
      h = inHigh[trailingIdx];
      l = inLow[trailingIdx];
      c = inClose[trailingIdx];
      if( o > 0.0 && h > 0.0 && l > 0.0 && c > 0.0 )
      {
         p1 = log(h / c) * log(h / o);
         p2 = log(l / c) * log(l / o);
         term = p1 + p2;
      } else 
      {
         term = 0.0;
      }
      periodTotal -= term;
      trailingIdx += 1;
      /* Rebuild as a fresh window sum when the running sum has collapsed to
       * below 1e-6 of the largest it has held since the last rebuild, or at
       * least every 32 windows -- VAR's rule (var.c:101-113). Measured against
       * the PEAK, not the current sum: what a running sum of add-then-subtract
       * carries is rounding at the scale of the largest window it has seen, so
       * once a quiet stretch arrives the current sum can be nothing but that
       * rounding. On an all-flat window the rebuild restores an exact 0.0,
       * where a plain running sum leaves a residual that is negative about
       * forty per cent of the time -- and a negative sum under an
       * unconditional root is where the composition of shipped functions
       * produces NaN.
       */
      barsSinceRebuild -= 1;
      if( windowTotal < 0.000001 * peakTotal || barsSinceRebuild <= 0 )
      {
         barsSinceRebuild = 32 * optInTimePeriod;
         windowStart = i - nbInitialElementNeeded;
         windowTotal = 0.0;
         for( j = windowStart; j <= i; j += 1 )
         {
            o = inOpen[j];
            h = inHigh[j];
            l = inLow[j];
            c = inClose[j];
            if( o > 0.0 && h > 0.0 && l > 0.0 && c > 0.0 )
            {
               p1 = log(h / c) * log(h / o);
               p2 = log(l / c) * log(l / o);
               term = p1 + p2;
            } else 
            {
               term = 0.0;
            }
            windowTotal += term;
         }
         /* The rebuilt window becomes the carried state, with its trailing
          * term removed again so the two paths leave the same thing behind.
          */
         periodTotal = windowTotal;
         peakTotal = windowTotal;
         o = inOpen[windowStart];
         h = inHigh[windowStart];
         l = inLow[windowStart];
         c = inClose[windowStart];
         if( o > 0.0 && h > 0.0 && l > 0.0 && c > 0.0 )
         {
            p1 = log(h / c) * log(h / o);
            p2 = log(l / c) * log(l / o);
            term = p1 + p2;
         } else 
         {
            term = 0.0;
         }
         periodTotal -= term;
      }
      /* The divide, then the root, then the scale -- the spelling every
       * implementation of this estimator uses, and what makes A = 1.0 exact.
       *
       * A sum at or below zero answers 0.0 rather than reaching the root. A
       * fresh sum of terms from consistent bars cannot be negative, so this
       * only catches a bar whose high or low sits strictly inside its open and
       * close, which is not a bar the estimator is defined on. VAR floors its
       * variance for the same reason, so that STDDEV can root it
       * unconditionally (var.c:165-166).
       */
      if( windowTotal > 0.0 )
      {
         outReal[outIdx] = sqrtA * sqrt(windowTotal / (double)optInTimePeriod);
      } else 
      {
         outReal[outIdx] = 0.0;
      }
      outIdx = outIdx + 1;
      i += 1;
   } while( i <= endIdx );
   *outNBElement= outIdx;
   *outBegIdx= startIdx;
   return TA_SUCCESS;
}

TA_RetCode TA_S_ROGERSSATCHELL( int    startIdx,
                                int    endIdx,
                                const float inOpen[],
                                const float inHigh[],
                                const float inLow[],
                                const float inClose[],
                                int optInTimePeriod,
                                double optInAnnualization,
                                int          *outBegIdx,
                                int          *outNBElement,
                                double        outReal[] )
{
   double o;
   double h;
   double l;
   double c;
   double p1;
   double p2;
   double term;
   double periodTotal;
   double windowTotal;
   double peakTotal;
   double sqrtA;
   int i;
   int j;
   int outIdx;
   int trailingIdx;
   int windowStart;
   int nbInitialElementNeeded;
   int barsSinceRebuild;

   if( (startIdx < 0) || (startIdx > TA_INDEX_MAX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_INDEX_MAX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 10;
   else if( (int)optInTimePeriod < 1 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( optInAnnualization == TA_REAL_DEFAULT )
      optInAnnualization = 252;
   else if( !(optInAnnualization >= 0e0 && optInAnnualization <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( !inOpen )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !inClose )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   nbInitialElementNeeded = optInTimePeriod - 1;
   if( startIdx < nbInitialElementNeeded )
   {
      startIdx = nbInitialElementNeeded;
   }
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   sqrtA = sqrt(optInAnnualization);
   trailingIdx = startIdx - nbInitialElementNeeded;
   periodTotal = 0.0;
   for( j = trailingIdx; j < startIdx; j += 1 )
   {
      o = (double)inOpen[j];
      h = (double)inHigh[j];
      l = (double)inLow[j];
      c = (double)inClose[j];
      if( o > 0.0 && h > 0.0 && l > 0.0 && c > 0.0 )
      {
         p1 = log(h / c) * log(h / o);
         p2 = log(l / c) * log(l / o);
         term = p1 + p2;
      } else 
      {
         term = 0.0;
      }
      periodTotal += term;
   }
   i = startIdx;
   outIdx = 0;
   barsSinceRebuild = 32 * optInTimePeriod;
   peakTotal = periodTotal;
   do
   {
      o = (double)inOpen[i];
      h = (double)inHigh[i];
      l = (double)inLow[i];
      c = (double)inClose[i];
      if( o > 0.0 && h > 0.0 && l > 0.0 && c > 0.0 )
      {
         p1 = log(h / c) * log(h / o);
         p2 = log(l / c) * log(l / o);
         term = p1 + p2;
      } else 
      {
         term = 0.0;
      }
      periodTotal += term;
      peakTotal = (periodTotal > peakTotal) ? periodTotal : peakTotal;
      windowTotal = periodTotal;
      o = (double)inOpen[trailingIdx];
      h = (double)inHigh[trailingIdx];
      l = (double)inLow[trailingIdx];
      c = (double)inClose[trailingIdx];
      if( o > 0.0 && h > 0.0 && l > 0.0 && c > 0.0 )
      {
         p1 = log(h / c) * log(h / o);
         p2 = log(l / c) * log(l / o);
         term = p1 + p2;
      } else 
      {
         term = 0.0;
      }
      periodTotal -= term;
      trailingIdx += 1;
      barsSinceRebuild -= 1;
      if( windowTotal < 0.000001 * peakTotal || barsSinceRebuild <= 0 )
      {
         barsSinceRebuild = 32 * optInTimePeriod;
         windowStart = i - nbInitialElementNeeded;
         windowTotal = 0.0;
         for( j = windowStart; j <= i; j += 1 )
         {
            o = (double)inOpen[j];
            h = (double)inHigh[j];
            l = (double)inLow[j];
            c = (double)inClose[j];
            if( o > 0.0 && h > 0.0 && l > 0.0 && c > 0.0 )
            {
               p1 = log(h / c) * log(h / o);
               p2 = log(l / c) * log(l / o);
               term = p1 + p2;
            } else 
            {
               term = 0.0;
            }
            windowTotal += term;
         }
         periodTotal = windowTotal;
         peakTotal = windowTotal;
         o = (double)inOpen[windowStart];
         h = (double)inHigh[windowStart];
         l = (double)inLow[windowStart];
         c = (double)inClose[windowStart];
         if( o > 0.0 && h > 0.0 && l > 0.0 && c > 0.0 )
         {
            p1 = log(h / c) * log(h / o);
            p2 = log(l / c) * log(l / o);
            term = p1 + p2;
         } else 
         {
            term = 0.0;
         }
         periodTotal -= term;
      }
      if( windowTotal > 0.0 )
      {
         outReal[outIdx] = sqrtA * sqrt(windowTotal / (double)optInTimePeriod);
      } else 
      {
         outReal[outIdx] = 0.0;
      }
      outIdx = outIdx + 1;
      i += 1;
   } while( i <= endIdx );
   *outNBElement= outIdx;
   *outBegIdx= startIdx;
   return TA_SUCCESS;
}

/**** Streaming API *****/

struct TA_ROGERSSATCHELL_Stream {
   /* The bars this handle has an output for (see TA_ROGERSSATCHELL_OutRange). */
   int outRangeBegIdx;
   int outRangeCount;
   /* The value(s) at the last bar the stream counted (see TA_ROGERSSATCHELL_Value). */
   double cur_outReal;
   int optInTimePeriod;
   double optInAnnualization;
   double pad_0;
   double periodTotal;
   double peakTotal;
   double pad_1;
   double sqrtA;
   int trailingIdx;
   int nbInitialElementNeeded;
   int barsSinceRebuild;
   int j;
   int windowStart;
   int i;
   int xCap;
   int xPhys;
   int xMask;
   double *x_inOpen;
   double *x_inHigh;
   double *x_inLow;
   double *x_inClose;
};

/* Private function, not in public API. */
static void TA_ROGERSSATCHELL_ReleaseImpl( struct TA_ROGERSSATCHELL_Stream *sp )
{
   if( !sp ) return;
   if( sp->x_inOpen ) TA_Free( sp->x_inOpen );
   if( sp->x_inHigh ) TA_Free( sp->x_inHigh );
   if( sp->x_inLow ) TA_Free( sp->x_inLow );
   if( sp->x_inClose ) TA_Free( sp->x_inClose );
   TA_Free( sp );
}

/* Private function, not in public API. */
static void TA_ROGERSSATCHELL_StepImpl( struct TA_ROGERSSATCHELL_Stream *sp, double inOpen, double inHigh, double inLow, double inClose, double *outReal )
{
   double o;
   double h;
   double l;
   double c;
   double p1;
   double p2;
   double term;
   double windowTotal;

   sp->x_inOpen[sp->i & sp->xMask] = inOpen;
   sp->x_inHigh[sp->i & sp->xMask] = inHigh;
   sp->x_inLow[sp->i & sp->xMask] = inLow;
   sp->x_inClose[sp->i & sp->xMask] = inClose;
   o = sp->x_inOpen[sp->i & sp->xMask];
   h = sp->x_inHigh[sp->i & sp->xMask];
   l = sp->x_inLow[sp->i & sp->xMask];
   c = sp->x_inClose[sp->i & sp->xMask];
   if( o > 0.0 && h > 0.0 && l > 0.0 && c > 0.0 )
   {
      p1 = log(h / c) * log(h / o);
      p2 = log(l / c) * log(l / o);
      term = p1 + p2;
   } else 
   {
      term = 0.0;
   }
   sp->periodTotal += term;
   sp->peakTotal = (sp->periodTotal > sp->peakTotal) ? sp->periodTotal : sp->peakTotal;
   /* The sum this bar's output is taken from, before the trailing term is
    * removed for the next one.
    */
   windowTotal = sp->periodTotal;
   o = sp->x_inOpen[sp->trailingIdx & sp->xMask];
   h = sp->x_inHigh[sp->trailingIdx & sp->xMask];
   l = sp->x_inLow[sp->trailingIdx & sp->xMask];
   c = sp->x_inClose[sp->trailingIdx & sp->xMask];
   if( o > 0.0 && h > 0.0 && l > 0.0 && c > 0.0 )
   {
      p1 = log(h / c) * log(h / o);
      p2 = log(l / c) * log(l / o);
      term = p1 + p2;
   } else 
   {
      term = 0.0;
   }
   sp->periodTotal -= term;
   sp->trailingIdx += 1;
   /* Rebuild as a fresh window sum when the running sum has collapsed to
    * below 1e-6 of the largest it has held since the last rebuild, or at
    * least every 32 windows -- VAR's rule (var.c:101-113). Measured against
    * the PEAK, not the current sum: what a running sum of add-then-subtract
    * carries is rounding at the scale of the largest window it has seen, so
    * once a quiet stretch arrives the current sum can be nothing but that
    * rounding. On an all-flat window the rebuild restores an exact 0.0,
    * where a plain running sum leaves a residual that is negative about
    * forty per cent of the time -- and a negative sum under an
    * unconditional root is where the composition of shipped functions
    * produces NaN.
    */
   sp->barsSinceRebuild -= 1;
   if( windowTotal < 0.000001 * sp->peakTotal || sp->barsSinceRebuild <= 0 )
   {
      sp->barsSinceRebuild = 32 * sp->optInTimePeriod;
      sp->windowStart = sp->i - sp->nbInitialElementNeeded;
      windowTotal = 0.0;
      for( sp->j = sp->windowStart; sp->j <= sp->i; sp->j += 1 )
      {
         o = sp->x_inOpen[sp->j & sp->xMask];
         h = sp->x_inHigh[sp->j & sp->xMask];
         l = sp->x_inLow[sp->j & sp->xMask];
         c = sp->x_inClose[sp->j & sp->xMask];
         if( o > 0.0 && h > 0.0 && l > 0.0 && c > 0.0 )
         {
            p1 = log(h / c) * log(h / o);
            p2 = log(l / c) * log(l / o);
            term = p1 + p2;
         } else 
         {
            term = 0.0;
         }
         windowTotal += term;
      }
      /* The rebuilt window becomes the carried state, with its trailing
       * term removed again so the two paths leave the same thing behind.
       */
      sp->periodTotal = windowTotal;
      sp->peakTotal = windowTotal;
      o = sp->x_inOpen[sp->windowStart & sp->xMask];
      h = sp->x_inHigh[sp->windowStart & sp->xMask];
      l = sp->x_inLow[sp->windowStart & sp->xMask];
      c = sp->x_inClose[sp->windowStart & sp->xMask];
      if( o > 0.0 && h > 0.0 && l > 0.0 && c > 0.0 )
      {
         p1 = log(h / c) * log(h / o);
         p2 = log(l / c) * log(l / o);
         term = p1 + p2;
      } else 
      {
         term = 0.0;
      }
      sp->periodTotal -= term;
   }
   /* The divide, then the root, then the scale -- the spelling every
    * implementation of this estimator uses, and what makes A = 1.0 exact.
    *
    * A sum at or below zero answers 0.0 rather than reaching the root. A
    * fresh sum of terms from consistent bars cannot be negative, so this
    * only catches a bar whose high or low sits strictly inside its open and
    * close, which is not a bar the estimator is defined on. VAR floors its
    * variance for the same reason, so that STDDEV can root it
    * unconditionally (var.c:165-166).
    */
   if( windowTotal > 0.0 )
   {
      *outReal= sp->sqrtA * sqrt(windowTotal / (double)sp->optInTimePeriod);
   } else 
   {
      *outReal= 0.0;
   }
   sp->i += 1;
   sp->cur_outReal = *outReal;
}

static TA_RetCode TA_ROGERSSATCHELL_OpenImpl( struct TA_ROGERSSATCHELL_Stream **stream, const double inOpen[], const double inHigh[], const double inLow[], const double inClose[], int startIdx, int historyLen, int optInTimePeriod, double optInAnnualization, int *outBegIdx, int *outNBElement, double outReal[], int outStride )
{
   struct TA_ROGERSSATCHELL_Stream *sp;
   int endIdx;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_INDEX_MAX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inOpen || !inHigh || !inLow || !inClose || !outReal ) return TA_BAD_PARAM;
   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 10;
   else if( (int)optInTimePeriod < 1 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( optInAnnualization == TA_REAL_DEFAULT )
      optInAnnualization = 252;
   else if( !(optInAnnualization >= 0e0 && optInAnnualization <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( startIdx > historyLen - 1 )
   {
      *outBegIdx = 0;
      *outNBElement = 0;
      return TA_INSUFFICIENT_HISTORY;
   }

   endIdx = historyLen - 1;

   {
      double o;
      double h;
      double l;
      double c;
      double p1;
      double p2;
      double term;
      double periodTotal = 0.0;
      double windowTotal;
      double peakTotal = 0.0;
      double sqrtA = 0.0;
      int i = 0;
      int j = 0;
      int outIdx;
      int trailingIdx = 0;
      int windowStart = 0;
      int nbInitialElementNeeded = 0;
      int barsSinceRebuild = 0;
      nbInitialElementNeeded = optInTimePeriod - 1;
      if( startIdx < nbInitialElementNeeded )
      {
         startIdx = nbInitialElementNeeded;
      }
      if( startIdx > endIdx )
      {
         *outBegIdx= 0;
         *outNBElement= 0;
         return TA_INSUFFICIENT_HISTORY;
      }
      /* Rogers and Satchell, The Annals of Applied Probability 1(4):504-512 (1991),
       * eq. (2) on p.505: with the log price measured from the bar's open,
       * S1 = ln(H/O), I1 = ln(L/O) and X1 = ln(C/O), one bar's unbiased estimate
       * of its variance is S1(S1 - X1) + I1(I1 - X1), which is ln(H/C)ln(H/O) +
       * ln(L/C)ln(L/O). Eq. (3) is what sets this estimator apart: that
       * expectation is sigma^2 whatever the drift, so a bar that opens at its low
       * and closes at its high -- all drift, no dispersion -- reads exactly zero,
       * where a range-only estimator reads volatility.
       *
       * The paper stops there. The window mean, the root and the annual scale are
       * the convention of every implementation of it, not the authors'.
       */
      /* Once, so that optInAnnualization = 1.0 is an exact identity rather than a
       * multiply by a rounded 1.0, and so the per-bar and annualised outputs
       * differ by exactly this factor.
       */
      sqrtA = sqrt(optInAnnualization);
      trailingIdx = startIdx - nbInitialElementNeeded;
      periodTotal = 0.0;
      for( j = trailingIdx; j < startIdx; j += 1 )
      {
         /* The two products are SEPARATE statements on purpose. Written as one
          * expression the generator's FMA detector fuses the first product into
          * the add (backends/fma.rs:406-433; a log call counts as a float factor
          * at :252-285), which moves 159 of 243 outputs on the corpus at n = 10
          * and buys nothing measurable. VWMA splits its product for the same
          * reason (vwma/vwma.c:78-81).
          *
          * The guard is the whole bar, tested exactly rather than against a fixed
          * band (#253): a bar with any price at or below zero contributes a 0.0
          * term and still counts toward the window's n. Zeroing only the products
          * that touch the bad price has no implementation behind it, and dropping
          * the bar from the window makes n data-dependent.
          */
         o = inOpen[j];
         h = inHigh[j];
         l = inLow[j];
         c = inClose[j];
         if( o > 0.0 && h > 0.0 && l > 0.0 && c > 0.0 )
         {
            p1 = log(h / c) * log(h / o);
            p2 = log(l / c) * log(l / o);
            term = p1 + p2;
         } else 
         {
            term = 0.0;
         }
         periodTotal += term;
      }
      /* outReal may be any of the four input arrays: the output written on a bar
       * lands at or before the window's own trailing index, so every input slot
       * this loop still reads is one no write has reached yet.
       */
      i = startIdx;
      outIdx = 0;
      barsSinceRebuild = 32 * optInTimePeriod;
      peakTotal = periodTotal;
      do
      {
         o = inOpen[i];
         h = inHigh[i];
         l = inLow[i];
         c = inClose[i];
         if( o > 0.0 && h > 0.0 && l > 0.0 && c > 0.0 )
         {
            p1 = log(h / c) * log(h / o);
            p2 = log(l / c) * log(l / o);
            term = p1 + p2;
         } else 
         {
            term = 0.0;
         }
         periodTotal += term;
         peakTotal = (periodTotal > peakTotal) ? periodTotal : peakTotal;
         /* The sum this bar's output is taken from, before the trailing term is
          * removed for the next one.
          */
         windowTotal = periodTotal;
         o = inOpen[trailingIdx];
         h = inHigh[trailingIdx];
         l = inLow[trailingIdx];
         c = inClose[trailingIdx];
         if( o > 0.0 && h > 0.0 && l > 0.0 && c > 0.0 )
         {
            p1 = log(h / c) * log(h / o);
            p2 = log(l / c) * log(l / o);
            term = p1 + p2;
         } else 
         {
            term = 0.0;
         }
         periodTotal -= term;
         trailingIdx += 1;
         /* Rebuild as a fresh window sum when the running sum has collapsed to
          * below 1e-6 of the largest it has held since the last rebuild, or at
          * least every 32 windows -- VAR's rule (var.c:101-113). Measured against
          * the PEAK, not the current sum: what a running sum of add-then-subtract
          * carries is rounding at the scale of the largest window it has seen, so
          * once a quiet stretch arrives the current sum can be nothing but that
          * rounding. On an all-flat window the rebuild restores an exact 0.0,
          * where a plain running sum leaves a residual that is negative about
          * forty per cent of the time -- and a negative sum under an
          * unconditional root is where the composition of shipped functions
          * produces NaN.
          */
         barsSinceRebuild -= 1;
         if( windowTotal < 0.000001 * peakTotal || barsSinceRebuild <= 0 )
         {
            barsSinceRebuild = 32 * optInTimePeriod;
            windowStart = i - nbInitialElementNeeded;
            windowTotal = 0.0;
            for( j = windowStart; j <= i; j += 1 )
            {
               o = inOpen[j];
               h = inHigh[j];
               l = inLow[j];
               c = inClose[j];
               if( o > 0.0 && h > 0.0 && l > 0.0 && c > 0.0 )
               {
                  p1 = log(h / c) * log(h / o);
                  p2 = log(l / c) * log(l / o);
                  term = p1 + p2;
               } else 
               {
                  term = 0.0;
               }
               windowTotal += term;
            }
            /* The rebuilt window becomes the carried state, with its trailing
             * term removed again so the two paths leave the same thing behind.
             */
            periodTotal = windowTotal;
            peakTotal = windowTotal;
            o = inOpen[windowStart];
            h = inHigh[windowStart];
            l = inLow[windowStart];
            c = inClose[windowStart];
            if( o > 0.0 && h > 0.0 && l > 0.0 && c > 0.0 )
            {
               p1 = log(h / c) * log(h / o);
               p2 = log(l / c) * log(l / o);
               term = p1 + p2;
            } else 
            {
               term = 0.0;
            }
            periodTotal -= term;
         }
         /* The divide, then the root, then the scale -- the spelling every
          * implementation of this estimator uses, and what makes A = 1.0 exact.
          *
          * A sum at or below zero answers 0.0 rather than reaching the root. A
          * fresh sum of terms from consistent bars cannot be negative, so this
          * only catches a bar whose high or low sits strictly inside its open and
          * close, which is not a bar the estimator is defined on. VAR floors its
          * variance for the same reason, so that STDDEV can root it
          * unconditionally (var.c:165-166).
          */
         if( windowTotal > 0.0 )
         {
            outReal[outIdx * outStride] = sqrtA * sqrt(windowTotal / (double)optInTimePeriod);
         } else 
         {
            outReal[outIdx * outStride] = 0.0;
         }
         outIdx = outIdx + 1;
         i += 1;
      } while( i <= endIdx );
      *outNBElement= outIdx;
      *outBegIdx= startIdx;

      /* Capture the live batch state into the handle. */
      sp = (struct TA_ROGERSSATCHELL_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) { return TA_ALLOC_ERR; }
      memset( sp, 0, sizeof(*sp) );
      sp->optInTimePeriod = optInTimePeriod;
      sp->optInAnnualization = optInAnnualization;
      sp->periodTotal = periodTotal;
      sp->peakTotal = peakTotal;
      sp->sqrtA = sqrtA;
      sp->trailingIdx = trailingIdx;
      sp->nbInitialElementNeeded = nbInitialElementNeeded;
      sp->barsSinceRebuild = barsSinceRebuild;
      sp->j = j;
      sp->windowStart = windowStart;
      sp->i = i;
      sp->xCap = (int)(i - trailingIdx) + 1;
      if( sp->xCap < 1 || sp->xCap > historyLen ) { TA_ROGERSSATCHELL_ReleaseImpl( sp ); return TA_INTERNAL_ERROR(483); }
      sp->xPhys = 1;
      while( sp->xPhys < sp->xCap ) sp->xPhys <<= 1;
      sp->xMask = sp->xPhys - 1;
      sp->x_inOpen = (double *)TA_Malloc( sizeof(double) * (size_t)sp->xPhys );
      if( !sp->x_inOpen ) { TA_ROGERSSATCHELL_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
      sp->x_inHigh = (double *)TA_Malloc( sizeof(double) * (size_t)sp->xPhys );
      if( !sp->x_inHigh ) { TA_ROGERSSATCHELL_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
      sp->x_inLow = (double *)TA_Malloc( sizeof(double) * (size_t)sp->xPhys );
      if( !sp->x_inLow ) { TA_ROGERSSATCHELL_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
      sp->x_inClose = (double *)TA_Malloc( sizeof(double) * (size_t)sp->xPhys );
      if( !sp->x_inClose ) { TA_ROGERSSATCHELL_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
      { int fillJ;
        for( fillJ = historyLen - sp->xCap; fillJ < historyLen; fillJ++ )
        {
           sp->x_inOpen[fillJ & sp->xMask] = inOpen[fillJ];
           sp->x_inHigh[fillJ & sp->xMask] = inHigh[fillJ];
           sp->x_inLow[fillJ & sp->xMask] = inLow[fillJ];
           sp->x_inClose[fillJ & sp->xMask] = inClose[fillJ];
        }
      }
      sp->outRangeBegIdx = *outBegIdx;
      sp->outRangeCount = *outNBElement;
      sp->cur_outReal = outReal[(*outNBElement - 1) * outStride];
      *stream = sp;
      return TA_SUCCESS;
   }
}

/* Private function, not in public API. */
TA_RetCode TA_ROGERSSATCHELL_OpenInternal( struct TA_ROGERSSATCHELL_Stream **stream, const double inOpen[], const double inHigh[], const double inLow[], const double inClose[], int startIdx, int historyLen, int optInTimePeriod, double optInAnnualization, double *outReal )
{
   TA_RetCode retCode;
   int dummyBegIdx = 0;
   int dummyNBElement = 0;
   double sink_outReal = 0.0;
   retCode = TA_ROGERSSATCHELL_OpenImpl( stream, inOpen, inHigh, inLow, inClose, startIdx, historyLen, optInTimePeriod, optInAnnualization, &dummyBegIdx, &dummyNBElement, &sink_outReal, 0 );
   if( retCode == TA_SUCCESS )
   {
      *outReal = sink_outReal;
   }
   return retCode;
}

TA_LIB_API TA_RetCode TA_ROGERSSATCHELL_Open( TA_ROGERSSATCHELL_Stream **stream, const double inOpen[], const double inHigh[], const double inLow[], const double inClose[], int historyLen, int optInTimePeriod, double optInAnnualization, double *outReal )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_INDEX_MAX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inOpen || !inHigh || !inLow || !inClose || !outReal ) return TA_BAD_PARAM;
   return TA_ROGERSSATCHELL_OpenInternal( stream, inOpen, inHigh, inLow, inClose, 0, historyLen, optInTimePeriod, optInAnnualization, outReal );
}

TA_LIB_API TA_RetCode TA_ROGERSSATCHELL_OpenAndFill( TA_ROGERSSATCHELL_Stream **stream, const double inOpen[], const double inHigh[], const double inLow[], const double inClose[], int historyLen, int optInTimePeriod, double optInAnnualization, int *outBegIdx, int *outNBElement, double outReal[] )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_INDEX_MAX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inOpen || !inHigh || !inLow || !inClose || !outBegIdx || !outNBElement || !outReal ) return TA_BAD_PARAM;
   if( (const void *)outReal == (const void *)inOpen || (const void *)outReal == (const void *)inHigh || (const void *)outReal == (const void *)inLow || (const void *)outReal == (const void *)inClose ) return TA_BAD_PARAM;
   return TA_ROGERSSATCHELL_OpenAndFillInternal( stream, inOpen, inHigh, inLow, inClose, 0, historyLen, optInTimePeriod, optInAnnualization, outBegIdx, outNBElement, outReal );
}

/* Private function, not in public API. */
TA_RetCode TA_ROGERSSATCHELL_OpenAndFillInternal( struct TA_ROGERSSATCHELL_Stream **stream, const double inOpen[], const double inHigh[], const double inLow[], const double inClose[], int startIdx, int historyLen, int optInTimePeriod, double optInAnnualization, int *outBegIdx, int *outNBElement, double outReal[] )
{
   return TA_ROGERSSATCHELL_OpenImpl( stream, inOpen, inHigh, inLow, inClose, startIdx, historyLen, optInTimePeriod, optInAnnualization, outBegIdx, outNBElement, outReal, 1 );
}

TA_LIB_API TA_RetCode TA_ROGERSSATCHELL_Update( TA_ROGERSSATCHELL_Stream *stream, double inOpen, double inHigh, double inLow, double inClose, double *outReal )
{
   if( !stream ) return TA_BAD_PARAM;
   if( stream->outRangeBegIdx + stream->outRangeCount > TA_INDEX_MAX )
      return TA_OUT_OF_RANGE_END_INDEX;
   if( !outReal ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inOpen ) || !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) || !TA_IS_FINITE( inClose ) ) return TA_BAD_PARAM;
   TA_ROGERSSATCHELL_StepImpl( stream, inOpen, inHigh, inLow, inClose, outReal );
   stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_ROGERSSATCHELL_Peek( const TA_ROGERSSATCHELL_Stream *stream, double inOpen, double inHigh, double inLow, double inClose, double *outReal )
{
   const struct TA_ROGERSSATCHELL_Stream *sp = stream;
   double o;
   double h;
   double l;
   double c;
   double p1;
   double p2;
   double term;
   double windowTotal;
   int barsSinceRebuild;
   int j;
   double peakTotal;
   double periodTotal;
   int trailingIdx;
   int windowStart;
   double *x_inClose;
   double *x_inHigh;
   double *x_inLow;
   double *x_inOpen;
   int pkSlot0 = -1;
   double pkVal0 = 0.0;
   int pkSlot1 = -1;
   double pkVal1 = 0.0;
   int pkSlot2 = -1;
   double pkVal2 = 0.0;
   int pkSlot3 = -1;
   double pkVal3 = 0.0;

   if( !stream || !outReal ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inOpen ) || !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) || !TA_IS_FINITE( inClose ) ) return TA_BAD_PARAM;
   barsSinceRebuild = sp->barsSinceRebuild;
   j = sp->j;
   peakTotal = sp->peakTotal;
   periodTotal = sp->periodTotal;
   trailingIdx = sp->trailingIdx;
   windowStart = sp->windowStart;
   x_inClose = sp->x_inClose;
   x_inHigh = sp->x_inHigh;
   x_inLow = sp->x_inLow;
   x_inOpen = sp->x_inOpen;
   pkSlot0 = sp->i & sp->xMask;
   pkVal0 = inOpen;
   pkSlot1 = sp->i & sp->xMask;
   pkVal1 = inHigh;
   pkSlot2 = sp->i & sp->xMask;
   pkVal2 = inLow;
   pkSlot3 = sp->i & sp->xMask;
   pkVal3 = inClose;
   o = ((sp->i & sp->xMask) != pkSlot0) ? x_inOpen[sp->i & sp->xMask] : pkVal0;
   h = ((sp->i & sp->xMask) != pkSlot1) ? x_inHigh[sp->i & sp->xMask] : pkVal1;
   l = ((sp->i & sp->xMask) != pkSlot2) ? x_inLow[sp->i & sp->xMask] : pkVal2;
   c = ((sp->i & sp->xMask) != pkSlot3) ? x_inClose[sp->i & sp->xMask] : pkVal3;
   if( o > 0.0 && h > 0.0 && l > 0.0 && c > 0.0 )
   {
      p1 = log(h / c) * log(h / o);
      p2 = log(l / c) * log(l / o);
      term = p1 + p2;
   } else 
   {
      term = 0.0;
   }
   periodTotal += term;
   peakTotal = (periodTotal > peakTotal) ? periodTotal : peakTotal;
   /* The sum this bar's output is taken from, before the trailing term is
    * removed for the next one.
    */
   windowTotal = periodTotal;
   o = ((trailingIdx & sp->xMask) != pkSlot0) ? x_inOpen[trailingIdx & sp->xMask] : pkVal0;
   h = ((trailingIdx & sp->xMask) != pkSlot1) ? x_inHigh[trailingIdx & sp->xMask] : pkVal1;
   l = ((trailingIdx & sp->xMask) != pkSlot2) ? x_inLow[trailingIdx & sp->xMask] : pkVal2;
   c = ((trailingIdx & sp->xMask) != pkSlot3) ? x_inClose[trailingIdx & sp->xMask] : pkVal3;
   if( o > 0.0 && h > 0.0 && l > 0.0 && c > 0.0 )
   {
      p1 = log(h / c) * log(h / o);
      p2 = log(l / c) * log(l / o);
      term = p1 + p2;
   } else 
   {
      term = 0.0;
   }
   periodTotal -= term;
   trailingIdx += 1;
   /* Rebuild as a fresh window sum when the running sum has collapsed to
    * below 1e-6 of the largest it has held since the last rebuild, or at
    * least every 32 windows -- VAR's rule (var.c:101-113). Measured against
    * the PEAK, not the current sum: what a running sum of add-then-subtract
    * carries is rounding at the scale of the largest window it has seen, so
    * once a quiet stretch arrives the current sum can be nothing but that
    * rounding. On an all-flat window the rebuild restores an exact 0.0,
    * where a plain running sum leaves a residual that is negative about
    * forty per cent of the time -- and a negative sum under an
    * unconditional root is where the composition of shipped functions
    * produces NaN.
    */
   barsSinceRebuild -= 1;
   if( windowTotal < 0.000001 * peakTotal || barsSinceRebuild <= 0 )
   {
      barsSinceRebuild = 32 * sp->optInTimePeriod;
      windowStart = sp->i - sp->nbInitialElementNeeded;
      windowTotal = 0.0;
      for( j = windowStart; j <= sp->i; j += 1 )
      {
         o = ((j & sp->xMask) != pkSlot0) ? x_inOpen[j & sp->xMask] : pkVal0;
         h = ((j & sp->xMask) != pkSlot1) ? x_inHigh[j & sp->xMask] : pkVal1;
         l = ((j & sp->xMask) != pkSlot2) ? x_inLow[j & sp->xMask] : pkVal2;
         c = ((j & sp->xMask) != pkSlot3) ? x_inClose[j & sp->xMask] : pkVal3;
         if( o > 0.0 && h > 0.0 && l > 0.0 && c > 0.0 )
         {
            p1 = log(h / c) * log(h / o);
            p2 = log(l / c) * log(l / o);
            term = p1 + p2;
         } else 
         {
            term = 0.0;
         }
         windowTotal += term;
      }
      /* The rebuilt window becomes the carried state, with its trailing
       * term removed again so the two paths leave the same thing behind.
       */
      periodTotal = windowTotal;
      peakTotal = windowTotal;
      o = ((windowStart & sp->xMask) != pkSlot0) ? x_inOpen[windowStart & sp->xMask] : pkVal0;
      h = ((windowStart & sp->xMask) != pkSlot1) ? x_inHigh[windowStart & sp->xMask] : pkVal1;
      l = ((windowStart & sp->xMask) != pkSlot2) ? x_inLow[windowStart & sp->xMask] : pkVal2;
      c = ((windowStart & sp->xMask) != pkSlot3) ? x_inClose[windowStart & sp->xMask] : pkVal3;
      if( o > 0.0 && h > 0.0 && l > 0.0 && c > 0.0 )
      {
         p1 = log(h / c) * log(h / o);
         p2 = log(l / c) * log(l / o);
         term = p1 + p2;
      } else 
      {
         term = 0.0;
      }
      periodTotal -= term;
   }
   /* The divide, then the root, then the scale -- the spelling every
    * implementation of this estimator uses, and what makes A = 1.0 exact.
    *
    * A sum at or below zero answers 0.0 rather than reaching the root. A
    * fresh sum of terms from consistent bars cannot be negative, so this
    * only catches a bar whose high or low sits strictly inside its open and
    * close, which is not a bar the estimator is defined on. VAR floors its
    * variance for the same reason, so that STDDEV can root it
    * unconditionally (var.c:165-166).
    */
   if( windowTotal > 0.0 )
   {
      *outReal= sp->sqrtA * sqrt(windowTotal / (double)sp->optInTimePeriod);
   } else 
   {
      *outReal= 0.0;
   }
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_ROGERSSATCHELL_Close( TA_ROGERSSATCHELL_Stream *stream )
{
   TA_ROGERSSATCHELL_ReleaseImpl( stream );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_ROGERSSATCHELL_Value( const TA_ROGERSSATCHELL_Stream *stream, double *outReal )
{
   if( !stream || !outReal ) return TA_BAD_PARAM;
   *outReal = stream->cur_outReal;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_ROGERSSATCHELL_OutRange( const TA_ROGERSSATCHELL_Stream *stream, int *outBegIdx, int *outNBElement )
{
   if( !stream || !outBegIdx || !outNBElement ) return TA_BAD_PARAM;
   *outBegIdx = stream->outRangeBegIdx;
   *outNBElement = stream->outRangeCount;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_ROGERSSATCHELL_Advance( TA_ROGERSSATCHELL_Stream *stream )
{
   if( !stream ) return TA_BAD_PARAM;
   if( stream->outRangeBegIdx + stream->outRangeCount > TA_INDEX_MAX )
      return TA_OUT_OF_RANGE_END_INDEX;
   stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_ROGERSSATCHELL_Clone( const TA_ROGERSSATCHELL_Stream *stream, TA_ROGERSSATCHELL_Stream **clone )
{
   struct TA_ROGERSSATCHELL_Stream *sp;

   if( !clone ) return TA_BAD_PARAM;
   *clone = NULL;
   if( !stream ) return TA_BAD_PARAM;
   sp = (struct TA_ROGERSSATCHELL_Stream *)TA_Malloc( sizeof(*sp) );
   if( !sp ) return TA_ALLOC_ERR;
   *sp = *stream;
   sp->x_inOpen = NULL;
   sp->x_inHigh = NULL;
   sp->x_inLow = NULL;
   sp->x_inClose = NULL;
   if( stream->x_inOpen )
   { size_t copyN = (size_t)(sp->xPhys);
     sp->x_inOpen = (double *)TA_Malloc( sizeof(double) * copyN );
     if( !sp->x_inOpen ) { TA_ROGERSSATCHELL_Close( sp ); return TA_ALLOC_ERR; }
     memcpy( sp->x_inOpen, stream->x_inOpen, sizeof(double) * copyN ); }
   if( stream->x_inHigh )
   { size_t copyN = (size_t)(sp->xPhys);
     sp->x_inHigh = (double *)TA_Malloc( sizeof(double) * copyN );
     if( !sp->x_inHigh ) { TA_ROGERSSATCHELL_Close( sp ); return TA_ALLOC_ERR; }
     memcpy( sp->x_inHigh, stream->x_inHigh, sizeof(double) * copyN ); }
   if( stream->x_inLow )
   { size_t copyN = (size_t)(sp->xPhys);
     sp->x_inLow = (double *)TA_Malloc( sizeof(double) * copyN );
     if( !sp->x_inLow ) { TA_ROGERSSATCHELL_Close( sp ); return TA_ALLOC_ERR; }
     memcpy( sp->x_inLow, stream->x_inLow, sizeof(double) * copyN ); }
   if( stream->x_inClose )
   { size_t copyN = (size_t)(sp->xPhys);
     sp->x_inClose = (double *)TA_Malloc( sizeof(double) * copyN );
     if( !sp->x_inClose ) { TA_ROGERSSATCHELL_Close( sp ); return TA_ALLOC_ERR; }
     memcpy( sp->x_inClose, stream->x_inClose, sizeof(double) * copyN ); }
   *clone = sp;
   return TA_SUCCESS;
}

