/* TA-LIB Copyright (c) 1999-2026, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_stream_private.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  MF       Mario Fortier
 *  CC       Claude Code (AI assistant)
 *
 * Change history:
 *
 *  MMDDYY BY     Description
 *  -------------------------------------------------------------------
 *  082026 MF,CC  Initial version (#238).
 */

TA_LIB_API int TA_SMI_Lookback( int optInTimePeriod, int optInFastPeriod, int optInSlowPeriod, int optInSignalPeriod )
{
   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 13;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return -1;
   if( (int)optInFastPeriod == TA_INTEGER_DEFAULT )
      optInFastPeriod = 2;
   else if( (int)optInFastPeriod < 2 || (int)optInFastPeriod > 100000 )
      return -1;
   if( (int)optInSlowPeriod == TA_INTEGER_DEFAULT )
      optInSlowPeriod = 25;
   else if( (int)optInSlowPeriod < 2 || (int)optInSlowPeriod > 100000 )
      return -1;
   if( (int)optInSignalPeriod == TA_INTEGER_DEFAULT )
      optInSignalPeriod = 9;
   else if( (int)optInSignalPeriod < 2 || (int)optInSignalPeriod > 100000 )
      return -1;
   /* One high/low window, then the three EMA warm-ups the pipeline stacks on
    * top of it: slow smooths the raw momentum, fast smooths that, and signal
    * smooths the finished SMI line. Every term is exactly the lookback of the
    * function it comes from, so none of them is restated here -- which is also
    * what makes SMI inherit TA_FUNC_UNST_EMA from its callee.
    */
   return optInTimePeriod - 1 + TA_EMA_Lookback(optInSlowPeriod) + TA_EMA_Lookback(optInFastPeriod) + TA_EMA_Lookback(optInSignalPeriod);
}

TA_FMA_MULTIVERSION
TA_LIB_API TA_RetCode TA_SMI( int    startIdx,
                              int    endIdx,
                              const double inHigh[],
                              const double inLow[],
                              const double inClose[],
                              int optInTimePeriod,
                              int optInFastPeriod,
                              int optInSlowPeriod,
                              int optInSignalPeriod,
                              int          *outBegIdx,
                              int          *outNBElement,
                              double        outSMI[],
                              double        outSMISignal[] )
{
   double kSlow;
   double kFast;
   double kSignal;
   double highest;
   double lowest;
   double tmp;
   double emaSlowNum;
   double emaSlowDen;
   double emaFastNum;
   double emaFastDen;
   double sumSlowNum;
   double sumSlowDen;
   double sumFastNum;
   double sumFastDen;
   double sumSignal;
   double num;
   double den;
   double halfDen;
   double smiValue;
   double prevSignal;
   int lookbackTotal;
   int lookbackSlow;
   int lookbackFast;
   int today;
   int trailingIdx;
   int highestIdx;
   int lowestIdx;
   int i;
   int outIdx;
   int nBar;
   int nFast;
   int nSignal;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !inClose )
      return TA_BAD_PARAM;
   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 13;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInFastPeriod == TA_INTEGER_DEFAULT )
      optInFastPeriod = 2;
   else if( (int)optInFastPeriod < 2 || (int)optInFastPeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInSlowPeriod == TA_INTEGER_DEFAULT )
      optInSlowPeriod = 25;
   else if( (int)optInSlowPeriod < 2 || (int)optInSlowPeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInSignalPeriod == TA_INTEGER_DEFAULT )
      optInSignalPeriod = 9;
   else if( (int)optInSignalPeriod < 2 || (int)optInSignalPeriod > 100000 )
      return TA_BAD_PARAM;
   if( !outSMI )
      return TA_BAD_PARAM;
   if( !outSMISignal )
      return TA_BAD_PARAM;
   if( outSMI == outSMISignal )
      return TA_BAD_PARAM;

   lookbackTotal = TA_SMI_Lookback(optInTimePeriod,optInFastPeriod,optInSlowPeriod,optInSignalPeriod);
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   *outBegIdx= startIdx;
   /* Blau's pipeline in one pass. A composed form is not available: the
    * streaming producer model carries exactly one intermediate series
    * (streaming.rs:2076) and SMI has two, the numerator and the denominator,
    * which must be smoothed separately before they are divided.
    *
    * Each of the three stages seeds the way ema.c does -- a simple average of
    * that stage's first 'period' inputs -- so the result is bit-identical to
    * TA_MAX + TA_MIN followed by four TA_EMA calls. The stage boundaries below
    * are the callee LOOKBACKS, not (period-1), so that a warm
    * TA_SetUnstablePeriod(TA_FUNC_UNST_EMA) folds in: each stage then seeds
    * from the values its predecessor would have published, exactly as the
    * composed form does. The seed sums accumulate from 0.0 in production
    * order; do not reorder or fuse them (0.0+x is not x for x=-0.0).
    *
    * TA_GetCompatibility() is deliberately NOT consulted, for the reason
    * spelled out in efi.c: ema.c's TA_COMPATIBILITY_METASTOCK seeding arm is
    * preserved for the functions that already shipped with it and dropped from
    * new ones, and it is not reachable at all from the Rust, Java and C# APIs.
    * The seeding choice itself is measured in docs/studies/ema-seeding/README.md.
    */
   kSlow = 2.0 / (double)(optInSlowPeriod + 1);
   kFast = 2.0 / (double)(optInFastPeriod + 1);
   kSignal = 2.0 / (double)(optInSignalPeriod + 1);
   lookbackSlow = TA_EMA_Lookback(optInSlowPeriod);
   lookbackFast = TA_EMA_Lookback(optInFastPeriod);
   emaSlowNum = 0.0;
   emaSlowDen = 0.0;
   emaFastNum = 0.0;
   emaFastDen = 0.0;
   prevSignal = 0.0;
   smiValue = 0.0;
   sumSlowNum = 0.0;
   sumSlowDen = 0.0;
   sumFastNum = 0.0;
   sumFastDen = 0.0;
   sumSignal = 0.0;
   highest = 0.0;
   lowest = 0.0;
   highestIdx = 0 - 1;
   lowestIdx = 0 - 1;
   /* The first bar carrying a full high/low window. */
   trailingIdx = startIdx - lookbackTotal;
   today = trailingIdx + (optInTimePeriod - 1);
   nBar = 0;
   /* Warm-up. Runs through startIdx inclusive: the last pass here is the one
    * that completes the signal seed, so it produces the first output pair.
    */
   while( today <= startIdx )
   {
      /* Set the lowest low */
      tmp = inLow[today];
      if( lowestIdx < trailingIdx )
      {
         lowestIdx = trailingIdx;
         lowest = inLow[lowestIdx];
         i = lowestIdx;
         while( ++i <= today )
         {
            tmp = inLow[i];
            if( tmp < lowest )
            {
               lowestIdx = i;
               lowest = tmp;
            }
         }
      } else if( tmp <= lowest )
      {
         lowestIdx = today;
         lowest = tmp;
      }
      /* Set the highest high */
      tmp = inHigh[today];
      if( highestIdx < trailingIdx )
      {
         highestIdx = trailingIdx;
         highest = inHigh[highestIdx];
         i = highestIdx;
         while( ++i <= today )
         {
            tmp = inHigh[i];
            if( tmp > highest )
            {
               highestIdx = i;
               highest = tmp;
            }
         }
      } else if( tmp >= highest )
      {
         highestIdx = today;
         highest = tmp;
      }
      den = highest - lowest;
      num = inClose[today] - (highest + lowest) * 0.5;
      /* Stage 1: the slow EMA, over the raw momentum. */
      if( nBar < optInSlowPeriod )
      {
         sumSlowNum = sumSlowNum + num;
         sumSlowDen = sumSlowDen + den;
         if( nBar == optInSlowPeriod - 1 )
         {
            emaSlowNum = sumSlowNum / optInSlowPeriod;
            emaSlowDen = sumSlowDen / optInSlowPeriod;
         }
      } else 
      {
         emaSlowNum = fma(num - emaSlowNum, kSlow, emaSlowNum);
         emaSlowDen = fma(den - emaSlowDen, kSlow, emaSlowDen);
      }
      /* Stage 2: the fast EMA, over what stage 1 publishes.
       *
       * The stage counters are compared BEFORE they are subtracted, never
       * after. Writing this as `nFast = nBar - lookbackSlow; if( nFast >= 0 )`
       * is correct in C, where the counters are signed, and broken everywhere
       * else: the Rust backend renders them as `usize`, so the subtraction
       * underflows for the first lookbackSlow bars -- a panic in a debug build
       * and a wrap in release. It would also be invisible to the cross-language
       * gate, which runs release servers at unstable period 0, where the branch
       * the wrap wrongly takes happens to be a no-op because both accumulators
       * are still 0.0.
       */
      if( nBar >= lookbackSlow )
      {
         nFast = nBar - lookbackSlow;
         if( nFast < optInFastPeriod )
         {
            sumFastNum = sumFastNum + emaSlowNum;
            sumFastDen = sumFastDen + emaSlowDen;
            if( nFast == optInFastPeriod - 1 )
            {
               emaFastNum = sumFastNum / optInFastPeriod;
               emaFastDen = sumFastDen / optInFastPeriod;
            }
         } else 
         {
            emaFastNum = fma(emaSlowNum - emaFastNum, kFast, emaFastNum);
            emaFastDen = fma(emaSlowDen - emaFastDen, kFast, emaFastDen);
         }
      }
      /* Stage 3: the SMI line, then the signal EMA over it. */
      if( nBar >= lookbackSlow + lookbackFast )
      {
         nSignal = nBar - lookbackSlow - lookbackFast;
         halfDen = 0.5 * emaFastDen;
         if( !TA_IS_ZERO(halfDen) )
         {
            smiValue = 100.0 * emaFastNum / halfDen;
         } else 
         {
            smiValue = 0.0;
         }
         if( nSignal < optInSignalPeriod )
         {
            sumSignal = sumSignal + smiValue;
            if( nSignal == optInSignalPeriod - 1 )
            {
               prevSignal = sumSignal / optInSignalPeriod;
            }
         } else 
         {
            prevSignal = fma(smiValue - prevSignal, kSignal, prevSignal);
         }
      }
      nBar = nBar + 1;
      trailingIdx = trailingIdx + 1;
      today = today + 1;
   }
   outSMI[0] = smiValue;
   outSMISignal[0] = prevSignal;
   outIdx = 1;
   /* Stable zone. Every stage is a pure recursion from here on. */
   while( today <= endIdx )
   {
      /* Set the lowest low */
      tmp = inLow[today];
      if( lowestIdx < trailingIdx )
      {
         lowestIdx = trailingIdx;
         lowest = inLow[lowestIdx];
         i = lowestIdx;
         while( ++i <= today )
         {
            tmp = inLow[i];
            if( tmp < lowest )
            {
               lowestIdx = i;
               lowest = tmp;
            }
         }
      } else if( tmp <= lowest )
      {
         lowestIdx = today;
         lowest = tmp;
      }
      /* Set the highest high */
      tmp = inHigh[today];
      if( highestIdx < trailingIdx )
      {
         highestIdx = trailingIdx;
         highest = inHigh[highestIdx];
         i = highestIdx;
         while( ++i <= today )
         {
            tmp = inHigh[i];
            if( tmp > highest )
            {
               highestIdx = i;
               highest = tmp;
            }
         }
      } else if( tmp >= highest )
      {
         highestIdx = today;
         highest = tmp;
      }
      den = highest - lowest;
      num = inClose[today] - (highest + lowest) * 0.5;
      emaSlowNum = fma(num - emaSlowNum, kSlow, emaSlowNum);
      emaSlowDen = fma(den - emaSlowDen, kSlow, emaSlowDen);
      emaFastNum = fma(emaSlowNum - emaFastNum, kFast, emaFastNum);
      emaFastDen = fma(emaSlowDen - emaFastDen, kFast, emaFastDen);
      /* Guard with TA_IS_ZERO, not an exact `halfDen != 0.0`: a machine-flat
       * window leaves a sub-epsilon residue that an exact check would divide
       * into noise (issue #107 / STOCHRSI). A window whose bars are all
       * H == L makes num zero too, so this is 0/0, and the neutral 0.0 is the
       * CCI (#7) and IMI (#112) convention.
       */
      halfDen = 0.5 * emaFastDen;
      if( !TA_IS_ZERO(halfDen) )
      {
         smiValue = 100.0 * emaFastNum / halfDen;
      } else 
      {
         smiValue = 0.0;
      }
      prevSignal = fma(smiValue - prevSignal, kSignal, prevSignal);
      outSMI[outIdx] = smiValue;
      outSMISignal[outIdx] = prevSignal;
      outIdx = outIdx + 1;
      trailingIdx = trailingIdx + 1;
      today = today + 1;
   }
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

TA_FMA_MULTIVERSION
TA_RetCode TA_S_SMI( int    startIdx,
                     int    endIdx,
                     const float inHigh[],
                     const float inLow[],
                     const float inClose[],
                     int optInTimePeriod,
                     int optInFastPeriod,
                     int optInSlowPeriod,
                     int optInSignalPeriod,
                     int          *outBegIdx,
                     int          *outNBElement,
                     double        outSMI[],
                     double        outSMISignal[] )
{
   double kSlow;
   double kFast;
   double kSignal;
   double highest;
   double lowest;
   double tmp;
   double emaSlowNum;
   double emaSlowDen;
   double emaFastNum;
   double emaFastDen;
   double sumSlowNum;
   double sumSlowDen;
   double sumFastNum;
   double sumFastDen;
   double sumSignal;
   double num;
   double den;
   double halfDen;
   double smiValue;
   double prevSignal;
   int lookbackTotal;
   int lookbackSlow;
   int lookbackFast;
   int today;
   int trailingIdx;
   int highestIdx;
   int lowestIdx;
   int i;
   int outIdx;
   int nBar;
   int nFast;
   int nSignal;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !inClose )
      return TA_BAD_PARAM;
   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 13;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInFastPeriod == TA_INTEGER_DEFAULT )
      optInFastPeriod = 2;
   else if( (int)optInFastPeriod < 2 || (int)optInFastPeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInSlowPeriod == TA_INTEGER_DEFAULT )
      optInSlowPeriod = 25;
   else if( (int)optInSlowPeriod < 2 || (int)optInSlowPeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInSignalPeriod == TA_INTEGER_DEFAULT )
      optInSignalPeriod = 9;
   else if( (int)optInSignalPeriod < 2 || (int)optInSignalPeriod > 100000 )
      return TA_BAD_PARAM;
   if( !outSMI )
      return TA_BAD_PARAM;
   if( !outSMISignal )
      return TA_BAD_PARAM;
   if( outSMI == outSMISignal )
      return TA_BAD_PARAM;

   lookbackTotal = TA_SMI_Lookback(optInTimePeriod,optInFastPeriod,optInSlowPeriod,optInSignalPeriod);
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   *outBegIdx= startIdx;
   kSlow = 2.0 / (double)(optInSlowPeriod + 1);
   kFast = 2.0 / (double)(optInFastPeriod + 1);
   kSignal = 2.0 / (double)(optInSignalPeriod + 1);
   lookbackSlow = TA_EMA_Lookback(optInSlowPeriod);
   lookbackFast = TA_EMA_Lookback(optInFastPeriod);
   emaSlowNum = 0.0;
   emaSlowDen = 0.0;
   emaFastNum = 0.0;
   emaFastDen = 0.0;
   prevSignal = 0.0;
   smiValue = 0.0;
   sumSlowNum = 0.0;
   sumSlowDen = 0.0;
   sumFastNum = 0.0;
   sumFastDen = 0.0;
   sumSignal = 0.0;
   highest = 0.0;
   lowest = 0.0;
   highestIdx = 0 - 1;
   lowestIdx = 0 - 1;
   trailingIdx = startIdx - lookbackTotal;
   today = trailingIdx + (optInTimePeriod - 1);
   nBar = 0;
   while( today <= startIdx )
   {
      tmp = (double)inLow[today];
      if( lowestIdx < trailingIdx )
      {
         lowestIdx = trailingIdx;
         lowest = (double)inLow[lowestIdx];
         i = lowestIdx;
         while( ++i <= today )
         {
            tmp = (double)inLow[i];
            if( tmp < lowest )
            {
               lowestIdx = i;
               lowest = tmp;
            }
         }
      } else if( tmp <= lowest )
      {
         lowestIdx = today;
         lowest = tmp;
      }
      tmp = (double)inHigh[today];
      if( highestIdx < trailingIdx )
      {
         highestIdx = trailingIdx;
         highest = (double)inHigh[highestIdx];
         i = highestIdx;
         while( ++i <= today )
         {
            tmp = (double)inHigh[i];
            if( tmp > highest )
            {
               highestIdx = i;
               highest = tmp;
            }
         }
      } else if( tmp >= highest )
      {
         highestIdx = today;
         highest = tmp;
      }
      den = highest - lowest;
      num = (double)inClose[today] - (highest + lowest) * 0.5;
      if( nBar < optInSlowPeriod )
      {
         sumSlowNum = sumSlowNum + num;
         sumSlowDen = sumSlowDen + den;
         if( nBar == optInSlowPeriod - 1 )
         {
            emaSlowNum = sumSlowNum / optInSlowPeriod;
            emaSlowDen = sumSlowDen / optInSlowPeriod;
         }
      } else 
      {
         emaSlowNum = fma(num - emaSlowNum, kSlow, emaSlowNum);
         emaSlowDen = fma(den - emaSlowDen, kSlow, emaSlowDen);
      }
      if( nBar >= lookbackSlow )
      {
         nFast = nBar - lookbackSlow;
         if( nFast < optInFastPeriod )
         {
            sumFastNum = sumFastNum + emaSlowNum;
            sumFastDen = sumFastDen + emaSlowDen;
            if( nFast == optInFastPeriod - 1 )
            {
               emaFastNum = sumFastNum / optInFastPeriod;
               emaFastDen = sumFastDen / optInFastPeriod;
            }
         } else 
         {
            emaFastNum = fma(emaSlowNum - emaFastNum, kFast, emaFastNum);
            emaFastDen = fma(emaSlowDen - emaFastDen, kFast, emaFastDen);
         }
      }
      if( nBar >= lookbackSlow + lookbackFast )
      {
         nSignal = nBar - lookbackSlow - lookbackFast;
         halfDen = 0.5 * emaFastDen;
         if( !TA_IS_ZERO(halfDen) )
         {
            smiValue = 100.0 * emaFastNum / halfDen;
         } else 
         {
            smiValue = 0.0;
         }
         if( nSignal < optInSignalPeriod )
         {
            sumSignal = sumSignal + smiValue;
            if( nSignal == optInSignalPeriod - 1 )
            {
               prevSignal = sumSignal / optInSignalPeriod;
            }
         } else 
         {
            prevSignal = fma(smiValue - prevSignal, kSignal, prevSignal);
         }
      }
      nBar = nBar + 1;
      trailingIdx = trailingIdx + 1;
      today = today + 1;
   }
   outSMI[0] = smiValue;
   outSMISignal[0] = prevSignal;
   outIdx = 1;
   while( today <= endIdx )
   {
      tmp = (double)inLow[today];
      if( lowestIdx < trailingIdx )
      {
         lowestIdx = trailingIdx;
         lowest = (double)inLow[lowestIdx];
         i = lowestIdx;
         while( ++i <= today )
         {
            tmp = (double)inLow[i];
            if( tmp < lowest )
            {
               lowestIdx = i;
               lowest = tmp;
            }
         }
      } else if( tmp <= lowest )
      {
         lowestIdx = today;
         lowest = tmp;
      }
      tmp = (double)inHigh[today];
      if( highestIdx < trailingIdx )
      {
         highestIdx = trailingIdx;
         highest = (double)inHigh[highestIdx];
         i = highestIdx;
         while( ++i <= today )
         {
            tmp = (double)inHigh[i];
            if( tmp > highest )
            {
               highestIdx = i;
               highest = tmp;
            }
         }
      } else if( tmp >= highest )
      {
         highestIdx = today;
         highest = tmp;
      }
      den = highest - lowest;
      num = (double)inClose[today] - (highest + lowest) * 0.5;
      emaSlowNum = fma(num - emaSlowNum, kSlow, emaSlowNum);
      emaSlowDen = fma(den - emaSlowDen, kSlow, emaSlowDen);
      emaFastNum = fma(emaSlowNum - emaFastNum, kFast, emaFastNum);
      emaFastDen = fma(emaSlowDen - emaFastDen, kFast, emaFastDen);
      halfDen = 0.5 * emaFastDen;
      if( !TA_IS_ZERO(halfDen) )
      {
         smiValue = 100.0 * emaFastNum / halfDen;
      } else 
      {
         smiValue = 0.0;
      }
      prevSignal = fma(smiValue - prevSignal, kSignal, prevSignal);
      outSMI[outIdx] = smiValue;
      outSMISignal[outIdx] = prevSignal;
      outIdx = outIdx + 1;
      trailingIdx = trailingIdx + 1;
      today = today + 1;
   }
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

/**** Streaming API *****/

struct TA_SMI_Stream {
   /* The bars this handle has a value for (see TA_StreamOutRange).
    * Kept first, and in this order, in every stream struct. */
   int outRangeBegIdx;
   int outRangeCount;
   int optInTimePeriod;
   int optInFastPeriod;
   int optInSlowPeriod;
   int optInSignalPeriod;
   double kSlow;
   double kFast;
   double kSignal;
   double highest;
   double lowest;
   double emaSlowNum;
   double emaSlowDen;
   double emaFastNum;
   double emaFastDen;
   double prevSignal;
   int trailingIdx;
   int highestIdx;
   int lowestIdx;
   int i;
   int today;
   int xCap;
   int xPhys;
   int xMask;
   double *x_inHigh;
   double *xMirror_inHigh;
   double *x_inLow;
   double *xMirror_inLow;
   double *x_inClose;
   double *xMirror_inClose;
};

/* Private function, not in public API. */
static void TA_SMI_ReleaseImpl( struct TA_SMI_Stream *sp )
{
   if( !sp ) return;
   if( sp->x_inHigh ) TA_Free( sp->x_inHigh );
   if( sp->xMirror_inHigh ) TA_Free( sp->xMirror_inHigh );
   if( sp->x_inLow ) TA_Free( sp->x_inLow );
   if( sp->xMirror_inLow ) TA_Free( sp->xMirror_inLow );
   if( sp->x_inClose ) TA_Free( sp->x_inClose );
   if( sp->xMirror_inClose ) TA_Free( sp->xMirror_inClose );
   TA_Free( sp );
}

/* Private function, not in public API. */
static void TA_SMI_StepImpl( struct TA_SMI_Stream *sp, double inHigh, double inLow, double inClose, double *outSMI, double *outSMISignal )
{
   double tmp;
   double num;
   double den;
   double halfDen;
   double smiValue;
   double prevSignal = sp->prevSignal;

   if( sp->today >= 1073741824 )
   {
      int rebaseShift = sp->trailingIdx & ~sp->xMask;
      sp->today -= rebaseShift;
      sp->trailingIdx -= rebaseShift;
      sp->highestIdx -= rebaseShift;
      sp->i -= rebaseShift;
      sp->lowestIdx -= rebaseShift;
   }
   sp->x_inHigh[sp->today & sp->xMask] = inHigh;
   sp->x_inLow[sp->today & sp->xMask] = inLow;
   sp->x_inClose[sp->today & sp->xMask] = inClose;
   /* Set the lowest low */
   tmp = sp->x_inLow[sp->today & sp->xMask];
   if( sp->lowestIdx < sp->trailingIdx )
   {
      sp->lowestIdx = sp->trailingIdx;
      sp->lowest = sp->x_inLow[sp->lowestIdx & sp->xMask];
      sp->i = sp->lowestIdx;
      while( ++sp->i <= sp->today )
      {
         tmp = sp->x_inLow[sp->i & sp->xMask];
         if( tmp < sp->lowest )
         {
            sp->lowestIdx = sp->i;
            sp->lowest = tmp;
         }
      }
   } else if( tmp <= sp->lowest )
   {
      sp->lowestIdx = sp->today;
      sp->lowest = tmp;
   }
   /* Set the highest high */
   tmp = sp->x_inHigh[sp->today & sp->xMask];
   if( sp->highestIdx < sp->trailingIdx )
   {
      sp->highestIdx = sp->trailingIdx;
      sp->highest = sp->x_inHigh[sp->highestIdx & sp->xMask];
      sp->i = sp->highestIdx;
      while( ++sp->i <= sp->today )
      {
         tmp = sp->x_inHigh[sp->i & sp->xMask];
         if( tmp > sp->highest )
         {
            sp->highestIdx = sp->i;
            sp->highest = tmp;
         }
      }
   } else if( tmp >= sp->highest )
   {
      sp->highestIdx = sp->today;
      sp->highest = tmp;
   }
   den = sp->highest - sp->lowest;
   num = sp->x_inClose[sp->today & sp->xMask] - (sp->highest + sp->lowest) * 0.5;
   sp->emaSlowNum = fma(num - sp->emaSlowNum, sp->kSlow, sp->emaSlowNum);
   sp->emaSlowDen = fma(den - sp->emaSlowDen, sp->kSlow, sp->emaSlowDen);
   sp->emaFastNum = fma(sp->emaSlowNum - sp->emaFastNum, sp->kFast, sp->emaFastNum);
   sp->emaFastDen = fma(sp->emaSlowDen - sp->emaFastDen, sp->kFast, sp->emaFastDen);
   /* Guard with TA_IS_ZERO, not an exact `halfDen != 0.0`: a machine-flat
    * window leaves a sub-epsilon residue that an exact check would divide
    * into noise (issue #107 / STOCHRSI). A window whose bars are all
    * H == L makes num zero too, so this is 0/0, and the neutral 0.0 is the
    * CCI (#7) and IMI (#112) convention.
    */
   halfDen = 0.5 * sp->emaFastDen;
   if( !TA_IS_ZERO(halfDen) )
   {
      smiValue = 100.0 * sp->emaFastNum / halfDen;
   } else 
   {
      smiValue = 0.0;
   }
   prevSignal = fma(smiValue - prevSignal, sp->kSignal, prevSignal);
   *outSMI= smiValue;
   *outSMISignal= prevSignal;
   sp->trailingIdx = sp->trailingIdx + 1;
   sp->today = sp->today + 1;
   sp->prevSignal = prevSignal;
}

static TA_RetCode TA_SMI_OpenImpl( struct TA_SMI_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], int startIdx, int historyLen, int optInTimePeriod, int optInFastPeriod, int optInSlowPeriod, int optInSignalPeriod, int *outBegIdx, int *outNBElement, double outSMI[], double outSMISignal[], int outStride )
{
   struct TA_SMI_Stream *sp;
   int endIdx;
   int dummyBegIdx;
   int dummyNBElement;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( !inHigh || !inLow || !inClose || !outSMI || !outSMISignal ) return TA_BAD_PARAM;
   if( historyLen < 1 ) return TA_BAD_PARAM;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 13;
   else if( (int)optInTimePeriod < 2 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInFastPeriod == TA_INTEGER_DEFAULT )
      optInFastPeriod = 2;
   else if( (int)optInFastPeriod < 2 || (int)optInFastPeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInSlowPeriod == TA_INTEGER_DEFAULT )
      optInSlowPeriod = 25;
   else if( (int)optInSlowPeriod < 2 || (int)optInSlowPeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInSignalPeriod == TA_INTEGER_DEFAULT )
      optInSignalPeriod = 9;
   else if( (int)optInSignalPeriod < 2 || (int)optInSignalPeriod > 100000 )
      return TA_BAD_PARAM;
   if( startIdx > historyLen - 1 )
   {
      *outBegIdx = 0;
      *outNBElement = 0;
      return TA_INSUFFICIENT_HISTORY;
   }

   endIdx = historyLen - 1;
   dummyBegIdx = 0;
   dummyNBElement = 0;
   (void)startIdx; (void)dummyBegIdx; (void)dummyNBElement;

   {
      double kSlow = 0.0;
      double kFast = 0.0;
      double kSignal = 0.0;
      double highest = 0.0;
      double lowest = 0.0;
      double tmp;
      double emaSlowNum = 0.0;
      double emaSlowDen = 0.0;
      double emaFastNum = 0.0;
      double emaFastDen = 0.0;
      double sumSlowNum;
      double sumSlowDen;
      double sumFastNum;
      double sumFastDen;
      double sumSignal;
      double num;
      double den;
      double halfDen;
      double smiValue;
      double prevSignal = 0.0;
      int lookbackTotal;
      int lookbackSlow;
      int lookbackFast;
      int today = 0;
      int trailingIdx = 0;
      int highestIdx = 0;
      int lowestIdx = 0;
      int i = 0;
      int outIdx;
      int nBar;
      int nFast;
      int nSignal;
      lookbackTotal = TA_SMI_Lookback(optInTimePeriod,optInFastPeriod,optInSlowPeriod,optInSignalPeriod);
      if( startIdx < lookbackTotal )
      {
         startIdx = lookbackTotal;
      }
      if( startIdx > endIdx )
      {
         *outBegIdx= 0;
         *outNBElement= 0;
         return TA_INSUFFICIENT_HISTORY;
      }
      *outBegIdx= startIdx;
      /* Blau's pipeline in one pass. A composed form is not available: the
       * streaming producer model carries exactly one intermediate series
       * (streaming.rs:2076) and SMI has two, the numerator and the denominator,
       * which must be smoothed separately before they are divided.
       *
       * Each of the three stages seeds the way ema.c does -- a simple average of
       * that stage's first 'period' inputs -- so the result is bit-identical to
       * TA_MAX + TA_MIN followed by four TA_EMA calls. The stage boundaries below
       * are the callee LOOKBACKS, not (period-1), so that a warm
       * TA_SetUnstablePeriod(TA_FUNC_UNST_EMA) folds in: each stage then seeds
       * from the values its predecessor would have published, exactly as the
       * composed form does. The seed sums accumulate from 0.0 in production
       * order; do not reorder or fuse them (0.0+x is not x for x=-0.0).
       *
       * TA_GetCompatibility() is deliberately NOT consulted, for the reason
       * spelled out in efi.c: ema.c's TA_COMPATIBILITY_METASTOCK seeding arm is
       * preserved for the functions that already shipped with it and dropped from
       * new ones, and it is not reachable at all from the Rust, Java and C# APIs.
       * The seeding choice itself is measured in docs/studies/ema-seeding/README.md.
       */
      kSlow = 2.0 / (double)(optInSlowPeriod + 1);
      kFast = 2.0 / (double)(optInFastPeriod + 1);
      kSignal = 2.0 / (double)(optInSignalPeriod + 1);
      lookbackSlow = TA_EMA_Lookback(optInSlowPeriod);
      lookbackFast = TA_EMA_Lookback(optInFastPeriod);
      emaSlowNum = 0.0;
      emaSlowDen = 0.0;
      emaFastNum = 0.0;
      emaFastDen = 0.0;
      prevSignal = 0.0;
      smiValue = 0.0;
      sumSlowNum = 0.0;
      sumSlowDen = 0.0;
      sumFastNum = 0.0;
      sumFastDen = 0.0;
      sumSignal = 0.0;
      highest = 0.0;
      lowest = 0.0;
      highestIdx = 0 - 1;
      lowestIdx = 0 - 1;
      /* The first bar carrying a full high/low window. */
      trailingIdx = startIdx - lookbackTotal;
      today = trailingIdx + (optInTimePeriod - 1);
      nBar = 0;
      /* Warm-up. Runs through startIdx inclusive: the last pass here is the one
       * that completes the signal seed, so it produces the first output pair.
       */
      while( today <= startIdx )
      {
         /* Set the lowest low */
         tmp = inLow[today];
         if( lowestIdx < trailingIdx )
         {
            lowestIdx = trailingIdx;
            lowest = inLow[lowestIdx];
            i = lowestIdx;
            while( ++i <= today )
            {
               tmp = inLow[i];
               if( tmp < lowest )
               {
                  lowestIdx = i;
                  lowest = tmp;
               }
            }
         } else if( tmp <= lowest )
         {
            lowestIdx = today;
            lowest = tmp;
         }
         /* Set the highest high */
         tmp = inHigh[today];
         if( highestIdx < trailingIdx )
         {
            highestIdx = trailingIdx;
            highest = inHigh[highestIdx];
            i = highestIdx;
            while( ++i <= today )
            {
               tmp = inHigh[i];
               if( tmp > highest )
               {
                  highestIdx = i;
                  highest = tmp;
               }
            }
         } else if( tmp >= highest )
         {
            highestIdx = today;
            highest = tmp;
         }
         den = highest - lowest;
         num = inClose[today] - (highest + lowest) * 0.5;
         /* Stage 1: the slow EMA, over the raw momentum. */
         if( nBar < optInSlowPeriod )
         {
            sumSlowNum = sumSlowNum + num;
            sumSlowDen = sumSlowDen + den;
            if( nBar == optInSlowPeriod - 1 )
            {
               emaSlowNum = sumSlowNum / optInSlowPeriod;
               emaSlowDen = sumSlowDen / optInSlowPeriod;
            }
         } else 
         {
            emaSlowNum = fma(num - emaSlowNum, kSlow, emaSlowNum);
            emaSlowDen = fma(den - emaSlowDen, kSlow, emaSlowDen);
         }
         /* Stage 2: the fast EMA, over what stage 1 publishes.
          *
          * The stage counters are compared BEFORE they are subtracted, never
          * after. Writing this as `nFast = nBar - lookbackSlow; if( nFast >= 0 )`
          * is correct in C, where the counters are signed, and broken everywhere
          * else: the Rust backend renders them as `usize`, so the subtraction
          * underflows for the first lookbackSlow bars -- a panic in a debug build
          * and a wrap in release. It would also be invisible to the cross-language
          * gate, which runs release servers at unstable period 0, where the branch
          * the wrap wrongly takes happens to be a no-op because both accumulators
          * are still 0.0.
          */
         if( nBar >= lookbackSlow )
         {
            nFast = nBar - lookbackSlow;
            if( nFast < optInFastPeriod )
            {
               sumFastNum = sumFastNum + emaSlowNum;
               sumFastDen = sumFastDen + emaSlowDen;
               if( nFast == optInFastPeriod - 1 )
               {
                  emaFastNum = sumFastNum / optInFastPeriod;
                  emaFastDen = sumFastDen / optInFastPeriod;
               }
            } else 
            {
               emaFastNum = fma(emaSlowNum - emaFastNum, kFast, emaFastNum);
               emaFastDen = fma(emaSlowDen - emaFastDen, kFast, emaFastDen);
            }
         }
         /* Stage 3: the SMI line, then the signal EMA over it. */
         if( nBar >= lookbackSlow + lookbackFast )
         {
            nSignal = nBar - lookbackSlow - lookbackFast;
            halfDen = 0.5 * emaFastDen;
            if( !TA_IS_ZERO(halfDen) )
            {
               smiValue = 100.0 * emaFastNum / halfDen;
            } else 
            {
               smiValue = 0.0;
            }
            if( nSignal < optInSignalPeriod )
            {
               sumSignal = sumSignal + smiValue;
               if( nSignal == optInSignalPeriod - 1 )
               {
                  prevSignal = sumSignal / optInSignalPeriod;
               }
            } else 
            {
               prevSignal = fma(smiValue - prevSignal, kSignal, prevSignal);
            }
         }
         nBar = nBar + 1;
         trailingIdx = trailingIdx + 1;
         today = today + 1;
      }
      outSMI[0 * outStride] = smiValue;
      outSMISignal[0 * outStride] = prevSignal;
      outIdx = 1;
      /* Stable zone. Every stage is a pure recursion from here on. */
      while( today <= endIdx )
      {
         /* Set the lowest low */
         tmp = inLow[today];
         if( lowestIdx < trailingIdx )
         {
            lowestIdx = trailingIdx;
            lowest = inLow[lowestIdx];
            i = lowestIdx;
            while( ++i <= today )
            {
               tmp = inLow[i];
               if( tmp < lowest )
               {
                  lowestIdx = i;
                  lowest = tmp;
               }
            }
         } else if( tmp <= lowest )
         {
            lowestIdx = today;
            lowest = tmp;
         }
         /* Set the highest high */
         tmp = inHigh[today];
         if( highestIdx < trailingIdx )
         {
            highestIdx = trailingIdx;
            highest = inHigh[highestIdx];
            i = highestIdx;
            while( ++i <= today )
            {
               tmp = inHigh[i];
               if( tmp > highest )
               {
                  highestIdx = i;
                  highest = tmp;
               }
            }
         } else if( tmp >= highest )
         {
            highestIdx = today;
            highest = tmp;
         }
         den = highest - lowest;
         num = inClose[today] - (highest + lowest) * 0.5;
         emaSlowNum = fma(num - emaSlowNum, kSlow, emaSlowNum);
         emaSlowDen = fma(den - emaSlowDen, kSlow, emaSlowDen);
         emaFastNum = fma(emaSlowNum - emaFastNum, kFast, emaFastNum);
         emaFastDen = fma(emaSlowDen - emaFastDen, kFast, emaFastDen);
         /* Guard with TA_IS_ZERO, not an exact `halfDen != 0.0`: a machine-flat
          * window leaves a sub-epsilon residue that an exact check would divide
          * into noise (issue #107 / STOCHRSI). A window whose bars are all
          * H == L makes num zero too, so this is 0/0, and the neutral 0.0 is the
          * CCI (#7) and IMI (#112) convention.
          */
         halfDen = 0.5 * emaFastDen;
         if( !TA_IS_ZERO(halfDen) )
         {
            smiValue = 100.0 * emaFastNum / halfDen;
         } else 
         {
            smiValue = 0.0;
         }
         prevSignal = fma(smiValue - prevSignal, kSignal, prevSignal);
         outSMI[outIdx * outStride] = smiValue;
         outSMISignal[outIdx * outStride] = prevSignal;
         outIdx = outIdx + 1;
         trailingIdx = trailingIdx + 1;
         today = today + 1;
      }
      *outNBElement= outIdx;

      /* Capture the live batch state into the handle. */
      sp = (struct TA_SMI_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) { return TA_ALLOC_ERR; }
      memset( sp, 0, sizeof(*sp) );
      sp->optInTimePeriod = optInTimePeriod;
      sp->optInFastPeriod = optInFastPeriod;
      sp->optInSlowPeriod = optInSlowPeriod;
      sp->optInSignalPeriod = optInSignalPeriod;
      sp->kSlow = kSlow;
      sp->kFast = kFast;
      sp->kSignal = kSignal;
      sp->highest = highest;
      sp->lowest = lowest;
      sp->emaSlowNum = emaSlowNum;
      sp->emaSlowDen = emaSlowDen;
      sp->emaFastNum = emaFastNum;
      sp->emaFastDen = emaFastDen;
      sp->prevSignal = prevSignal;
      sp->trailingIdx = trailingIdx;
      sp->highestIdx = highestIdx;
      sp->lowestIdx = lowestIdx;
      sp->i = i;
      sp->today = today;
      sp->xCap = (int)(today - trailingIdx) + 1;
      if( sp->xCap < 1 || sp->xCap > historyLen ) { TA_SMI_ReleaseImpl( sp ); return TA_INTERNAL_ERROR; }
      sp->xPhys = 1;
      while( sp->xPhys < sp->xCap ) sp->xPhys <<= 1;
      sp->xMask = sp->xPhys - 1;
      sp->x_inHigh = (double *)TA_Malloc( sizeof(double) * (size_t)sp->xPhys );
      if( !sp->x_inHigh ) { TA_SMI_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
      sp->xMirror_inHigh = (double *)TA_Malloc( sizeof(double) * (size_t)sp->xPhys );
      if( !sp->xMirror_inHigh ) { TA_SMI_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
      sp->x_inLow = (double *)TA_Malloc( sizeof(double) * (size_t)sp->xPhys );
      if( !sp->x_inLow ) { TA_SMI_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
      sp->xMirror_inLow = (double *)TA_Malloc( sizeof(double) * (size_t)sp->xPhys );
      if( !sp->xMirror_inLow ) { TA_SMI_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
      sp->x_inClose = (double *)TA_Malloc( sizeof(double) * (size_t)sp->xPhys );
      if( !sp->x_inClose ) { TA_SMI_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
      sp->xMirror_inClose = (double *)TA_Malloc( sizeof(double) * (size_t)sp->xPhys );
      if( !sp->xMirror_inClose ) { TA_SMI_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
      { int fillJ;
        for( fillJ = historyLen - sp->xCap; fillJ < historyLen; fillJ++ )
        {
           sp->x_inHigh[fillJ & sp->xMask] = inHigh[fillJ];
           sp->x_inLow[fillJ & sp->xMask] = inLow[fillJ];
           sp->x_inClose[fillJ & sp->xMask] = inClose[fillJ];
        }
      }
      sp->outRangeBegIdx = *outBegIdx;
      sp->outRangeCount = *outNBElement;
      *stream = sp;
      return TA_SUCCESS;
   }
}

/* Private function, not in public API. */
TA_RetCode TA_SMI_OpenInternal( struct TA_SMI_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], int startIdx, int historyLen, int optInTimePeriod, int optInFastPeriod, int optInSlowPeriod, int optInSignalPeriod, double *outSMI, double *outSMISignal )
{
   TA_RetCode retCode;
   int dummyBegIdx = 0;
   int dummyNBElement = 0;
   double sink_outSMI = 0.0;
   double sink_outSMISignal = 0.0;
   retCode = TA_SMI_OpenImpl( stream, inHigh, inLow, inClose, startIdx, historyLen, optInTimePeriod, optInFastPeriod, optInSlowPeriod, optInSignalPeriod, &dummyBegIdx, &dummyNBElement, &sink_outSMI, &sink_outSMISignal, 0 );
   if( retCode == TA_SUCCESS )
   {
      *outSMI = sink_outSMI;
      *outSMISignal = sink_outSMISignal;
   }
   return retCode;
}

TA_LIB_API TA_RetCode TA_SMI_Open( TA_SMI_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], int historyLen, int optInTimePeriod, int optInFastPeriod, int optInSlowPeriod, int optInSignalPeriod, double *outSMI, double *outSMISignal )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( !inHigh || !inLow || !inClose || !outSMI || !outSMISignal ) return TA_BAD_PARAM;
   if( historyLen < 1 ) return TA_BAD_PARAM;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   return TA_SMI_OpenInternal( stream, inHigh, inLow, inClose, 0, historyLen, optInTimePeriod, optInFastPeriod, optInSlowPeriod, optInSignalPeriod, outSMI, outSMISignal );
}

TA_LIB_API TA_RetCode TA_SMI_OpenAndFill( TA_SMI_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], int historyLen, int optInTimePeriod, int optInFastPeriod, int optInSlowPeriod, int optInSignalPeriod, int *outBegIdx, int *outNBElement, double outSMI[], double outSMISignal[] )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( !outBegIdx || !outNBElement ) return TA_BAD_PARAM;
   if( !inHigh || !inLow || !inClose || !outSMI || !outSMISignal ) return TA_BAD_PARAM;
   if( historyLen < 1 ) return TA_BAD_PARAM;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( (const void *)outSMI == (const void *)inHigh || (const void *)outSMI == (const void *)inLow || (const void *)outSMI == (const void *)inClose || (const void *)outSMISignal == (const void *)inHigh || (const void *)outSMISignal == (const void *)inLow || (const void *)outSMISignal == (const void *)inClose || (const void *)outSMI == (const void *)outSMISignal ) return TA_BAD_PARAM;
   return TA_SMI_OpenAndFillInternal( stream, inHigh, inLow, inClose, 0, historyLen, optInTimePeriod, optInFastPeriod, optInSlowPeriod, optInSignalPeriod, outBegIdx, outNBElement, outSMI, outSMISignal );
}

/* Private function, not in public API. */
TA_RetCode TA_SMI_OpenAndFillInternal( struct TA_SMI_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], int startIdx, int historyLen, int optInTimePeriod, int optInFastPeriod, int optInSlowPeriod, int optInSignalPeriod, int *outBegIdx, int *outNBElement, double outSMI[], double outSMISignal[] )
{
   return TA_SMI_OpenImpl( stream, inHigh, inLow, inClose, startIdx, historyLen, optInTimePeriod, optInFastPeriod, optInSlowPeriod, optInSignalPeriod, outBegIdx, outNBElement, outSMI, outSMISignal, 1 );
}

TA_LIB_API TA_RetCode TA_SMI_Update( TA_SMI_Stream *stream, double inHigh, double inLow, double inClose, double *outSMI, double *outSMISignal )
{
   if( !stream || !outSMI || !outSMISignal ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) || !TA_IS_FINITE( inClose ) ) return TA_BAD_PARAM;
   TA_SMI_StepImpl( stream, inHigh, inLow, inClose, outSMI, outSMISignal );
   if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_SMI_Peek( const TA_SMI_Stream *stream, double inHigh, double inLow, double inClose, double *outSMI, double *outSMISignal )
{
   struct TA_SMI_Stream scratch;

   if( !stream || !outSMI || !outSMISignal ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) || !TA_IS_FINITE( inClose ) ) return TA_BAD_PARAM;
   scratch = *stream;
   scratch.x_inHigh = stream->xMirror_inHigh;
   memcpy( scratch.x_inHigh, stream->x_inHigh, sizeof(double) * (size_t)stream->xPhys );
   scratch.x_inLow = stream->xMirror_inLow;
   memcpy( scratch.x_inLow, stream->x_inLow, sizeof(double) * (size_t)stream->xPhys );
   scratch.x_inClose = stream->xMirror_inClose;
   memcpy( scratch.x_inClose, stream->x_inClose, sizeof(double) * (size_t)stream->xPhys );
   TA_SMI_StepImpl( &scratch, inHigh, inLow, inClose, outSMI, outSMISignal );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_SMI_UpdateAndFill( TA_SMI_Stream *stream, const double inHigh[], const double inLow[], const double inClose[], int barCount, double outSMI[], double outSMISignal[] )
{
   int i;

   if( !stream || !inHigh || !inLow || !inClose || !outSMI || !outSMISignal ) return TA_BAD_PARAM;
   if( barCount < 0 ) return TA_BAD_PARAM;
   if( (const void *)outSMI == (const void *)inHigh || (const void *)outSMI == (const void *)inLow || (const void *)outSMI == (const void *)inClose || (const void *)outSMISignal == (const void *)inHigh || (const void *)outSMISignal == (const void *)inLow || (const void *)outSMISignal == (const void *)inClose || (const void *)outSMI == (const void *)outSMISignal ) return TA_BAD_PARAM;
   for( i = 0; i < barCount; i++ )
   {
      if( !TA_IS_FINITE( inHigh[i] ) || !TA_IS_FINITE( inLow[i] ) || !TA_IS_FINITE( inClose[i] ) ) return TA_BAD_PARAM;
      TA_SMI_StepImpl( stream, inHigh[i], inLow[i], inClose[i], &outSMI[i], &outSMISignal[i] );
      if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   }
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_SMI_Close( TA_SMI_Stream *stream )
{
   TA_SMI_ReleaseImpl( stream );
   return TA_SUCCESS;
}

