/* TA-LIB Copyright (c) 1999-2026, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_stream_private.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  MF       Mario Fortier
 *  EKO      echo999@ifrance.com
 *  CC       Claude Code (AI assistant)
 *
 * Change history:
 *
 *  MMDDYY BY    Description
 *  -------------------------------------------------------------------
 *  010802 MF    Template creation.
 *  051103 EKO   Found bug and fix related to outFastD.
 *  052603 MF    Adapt code to compile with .NET Managed C++
 *  071026 MF,CC Fix #107. Guard the Fast-K division with TA_IS_ZERO, not an
 *               exact `diff != 0.0`, so a machine-flat window yields 0 instead
 *               of dividing a sub-epsilon residue into [0,100] noise (STOCHRSI).
 *  072026 MF,CC Fix #130. Never elect outFastD as the K scratch buffer: %D's
 *               in-place ma() destroyed the raw K before the final copy.
 *  082326 MF,CC Fix #253. Scale that guard to the window's own extremes: the
 *               fixed band zeroed the whole output for any instrument quoted
 *               small enough to fall under it.
 *  082726 MF,CC Drop the dead retCode block after the copy: the rejection is
 *               already answered above it, and the shape reads like #269.
 */

TA_LIB_API int TA_STOCHF_Lookback( int optInFastK_Period, int optInFastD_Period, TA_MAType optInFastD_MAType )
{
   int retValue;
   if( (int)optInFastK_Period == TA_INTEGER_DEFAULT )
      optInFastK_Period = 5;
   else if( (int)optInFastK_Period < 1 || (int)optInFastK_Period > 100000 )
      return -1;
   if( (int)optInFastD_Period == TA_INTEGER_DEFAULT )
      optInFastD_Period = 3;
   else if( (int)optInFastD_Period < 1 || (int)optInFastD_Period > 100000 )
      return -1;
   if( (int)optInFastD_MAType == TA_INTEGER_DEFAULT || optInFastD_MAType == TA_MAType_DEFAULT )
      optInFastD_MAType = 0;
   else if( (int)optInFastD_MAType < TA_MATYPE_MIN || (int)optInFastD_MAType > TA_MATYPE_MAX )
      return -1;
   /* Account for the initial data needed for Fast-K. */
   retValue = optInFastK_Period - 1;
   /* Add the smoothing being done for Fast-D */
   retValue += TA_MA_Lookback(optInFastD_Period,optInFastD_MAType);
   return retValue;
}

TA_LIB_API TA_RetCode TA_STOCHF( int    startIdx,
                                 int    endIdx,
                                 const double inHigh[],
                                 const double inLow[],
                                 const double inClose[],
                                 int optInFastK_Period,
                                 int optInFastD_Period,
                                 TA_MAType optInFastD_MAType,
                                 int          *outBegIdx,
                                 int          *outNBElement,
                                 double        outFastK[],
                                 double        outFastD[] )
{
   TA_RetCode retCode;
   double lowest;
   double highest;
   double tmp;
   double diff;
   double *tempBuffer;
   int outIdx;
   int lowestIdx;
   int highestIdx;
   int lookbackTotal;
   int lookbackK;
   int lookbackFastD;
   int trailingIdx;
   int today;
   int i;
   int bufferIsAllocated;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInFastK_Period == TA_INTEGER_DEFAULT )
      optInFastK_Period = 5;
   else if( (int)optInFastK_Period < 1 || (int)optInFastK_Period > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInFastD_Period == TA_INTEGER_DEFAULT )
      optInFastD_Period = 3;
   else if( (int)optInFastD_Period < 1 || (int)optInFastD_Period > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInFastD_MAType == TA_INTEGER_DEFAULT || optInFastD_MAType == TA_MAType_DEFAULT )
      optInFastD_MAType = 0;
   else if( (int)optInFastD_MAType < TA_MATYPE_MIN || (int)optInFastD_MAType > TA_MATYPE_MAX )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !inClose )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outFastK )
      return TA_BAD_PARAM;
   if( !outFastD )
      return TA_BAD_PARAM;
   if( outFastK == outFastD )
      return TA_BAD_PARAM;

   i = 0;
   /* With stochastic, there is a total of 4 different lines that
    * are defined: FASTK, FASTD, SLOWK and SLOWD.
    *
    * The D is the signal line usually drawn over its
    * corresponding K function.
    *
    *                    (Today's Close - LowestLow)
    *  FASTK(Kperiod) =  --------------------------- * 100
    *                     (HighestHigh - LowestLow)
    *
    *  FASTD(FastDperiod, MA type) = MA Smoothed FASTK over FastDperiod
    *
    *  SLOWK(SlowKperiod, MA type) = MA Smoothed FASTK over SlowKperiod
    *
    *  SLOWD(SlowDperiod, MA Type) = MA Smoothed SLOWK over SlowDperiod
    *
    * The HighestHigh and LowestLow are the extreme values among the
    * last 'Kperiod'.
    *
    * SLOWK and FASTD are equivalent when using the same period.
    *
    * The following shows how these four lines are made available in TA-LIB:
    *
    *  TA_STOCH  : Returns the SLOWK and SLOWD
    *  TA_STOCHF : Returns the FASTK and FASTD
    *
    * The TA_STOCH function correspond to the more widely implemented version
    * found in many software/charting package. The TA_STOCHF is more rarely
    * used because its higher volatility cause often whipsaws.
    */
   /* Identify the lookback needed. */
   lookbackK = optInFastK_Period - 1;
   lookbackFastD = TA_MA_Lookback(optInFastD_Period,optInFastD_MAType);
   lookbackTotal = lookbackK + lookbackFastD;
   /* Move up the start index if there is not
    * enough initial data.
    */
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   /* Make sure there is still something to evaluate. */
   if( startIdx > endIdx )
   {
      /* Succeed... but no data in the output. */
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   /* Do the K calculation:
    *
    *    Kt = 100 x ((Ct-Lt)/(Ht-Lt))
    *
    * Kt is today stochastic
    * Ct is today closing price.
    * Lt is the lowest price of the last K Period (including today)
    * Ht is the highest price of the last K Period (including today)
    */
   /* Proceed with the calculation for the requested range.
    * Note that this algorithm allows the input and
    * output to be the same buffer.
    */
   outIdx = 0;
   /* Calculate just enough K for ending up with the caller
    * requested range. (The range of k must consider all
    * the lookback involve with the smoothing).
    */
   trailingIdx = startIdx - lookbackTotal;
   today = trailingIdx + lookbackK;
   highestIdx = 0 - 1;
   lowestIdx = highestIdx;
   lowest = 0.0;
   highest = lowest;
   diff = highest;
   /* Allocate a temporary buffer large enough to
    * store the K.
    *
    * When outFastK aliases a price input the caller buffer doubles as the
    * scratch, saving one allocation: the K writes trail the min/max window
    * reads, and the final memmove is overlap-safe. outFastD must NOT be
    * elected: the %D ma() below would then run in place over the raw K
    * that the memmove into outFastK still needs (issue #130).
    */
   bufferIsAllocated = 0;
   if( outFastK == inHigh || outFastK == inLow || outFastK == inClose )
   {
      tempBuffer = outFastK;
   } else 
   {
      bufferIsAllocated = 1;
      tempBuffer = malloc((endIdx - today + 1) * sizeof(double));
      if( !tempBuffer )
      {
         *outBegIdx= 0;
         *outNBElement= 0;
         return TA_ALLOC_ERR;
      }
   }
   /* Do the K calculation */
   while( today <= endIdx )
   {
      /* Set the lowest low */
      tmp = inLow[today];
      if( lowestIdx < trailingIdx )
      {
         lowestIdx = trailingIdx;
         lowest = inLow[lowestIdx];
         i = lowestIdx;
         while( ++i <= today )
         {
            tmp = inLow[i];
            if( tmp < lowest )
            {
               lowestIdx = i;
               lowest = tmp;
            }
         }
         diff = (highest - lowest) / 100.0;
      } else if( tmp <= lowest )
      {
         lowestIdx = today;
         lowest = tmp;
         diff = (highest - lowest) / 100.0;
      }
      /* Set the highest high */
      tmp = inHigh[today];
      if( highestIdx < trailingIdx )
      {
         highestIdx = trailingIdx;
         highest = inHigh[highestIdx];
         i = highestIdx;
         while( ++i <= today )
         {
            tmp = inHigh[i];
            if( tmp > highest )
            {
               highestIdx = i;
               highest = tmp;
            }
         }
         diff = (highest - lowest) / 100.0;
      } else if( tmp >= highest )
      {
         highestIdx = today;
         highest = tmp;
         diff = (highest - lowest) / 100.0;
      }
      /* Calculate stochastic. The guard is not an exact `diff != 0.0`: a
       * machine-flat window leaves a sub-epsilon residue that an exact check
       * would divide into [0,100] noise (issue #107 / STOCHRSI). It is the
       * range against ITS OWN two extremes, not against a fixed band: the range
       * carries the quote unit, so a constant put against it answers "flat" for
       * every window of an instrument quoted below it and zeroed the whole
       * output (issue #253).
       */
      if( !TA_IS_ZERO_SCALED(highest - lowest, fabs(highest) + fabs(lowest)) )
      {
         tempBuffer[outIdx++] = (inClose[today] - lowest) / diff;
      } else 
      {
         tempBuffer[outIdx++] = 0.0;
      }
      trailingIdx += 1;
      today += 1;
   }
   /* Fast-K calculation completed. This K calculation is returned
    * to the caller. It is smoothed to become Fast-D.
    */
   retCode = TA_MA(0,outIdx - 1,tempBuffer,optInFastD_Period,optInFastD_MAType,outBegIdx,outNBElement,outFastD);
   if( retCode != TA_SUCCESS || (int)*outNBElement == 0 )
   {
      if( bufferIsAllocated )
      {
         free(tempBuffer);
      }
      /* Something wrong happen? No further data? */
      *outBegIdx= 0;
      *outNBElement= 0;
      return retCode;
   }
   /* Copy tempBuffer into the caller buffer.
    * (Calculation could not be done directly in the
    *  caller buffer because more input data then the
    *  requested range was needed for doing %D).
    */
   /* memmove, not memcpy: tempBuffer aliases outFastK when the caller buffer is
    * reused as scratch, so source and destination overlap (issue #94).
    */
   memmove(outFastK,&tempBuffer[lookbackFastD],(int)*outNBElement * sizeof(double));
   if( bufferIsAllocated )
   {
      free(tempBuffer);
   }
   /* Note: Keep the outBegIdx relative to the
    *       caller input before returning.
    */
   *outBegIdx= startIdx;
   return TA_SUCCESS;
}

TA_RetCode TA_S_STOCHF( int    startIdx,
                        int    endIdx,
                        const float inHigh[],
                        const float inLow[],
                        const float inClose[],
                        int optInFastK_Period,
                        int optInFastD_Period,
                        TA_MAType optInFastD_MAType,
                        int          *outBegIdx,
                        int          *outNBElement,
                        double        outFastK[],
                        double        outFastD[] )
{
   TA_RetCode retCode;
   double lowest;
   double highest;
   double tmp;
   double diff;
   double *tempBuffer;
   int outIdx;
   int lowestIdx;
   int highestIdx;
   int lookbackTotal;
   int lookbackK;
   int lookbackFastD;
   int trailingIdx;
   int today;
   int i;
   int bufferIsAllocated;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInFastK_Period == TA_INTEGER_DEFAULT )
      optInFastK_Period = 5;
   else if( (int)optInFastK_Period < 1 || (int)optInFastK_Period > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInFastD_Period == TA_INTEGER_DEFAULT )
      optInFastD_Period = 3;
   else if( (int)optInFastD_Period < 1 || (int)optInFastD_Period > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInFastD_MAType == TA_INTEGER_DEFAULT || optInFastD_MAType == TA_MAType_DEFAULT )
      optInFastD_MAType = 0;
   else if( (int)optInFastD_MAType < TA_MATYPE_MIN || (int)optInFastD_MAType > TA_MATYPE_MAX )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !inClose )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outFastK )
      return TA_BAD_PARAM;
   if( !outFastD )
      return TA_BAD_PARAM;
   if( outFastK == outFastD )
      return TA_BAD_PARAM;

   i = 0;
   lookbackK = optInFastK_Period - 1;
   lookbackFastD = TA_MA_Lookback(optInFastD_Period,optInFastD_MAType);
   lookbackTotal = lookbackK + lookbackFastD;
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   outIdx = 0;
   trailingIdx = startIdx - lookbackTotal;
   today = trailingIdx + lookbackK;
   highestIdx = 0 - 1;
   lowestIdx = highestIdx;
   lowest = 0.0;
   highest = lowest;
   diff = highest;
   bufferIsAllocated = 0;
   if( 0 || 0 || 0 )
   {
      tempBuffer = outFastK;
   } else 
   {
      bufferIsAllocated = 1;
      tempBuffer = malloc((endIdx - today + 1) * sizeof(double));
      if( !tempBuffer )
      {
         *outBegIdx= 0;
         *outNBElement= 0;
         return TA_ALLOC_ERR;
      }
   }
   while( today <= endIdx )
   {
      tmp = (double)inLow[today];
      if( lowestIdx < trailingIdx )
      {
         lowestIdx = trailingIdx;
         lowest = (double)inLow[lowestIdx];
         i = lowestIdx;
         while( ++i <= today )
         {
            tmp = (double)inLow[i];
            if( tmp < lowest )
            {
               lowestIdx = i;
               lowest = tmp;
            }
         }
         diff = (highest - lowest) / 100.0;
      } else if( tmp <= lowest )
      {
         lowestIdx = today;
         lowest = tmp;
         diff = (highest - lowest) / 100.0;
      }
      tmp = (double)inHigh[today];
      if( highestIdx < trailingIdx )
      {
         highestIdx = trailingIdx;
         highest = (double)inHigh[highestIdx];
         i = highestIdx;
         while( ++i <= today )
         {
            tmp = (double)inHigh[i];
            if( tmp > highest )
            {
               highestIdx = i;
               highest = tmp;
            }
         }
         diff = (highest - lowest) / 100.0;
      } else if( tmp >= highest )
      {
         highestIdx = today;
         highest = tmp;
         diff = (highest - lowest) / 100.0;
      }
      if( !TA_IS_ZERO_SCALED(highest - lowest, fabs(highest) + fabs(lowest)) )
      {
         tempBuffer[outIdx++] = ((double)inClose[today] - lowest) / diff;
      } else 
      {
         tempBuffer[outIdx++] = 0.0;
      }
      trailingIdx += 1;
      today += 1;
   }
   retCode = TA_MA(0,outIdx - 1,tempBuffer,optInFastD_Period,optInFastD_MAType,outBegIdx,outNBElement,outFastD);
   if( retCode != TA_SUCCESS || (int)*outNBElement == 0 )
   {
      if( bufferIsAllocated )
      {
         free(tempBuffer);
      }
      *outBegIdx= 0;
      *outNBElement= 0;
      return retCode;
   }
   memmove(outFastK,&tempBuffer[lookbackFastD],(int)*outNBElement * sizeof(double));
   if( bufferIsAllocated )
   {
      free(tempBuffer);
   }
   *outBegIdx= startIdx;
   return TA_SUCCESS;
}

/**** Streaming API *****/

struct TA_STOCHF_Stream {
   /* The bars this handle has an output for (see TA_StreamOutRange).
    * Kept first, and in this order, in every stream struct. */
   int outRangeBegIdx;
   int outRangeCount;
   /* The value(s) at the last bar the stream counted (see TA_STOCHF_Value). */
   double cur_outFastK;
   double cur_outFastD;
   int optInFastK_Period;
   int optInFastD_Period;
   TA_MAType optInFastD_MAType;
   double lowest;
   double highest;
   double diff;
   int lowestIdx;
   int highestIdx;
   int trailingIdx;
   int i;
   int today;
   int xCap;
   int xPhys;
   int xMask;
   double *x_inHigh;
   double *x_inLow;
   double *x_inClose;
   TA_MA_Stream *sub0;
};

/* Private function, not in public API. */
static void TA_STOCHF_ReleaseImpl( struct TA_STOCHF_Stream *sp )
{
   if( !sp ) return;
   if( sp->x_inHigh ) TA_Free( sp->x_inHigh );
   if( sp->x_inLow ) TA_Free( sp->x_inLow );
   if( sp->x_inClose ) TA_Free( sp->x_inClose );
   TA_Free( sp );
}

/* Private function, not in public API. */
static TA_RetCode TA_STOCHF_StepImpl( struct TA_STOCHF_Stream *sp, double inHigh, double inLow, double inClose, double *outFastK, double *outFastD )
{
   double cur_tempBuffer = 0.0;
   double cur_outFastD = 0.0;
   double tmp;

   if( sp->today >= 1073741824 )
   {
      int rebaseShift = sp->trailingIdx & ~sp->xMask;
      sp->today -= rebaseShift;
      sp->trailingIdx -= rebaseShift;
      sp->highestIdx -= rebaseShift;
      sp->i -= rebaseShift;
      sp->lowestIdx -= rebaseShift;
   }
   sp->x_inHigh[sp->today & sp->xMask] = inHigh;
   sp->x_inLow[sp->today & sp->xMask] = inLow;
   sp->x_inClose[sp->today & sp->xMask] = inClose;
   /* Set the lowest low */
   tmp = sp->x_inLow[sp->today & sp->xMask];
   if( sp->lowestIdx < sp->trailingIdx )
   {
      sp->lowestIdx = sp->trailingIdx;
      sp->lowest = sp->x_inLow[sp->lowestIdx & sp->xMask];
      sp->i = sp->lowestIdx;
      while( ++sp->i <= sp->today )
      {
         tmp = sp->x_inLow[sp->i & sp->xMask];
         if( tmp < sp->lowest )
         {
            sp->lowestIdx = sp->i;
            sp->lowest = tmp;
         }
      }
      sp->diff = (sp->highest - sp->lowest) / 100.0;
   } else if( tmp <= sp->lowest )
   {
      sp->lowestIdx = sp->today;
      sp->lowest = tmp;
      sp->diff = (sp->highest - sp->lowest) / 100.0;
   }
   /* Set the highest high */
   tmp = sp->x_inHigh[sp->today & sp->xMask];
   if( sp->highestIdx < sp->trailingIdx )
   {
      sp->highestIdx = sp->trailingIdx;
      sp->highest = sp->x_inHigh[sp->highestIdx & sp->xMask];
      sp->i = sp->highestIdx;
      while( ++sp->i <= sp->today )
      {
         tmp = sp->x_inHigh[sp->i & sp->xMask];
         if( tmp > sp->highest )
         {
            sp->highestIdx = sp->i;
            sp->highest = tmp;
         }
      }
      sp->diff = (sp->highest - sp->lowest) / 100.0;
   } else if( tmp >= sp->highest )
   {
      sp->highestIdx = sp->today;
      sp->highest = tmp;
      sp->diff = (sp->highest - sp->lowest) / 100.0;
   }
   /* Calculate stochastic. The guard is not an exact `diff != 0.0`: a
    * machine-flat window leaves a sub-epsilon residue that an exact check
    * would divide into [0,100] noise (issue #107 / STOCHRSI). It is the
    * range against ITS OWN two extremes, not against a fixed band: the range
    * carries the quote unit, so a constant put against it answers "flat" for
    * every window of an instrument quoted below it and zeroed the whole
    * output (issue #253).
    */
   if( !TA_IS_ZERO_SCALED(sp->highest - sp->lowest, fabs(sp->highest) + fabs(sp->lowest)) )
   {
      cur_tempBuffer = (sp->x_inClose[sp->today & sp->xMask] - sp->lowest) / sp->diff;
   } else 
   {
      cur_tempBuffer = 0.0;
   }
   sp->trailingIdx += 1;
   sp->today += 1;

   /* Pipeline the new bar through the sub-streams (batch tail order). */
   {
      TA_RetCode subRc = TA_MA_Update( sp->sub0, cur_tempBuffer, &cur_outFastD );
      if( subRc != TA_SUCCESS ) return subRc;
   }
   *outFastK = cur_tempBuffer;
   *outFastD = cur_outFastD;
   return TA_SUCCESS;
}

static TA_RetCode TA_STOCHF_OpenImpl( struct TA_STOCHF_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], int startIdx, int historyLen, int optInFastK_Period, int optInFastD_Period, TA_MAType optInFastD_MAType, int *outBegIdx, int *outNBElement, double outFastK[], double outFastD[], int outStride )
{
   struct TA_STOCHF_Stream *sp;
   int endIdx;
   int dummyBegIdx;
   int dummyNBElement;
   TA_RetCode subRc;
   double subOpenDummy;
   double *sc_outFastK;
   double *sc_outFastD;
   TA_MA_Stream *sub0;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !inClose || !outFastK || !outFastD ) return TA_BAD_PARAM;
   if( (int)optInFastK_Period == TA_INTEGER_DEFAULT )
      optInFastK_Period = 5;
   else if( (int)optInFastK_Period < 1 || (int)optInFastK_Period > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInFastD_Period == TA_INTEGER_DEFAULT )
      optInFastD_Period = 3;
   else if( (int)optInFastD_Period < 1 || (int)optInFastD_Period > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInFastD_MAType == TA_INTEGER_DEFAULT || optInFastD_MAType == TA_MAType_DEFAULT )
      optInFastD_MAType = 0;
   else if( (int)optInFastD_MAType < TA_MATYPE_MIN || (int)optInFastD_MAType > TA_MATYPE_MAX )
      return TA_BAD_PARAM;
   if( startIdx > historyLen - 1 )
   {
      *outBegIdx = 0;
      *outNBElement = 0;
      return TA_INSUFFICIENT_HISTORY;
   }

   endIdx = historyLen - 1;
   dummyBegIdx = 0;
   dummyNBElement = 0;
   subRc = TA_SUCCESS;
   subOpenDummy = 0.0;
   sub0 = NULL;
   (void)startIdx; (void)dummyBegIdx; (void)dummyNBElement; (void)subRc; (void)subOpenDummy;
   if( outStride ) sc_outFastK = outFastK;
   else
   {
      sc_outFastK = (double *)TA_Malloc( sizeof(double) * (size_t)historyLen );
      if( !sc_outFastK ) { return TA_ALLOC_ERR; }
   }
   if( outStride ) sc_outFastD = outFastD;
   else
   {
      sc_outFastD = (double *)TA_Malloc( sizeof(double) * (size_t)historyLen );
      if( !sc_outFastD ) { TA_Free( sc_outFastK ); return TA_ALLOC_ERR; }
   }

   {
      TA_RetCode retCode;
      double lowest;
      double highest;
      double tmp;
      double diff;
      double *tempBuffer;
      int outIdx;
      int lowestIdx;
      int highestIdx;
      int lookbackTotal;
      int lookbackK;
      int lookbackFastD;
      int trailingIdx;
      int today;
      int i = 0;
      int bufferIsAllocated;
      /* With stochastic, there is a total of 4 different lines that
       * are defined: FASTK, FASTD, SLOWK and SLOWD.
       *
       * The D is the signal line usually drawn over its
       * corresponding K function.
       *
       *                    (Today's Close - LowestLow)
       *  FASTK(Kperiod) =  --------------------------- * 100
       *                     (HighestHigh - LowestLow)
       *
       *  FASTD(FastDperiod, MA type) = MA Smoothed FASTK over FastDperiod
       *
       *  SLOWK(SlowKperiod, MA type) = MA Smoothed FASTK over SlowKperiod
       *
       *  SLOWD(SlowDperiod, MA Type) = MA Smoothed SLOWK over SlowDperiod
       *
       * The HighestHigh and LowestLow are the extreme values among the
       * last 'Kperiod'.
       *
       * SLOWK and FASTD are equivalent when using the same period.
       *
       * The following shows how these four lines are made available in TA-LIB:
       *
       *  TA_STOCH  : Returns the SLOWK and SLOWD
       *  TA_STOCHF : Returns the FASTK and FASTD
       *
       * The TA_STOCH function correspond to the more widely implemented version
       * found in many software/charting package. The TA_STOCHF is more rarely
       * used because its higher volatility cause often whipsaws.
       */
      /* Identify the lookback needed. */
      lookbackK = optInFastK_Period - 1;
      lookbackFastD = TA_MA_Lookback(optInFastD_Period,optInFastD_MAType);
      lookbackTotal = lookbackK + lookbackFastD;
      /* Move up the start index if there is not
       * enough initial data.
       */
      if( startIdx < lookbackTotal )
      {
         startIdx = lookbackTotal;
      }
      /* Make sure there is still something to evaluate. */
      if( startIdx > endIdx )
      {
         /* Succeed... but no data in the output. */
         dummyBegIdx = 0;
         dummyNBElement = 0;
         TA_MA_Close( sub0 ); if( !outStride ) TA_Free( sc_outFastK ); if( !outStride ) TA_Free( sc_outFastD );
         return TA_INSUFFICIENT_HISTORY;
      }
      /* Do the K calculation:
       *
       *    Kt = 100 x ((Ct-Lt)/(Ht-Lt))
       *
       * Kt is today stochastic
       * Ct is today closing price.
       * Lt is the lowest price of the last K Period (including today)
       * Ht is the highest price of the last K Period (including today)
       */
      /* Proceed with the calculation for the requested range.
       * Note that this algorithm allows the input and
       * output to be the same buffer.
       */
      outIdx = 0;
      /* Calculate just enough K for ending up with the caller
       * requested range. (The range of k must consider all
       * the lookback involve with the smoothing).
       */
      trailingIdx = startIdx - lookbackTotal;
      today = trailingIdx + lookbackK;
      highestIdx = 0 - 1;
      lowestIdx = highestIdx;
      lowest = 0.0;
      highest = lowest;
      diff = highest;
      /* Allocate a temporary buffer large enough to
       * store the K.
       *
       * When outFastK aliases a price input the caller buffer doubles as the
       * scratch, saving one allocation: the K writes trail the min/max window
       * reads, and the final memmove is overlap-safe. outFastD must NOT be
       * elected: the %D ma() below would then run in place over the raw K
       * that the memmove into outFastK still needs (issue #130).
       */
      bufferIsAllocated = 0;
      if( sc_outFastK == inHigh || sc_outFastK == inLow || sc_outFastK == inClose )
      {
         tempBuffer = sc_outFastK;
      } else 
      {
         bufferIsAllocated = 1;
         tempBuffer = malloc((endIdx - today + 1) * sizeof(double));
         if( !tempBuffer )
         {
            TA_MA_Close( sub0 ); if( !outStride ) TA_Free( sc_outFastK ); if( !outStride ) TA_Free( sc_outFastD );
            return TA_ALLOC_ERR;
         }
      }
      /* Do the K calculation */
      while( today <= endIdx )
      {
         /* Set the lowest low */
         tmp = inLow[today];
         if( lowestIdx < trailingIdx )
         {
            lowestIdx = trailingIdx;
            lowest = inLow[lowestIdx];
            i = lowestIdx;
            while( ++i <= today )
            {
               tmp = inLow[i];
               if( tmp < lowest )
               {
                  lowestIdx = i;
                  lowest = tmp;
               }
            }
            diff = (highest - lowest) / 100.0;
         } else if( tmp <= lowest )
         {
            lowestIdx = today;
            lowest = tmp;
            diff = (highest - lowest) / 100.0;
         }
         /* Set the highest high */
         tmp = inHigh[today];
         if( highestIdx < trailingIdx )
         {
            highestIdx = trailingIdx;
            highest = inHigh[highestIdx];
            i = highestIdx;
            while( ++i <= today )
            {
               tmp = inHigh[i];
               if( tmp > highest )
               {
                  highestIdx = i;
                  highest = tmp;
               }
            }
            diff = (highest - lowest) / 100.0;
         } else if( tmp >= highest )
         {
            highestIdx = today;
            highest = tmp;
            diff = (highest - lowest) / 100.0;
         }
         /* Calculate stochastic. The guard is not an exact `diff != 0.0`: a
          * machine-flat window leaves a sub-epsilon residue that an exact check
          * would divide into [0,100] noise (issue #107 / STOCHRSI). It is the
          * range against ITS OWN two extremes, not against a fixed band: the range
          * carries the quote unit, so a constant put against it answers "flat" for
          * every window of an instrument quoted below it and zeroed the whole
          * output (issue #253).
          */
         if( !TA_IS_ZERO_SCALED(highest - lowest, fabs(highest) + fabs(lowest)) )
         {
            tempBuffer[outIdx++] = (inClose[today] - lowest) / diff;
         } else 
         {
            tempBuffer[outIdx++] = 0.0;
         }
         trailingIdx += 1;
         today += 1;
      }
      /* Fast-K calculation completed. This K calculation is returned
       * to the caller. It is smoothed to become Fast-D.
       */
      /* Sub-stream 0: ma over `tempBuffer`, warmed from bar 0 up to the
       * sub-call's own startIdx (the seeding point). */
      {
         subRc = TA_MA_OpenAndFillInternal( &sub0, tempBuffer, (0), (outIdx - 1) + 1, optInFastD_Period, optInFastD_MAType, &dummyBegIdx, &dummyNBElement, sc_outFastD );
         if( subRc != TA_SUCCESS )
         {
            if( bufferIsAllocated )
            {
               free(tempBuffer);
            }
            TA_MA_Close( sub0 ); if( !outStride ) TA_Free( sc_outFastK ); if( !outStride ) TA_Free( sc_outFastD );
            return subRc;
         }
      }
      retCode = subRc;
      if( retCode != TA_SUCCESS || (int)dummyNBElement == 0 )
      {
         if( bufferIsAllocated )
         {
            free(tempBuffer);
         }
         /* Something wrong happen? No further data? */
         dummyBegIdx = 0;
         dummyNBElement = 0;
         TA_MA_Close( sub0 ); if( !outStride ) TA_Free( sc_outFastK ); if( !outStride ) TA_Free( sc_outFastD );
         return retCode;
      }
      /* Copy tempBuffer into the caller buffer.
       * (Calculation could not be done directly in the
       *  caller buffer because more input data then the
       *  requested range was needed for doing %D).
       */
      /* memmove, not memcpy: tempBuffer aliases outFastK when the caller buffer is
       * reused as scratch, so source and destination overlap (issue #94).
       */
      memmove(sc_outFastK,&tempBuffer[lookbackFastD],(int)dummyNBElement * sizeof(double));
      if( bufferIsAllocated )
      {
         free(tempBuffer);
      }
      /* Note: Keep the outBegIdx relative to the
       *       caller input before returning.
       */
      dummyBegIdx = startIdx;

      /* Capture the live producer state + sub handles. */
      if( dummyNBElement < 1 ) { TA_MA_Close( sub0 ); if( !outStride ) TA_Free( sc_outFastK ); if( !outStride ) TA_Free( sc_outFastD ); return TA_INSUFFICIENT_HISTORY; }
      sp = (struct TA_STOCHF_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) { TA_MA_Close( sub0 ); if( !outStride ) TA_Free( sc_outFastK ); if( !outStride ) TA_Free( sc_outFastD ); return TA_ALLOC_ERR; }
      memset( sp, 0, sizeof(*sp) );
      sp->optInFastK_Period = optInFastK_Period;
      sp->optInFastD_Period = optInFastD_Period;
      sp->optInFastD_MAType = optInFastD_MAType;
      sp->lowest = lowest;
      sp->highest = highest;
      sp->diff = diff;
      sp->lowestIdx = lowestIdx;
      sp->highestIdx = highestIdx;
      sp->trailingIdx = trailingIdx;
      sp->i = i;
      sp->today = today;
      sp->xCap = (int)(today - trailingIdx) + 1;
      if( sp->xCap < 1 || sp->xCap > historyLen ) { TA_MA_Close( sub0 ); if( !outStride ) TA_Free( sc_outFastK ); if( !outStride ) TA_Free( sc_outFastD ); TA_STOCHF_ReleaseImpl( sp ); return TA_INTERNAL_ERROR(386); }
      sp->xPhys = 1;
      while( sp->xPhys < sp->xCap ) sp->xPhys <<= 1;
      sp->xMask = sp->xPhys - 1;
      sp->x_inHigh = (double *)TA_Malloc( sizeof(double) * (size_t)sp->xPhys );
      if( !sp->x_inHigh ) { TA_MA_Close( sub0 ); if( !outStride ) TA_Free( sc_outFastK ); if( !outStride ) TA_Free( sc_outFastD ); TA_STOCHF_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
      sp->x_inLow = (double *)TA_Malloc( sizeof(double) * (size_t)sp->xPhys );
      if( !sp->x_inLow ) { TA_MA_Close( sub0 ); if( !outStride ) TA_Free( sc_outFastK ); if( !outStride ) TA_Free( sc_outFastD ); TA_STOCHF_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
      sp->x_inClose = (double *)TA_Malloc( sizeof(double) * (size_t)sp->xPhys );
      if( !sp->x_inClose ) { TA_MA_Close( sub0 ); if( !outStride ) TA_Free( sc_outFastK ); if( !outStride ) TA_Free( sc_outFastD ); TA_STOCHF_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
      { int fillJ;
        for( fillJ = historyLen - sp->xCap; fillJ < historyLen; fillJ++ )
        {
           sp->x_inHigh[fillJ & sp->xMask] = inHigh[fillJ];
           sp->x_inLow[fillJ & sp->xMask] = inLow[fillJ];
           sp->x_inClose[fillJ & sp->xMask] = inClose[fillJ];
        }
      }
      sp->sub0 = sub0;
      *outBegIdx = dummyBegIdx;
      *outNBElement = dummyNBElement;
      if( !outStride ) outFastK[0] = sc_outFastK[dummyNBElement - 1];
      if( !outStride ) outFastD[0] = sc_outFastD[dummyNBElement - 1];
      if( !outStride ) TA_Free( sc_outFastK );
      if( !outStride ) TA_Free( sc_outFastD );
      sp->outRangeBegIdx = *outBegIdx;
      sp->outRangeCount = *outNBElement;
      sp->cur_outFastK = outFastK[(*outNBElement - 1) * outStride];
      sp->cur_outFastD = outFastD[(*outNBElement - 1) * outStride];
      *stream = sp;
      return TA_SUCCESS;
   }
}

/* Private function, not in public API. */
TA_RetCode TA_STOCHF_OpenInternal( struct TA_STOCHF_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], int startIdx, int historyLen, int optInFastK_Period, int optInFastD_Period, TA_MAType optInFastD_MAType, double *outFastK, double *outFastD )
{
   TA_RetCode retCode;
   int dummyBegIdx = 0;
   int dummyNBElement = 0;
   double sink_outFastK = 0.0;
   double sink_outFastD = 0.0;
   retCode = TA_STOCHF_OpenImpl( stream, inHigh, inLow, inClose, startIdx, historyLen, optInFastK_Period, optInFastD_Period, optInFastD_MAType, &dummyBegIdx, &dummyNBElement, &sink_outFastK, &sink_outFastD, 0 );
   if( retCode == TA_SUCCESS )
   {
      *outFastK = sink_outFastK;
      *outFastD = sink_outFastD;
   }
   return retCode;
}

TA_LIB_API TA_RetCode TA_STOCHF_Open( TA_STOCHF_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], int historyLen, int optInFastK_Period, int optInFastD_Period, TA_MAType optInFastD_MAType, double *outFastK, double *outFastD )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !inClose || !outFastK || !outFastD ) return TA_BAD_PARAM;
   return TA_STOCHF_OpenInternal( stream, inHigh, inLow, inClose, 0, historyLen, optInFastK_Period, optInFastD_Period, optInFastD_MAType, outFastK, outFastD );
}

TA_LIB_API TA_RetCode TA_STOCHF_OpenAndFill( TA_STOCHF_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], int historyLen, int optInFastK_Period, int optInFastD_Period, TA_MAType optInFastD_MAType, int *outBegIdx, int *outNBElement, double outFastK[], double outFastD[] )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !inClose || !outBegIdx || !outNBElement || !outFastK || !outFastD ) return TA_BAD_PARAM;
   if( (const void *)outFastK == (const void *)inHigh || (const void *)outFastK == (const void *)inLow || (const void *)outFastK == (const void *)inClose || (const void *)outFastD == (const void *)inHigh || (const void *)outFastD == (const void *)inLow || (const void *)outFastD == (const void *)inClose || (const void *)outFastK == (const void *)outFastD ) return TA_BAD_PARAM;
   return TA_STOCHF_OpenAndFillInternal( stream, inHigh, inLow, inClose, 0, historyLen, optInFastK_Period, optInFastD_Period, optInFastD_MAType, outBegIdx, outNBElement, outFastK, outFastD );
}

/* Private function, not in public API. */
TA_RetCode TA_STOCHF_OpenAndFillInternal( struct TA_STOCHF_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], int startIdx, int historyLen, int optInFastK_Period, int optInFastD_Period, TA_MAType optInFastD_MAType, int *outBegIdx, int *outNBElement, double outFastK[], double outFastD[] )
{
   return TA_STOCHF_OpenImpl( stream, inHigh, inLow, inClose, startIdx, historyLen, optInFastK_Period, optInFastD_Period, optInFastD_MAType, outBegIdx, outNBElement, outFastK, outFastD, 1 );
}

TA_LIB_API TA_RetCode TA_STOCHF_Update( TA_STOCHF_Stream *stream, double inHigh, double inLow, double inClose, double *outFastK, double *outFastD )
{
   TA_RetCode retCode;

   if( !stream || !outFastK || !outFastD ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) || !TA_IS_FINITE( inClose ) )
   {
      if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
      return TA_BAD_PARAM;
   }
   retCode = TA_STOCHF_StepImpl( stream, inHigh, inLow, inClose, outFastK, outFastD );
   if( retCode != TA_SUCCESS ) return retCode;
   stream->cur_outFastK = *outFastK;
   stream->cur_outFastD = *outFastD;
   if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_STOCHF_Peek( const TA_STOCHF_Stream *stream, double inHigh, double inLow, double inClose, double *outFastK, double *outFastD )
{
   const struct TA_STOCHF_Stream *sp = stream;
   double cur_tempBuffer = 0.0;
   double cur_outFastD = 0.0;
   double tmp;
   double diff;
   double highest;
   int highestIdx;
   int i;
   double lowest;
   int lowestIdx;
   int today;
   int trailingIdx;
   double *x_inClose;
   double *x_inHigh;
   double *x_inLow;
   int pkSlot0 = -1;
   double pkVal0 = 0.0;
   int pkSlot1 = -1;
   double pkVal1 = 0.0;
   int pkSlot2 = -1;
   double pkVal2 = 0.0;

   if( !stream || !outFastK || !outFastD ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) || !TA_IS_FINITE( inClose ) ) return TA_BAD_PARAM;
   diff = sp->diff;
   highest = sp->highest;
   highestIdx = sp->highestIdx;
   i = sp->i;
   lowest = sp->lowest;
   lowestIdx = sp->lowestIdx;
   today = sp->today;
   trailingIdx = sp->trailingIdx;
   x_inClose = sp->x_inClose;
   x_inHigh = sp->x_inHigh;
   x_inLow = sp->x_inLow;
   if( today >= 1073741824 )
   {
      int rebaseShift = trailingIdx & ~sp->xMask;
      today -= rebaseShift;
      trailingIdx -= rebaseShift;
      highestIdx -= rebaseShift;
      i -= rebaseShift;
      lowestIdx -= rebaseShift;
   }
   pkSlot0 = today & sp->xMask;
   pkVal0 = inHigh;
   pkSlot1 = today & sp->xMask;
   pkVal1 = inLow;
   pkSlot2 = today & sp->xMask;
   pkVal2 = inClose;
   /* Set the lowest low */
   tmp = ((today & sp->xMask) != pkSlot1) ? x_inLow[today & sp->xMask] : pkVal1;
   if( lowestIdx < trailingIdx )
   {
      lowestIdx = trailingIdx;
      lowest = ((lowestIdx & sp->xMask) != pkSlot1) ? x_inLow[lowestIdx & sp->xMask] : pkVal1;
      i = lowestIdx;
      while( ++i <= today )
      {
         tmp = ((i & sp->xMask) != pkSlot1) ? x_inLow[i & sp->xMask] : pkVal1;
         if( tmp < lowest )
         {
            lowestIdx = i;
            lowest = tmp;
         }
      }
      diff = (highest - lowest) / 100.0;
   } else if( tmp <= lowest )
   {
      lowestIdx = today;
      lowest = tmp;
      diff = (highest - lowest) / 100.0;
   }
   /* Set the highest high */
   tmp = ((today & sp->xMask) != pkSlot0) ? x_inHigh[today & sp->xMask] : pkVal0;
   if( highestIdx < trailingIdx )
   {
      highestIdx = trailingIdx;
      highest = ((highestIdx & sp->xMask) != pkSlot0) ? x_inHigh[highestIdx & sp->xMask] : pkVal0;
      i = highestIdx;
      while( ++i <= today )
      {
         tmp = ((i & sp->xMask) != pkSlot0) ? x_inHigh[i & sp->xMask] : pkVal0;
         if( tmp > highest )
         {
            highestIdx = i;
            highest = tmp;
         }
      }
      diff = (highest - lowest) / 100.0;
   } else if( tmp >= highest )
   {
      highestIdx = today;
      highest = tmp;
      diff = (highest - lowest) / 100.0;
   }
   /* Calculate stochastic. The guard is not an exact `diff != 0.0`: a
    * machine-flat window leaves a sub-epsilon residue that an exact check
    * would divide into [0,100] noise (issue #107 / STOCHRSI). It is the
    * range against ITS OWN two extremes, not against a fixed band: the range
    * carries the quote unit, so a constant put against it answers "flat" for
    * every window of an instrument quoted below it and zeroed the whole
    * output (issue #253).
    */
   if( !TA_IS_ZERO_SCALED(highest - lowest, fabs(highest) + fabs(lowest)) )
   {
      cur_tempBuffer = ((((today & sp->xMask) != pkSlot2) ? x_inClose[today & sp->xMask] : pkVal2) - lowest) / diff;
   } else 
   {
      cur_tempBuffer = 0.0;
   }

   /* Pipeline the new bar through the sub-streams (batch tail order). */
   {
      TA_RetCode subRc = TA_MA_Peek( (const TA_MA_Stream *)sp->sub0, cur_tempBuffer, &cur_outFastD );
      if( subRc != TA_SUCCESS ) return subRc;
   }
   *outFastK = cur_tempBuffer;
   *outFastD = cur_outFastD;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_STOCHF_UpdateAndFill( TA_STOCHF_Stream *stream, const double inHigh[], const double inLow[], const double inClose[], int barCount, double outFastK[], double outFastD[] )
{
   int i;
   TA_RetCode retCode;

   if( !stream || !inHigh || !inLow || !inClose || !outFastK || !outFastD ) return TA_BAD_PARAM;
   if( barCount < 0 ) return TA_BAD_PARAM;
   if( (const void *)outFastK == (const void *)inHigh || (const void *)outFastK == (const void *)inLow || (const void *)outFastK == (const void *)inClose || (const void *)outFastD == (const void *)inHigh || (const void *)outFastD == (const void *)inLow || (const void *)outFastD == (const void *)inClose || (const void *)outFastK == (const void *)outFastD ) return TA_BAD_PARAM;
   for( i = 0; i < barCount; i++ )
   {
      if( !TA_IS_FINITE( inHigh[i] ) || !TA_IS_FINITE( inLow[i] ) || !TA_IS_FINITE( inClose[i] ) )
      {
         if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
         return TA_BAD_PARAM;
      }
      retCode = TA_STOCHF_StepImpl( stream, inHigh[i], inLow[i], inClose[i], &outFastK[i], &outFastD[i] );
      if( retCode != TA_SUCCESS ) return retCode;
      stream->cur_outFastK = outFastK[i];
      stream->cur_outFastD = outFastD[i];
      if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   }
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_STOCHF_Close( TA_STOCHF_Stream *stream )
{
   if( !stream ) return TA_SUCCESS;
   TA_MA_Close( stream->sub0 );
   TA_STOCHF_ReleaseImpl( stream );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_STOCHF_Value( const TA_STOCHF_Stream *stream, double *outFastK, double *outFastD )
{
   if( !stream || !outFastK || !outFastD ) return TA_BAD_PARAM;
   *outFastK = stream->cur_outFastK;
   *outFastD = stream->cur_outFastD;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_STOCHF_Clone( const TA_STOCHF_Stream *stream, TA_STOCHF_Stream **clone )
{
   struct TA_STOCHF_Stream *sp;

   if( !clone ) return TA_BAD_PARAM;
   *clone = NULL;
   if( !stream ) return TA_BAD_PARAM;
   sp = (struct TA_STOCHF_Stream *)TA_Malloc( sizeof(*sp) );
   if( !sp ) return TA_ALLOC_ERR;
   *sp = *stream;
   sp->x_inHigh = NULL;
   sp->x_inLow = NULL;
   sp->x_inClose = NULL;
   sp->sub0 = NULL;
   if( stream->x_inHigh )
   { size_t copyN = (size_t)(sp->xPhys);
     sp->x_inHigh = (double *)TA_Malloc( sizeof(double) * copyN );
     if( !sp->x_inHigh ) { TA_STOCHF_Close( sp ); return TA_ALLOC_ERR; }
     memcpy( sp->x_inHigh, stream->x_inHigh, sizeof(double) * copyN ); }
   if( stream->x_inLow )
   { size_t copyN = (size_t)(sp->xPhys);
     sp->x_inLow = (double *)TA_Malloc( sizeof(double) * copyN );
     if( !sp->x_inLow ) { TA_STOCHF_Close( sp ); return TA_ALLOC_ERR; }
     memcpy( sp->x_inLow, stream->x_inLow, sizeof(double) * copyN ); }
   if( stream->x_inClose )
   { size_t copyN = (size_t)(sp->xPhys);
     sp->x_inClose = (double *)TA_Malloc( sizeof(double) * copyN );
     if( !sp->x_inClose ) { TA_STOCHF_Close( sp ); return TA_ALLOC_ERR; }
     memcpy( sp->x_inClose, stream->x_inClose, sizeof(double) * copyN ); }
   if( stream->sub0 )
   { TA_RetCode subRc = TA_MA_Clone( stream->sub0, &sp->sub0 );
     if( subRc != TA_SUCCESS ) { TA_STOCHF_Close( sp ); return subRc; } }
   *clone = sp;
   return TA_SUCCESS;
}

