/* TA-LIB Copyright (c) 1999-2026, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_stream_private.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  MF       Mario Fortier
 *  PP       Peter Pudaite
 *  CF       Christo Fogelberg
 *
 * Change history:
 *
 *  MMDDYY BY    Description
 *  -------------------------------------------------------------------
 *  120802 MF    Template creation.
 *  091503 PP    Reworked TA_SAR to allow customisation of more SAR params.
 *  092103 MF    Some changes related on first round of tests
 *  092303 PP    Minor bug fixes.
 *  122104 MF,CF Fix#1089506 for out-of-bound access to ep_temp.
 *  082726 MF,CC Answer a rejected minus_dm before reading ep_temp, not after:
 *               the read was of an uninitialised local.
 */

TA_LIB_API int TA_SAREXT_Lookback( double optInStartValue, double optInOffsetOnReverse, double optInAccelerationInitLong, double optInAccelerationLong, double optInAccelerationMaxLong, double optInAccelerationInitShort, double optInAccelerationShort, double optInAccelerationMaxShort )
{
   if( optInStartValue == TA_REAL_DEFAULT )
      optInStartValue = 0;
   else if( !(optInStartValue >= TA_REAL_MIN && optInStartValue <= TA_REAL_MAX) )
      return -1;
   if( optInOffsetOnReverse == TA_REAL_DEFAULT )
      optInOffsetOnReverse = 0;
   else if( !(optInOffsetOnReverse >= 0e0 && optInOffsetOnReverse <= TA_REAL_MAX) )
      return -1;
   if( optInAccelerationInitLong == TA_REAL_DEFAULT )
      optInAccelerationInitLong = 0.02;
   else if( !(optInAccelerationInitLong >= 0e0 && optInAccelerationInitLong <= TA_REAL_MAX) )
      return -1;
   if( optInAccelerationLong == TA_REAL_DEFAULT )
      optInAccelerationLong = 0.02;
   else if( !(optInAccelerationLong >= 0e0 && optInAccelerationLong <= TA_REAL_MAX) )
      return -1;
   if( optInAccelerationMaxLong == TA_REAL_DEFAULT )
      optInAccelerationMaxLong = 0.2;
   else if( !(optInAccelerationMaxLong >= 0e0 && optInAccelerationMaxLong <= TA_REAL_MAX) )
      return -1;
   if( optInAccelerationInitShort == TA_REAL_DEFAULT )
      optInAccelerationInitShort = 0.02;
   else if( !(optInAccelerationInitShort >= 0e0 && optInAccelerationInitShort <= TA_REAL_MAX) )
      return -1;
   if( optInAccelerationShort == TA_REAL_DEFAULT )
      optInAccelerationShort = 0.02;
   else if( !(optInAccelerationShort >= 0e0 && optInAccelerationShort <= TA_REAL_MAX) )
      return -1;
   if( optInAccelerationMaxShort == TA_REAL_DEFAULT )
      optInAccelerationMaxShort = 0.2;
   else if( !(optInAccelerationMaxShort >= 0e0 && optInAccelerationMaxShort <= TA_REAL_MAX) )
      return -1;
   /* SAR always sacrifices one price bar to establish the
    * initial extreme price.
    */
   return 1;
}

TA_FMA_MULTIVERSION
TA_LIB_API TA_RetCode TA_SAREXT( int    startIdx,
                                 int    endIdx,
                                 const double inHigh[],
                                 const double inLow[],
                                 double optInStartValue,
                                 double optInOffsetOnReverse,
                                 double optInAccelerationInitLong,
                                 double optInAccelerationLong,
                                 double optInAccelerationMaxLong,
                                 double optInAccelerationInitShort,
                                 double optInAccelerationShort,
                                 double optInAccelerationMaxShort,
                                 int          *outBegIdx,
                                 int          *outNBElement,
                                 double        outReal[] )
{
   TA_RetCode retCode;
   int isLong;
   int todayIdx;
   int outIdx;
   int tempInt;
   double newHigh;
   double newLow;
   double prevHigh;
   double prevLow;
   double afLong;
   double afShort;
   double ep;
   double sar;
   double ep_temp[1];

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( optInStartValue == TA_REAL_DEFAULT )
      optInStartValue = 0;
   else if( !(optInStartValue >= TA_REAL_MIN && optInStartValue <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( optInOffsetOnReverse == TA_REAL_DEFAULT )
      optInOffsetOnReverse = 0;
   else if( !(optInOffsetOnReverse >= 0e0 && optInOffsetOnReverse <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( optInAccelerationInitLong == TA_REAL_DEFAULT )
      optInAccelerationInitLong = 0.02;
   else if( !(optInAccelerationInitLong >= 0e0 && optInAccelerationInitLong <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( optInAccelerationLong == TA_REAL_DEFAULT )
      optInAccelerationLong = 0.02;
   else if( !(optInAccelerationLong >= 0e0 && optInAccelerationLong <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( optInAccelerationMaxLong == TA_REAL_DEFAULT )
      optInAccelerationMaxLong = 0.2;
   else if( !(optInAccelerationMaxLong >= 0e0 && optInAccelerationMaxLong <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( optInAccelerationInitShort == TA_REAL_DEFAULT )
      optInAccelerationInitShort = 0.02;
   else if( !(optInAccelerationInitShort >= 0e0 && optInAccelerationInitShort <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( optInAccelerationShort == TA_REAL_DEFAULT )
      optInAccelerationShort = 0.02;
   else if( !(optInAccelerationShort >= 0e0 && optInAccelerationShort <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( optInAccelerationMaxShort == TA_REAL_DEFAULT )
      optInAccelerationMaxShort = 0.2;
   else if( !(optInAccelerationMaxShort >= 0e0 && optInAccelerationMaxShort <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   /* > 0 indicates long. == 0 indicates short */
   /* This function is the same as TA_SAR, except that the caller has
    * greater control on the SAR dynamic and initial state.
    *
    * In additon, the TA_SAREXT returns negative values when the position
    * is short. This allow to distinguish when the SAR do actually reverse.
    */
   /* Implementation of the SAR has been a little bit open to interpretation
    * since Wilder (the original author) did not define a precise algorithm
    * on how to bootstrap the algorithm. Take any existing software application
    * and you will see slight variation on how the algorithm was adapted.
    *
    * What is the initial trade direction? Long or short?
    * ===================================================
    * The interpretation of what should be the initial SAR values is
    * open to interpretation, particularly since the caller to the function
    * does not specify the initial direction of the trade.
    *
    * In TA-Lib, the following default logic is used:
    *  - Calculate +DM and -DM between the first and
    *    second bar. The highest directional indication will
    *    indicate the assumed direction of the trade for the second
    *    price bar.
    *  - In the case of a tie between +DM and -DM,
    *    the direction is LONG by default.
    *
    * What is the initial "extreme point" and thus SAR?
    * =================================================
    * The following shows how different people took different approach:
    *  - Metastock use the first price bar high/low depending of
    *    the direction. No SAR is calculated for the first price
    *    bar.
    *  - Tradestation use the closing price of the second bar. No
    *    SAR are calculated for the first price bar.
    *  - Wilder (the original author) use the SIP from the
    *    previous trade (cannot be implement here since the
    *    direction and length of the previous trade is unknonw).
    *  - The Magazine TASC seems to follow Wilder approach which
    *    is not practical here.
    *
    * TA-Lib "consume" the first price bar and use its high/low as the
    * initial SAR of the second price bar. I found that approach to be
    * the closest to Wilders idea of having the first entry day use
    * the previous extreme point, except that here the extreme point is
    * derived solely from the first price bar. I found the same approach
    * to be used by Metastock.
    *
    *
    * Can I force the initial SAR?
    * ============================
    * Yes. Using the optInStartValue_0 parameter:
    *  optInStartValue_0 >  0 : SAR is long at optInStartValue_0.
    *  optInStartValue_0 <  0 : SAR is short at fabs(optInStartValue_0).
    *
    * And when optInStartValue_0 == 0, the logic is the same as for TA_SAR
    * (See previous two sections).
    */
   /* Identify the minimum number of price bar needed
    * to calculate at least one output.
    *
    * Move up the start index if there is not
    * enough initial data.
    */
   if( startIdx < 1 )
   {
      startIdx = 1;
   }
   /* Make sure there is still something to evaluate. */
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   /* Check if the acceleration factors are being defined by the user.
    * Make sure the acceleration and maximum are coherent.
    * If not, correct the acceleration.
    * Default afLong = 0.02
    * Default afShort = 0.02
    */
   afLong = optInAccelerationInitLong;
   afShort = optInAccelerationInitShort;
   if( afLong > optInAccelerationMaxLong )
   {
      optInAccelerationInitLong = optInAccelerationMaxLong;
      afLong = optInAccelerationInitLong;
   }
   if( optInAccelerationLong > optInAccelerationMaxLong )
   {
      optInAccelerationLong = optInAccelerationMaxLong;
   }
   if( afShort > optInAccelerationMaxShort )
   {
      optInAccelerationInitShort = optInAccelerationMaxShort;
      afShort = optInAccelerationInitShort;
   }
   if( optInAccelerationShort > optInAccelerationMaxShort )
   {
      optInAccelerationShort = optInAccelerationMaxShort;
   }
   /* Initialise SAR calculations */
   if( optInStartValue == 0 )
   {
      /* Default action */
      /* Identify if the initial direction is long or short.
       * (ep is just used as a temp buffer here, the name
       *  of the parameter is not significant).
       */
      retCode = TA_MINUS_DM(startIdx,startIdx,inHigh,inLow,1,&tempInt,&tempInt,ep_temp);
      if( retCode != TA_SUCCESS )
      {
         *outBegIdx= 0;
         *outNBElement= 0;
         return retCode;
      }
      if( ep_temp[0] > 0 )
      {
         isLong = 0;
      } else 
      {
         isLong = 1;
      }
   } else if( optInStartValue > 0 )
   {
      /* Start Long */
      isLong = 1;
   } else 
   {
      /* optInStartValue_0 < 0 => Start Short */
      isLong = 0;
   }
   *outBegIdx= startIdx;
   outIdx = 0;
   /* Write the first SAR. */
   todayIdx = startIdx;
   newHigh = inHigh[todayIdx - 1];
   newLow = inLow[todayIdx - 1];
   if( optInStartValue == 0 )
   {
      /* Default action */
      if( isLong == 1 )
      {
         ep = inHigh[todayIdx];
         sar = newLow;
      } else 
      {
         ep = inLow[todayIdx];
         sar = newHigh;
      }
   } else if( optInStartValue > 0 )
   {
      /* Start Long at specified value. */
      ep = inHigh[todayIdx];
      sar = optInStartValue;
   } else 
   {
      /* if optInStartValue < 0 => Start Short at specified value. */
      ep = inLow[todayIdx];
      sar = fabs(optInStartValue);
   }
   /* Cheat on the newLow and newHigh for the
    * first iteration.
    */
   newLow = inLow[todayIdx];
   newHigh = inHigh[todayIdx];
   while( todayIdx <= endIdx )
   {
      prevLow = newLow;
      prevHigh = newHigh;
      newLow = inLow[todayIdx];
      newHigh = inHigh[todayIdx];
      todayIdx += 1;
      if( isLong == 1 )
      {
         /* Switch to short if the low penetrates the SAR value. */
         if( newLow <= sar )
         {
            /* Switch and Overide the SAR with the ep */
            isLong = 0;
            sar = ep;
            /* Make sure the overide SAR is within
             * yesterday's and today's range.
             */
            if( sar < prevHigh )
            {
               sar = prevHigh;
            }
            if( sar < newHigh )
            {
               sar = newHigh;
            }
            /* Output the overide SAR */
            if( optInOffsetOnReverse != 0.0 )
            {
               sar += sar * optInOffsetOnReverse;
            }
            outReal[outIdx++] = 0 - sar;
            /* Adjust afShort and ep */
            afShort = optInAccelerationInitShort;
            ep = newLow;
            /* Calculate the new SAR */
            sar = fma(afShort, ep - sar, sar);
            /* Make sure the new SAR is within
             * yesterday's and today's range.
             */
            if( sar < prevHigh )
            {
               sar = prevHigh;
            }
            if( sar < newHigh )
            {
               sar = newHigh;
            }
         } else 
         {
            /* No switch */
            /* Output the SAR (was calculated in the previous iteration) */
            outReal[outIdx++] = sar;
            /* Adjust afLong and ep. */
            if( newHigh > ep )
            {
               ep = newHigh;
               afLong += optInAccelerationLong;
               if( afLong > optInAccelerationMaxLong )
               {
                  afLong = optInAccelerationMaxLong;
               }
            }
            /* Calculate the new SAR */
            sar = fma(afLong, ep - sar, sar);
            /* Make sure the new SAR is within
             * yesterday's and today's range.
             */
            if( sar > prevLow )
            {
               sar = prevLow;
            }
            if( sar > newLow )
            {
               sar = newLow;
            }
         }
      /* Switch to long if the high penetrates the SAR value. */
      } else if( newHigh >= sar )
      {
         /* Switch and Overide the SAR with the ep */
         isLong = 1;
         sar = ep;
         /* Make sure the overide SAR is within
          * yesterday's and today's range.
          */
         if( sar > prevLow )
         {
            sar = prevLow;
         }
         if( sar > newLow )
         {
            sar = newLow;
         }
         /* Output the overide SAR */
         if( optInOffsetOnReverse != 0.0 )
         {
            sar -= sar * optInOffsetOnReverse;
         }
         outReal[outIdx++] = sar;
         /* Adjust afLong and ep */
         afLong = optInAccelerationInitLong;
         ep = newHigh;
         /* Calculate the new SAR */
         sar = fma(afLong, ep - sar, sar);
         /* Make sure the new SAR is within
          * yesterday's and today's range.
          */
         if( sar > prevLow )
         {
            sar = prevLow;
         }
         if( sar > newLow )
         {
            sar = newLow;
         }
      } else 
      {
         /* No switch */
         /* Output the SAR (was calculated in the previous iteration) */
         outReal[outIdx++] = 0 - sar;
         /* Adjust afShort and ep. */
         if( newLow < ep )
         {
            ep = newLow;
            afShort += optInAccelerationShort;
            if( afShort > optInAccelerationMaxShort )
            {
               afShort = optInAccelerationMaxShort;
            }
         }
         /* Calculate the new SAR */
         sar = fma(afShort, ep - sar, sar);
         /* Make sure the new SAR is within
          * yesterday's and today's range.
          */
         if( sar < prevHigh )
         {
            sar = prevHigh;
         }
         if( sar < newHigh )
         {
            sar = newHigh;
         }
      }
   }
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

TA_FMA_MULTIVERSION
TA_RetCode TA_S_SAREXT( int    startIdx,
                        int    endIdx,
                        const float inHigh[],
                        const float inLow[],
                        double optInStartValue,
                        double optInOffsetOnReverse,
                        double optInAccelerationInitLong,
                        double optInAccelerationLong,
                        double optInAccelerationMaxLong,
                        double optInAccelerationInitShort,
                        double optInAccelerationShort,
                        double optInAccelerationMaxShort,
                        int          *outBegIdx,
                        int          *outNBElement,
                        double        outReal[] )
{
   TA_RetCode retCode;
   int isLong;
   int todayIdx;
   int outIdx;
   int tempInt;
   double newHigh;
   double newLow;
   double prevHigh;
   double prevLow;
   double afLong;
   double afShort;
   double ep;
   double sar;
   double ep_temp[1];

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( optInStartValue == TA_REAL_DEFAULT )
      optInStartValue = 0;
   else if( !(optInStartValue >= TA_REAL_MIN && optInStartValue <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( optInOffsetOnReverse == TA_REAL_DEFAULT )
      optInOffsetOnReverse = 0;
   else if( !(optInOffsetOnReverse >= 0e0 && optInOffsetOnReverse <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( optInAccelerationInitLong == TA_REAL_DEFAULT )
      optInAccelerationInitLong = 0.02;
   else if( !(optInAccelerationInitLong >= 0e0 && optInAccelerationInitLong <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( optInAccelerationLong == TA_REAL_DEFAULT )
      optInAccelerationLong = 0.02;
   else if( !(optInAccelerationLong >= 0e0 && optInAccelerationLong <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( optInAccelerationMaxLong == TA_REAL_DEFAULT )
      optInAccelerationMaxLong = 0.2;
   else if( !(optInAccelerationMaxLong >= 0e0 && optInAccelerationMaxLong <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( optInAccelerationInitShort == TA_REAL_DEFAULT )
      optInAccelerationInitShort = 0.02;
   else if( !(optInAccelerationInitShort >= 0e0 && optInAccelerationInitShort <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( optInAccelerationShort == TA_REAL_DEFAULT )
      optInAccelerationShort = 0.02;
   else if( !(optInAccelerationShort >= 0e0 && optInAccelerationShort <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( optInAccelerationMaxShort == TA_REAL_DEFAULT )
      optInAccelerationMaxShort = 0.2;
   else if( !(optInAccelerationMaxShort >= 0e0 && optInAccelerationMaxShort <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   if( startIdx < 1 )
   {
      startIdx = 1;
   }
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   afLong = optInAccelerationInitLong;
   afShort = optInAccelerationInitShort;
   if( afLong > optInAccelerationMaxLong )
   {
      optInAccelerationInitLong = optInAccelerationMaxLong;
      afLong = optInAccelerationInitLong;
   }
   if( optInAccelerationLong > optInAccelerationMaxLong )
   {
      optInAccelerationLong = optInAccelerationMaxLong;
   }
   if( afShort > optInAccelerationMaxShort )
   {
      optInAccelerationInitShort = optInAccelerationMaxShort;
      afShort = optInAccelerationInitShort;
   }
   if( optInAccelerationShort > optInAccelerationMaxShort )
   {
      optInAccelerationShort = optInAccelerationMaxShort;
   }
   if( optInStartValue == 0 )
   {
      retCode = TA_S_MINUS_DM(startIdx,startIdx,inHigh,inLow,1,&tempInt,&tempInt,ep_temp);
      if( retCode != TA_SUCCESS )
      {
         *outBegIdx= 0;
         *outNBElement= 0;
         return retCode;
      }
      if( ep_temp[0] > 0 )
      {
         isLong = 0;
      } else 
      {
         isLong = 1;
      }
   } else if( optInStartValue > 0 )
   {
      isLong = 1;
   } else 
   {
      isLong = 0;
   }
   *outBegIdx= startIdx;
   outIdx = 0;
   todayIdx = startIdx;
   newHigh = (double)inHigh[todayIdx - 1];
   newLow = (double)inLow[todayIdx - 1];
   if( optInStartValue == 0 )
   {
      if( isLong == 1 )
      {
         ep = (double)inHigh[todayIdx];
         sar = newLow;
      } else 
      {
         ep = (double)inLow[todayIdx];
         sar = newHigh;
      }
   } else if( optInStartValue > 0 )
   {
      ep = (double)inHigh[todayIdx];
      sar = optInStartValue;
   } else 
   {
      ep = (double)inLow[todayIdx];
      sar = fabs(optInStartValue);
   }
   newLow = (double)inLow[todayIdx];
   newHigh = (double)inHigh[todayIdx];
   while( todayIdx <= endIdx )
   {
      prevLow = newLow;
      prevHigh = newHigh;
      newLow = (double)inLow[todayIdx];
      newHigh = (double)inHigh[todayIdx];
      todayIdx += 1;
      if( isLong == 1 )
      {
         if( newLow <= sar )
         {
            isLong = 0;
            sar = ep;
            if( sar < prevHigh )
            {
               sar = prevHigh;
            }
            if( sar < newHigh )
            {
               sar = newHigh;
            }
            if( optInOffsetOnReverse != 0.0 )
            {
               sar += sar * optInOffsetOnReverse;
            }
            outReal[outIdx++] = 0 - sar;
            afShort = optInAccelerationInitShort;
            ep = newLow;
            sar = fma(afShort, ep - sar, sar);
            if( sar < prevHigh )
            {
               sar = prevHigh;
            }
            if( sar < newHigh )
            {
               sar = newHigh;
            }
         } else 
         {
            outReal[outIdx++] = sar;
            if( newHigh > ep )
            {
               ep = newHigh;
               afLong += optInAccelerationLong;
               if( afLong > optInAccelerationMaxLong )
               {
                  afLong = optInAccelerationMaxLong;
               }
            }
            sar = fma(afLong, ep - sar, sar);
            if( sar > prevLow )
            {
               sar = prevLow;
            }
            if( sar > newLow )
            {
               sar = newLow;
            }
         }
      } else if( newHigh >= sar )
      {
         isLong = 1;
         sar = ep;
         if( sar > prevLow )
         {
            sar = prevLow;
         }
         if( sar > newLow )
         {
            sar = newLow;
         }
         if( optInOffsetOnReverse != 0.0 )
         {
            sar -= sar * optInOffsetOnReverse;
         }
         outReal[outIdx++] = sar;
         afLong = optInAccelerationInitLong;
         ep = newHigh;
         sar = fma(afLong, ep - sar, sar);
         if( sar > prevLow )
         {
            sar = prevLow;
         }
         if( sar > newLow )
         {
            sar = newLow;
         }
      } else 
      {
         outReal[outIdx++] = 0 - sar;
         if( newLow < ep )
         {
            ep = newLow;
            afShort += optInAccelerationShort;
            if( afShort > optInAccelerationMaxShort )
            {
               afShort = optInAccelerationMaxShort;
            }
         }
         sar = fma(afShort, ep - sar, sar);
         if( sar < prevHigh )
         {
            sar = prevHigh;
         }
         if( sar < newHigh )
         {
            sar = newHigh;
         }
      }
   }
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

/**** Streaming API *****/

struct TA_SAREXT_Stream {
   /* The bars this handle has an output for (see TA_StreamOutRange).
    * Kept first, and in this order, in every stream struct. */
   int outRangeBegIdx;
   int outRangeCount;
   /* The value(s) at the last bar the stream counted (see TA_SAREXT_Value). */
   double cur_outReal;
   double optInStartValue;
   double optInOffsetOnReverse;
   double optInAccelerationInitLong;
   double optInAccelerationLong;
   double optInAccelerationMaxLong;
   double optInAccelerationInitShort;
   double optInAccelerationShort;
   double optInAccelerationMaxShort;
   int isLong;
   double newHigh;
   double newLow;
   double afLong;
   double afShort;
   double ep;
   double sar;
};

/* Private function, not in public API. */
static void TA_SAREXT_StepImpl( struct TA_SAREXT_Stream *sp, double inHigh, double inLow, double *outReal )
{
   double prevHigh;
   double prevLow;
   double newHigh;
   double newLow;
   double sar;

   newHigh = sp->newHigh;
   newLow = sp->newLow;
   sar = sp->sar;
   prevLow = newLow;
   prevHigh = newHigh;
   newLow = inLow;
   newHigh = inHigh;
   if( sp->isLong == 1 )
   {
      /* Switch to short if the low penetrates the SAR value. */
      if( newLow <= sar )
      {
         /* Switch and Overide the SAR with the ep */
         sp->isLong = 0;
         sar = sp->ep;
         /* Make sure the overide SAR is within
          * yesterday's and today's range.
          */
         if( sar < prevHigh )
         {
            sar = prevHigh;
         }
         if( sar < newHigh )
         {
            sar = newHigh;
         }
         /* Output the overide SAR */
         if( sp->optInOffsetOnReverse != 0.0 )
         {
            sar += sar * sp->optInOffsetOnReverse;
         }
         *outReal= 0 - sar;
         /* Adjust afShort and ep */
         sp->afShort = sp->optInAccelerationInitShort;
         sp->ep = newLow;
         /* Calculate the new SAR */
         sar = fma(sp->afShort, sp->ep - sar, sar);
         /* Make sure the new SAR is within
          * yesterday's and today's range.
          */
         if( sar < prevHigh )
         {
            sar = prevHigh;
         }
         if( sar < newHigh )
         {
            sar = newHigh;
         }
      } else 
      {
         /* No switch */
         /* Output the SAR (was calculated in the previous iteration) */
         *outReal= sar;
         /* Adjust afLong and ep. */
         if( newHigh > sp->ep )
         {
            sp->ep = newHigh;
            sp->afLong += sp->optInAccelerationLong;
            if( sp->afLong > sp->optInAccelerationMaxLong )
            {
               sp->afLong = sp->optInAccelerationMaxLong;
            }
         }
         /* Calculate the new SAR */
         sar = fma(sp->afLong, sp->ep - sar, sar);
         /* Make sure the new SAR is within
          * yesterday's and today's range.
          */
         if( sar > prevLow )
         {
            sar = prevLow;
         }
         if( sar > newLow )
         {
            sar = newLow;
         }
      }
   /* Switch to long if the high penetrates the SAR value. */
   } else if( newHigh >= sar )
   {
      /* Switch and Overide the SAR with the ep */
      sp->isLong = 1;
      sar = sp->ep;
      /* Make sure the overide SAR is within
       * yesterday's and today's range.
       */
      if( sar > prevLow )
      {
         sar = prevLow;
      }
      if( sar > newLow )
      {
         sar = newLow;
      }
      /* Output the overide SAR */
      if( sp->optInOffsetOnReverse != 0.0 )
      {
         sar -= sar * sp->optInOffsetOnReverse;
      }
      *outReal= sar;
      /* Adjust afLong and ep */
      sp->afLong = sp->optInAccelerationInitLong;
      sp->ep = newHigh;
      /* Calculate the new SAR */
      sar = fma(sp->afLong, sp->ep - sar, sar);
      /* Make sure the new SAR is within
       * yesterday's and today's range.
       */
      if( sar > prevLow )
      {
         sar = prevLow;
      }
      if( sar > newLow )
      {
         sar = newLow;
      }
   } else 
   {
      /* No switch */
      /* Output the SAR (was calculated in the previous iteration) */
      *outReal= 0 - sar;
      /* Adjust afShort and ep. */
      if( newLow < sp->ep )
      {
         sp->ep = newLow;
         sp->afShort += sp->optInAccelerationShort;
         if( sp->afShort > sp->optInAccelerationMaxShort )
         {
            sp->afShort = sp->optInAccelerationMaxShort;
         }
      }
      /* Calculate the new SAR */
      sar = fma(sp->afShort, sp->ep - sar, sar);
      /* Make sure the new SAR is within
       * yesterday's and today's range.
       */
      if( sar < prevHigh )
      {
         sar = prevHigh;
      }
      if( sar < newHigh )
      {
         sar = newHigh;
      }
   }
   sp->cur_outReal = *outReal;
   sp->newHigh = newHigh;
   sp->newLow = newLow;
   sp->sar = sar;
}

static TA_RetCode TA_SAREXT_OpenImpl( struct TA_SAREXT_Stream **stream, const double inHigh[], const double inLow[], int startIdx, int historyLen, double optInStartValue, double optInOffsetOnReverse, double optInAccelerationInitLong, double optInAccelerationLong, double optInAccelerationMaxLong, double optInAccelerationInitShort, double optInAccelerationShort, double optInAccelerationMaxShort, int *outBegIdx, int *outNBElement, double outReal[], int outStride )
{
   struct TA_SAREXT_Stream *sp;
   int endIdx;
   int dummyBegIdx;
   int dummyNBElement;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !outReal ) return TA_BAD_PARAM;
   if( optInStartValue == TA_REAL_DEFAULT )
      optInStartValue = 0;
   else if( !(optInStartValue >= TA_REAL_MIN && optInStartValue <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( optInOffsetOnReverse == TA_REAL_DEFAULT )
      optInOffsetOnReverse = 0;
   else if( !(optInOffsetOnReverse >= 0e0 && optInOffsetOnReverse <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( optInAccelerationInitLong == TA_REAL_DEFAULT )
      optInAccelerationInitLong = 0.02;
   else if( !(optInAccelerationInitLong >= 0e0 && optInAccelerationInitLong <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( optInAccelerationLong == TA_REAL_DEFAULT )
      optInAccelerationLong = 0.02;
   else if( !(optInAccelerationLong >= 0e0 && optInAccelerationLong <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( optInAccelerationMaxLong == TA_REAL_DEFAULT )
      optInAccelerationMaxLong = 0.2;
   else if( !(optInAccelerationMaxLong >= 0e0 && optInAccelerationMaxLong <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( optInAccelerationInitShort == TA_REAL_DEFAULT )
      optInAccelerationInitShort = 0.02;
   else if( !(optInAccelerationInitShort >= 0e0 && optInAccelerationInitShort <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( optInAccelerationShort == TA_REAL_DEFAULT )
      optInAccelerationShort = 0.02;
   else if( !(optInAccelerationShort >= 0e0 && optInAccelerationShort <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( optInAccelerationMaxShort == TA_REAL_DEFAULT )
      optInAccelerationMaxShort = 0.2;
   else if( !(optInAccelerationMaxShort >= 0e0 && optInAccelerationMaxShort <= TA_REAL_MAX) )
      return TA_BAD_PARAM;
   if( startIdx > historyLen - 1 )
   {
      *outBegIdx = 0;
      *outNBElement = 0;
      return TA_INSUFFICIENT_HISTORY;
   }

   endIdx = historyLen - 1;
   dummyBegIdx = 0;
   dummyNBElement = 0;
   (void)startIdx; (void)dummyBegIdx; (void)dummyNBElement;

   {
      TA_RetCode retCode;
      int isLong = 0;
      /* > 0 indicates long. == 0 indicates short */
      int todayIdx;
      int outIdx;
      int tempInt;
      double newHigh = 0.0;
      double newLow = 0.0;
      double prevHigh;
      double prevLow;
      double afLong = 0.0;
      double afShort = 0.0;
      double ep = 0.0;
      double sar = 0.0;
      double ep_temp[1];
      /* This function is the same as TA_SAR, except that the caller has
       * greater control on the SAR dynamic and initial state.
       *
       * In additon, the TA_SAREXT returns negative values when the position
       * is short. This allow to distinguish when the SAR do actually reverse.
       */
      /* Implementation of the SAR has been a little bit open to interpretation
       * since Wilder (the original author) did not define a precise algorithm
       * on how to bootstrap the algorithm. Take any existing software application
       * and you will see slight variation on how the algorithm was adapted.
       *
       * What is the initial trade direction? Long or short?
       * ===================================================
       * The interpretation of what should be the initial SAR values is
       * open to interpretation, particularly since the caller to the function
       * does not specify the initial direction of the trade.
       *
       * In TA-Lib, the following default logic is used:
       *  - Calculate +DM and -DM between the first and
       *    second bar. The highest directional indication will
       *    indicate the assumed direction of the trade for the second
       *    price bar.
       *  - In the case of a tie between +DM and -DM,
       *    the direction is LONG by default.
       *
       * What is the initial "extreme point" and thus SAR?
       * =================================================
       * The following shows how different people took different approach:
       *  - Metastock use the first price bar high/low depending of
       *    the direction. No SAR is calculated for the first price
       *    bar.
       *  - Tradestation use the closing price of the second bar. No
       *    SAR are calculated for the first price bar.
       *  - Wilder (the original author) use the SIP from the
       *    previous trade (cannot be implement here since the
       *    direction and length of the previous trade is unknonw).
       *  - The Magazine TASC seems to follow Wilder approach which
       *    is not practical here.
       *
       * TA-Lib "consume" the first price bar and use its high/low as the
       * initial SAR of the second price bar. I found that approach to be
       * the closest to Wilders idea of having the first entry day use
       * the previous extreme point, except that here the extreme point is
       * derived solely from the first price bar. I found the same approach
       * to be used by Metastock.
       *
       *
       * Can I force the initial SAR?
       * ============================
       * Yes. Using the optInStartValue_0 parameter:
       *  optInStartValue_0 >  0 : SAR is long at optInStartValue_0.
       *  optInStartValue_0 <  0 : SAR is short at fabs(optInStartValue_0).
       *
       * And when optInStartValue_0 == 0, the logic is the same as for TA_SAR
       * (See previous two sections).
       */
      /* Identify the minimum number of price bar needed
       * to calculate at least one output.
       *
       * Move up the start index if there is not
       * enough initial data.
       */
      if( startIdx < 1 )
      {
         startIdx = 1;
      }
      /* Make sure there is still something to evaluate. */
      if( startIdx > endIdx )
      {
         *outBegIdx= 0;
         *outNBElement= 0;
         return TA_INSUFFICIENT_HISTORY;
      }
      /* Check if the acceleration factors are being defined by the user.
       * Make sure the acceleration and maximum are coherent.
       * If not, correct the acceleration.
       * Default afLong = 0.02
       * Default afShort = 0.02
       */
      afLong = optInAccelerationInitLong;
      afShort = optInAccelerationInitShort;
      if( afLong > optInAccelerationMaxLong )
      {
         optInAccelerationInitLong = optInAccelerationMaxLong;
         afLong = optInAccelerationInitLong;
      }
      if( optInAccelerationLong > optInAccelerationMaxLong )
      {
         optInAccelerationLong = optInAccelerationMaxLong;
      }
      if( afShort > optInAccelerationMaxShort )
      {
         optInAccelerationInitShort = optInAccelerationMaxShort;
         afShort = optInAccelerationInitShort;
      }
      if( optInAccelerationShort > optInAccelerationMaxShort )
      {
         optInAccelerationShort = optInAccelerationMaxShort;
      }
      /* Initialise SAR calculations */
      if( optInStartValue == 0 )
      {
         /* Default action */
         /* Identify if the initial direction is long or short.
          * (ep is just used as a temp buffer here, the name
          *  of the parameter is not significant).
          */
         retCode = TA_MINUS_DM(startIdx,startIdx,inHigh,inLow,1,&tempInt,&tempInt,ep_temp);
         if( retCode != TA_SUCCESS )
         {
            *outBegIdx= 0;
            *outNBElement= 0;
            return retCode;
         }
         if( ep_temp[0] > 0 )
         {
            isLong = 0;
         } else 
         {
            isLong = 1;
         }
      } else if( optInStartValue > 0 )
      {
         /* Start Long */
         isLong = 1;
      } else 
      {
         /* optInStartValue_0 < 0 => Start Short */
         isLong = 0;
      }
      *outBegIdx= startIdx;
      outIdx = 0;
      /* Write the first SAR. */
      todayIdx = startIdx;
      newHigh = inHigh[todayIdx - 1];
      newLow = inLow[todayIdx - 1];
      if( optInStartValue == 0 )
      {
         /* Default action */
         if( isLong == 1 )
         {
            ep = inHigh[todayIdx];
            sar = newLow;
         } else 
         {
            ep = inLow[todayIdx];
            sar = newHigh;
         }
      } else if( optInStartValue > 0 )
      {
         /* Start Long at specified value. */
         ep = inHigh[todayIdx];
         sar = optInStartValue;
      } else 
      {
         /* if optInStartValue < 0 => Start Short at specified value. */
         ep = inLow[todayIdx];
         sar = fabs(optInStartValue);
      }
      /* Cheat on the newLow and newHigh for the
       * first iteration.
       */
      newLow = inLow[todayIdx];
      newHigh = inHigh[todayIdx];
      while( todayIdx <= endIdx )
      {
         prevLow = newLow;
         prevHigh = newHigh;
         newLow = inLow[todayIdx];
         newHigh = inHigh[todayIdx];
         todayIdx += 1;
         if( isLong == 1 )
         {
            /* Switch to short if the low penetrates the SAR value. */
            if( newLow <= sar )
            {
               /* Switch and Overide the SAR with the ep */
               isLong = 0;
               sar = ep;
               /* Make sure the overide SAR is within
                * yesterday's and today's range.
                */
               if( sar < prevHigh )
               {
                  sar = prevHigh;
               }
               if( sar < newHigh )
               {
                  sar = newHigh;
               }
               /* Output the overide SAR */
               if( optInOffsetOnReverse != 0.0 )
               {
                  sar += sar * optInOffsetOnReverse;
               }
               outReal[outIdx++ * outStride] = 0 - sar;
               /* Adjust afShort and ep */
               afShort = optInAccelerationInitShort;
               ep = newLow;
               /* Calculate the new SAR */
               sar = fma(afShort, ep - sar, sar);
               /* Make sure the new SAR is within
                * yesterday's and today's range.
                */
               if( sar < prevHigh )
               {
                  sar = prevHigh;
               }
               if( sar < newHigh )
               {
                  sar = newHigh;
               }
            } else 
            {
               /* No switch */
               /* Output the SAR (was calculated in the previous iteration) */
               outReal[outIdx++ * outStride] = sar;
               /* Adjust afLong and ep. */
               if( newHigh > ep )
               {
                  ep = newHigh;
                  afLong += optInAccelerationLong;
                  if( afLong > optInAccelerationMaxLong )
                  {
                     afLong = optInAccelerationMaxLong;
                  }
               }
               /* Calculate the new SAR */
               sar = fma(afLong, ep - sar, sar);
               /* Make sure the new SAR is within
                * yesterday's and today's range.
                */
               if( sar > prevLow )
               {
                  sar = prevLow;
               }
               if( sar > newLow )
               {
                  sar = newLow;
               }
            }
         /* Switch to long if the high penetrates the SAR value. */
         } else if( newHigh >= sar )
         {
            /* Switch and Overide the SAR with the ep */
            isLong = 1;
            sar = ep;
            /* Make sure the overide SAR is within
             * yesterday's and today's range.
             */
            if( sar > prevLow )
            {
               sar = prevLow;
            }
            if( sar > newLow )
            {
               sar = newLow;
            }
            /* Output the overide SAR */
            if( optInOffsetOnReverse != 0.0 )
            {
               sar -= sar * optInOffsetOnReverse;
            }
            outReal[outIdx++ * outStride] = sar;
            /* Adjust afLong and ep */
            afLong = optInAccelerationInitLong;
            ep = newHigh;
            /* Calculate the new SAR */
            sar = fma(afLong, ep - sar, sar);
            /* Make sure the new SAR is within
             * yesterday's and today's range.
             */
            if( sar > prevLow )
            {
               sar = prevLow;
            }
            if( sar > newLow )
            {
               sar = newLow;
            }
         } else 
         {
            /* No switch */
            /* Output the SAR (was calculated in the previous iteration) */
            outReal[outIdx++ * outStride] = 0 - sar;
            /* Adjust afShort and ep. */
            if( newLow < ep )
            {
               ep = newLow;
               afShort += optInAccelerationShort;
               if( afShort > optInAccelerationMaxShort )
               {
                  afShort = optInAccelerationMaxShort;
               }
            }
            /* Calculate the new SAR */
            sar = fma(afShort, ep - sar, sar);
            /* Make sure the new SAR is within
             * yesterday's and today's range.
             */
            if( sar < prevHigh )
            {
               sar = prevHigh;
            }
            if( sar < newHigh )
            {
               sar = newHigh;
            }
         }
      }
      *outNBElement= outIdx;

      /* Capture the live batch state into the handle. */
      sp = (struct TA_SAREXT_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) { return TA_ALLOC_ERR; }
      memset( sp, 0, sizeof(*sp) );
      sp->optInStartValue = optInStartValue;
      sp->optInOffsetOnReverse = optInOffsetOnReverse;
      sp->optInAccelerationInitLong = optInAccelerationInitLong;
      sp->optInAccelerationLong = optInAccelerationLong;
      sp->optInAccelerationMaxLong = optInAccelerationMaxLong;
      sp->optInAccelerationInitShort = optInAccelerationInitShort;
      sp->optInAccelerationShort = optInAccelerationShort;
      sp->optInAccelerationMaxShort = optInAccelerationMaxShort;
      sp->isLong = isLong;
      sp->newHigh = newHigh;
      sp->newLow = newLow;
      sp->afLong = afLong;
      sp->afShort = afShort;
      sp->ep = ep;
      sp->sar = sar;
      sp->outRangeBegIdx = *outBegIdx;
      sp->outRangeCount = *outNBElement;
      sp->cur_outReal = outReal[(*outNBElement - 1) * outStride];
      *stream = sp;
      return TA_SUCCESS;
   }
}

/* Private function, not in public API. */
TA_RetCode TA_SAREXT_OpenInternal( struct TA_SAREXT_Stream **stream, const double inHigh[], const double inLow[], int startIdx, int historyLen, double optInStartValue, double optInOffsetOnReverse, double optInAccelerationInitLong, double optInAccelerationLong, double optInAccelerationMaxLong, double optInAccelerationInitShort, double optInAccelerationShort, double optInAccelerationMaxShort, double *outReal )
{
   TA_RetCode retCode;
   int dummyBegIdx = 0;
   int dummyNBElement = 0;
   double sink_outReal = 0.0;
   retCode = TA_SAREXT_OpenImpl( stream, inHigh, inLow, startIdx, historyLen, optInStartValue, optInOffsetOnReverse, optInAccelerationInitLong, optInAccelerationLong, optInAccelerationMaxLong, optInAccelerationInitShort, optInAccelerationShort, optInAccelerationMaxShort, &dummyBegIdx, &dummyNBElement, &sink_outReal, 0 );
   if( retCode == TA_SUCCESS )
   {
      *outReal = sink_outReal;
   }
   return retCode;
}

TA_LIB_API TA_RetCode TA_SAREXT_Open( TA_SAREXT_Stream **stream, const double inHigh[], const double inLow[], int historyLen, double optInStartValue, double optInOffsetOnReverse, double optInAccelerationInitLong, double optInAccelerationLong, double optInAccelerationMaxLong, double optInAccelerationInitShort, double optInAccelerationShort, double optInAccelerationMaxShort, double *outReal )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !outReal ) return TA_BAD_PARAM;
   return TA_SAREXT_OpenInternal( stream, inHigh, inLow, 0, historyLen, optInStartValue, optInOffsetOnReverse, optInAccelerationInitLong, optInAccelerationLong, optInAccelerationMaxLong, optInAccelerationInitShort, optInAccelerationShort, optInAccelerationMaxShort, outReal );
}

TA_LIB_API TA_RetCode TA_SAREXT_OpenAndFill( TA_SAREXT_Stream **stream, const double inHigh[], const double inLow[], int historyLen, double optInStartValue, double optInOffsetOnReverse, double optInAccelerationInitLong, double optInAccelerationLong, double optInAccelerationMaxLong, double optInAccelerationInitShort, double optInAccelerationShort, double optInAccelerationMaxShort, int *outBegIdx, int *outNBElement, double outReal[] )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !outBegIdx || !outNBElement || !outReal ) return TA_BAD_PARAM;
   if( (const void *)outReal == (const void *)inHigh || (const void *)outReal == (const void *)inLow ) return TA_BAD_PARAM;
   return TA_SAREXT_OpenAndFillInternal( stream, inHigh, inLow, 0, historyLen, optInStartValue, optInOffsetOnReverse, optInAccelerationInitLong, optInAccelerationLong, optInAccelerationMaxLong, optInAccelerationInitShort, optInAccelerationShort, optInAccelerationMaxShort, outBegIdx, outNBElement, outReal );
}

/* Private function, not in public API. */
TA_RetCode TA_SAREXT_OpenAndFillInternal( struct TA_SAREXT_Stream **stream, const double inHigh[], const double inLow[], int startIdx, int historyLen, double optInStartValue, double optInOffsetOnReverse, double optInAccelerationInitLong, double optInAccelerationLong, double optInAccelerationMaxLong, double optInAccelerationInitShort, double optInAccelerationShort, double optInAccelerationMaxShort, int *outBegIdx, int *outNBElement, double outReal[] )
{
   return TA_SAREXT_OpenImpl( stream, inHigh, inLow, startIdx, historyLen, optInStartValue, optInOffsetOnReverse, optInAccelerationInitLong, optInAccelerationLong, optInAccelerationMaxLong, optInAccelerationInitShort, optInAccelerationShort, optInAccelerationMaxShort, outBegIdx, outNBElement, outReal, 1 );
}

TA_LIB_API TA_RetCode TA_SAREXT_Update( TA_SAREXT_Stream *stream, double inHigh, double inLow, double *outReal )
{
   if( !stream || !outReal ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) )
   {
      if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
      return TA_BAD_PARAM;
   }
   TA_SAREXT_StepImpl( stream, inHigh, inLow, outReal );
   if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_SAREXT_Peek( const TA_SAREXT_Stream *stream, double inHigh, double inLow, double *outReal )
{
   struct TA_SAREXT_Stream scratch;
   struct TA_SAREXT_Stream *sp = &scratch;
   double prevHigh;
   double prevLow;
   double newHigh;
   double newLow;
   double sar;

   if( !stream || !outReal ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) ) return TA_BAD_PARAM;
   scratch = *stream;
   newHigh = sp->newHigh;
   newLow = sp->newLow;
   sar = sp->sar;
   prevLow = newLow;
   prevHigh = newHigh;
   newLow = inLow;
   newHigh = inHigh;
   if( sp->isLong == 1 )
   {
      /* Switch to short if the low penetrates the SAR value. */
      if( newLow <= sar )
      {
         /* Switch and Overide the SAR with the ep */
         sp->isLong = 0;
         sar = sp->ep;
         /* Make sure the overide SAR is within
          * yesterday's and today's range.
          */
         if( sar < prevHigh )
         {
            sar = prevHigh;
         }
         if( sar < newHigh )
         {
            sar = newHigh;
         }
         /* Output the overide SAR */
         if( sp->optInOffsetOnReverse != 0.0 )
         {
            sar += sar * sp->optInOffsetOnReverse;
         }
         *outReal= 0 - sar;
         /* Adjust afShort and ep */
         sp->afShort = sp->optInAccelerationInitShort;
         sp->ep = newLow;
         /* Calculate the new SAR */
         sar = fma(sp->afShort, sp->ep - sar, sar);
         /* Make sure the new SAR is within
          * yesterday's and today's range.
          */
         if( sar < prevHigh )
         {
            sar = prevHigh;
         }
         if( sar < newHigh )
         {
            sar = newHigh;
         }
      } else 
      {
         /* No switch */
         /* Output the SAR (was calculated in the previous iteration) */
         *outReal= sar;
         /* Adjust afLong and ep. */
         if( newHigh > sp->ep )
         {
            sp->ep = newHigh;
            sp->afLong += sp->optInAccelerationLong;
            if( sp->afLong > sp->optInAccelerationMaxLong )
            {
               sp->afLong = sp->optInAccelerationMaxLong;
            }
         }
         /* Calculate the new SAR */
         sar = fma(sp->afLong, sp->ep - sar, sar);
         /* Make sure the new SAR is within
          * yesterday's and today's range.
          */
         if( sar > prevLow )
         {
            sar = prevLow;
         }
         if( sar > newLow )
         {
            sar = newLow;
         }
      }
   /* Switch to long if the high penetrates the SAR value. */
   } else if( newHigh >= sar )
   {
      /* Switch and Overide the SAR with the ep */
      sp->isLong = 1;
      sar = sp->ep;
      /* Make sure the overide SAR is within
       * yesterday's and today's range.
       */
      if( sar > prevLow )
      {
         sar = prevLow;
      }
      if( sar > newLow )
      {
         sar = newLow;
      }
      /* Output the overide SAR */
      if( sp->optInOffsetOnReverse != 0.0 )
      {
         sar -= sar * sp->optInOffsetOnReverse;
      }
      *outReal= sar;
      /* Adjust afLong and ep */
      sp->afLong = sp->optInAccelerationInitLong;
      sp->ep = newHigh;
      /* Calculate the new SAR */
      sar = fma(sp->afLong, sp->ep - sar, sar);
      /* Make sure the new SAR is within
       * yesterday's and today's range.
       */
      if( sar > prevLow )
      {
         sar = prevLow;
      }
      if( sar > newLow )
      {
         sar = newLow;
      }
   } else 
   {
      /* No switch */
      /* Output the SAR (was calculated in the previous iteration) */
      *outReal= 0 - sar;
      /* Adjust afShort and ep. */
      if( newLow < sp->ep )
      {
         sp->ep = newLow;
         sp->afShort += sp->optInAccelerationShort;
         if( sp->afShort > sp->optInAccelerationMaxShort )
         {
            sp->afShort = sp->optInAccelerationMaxShort;
         }
      }
      /* Calculate the new SAR */
      sar = fma(sp->afShort, sp->ep - sar, sar);
      /* Make sure the new SAR is within
       * yesterday's and today's range.
       */
      if( sar < prevHigh )
      {
         sar = prevHigh;
      }
      if( sar < newHigh )
      {
         sar = newHigh;
      }
   }
   sp->cur_outReal = *outReal;
   sp->newHigh = newHigh;
   sp->newLow = newLow;
   sp->sar = sar;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_SAREXT_UpdateAndFill( TA_SAREXT_Stream *stream, const double inHigh[], const double inLow[], int barCount, double outReal[] )
{
   int i;

   if( !stream || !inHigh || !inLow || !outReal ) return TA_BAD_PARAM;
   if( barCount < 0 ) return TA_BAD_PARAM;
   if( (const void *)outReal == (const void *)inHigh || (const void *)outReal == (const void *)inLow ) return TA_BAD_PARAM;
   for( i = 0; i < barCount; i++ )
   {
      if( !TA_IS_FINITE( inHigh[i] ) || !TA_IS_FINITE( inLow[i] ) )
      {
         if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
         return TA_BAD_PARAM;
      }
      TA_SAREXT_StepImpl( stream, inHigh[i], inLow[i], &outReal[i] );
      if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   }
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_SAREXT_Close( TA_SAREXT_Stream *stream )
{
   if( stream ) TA_Free( stream );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_SAREXT_Value( const TA_SAREXT_Stream *stream, double *outReal )
{
   if( !stream || !outReal ) return TA_BAD_PARAM;
   *outReal = stream->cur_outReal;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_SAREXT_Clone( const TA_SAREXT_Stream *stream, TA_SAREXT_Stream **clone )
{
   struct TA_SAREXT_Stream *sp;

   if( !clone ) return TA_BAD_PARAM;
   *clone = NULL;
   if( !stream ) return TA_BAD_PARAM;
   sp = (struct TA_SAREXT_Stream *)TA_Malloc( sizeof(*sp) );
   if( !sp ) return TA_ALLOC_ERR;
   *sp = *stream;
   *clone = sp;
   return TA_SUCCESS;
}

