/* TA-LIB Copyright (c) 1999-2026, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_stream_private.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  MF       Mario Fortier
 *  KL       Kevin Lin (@kevinlincg)
 *  CC       Claude Code (AI assistant)
 *
 * Change history:
 *
 *  MMDDYY BY     Description
 *  -------------------------------------------------------------------
 *  100126 KL,CC  Creation (#486).
 */

TA_LIB_API int TA_SWAK_BP_Lookback( int optInTimePeriod, double optInDelta )
{
   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 20;
   else if( (int)optInTimePeriod < 5 || (int)optInTimePeriod > 2000 )
      return -1;
   if( optInDelta == TA_REAL_DEFAULT )
      optInDelta = 0.1;
   else if( !(optInDelta >= 5e-2 && optInDelta <= 5e-1) )
      return -1;
   /* No structural lookback: the two input slots and the two output slots are
    * seeded from the first bar rather than read from before it, and there is
    * no callee whose lookback could be inherited (ha.c:16-19).
    */
   return TA_GLOBALS_UNSTABLE_PERIOD(TA_FUNC_UNST_SWAK_BP,Swak_bp);
}

TA_LIB_API int TA_SWAK_BP_DisplayShift( int optInTimePeriod, double optInDelta, int outputIdx )
{
   if( TA_SWAK_BP_Lookback( optInTimePeriod, optInDelta ) < 0 )
      return INT_MIN;
   if( outputIdx < 0 || outputIdx >= 1 )
      return INT_MIN;
   return 0;
}

TA_FMA_MULTIVERSION
TA_LIB_API TA_RetCode TA_SWAK_BP( int    startIdx,
                                  int    endIdx,
                                  const double inReal[],
                                  int optInTimePeriod,
                                  double optInDelta,
                                  int          *outBegIdx,
                                  int          *outNBElement,
                                  double        outReal[] )
{
   int i;
   int outIdx;
   int today;
   int lookbackTotal;
   double w;
   double beta;
   double t;
   double abp;
   double c0;
   double a1;
   double a2;
   double x0;
   double x1;
   double x2;
   double y;
   double y1;
   double y2;

   if( (startIdx < 0) || (startIdx > TA_INDEX_MAX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_INDEX_MAX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 20;
   else if( (int)optInTimePeriod < 5 || (int)optInTimePeriod > 2000 )
      return TA_BAD_PARAM;
   if( optInDelta == TA_REAL_DEFAULT )
      optInDelta = 0.1;
   else if( !(optInDelta >= 5e-2 && optInDelta <= 5e-1) )
      return TA_BAD_PARAM;
   if( !inReal )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   *outBegIdx= 0;
   *outNBElement= 0;
   lookbackTotal = TA_SWAK_BP_Lookback(optInTimePeriod,optInDelta);
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   if( startIdx > endIdx )
   {
      return TA_SUCCESS;
   }
   /* The band-pass row (Ehlers, Stocks & Commodities January 2006, Figure 5).
    * The paper's 360/P is a full turn, so 2*pi/P; beta is the cosine of the
    * centre frequency and t is the half-bandwidth angle.
    */
   w = 2.0 * 3.141592653589793 / (double)optInTimePeriod;
   beta = cos(w);
   t = 4.0 * 3.141592653589793 * optInDelta / (double)optInTimePeriod;
   /* abp is written as (1 - sin t)/cos t rather than the paper's
    * gamma - sqrt(gamma^2 - 1) with gamma = 1/cos t. The two are equal for
    * 0 < t < pi/2, which this function's ranges guarantee (t <= 0.4*pi), but
    * the published form cancels as t -> 0 because gamma^2 - 1 goes as t^2.
    * Against a 60-digit reference the published form is already 4.5e-13 off
    * at the period cap; this one is not, and that is what lets the cap be
    * 2000 rather than 1000.
    */
   abp = (1.0 - sin(t)) / cos(t);
   /* The numerator (1, 0, -1) is zero both on a constant and on a Nyquist
    * alternation, so this row answers 0 at DC and at Nyquist, and exactly 1
    * with zero phase at the centre period itself.
    */
   c0 = (1.0 - abp) / 2.0;
   a1 = beta * (1.0 + abp);
   a2 = -abp;
   today = startIdx - lookbackTotal;
   /* Start in the steady state of a constant input equal to the first bar: a
    * band-pass of a constant is 0, so both output slots start there while both
    * input slots hold the bar. The input slots are carried in locals and never
    * re-read from inReal, because outReal may alias it.
    */
   x1 = inReal[today];
   x2 = x1;
   y1 = 0.0;
   y2 = 0.0;
   /* Skip the unstable period: run the recurrence but publish nothing. */
   i = lookbackTotal;
   while( i != 0 )
   {
      x0 = inReal[today];
      y = fma(a1, y1, fma(a2, y2, c0 * (x0 - x2)));
      x2 = x1;
      x1 = x0;
      y2 = y1;
      y1 = y;
      today += 1;
      i -= 1;
   }
   outIdx = 0;
   while( today <= endIdx )
   {
      /* The evaluation order is the bit-exactness contract across backends:
       * the numerator as c0*(x0 - x2), then the a1 feedback, then a2. The
       * middle tap is zero and dropped rather than added, which costs an
       * operation per bar and nothing else: adding 0.0*x1 would land on the
       * same bits, +0.0 for a cancelled numerator included.
       */
      x0 = inReal[today];
      y = fma(a1, y1, fma(a2, y2, c0 * (x0 - x2)));
      x2 = x1;
      x1 = x0;
      y2 = y1;
      y1 = y;
      outReal[outIdx] = y;
      outIdx = outIdx + 1;
      today += 1;
   }
   *outNBElement= outIdx;
   *outBegIdx= startIdx;
   return TA_SUCCESS;
}

TA_FMA_MULTIVERSION
TA_RetCode TA_S_SWAK_BP( int    startIdx,
                         int    endIdx,
                         const float inReal[],
                         int optInTimePeriod,
                         double optInDelta,
                         int          *outBegIdx,
                         int          *outNBElement,
                         double        outReal[] )
{
   int i;
   int outIdx;
   int today;
   int lookbackTotal;
   double w;
   double beta;
   double t;
   double abp;
   double c0;
   double a1;
   double a2;
   double x0;
   double x1;
   double x2;
   double y;
   double y1;
   double y2;

   if( (startIdx < 0) || (startIdx > TA_INDEX_MAX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_INDEX_MAX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 20;
   else if( (int)optInTimePeriod < 5 || (int)optInTimePeriod > 2000 )
      return TA_BAD_PARAM;
   if( optInDelta == TA_REAL_DEFAULT )
      optInDelta = 0.1;
   else if( !(optInDelta >= 5e-2 && optInDelta <= 5e-1) )
      return TA_BAD_PARAM;
   if( !inReal )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   *outBegIdx= 0;
   *outNBElement= 0;
   lookbackTotal = TA_SWAK_BP_Lookback(optInTimePeriod,optInDelta);
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   if( startIdx > endIdx )
   {
      return TA_SUCCESS;
   }
   w = 2.0 * 3.141592653589793 / (double)optInTimePeriod;
   beta = cos(w);
   t = 4.0 * 3.141592653589793 * optInDelta / (double)optInTimePeriod;
   abp = (1.0 - sin(t)) / cos(t);
   c0 = (1.0 - abp) / 2.0;
   a1 = beta * (1.0 + abp);
   a2 = -abp;
   today = startIdx - lookbackTotal;
   x1 = (double)inReal[today];
   x2 = x1;
   y1 = 0.0;
   y2 = 0.0;
   i = lookbackTotal;
   while( i != 0 )
   {
      x0 = (double)inReal[today];
      y = fma(a1, y1, fma(a2, y2, c0 * (x0 - x2)));
      x2 = x1;
      x1 = x0;
      y2 = y1;
      y1 = y;
      today += 1;
      i -= 1;
   }
   outIdx = 0;
   while( today <= endIdx )
   {
      x0 = (double)inReal[today];
      y = fma(a1, y1, fma(a2, y2, c0 * (x0 - x2)));
      x2 = x1;
      x1 = x0;
      y2 = y1;
      y1 = y;
      outReal[outIdx] = y;
      outIdx = outIdx + 1;
      today += 1;
   }
   *outNBElement= outIdx;
   *outBegIdx= startIdx;
   return TA_SUCCESS;
}

/**** Streaming API *****/

struct TA_SWAK_BP_Stream {
   /* The bars this handle has an output for (see TA_SWAK_BP_OutRange). */
   int outRangeBegIdx;
   int outRangeCount;
   /* The value(s) at the last bar the stream counted (see TA_SWAK_BP_Value). */
   double cur_outReal;
   int optInTimePeriod;
   double optInDelta;
   double c0;
   double a1;
   double a2;
   double pad_0;
   double x1;
   double x2;
   double y1;
   double y2;
};

/* Private function, not in public API. */
static TA_FMA_STEP_INLINE void TA_SWAK_BP_StepImpl( struct TA_SWAK_BP_Stream *sp, double inReal, double *outReal )
{
   double x0;
   double y;

   /* The evaluation order is the bit-exactness contract across backends:
    * the numerator as c0*(x0 - x2), then the a1 feedback, then a2. The
    * middle tap is zero and dropped rather than added, which costs an
    * operation per bar and nothing else: adding 0.0*x1 would land on the
    * same bits, +0.0 for a cancelled numerator included.
    */
   x0 = inReal;
   y = fma(sp->a1, sp->y1, fma(sp->a2, sp->y2, sp->c0 * (x0 - sp->x2)));
   sp->x2 = sp->x1;
   sp->x1 = x0;
   sp->y2 = sp->y1;
   sp->y1 = y;
   *outReal= y;
   sp->cur_outReal = *outReal;
}

static TA_RetCode TA_SWAK_BP_OpenImpl( struct TA_SWAK_BP_Stream **stream, const double inReal[], int startIdx, int historyLen, int optInTimePeriod, double optInDelta, int *outBegIdx, int *outNBElement, double outReal[], int outStride )
{
   struct TA_SWAK_BP_Stream *sp;
   int endIdx;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_INDEX_MAX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inReal || !outReal ) return TA_BAD_PARAM;
   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 20;
   else if( (int)optInTimePeriod < 5 || (int)optInTimePeriod > 2000 )
      return TA_BAD_PARAM;
   if( optInDelta == TA_REAL_DEFAULT )
      optInDelta = 0.1;
   else if( !(optInDelta >= 5e-2 && optInDelta <= 5e-1) )
      return TA_BAD_PARAM;
   if( startIdx > historyLen - 1 )
   {
      *outBegIdx = 0;
      *outNBElement = 0;
      return TA_INSUFFICIENT_HISTORY;
   }

   endIdx = historyLen - 1;

   {
      int i;
      int outIdx;
      int today;
      int lookbackTotal;
      double w;
      double beta;
      double t;
      double abp;
      double c0 = 0.0;
      double a1 = 0.0;
      double a2 = 0.0;
      double x0;
      double x1 = 0.0;
      double x2 = 0.0;
      double y;
      double y1 = 0.0;
      double y2 = 0.0;
      *outBegIdx= 0;
      *outNBElement= 0;
      lookbackTotal = TA_SWAK_BP_Lookback(optInTimePeriod,optInDelta);
      if( startIdx < lookbackTotal )
      {
         startIdx = lookbackTotal;
      }
      if( startIdx > endIdx )
      {
         return TA_INSUFFICIENT_HISTORY;
      }
      /* The band-pass row (Ehlers, Stocks & Commodities January 2006, Figure 5).
       * The paper's 360/P is a full turn, so 2*pi/P; beta is the cosine of the
       * centre frequency and t is the half-bandwidth angle.
       */
      w = 2.0 * 3.141592653589793 / (double)optInTimePeriod;
      beta = cos(w);
      t = 4.0 * 3.141592653589793 * optInDelta / (double)optInTimePeriod;
      /* abp is written as (1 - sin t)/cos t rather than the paper's
       * gamma - sqrt(gamma^2 - 1) with gamma = 1/cos t. The two are equal for
       * 0 < t < pi/2, which this function's ranges guarantee (t <= 0.4*pi), but
       * the published form cancels as t -> 0 because gamma^2 - 1 goes as t^2.
       * Against a 60-digit reference the published form is already 4.5e-13 off
       * at the period cap; this one is not, and that is what lets the cap be
       * 2000 rather than 1000.
       */
      abp = (1.0 - sin(t)) / cos(t);
      /* The numerator (1, 0, -1) is zero both on a constant and on a Nyquist
       * alternation, so this row answers 0 at DC and at Nyquist, and exactly 1
       * with zero phase at the centre period itself.
       */
      c0 = (1.0 - abp) / 2.0;
      a1 = beta * (1.0 + abp);
      a2 = -abp;
      today = startIdx - lookbackTotal;
      /* Start in the steady state of a constant input equal to the first bar: a
       * band-pass of a constant is 0, so both output slots start there while both
       * input slots hold the bar. The input slots are carried in locals and never
       * re-read from inReal, because outReal may alias it.
       */
      x1 = inReal[today];
      x2 = x1;
      y1 = 0.0;
      y2 = 0.0;
      /* Skip the unstable period: run the recurrence but publish nothing. */
      i = lookbackTotal;
      while( i != 0 )
      {
         x0 = inReal[today];
         y = fma(a1, y1, fma(a2, y2, c0 * (x0 - x2)));
         x2 = x1;
         x1 = x0;
         y2 = y1;
         y1 = y;
         today += 1;
         i -= 1;
      }
      outIdx = 0;
      while( today <= endIdx )
      {
         /* The evaluation order is the bit-exactness contract across backends:
          * the numerator as c0*(x0 - x2), then the a1 feedback, then a2. The
          * middle tap is zero and dropped rather than added, which costs an
          * operation per bar and nothing else: adding 0.0*x1 would land on the
          * same bits, +0.0 for a cancelled numerator included.
          */
         x0 = inReal[today];
         y = fma(a1, y1, fma(a2, y2, c0 * (x0 - x2)));
         x2 = x1;
         x1 = x0;
         y2 = y1;
         y1 = y;
         outReal[outIdx * outStride] = y;
         outIdx = outIdx + 1;
         today += 1;
      }
      *outNBElement= outIdx;
      *outBegIdx= startIdx;

      /* Capture the live batch state into the handle. */
      sp = (struct TA_SWAK_BP_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) { return TA_ALLOC_ERR; }
      memset( sp, 0, sizeof(*sp) );
      sp->optInTimePeriod = optInTimePeriod;
      sp->optInDelta = optInDelta;
      sp->c0 = c0;
      sp->a1 = a1;
      sp->a2 = a2;
      sp->x1 = x1;
      sp->x2 = x2;
      sp->y1 = y1;
      sp->y2 = y2;
      sp->outRangeBegIdx = *outBegIdx;
      sp->outRangeCount = *outNBElement;
      sp->cur_outReal = outReal[(*outNBElement - 1) * outStride];
      *stream = sp;
      return TA_SUCCESS;
   }
}

/* Private function, not in public API. */
TA_RetCode TA_SWAK_BP_OpenInternal( struct TA_SWAK_BP_Stream **stream, const double inReal[], int startIdx, int historyLen, int optInTimePeriod, double optInDelta, double *outReal )
{
   TA_RetCode retCode;
   int dummyBegIdx = 0;
   int dummyNBElement = 0;
   double sink_outReal = 0.0;
   retCode = TA_SWAK_BP_OpenImpl( stream, inReal, startIdx, historyLen, optInTimePeriod, optInDelta, &dummyBegIdx, &dummyNBElement, &sink_outReal, 0 );
   if( retCode == TA_SUCCESS )
   {
      *outReal = sink_outReal;
   }
   return retCode;
}

TA_LIB_API TA_RetCode TA_SWAK_BP_Open( TA_SWAK_BP_Stream **stream, const double inReal[], int historyLen, int optInTimePeriod, double optInDelta, double *outReal )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_INDEX_MAX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inReal || !outReal ) return TA_BAD_PARAM;
   return TA_SWAK_BP_OpenInternal( stream, inReal, 0, historyLen, optInTimePeriod, optInDelta, outReal );
}

TA_LIB_API TA_RetCode TA_SWAK_BP_OpenAndFill( TA_SWAK_BP_Stream **stream, const double inReal[], int historyLen, int optInTimePeriod, double optInDelta, int *outBegIdx, int *outNBElement, double outReal[] )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_INDEX_MAX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inReal || !outBegIdx || !outNBElement || !outReal ) return TA_BAD_PARAM;
   if( (const void *)outReal == (const void *)inReal ) return TA_BAD_PARAM;
   return TA_SWAK_BP_OpenAndFillInternal( stream, inReal, 0, historyLen, optInTimePeriod, optInDelta, outBegIdx, outNBElement, outReal );
}

/* Private function, not in public API. */
TA_RetCode TA_SWAK_BP_OpenAndFillInternal( struct TA_SWAK_BP_Stream **stream, const double inReal[], int startIdx, int historyLen, int optInTimePeriod, double optInDelta, int *outBegIdx, int *outNBElement, double outReal[] )
{
   return TA_SWAK_BP_OpenImpl( stream, inReal, startIdx, historyLen, optInTimePeriod, optInDelta, outBegIdx, outNBElement, outReal, 1 );
}

TA_FMA_MULTIVERSION
TA_LIB_API TA_RetCode TA_SWAK_BP_Update( TA_SWAK_BP_Stream *stream, double inReal, double *outReal )
{
   if( !stream ) return TA_BAD_PARAM;
   if( stream->outRangeBegIdx + stream->outRangeCount > TA_INDEX_MAX )
      return TA_OUT_OF_RANGE_END_INDEX;
   if( !outReal ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inReal ) ) return TA_BAD_PARAM;
   TA_SWAK_BP_StepImpl( stream, inReal, outReal );
   stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_FMA_MULTIVERSION
TA_LIB_API TA_RetCode TA_SWAK_BP_Peek( const TA_SWAK_BP_Stream *stream, double inReal, double *outReal )
{
   const struct TA_SWAK_BP_Stream *sp = stream;
   double x0;
   double y;
   double x1;
   double x2;
   double y1;
   double y2;

   if( !stream || !outReal ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inReal ) ) return TA_BAD_PARAM;
   x1 = sp->x1;
   x2 = sp->x2;
   y1 = sp->y1;
   y2 = sp->y2;
   /* The evaluation order is the bit-exactness contract across backends:
    * the numerator as c0*(x0 - x2), then the a1 feedback, then a2. The
    * middle tap is zero and dropped rather than added, which costs an
    * operation per bar and nothing else: adding 0.0*x1 would land on the
    * same bits, +0.0 for a cancelled numerator included.
    */
   x0 = inReal;
   y = fma(sp->a1, y1, fma(sp->a2, y2, sp->c0 * (x0 - x2)));
   x2 = x1;
   x1 = x0;
   y2 = y1;
   y1 = y;
   *outReal= y;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_SWAK_BP_Close( TA_SWAK_BP_Stream *stream )
{
   if( stream ) TA_Free( stream );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_SWAK_BP_Value( const TA_SWAK_BP_Stream *stream, double *outReal )
{
   if( !stream || !outReal ) return TA_BAD_PARAM;
   *outReal = stream->cur_outReal;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_SWAK_BP_OutRange( const TA_SWAK_BP_Stream *stream, int *outBegIdx, int *outNBElement )
{
   if( !stream || !outBegIdx || !outNBElement ) return TA_BAD_PARAM;
   *outBegIdx = stream->outRangeBegIdx;
   *outNBElement = stream->outRangeCount;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_SWAK_BP_Advance( TA_SWAK_BP_Stream *stream )
{
   if( !stream ) return TA_BAD_PARAM;
   if( stream->outRangeBegIdx + stream->outRangeCount > TA_INDEX_MAX )
      return TA_OUT_OF_RANGE_END_INDEX;
   stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_SWAK_BP_Clone( const TA_SWAK_BP_Stream *stream, TA_SWAK_BP_Stream **clone )
{
   struct TA_SWAK_BP_Stream *sp;

   if( !clone ) return TA_BAD_PARAM;
   *clone = NULL;
   if( !stream ) return TA_BAD_PARAM;
   sp = (struct TA_SWAK_BP_Stream *)TA_Malloc( sizeof(*sp) );
   if( !sp ) return TA_ALLOC_ERR;
   *sp = *stream;
   *clone = sp;
   return TA_SUCCESS;
}

