/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_unguarded.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  MF       Mario Fortier
 *  AA       Andrew Atkinson
 *  CC       Claude Code (AI assistant)
 *
 * Change history:
 *
 *  MMDDYY BY     Description
 *  -------------------------------------------------------------------
 *  112400 MF     Template creation.
 *  052603 MF     Adapt code to compile with .NET Managed C++
 *  020605 AA     Fix #1117656. NULL pointer assignement.
 *  070526 MF,CC  Speed optimization: single lockstep pass (bit-exact
 *                for startIdx <= lookback). Fix #98: partial-range
 *                output was mislabeled by up to one EMA lookback.
 */

TA_LIB_API int TA_TRIX_Lookback( int optInTimePeriod )
{
   int emaLookback;
   if( (int)optInTimePeriod == (int)0x80000000 )
      optInTimePeriod = 30;
   else if( (int)optInTimePeriod < 1 || (int)optInTimePeriod > 100000 )
      return -1;
   emaLookback = TA_EMA_Lookback(optInTimePeriod);
   return emaLookback * 3 + TA_ROCR_Lookback(1);
}

TA_LIB_API TA_RetCode TA_TRIX( int    startIdx,
                               int    endIdx,
                               const double inReal[],
                               int optInTimePeriod,
                               int          *outBegIdx,
                               int          *outNBElement,
                               double        outReal[] )
{
   double prevEMA1;
   double prevEMA2;
   double prevEMA3;
   double tempReal;
   double optInK_1;
   int i;
   int today;
   int outIdx;
   int lookbackEMA;
   int lookbackTotal;

   if( startIdx < 0 )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( !inReal )
      return TA_BAD_PARAM;
   if( (int)optInTimePeriod == (int)0x80000000 )
      optInTimePeriod = 30;
   else if( (int)optInTimePeriod < 1 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   /* TRIX = 1-day percent rate-of-change of a triple EMA. */
   /* Will change only on success. */
   *outNBElement= 0;
   *outBegIdx= 0;
   /* Adjust startIdx to account for the lookback period. */
   lookbackEMA = TA_EMA_Lookback(optInTimePeriod);
   lookbackTotal = lookbackEMA * 3 + TA_ROCR_Lookback(1);
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   /* Make sure there is still something to evaluate. */
   if( startIdx > endIdx )
   {
      return TA_SUCCESS;
   }
   /* Single lockstep pass: EMA1 feeds EMA2 feeds EMA3, output is the
    * roc() of consecutive EMA3 values. Output element j is the TRIX
    * of bar startIdx+j (fix #98). The arithmetic order below is the
    * bit-exactness contract — do not reorder or fuse operations; the
    * seed sums accumulate from 0.0 in production order (0.0+x is not
    * x for x=-0.0). In-place safe: outReal[outIdx] is written after
    * inReal[startIdx+outIdx] was read.
    */
   optInK_1 = 2.0 / (double)(optInTimePeriod + 1);
   if( TA_GLOBALS_COMPATIBILITY == ENUM_VALUE(Compatibility,TA_COMPATIBILITY_DEFAULT,Default) )
   {
      /* Seed EMA1 with a simple average of the first
       * 'period' price bars.
       */
      today = startIdx - lookbackTotal;
      i = optInTimePeriod;
      tempReal = 0.0;
      while( i-- > 0 )
      {
         tempReal += inReal[today++];
      }
      prevEMA1 = tempReal / optInTimePeriod;
      /* Advance EMA1 alone through its unstable period, up to
       * the bar where EMA2 seeding begins.
       */
      while( today <= startIdx - (lookbackEMA * 2 + 1) )
      {
         prevEMA1 = (inReal[today++] - prevEMA1) * optInK_1 + prevEMA1;
      }
      /* Seed EMA2 with a simple average of the first 'period'
       * EMA1 values, accumulated as EMA1 produces them.
       */
      tempReal = 0.0;
      tempReal += prevEMA1;
      i = optInTimePeriod - 1;
      while( i-- > 0 )
      {
         prevEMA1 = (inReal[today++] - prevEMA1) * optInK_1 + prevEMA1;
         tempReal += prevEMA1;
      }
      prevEMA2 = tempReal / optInTimePeriod;
   } else 
   {
      /* Metastock/Tradestation: seed EMA1 from the first price
       * bar, EMA2 from the first EMA1 value.
       */
      prevEMA1 = inReal[0];
      today = 1;
      while( today <= startIdx - (lookbackEMA * 2 + 1) )
      {
         prevEMA1 = (inReal[today++] - prevEMA1) * optInK_1 + prevEMA1;
      }
      prevEMA2 = prevEMA1;
   }
   /* Advance EMA1 and EMA2 in lockstep through the unstable
    * period of EMA2, up to the bar where EMA3 seeding begins.
    */
   while( today <= startIdx - (lookbackEMA + 1) )
   {
      prevEMA1 = (inReal[today++] - prevEMA1) * optInK_1 + prevEMA1;
      prevEMA2 = (prevEMA1 - prevEMA2) * optInK_1 + prevEMA2;
   }
   if( TA_GLOBALS_COMPATIBILITY == ENUM_VALUE(Compatibility,TA_COMPATIBILITY_DEFAULT,Default) )
   {
      /* Seed EMA3 with a simple average of the first 'period'
       * EMA2 values, accumulated as EMA2 produces them.
       */
      tempReal = 0.0;
      tempReal += prevEMA2;
      i = optInTimePeriod - 1;
      while( i-- > 0 )
      {
         prevEMA1 = (inReal[today++] - prevEMA1) * optInK_1 + prevEMA1;
         prevEMA2 = (prevEMA1 - prevEMA2) * optInK_1 + prevEMA2;
         tempReal += prevEMA2;
      }
      prevEMA3 = tempReal / optInTimePeriod;
   } else 
   {
      /* Metastock/Tradestation: seed EMA3 from the first EMA2
       * value.
       */
      prevEMA3 = prevEMA2;
   }
   /* Advance all three EMA in lockstep through the unstable
    * period of EMA3, up to the bar before the first output.
    */
   while( today <= startIdx - 1 )
   {
      prevEMA1 = (inReal[today++] - prevEMA1) * optInK_1 + prevEMA1;
      prevEMA2 = (prevEMA1 - prevEMA2) * optInK_1 + prevEMA2;
      prevEMA3 = (prevEMA2 - prevEMA3) * optInK_1 + prevEMA3;
   }
   /* Stable zone: keep advancing the three EMA in lockstep and
    * write the 1-day rate-of-change of EMA3 into the output.
    */
   outIdx = 0;
   while( today <= endIdx )
   {
      tempReal = prevEMA3;
      prevEMA1 = (inReal[today++] - prevEMA1) * optInK_1 + prevEMA1;
      prevEMA2 = (prevEMA1 - prevEMA2) * optInK_1 + prevEMA2;
      prevEMA3 = (prevEMA2 - prevEMA3) * optInK_1 + prevEMA3;
      if( tempReal != 0.0 )
      {
         outReal[outIdx++] = (prevEMA3 / tempReal - 1.0) * 100.0;
      } else 
      {
         outReal[outIdx++] = 0.0;
      }
   }
   /* Succeed. Indicate where the output starts relative to
    * the caller input.
    */
   *outBegIdx= startIdx;
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_TRIX_Unguarded( int    startIdx,
                                         int    endIdx,
                                         const double inReal[],
                                         int optInTimePeriod,
                                         int          *outBegIdx,
                                         int          *outNBElement,
                                         double        outReal[] )
{
   double prevEMA1;
   double prevEMA2;
   double prevEMA3;
   double tempReal;
   double optInK_1;
   int i;
   int today;
   int outIdx;
   int lookbackEMA;
   int lookbackTotal;

   *outNBElement= 0;
   *outBegIdx= 0;
   lookbackEMA = TA_EMA_Lookback(optInTimePeriod);
   lookbackTotal = lookbackEMA * 3 + TA_ROCR_Lookback(1);
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   if( startIdx > endIdx )
   {
      return TA_SUCCESS;
   }
   optInK_1 = 2.0 / (double)(optInTimePeriod + 1);
   if( TA_GLOBALS_COMPATIBILITY == ENUM_VALUE(Compatibility,TA_COMPATIBILITY_DEFAULT,Default) )
   {
      today = startIdx - lookbackTotal;
      i = optInTimePeriod;
      tempReal = 0.0;
      while( i-- > 0 )
      {
         tempReal += inReal[today++];
      }
      prevEMA1 = tempReal / optInTimePeriod;
      while( today <= startIdx - (lookbackEMA * 2 + 1) )
      {
         prevEMA1 = (inReal[today++] - prevEMA1) * optInK_1 + prevEMA1;
      }
      tempReal = 0.0;
      tempReal += prevEMA1;
      i = optInTimePeriod - 1;
      while( i-- > 0 )
      {
         prevEMA1 = (inReal[today++] - prevEMA1) * optInK_1 + prevEMA1;
         tempReal += prevEMA1;
      }
      prevEMA2 = tempReal / optInTimePeriod;
   } else 
   {
      prevEMA1 = inReal[0];
      today = 1;
      while( today <= startIdx - (lookbackEMA * 2 + 1) )
      {
         prevEMA1 = (inReal[today++] - prevEMA1) * optInK_1 + prevEMA1;
      }
      prevEMA2 = prevEMA1;
   }
   while( today <= startIdx - (lookbackEMA + 1) )
   {
      prevEMA1 = (inReal[today++] - prevEMA1) * optInK_1 + prevEMA1;
      prevEMA2 = (prevEMA1 - prevEMA2) * optInK_1 + prevEMA2;
   }
   if( TA_GLOBALS_COMPATIBILITY == ENUM_VALUE(Compatibility,TA_COMPATIBILITY_DEFAULT,Default) )
   {
      tempReal = 0.0;
      tempReal += prevEMA2;
      i = optInTimePeriod - 1;
      while( i-- > 0 )
      {
         prevEMA1 = (inReal[today++] - prevEMA1) * optInK_1 + prevEMA1;
         prevEMA2 = (prevEMA1 - prevEMA2) * optInK_1 + prevEMA2;
         tempReal += prevEMA2;
      }
      prevEMA3 = tempReal / optInTimePeriod;
   } else 
   {
      prevEMA3 = prevEMA2;
   }
   while( today <= startIdx - 1 )
   {
      prevEMA1 = (inReal[today++] - prevEMA1) * optInK_1 + prevEMA1;
      prevEMA2 = (prevEMA1 - prevEMA2) * optInK_1 + prevEMA2;
      prevEMA3 = (prevEMA2 - prevEMA3) * optInK_1 + prevEMA3;
   }
   outIdx = 0;
   while( today <= endIdx )
   {
      tempReal = prevEMA3;
      prevEMA1 = (inReal[today++] - prevEMA1) * optInK_1 + prevEMA1;
      prevEMA2 = (prevEMA1 - prevEMA2) * optInK_1 + prevEMA2;
      prevEMA3 = (prevEMA2 - prevEMA3) * optInK_1 + prevEMA3;
      if( tempReal != 0.0 )
      {
         outReal[outIdx++] = (prevEMA3 / tempReal - 1.0) * 100.0;
      } else 
      {
         outReal[outIdx++] = 0.0;
      }
   }
   *outBegIdx= startIdx;
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

TA_RetCode TA_S_TRIX( int    startIdx,
                      int    endIdx,
                      const float inReal[],
                      int optInTimePeriod,
                      int          *outBegIdx,
                      int          *outNBElement,
                      double        outReal[] )
{
   double prevEMA1;
   double prevEMA2;
   double prevEMA3;
   double tempReal;
   double optInK_1;
   int i;
   int today;
   int outIdx;
   int lookbackEMA;
   int lookbackTotal;

   if( startIdx < 0 )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( !inReal )
      return TA_BAD_PARAM;
   if( (int)optInTimePeriod == (int)0x80000000 )
      optInTimePeriod = 30;
   else if( (int)optInTimePeriod < 1 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   *outNBElement= 0;
   *outBegIdx= 0;
   lookbackEMA = TA_EMA_Lookback(optInTimePeriod);
   lookbackTotal = lookbackEMA * 3 + TA_ROCR_Lookback(1);
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   if( startIdx > endIdx )
   {
      return TA_SUCCESS;
   }
   optInK_1 = 2.0 / (double)(optInTimePeriod + 1);
   if( TA_GLOBALS_COMPATIBILITY == ENUM_VALUE(Compatibility,TA_COMPATIBILITY_DEFAULT,Default) )
   {
      today = startIdx - lookbackTotal;
      i = optInTimePeriod;
      tempReal = 0.0;
      while( i-- > 0 )
      {
         tempReal += (double)inReal[today++];
      }
      prevEMA1 = tempReal / optInTimePeriod;
      while( today <= startIdx - (lookbackEMA * 2 + 1) )
      {
         prevEMA1 = ((double)inReal[today++] - prevEMA1) * optInK_1 + prevEMA1;
      }
      tempReal = 0.0;
      tempReal += prevEMA1;
      i = optInTimePeriod - 1;
      while( i-- > 0 )
      {
         prevEMA1 = ((double)inReal[today++] - prevEMA1) * optInK_1 + prevEMA1;
         tempReal += prevEMA1;
      }
      prevEMA2 = tempReal / optInTimePeriod;
   } else 
   {
      prevEMA1 = (double)inReal[0];
      today = 1;
      while( today <= startIdx - (lookbackEMA * 2 + 1) )
      {
         prevEMA1 = ((double)inReal[today++] - prevEMA1) * optInK_1 + prevEMA1;
      }
      prevEMA2 = prevEMA1;
   }
   while( today <= startIdx - (lookbackEMA + 1) )
   {
      prevEMA1 = ((double)inReal[today++] - prevEMA1) * optInK_1 + prevEMA1;
      prevEMA2 = (prevEMA1 - prevEMA2) * optInK_1 + prevEMA2;
   }
   if( TA_GLOBALS_COMPATIBILITY == ENUM_VALUE(Compatibility,TA_COMPATIBILITY_DEFAULT,Default) )
   {
      tempReal = 0.0;
      tempReal += prevEMA2;
      i = optInTimePeriod - 1;
      while( i-- > 0 )
      {
         prevEMA1 = ((double)inReal[today++] - prevEMA1) * optInK_1 + prevEMA1;
         prevEMA2 = (prevEMA1 - prevEMA2) * optInK_1 + prevEMA2;
         tempReal += prevEMA2;
      }
      prevEMA3 = tempReal / optInTimePeriod;
   } else 
   {
      prevEMA3 = prevEMA2;
   }
   while( today <= startIdx - 1 )
   {
      prevEMA1 = ((double)inReal[today++] - prevEMA1) * optInK_1 + prevEMA1;
      prevEMA2 = (prevEMA1 - prevEMA2) * optInK_1 + prevEMA2;
      prevEMA3 = (prevEMA2 - prevEMA3) * optInK_1 + prevEMA3;
   }
   outIdx = 0;
   while( today <= endIdx )
   {
      tempReal = prevEMA3;
      prevEMA1 = ((double)inReal[today++] - prevEMA1) * optInK_1 + prevEMA1;
      prevEMA2 = (prevEMA1 - prevEMA2) * optInK_1 + prevEMA2;
      prevEMA3 = (prevEMA2 - prevEMA3) * optInK_1 + prevEMA3;
      if( tempReal != 0.0 )
      {
         outReal[outIdx++] = (prevEMA3 / tempReal - 1.0) * 100.0;
      } else 
      {
         outReal[outIdx++] = 0.0;
      }
   }
   *outBegIdx= startIdx;
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

TA_RetCode TA_S_TRIX_Unguarded( int    startIdx,
                                int    endIdx,
                                const float inReal[],
                                int optInTimePeriod,
                                int          *outBegIdx,
                                int          *outNBElement,
                                double        outReal[] )
{
   double prevEMA1;
   double prevEMA2;
   double prevEMA3;
   double tempReal;
   double optInK_1;
   int i;
   int today;
   int outIdx;
   int lookbackEMA;
   int lookbackTotal;

   *outNBElement= 0;
   *outBegIdx= 0;
   lookbackEMA = TA_EMA_Lookback(optInTimePeriod);
   lookbackTotal = lookbackEMA * 3 + TA_ROCR_Lookback(1);
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   if( startIdx > endIdx )
   {
      return TA_SUCCESS;
   }
   optInK_1 = 2.0 / (double)(optInTimePeriod + 1);
   if( TA_GLOBALS_COMPATIBILITY == ENUM_VALUE(Compatibility,TA_COMPATIBILITY_DEFAULT,Default) )
   {
      today = startIdx - lookbackTotal;
      i = optInTimePeriod;
      tempReal = 0.0;
      while( i-- > 0 )
      {
         tempReal += (double)inReal[today++];
      }
      prevEMA1 = tempReal / optInTimePeriod;
      while( today <= startIdx - (lookbackEMA * 2 + 1) )
      {
         prevEMA1 = ((double)inReal[today++] - prevEMA1) * optInK_1 + prevEMA1;
      }
      tempReal = 0.0;
      tempReal += prevEMA1;
      i = optInTimePeriod - 1;
      while( i-- > 0 )
      {
         prevEMA1 = ((double)inReal[today++] - prevEMA1) * optInK_1 + prevEMA1;
         tempReal += prevEMA1;
      }
      prevEMA2 = tempReal / optInTimePeriod;
   } else 
   {
      prevEMA1 = (double)inReal[0];
      today = 1;
      while( today <= startIdx - (lookbackEMA * 2 + 1) )
      {
         prevEMA1 = ((double)inReal[today++] - prevEMA1) * optInK_1 + prevEMA1;
      }
      prevEMA2 = prevEMA1;
   }
   while( today <= startIdx - (lookbackEMA + 1) )
   {
      prevEMA1 = ((double)inReal[today++] - prevEMA1) * optInK_1 + prevEMA1;
      prevEMA2 = (prevEMA1 - prevEMA2) * optInK_1 + prevEMA2;
   }
   if( TA_GLOBALS_COMPATIBILITY == ENUM_VALUE(Compatibility,TA_COMPATIBILITY_DEFAULT,Default) )
   {
      tempReal = 0.0;
      tempReal += prevEMA2;
      i = optInTimePeriod - 1;
      while( i-- > 0 )
      {
         prevEMA1 = ((double)inReal[today++] - prevEMA1) * optInK_1 + prevEMA1;
         prevEMA2 = (prevEMA1 - prevEMA2) * optInK_1 + prevEMA2;
         tempReal += prevEMA2;
      }
      prevEMA3 = tempReal / optInTimePeriod;
   } else 
   {
      prevEMA3 = prevEMA2;
   }
   while( today <= startIdx - 1 )
   {
      prevEMA1 = ((double)inReal[today++] - prevEMA1) * optInK_1 + prevEMA1;
      prevEMA2 = (prevEMA1 - prevEMA2) * optInK_1 + prevEMA2;
      prevEMA3 = (prevEMA2 - prevEMA3) * optInK_1 + prevEMA3;
   }
   outIdx = 0;
   while( today <= endIdx )
   {
      tempReal = prevEMA3;
      prevEMA1 = ((double)inReal[today++] - prevEMA1) * optInK_1 + prevEMA1;
      prevEMA2 = (prevEMA1 - prevEMA2) * optInK_1 + prevEMA2;
      prevEMA3 = (prevEMA2 - prevEMA3) * optInK_1 + prevEMA3;
      if( tempReal != 0.0 )
      {
         outReal[outIdx++] = (prevEMA3 / tempReal - 1.0) * 100.0;
      } else 
      {
         outReal[outIdx++] = 0.0;
      }
   }
   *outBegIdx= startIdx;
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

