/* TA-LIB Copyright (c) 1999-2026, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_stream_private.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  MF       Mario Fortier
 *  CC       Claude Code (AI assistant)
 *
 * Change history:
 *
 *  MMDDYY BY     Description
 *  -------------------------------------------------------------------
 *  090426 MF,CC  First version (#360).
 */

TA_LIB_API int TA_TSI_Lookback( int optInFirstPeriod, int optInSecondPeriod )
{
   if( (int)optInFirstPeriod == TA_INTEGER_DEFAULT )
      optInFirstPeriod = 25;
   else if( (int)optInFirstPeriod < 2 || (int)optInFirstPeriod > 100000 )
      return -1;
   if( (int)optInSecondPeriod == TA_INTEGER_DEFAULT )
      optInSecondPeriod = 13;
   else if( (int)optInSecondPeriod < 2 || (int)optInSecondPeriod > 100000 )
      return -1;
   /* One bar forms the first close-to-close change, then the two EMA warm-ups
    * the pipeline stacks on it. Each term is exactly the lookback of the
    * function it comes from, which is also what makes TSI inherit
    * TA_FUNC_UNST_EMA from its callee.
    */
   return 1 + TA_EMA_Lookback(optInFirstPeriod) + TA_EMA_Lookback(optInSecondPeriod);
}

TA_FMA_MULTIVERSION
TA_LIB_API TA_RetCode TA_TSI( int    startIdx,
                              int    endIdx,
                              const double inReal[],
                              int optInFirstPeriod,
                              int optInSecondPeriod,
                              int          *outBegIdx,
                              int          *outNBElement,
                              double        outReal[] )
{
   double kFirst;
   double kSecond;
   double emaFirstNum;
   double emaFirstDen;
   double emaSecondNum;
   double emaSecondDen;
   double sumFirstNum;
   double sumFirstDen;
   double sumSecondNum;
   double sumSecondDen;
   double prevClose;
   double mom;
   double absMom;
   double tsiValue;
   int lookbackTotal;
   int lookbackFirst;
   int today;
   int outIdx;
   int nBar;
   int nSecond;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInFirstPeriod == TA_INTEGER_DEFAULT )
      optInFirstPeriod = 25;
   else if( (int)optInFirstPeriod < 2 || (int)optInFirstPeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInSecondPeriod == TA_INTEGER_DEFAULT )
      optInSecondPeriod = 13;
   else if( (int)optInSecondPeriod < 2 || (int)optInSecondPeriod > 100000 )
      return TA_BAD_PARAM;
   if( !inReal )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   lookbackTotal = TA_TSI_Lookback(optInFirstPeriod,optInSecondPeriod);
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   *outBegIdx= startIdx;
   /* Blau's double smoothing in one pass: the signed momentum and its
    * magnitude are carried through the same two EMA stages, then divided.
    *
    * Each stage seeds the way ema.c does -- a simple average of that stage's
    * first 'period' inputs -- so the result is bit-identical to TA_MOM(1)
    * followed by two TA_EMA calls on each chain. The stage boundary below is
    * the callee LOOKBACK, not (period-1), so that a warm
    * TA_SetUnstablePeriod(TA_FUNC_UNST_EMA) folds in: the second stage then
    * seeds from the values the first would have published. The seed sums
    * accumulate from 0.0 in production order and the recurrence is
    * ((x-prev)*k)+prev rather than the algebraically equal k*x+(1-k)*prev; do
    * not reorder or fuse them (0.0+x is not x for x=-0.0). That order IS the
    * bit-exactness contract against the composed reference.
    *
    * TA_GetCompatibility() is deliberately NOT consulted, for the reason
    * spelled out in efi.c: ema.c's TA_COMPATIBILITY_METASTOCK seeding arm is
    * preserved for the functions that already shipped with it and dropped from
    * new ones, and it is not reachable at all from the Rust, Java and C# APIs.
    *
    * prevClose is carried in a scalar rather than re-read from inReal[t-1]
    * because outReal may alias inReal: the slot holding close[t-1] may already
    * hold an output written a bar earlier.
    */
   kFirst = 2.0 / (double)(optInFirstPeriod + 1);
   kSecond = 2.0 / (double)(optInSecondPeriod + 1);
   lookbackFirst = TA_EMA_Lookback(optInFirstPeriod);
   emaFirstNum = 0.0;
   emaFirstDen = 0.0;
   emaSecondNum = 0.0;
   emaSecondDen = 0.0;
   sumFirstNum = 0.0;
   sumFirstDen = 0.0;
   sumSecondNum = 0.0;
   sumSecondDen = 0.0;
   /* The first bar carrying a close-to-close change. */
   today = startIdx - lookbackTotal + 1;
   prevClose = inReal[today - 1];
   nBar = 0;
   /* Warm-up. Runs through startIdx inclusive: the last pass here completes
    * the second stage's seed, so it produces the first output.
    */
   while( today <= startIdx )
   {
      mom = inReal[today] - prevClose;
      prevClose = inReal[today];
      absMom = fabs(mom);
      /* Stage 1: the first EMA, over the raw momentum and its magnitude. */
      if( nBar < optInFirstPeriod )
      {
         sumFirstNum = sumFirstNum + mom;
         sumFirstDen = sumFirstDen + absMom;
         if( nBar == optInFirstPeriod - 1 )
         {
            emaFirstNum = sumFirstNum / optInFirstPeriod;
            emaFirstDen = sumFirstDen / optInFirstPeriod;
         }
      } else 
      {
         emaFirstNum = fma(mom - emaFirstNum, kFirst, emaFirstNum);
         emaFirstDen = fma(absMom - emaFirstDen, kFirst, emaFirstDen);
      }
      /* Stage 2: the second EMA, over what stage 1 publishes.
       *
       * The stage counter is compared BEFORE it is subtracted, never after.
       * Writing this as `nSecond = nBar - lookbackFirst; if( nSecond >= 0 )`
       * is correct in C, where the counters are signed, and broken everywhere
       * else: the Rust backend renders them as usize, so the subtraction
       * underflows for the first lookbackFirst bars -- a panic in a debug
       * build and a wrap in release. It would also be invisible to the
       * cross-language gate, which runs release servers at unstable period 0,
       * where the branch the wrap wrongly takes happens to be a no-op because
       * both accumulators are still 0.0. smi.c states the same rule.
       */
      if( nBar >= lookbackFirst )
      {
         nSecond = nBar - lookbackFirst;
         if( nSecond < optInSecondPeriod )
         {
            sumSecondNum = sumSecondNum + emaFirstNum;
            sumSecondDen = sumSecondDen + emaFirstDen;
            if( nSecond == optInSecondPeriod - 1 )
            {
               emaSecondNum = sumSecondNum / optInSecondPeriod;
               emaSecondDen = sumSecondDen / optInSecondPeriod;
            }
         } else 
         {
            emaSecondNum = fma(emaFirstNum - emaSecondNum, kSecond, emaSecondNum);
            emaSecondDen = fma(emaFirstDen - emaSecondDen, kSecond, emaSecondDen);
         }
      }
      nBar = nBar + 1;
      today = today + 1;
   }
   /* The denominator is an EMA of an EMA of |momentum|: every term is
    * non-negative and every weight positive, so it is zero only when every
    * change that reached it was exactly zero -- 0/0, since the numerator is
    * zero with it, reported as the neutral 0.0 by the CCI (#7) and IMI (#112)
    * convention. Tested exactly rather than against a fixed band: a price
    * change carries the quote unit, and TA_IS_ZERO zeroes the oscillator for
    * any instrument quoted below it (issue #253).
    */
   if( emaSecondDen > 0.0 )
   {
      tsiValue = 100.0 * emaSecondNum / emaSecondDen;
   } else 
   {
      tsiValue = 0.0;
   }
   outReal[0] = tsiValue;
   outIdx = 1;
   /* Stable zone. Both stages are a pure recursion from here on. */
   while( today <= endIdx )
   {
      mom = inReal[today] - prevClose;
      prevClose = inReal[today];
      absMom = fabs(mom);
      emaFirstNum = fma(mom - emaFirstNum, kFirst, emaFirstNum);
      emaFirstDen = fma(absMom - emaFirstDen, kFirst, emaFirstDen);
      emaSecondNum = fma(emaFirstNum - emaSecondNum, kSecond, emaSecondNum);
      emaSecondDen = fma(emaFirstDen - emaSecondDen, kSecond, emaSecondDen);
      if( emaSecondDen > 0.0 )
      {
         tsiValue = 100.0 * emaSecondNum / emaSecondDen;
      } else 
      {
         tsiValue = 0.0;
      }
      outReal[outIdx] = tsiValue;
      outIdx = outIdx + 1;
      today = today + 1;
   }
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

TA_FMA_MULTIVERSION
TA_RetCode TA_S_TSI( int    startIdx,
                     int    endIdx,
                     const float inReal[],
                     int optInFirstPeriod,
                     int optInSecondPeriod,
                     int          *outBegIdx,
                     int          *outNBElement,
                     double        outReal[] )
{
   double kFirst;
   double kSecond;
   double emaFirstNum;
   double emaFirstDen;
   double emaSecondNum;
   double emaSecondDen;
   double sumFirstNum;
   double sumFirstDen;
   double sumSecondNum;
   double sumSecondDen;
   double prevClose;
   double mom;
   double absMom;
   double tsiValue;
   int lookbackTotal;
   int lookbackFirst;
   int today;
   int outIdx;
   int nBar;
   int nSecond;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInFirstPeriod == TA_INTEGER_DEFAULT )
      optInFirstPeriod = 25;
   else if( (int)optInFirstPeriod < 2 || (int)optInFirstPeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInSecondPeriod == TA_INTEGER_DEFAULT )
      optInSecondPeriod = 13;
   else if( (int)optInSecondPeriod < 2 || (int)optInSecondPeriod > 100000 )
      return TA_BAD_PARAM;
   if( !inReal )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   lookbackTotal = TA_TSI_Lookback(optInFirstPeriod,optInSecondPeriod);
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   *outBegIdx= startIdx;
   kFirst = 2.0 / (double)(optInFirstPeriod + 1);
   kSecond = 2.0 / (double)(optInSecondPeriod + 1);
   lookbackFirst = TA_EMA_Lookback(optInFirstPeriod);
   emaFirstNum = 0.0;
   emaFirstDen = 0.0;
   emaSecondNum = 0.0;
   emaSecondDen = 0.0;
   sumFirstNum = 0.0;
   sumFirstDen = 0.0;
   sumSecondNum = 0.0;
   sumSecondDen = 0.0;
   today = startIdx - lookbackTotal + 1;
   prevClose = (double)inReal[today - 1];
   nBar = 0;
   while( today <= startIdx )
   {
      mom = (double)inReal[today] - prevClose;
      prevClose = (double)inReal[today];
      absMom = fabs(mom);
      if( nBar < optInFirstPeriod )
      {
         sumFirstNum = sumFirstNum + mom;
         sumFirstDen = sumFirstDen + absMom;
         if( nBar == optInFirstPeriod - 1 )
         {
            emaFirstNum = sumFirstNum / optInFirstPeriod;
            emaFirstDen = sumFirstDen / optInFirstPeriod;
         }
      } else 
      {
         emaFirstNum = fma(mom - emaFirstNum, kFirst, emaFirstNum);
         emaFirstDen = fma(absMom - emaFirstDen, kFirst, emaFirstDen);
      }
      if( nBar >= lookbackFirst )
      {
         nSecond = nBar - lookbackFirst;
         if( nSecond < optInSecondPeriod )
         {
            sumSecondNum = sumSecondNum + emaFirstNum;
            sumSecondDen = sumSecondDen + emaFirstDen;
            if( nSecond == optInSecondPeriod - 1 )
            {
               emaSecondNum = sumSecondNum / optInSecondPeriod;
               emaSecondDen = sumSecondDen / optInSecondPeriod;
            }
         } else 
         {
            emaSecondNum = fma(emaFirstNum - emaSecondNum, kSecond, emaSecondNum);
            emaSecondDen = fma(emaFirstDen - emaSecondDen, kSecond, emaSecondDen);
         }
      }
      nBar = nBar + 1;
      today = today + 1;
   }
   if( emaSecondDen > 0.0 )
   {
      tsiValue = 100.0 * emaSecondNum / emaSecondDen;
   } else 
   {
      tsiValue = 0.0;
   }
   outReal[0] = tsiValue;
   outIdx = 1;
   while( today <= endIdx )
   {
      mom = (double)inReal[today] - prevClose;
      prevClose = (double)inReal[today];
      absMom = fabs(mom);
      emaFirstNum = fma(mom - emaFirstNum, kFirst, emaFirstNum);
      emaFirstDen = fma(absMom - emaFirstDen, kFirst, emaFirstDen);
      emaSecondNum = fma(emaFirstNum - emaSecondNum, kSecond, emaSecondNum);
      emaSecondDen = fma(emaFirstDen - emaSecondDen, kSecond, emaSecondDen);
      if( emaSecondDen > 0.0 )
      {
         tsiValue = 100.0 * emaSecondNum / emaSecondDen;
      } else 
      {
         tsiValue = 0.0;
      }
      outReal[outIdx] = tsiValue;
      outIdx = outIdx + 1;
      today = today + 1;
   }
   *outNBElement= outIdx;
   return TA_SUCCESS;
}

/**** Streaming API *****/

struct TA_TSI_Stream {
   /* The bars this handle has an output for (see TA_StreamOutRange).
    * Kept first, and in this order, in every stream struct. */
   int outRangeBegIdx;
   int outRangeCount;
   /* The value(s) at the last bar the stream counted (see TA_TSI_Value). */
   double cur_outReal;
   int optInFirstPeriod;
   int optInSecondPeriod;
   double kFirst;
   double kSecond;
   double emaFirstNum;
   double emaFirstDen;
   double emaSecondNum;
   double emaSecondDen;
   double prevClose;
};

/* Private function, not in public API. */
static void TA_TSI_StepImpl( struct TA_TSI_Stream *sp, double inReal, double *outReal )
{
   double mom;
   double absMom;
   double tsiValue;

   mom = inReal - sp->prevClose;
   sp->prevClose = inReal;
   absMom = fabs(mom);
   sp->emaFirstNum = fma(mom - sp->emaFirstNum, sp->kFirst, sp->emaFirstNum);
   sp->emaFirstDen = fma(absMom - sp->emaFirstDen, sp->kFirst, sp->emaFirstDen);
   sp->emaSecondNum = fma(sp->emaFirstNum - sp->emaSecondNum, sp->kSecond, sp->emaSecondNum);
   sp->emaSecondDen = fma(sp->emaFirstDen - sp->emaSecondDen, sp->kSecond, sp->emaSecondDen);
   if( sp->emaSecondDen > 0.0 )
   {
      tsiValue = 100.0 * sp->emaSecondNum / sp->emaSecondDen;
   } else 
   {
      tsiValue = 0.0;
   }
   *outReal= tsiValue;
   sp->cur_outReal = *outReal;
}

static TA_RetCode TA_TSI_OpenImpl( struct TA_TSI_Stream **stream, const double inReal[], int startIdx, int historyLen, int optInFirstPeriod, int optInSecondPeriod, int *outBegIdx, int *outNBElement, double outReal[], int outStride )
{
   struct TA_TSI_Stream *sp;
   int endIdx;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inReal || !outReal ) return TA_BAD_PARAM;
   if( (int)optInFirstPeriod == TA_INTEGER_DEFAULT )
      optInFirstPeriod = 25;
   else if( (int)optInFirstPeriod < 2 || (int)optInFirstPeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInSecondPeriod == TA_INTEGER_DEFAULT )
      optInSecondPeriod = 13;
   else if( (int)optInSecondPeriod < 2 || (int)optInSecondPeriod > 100000 )
      return TA_BAD_PARAM;
   if( startIdx > historyLen - 1 )
   {
      *outBegIdx = 0;
      *outNBElement = 0;
      return TA_INSUFFICIENT_HISTORY;
   }

   endIdx = historyLen - 1;

   {
      double kFirst = 0.0;
      double kSecond = 0.0;
      double emaFirstNum = 0.0;
      double emaFirstDen = 0.0;
      double emaSecondNum = 0.0;
      double emaSecondDen = 0.0;
      double sumFirstNum;
      double sumFirstDen;
      double sumSecondNum;
      double sumSecondDen;
      double prevClose = 0.0;
      double mom;
      double absMom;
      double tsiValue;
      int lookbackTotal;
      int lookbackFirst;
      int today;
      int outIdx;
      int nBar;
      int nSecond;
      lookbackTotal = TA_TSI_Lookback(optInFirstPeriod,optInSecondPeriod);
      if( startIdx < lookbackTotal )
      {
         startIdx = lookbackTotal;
      }
      if( startIdx > endIdx )
      {
         *outBegIdx= 0;
         *outNBElement= 0;
         return TA_INSUFFICIENT_HISTORY;
      }
      *outBegIdx= startIdx;
      /* Blau's double smoothing in one pass: the signed momentum and its
       * magnitude are carried through the same two EMA stages, then divided.
       *
       * Each stage seeds the way ema.c does -- a simple average of that stage's
       * first 'period' inputs -- so the result is bit-identical to TA_MOM(1)
       * followed by two TA_EMA calls on each chain. The stage boundary below is
       * the callee LOOKBACK, not (period-1), so that a warm
       * TA_SetUnstablePeriod(TA_FUNC_UNST_EMA) folds in: the second stage then
       * seeds from the values the first would have published. The seed sums
       * accumulate from 0.0 in production order and the recurrence is
       * ((x-prev)*k)+prev rather than the algebraically equal k*x+(1-k)*prev; do
       * not reorder or fuse them (0.0+x is not x for x=-0.0). That order IS the
       * bit-exactness contract against the composed reference.
       *
       * TA_GetCompatibility() is deliberately NOT consulted, for the reason
       * spelled out in efi.c: ema.c's TA_COMPATIBILITY_METASTOCK seeding arm is
       * preserved for the functions that already shipped with it and dropped from
       * new ones, and it is not reachable at all from the Rust, Java and C# APIs.
       *
       * prevClose is carried in a scalar rather than re-read from inReal[t-1]
       * because outReal may alias inReal: the slot holding close[t-1] may already
       * hold an output written a bar earlier.
       */
      kFirst = 2.0 / (double)(optInFirstPeriod + 1);
      kSecond = 2.0 / (double)(optInSecondPeriod + 1);
      lookbackFirst = TA_EMA_Lookback(optInFirstPeriod);
      emaFirstNum = 0.0;
      emaFirstDen = 0.0;
      emaSecondNum = 0.0;
      emaSecondDen = 0.0;
      sumFirstNum = 0.0;
      sumFirstDen = 0.0;
      sumSecondNum = 0.0;
      sumSecondDen = 0.0;
      /* The first bar carrying a close-to-close change. */
      today = startIdx - lookbackTotal + 1;
      prevClose = inReal[today - 1];
      nBar = 0;
      /* Warm-up. Runs through startIdx inclusive: the last pass here completes
       * the second stage's seed, so it produces the first output.
       */
      while( today <= startIdx )
      {
         mom = inReal[today] - prevClose;
         prevClose = inReal[today];
         absMom = fabs(mom);
         /* Stage 1: the first EMA, over the raw momentum and its magnitude. */
         if( nBar < optInFirstPeriod )
         {
            sumFirstNum = sumFirstNum + mom;
            sumFirstDen = sumFirstDen + absMom;
            if( nBar == optInFirstPeriod - 1 )
            {
               emaFirstNum = sumFirstNum / optInFirstPeriod;
               emaFirstDen = sumFirstDen / optInFirstPeriod;
            }
         } else 
         {
            emaFirstNum = fma(mom - emaFirstNum, kFirst, emaFirstNum);
            emaFirstDen = fma(absMom - emaFirstDen, kFirst, emaFirstDen);
         }
         /* Stage 2: the second EMA, over what stage 1 publishes.
          *
          * The stage counter is compared BEFORE it is subtracted, never after.
          * Writing this as `nSecond = nBar - lookbackFirst; if( nSecond >= 0 )`
          * is correct in C, where the counters are signed, and broken everywhere
          * else: the Rust backend renders them as usize, so the subtraction
          * underflows for the first lookbackFirst bars -- a panic in a debug
          * build and a wrap in release. It would also be invisible to the
          * cross-language gate, which runs release servers at unstable period 0,
          * where the branch the wrap wrongly takes happens to be a no-op because
          * both accumulators are still 0.0. smi.c states the same rule.
          */
         if( nBar >= lookbackFirst )
         {
            nSecond = nBar - lookbackFirst;
            if( nSecond < optInSecondPeriod )
            {
               sumSecondNum = sumSecondNum + emaFirstNum;
               sumSecondDen = sumSecondDen + emaFirstDen;
               if( nSecond == optInSecondPeriod - 1 )
               {
                  emaSecondNum = sumSecondNum / optInSecondPeriod;
                  emaSecondDen = sumSecondDen / optInSecondPeriod;
               }
            } else 
            {
               emaSecondNum = fma(emaFirstNum - emaSecondNum, kSecond, emaSecondNum);
               emaSecondDen = fma(emaFirstDen - emaSecondDen, kSecond, emaSecondDen);
            }
         }
         nBar = nBar + 1;
         today = today + 1;
      }
      /* The denominator is an EMA of an EMA of |momentum|: every term is
       * non-negative and every weight positive, so it is zero only when every
       * change that reached it was exactly zero -- 0/0, since the numerator is
       * zero with it, reported as the neutral 0.0 by the CCI (#7) and IMI (#112)
       * convention. Tested exactly rather than against a fixed band: a price
       * change carries the quote unit, and TA_IS_ZERO zeroes the oscillator for
       * any instrument quoted below it (issue #253).
       */
      if( emaSecondDen > 0.0 )
      {
         tsiValue = 100.0 * emaSecondNum / emaSecondDen;
      } else 
      {
         tsiValue = 0.0;
      }
      outReal[0 * outStride] = tsiValue;
      outIdx = 1;
      /* Stable zone. Both stages are a pure recursion from here on. */
      while( today <= endIdx )
      {
         mom = inReal[today] - prevClose;
         prevClose = inReal[today];
         absMom = fabs(mom);
         emaFirstNum = fma(mom - emaFirstNum, kFirst, emaFirstNum);
         emaFirstDen = fma(absMom - emaFirstDen, kFirst, emaFirstDen);
         emaSecondNum = fma(emaFirstNum - emaSecondNum, kSecond, emaSecondNum);
         emaSecondDen = fma(emaFirstDen - emaSecondDen, kSecond, emaSecondDen);
         if( emaSecondDen > 0.0 )
         {
            tsiValue = 100.0 * emaSecondNum / emaSecondDen;
         } else 
         {
            tsiValue = 0.0;
         }
         outReal[outIdx * outStride] = tsiValue;
         outIdx = outIdx + 1;
         today = today + 1;
      }
      *outNBElement= outIdx;

      /* Capture the live batch state into the handle. */
      sp = (struct TA_TSI_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) { return TA_ALLOC_ERR; }
      memset( sp, 0, sizeof(*sp) );
      sp->optInFirstPeriod = optInFirstPeriod;
      sp->optInSecondPeriod = optInSecondPeriod;
      sp->kFirst = kFirst;
      sp->kSecond = kSecond;
      sp->emaFirstNum = emaFirstNum;
      sp->emaFirstDen = emaFirstDen;
      sp->emaSecondNum = emaSecondNum;
      sp->emaSecondDen = emaSecondDen;
      sp->prevClose = prevClose;
      sp->outRangeBegIdx = *outBegIdx;
      sp->outRangeCount = *outNBElement;
      sp->cur_outReal = outReal[(*outNBElement - 1) * outStride];
      *stream = sp;
      return TA_SUCCESS;
   }
}

/* Private function, not in public API. */
TA_RetCode TA_TSI_OpenInternal( struct TA_TSI_Stream **stream, const double inReal[], int startIdx, int historyLen, int optInFirstPeriod, int optInSecondPeriod, double *outReal )
{
   TA_RetCode retCode;
   int dummyBegIdx = 0;
   int dummyNBElement = 0;
   double sink_outReal = 0.0;
   retCode = TA_TSI_OpenImpl( stream, inReal, startIdx, historyLen, optInFirstPeriod, optInSecondPeriod, &dummyBegIdx, &dummyNBElement, &sink_outReal, 0 );
   if( retCode == TA_SUCCESS )
   {
      *outReal = sink_outReal;
   }
   return retCode;
}

TA_LIB_API TA_RetCode TA_TSI_Open( TA_TSI_Stream **stream, const double inReal[], int historyLen, int optInFirstPeriod, int optInSecondPeriod, double *outReal )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inReal || !outReal ) return TA_BAD_PARAM;
   return TA_TSI_OpenInternal( stream, inReal, 0, historyLen, optInFirstPeriod, optInSecondPeriod, outReal );
}

TA_LIB_API TA_RetCode TA_TSI_OpenAndFill( TA_TSI_Stream **stream, const double inReal[], int historyLen, int optInFirstPeriod, int optInSecondPeriod, int *outBegIdx, int *outNBElement, double outReal[] )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inReal || !outBegIdx || !outNBElement || !outReal ) return TA_BAD_PARAM;
   if( (const void *)outReal == (const void *)inReal ) return TA_BAD_PARAM;
   return TA_TSI_OpenAndFillInternal( stream, inReal, 0, historyLen, optInFirstPeriod, optInSecondPeriod, outBegIdx, outNBElement, outReal );
}

/* Private function, not in public API. */
TA_RetCode TA_TSI_OpenAndFillInternal( struct TA_TSI_Stream **stream, const double inReal[], int startIdx, int historyLen, int optInFirstPeriod, int optInSecondPeriod, int *outBegIdx, int *outNBElement, double outReal[] )
{
   return TA_TSI_OpenImpl( stream, inReal, startIdx, historyLen, optInFirstPeriod, optInSecondPeriod, outBegIdx, outNBElement, outReal, 1 );
}

TA_LIB_API TA_RetCode TA_TSI_Update( TA_TSI_Stream *stream, double inReal, double *outReal )
{
   if( !stream || !outReal ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inReal ) )
   {
      if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
      return TA_BAD_PARAM;
   }
   TA_TSI_StepImpl( stream, inReal, outReal );
   if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_FMA_MULTIVERSION
TA_LIB_API TA_RetCode TA_TSI_Peek( const TA_TSI_Stream *stream, double inReal, double *outReal )
{
   const struct TA_TSI_Stream *sp = stream;
   double mom;
   double absMom;
   double tsiValue;
   double emaFirstDen;
   double emaFirstNum;
   double emaSecondDen;
   double emaSecondNum;
   double prevClose;

   if( !stream || !outReal ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inReal ) ) return TA_BAD_PARAM;
   emaFirstDen = sp->emaFirstDen;
   emaFirstNum = sp->emaFirstNum;
   emaSecondDen = sp->emaSecondDen;
   emaSecondNum = sp->emaSecondNum;
   prevClose = sp->prevClose;
   mom = inReal - prevClose;
   prevClose = inReal;
   absMom = fabs(mom);
   emaFirstNum = fma(mom - emaFirstNum, sp->kFirst, emaFirstNum);
   emaFirstDen = fma(absMom - emaFirstDen, sp->kFirst, emaFirstDen);
   emaSecondNum = fma(emaFirstNum - emaSecondNum, sp->kSecond, emaSecondNum);
   emaSecondDen = fma(emaFirstDen - emaSecondDen, sp->kSecond, emaSecondDen);
   if( emaSecondDen > 0.0 )
   {
      tsiValue = 100.0 * emaSecondNum / emaSecondDen;
   } else 
   {
      tsiValue = 0.0;
   }
   *outReal= tsiValue;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_TSI_UpdateAndFill( TA_TSI_Stream *stream, const double inReal[], int barCount, double outReal[] )
{
   int i;

   if( !stream || !inReal || !outReal ) return TA_BAD_PARAM;
   if( barCount < 0 ) return TA_BAD_PARAM;
   if( (const void *)outReal == (const void *)inReal ) return TA_BAD_PARAM;
   for( i = 0; i < barCount; i++ )
   {
      if( !TA_IS_FINITE( inReal[i] ) )
      {
         if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
         return TA_BAD_PARAM;
      }
      TA_TSI_StepImpl( stream, inReal[i], &outReal[i] );
      if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   }
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_TSI_Close( TA_TSI_Stream *stream )
{
   if( stream ) TA_Free( stream );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_TSI_Value( const TA_TSI_Stream *stream, double *outReal )
{
   if( !stream || !outReal ) return TA_BAD_PARAM;
   *outReal = stream->cur_outReal;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_TSI_Clone( const TA_TSI_Stream *stream, TA_TSI_Stream **clone )
{
   struct TA_TSI_Stream *sp;

   if( !clone ) return TA_BAD_PARAM;
   *clone = NULL;
   if( !stream ) return TA_BAD_PARAM;
   sp = (struct TA_TSI_Stream *)TA_Malloc( sizeof(*sp) );
   if( !sp ) return TA_ALLOC_ERR;
   *sp = *stream;
   *clone = sp;
   return TA_SUCCESS;
}

