/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_unguarded.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  MF       Mario Fortier
 *
 *
 * Change history:
 *
 *  MMDDYY BY   Description
 *  -------------------------------------------------------------------
 *  112400 MF   Template creation.
 *  052603 MF   Adapt code to compile with .NET Managed C++
 */

TA_LIB_API int TA_WMA_Lookback( int optInTimePeriod )
{
   if( (int)optInTimePeriod == (int)0x80000000 )
      optInTimePeriod = 30;
   else if( (int)optInTimePeriod < 1 || (int)optInTimePeriod > 100000 )
      return -1;
   return optInTimePeriod - 1;
}

TA_LIB_API TA_RetCode TA_WMA( int    startIdx,
                              int    endIdx,
                              const double inReal[],
                              int optInTimePeriod,
                              int          *outBegIdx,
                              int          *outNBElement,
                              double        outReal[] )
{
   int inIdx;
   int outIdx;
   int i;
   int trailingIdx;
   int divider;
   double periodSum;
   double periodSub;
   double tempReal;
   double trailingValue;
   int lookbackTotal;

   if( startIdx < 0 )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( !inReal )
      return TA_BAD_PARAM;
   if( (int)optInTimePeriod == (int)0x80000000 )
      optInTimePeriod = 30;
   else if( (int)optInTimePeriod < 1 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   lookbackTotal = optInTimePeriod - 1;
   /* Move up the start index if there is not
    * enough initial data.
    */
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   /* Make sure there is still something to evaluate. */
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   /* To make the rest more efficient, handle exception
    * case where the user is asking for a period of '1'.
    * In that case outputs equals inputs for the requested
    * range.
    */
   if( optInTimePeriod == 1 )
   {
      *outBegIdx= startIdx;
      *outNBElement= endIdx - startIdx + 1;
      memmove(outReal,&inReal[startIdx],(int)*outNBElement * sizeof(double));
      return TA_SUCCESS;
   }
   /* Calculate the divider (always an integer value).
    * By induction: 1+2+3+4+'n' = n(n+1)/2
    * '>>1' is usually faster than '/2' for unsigned.
    */
   divider = optInTimePeriod * (optInTimePeriod + 1) >> 1;
   /* The algo used here use a very basic property of
    * multiplication/addition: (x*2) = x+x
    *
    * As an example, a 3 period weighted can be
    * interpreted in two way:
    *  (x1*1)+(x2*2)+(x3*3)
    *      OR
    *  x1+x2+x2+x3+x3+x3 (this is the periodSum)
    *
    * When you move forward in the time serie
    * you can quickly adjust the periodSum for the
    * period by substracting:
    *   x1+x2+x3 (This is the periodSub)
    * Making the new periodSum equals to:
    *   x2+x3+x3
    *
    * You can then add the new price bar
    * which is x4+x4+x4 giving:
    *   x2+x3+x3+x4+x4+x4
    *
    * At this point one iteration is completed and you can
    * see that we are back to the step 1 of this example.
    *
    * Why making it so un-intuitive? The number of memory
    * access and floating point operations are kept to a
    * minimum with this algo.
    */
   outIdx = 0;
   trailingIdx = startIdx - lookbackTotal;
   /* Evaluate the initial periodSum/periodSub and trailingValue. */
   periodSub = (double)0.0;
   periodSum = periodSub;
   inIdx = trailingIdx;
   i = 1;
   while( inIdx < startIdx )
   {
      tempReal = inReal[inIdx++];
      periodSub += tempReal;
      periodSum += tempReal * i;
      i += 1;
   }
   trailingValue = 0.0;
   /* Tight loop for the requested range. */
   while( inIdx <= endIdx )
   {
      /* Add the current price bar to the sum
       * who are carried through the iterations.
       */
      tempReal = inReal[inIdx++];
      periodSub += tempReal;
      periodSub -= trailingValue;
      periodSum += tempReal * optInTimePeriod;
      /* Save the trailing value for being substract at
       * the next iteration.
       * (must be saved here just in case outReal and
       *  inReal are the same buffer).
       */
      trailingValue = inReal[trailingIdx++];
      /* Calculate the WMA for this price bar. */
      outReal[outIdx++] = periodSum / divider;
      /* Prepare the periodSum for the next iteration. */
      periodSum -= periodSub;
   }
   /* Set output limits. */
   *outNBElement= outIdx;
   *outBegIdx= startIdx;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_WMA_Unguarded( int    startIdx,
                                        int    endIdx,
                                        const double inReal[],
                                        int optInTimePeriod,
                                        int          *outBegIdx,
                                        int          *outNBElement,
                                        double        outReal[] )
{
   int inIdx;
   int outIdx;
   int i;
   int trailingIdx;
   int divider;
   double periodSum;
   double periodSub;
   double tempReal;
   double trailingValue;
   int lookbackTotal;

   lookbackTotal = optInTimePeriod - 1;
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   if( optInTimePeriod == 1 )
   {
      *outBegIdx= startIdx;
      *outNBElement= endIdx - startIdx + 1;
      memmove(outReal,&inReal[startIdx],(int)*outNBElement * sizeof(double));
      return TA_SUCCESS;
   }
   divider = optInTimePeriod * (optInTimePeriod + 1) >> 1;
   outIdx = 0;
   trailingIdx = startIdx - lookbackTotal;
   periodSub = (double)0.0;
   periodSum = periodSub;
   inIdx = trailingIdx;
   i = 1;
   while( inIdx < startIdx )
   {
      tempReal = inReal[inIdx++];
      periodSub += tempReal;
      periodSum += tempReal * i;
      i += 1;
   }
   trailingValue = 0.0;
   while( inIdx <= endIdx )
   {
      tempReal = inReal[inIdx++];
      periodSub += tempReal;
      periodSub -= trailingValue;
      periodSum += tempReal * optInTimePeriod;
      trailingValue = inReal[trailingIdx++];
      outReal[outIdx++] = periodSum / divider;
      periodSum -= periodSub;
   }
   *outNBElement= outIdx;
   *outBegIdx= startIdx;
   return TA_SUCCESS;
}

TA_RetCode TA_S_WMA( int    startIdx,
                     int    endIdx,
                     const float inReal[],
                     int optInTimePeriod,
                     int          *outBegIdx,
                     int          *outNBElement,
                     double        outReal[] )
{
   int inIdx;
   int outIdx;
   int i;
   int trailingIdx;
   int divider;
   double periodSum;
   double periodSub;
   double tempReal;
   double trailingValue;
   int lookbackTotal;

   if( startIdx < 0 )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( !inReal )
      return TA_BAD_PARAM;
   if( (int)optInTimePeriod == (int)0x80000000 )
      optInTimePeriod = 30;
   else if( (int)optInTimePeriod < 1 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   lookbackTotal = optInTimePeriod - 1;
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   if( optInTimePeriod == 1 )
   {
      *outBegIdx= startIdx;
      *outNBElement= endIdx - startIdx + 1;
      memmove(outReal,&inReal[startIdx],(int)*outNBElement * sizeof(double));
      return TA_SUCCESS;
   }
   divider = optInTimePeriod * (optInTimePeriod + 1) >> 1;
   outIdx = 0;
   trailingIdx = startIdx - lookbackTotal;
   periodSub = (double)0.0;
   periodSum = periodSub;
   inIdx = trailingIdx;
   i = 1;
   while( inIdx < startIdx )
   {
      tempReal = (double)inReal[inIdx++];
      periodSub += tempReal;
      periodSum += tempReal * i;
      i += 1;
   }
   trailingValue = 0.0;
   while( inIdx <= endIdx )
   {
      tempReal = (double)inReal[inIdx++];
      periodSub += tempReal;
      periodSub -= trailingValue;
      periodSum += tempReal * optInTimePeriod;
      trailingValue = (double)inReal[trailingIdx++];
      outReal[outIdx++] = periodSum / divider;
      periodSum -= periodSub;
   }
   *outNBElement= outIdx;
   *outBegIdx= startIdx;
   return TA_SUCCESS;
}

TA_RetCode TA_S_WMA_Unguarded( int    startIdx,
                               int    endIdx,
                               const float inReal[],
                               int optInTimePeriod,
                               int          *outBegIdx,
                               int          *outNBElement,
                               double        outReal[] )
{
   int inIdx;
   int outIdx;
   int i;
   int trailingIdx;
   int divider;
   double periodSum;
   double periodSub;
   double tempReal;
   double trailingValue;
   int lookbackTotal;

   lookbackTotal = optInTimePeriod - 1;
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   if( optInTimePeriod == 1 )
   {
      *outBegIdx= startIdx;
      *outNBElement= endIdx - startIdx + 1;
      memmove(outReal,&inReal[startIdx],(int)*outNBElement * sizeof(double));
      return TA_SUCCESS;
   }
   divider = optInTimePeriod * (optInTimePeriod + 1) >> 1;
   outIdx = 0;
   trailingIdx = startIdx - lookbackTotal;
   periodSub = (double)0.0;
   periodSum = periodSub;
   inIdx = trailingIdx;
   i = 1;
   while( inIdx < startIdx )
   {
      tempReal = (double)inReal[inIdx++];
      periodSub += tempReal;
      periodSum += tempReal * i;
      i += 1;
   }
   trailingValue = 0.0;
   while( inIdx <= endIdx )
   {
      tempReal = (double)inReal[inIdx++];
      periodSub += tempReal;
      periodSub -= trailingValue;
      periodSum += tempReal * optInTimePeriod;
      trailingValue = (double)inReal[trailingIdx++];
      outReal[outIdx++] = periodSum / divider;
      periodSum -= periodSub;
   }
   *outNBElement= outIdx;
   *outBegIdx= startIdx;
   return TA_SUCCESS;
}

/**** Streaming API *****/

struct TA_WMA_Stream {
   int optInTimePeriod;
   int divider;
   double periodSum;
   double periodSub;
   double trailingValue;
   int ringPos_trailingIdx;
   int ringCap_trailingIdx;
   double *ring_trailingIdx_inReal;
   double *ringMirror_trailingIdx_inReal;
};

/* Private function, not in public API. */
static void TA_WMA_ReleaseInternal( struct TA_WMA_Stream *sp )
{
   if( !sp ) return;
   if( sp->ring_trailingIdx_inReal ) TA_Free( sp->ring_trailingIdx_inReal );
   if( sp->ringMirror_trailingIdx_inReal ) TA_Free( sp->ringMirror_trailingIdx_inReal );
   TA_Free( sp );
}

/* Private function, not in public API. */
static void TA_WMA_StepInternal( struct TA_WMA_Stream *sp, double inReal, double *outReal )
{
   double tempReal;

   if( sp->optInTimePeriod == 1 )
   {
      *outReal= inReal;
      return;
   }
   if( sp->ringCap_trailingIdx == 0 )
   {
      sp->ring_trailingIdx_inReal[0] = inReal;
   }
   /* Add the current price bar to the sum
    * who are carried through the iterations.
    */
   tempReal = inReal;
   sp->periodSub += tempReal;
   sp->periodSub -= sp->trailingValue;
   sp->periodSum += tempReal * sp->optInTimePeriod;
   /* Save the trailing value for being substract at
    * the next iteration.
    * (must be saved here just in case outReal and
    *  inReal are the same buffer).
    */
   sp->trailingValue = sp->ring_trailingIdx_inReal[sp->ringPos_trailingIdx];
   /* Calculate the WMA for this price bar. */
   *outReal= sp->periodSum / sp->divider;
   /* Prepare the periodSum for the next iteration. */
   sp->periodSum -= sp->periodSub;
   sp->ring_trailingIdx_inReal[sp->ringPos_trailingIdx] = inReal;
   sp->ringPos_trailingIdx = sp->ringPos_trailingIdx + 1;
   if( sp->ringPos_trailingIdx >= sp->ringCap_trailingIdx )
   {
      sp->ringPos_trailingIdx = 0;
   }
}

/* Private function, not in public API. */
TA_RetCode TA_WMA_OpenInternal( int optInTimePeriod, const double inReal[], int startIdx, int historyLen, struct TA_WMA_Stream **stream, double *outReal )
{
   struct TA_WMA_Stream *sp;
   int endIdx;
   int dummyBegIdx;
   int dummyNBElement;
   double lastValue_outReal;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( !inReal || !outReal ) return TA_BAD_PARAM;
   if( historyLen < 1 ) return TA_BAD_PARAM;
   if( (int)optInTimePeriod == (int)0x80000000 )
      optInTimePeriod = 30;
   else if( (int)optInTimePeriod < 1 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;

   endIdx = historyLen - 1;
   dummyBegIdx = 0;
   dummyNBElement = 0;
   lastValue_outReal = 0.0;
   (void)startIdx; (void)dummyBegIdx; (void)dummyNBElement;

   if( optInTimePeriod == 1 )
   {
      if( historyLen < TA_WMA_Lookback( optInTimePeriod ) + 1 ) return TA_BAD_PARAM;
      sp = (struct TA_WMA_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) { return TA_ALLOC_ERR; }
      memset( sp, 0, sizeof(*sp) );
      sp->optInTimePeriod = optInTimePeriod;
      sp->ringCap_trailingIdx = 0;
      { size_t allocN = (size_t)(sp->ringCap_trailingIdx > 0 ? sp->ringCap_trailingIdx : 1);
        sp->ring_trailingIdx_inReal = (double *)TA_Malloc( sizeof(double) * allocN );
        if( !sp->ring_trailingIdx_inReal ) { TA_WMA_ReleaseInternal( sp ); return TA_ALLOC_ERR; }
        sp->ringMirror_trailingIdx_inReal = (double *)TA_Malloc( sizeof(double) * allocN );
        if( !sp->ringMirror_trailingIdx_inReal ) { TA_WMA_ReleaseInternal( sp ); return TA_ALLOC_ERR; }
        memset( sp->ring_trailingIdx_inReal, 0, sizeof(double) * allocN );
      }
      sp->ringPos_trailingIdx = 0;
      *outReal = inReal[historyLen - 1];
      *stream = sp;
      return TA_SUCCESS;
   }

   {
      int inIdx;
      int outIdx;
      int i;
      int trailingIdx;
      int divider = 0;
      double periodSum = 0.0;
      double periodSub = 0.0;
      double tempReal;
      double trailingValue = 0.0;
      int lookbackTotal;
      lookbackTotal = optInTimePeriod - 1;
      /* Move up the start index if there is not
       * enough initial data.
       */
      if( startIdx < lookbackTotal )
      {
         startIdx = lookbackTotal;
      }
      /* Make sure there is still something to evaluate. */
      if( startIdx > endIdx )
      {
         dummyBegIdx = 0;
         dummyNBElement = 0;
         return TA_BAD_PARAM;
      }
      /* To make the rest more efficient, handle exception
       * case where the user is asking for a period of '1'.
       * In that case outputs equals inputs for the requested
       * range.
       */
      if( optInTimePeriod == 1 )
      {
         dummyBegIdx = startIdx;
         dummyNBElement = endIdx - startIdx + 1;
         memmove(outReal,&inReal[startIdx],(int)dummyNBElement * sizeof(double));
         return TA_BAD_PARAM;
      }
      /* Calculate the divider (always an integer value).
       * By induction: 1+2+3+4+'n' = n(n+1)/2
       * '>>1' is usually faster than '/2' for unsigned.
       */
      divider = optInTimePeriod * (optInTimePeriod + 1) >> 1;
      /* The algo used here use a very basic property of
       * multiplication/addition: (x*2) = x+x
       *
       * As an example, a 3 period weighted can be
       * interpreted in two way:
       *  (x1*1)+(x2*2)+(x3*3)
       *      OR
       *  x1+x2+x2+x3+x3+x3 (this is the periodSum)
       *
       * When you move forward in the time serie
       * you can quickly adjust the periodSum for the
       * period by substracting:
       *   x1+x2+x3 (This is the periodSub)
       * Making the new periodSum equals to:
       *   x2+x3+x3
       *
       * You can then add the new price bar
       * which is x4+x4+x4 giving:
       *   x2+x3+x3+x4+x4+x4
       *
       * At this point one iteration is completed and you can
       * see that we are back to the step 1 of this example.
       *
       * Why making it so un-intuitive? The number of memory
       * access and floating point operations are kept to a
       * minimum with this algo.
       */
      outIdx = 0;
      trailingIdx = startIdx - lookbackTotal;
      /* Evaluate the initial periodSum/periodSub and trailingValue. */
      periodSub = (double)0.0;
      periodSum = periodSub;
      inIdx = trailingIdx;
      i = 1;
      while( inIdx < startIdx )
      {
         tempReal = inReal[inIdx++];
         periodSub += tempReal;
         periodSum += tempReal * i;
         i += 1;
      }
      trailingValue = 0.0;
      /* Tight loop for the requested range. */
      while( inIdx <= endIdx )
      {
         /* Add the current price bar to the sum
          * who are carried through the iterations.
          */
         tempReal = inReal[inIdx++];
         periodSub += tempReal;
         periodSub -= trailingValue;
         periodSum += tempReal * optInTimePeriod;
         /* Save the trailing value for being substract at
          * the next iteration.
          * (must be saved here just in case outReal and
          *  inReal are the same buffer).
          */
         trailingValue = inReal[trailingIdx++];
         /* Calculate the WMA for this price bar. */
         lastValue_outReal = periodSum / divider;
         /* Prepare the periodSum for the next iteration. */
         periodSum -= periodSub;
      }
      /* Set output limits. */
      dummyNBElement = outIdx;
      dummyBegIdx = startIdx;

      /* Capture the live batch state into the handle. */
      sp = (struct TA_WMA_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) { return TA_ALLOC_ERR; }
      memset( sp, 0, sizeof(*sp) );
      sp->optInTimePeriod = optInTimePeriod;
      sp->divider = divider;
      sp->periodSum = periodSum;
      sp->periodSub = periodSub;
      sp->trailingValue = trailingValue;
      sp->ringCap_trailingIdx = (int)(inIdx - trailingIdx);
      if( sp->ringCap_trailingIdx < 0 || sp->ringCap_trailingIdx > historyLen ) { TA_WMA_ReleaseInternal( sp ); return TA_INTERNAL_ERROR; }
      { size_t allocN = (size_t)(sp->ringCap_trailingIdx > 0 ? sp->ringCap_trailingIdx : 1);
        sp->ring_trailingIdx_inReal = (double *)TA_Malloc( sizeof(double) * allocN );
        if( !sp->ring_trailingIdx_inReal ) { TA_WMA_ReleaseInternal( sp ); return TA_ALLOC_ERR; }
        sp->ringMirror_trailingIdx_inReal = (double *)TA_Malloc( sizeof(double) * allocN );
        if( !sp->ringMirror_trailingIdx_inReal ) { TA_WMA_ReleaseInternal( sp ); return TA_ALLOC_ERR; }
        memcpy( sp->ring_trailingIdx_inReal, inReal + (historyLen - sp->ringCap_trailingIdx), sizeof(double) * (size_t)sp->ringCap_trailingIdx );
      }
      sp->ringPos_trailingIdx = 0;
      *outReal = lastValue_outReal;
      *stream = sp;
      return TA_SUCCESS;
   }
}

TA_LIB_API TA_RetCode TA_WMA_Open( int optInTimePeriod, const double inReal[], int historyLen, TA_WMA_Stream **stream, double *outReal )
{
   return TA_WMA_OpenInternal( optInTimePeriod, inReal, 0, historyLen, stream, outReal );
}

TA_LIB_API TA_RetCode TA_WMA_Update( TA_WMA_Stream *stream, double inReal, double *outReal )
{
   if( !stream || !outReal ) return TA_BAD_PARAM;
   TA_WMA_StepInternal( stream, inReal, outReal );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_WMA_Peek( const TA_WMA_Stream *stream, double inReal, double *outReal )
{
   struct TA_WMA_Stream scratch;

   if( !stream || !outReal ) return TA_BAD_PARAM;
   scratch = *stream;
   scratch.ring_trailingIdx_inReal = stream->ringMirror_trailingIdx_inReal;
   memcpy( scratch.ring_trailingIdx_inReal, stream->ring_trailingIdx_inReal, sizeof(double) * (size_t)(stream->ringCap_trailingIdx > 0 ? stream->ringCap_trailingIdx : 1) );
   TA_WMA_StepInternal( &scratch, inReal, outReal );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_WMA_Close( TA_WMA_Stream *stream )
{
   TA_WMA_ReleaseInternal( stream );
   return TA_SUCCESS;
}

