/* TA-LIB Copyright (c) 1999-2026, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_stream_private.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  MF       Mario Fortier
 *  CC       Claude Code (AI assistant)
 *
 * Change history:
 *
 *  MMDDYY BY     Description
 *  -------------------------------------------------------------------
 *  100626 MF,CC  Initial version (#476).
 */

TA_LIB_API int TA_WAVETREND_Lookback( int optInChannelPeriod, int optInAveragePeriod, int optInSignalPeriod )
{
   if( (int)optInChannelPeriod == TA_INTEGER_DEFAULT )
      optInChannelPeriod = 10;
   else if( (int)optInChannelPeriod < 2 || (int)optInChannelPeriod > 100000 )
      return -1;
   if( (int)optInAveragePeriod == TA_INTEGER_DEFAULT )
      optInAveragePeriod = 21;
   else if( (int)optInAveragePeriod < 1 || (int)optInAveragePeriod > 100000 )
      return -1;
   if( (int)optInSignalPeriod == TA_INTEGER_DEFAULT )
      optInSignalPeriod = 4;
   else if( (int)optInSignalPeriod < 1 || (int)optInSignalPeriod > 100000 )
      return -1;
   /* Two exponential averages over the channel period -- one of the typical
    * price, one of the absolute distance from it -- then the oscillator's own
    * smoothing and the simple average that makes the signal line. Every term
    * is exactly the lookback of the function it comes from, so none of them is
    * restated here: that is what makes WAVETREND inherit TA_FUNC_UNST_EMA from
    * its callees rather than take an id of its own.
    *
    * The EMA term appears THREE times, so a warm
    * TA_SetUnstablePeriod(TA_FUNC_UNST_EMA, k) moves the lookback by 3k.
    */
   return TA_EMA_Lookback(optInChannelPeriod) + TA_EMA_Lookback(optInChannelPeriod) + TA_EMA_Lookback(optInAveragePeriod) + TA_SMA_Lookback(optInSignalPeriod);
}

TA_LIB_API int TA_WAVETREND_DisplayShift( int optInChannelPeriod, int optInAveragePeriod, int optInSignalPeriod, int outputIdx )
{
   if( TA_WAVETREND_Lookback( optInChannelPeriod, optInAveragePeriod, optInSignalPeriod ) < 0 )
      return INT_MIN;
   if( outputIdx < 0 || outputIdx >= 2 )
      return INT_MIN;
   return 0;
}

TA_FMA_MULTIVERSION
TA_LIB_API TA_RetCode TA_WAVETREND( int    startIdx,
                                    int    endIdx,
                                    const double inHigh[],
                                    const double inLow[],
                                    const double inClose[],
                                    int optInChannelPeriod,
                                    int optInAveragePeriod,
                                    int optInSignalPeriod,
                                    int          *outBegIdx,
                                    int          *outNBElement,
                                    double        outWT1[],
                                    double        outWT2[] )
{
   double k1;
   double beta1;
   double k2;
   double beta2;
   double ap;
   double esa;
   double dev;
   double d;
   double ci;
   double wt1;
   double prevAp;
   double prevEsa;
   double num;
   double scaledDev;
   double sumEsa;
   double sumD;
   double sumCi;
   double sumSignal;
   int lookbackTotal;
   int lookbackChannel;
   int lookbackAverage;
   int today;
   int outIdx;
   int nAp;
   int nDev;
   int nCi;
   int nSig;
   double local_wtBuffer[32];
   double *wtBuffer = &local_wtBuffer[0];
   int wtBuffer_Idx;
   int maxIdx_wtBuffer;

   if( (startIdx < 0) || (startIdx > TA_INDEX_MAX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_INDEX_MAX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInChannelPeriod == TA_INTEGER_DEFAULT )
      optInChannelPeriod = 10;
   else if( (int)optInChannelPeriod < 2 || (int)optInChannelPeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInAveragePeriod == TA_INTEGER_DEFAULT )
      optInAveragePeriod = 21;
   else if( (int)optInAveragePeriod < 1 || (int)optInAveragePeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInSignalPeriod == TA_INTEGER_DEFAULT )
      optInSignalPeriod = 4;
   else if( (int)optInSignalPeriod < 1 || (int)optInSignalPeriod > 100000 )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !inClose )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outWT1 )
      return TA_BAD_PARAM;
   if( !outWT2 )
      return TA_BAD_PARAM;
   if( outWT1 == outWT2 )
      return TA_BAD_PARAM;

   /* LazyBear's WaveTrend Oscillator (TradingView, 2014), lines 14 to 21: the
    * typical price's distance from its own exponential average, normalised by
    * an exponential average of that distance's absolute value and by Lambert's
    * CCI constant, then smoothed.
    *
    *    ap  = (H + L + C)/3
    *    esa = EMA(ap, n1)
    *    d   = EMA(|ap - esa|, n1)
    *    ci  = (ap - esa) / (0.015 * d)
    *    WT1 = EMA(ci, n2)        WT2 = SMA(WT1, n3)
    *
    * The middle stage is an exponential CCI, not TA_CCI: cci.c averages with
    * an SMA and takes the mean deviation around that window's own SMA, where
    * this uses two exponential averages.
    *
    * Each stage seeds the way ema.c and sma.c seed, and each stage boundary
    * below is the callee's LOOKBACK rather than (period-1), so the result is
    * bit-identical to the composed chain on moving data and a warm unstable
    * period folds in. The two guards are what the chain cannot express; they
    * are the reason this ships as a function.
    */
   /* This ptr will point on a circular buffer of at least
    * "optInSignalPeriod" element.
    */
   lookbackTotal = TA_WAVETREND_Lookback(optInChannelPeriod,optInAveragePeriod,optInSignalPeriod);
   /* Move up the start index if there is not
    * enough initial data.
    */
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   /* Make sure there is still something to evaluate. */
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   if( optInSignalPeriod < 1 ) return TA_INTERNAL_ERROR(485);
   if( (int)optInSignalPeriod > (int)(sizeof(local_wtBuffer)/sizeof(double)) )
   {
      wtBuffer = TA_Malloc( sizeof(double)*optInSignalPeriod );
      if( !wtBuffer )
      {
         return TA_ALLOC_ERR;
      }
   }
   else
   {
      wtBuffer = &local_wtBuffer[0];
   }
   maxIdx_wtBuffer = (optInSignalPeriod-1);
   wtBuffer_Idx = 0;
   lookbackChannel = TA_EMA_Lookback(optInChannelPeriod);
   lookbackAverage = TA_EMA_Lookback(optInAveragePeriod);
   beta1 = (double)(optInChannelPeriod - 1) / (double)(optInChannelPeriod + 1);
   k1 = 1.0 - beta1;
   beta1 = 1.0 - k1;
   beta2 = (double)(optInAveragePeriod - 1) / (double)(optInAveragePeriod + 1);
   k2 = 1.0 - beta2;
   beta2 = 1.0 - k2;
   esa = 0.0;
   d = 0.0;
   ci = 0.0;
   wt1 = 0.0;
   sumEsa = 0.0;
   sumD = 0.0;
   sumCi = 0.0;
   sumSignal = 0.0;
   nAp = 0;
   /* The fixpoint test compares against the previous bar's pair. Starting both
    * at 0.0 cannot make it fire spuriously: it would need a bar whose typical
    * price and whose exponential average are both exactly zero, and a zero
    * typical price makes the numerator zero anyway, which is what the test
    * would have substituted.
    */
   prevAp = 0.0;
   prevEsa = 0.0;
   today = startIdx - lookbackTotal;
   /* Warm-up. Runs through startIdx inclusive: the last pass is the one that
    * completes the signal window, so it leaves the first output in the state.
    */
   while( today <= startIdx )
   {
      ap = (inHigh[today] + inLow[today] + inClose[today]) / 3.0;
      /* Stage 1: the exponential average of the typical price. */
      if( nAp < optInChannelPeriod )
      {
         sumEsa = sumEsa + ap;
         if( nAp == optInChannelPeriod - 1 )
         {
            esa = sumEsa / optInChannelPeriod;
         }
      } else 
      {
         esa = fma(beta1, esa, k1 * ap);
      }
      /* Stage 2: the exponential average of the absolute distance, over what
       * stage 1 publishes. The counter is compared before it is subtracted,
       * never after: the Rust backend renders these as usize.
       */
      if( nAp >= lookbackChannel )
      {
         nDev = nAp - lookbackChannel;
         /* GUARD 1, the fixpoint test. With a constant input the exponential
          * step stops moving once k*|ap - esa| falls under half an ulp, and
          * esa then FREEZES up to (n1+1)/4 ulps away from the price. That
          * frozen residue is a real non-zero distance, so the naive form
          * divides it by its own exponential average and walks to
          * +/-1/0.015 = +/-66.67 -- an extreme reading produced by nothing
          * but rounding. When the pair has not moved, the average has reached
          * its fixpoint and the distance is exactly that residue, so the
          * numerator is taken as zero. The test is exact, so it is
          * independent of scale and period, unlike a fixed epsilon band.
          */
         num = ap - esa;
         if( ap == prevAp && esa == prevEsa )
         {
            num = 0.0;
         }
         dev = num;
         if( dev < 0.0 )
         {
            dev = -dev;
         }
         if( nDev < optInChannelPeriod )
         {
            sumD = sumD + dev;
            if( nDev == optInChannelPeriod - 1 )
            {
               d = sumD / optInChannelPeriod;
            }
         } else 
         {
            d = fma(beta1, d, k1 * dev);
         }
         /* Stage 3: the oscillator, then its own smoothing. */
         if( nDev >= lookbackChannel )
         {
            nCi = nDev - lookbackChannel;
            /* GUARD 2, the exact divisor. Test the PRODUCT the division uses,
             * not the deviation: 0.015*d underflows to zero while d is still
             * non-zero (#395). A zero divisor is 0/0 -- no distance against no
             * average distance -- so the oscillator reads its neutral 0.0
             * (#112), as tsi.c does.
             */
            scaledDev = 0.015 * d;
            if( scaledDev > 0.0 )
            {
               ci = num / scaledDev;
            } else 
            {
               ci = 0.0;
            }
            if( nCi < optInAveragePeriod )
            {
               sumCi = sumCi + ci;
               if( nCi == optInAveragePeriod - 1 )
               {
                  wt1 = sumCi / optInAveragePeriod;
               }
            } else 
            {
               wt1 = fma(beta2, wt1, k2 * ci);
            }
            if( nCi >= lookbackAverage )
            {
               wtBuffer[wtBuffer_Idx] = wt1;
               sumSignal = sumSignal + wt1;
               wtBuffer_Idx++;
               if( wtBuffer_Idx > maxIdx_wtBuffer ) wtBuffer_Idx = 0;
            }
         }
      }
      prevAp = ap;
      prevEsa = esa;
      nAp = nAp + 1;
      today = today + 1;
   }
   /* The first output. The warm-up's last pass stored this bar's WT1 into the
    * ring and added it to the running sum, so the average is ready here.
    */
   outWT1[0] = wt1;
   outWT2[0] = sumSignal / (double)optInSignalPeriod;
   outIdx = 1;
   sumSignal = sumSignal - wtBuffer[wtBuffer_Idx];
   /* Stable zone. One bar past the first output every stage is past its seed,
    * at every reachable parameter triple: the shortest case, 2/1/1, arrives
    * with the deviation average and the oscillator smoothing both one bar
    * into their recursions. So nothing here branches on a counter, and the
    * stores always run -- which is what keeps the managed backends' peek
    * frames from carrying a seeded output local.
    */
   while( today <= endIdx )
   {
      ap = (inHigh[today] + inLow[today] + inClose[today]) / 3.0;
      esa = fma(beta1, esa, k1 * ap);
      num = ap - esa;
      if( ap == prevAp && esa == prevEsa )
      {
         num = 0.0;
      }
      dev = num;
      if( dev < 0.0 )
      {
         dev = -dev;
      }
      d = fma(beta1, d, k1 * dev);
      scaledDev = 0.015 * d;
      if( scaledDev > 0.0 )
      {
         ci = num / scaledDev;
      } else 
      {
         ci = 0.0;
      }
      wt1 = fma(beta2, wt1, k2 * ci);
      wtBuffer[wtBuffer_Idx] = wt1;
      sumSignal = sumSignal + wt1;
      outWT1[outIdx] = wt1;
      outWT2[outIdx] = sumSignal / (double)optInSignalPeriod;
      outIdx = outIdx + 1;
      wtBuffer_Idx++;
      if( wtBuffer_Idx > maxIdx_wtBuffer ) wtBuffer_Idx = 0;
      sumSignal = sumSignal - wtBuffer[wtBuffer_Idx];
      prevAp = ap;
      prevEsa = esa;
      today = today + 1;
   }
   if( wtBuffer != &local_wtBuffer[0] ) { TA_Free( wtBuffer ); wtBuffer = &local_wtBuffer[0]; }
   *outNBElement= outIdx;
   *outBegIdx= startIdx;
   return TA_SUCCESS;
}

TA_FMA_MULTIVERSION
TA_RetCode TA_S_WAVETREND( int    startIdx,
                           int    endIdx,
                           const float inHigh[],
                           const float inLow[],
                           const float inClose[],
                           int optInChannelPeriod,
                           int optInAveragePeriod,
                           int optInSignalPeriod,
                           int          *outBegIdx,
                           int          *outNBElement,
                           double        outWT1[],
                           double        outWT2[] )
{
   double k1;
   double beta1;
   double k2;
   double beta2;
   double ap;
   double esa;
   double dev;
   double d;
   double ci;
   double wt1;
   double prevAp;
   double prevEsa;
   double num;
   double scaledDev;
   double sumEsa;
   double sumD;
   double sumCi;
   double sumSignal;
   int lookbackTotal;
   int lookbackChannel;
   int lookbackAverage;
   int today;
   int outIdx;
   int nAp;
   int nDev;
   int nCi;
   int nSig;
   double local_wtBuffer[32];
   double *wtBuffer = &local_wtBuffer[0];
   int wtBuffer_Idx;
   int maxIdx_wtBuffer;

   if( (startIdx < 0) || (startIdx > TA_INDEX_MAX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_INDEX_MAX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInChannelPeriod == TA_INTEGER_DEFAULT )
      optInChannelPeriod = 10;
   else if( (int)optInChannelPeriod < 2 || (int)optInChannelPeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInAveragePeriod == TA_INTEGER_DEFAULT )
      optInAveragePeriod = 21;
   else if( (int)optInAveragePeriod < 1 || (int)optInAveragePeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInSignalPeriod == TA_INTEGER_DEFAULT )
      optInSignalPeriod = 4;
   else if( (int)optInSignalPeriod < 1 || (int)optInSignalPeriod > 100000 )
      return TA_BAD_PARAM;
   if( !inHigh )
      return TA_BAD_PARAM;
   if( !inLow )
      return TA_BAD_PARAM;
   if( !inClose )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outWT1 )
      return TA_BAD_PARAM;
   if( !outWT2 )
      return TA_BAD_PARAM;
   if( outWT1 == outWT2 )
      return TA_BAD_PARAM;

   lookbackTotal = TA_WAVETREND_Lookback(optInChannelPeriod,optInAveragePeriod,optInSignalPeriod);
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   if( optInSignalPeriod < 1 ) return TA_INTERNAL_ERROR(485);
   if( (int)optInSignalPeriod > (int)(sizeof(local_wtBuffer)/sizeof(double)) )
   {
      wtBuffer = TA_Malloc( sizeof(double)*optInSignalPeriod );
      if( !wtBuffer )
      {
         return TA_ALLOC_ERR;
      }
   }
   else
   {
      wtBuffer = &local_wtBuffer[0];
   }
   maxIdx_wtBuffer = (optInSignalPeriod-1);
   wtBuffer_Idx = 0;
   lookbackChannel = TA_EMA_Lookback(optInChannelPeriod);
   lookbackAverage = TA_EMA_Lookback(optInAveragePeriod);
   beta1 = (double)(optInChannelPeriod - 1) / (double)(optInChannelPeriod + 1);
   k1 = 1.0 - beta1;
   beta1 = 1.0 - k1;
   beta2 = (double)(optInAveragePeriod - 1) / (double)(optInAveragePeriod + 1);
   k2 = 1.0 - beta2;
   beta2 = 1.0 - k2;
   esa = 0.0;
   d = 0.0;
   ci = 0.0;
   wt1 = 0.0;
   sumEsa = 0.0;
   sumD = 0.0;
   sumCi = 0.0;
   sumSignal = 0.0;
   nAp = 0;
   prevAp = 0.0;
   prevEsa = 0.0;
   today = startIdx - lookbackTotal;
   while( today <= startIdx )
   {
      ap = ((double)inHigh[today] + (double)inLow[today] + (double)inClose[today]) / 3.0;
      if( nAp < optInChannelPeriod )
      {
         sumEsa = sumEsa + ap;
         if( nAp == optInChannelPeriod - 1 )
         {
            esa = sumEsa / optInChannelPeriod;
         }
      } else 
      {
         esa = fma(beta1, esa, k1 * ap);
      }
      if( nAp >= lookbackChannel )
      {
         nDev = nAp - lookbackChannel;
         num = ap - esa;
         if( ap == prevAp && esa == prevEsa )
         {
            num = 0.0;
         }
         dev = num;
         if( dev < 0.0 )
         {
            dev = -dev;
         }
         if( nDev < optInChannelPeriod )
         {
            sumD = sumD + dev;
            if( nDev == optInChannelPeriod - 1 )
            {
               d = sumD / optInChannelPeriod;
            }
         } else 
         {
            d = fma(beta1, d, k1 * dev);
         }
         if( nDev >= lookbackChannel )
         {
            nCi = nDev - lookbackChannel;
            scaledDev = 0.015 * d;
            if( scaledDev > 0.0 )
            {
               ci = num / scaledDev;
            } else 
            {
               ci = 0.0;
            }
            if( nCi < optInAveragePeriod )
            {
               sumCi = sumCi + ci;
               if( nCi == optInAveragePeriod - 1 )
               {
                  wt1 = sumCi / optInAveragePeriod;
               }
            } else 
            {
               wt1 = fma(beta2, wt1, k2 * ci);
            }
            if( nCi >= lookbackAverage )
            {
               wtBuffer[wtBuffer_Idx] = wt1;
               sumSignal = sumSignal + wt1;
               wtBuffer_Idx++;
               if( wtBuffer_Idx > maxIdx_wtBuffer ) wtBuffer_Idx = 0;
            }
         }
      }
      prevAp = ap;
      prevEsa = esa;
      nAp = nAp + 1;
      today = today + 1;
   }
   outWT1[0] = wt1;
   outWT2[0] = sumSignal / (double)optInSignalPeriod;
   outIdx = 1;
   sumSignal = sumSignal - wtBuffer[wtBuffer_Idx];
   while( today <= endIdx )
   {
      ap = ((double)inHigh[today] + (double)inLow[today] + (double)inClose[today]) / 3.0;
      esa = fma(beta1, esa, k1 * ap);
      num = ap - esa;
      if( ap == prevAp && esa == prevEsa )
      {
         num = 0.0;
      }
      dev = num;
      if( dev < 0.0 )
      {
         dev = -dev;
      }
      d = fma(beta1, d, k1 * dev);
      scaledDev = 0.015 * d;
      if( scaledDev > 0.0 )
      {
         ci = num / scaledDev;
      } else 
      {
         ci = 0.0;
      }
      wt1 = fma(beta2, wt1, k2 * ci);
      wtBuffer[wtBuffer_Idx] = wt1;
      sumSignal = sumSignal + wt1;
      outWT1[outIdx] = wt1;
      outWT2[outIdx] = sumSignal / (double)optInSignalPeriod;
      outIdx = outIdx + 1;
      wtBuffer_Idx++;
      if( wtBuffer_Idx > maxIdx_wtBuffer ) wtBuffer_Idx = 0;
      sumSignal = sumSignal - wtBuffer[wtBuffer_Idx];
      prevAp = ap;
      prevEsa = esa;
      today = today + 1;
   }
   if( wtBuffer != &local_wtBuffer[0] ) { TA_Free( wtBuffer ); wtBuffer = &local_wtBuffer[0]; }
   *outNBElement= outIdx;
   *outBegIdx= startIdx;
   return TA_SUCCESS;
}

/**** Streaming API *****/

struct TA_WAVETREND_Stream {
   /* The bars this handle has an output for (see TA_WAVETREND_OutRange). */
   int outRangeBegIdx;
   int outRangeCount;
   /* The value(s) at the last bar the stream counted (see TA_WAVETREND_Value). */
   double cur_outWT1;
   double cur_outWT2;
   int optInChannelPeriod;
   int optInAveragePeriod;
   int optInSignalPeriod;
   double k1;
   double beta1;
   double k2;
   double beta2;
   double pad_0;
   double esa;
   double d;
   double wt1;
   double prevAp;
   double prevEsa;
   double sumSignal;
   int wtBuffer_Idx;
   int maxIdx_wtBuffer;
   int cbSize_wtBuffer;
   double *cb_wtBuffer;
};

/* Private function, not in public API. */
static void TA_WAVETREND_ReleaseImpl( struct TA_WAVETREND_Stream *sp )
{
   if( !sp ) return;
   if( sp->cb_wtBuffer ) TA_Free( sp->cb_wtBuffer );
   TA_Free( sp );
}

/* Private function, not in public API. */
static TA_FMA_STEP_INLINE void TA_WAVETREND_StepImpl( struct TA_WAVETREND_Stream *sp, double inHigh, double inLow, double inClose, double *outWT1, double *outWT2 )
{
   double ap;
   double dev;
   double ci;
   double num;
   double scaledDev;
   double esa;
   double wt1;
   double sumSignal;

   esa = sp->esa;
   wt1 = sp->wt1;
   sumSignal = sp->sumSignal;
   ap = (inHigh + inLow + inClose) / 3.0;
   esa = fma(sp->beta1, esa, sp->k1 * ap);
   num = ap - esa;
   if( ap == sp->prevAp && esa == sp->prevEsa )
   {
      num = 0.0;
   }
   dev = num;
   if( dev < 0.0 )
   {
      dev = -dev;
   }
   sp->d = fma(sp->beta1, sp->d, sp->k1 * dev);
   scaledDev = 0.015 * sp->d;
   if( scaledDev > 0.0 )
   {
      ci = num / scaledDev;
   } else 
   {
      ci = 0.0;
   }
   wt1 = fma(sp->beta2, wt1, sp->k2 * ci);
   sp->cb_wtBuffer[sp->wtBuffer_Idx] = wt1;
   sumSignal = sumSignal + wt1;
   *outWT1= wt1;
   *outWT2= sumSignal / (double)sp->optInSignalPeriod;
   sp->wtBuffer_Idx = sp->wtBuffer_Idx + 1;
   if( sp->wtBuffer_Idx > sp->maxIdx_wtBuffer )
   {
      sp->wtBuffer_Idx = 0;
   }
   sumSignal = sumSignal - sp->cb_wtBuffer[sp->wtBuffer_Idx];
   sp->prevAp = ap;
   sp->prevEsa = esa;
   sp->cur_outWT1 = *outWT1;
   sp->cur_outWT2 = *outWT2;
   sp->esa = esa;
   sp->wt1 = wt1;
   sp->sumSignal = sumSignal;
}

static TA_FMA_STEP_INLINE TA_RetCode TA_WAVETREND_OpenImpl( struct TA_WAVETREND_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], int startIdx, int historyLen, int optInChannelPeriod, int optInAveragePeriod, int optInSignalPeriod, int *outBegIdx, int *outNBElement, double outWT1[], double outWT2[], int outStride )
{
   struct TA_WAVETREND_Stream *sp;
   double local_wtBuffer[32];
   double *wtBuffer;
   int wtBuffer_Idx;
   int maxIdx_wtBuffer;
   int endIdx;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_INDEX_MAX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !inClose || !outWT1 || !outWT2 ) return TA_BAD_PARAM;
   if( (int)optInChannelPeriod == TA_INTEGER_DEFAULT )
      optInChannelPeriod = 10;
   else if( (int)optInChannelPeriod < 2 || (int)optInChannelPeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInAveragePeriod == TA_INTEGER_DEFAULT )
      optInAveragePeriod = 21;
   else if( (int)optInAveragePeriod < 1 || (int)optInAveragePeriod > 100000 )
      return TA_BAD_PARAM;
   if( (int)optInSignalPeriod == TA_INTEGER_DEFAULT )
      optInSignalPeriod = 4;
   else if( (int)optInSignalPeriod < 1 || (int)optInSignalPeriod > 100000 )
      return TA_BAD_PARAM;
   if( startIdx > historyLen - 1 )
   {
      *outBegIdx = 0;
      *outNBElement = 0;
      return TA_INSUFFICIENT_HISTORY;
   }

   endIdx = historyLen - 1;

   {
      double k1 = 0.0;
      double beta1 = 0.0;
      double k2 = 0.0;
      double beta2 = 0.0;
      double ap;
      double esa = 0.0;
      double dev;
      double d = 0.0;
      double ci;
      double wt1 = 0.0;
      double prevAp = 0.0;
      double prevEsa = 0.0;
      double num;
      double scaledDev;
      double sumEsa;
      double sumD;
      double sumCi;
      double sumSignal = 0.0;
      int lookbackTotal;
      int lookbackChannel;
      int lookbackAverage;
      int today;
      int outIdx;
      int nAp;
      int nDev;
      int nCi;
      int nSig;
      /* LazyBear's WaveTrend Oscillator (TradingView, 2014), lines 14 to 21: the
       * typical price's distance from its own exponential average, normalised by
       * an exponential average of that distance's absolute value and by Lambert's
       * CCI constant, then smoothed.
       *
       *    ap  = (H + L + C)/3
       *    esa = EMA(ap, n1)
       *    d   = EMA(|ap - esa|, n1)
       *    ci  = (ap - esa) / (0.015 * d)
       *    WT1 = EMA(ci, n2)        WT2 = SMA(WT1, n3)
       *
       * The middle stage is an exponential CCI, not TA_CCI: cci.c averages with
       * an SMA and takes the mean deviation around that window's own SMA, where
       * this uses two exponential averages.
       *
       * Each stage seeds the way ema.c and sma.c seed, and each stage boundary
       * below is the callee's LOOKBACK rather than (period-1), so the result is
       * bit-identical to the composed chain on moving data and a warm unstable
       * period folds in. The two guards are what the chain cannot express; they
       * are the reason this ships as a function.
       */
      /* This ptr will point on a circular buffer of at least
       * "optInSignalPeriod" element.
       */
      lookbackTotal = TA_WAVETREND_Lookback(optInChannelPeriod,optInAveragePeriod,optInSignalPeriod);
      /* Move up the start index if there is not
       * enough initial data.
       */
      if( startIdx < lookbackTotal )
      {
         startIdx = lookbackTotal;
      }
      /* Make sure there is still something to evaluate. */
      if( startIdx > endIdx )
      {
         *outBegIdx= 0;
         *outNBElement= 0;
         return TA_INSUFFICIENT_HISTORY;
      }
      if( optInSignalPeriod < 1 ) return TA_INTERNAL_ERROR(485);
      if( (int)optInSignalPeriod > (int)(sizeof(local_wtBuffer)/sizeof(double)) )
      {
         wtBuffer = TA_Malloc( sizeof(double)*optInSignalPeriod );
         if( !wtBuffer )
         {
            return TA_ALLOC_ERR;
         }
      }
      else
      {
         wtBuffer = &local_wtBuffer[0];
      }
      maxIdx_wtBuffer = (optInSignalPeriod-1);
      wtBuffer_Idx = 0;
      lookbackChannel = TA_EMA_Lookback(optInChannelPeriod);
      lookbackAverage = TA_EMA_Lookback(optInAveragePeriod);
      beta1 = (double)(optInChannelPeriod - 1) / (double)(optInChannelPeriod + 1);
      k1 = 1.0 - beta1;
      beta1 = 1.0 - k1;
      beta2 = (double)(optInAveragePeriod - 1) / (double)(optInAveragePeriod + 1);
      k2 = 1.0 - beta2;
      beta2 = 1.0 - k2;
      esa = 0.0;
      d = 0.0;
      ci = 0.0;
      wt1 = 0.0;
      sumEsa = 0.0;
      sumD = 0.0;
      sumCi = 0.0;
      sumSignal = 0.0;
      nAp = 0;
      /* The fixpoint test compares against the previous bar's pair. Starting both
       * at 0.0 cannot make it fire spuriously: it would need a bar whose typical
       * price and whose exponential average are both exactly zero, and a zero
       * typical price makes the numerator zero anyway, which is what the test
       * would have substituted.
       */
      prevAp = 0.0;
      prevEsa = 0.0;
      today = startIdx - lookbackTotal;
      /* Warm-up. Runs through startIdx inclusive: the last pass is the one that
       * completes the signal window, so it leaves the first output in the state.
       */
      while( today <= startIdx )
      {
         ap = (inHigh[today] + inLow[today] + inClose[today]) / 3.0;
         /* Stage 1: the exponential average of the typical price. */
         if( nAp < optInChannelPeriod )
         {
            sumEsa = sumEsa + ap;
            if( nAp == optInChannelPeriod - 1 )
            {
               esa = sumEsa / optInChannelPeriod;
            }
         } else 
         {
            esa = fma(beta1, esa, k1 * ap);
         }
         /* Stage 2: the exponential average of the absolute distance, over what
          * stage 1 publishes. The counter is compared before it is subtracted,
          * never after: the Rust backend renders these as usize.
          */
         if( nAp >= lookbackChannel )
         {
            nDev = nAp - lookbackChannel;
            /* GUARD 1, the fixpoint test. With a constant input the exponential
             * step stops moving once k*|ap - esa| falls under half an ulp, and
             * esa then FREEZES up to (n1+1)/4 ulps away from the price. That
             * frozen residue is a real non-zero distance, so the naive form
             * divides it by its own exponential average and walks to
             * +/-1/0.015 = +/-66.67 -- an extreme reading produced by nothing
             * but rounding. When the pair has not moved, the average has reached
             * its fixpoint and the distance is exactly that residue, so the
             * numerator is taken as zero. The test is exact, so it is
             * independent of scale and period, unlike a fixed epsilon band.
             */
            num = ap - esa;
            if( ap == prevAp && esa == prevEsa )
            {
               num = 0.0;
            }
            dev = num;
            if( dev < 0.0 )
            {
               dev = -dev;
            }
            if( nDev < optInChannelPeriod )
            {
               sumD = sumD + dev;
               if( nDev == optInChannelPeriod - 1 )
               {
                  d = sumD / optInChannelPeriod;
               }
            } else 
            {
               d = fma(beta1, d, k1 * dev);
            }
            /* Stage 3: the oscillator, then its own smoothing. */
            if( nDev >= lookbackChannel )
            {
               nCi = nDev - lookbackChannel;
               /* GUARD 2, the exact divisor. Test the PRODUCT the division uses,
                * not the deviation: 0.015*d underflows to zero while d is still
                * non-zero (#395). A zero divisor is 0/0 -- no distance against no
                * average distance -- so the oscillator reads its neutral 0.0
                * (#112), as tsi.c does.
                */
               scaledDev = 0.015 * d;
               if( scaledDev > 0.0 )
               {
                  ci = num / scaledDev;
               } else 
               {
                  ci = 0.0;
               }
               if( nCi < optInAveragePeriod )
               {
                  sumCi = sumCi + ci;
                  if( nCi == optInAveragePeriod - 1 )
                  {
                     wt1 = sumCi / optInAveragePeriod;
                  }
               } else 
               {
                  wt1 = fma(beta2, wt1, k2 * ci);
               }
               if( nCi >= lookbackAverage )
               {
                  wtBuffer[wtBuffer_Idx] = wt1;
                  sumSignal = sumSignal + wt1;
                  wtBuffer_Idx++;
                  if( wtBuffer_Idx > maxIdx_wtBuffer ) wtBuffer_Idx = 0;
               }
            }
         }
         prevAp = ap;
         prevEsa = esa;
         nAp = nAp + 1;
         today = today + 1;
      }
      /* The first output. The warm-up's last pass stored this bar's WT1 into the
       * ring and added it to the running sum, so the average is ready here.
       */
      outWT1[0 * outStride] = wt1;
      outWT2[0 * outStride] = sumSignal / (double)optInSignalPeriod;
      outIdx = 1;
      sumSignal = sumSignal - wtBuffer[wtBuffer_Idx];
      /* Stable zone. One bar past the first output every stage is past its seed,
       * at every reachable parameter triple: the shortest case, 2/1/1, arrives
       * with the deviation average and the oscillator smoothing both one bar
       * into their recursions. So nothing here branches on a counter, and the
       * stores always run -- which is what keeps the managed backends' peek
       * frames from carrying a seeded output local.
       */
      while( today <= endIdx )
      {
         ap = (inHigh[today] + inLow[today] + inClose[today]) / 3.0;
         esa = fma(beta1, esa, k1 * ap);
         num = ap - esa;
         if( ap == prevAp && esa == prevEsa )
         {
            num = 0.0;
         }
         dev = num;
         if( dev < 0.0 )
         {
            dev = -dev;
         }
         d = fma(beta1, d, k1 * dev);
         scaledDev = 0.015 * d;
         if( scaledDev > 0.0 )
         {
            ci = num / scaledDev;
         } else 
         {
            ci = 0.0;
         }
         wt1 = fma(beta2, wt1, k2 * ci);
         wtBuffer[wtBuffer_Idx] = wt1;
         sumSignal = sumSignal + wt1;
         outWT1[outIdx * outStride] = wt1;
         outWT2[outIdx * outStride] = sumSignal / (double)optInSignalPeriod;
         outIdx = outIdx + 1;
         wtBuffer_Idx++;
         if( wtBuffer_Idx > maxIdx_wtBuffer ) wtBuffer_Idx = 0;
         sumSignal = sumSignal - wtBuffer[wtBuffer_Idx];
         prevAp = ap;
         prevEsa = esa;
         today = today + 1;
      }
      *outNBElement= outIdx;
      *outBegIdx= startIdx;

      /* Capture the live batch state into the handle. */
      sp = (struct TA_WAVETREND_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) { if( wtBuffer != &local_wtBuffer[0] ) { TA_Free( wtBuffer ); } return TA_ALLOC_ERR; }
      memset( sp, 0, sizeof(*sp) );
      sp->optInChannelPeriod = optInChannelPeriod;
      sp->optInAveragePeriod = optInAveragePeriod;
      sp->optInSignalPeriod = optInSignalPeriod;
      sp->k1 = k1;
      sp->beta1 = beta1;
      sp->k2 = k2;
      sp->beta2 = beta2;
      sp->esa = esa;
      sp->d = d;
      sp->wt1 = wt1;
      sp->prevAp = prevAp;
      sp->prevEsa = prevEsa;
      sp->sumSignal = sumSignal;
      sp->wtBuffer_Idx = wtBuffer_Idx;
      sp->maxIdx_wtBuffer = maxIdx_wtBuffer;
      sp->cbSize_wtBuffer = maxIdx_wtBuffer + 1;
      if( sp->cbSize_wtBuffer < 1 || sp->cbSize_wtBuffer > historyLen + 1 ) { if( wtBuffer != &local_wtBuffer[0] ) { TA_Free( wtBuffer ); } TA_WAVETREND_ReleaseImpl( sp ); return TA_INTERNAL_ERROR(486); }
      sp->cb_wtBuffer = (double *)TA_Malloc( sizeof(double) * (size_t)sp->cbSize_wtBuffer );
      if( !sp->cb_wtBuffer ) { if( wtBuffer != &local_wtBuffer[0] ) { TA_Free( wtBuffer ); } TA_WAVETREND_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
      memcpy( sp->cb_wtBuffer, wtBuffer, sizeof(double) * (size_t)sp->cbSize_wtBuffer );
      if( wtBuffer != &local_wtBuffer[0] ) { TA_Free( wtBuffer ); } 
      sp->outRangeBegIdx = *outBegIdx;
      sp->outRangeCount = *outNBElement;
      sp->cur_outWT1 = outWT1[(*outNBElement - 1) * outStride];
      sp->cur_outWT2 = outWT2[(*outNBElement - 1) * outStride];
      *stream = sp;
      return TA_SUCCESS;
   }
}

TA_FMA_OPEN_CLONE static TA_RetCode TA_WAVETREND_OpenImplFma( struct TA_WAVETREND_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], int startIdx, int historyLen, int optInChannelPeriod, int optInAveragePeriod, int optInSignalPeriod, int *outBegIdx, int *outNBElement, double outWT1[], double outWT2[], int outStride )
{
   return TA_WAVETREND_OpenImpl( stream, inHigh, inLow, inClose, startIdx, historyLen, optInChannelPeriod, optInAveragePeriod, optInSignalPeriod, outBegIdx, outNBElement, outWT1, outWT2, outStride );
}

TA_FMA_OPEN_PLAIN static TA_RetCode TA_WAVETREND_OpenImplPlain( struct TA_WAVETREND_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], int startIdx, int historyLen, int optInChannelPeriod, int optInAveragePeriod, int optInSignalPeriod, int *outBegIdx, int *outNBElement, double outWT1[], double outWT2[], int outStride )
{
   return TA_WAVETREND_OpenImpl( stream, inHigh, inLow, inClose, startIdx, historyLen, optInChannelPeriod, optInAveragePeriod, optInSignalPeriod, outBegIdx, outNBElement, outWT1, outWT2, outStride );
}

/* Private function, not in public API. */
TA_RetCode TA_WAVETREND_OpenInternal( struct TA_WAVETREND_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], int startIdx, int historyLen, int optInChannelPeriod, int optInAveragePeriod, int optInSignalPeriod, double *outWT1, double *outWT2 )
{
   TA_RetCode retCode;
   int dummyBegIdx = 0;
   int dummyNBElement = 0;
   double sink_outWT1 = 0.0;
   double sink_outWT2 = 0.0;
   retCode = TA_FMA_AVAILABLE ? TA_WAVETREND_OpenImplFma( stream, inHigh, inLow, inClose, startIdx, historyLen, optInChannelPeriod, optInAveragePeriod, optInSignalPeriod, &dummyBegIdx, &dummyNBElement, &sink_outWT1, &sink_outWT2, 0 ) : TA_WAVETREND_OpenImplPlain( stream, inHigh, inLow, inClose, startIdx, historyLen, optInChannelPeriod, optInAveragePeriod, optInSignalPeriod, &dummyBegIdx, &dummyNBElement, &sink_outWT1, &sink_outWT2, 0 );
   if( retCode == TA_SUCCESS )
   {
      *outWT1 = sink_outWT1;
      *outWT2 = sink_outWT2;
   }
   return retCode;
}

TA_LIB_API TA_RetCode TA_WAVETREND_Open( TA_WAVETREND_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], int historyLen, int optInChannelPeriod, int optInAveragePeriod, int optInSignalPeriod, double *outWT1, double *outWT2 )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_INDEX_MAX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !inClose || !outWT1 || !outWT2 ) return TA_BAD_PARAM;
   return TA_WAVETREND_OpenInternal( stream, inHigh, inLow, inClose, 0, historyLen, optInChannelPeriod, optInAveragePeriod, optInSignalPeriod, outWT1, outWT2 );
}

TA_LIB_API TA_RetCode TA_WAVETREND_OpenAndFill( TA_WAVETREND_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], int historyLen, int optInChannelPeriod, int optInAveragePeriod, int optInSignalPeriod, int *outBegIdx, int *outNBElement, double outWT1[], double outWT2[] )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_INDEX_MAX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inHigh || !inLow || !inClose || !outBegIdx || !outNBElement || !outWT1 || !outWT2 ) return TA_BAD_PARAM;
   if( (const void *)outWT1 == (const void *)inHigh || (const void *)outWT1 == (const void *)inLow || (const void *)outWT1 == (const void *)inClose || (const void *)outWT2 == (const void *)inHigh || (const void *)outWT2 == (const void *)inLow || (const void *)outWT2 == (const void *)inClose || (const void *)outWT1 == (const void *)outWT2 ) return TA_BAD_PARAM;
   return TA_WAVETREND_OpenAndFillInternal( stream, inHigh, inLow, inClose, 0, historyLen, optInChannelPeriod, optInAveragePeriod, optInSignalPeriod, outBegIdx, outNBElement, outWT1, outWT2 );
}

/* Private function, not in public API. */
TA_RetCode TA_WAVETREND_OpenAndFillInternal( struct TA_WAVETREND_Stream **stream, const double inHigh[], const double inLow[], const double inClose[], int startIdx, int historyLen, int optInChannelPeriod, int optInAveragePeriod, int optInSignalPeriod, int *outBegIdx, int *outNBElement, double outWT1[], double outWT2[] )
{
   return TA_FMA_AVAILABLE ? TA_WAVETREND_OpenImplFma( stream, inHigh, inLow, inClose, startIdx, historyLen, optInChannelPeriod, optInAveragePeriod, optInSignalPeriod, outBegIdx, outNBElement, outWT1, outWT2, 1 ) : TA_WAVETREND_OpenImplPlain( stream, inHigh, inLow, inClose, startIdx, historyLen, optInChannelPeriod, optInAveragePeriod, optInSignalPeriod, outBegIdx, outNBElement, outWT1, outWT2, 1 );
}

TA_FMA_MULTIVERSION
TA_LIB_API TA_RetCode TA_WAVETREND_Update( TA_WAVETREND_Stream *stream, double inHigh, double inLow, double inClose, double *outWT1, double *outWT2 )
{
   if( !stream ) return TA_BAD_PARAM;
   if( stream->outRangeBegIdx + stream->outRangeCount > TA_INDEX_MAX )
      return TA_OUT_OF_RANGE_END_INDEX;
   if( !outWT1 || !outWT2 ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) || !TA_IS_FINITE( inClose ) ) return TA_BAD_PARAM;
   TA_WAVETREND_StepImpl( stream, inHigh, inLow, inClose, outWT1, outWT2 );
   stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_FMA_MULTIVERSION
TA_LIB_API TA_RetCode TA_WAVETREND_Peek( const TA_WAVETREND_Stream *stream, double inHigh, double inLow, double inClose, double *outWT1, double *outWT2 )
{
   const struct TA_WAVETREND_Stream *sp = stream;
   double ap;
   double dev;
   double ci;
   double num;
   double scaledDev;
   double d;
   double esa;
   double sumSignal;
   double wt1;

   if( !stream || !outWT1 || !outWT2 ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inHigh ) || !TA_IS_FINITE( inLow ) || !TA_IS_FINITE( inClose ) ) return TA_BAD_PARAM;
   d = sp->d;
   esa = sp->esa;
   sumSignal = sp->sumSignal;
   wt1 = sp->wt1;
   ap = (inHigh + inLow + inClose) / 3.0;
   esa = fma(sp->beta1, esa, sp->k1 * ap);
   num = ap - esa;
   if( ap == sp->prevAp && esa == sp->prevEsa )
   {
      num = 0.0;
   }
   dev = num;
   if( dev < 0.0 )
   {
      dev = -dev;
   }
   d = fma(sp->beta1, d, sp->k1 * dev);
   scaledDev = 0.015 * d;
   if( scaledDev > 0.0 )
   {
      ci = num / scaledDev;
   } else 
   {
      ci = 0.0;
   }
   wt1 = fma(sp->beta2, wt1, sp->k2 * ci);
   sumSignal = sumSignal + wt1;
   *outWT1= wt1;
   *outWT2= sumSignal / (double)sp->optInSignalPeriod;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_WAVETREND_Close( TA_WAVETREND_Stream *stream )
{
   TA_WAVETREND_ReleaseImpl( stream );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_WAVETREND_Value( const TA_WAVETREND_Stream *stream, double *outWT1, double *outWT2 )
{
   if( !stream || !outWT1 || !outWT2 ) return TA_BAD_PARAM;
   *outWT1 = stream->cur_outWT1;
   *outWT2 = stream->cur_outWT2;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_WAVETREND_OutRange( const TA_WAVETREND_Stream *stream, int *outBegIdx, int *outNBElement )
{
   if( !stream || !outBegIdx || !outNBElement ) return TA_BAD_PARAM;
   *outBegIdx = stream->outRangeBegIdx;
   *outNBElement = stream->outRangeCount;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_WAVETREND_Advance( TA_WAVETREND_Stream *stream )
{
   if( !stream ) return TA_BAD_PARAM;
   if( stream->outRangeBegIdx + stream->outRangeCount > TA_INDEX_MAX )
      return TA_OUT_OF_RANGE_END_INDEX;
   stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_WAVETREND_Clone( const TA_WAVETREND_Stream *stream, TA_WAVETREND_Stream **clone )
{
   struct TA_WAVETREND_Stream *sp;

   if( !clone ) return TA_BAD_PARAM;
   *clone = NULL;
   if( !stream ) return TA_BAD_PARAM;
   sp = (struct TA_WAVETREND_Stream *)TA_Malloc( sizeof(*sp) );
   if( !sp ) return TA_ALLOC_ERR;
   *sp = *stream;
   sp->cb_wtBuffer = NULL;
   if( stream->cb_wtBuffer )
   { size_t copyN = (size_t)(sp->cbSize_wtBuffer);
     sp->cb_wtBuffer = (double *)TA_Malloc( sizeof(double) * copyN );
     if( !sp->cb_wtBuffer ) { TA_WAVETREND_Close( sp ); return TA_ALLOC_ERR; }
     memcpy( sp->cb_wtBuffer, stream->cb_wtBuffer, sizeof(double) * copyN ); }
   *clone = sp;
   return TA_SUCCESS;
}

