/* TA-LIB Copyright (c) 1999-2026, Mario Fortier
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or
* without modification, are permitted provided that the following
* conditions are met:
*
* - Redistributions of source code must retain the above copyright
*   notice, this list of conditions and the following disclaimer.
*
* - Redistributions in binary form must reproduce the above copyright
*   notice, this list of conditions and the following disclaimer in
*   the documentation and/or other materials provided with the
*   distribution.
*
* - Neither name of author nor the names of its contributors
*   may be used to endorse or promote products derived from this
*   software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
* FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
* REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
* WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* AUTO-GENERATED by ta_codegen — DO NOT EDIT.
* Source of truth: ta_codegen/input/<name>/  (regenerate: cd ta_codegen/generator && cargo run -- generate)
*/

#include <string.h>
#include <math.h>
#include "ta_func.h"
#include "ta_utility.h"
#include "ta_memory.h"
#include "ta_func_stream_private.h"

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  MF       Mario Fortier
 *
 *
 * Change history:
 *
 *  MMDDYY BY   Description
 *  -------------------------------------------------------------------
 *  112400 MF   Template creation.
 *  052603 MF   Adapt code to compile with .NET Managed C++
 *  082426 MF,CC Fix #255. Re-anchor the running sums: every 32*period bars,
 *               and on the bar a large value leaves the window.
 */

TA_LIB_API int TA_WMA_Lookback( int optInTimePeriod )
{
   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 30;
   else if( (int)optInTimePeriod < 1 || (int)optInTimePeriod > 100000 )
      return -1;
   return optInTimePeriod - 1;
}

TA_LIB_API TA_RetCode TA_WMA( int    startIdx,
                              int    endIdx,
                              const double inReal[],
                              int optInTimePeriod,
                              int          *outBegIdx,
                              int          *outNBElement,
                              double        outReal[] )
{
   int inIdx;
   int outIdx;
   int i;
   int trailingIdx;
   int j;
   int rw;
   int lookbackWin;
   int barsSinceReseed;
   double periodSum;
   double periodSub;
   double tempReal;
   double trailingValue;
   double divider;
   int lookbackTotal;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 30;
   else if( (int)optInTimePeriod < 1 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( !inReal )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   lookbackTotal = optInTimePeriod - 1;
   /* Move up the start index if there is not
    * enough initial data.
    */
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   /* Make sure there is still something to evaluate. */
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   /* To make the rest more efficient, handle exception
    * case where the user is asking for a period of '1'.
    * In that case outputs equals inputs for the requested
    * range.
    */
   if( optInTimePeriod == 1 )
   {
      *outBegIdx= startIdx;
      *outNBElement= endIdx - startIdx + 1;
      /* Element loop, not a block copy: the C single-precision variant reads a
       * float array, so a double-sized byte copy would reinterpret and
       * over-read it (#137). Forward order keeps the in-place case correct (#94).
       */
      inIdx = startIdx;
      for( i = 0; i < (int)*outNBElement; i += 1 )
      {
         outReal[i] = inReal[inIdx++];
      }
      return TA_SUCCESS;
   }
   /* Weighted denominator 1+2+...+n = n(n+1)/2. Computed in double: the
    * int product n*(n+1) overflows int32 at n>=46341 (#142).
    */
   divider = (double)optInTimePeriod * (optInTimePeriod + 1) / 2.0;
   /* The algo used here use a very basic property of
    * multiplication/addition: (x*2) = x+x
    *
    * As an example, a 3 period weighted can be
    * interpreted in two way:
    *  (x1*1)+(x2*2)+(x3*3)
    *      OR
    *  x1+x2+x2+x3+x3+x3 (this is the periodSum)
    *
    * When you move forward in the time serie
    * you can quickly adjust the periodSum for the
    * period by substracting:
    *   x1+x2+x3 (This is the periodSub)
    * Making the new periodSum equals to:
    *   x2+x3+x3
    *
    * You can then add the new price bar
    * which is x4+x4+x4 giving:
    *   x2+x3+x3+x4+x4+x4
    *
    * At this point one iteration is completed and you can
    * see that we are back to the step 1 of this example.
    *
    * Why making it so un-intuitive? The number of memory
    * access and floating point operations are kept to a
    * minimum with this algo.
    */
   outIdx = 0;
   trailingIdx = startIdx - lookbackTotal;
   /* Evaluate the initial periodSum/periodSub and trailingValue. */
   lookbackWin = optInTimePeriod - 1;
   periodSub = (double)0.0;
   periodSum = periodSub;
   inIdx = trailingIdx;
   i = 1;
   while( inIdx < startIdx )
   {
      tempReal = inReal[inIdx];
      inIdx += 1;
      periodSub += tempReal;
      periodSum += tempReal * i;
      i += 1;
   }
   barsSinceReseed = 8 * optInTimePeriod;
   trailingValue = 0.0;
   /* Tight loop for the requested range. */
   while( inIdx <= endIdx )
   {
      /* Add the current price bar to the sum
       * who are carried through the iterations.
       */
      tempReal = inReal[inIdx];
      periodSub += tempReal;
      periodSub -= trailingValue;
      periodSum += tempReal * optInTimePeriod;
      /* Re-anchor: rebuild both totals from the window itself.
       *
       * periodSum and periodSub were running totals that were never
       * recomputed, so each bar's rounding joined a residue no later bar
       * could subtract, and its size was set by the largest value the totals
       * had ever held rather than by the current window. That is the defect
       * #254 fixed in the LINEARREG family, and `periodSum -= periodSub`
       * below is the same weight-shifting identity as that family's
       * `SumXY = SumXY + SumY - period*trailingValue` -- which is why WMA has
       * it and TA_SMA, whose output lives at its own sum's scale, does not.
       * Measured before the fix: worst range disagreement 1.41e-08 at 200000
       * bars against a 1e-10 tier, over the tier from ~10000 bars on ordinary
       * closes or ~1000 with one large print. After: 1.79e-12, flat in call
       * length.
       *
       * ONE TRIGGER, NOT TWO, AND THE INTERVAL IS 8*period NOT 32. The
       * LINEARREG family also carries an OUTLIER trigger (rebuild when the
       * departing value outweighs the window) because for a slope the
       * interval alone FAILS the tier outright, at 2.38e-10. WMA is not in
       * that position: its weights are bounded by `period` and its divider is
       * period*(period+1)/2, which dilutes the residue enough that the
       * interval alone holds. Swept over periods 2, 3, 4, 14, 50, 200, 1000,
       * 5000 and 20000 on 60000 bars, clean and with a 1000x print, the worst
       * is 2.2e-11 -- 4.6x inside the band, and the margin does not thin at
       * either end of the period range. Measured, the trigger bought 1.4e-11 -> 7e-12 and cost 1.17x
       * here and 1.65x in TA_HMA, whose three fused stages each pay it. The
       * shorter interval buys most of the accuracy for ~1.1x instead.
       *
       * The rebuild walks the window OLDEST FIRST with the weight counting UP
       * from 1 -- the priming scan's own order and weighting -- so a
       * re-anchored bar is bit-identical to the same bar computed by a call
       * that started there. That identity is what the range-stability
       * contract measures, and what test_wma.c W2/W3 assert.
       *
       * The loop start is written INLINE rather than through a `windowStart`
       * local: only that form is recognised as a rescan window, which is what
       * keeps this on the stream classifier's primary path. See
       * docs/ta_codegen_input_code.md.
       *
       * Reading the window is safe when outReal aliases inReal: the outputs
       * written so far occupy [0, outIdx-1], and the window starts at
       * startIdx-lookbackTotal+outIdx, which is >= outIdx.
       */
      barsSinceReseed -= 1;
      if( barsSinceReseed <= 0 )
      {
         barsSinceReseed = 8 * optInTimePeriod;
         periodSub = (double)0.0;
         periodSum = (double)0.0;
         rw = 1;
         for( j = inIdx - lookbackWin; j <= inIdx; j += 1 )
         {
            tempReal = inReal[j];
            periodSub += tempReal;
            periodSum += tempReal * rw;
            rw += 1;
         }
      }
      /* Save the trailing value for being substract at
       * the next iteration.
       * (must be saved here just in case outReal and
       *  inReal are the same buffer).
       */
      trailingValue = inReal[trailingIdx];
      trailingIdx += 1;
      /* Calculate the WMA for this price bar. */
      outReal[outIdx++] = periodSum / divider;
      /* Prepare the periodSum for the next iteration. */
      periodSum -= periodSub;
      inIdx += 1;
   }
   /* Set output limits. */
   *outNBElement= outIdx;
   *outBegIdx= startIdx;
   return TA_SUCCESS;
}

TA_RetCode TA_S_WMA( int    startIdx,
                     int    endIdx,
                     const float inReal[],
                     int optInTimePeriod,
                     int          *outBegIdx,
                     int          *outNBElement,
                     double        outReal[] )
{
   int inIdx;
   int outIdx;
   int i;
   int trailingIdx;
   int j;
   int rw;
   int lookbackWin;
   int barsSinceReseed;
   double periodSum;
   double periodSub;
   double tempReal;
   double trailingValue;
   double divider;
   int lookbackTotal;

   if( (startIdx < 0) || (startIdx > TA_MAX_INDEX) )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx > TA_MAX_INDEX) || (endIdx < startIdx) )
      return TA_OUT_OF_RANGE_END_INDEX;

   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 30;
   else if( (int)optInTimePeriod < 1 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( !inReal )
      return TA_BAD_PARAM;
   if( !outBegIdx || !outNBElement )
      return TA_BAD_PARAM;
   if( !outReal )
      return TA_BAD_PARAM;

   lookbackTotal = optInTimePeriod - 1;
   if( startIdx < lookbackTotal )
   {
      startIdx = lookbackTotal;
   }
   if( startIdx > endIdx )
   {
      *outBegIdx= 0;
      *outNBElement= 0;
      return TA_SUCCESS;
   }
   if( optInTimePeriod == 1 )
   {
      *outBegIdx= startIdx;
      *outNBElement= endIdx - startIdx + 1;
      inIdx = startIdx;
      for( i = 0; i < (int)*outNBElement; i += 1 )
      {
         outReal[i] = (double)inReal[inIdx++];
      }
      return TA_SUCCESS;
   }
   divider = (double)optInTimePeriod * (optInTimePeriod + 1) / 2.0;
   outIdx = 0;
   trailingIdx = startIdx - lookbackTotal;
   lookbackWin = optInTimePeriod - 1;
   periodSub = (double)0.0;
   periodSum = periodSub;
   inIdx = trailingIdx;
   i = 1;
   while( inIdx < startIdx )
   {
      tempReal = (double)inReal[inIdx];
      inIdx += 1;
      periodSub += tempReal;
      periodSum += tempReal * i;
      i += 1;
   }
   barsSinceReseed = 8 * optInTimePeriod;
   trailingValue = 0.0;
   while( inIdx <= endIdx )
   {
      tempReal = (double)inReal[inIdx];
      periodSub += tempReal;
      periodSub -= trailingValue;
      periodSum += tempReal * optInTimePeriod;
      barsSinceReseed -= 1;
      if( barsSinceReseed <= 0 )
      {
         barsSinceReseed = 8 * optInTimePeriod;
         periodSub = (double)0.0;
         periodSum = (double)0.0;
         rw = 1;
         for( j = inIdx - lookbackWin; j <= inIdx; j += 1 )
         {
            tempReal = (double)inReal[j];
            periodSub += tempReal;
            periodSum += tempReal * rw;
            rw += 1;
         }
      }
      trailingValue = (double)inReal[trailingIdx];
      trailingIdx += 1;
      outReal[outIdx++] = periodSum / divider;
      periodSum -= periodSub;
      inIdx += 1;
   }
   *outNBElement= outIdx;
   *outBegIdx= startIdx;
   return TA_SUCCESS;
}

/**** Streaming API *****/

struct TA_WMA_Stream {
   /* The bars this handle has an output for (see TA_StreamOutRange).
    * Kept first, and in this order, in every stream struct. */
   int outRangeBegIdx;
   int outRangeCount;
   /* The value(s) at the last bar the stream counted (see TA_WMA_Value). */
   double cur_outReal;
   int optInTimePeriod;
   int lookbackWin;
   int barsSinceReseed;
   double periodSum;
   double periodSub;
   double trailingValue;
   double divider;
   int ringPos_trailingIdx;
   int ringCap_trailingIdx;
   double *ring_trailingIdx_inReal;
   int winPos_j;
   int winCap_j;
   double *win_j_inReal;
};

/* Private function, not in public API. */
static void TA_WMA_ReleaseImpl( struct TA_WMA_Stream *sp )
{
   if( !sp ) return;
   if( sp->ring_trailingIdx_inReal ) TA_Free( sp->ring_trailingIdx_inReal );
   if( sp->win_j_inReal ) TA_Free( sp->win_j_inReal );
   TA_Free( sp );
}

/* Private function, not in public API. */
static void TA_WMA_StepImpl( struct TA_WMA_Stream *sp, double inReal, double *outReal )
{
   int j;
   int rw;
   double tempReal;
   double periodSum;
   double periodSub;

   periodSum = sp->periodSum;
   periodSub = sp->periodSub;
   if( sp->optInTimePeriod == 1 )
   {
      *outReal= inReal;
      sp->cur_outReal = *outReal;
      sp->periodSum = periodSum;
      sp->periodSub = periodSub;
      return;
   }
   if( sp->ringCap_trailingIdx == 0 )
   {
      sp->ring_trailingIdx_inReal[0] = inReal;
   }
   sp->win_j_inReal[sp->winPos_j] = inReal;
   /* Add the current price bar to the sum
    * who are carried through the iterations.
    */
   tempReal = inReal;
   periodSub += tempReal;
   periodSub -= sp->trailingValue;
   periodSum += tempReal * sp->optInTimePeriod;
   /* Re-anchor: rebuild both totals from the window itself.
    *
    * periodSum and periodSub were running totals that were never
    * recomputed, so each bar's rounding joined a residue no later bar
    * could subtract, and its size was set by the largest value the totals
    * had ever held rather than by the current window. That is the defect
    * #254 fixed in the LINEARREG family, and `periodSum -= periodSub`
    * below is the same weight-shifting identity as that family's
    * `SumXY = SumXY + SumY - period*trailingValue` -- which is why WMA has
    * it and TA_SMA, whose output lives at its own sum's scale, does not.
    * Measured before the fix: worst range disagreement 1.41e-08 at 200000
    * bars against a 1e-10 tier, over the tier from ~10000 bars on ordinary
    * closes or ~1000 with one large print. After: 1.79e-12, flat in call
    * length.
    *
    * ONE TRIGGER, NOT TWO, AND THE INTERVAL IS 8*period NOT 32. The
    * LINEARREG family also carries an OUTLIER trigger (rebuild when the
    * departing value outweighs the window) because for a slope the
    * interval alone FAILS the tier outright, at 2.38e-10. WMA is not in
    * that position: its weights are bounded by `period` and its divider is
    * period*(period+1)/2, which dilutes the residue enough that the
    * interval alone holds. Swept over periods 2, 3, 4, 14, 50, 200, 1000,
    * 5000 and 20000 on 60000 bars, clean and with a 1000x print, the worst
    * is 2.2e-11 -- 4.6x inside the band, and the margin does not thin at
    * either end of the period range. Measured, the trigger bought 1.4e-11 -> 7e-12 and cost 1.17x
    * here and 1.65x in TA_HMA, whose three fused stages each pay it. The
    * shorter interval buys most of the accuracy for ~1.1x instead.
    *
    * The rebuild walks the window OLDEST FIRST with the weight counting UP
    * from 1 -- the priming scan's own order and weighting -- so a
    * re-anchored bar is bit-identical to the same bar computed by a call
    * that started there. That identity is what the range-stability
    * contract measures, and what test_wma.c W2/W3 assert.
    *
    * The loop start is written INLINE rather than through a `windowStart`
    * local: only that form is recognised as a rescan window, which is what
    * keeps this on the stream classifier's primary path. See
    * docs/ta_codegen_input_code.md.
    *
    * Reading the window is safe when outReal aliases inReal: the outputs
    * written so far occupy [0, outIdx-1], and the window starts at
    * startIdx-lookbackTotal+outIdx, which is >= outIdx.
    */
   sp->barsSinceReseed -= 1;
   if( sp->barsSinceReseed <= 0 )
   {
      sp->barsSinceReseed = 8 * sp->optInTimePeriod;
      periodSub = (double)0.0;
      periodSum = (double)0.0;
      rw = 1;
      for( j = sp->lookbackWin; j >= 0; j -= 1 )
      {
         tempReal = sp->win_j_inReal[(sp->winPos_j + sp->winCap_j - j >= sp->winCap_j) ? sp->winPos_j + sp->winCap_j - j - sp->winCap_j : sp->winPos_j + sp->winCap_j - j];
         periodSub += tempReal;
         periodSum += tempReal * rw;
         rw += 1;
      }
   }
   /* Save the trailing value for being substract at
    * the next iteration.
    * (must be saved here just in case outReal and
    *  inReal are the same buffer).
    */
   sp->trailingValue = sp->ring_trailingIdx_inReal[sp->ringPos_trailingIdx];
   /* Calculate the WMA for this price bar. */
   *outReal= periodSum / sp->divider;
   /* Prepare the periodSum for the next iteration. */
   periodSum -= periodSub;
   sp->cur_outReal = *outReal;
   sp->ring_trailingIdx_inReal[sp->ringPos_trailingIdx] = inReal;
   sp->ringPos_trailingIdx = sp->ringPos_trailingIdx + 1;
   if( sp->ringPos_trailingIdx >= sp->ringCap_trailingIdx )
   {
      sp->ringPos_trailingIdx = 0;
   }
   sp->winPos_j = sp->winPos_j + 1;
   if( sp->winPos_j >= sp->winCap_j )
   {
      sp->winPos_j = 0;
   }
   sp->periodSum = periodSum;
   sp->periodSub = periodSub;
}

static TA_RetCode TA_WMA_OpenImpl( struct TA_WMA_Stream **stream, const double inReal[], int startIdx, int historyLen, int optInTimePeriod, int *outBegIdx, int *outNBElement, double outReal[], int outStride )
{
   struct TA_WMA_Stream *sp;
   int endIdx;
   int dummyBegIdx;
   int dummyNBElement;

   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inReal || !outReal ) return TA_BAD_PARAM;
   if( (int)optInTimePeriod == TA_INTEGER_DEFAULT )
      optInTimePeriod = 30;
   else if( (int)optInTimePeriod < 1 || (int)optInTimePeriod > 100000 )
      return TA_BAD_PARAM;
   if( startIdx > historyLen - 1 )
   {
      *outBegIdx = 0;
      *outNBElement = 0;
      return TA_INSUFFICIENT_HISTORY;
   }

   endIdx = historyLen - 1;
   dummyBegIdx = 0;
   dummyNBElement = 0;
   (void)startIdx; (void)dummyBegIdx; (void)dummyNBElement;

   if( optInTimePeriod == 1 )
   {
      int fillLb = TA_WMA_Lookback( optInTimePeriod );
      if( startIdx > fillLb ) fillLb = startIdx;
      if( historyLen < fillLb + 1 ) return TA_INSUFFICIENT_HISTORY;
      sp = (struct TA_WMA_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) { return TA_ALLOC_ERR; }
      memset( sp, 0, sizeof(*sp) );
      sp->optInTimePeriod = optInTimePeriod;
      sp->ringCap_trailingIdx = 0;
      { size_t allocN = (size_t)(sp->ringCap_trailingIdx > 0 ? sp->ringCap_trailingIdx : 1);
        sp->ring_trailingIdx_inReal = (double *)TA_Malloc( sizeof(double) * allocN );
        if( !sp->ring_trailingIdx_inReal ) { TA_WMA_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
        memset( sp->ring_trailingIdx_inReal, 0, sizeof(double) * allocN );
      }
      sp->ringPos_trailingIdx = 0;
      sp->winCap_j = 1;
      if( sp->winCap_j < 1 || sp->winCap_j > historyLen ) { TA_WMA_ReleaseImpl( sp ); return TA_INTERNAL_ERROR(401); }
      sp->win_j_inReal = (double *)TA_Malloc( sizeof(double) * (size_t)sp->winCap_j );
      if( !sp->win_j_inReal ) { TA_WMA_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
      sp->win_j_inReal[0] = 0.0;
      sp->winPos_j = 0;
      {
         int fillIdx;
         *outBegIdx = fillLb;
         *outNBElement = historyLen - fillLb;
         if( outStride )
         {
            for( fillIdx = 0; fillIdx < historyLen - fillLb; fillIdx++ )
            {
               outReal[fillIdx] = inReal[fillLb + fillIdx];
            }
         }
         else
         {
            outReal[0] = inReal[historyLen - 1];
         }
      }
      sp->outRangeBegIdx = *outBegIdx;
      sp->outRangeCount = *outNBElement;
      sp->cur_outReal = outReal[(*outNBElement - 1) * outStride];
      *stream = sp;
      return TA_SUCCESS;
   }

   {
      int inIdx;
      int outIdx;
      int i;
      int trailingIdx;
      int j;
      int rw;
      int lookbackWin = 0;
      int barsSinceReseed = 0;
      double periodSum = 0.0;
      double periodSub = 0.0;
      double tempReal;
      double trailingValue = 0.0;
      double divider = 0.0;
      int lookbackTotal;
      lookbackTotal = optInTimePeriod - 1;
      /* Move up the start index if there is not
       * enough initial data.
       */
      if( startIdx < lookbackTotal )
      {
         startIdx = lookbackTotal;
      }
      /* Make sure there is still something to evaluate. */
      if( startIdx > endIdx )
      {
         *outBegIdx= 0;
         *outNBElement= 0;
         return TA_INSUFFICIENT_HISTORY;
      }
      /* Weighted denominator 1+2+...+n = n(n+1)/2. Computed in double: the
       * int product n*(n+1) overflows int32 at n>=46341 (#142).
       */
      divider = (double)optInTimePeriod * (optInTimePeriod + 1) / 2.0;
      /* The algo used here use a very basic property of
       * multiplication/addition: (x*2) = x+x
       *
       * As an example, a 3 period weighted can be
       * interpreted in two way:
       *  (x1*1)+(x2*2)+(x3*3)
       *      OR
       *  x1+x2+x2+x3+x3+x3 (this is the periodSum)
       *
       * When you move forward in the time serie
       * you can quickly adjust the periodSum for the
       * period by substracting:
       *   x1+x2+x3 (This is the periodSub)
       * Making the new periodSum equals to:
       *   x2+x3+x3
       *
       * You can then add the new price bar
       * which is x4+x4+x4 giving:
       *   x2+x3+x3+x4+x4+x4
       *
       * At this point one iteration is completed and you can
       * see that we are back to the step 1 of this example.
       *
       * Why making it so un-intuitive? The number of memory
       * access and floating point operations are kept to a
       * minimum with this algo.
       */
      outIdx = 0;
      trailingIdx = startIdx - lookbackTotal;
      /* Evaluate the initial periodSum/periodSub and trailingValue. */
      lookbackWin = optInTimePeriod - 1;
      periodSub = (double)0.0;
      periodSum = periodSub;
      inIdx = trailingIdx;
      i = 1;
      while( inIdx < startIdx )
      {
         tempReal = inReal[inIdx];
         inIdx += 1;
         periodSub += tempReal;
         periodSum += tempReal * i;
         i += 1;
      }
      barsSinceReseed = 8 * optInTimePeriod;
      trailingValue = 0.0;
      /* Tight loop for the requested range. */
      while( inIdx <= endIdx )
      {
         /* Add the current price bar to the sum
          * who are carried through the iterations.
          */
         tempReal = inReal[inIdx];
         periodSub += tempReal;
         periodSub -= trailingValue;
         periodSum += tempReal * optInTimePeriod;
         /* Re-anchor: rebuild both totals from the window itself.
          *
          * periodSum and periodSub were running totals that were never
          * recomputed, so each bar's rounding joined a residue no later bar
          * could subtract, and its size was set by the largest value the totals
          * had ever held rather than by the current window. That is the defect
          * #254 fixed in the LINEARREG family, and `periodSum -= periodSub`
          * below is the same weight-shifting identity as that family's
          * `SumXY = SumXY + SumY - period*trailingValue` -- which is why WMA has
          * it and TA_SMA, whose output lives at its own sum's scale, does not.
          * Measured before the fix: worst range disagreement 1.41e-08 at 200000
          * bars against a 1e-10 tier, over the tier from ~10000 bars on ordinary
          * closes or ~1000 with one large print. After: 1.79e-12, flat in call
          * length.
          *
          * ONE TRIGGER, NOT TWO, AND THE INTERVAL IS 8*period NOT 32. The
          * LINEARREG family also carries an OUTLIER trigger (rebuild when the
          * departing value outweighs the window) because for a slope the
          * interval alone FAILS the tier outright, at 2.38e-10. WMA is not in
          * that position: its weights are bounded by `period` and its divider is
          * period*(period+1)/2, which dilutes the residue enough that the
          * interval alone holds. Swept over periods 2, 3, 4, 14, 50, 200, 1000,
          * 5000 and 20000 on 60000 bars, clean and with a 1000x print, the worst
          * is 2.2e-11 -- 4.6x inside the band, and the margin does not thin at
          * either end of the period range. Measured, the trigger bought 1.4e-11 -> 7e-12 and cost 1.17x
          * here and 1.65x in TA_HMA, whose three fused stages each pay it. The
          * shorter interval buys most of the accuracy for ~1.1x instead.
          *
          * The rebuild walks the window OLDEST FIRST with the weight counting UP
          * from 1 -- the priming scan's own order and weighting -- so a
          * re-anchored bar is bit-identical to the same bar computed by a call
          * that started there. That identity is what the range-stability
          * contract measures, and what test_wma.c W2/W3 assert.
          *
          * The loop start is written INLINE rather than through a `windowStart`
          * local: only that form is recognised as a rescan window, which is what
          * keeps this on the stream classifier's primary path. See
          * docs/ta_codegen_input_code.md.
          *
          * Reading the window is safe when outReal aliases inReal: the outputs
          * written so far occupy [0, outIdx-1], and the window starts at
          * startIdx-lookbackTotal+outIdx, which is >= outIdx.
          */
         barsSinceReseed -= 1;
         if( barsSinceReseed <= 0 )
         {
            barsSinceReseed = 8 * optInTimePeriod;
            periodSub = (double)0.0;
            periodSum = (double)0.0;
            rw = 1;
            for( j = inIdx - lookbackWin; j <= inIdx; j += 1 )
            {
               tempReal = inReal[j];
               periodSub += tempReal;
               periodSum += tempReal * rw;
               rw += 1;
            }
         }
         /* Save the trailing value for being substract at
          * the next iteration.
          * (must be saved here just in case outReal and
          *  inReal are the same buffer).
          */
         trailingValue = inReal[trailingIdx];
         trailingIdx += 1;
         /* Calculate the WMA for this price bar. */
         outReal[outIdx++ * outStride] = periodSum / divider;
         /* Prepare the periodSum for the next iteration. */
         periodSum -= periodSub;
         inIdx += 1;
      }
      /* Set output limits. */
      *outNBElement= outIdx;
      *outBegIdx= startIdx;

      /* Capture the live batch state into the handle. */
      sp = (struct TA_WMA_Stream *)TA_Malloc( sizeof(*sp) );
      if( !sp ) { return TA_ALLOC_ERR; }
      memset( sp, 0, sizeof(*sp) );
      sp->optInTimePeriod = optInTimePeriod;
      sp->lookbackWin = lookbackWin;
      sp->barsSinceReseed = barsSinceReseed;
      sp->periodSum = periodSum;
      sp->periodSub = periodSub;
      sp->trailingValue = trailingValue;
      sp->divider = divider;
      sp->ringCap_trailingIdx = (int)(inIdx - trailingIdx);
      if( sp->ringCap_trailingIdx < 0 || sp->ringCap_trailingIdx > historyLen ) { TA_WMA_ReleaseImpl( sp ); return TA_INTERNAL_ERROR(402); }
      { size_t allocN = (size_t)(sp->ringCap_trailingIdx > 0 ? sp->ringCap_trailingIdx : 1);
        sp->ring_trailingIdx_inReal = (double *)TA_Malloc( sizeof(double) * allocN );
        if( !sp->ring_trailingIdx_inReal ) { TA_WMA_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
        memcpy( sp->ring_trailingIdx_inReal, inReal + (historyLen - sp->ringCap_trailingIdx), sizeof(double) * (size_t)sp->ringCap_trailingIdx );
      }
      sp->ringPos_trailingIdx = 0;
      sp->winCap_j = (int)(lookbackWin + 1);
      if( sp->winCap_j < 1 || sp->winCap_j > historyLen ) { TA_WMA_ReleaseImpl( sp ); return TA_INTERNAL_ERROR(401); }
      sp->win_j_inReal = (double *)TA_Malloc( sizeof(double) * (size_t)sp->winCap_j );
      if( !sp->win_j_inReal ) { TA_WMA_ReleaseImpl( sp ); return TA_ALLOC_ERR; }
      memcpy( sp->win_j_inReal, inReal + (historyLen - sp->winCap_j), sizeof(double) * (size_t)sp->winCap_j );
      sp->winPos_j = 0;
      sp->outRangeBegIdx = *outBegIdx;
      sp->outRangeCount = *outNBElement;
      sp->cur_outReal = outReal[(*outNBElement - 1) * outStride];
      *stream = sp;
      return TA_SUCCESS;
   }
}

/* Private function, not in public API. */
TA_RetCode TA_WMA_OpenInternal( struct TA_WMA_Stream **stream, const double inReal[], int startIdx, int historyLen, int optInTimePeriod, double *outReal )
{
   TA_RetCode retCode;
   int dummyBegIdx = 0;
   int dummyNBElement = 0;
   double sink_outReal = 0.0;
   retCode = TA_WMA_OpenImpl( stream, inReal, startIdx, historyLen, optInTimePeriod, &dummyBegIdx, &dummyNBElement, &sink_outReal, 0 );
   if( retCode == TA_SUCCESS )
   {
      *outReal = sink_outReal;
   }
   return retCode;
}

TA_LIB_API TA_RetCode TA_WMA_Open( TA_WMA_Stream **stream, const double inReal[], int historyLen, int optInTimePeriod, double *outReal )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inReal || !outReal ) return TA_BAD_PARAM;
   return TA_WMA_OpenInternal( stream, inReal, 0, historyLen, optInTimePeriod, outReal );
}

TA_LIB_API TA_RetCode TA_WMA_OpenAndFill( TA_WMA_Stream **stream, const double inReal[], int historyLen, int optInTimePeriod, int *outBegIdx, int *outNBElement, double outReal[] )
{
   if( !stream ) return TA_BAD_PARAM;
   *stream = NULL;
   if( historyLen < 1 ) return TA_OUT_OF_RANGE_START_INDEX;
   if( historyLen > TA_MAX_INDEX + 1 ) return TA_OUT_OF_RANGE_END_INDEX;
   if( !inReal || !outBegIdx || !outNBElement || !outReal ) return TA_BAD_PARAM;
   if( (const void *)outReal == (const void *)inReal ) return TA_BAD_PARAM;
   return TA_WMA_OpenAndFillInternal( stream, inReal, 0, historyLen, optInTimePeriod, outBegIdx, outNBElement, outReal );
}

/* Private function, not in public API. */
TA_RetCode TA_WMA_OpenAndFillInternal( struct TA_WMA_Stream **stream, const double inReal[], int startIdx, int historyLen, int optInTimePeriod, int *outBegIdx, int *outNBElement, double outReal[] )
{
   return TA_WMA_OpenImpl( stream, inReal, startIdx, historyLen, optInTimePeriod, outBegIdx, outNBElement, outReal, 1 );
}

TA_LIB_API TA_RetCode TA_WMA_Update( TA_WMA_Stream *stream, double inReal, double *outReal )
{
   if( !stream || !outReal ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inReal ) )
   {
      if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
      return TA_BAD_PARAM;
   }
   TA_WMA_StepImpl( stream, inReal, outReal );
   if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_WMA_Peek( const TA_WMA_Stream *stream, double inReal, double *outReal )
{
   const struct TA_WMA_Stream *sp = stream;
   int j;
   int rw;
   double tempReal;
   int barsSinceReseed;
   double periodSum;
   double *win_j_inReal;
   int pkSlot1 = -1;
   double pkVal1 = 0.0;

   if( !stream || !outReal ) return TA_BAD_PARAM;
   if( !TA_IS_FINITE( inReal ) ) return TA_BAD_PARAM;
   barsSinceReseed = sp->barsSinceReseed;
   periodSum = sp->periodSum;
   win_j_inReal = sp->win_j_inReal;
   if( sp->optInTimePeriod == 1 )
   {
      *outReal= inReal;
      return TA_SUCCESS;
   }
   pkSlot1 = sp->winPos_j;
   pkVal1 = inReal;
   /* Add the current price bar to the sum
    * who are carried through the iterations.
    */
   tempReal = inReal;
   periodSum += tempReal * sp->optInTimePeriod;
   /* Re-anchor: rebuild both totals from the window itself.
    *
    * periodSum and periodSub were running totals that were never
    * recomputed, so each bar's rounding joined a residue no later bar
    * could subtract, and its size was set by the largest value the totals
    * had ever held rather than by the current window. That is the defect
    * #254 fixed in the LINEARREG family, and `periodSum -= periodSub`
    * below is the same weight-shifting identity as that family's
    * `SumXY = SumXY + SumY - period*trailingValue` -- which is why WMA has
    * it and TA_SMA, whose output lives at its own sum's scale, does not.
    * Measured before the fix: worst range disagreement 1.41e-08 at 200000
    * bars against a 1e-10 tier, over the tier from ~10000 bars on ordinary
    * closes or ~1000 with one large print. After: 1.79e-12, flat in call
    * length.
    *
    * ONE TRIGGER, NOT TWO, AND THE INTERVAL IS 8*period NOT 32. The
    * LINEARREG family also carries an OUTLIER trigger (rebuild when the
    * departing value outweighs the window) because for a slope the
    * interval alone FAILS the tier outright, at 2.38e-10. WMA is not in
    * that position: its weights are bounded by `period` and its divider is
    * period*(period+1)/2, which dilutes the residue enough that the
    * interval alone holds. Swept over periods 2, 3, 4, 14, 50, 200, 1000,
    * 5000 and 20000 on 60000 bars, clean and with a 1000x print, the worst
    * is 2.2e-11 -- 4.6x inside the band, and the margin does not thin at
    * either end of the period range. Measured, the trigger bought 1.4e-11 -> 7e-12 and cost 1.17x
    * here and 1.65x in TA_HMA, whose three fused stages each pay it. The
    * shorter interval buys most of the accuracy for ~1.1x instead.
    *
    * The rebuild walks the window OLDEST FIRST with the weight counting UP
    * from 1 -- the priming scan's own order and weighting -- so a
    * re-anchored bar is bit-identical to the same bar computed by a call
    * that started there. That identity is what the range-stability
    * contract measures, and what test_wma.c W2/W3 assert.
    *
    * The loop start is written INLINE rather than through a `windowStart`
    * local: only that form is recognised as a rescan window, which is what
    * keeps this on the stream classifier's primary path. See
    * docs/ta_codegen_input_code.md.
    *
    * Reading the window is safe when outReal aliases inReal: the outputs
    * written so far occupy [0, outIdx-1], and the window starts at
    * startIdx-lookbackTotal+outIdx, which is >= outIdx.
    */
   barsSinceReseed -= 1;
   if( barsSinceReseed <= 0 )
   {
      barsSinceReseed = 8 * sp->optInTimePeriod;
      periodSum = (double)0.0;
      rw = 1;
      for( j = sp->lookbackWin; j >= 0; j -= 1 )
      {
         tempReal = (((sp->winPos_j + sp->winCap_j - j >= sp->winCap_j) ? sp->winPos_j + sp->winCap_j - j - sp->winCap_j : sp->winPos_j + sp->winCap_j - j) != pkSlot1) ? win_j_inReal[(sp->winPos_j + sp->winCap_j - j >= sp->winCap_j) ? sp->winPos_j + sp->winCap_j - j - sp->winCap_j : sp->winPos_j + sp->winCap_j - j] : pkVal1;
         periodSum += tempReal * rw;
         rw += 1;
      }
   }
   /* Calculate the WMA for this price bar. */
   *outReal= periodSum / sp->divider;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_WMA_UpdateAndFill( TA_WMA_Stream *stream, const double inReal[], int barCount, double outReal[] )
{
   int i;

   if( !stream || !inReal || !outReal ) return TA_BAD_PARAM;
   if( barCount < 0 ) return TA_BAD_PARAM;
   if( (const void *)outReal == (const void *)inReal ) return TA_BAD_PARAM;
   for( i = 0; i < barCount; i++ )
   {
      if( !TA_IS_FINITE( inReal[i] ) )
      {
         if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
         return TA_BAD_PARAM;
      }
      TA_WMA_StepImpl( stream, inReal[i], &outReal[i] );
      if( stream->outRangeCount < TA_MAX_INDEX ) stream->outRangeCount++;
   }
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_WMA_Close( TA_WMA_Stream *stream )
{
   TA_WMA_ReleaseImpl( stream );
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_WMA_Value( const TA_WMA_Stream *stream, double *outReal )
{
   if( !stream || !outReal ) return TA_BAD_PARAM;
   *outReal = stream->cur_outReal;
   return TA_SUCCESS;
}

TA_LIB_API TA_RetCode TA_WMA_Clone( const TA_WMA_Stream *stream, TA_WMA_Stream **clone )
{
   struct TA_WMA_Stream *sp;

   if( !clone ) return TA_BAD_PARAM;
   *clone = NULL;
   if( !stream ) return TA_BAD_PARAM;
   sp = (struct TA_WMA_Stream *)TA_Malloc( sizeof(*sp) );
   if( !sp ) return TA_ALLOC_ERR;
   *sp = *stream;
   sp->ring_trailingIdx_inReal = NULL;
   sp->win_j_inReal = NULL;
   if( stream->ring_trailingIdx_inReal )
   { size_t copyN = (size_t)(sp->ringCap_trailingIdx > 0 ? sp->ringCap_trailingIdx : 1);
     sp->ring_trailingIdx_inReal = (double *)TA_Malloc( sizeof(double) * copyN );
     if( !sp->ring_trailingIdx_inReal ) { TA_WMA_Close( sp ); return TA_ALLOC_ERR; }
     memcpy( sp->ring_trailingIdx_inReal, stream->ring_trailingIdx_inReal, sizeof(double) * copyN ); }
   if( stream->win_j_inReal )
   { size_t copyN = (size_t)(sp->winCap_j);
     sp->win_j_inReal = (double *)TA_Malloc( sizeof(double) * copyN );
     if( !sp->win_j_inReal ) { TA_WMA_Close( sp ); return TA_ALLOC_ERR; }
     memcpy( sp->win_j_inReal, stream->win_j_inReal, sizeof(double) * copyN ); }
   *clone = sp;
   return TA_SUCCESS;
}

