/* TA-LIB Copyright (c) 1999-2003, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  MF       Mario Fortier
 *
 *
 * Change history:
 *
 *  MMDDYY BY   Description
 *  -------------------------------------------------------------------
 *  112400 MF   Template creation.
 *
 */
#include "ta_memory.h"

/**** START GENCODE SECTION 1 - DO NOT DELETE THIS LINE ****/
/* All code within this section is automatically
 * generated by gen_code. Any modification will be lost
 * next time gen_code is run.
 */

#ifndef TA_FUNC_H
   #include "ta_func.h"
#endif

#ifndef TA_UTILITY_H
   #include "ta_utility.h"
#endif

int TA_PPO_Lookback( int           optInFastPeriod_0, /* From 2 to TA_INTEGER_MAX */
                     int           optInSlowPeriod_1, /* From 2 to TA_INTEGER_MAX */
                     TA_MAType     optInMAType_2 ) 
/**** END GENCODE SECTION 1 - DO NOT DELETE THIS LINE ****/
{
   /* insert lookback code here. */
   (void)optInFastPeriod_0;

   /* Lookback is driven by the slow MA. */
   return TA_MA_Lookback( optInSlowPeriod_1, optInMAType_2 );
}

/**** START GENCODE SECTION 2 - DO NOT DELETE THIS LINE ****/
/*
 * TA_PPO - Percentage Price Oscillator
 * 
 * Input  = double
 * Output = double
 * 
 * Optional Parameters
 * -------------------
 * optInFastPeriod_0:(From 2 to TA_INTEGER_MAX)
 *    Number of period for the fast MA
 * 
 * optInSlowPeriod_1:(From 2 to TA_INTEGER_MAX)
 *    Number of period for the slow MA
 * 
 * optInMAType_2:
 *    Type of Moving Average
 * 
 * 
 */

TA_RetCode TA_PPO( int    startIdx,
                   int    endIdx,
                   const double inReal_0[],
                   int           optInFastPeriod_0, /* From 2 to TA_INTEGER_MAX */
                   int           optInSlowPeriod_1, /* From 2 to TA_INTEGER_MAX */
                   TA_MAType     optInMAType_2,
                   int          *outBegIdx,
                   int          *outNbElement,
                   double        outReal_0[] )
/**** END GENCODE SECTION 2 - DO NOT DELETE THIS LINE ****/
{
   /* Insert local variables here. */
   double *tempBuffer;
   TA_RetCode retCode;

/**** START GENCODE SECTION 3 - DO NOT DELETE THIS LINE ****/

#ifndef TA_FUNC_NO_RANGE_CHECK

   /* Validate the requested output range. */
   if( startIdx < 0 )
      return TA_OUT_OF_RANGE_START_INDEX;
   if( (endIdx < 0) || (endIdx < startIdx))
      return TA_OUT_OF_RANGE_END_INDEX;

   /* Validate the parameters. */
   if( !inReal_0 ) return TA_BAD_PARAM;
   /* min/max are checked for optInFastPeriod_0. */
   if( (int)optInFastPeriod_0 == TA_INTEGER_DEFAULT )
      optInFastPeriod_0 = 12;
   else if( ((int)optInFastPeriod_0 < 2) || ((int)optInFastPeriod_0 > 2147483647) )
      return TA_BAD_PARAM;

   /* min/max are checked for optInSlowPeriod_1. */
   if( (int)optInSlowPeriod_1 == TA_INTEGER_DEFAULT )
      optInSlowPeriod_1 = 26;
   else if( ((int)optInSlowPeriod_1 < 2) || ((int)optInSlowPeriod_1 > 2147483647) )
      return TA_BAD_PARAM;

   if( (int)optInMAType_2 == TA_INTEGER_DEFAULT )
      optInMAType_2 = 0;
   else if( ((int)optInMAType_2 < 0) || ((int)optInMAType_2 > 8) )
      return TA_BAD_PARAM;

   if( outReal_0 == NULL )
      return TA_BAD_PARAM;

#endif /* TA_FUNC_NO_RANGE_CHECK */

/**** END GENCODE SECTION 3 - DO NOT DELETE THIS LINE ****/

   /* Insert TA function code here. */

   /* Allocate an intermediate buffer. */
   tempBuffer = TA_Malloc( (endIdx-startIdx+1) * sizeof(double) );
   if( !tempBuffer )
      return TA_ALLOC_ERR;

   retCode = TA_INT_PO( startIdx, endIdx,                        
                        inReal_0,
                        optInFastPeriod_0, /* From 1 to 200 */
                        optInSlowPeriod_1, /* From 1 to 200 */
                        optInMAType_2,
                        outBegIdx,
                        outNbElement,
                        outReal_0,
                        tempBuffer,
                        1 /* Do percentage processing. */ );

   TA_Free(  tempBuffer );
   
   return TA_SUCCESS;
}

