/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility ta_codegen.
 *  Any modifications will be lost on next execution of ta_codegen.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  MF       Mario Fortier
 *  AA       Andrew Atkinson
 *
 * Change history:
 *
 *  MMDDYY BY   Description
 *  -------------------------------------------------------------------
 *  112400 MF   Template creation.
 *  052603 MF   Adapt code to compile with .NET Managed C++
 *  062804 MF   Resolve div by zero bug on limit case.
 *  020605 AA   Fix #1117666 Lookback & out-of-bound bug.
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::apo`]: the number of leading input values consumed before the
    /// first output value can be produced.
    ///
    /// # Arguments
    ///
    /// * `optInFastPeriod` — Period of the fast moving average (default 12, range 2..=100000)
    /// * `optInSlowPeriod` — Period of the slow moving average (default 26, range 2..=100000)
    /// * `optInMAType` — Moving-average type used for both MAs (default 0 = SMA, values: 0=SMA,
    ///   1=EMA, 2=WMA, 3=DEMA, 4=TEMA, 5=TRIMA, 6=KAMA, 7=MAMA, 8=T3)
    ///
    /// Returns `usize::MAX` when a parameter is out of range. Integer parameters accept `i32::MIN`
    /// to select their default value.
    #[inline]
    pub fn apo_lookback(&self, mut optInFastPeriod: i32, mut optInSlowPeriod: i32, mut optInMAType: i32) -> usize {
        if ((optInFastPeriod) as i32) == (i32::MIN) {
            optInFastPeriod = 12;
        } else if (((optInFastPeriod) as i32) < 2) || (((optInFastPeriod) as i32) > 100000) {
            return usize::MAX;
        }
        if ((optInSlowPeriod) as i32) == (i32::MIN) {
            optInSlowPeriod = 26;
        } else if (((optInSlowPeriod) as i32) < 2) || (((optInSlowPeriod) as i32) > 100000) {
            return usize::MAX;
        }
        // The slow MA is the key factor determining the lookback period.
        return self.ma_lookback((optInSlowPeriod).max(optInFastPeriod), optInMAType);
    }
    /// Absolute Price Oscillator: the difference between a fast and a slow moving average of the
    /// input, in price units. Measures short- vs long-term momentum. Positive when fast MA > slow
    /// MA (upward momentum); negative otherwise.
    ///
    /// # Formula
    ///
    /// ```text
    /// $APO = MA_{fast}(inReal) - MA_{slow}(inReal)$, both MAs of type optInMAType
    /// ```
    ///
    /// # Arguments
    ///
    /// * `startIdx` — Start index of the requested calculation range.
    /// * `endIdx` — End index of the requested calculation range (inclusive).
    /// * `inReal` — Source data series.
    /// * `optInFastPeriod` — Period of the fast moving average (default 12, range 2..=100000)
    /// * `optInSlowPeriod` — Period of the slow moving average (default 26, range 2..=100000)
    /// * `optInMAType` — Moving-average type used for both MAs (default 0 = SMA, values: 0=SMA,
    ///   1=EMA, 2=WMA, 3=DEMA, 4=TEMA, 5=TRIMA, 6=KAMA, 7=MAMA, 8=T3)
    /// * `outBegIdx` — Set to the input index of the first output value.
    /// * `outNBElement` — Set to the number of output values written.
    /// * `outReal` — Fast MA minus slow MA.
    ///
    /// Integer parameters accept `i32::MIN` to select their default value.
    ///
    /// # Errors
    ///
    /// Returns [`RetCode::OutOfRangeStartIndex`] when `endIdx < startIdx`, and
    /// [`RetCode::BadParam`] when an optional parameter is outside its documented range.
    ///
    /// # Panics
    ///
    /// Input slices must cover `startIdx..=endIdx` and output slices must hold the number of values
    /// produced for that range; an undersized slice panics. Sizing every output slice to the input
    /// length is always sufficient.
    ///
    /// # Examples
    ///
    /// ```
    /// use ta_lib::{Core, RetCode};
    ///
    /// let data: Vec<f64> = (0..252).map(|i| 100.0 + 10.0 * (0.1 * i as f64).sin()).collect();
    ///
    /// let core = Core::new();
    /// let mut out_beg = 0;
    /// let mut out_nb = 0;
    /// let mut out = vec![0.0; 252];
    ///
    /// let ret = core.apo(
    ///     0, data.len() - 1, &data, 12, 26, 0,
    ///     &mut out_beg, &mut out_nb, &mut out,
    /// );
    /// assert_eq!(ret, RetCode::Success);
    /// assert!(out_nb > 0);
    /// ```
    ///
    /// # See also
    ///
    /// [`Core::ppo`] · [`Core::macd`] · [`Core::ma`] · [`Core::ema`] · [`Core::sma`]
    ///
    /// Further reading: [ta-lib.org/functions/apo](https://ta-lib.org/functions/apo/)
    #[doc(alias = "AbsolutePriceOscillator")]
    pub fn apo(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        mut optInFastPeriod: i32,
        mut optInSlowPeriod: i32,
        mut optInMAType: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInFastPeriod) as i32) == (i32::MIN) {
            optInFastPeriod = 12;
        } else if (((optInFastPeriod) as i32) < 2) || (((optInFastPeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        if ((optInSlowPeriod) as i32) == (i32::MIN) {
            optInSlowPeriod = 26;
        } else if (((optInSlowPeriod) as i32) < 2) || (((optInSlowPeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        let mut startIdx = startIdx;
        let mut tempBuffer: Vec<f64> = Vec::new();
        let mut retCode: RetCode = RetCode::Success;
        let mut tempInteger: usize = 0_usize;
        let mut outBegIdx1: usize = 0_usize;
        let mut outNbElement1: usize = 0_usize;
        let mut outBegIdx2: usize = 0_usize;
        let mut outNbElement2: usize = 0_usize;
        let mut i: usize = 0_usize;
        let mut j: usize = 0_usize;
        // Allocate an intermediate buffer.
        tempBuffer = vec![0.0_f64; ((endIdx - startIdx + 1) * 1) as usize];
        // Make sure slow is really slower than
        // the fast period! if not, swap...
        if optInSlowPeriod < optInFastPeriod {
            // swap
            tempInteger = (optInSlowPeriod) as usize;
            optInSlowPeriod = optInFastPeriod;
            optInFastPeriod = (tempInteger) as i32;
        }
        // Calculate the fast MA into the tempBuffer.
        retCode = self.ma_unguarded(startIdx, endIdx, inReal, optInFastPeriod, optInMAType, &mut outBegIdx2, &mut outNbElement2, &mut tempBuffer[..]);
        if retCode == RetCode::Success {
            // Calculate the slow MA into the output.
            retCode = self.ma_unguarded(startIdx, endIdx, inReal, optInSlowPeriod, optInMAType, &mut outBegIdx1, &mut outNbElement1, outReal);
            if retCode == RetCode::Success {
                // The slow MA begins at or after the fast MA, so the offset is
                // valid whenever the slow MA produced output. Guard it so the empty
                // case leaves the difference loop untouched.
                if outNbElement1 > 0 {
                    tempInteger = outBegIdx1 - outBegIdx2;
                    // Calculate (fast MA)-(slow MA) in the output.
                    // for( i = 0, j = tempInteger; i < outNbElement1; i += 1, j += 1 )
                    i = 0;
                    j = tempInteger;
                    while i < outNbElement1 {
                        outReal[i] = ((tempBuffer[j] - outReal[i]) as f64);
                        i += 1;
                        j += 1;
                    }
                }
                (*outBegIdx) = outBegIdx1;
                (*outNBElement) = outNbElement1;
            }
        }
        return retCode;
    }
    /// Unguarded variant of [`Core::apo`], used for internal cross-indicator calls.
    ///
    /// Skips parameter validation; indexing stays safe. Every argument must satisfy the constraints
    /// documented on [`Core::apo`]; an out-of-range parameter, an input slice not covering
    /// `startIdx..=endIdx`, or an undersized output slice panics (never undefined behavior). Prefer
    /// [`Core::apo`].
    #[inline]
    pub fn apo_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        mut optInFastPeriod: i32,
        mut optInSlowPeriod: i32,
        mut optInMAType: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        let mut tempBuffer: Vec<f64> = Vec::new();
        let mut retCode: RetCode = RetCode::Success;
        let mut tempInteger: usize = 0_usize;
        let mut outBegIdx1: usize = 0_usize;
        let mut outNbElement1: usize = 0_usize;
        let mut outBegIdx2: usize = 0_usize;
        let mut outNbElement2: usize = 0_usize;
        let mut i: usize = 0_usize;
        let mut j: usize = 0_usize;
        assert!(endIdx < inReal.len());
        let _assertLb = self.apo_lookback(optInFastPeriod, optInSlowPeriod, optInMAType);
        let _assertStart = if startIdx > _assertLb { startIdx } else { _assertLb };
        assert!(_assertStart > endIdx || endIdx - _assertStart < outReal.len());
        tempBuffer = vec![0.0_f64; ((endIdx - startIdx + 1) * 1) as usize];
        if optInSlowPeriod < optInFastPeriod {
            tempInteger = (optInSlowPeriod) as usize;
            optInSlowPeriod = optInFastPeriod;
            optInFastPeriod = (tempInteger) as i32;
        }
        retCode = self.ma_unguarded(startIdx, endIdx, inReal, optInFastPeriod, optInMAType, &mut outBegIdx2, &mut outNbElement2, &mut tempBuffer[..]);
        if retCode == RetCode::Success {
            retCode = self.ma_unguarded(startIdx, endIdx, inReal, optInSlowPeriod, optInMAType, &mut outBegIdx1, &mut outNbElement1, outReal);
            if retCode == RetCode::Success {
                if outNbElement1 > 0 {
                    tempInteger = outBegIdx1 - outBegIdx2;
                    // for( i = 0, j = tempInteger; i < outNbElement1; i += 1, j += 1 )
                    i = 0;
                    j = tempInteger;
                    while i < outNbElement1 {
                        outReal[i] = ((tempBuffer[j] - outReal[i]) as f64);
                        i += 1;
                        j += 1;
                    }
                }
                (*outBegIdx) = outBegIdx1;
                (*outNBElement) = outNbElement1;
            }
        }
        return retCode;
    }
}
/***************/
/* End of File */
/***************/
