/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility ta_codegen.
 *  Any modifications will be lost on next execution of ta_codegen.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  AC       Angelo Ciceri
 *
 *
 * Change history:
 *
 *  MMDDYY BY   Description
 *  -------------------------------------------------------------------
 *  120904 AC   Creation
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::cdlpiercing`]: the number of leading input values consumed
    /// before the first output value can be produced.
    pub fn cdlpiercing_lookback(&self) -> usize {
        #[allow(non_snake_case)]
        let BodyLong_rangeType: i32 = self.candle_settings.body_long.range_type;
        #[allow(non_snake_case)]
        let BodyLong_avgPeriod: i32 = self.candle_settings.body_long.avg_period;
        #[allow(non_snake_case)]
        let BodyLong_factor: f64 = self.candle_settings.body_long.factor;
        return (BodyLong_avgPeriod + 1) as usize;
    }
    /// Two-candle pattern: a long black candle followed by a long white candle that opens below the
    /// prior low and closes back above the midpoint of the prior black body. Bullish reversal
    /// signal. A hit (+100) is a bullish reversal signal.
    ///
    /// # Notes
    ///
    /// * A prior downtrend is not verified.
    ///
    /// # Arguments
    ///
    /// * `startIdx` — Start index of the requested calculation range.
    /// * `endIdx` — End index of the requested calculation range (inclusive).
    /// * `inOpen` — Open prices per bar.
    /// * `inHigh` — High prices per bar.
    /// * `inLow` — Low prices per bar.
    /// * `inClose` — Close prices per bar.
    /// * `outBegIdx` — Set to the input index of the first output value.
    /// * `outNBElement` — Set to the number of output values written.
    /// * `outInteger` — +100 when the piercing pattern is detected; 0 otherwise. Always bullish,
    ///   never emits -100.
    ///
    /// # Errors
    ///
    /// Returns [`RetCode::OutOfRangeStartIndex`] when `endIdx < startIdx`.
    ///
    /// # Panics
    ///
    /// Input slices must cover `startIdx..=endIdx` and output slices must hold the number of values
    /// produced for that range; an undersized slice panics. Sizing every output slice to the input
    /// length is always sufficient.
    ///
    /// # Examples
    ///
    /// ```
    /// use ta_lib::{Core, RetCode};
    ///
    /// let open: Vec<f64> = (0..252).map(|i| 100.0 + 10.0 * (0.1 * i as f64 - 0.05).sin()).collect();
    /// let high: Vec<f64> = (0..252).map(|i| 101.0 + 10.0 * (0.1 * i as f64).sin()).collect();
    /// let low: Vec<f64> = (0..252).map(|i| 99.0 + 10.0 * (0.1 * i as f64).sin()).collect();
    /// let close: Vec<f64> = (0..252).map(|i| 100.0 + 10.0 * (0.1 * i as f64).sin()).collect();
    ///
    /// let core = Core::new();
    /// let mut out_beg = 0;
    /// let mut out_nb = 0;
    /// let mut out = vec![0i32; 252];
    ///
    /// let ret = core.cdlpiercing(
    ///     0, open.len() - 1, &open, &high, &low, &close,
    ///     &mut out_beg, &mut out_nb, &mut out,
    /// );
    /// assert_eq!(ret, RetCode::Success);
    /// assert!(out_nb > 0);
    /// ```
    ///
    /// # See also
    ///
    /// [`Core::cdldarkcloudcover`] · [`Core::cdlengulfing`] · [`Core::cdlmorningstar`]
    ///
    /// Further reading:
    /// [ta-lib.org/functions/cdlpiercing](https://ta-lib.org/functions/cdlpiercing/)
    #[doc(alias = "PiercingPattern")]
    #[doc(alias = "PiercingLine")]
    pub fn cdlpiercing(
        &self,
        startIdx: usize,
        endIdx: usize,
        inOpen: &[f64],
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        let mut startIdx = startIdx;
        let mut BodyLongPeriodTotal: [f64; 2 as usize] = [0.0_f64; 2 as usize];
        let mut i: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut totIdx: usize = 0_usize;
        let mut BodyLongTrailingIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        #[allow(non_snake_case)]
        let BodyLong_rangeType: i32 = self.candle_settings.body_long.range_type;
        #[allow(non_snake_case)]
        let BodyLong_avgPeriod: i32 = self.candle_settings.body_long.avg_period;
        #[allow(non_snake_case)]
        let BodyLong_factor: f64 = self.candle_settings.body_long.factor;
        // Identify the minimum number of price bar needed
        // to calculate at least one output.
        lookbackTotal = self.cdlpiercing_lookback();
        // Move up the start index if there is not
        // enough initial data.
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        // Make sure there is still something to evaluate.
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        // Do the calculation using tight loops.
        // Add-up the initial period, except for the last value.
        BodyLongPeriodTotal[1] = 0.0;
        BodyLongPeriodTotal[0] = 0.0;
        BodyLongTrailingIdx = startIdx - (BodyLong_avgPeriod) as usize;
        i = BodyLongTrailingIdx;
        while i < startIdx {
            let mut _candlerange_0: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_0 = (inClose[i - 1] - inOpen[i - 1]).abs();
                }
                1 => {
                    _candlerange_0 = inHigh[i - 1] - inLow[i - 1];
                }
                2 => {
                    _candlerange_0 = inHigh[i - 1] - inLow[i - 1] - (inClose[i - 1] - inOpen[i - 1]).abs();
                }
                _ => {
                    _candlerange_0 = 0.0;
                }
            }
            BodyLongPeriodTotal[1] = BodyLongPeriodTotal[1] + _candlerange_0;
            let mut _candlerange_1: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_1 = (inClose[i] - inOpen[i]).abs();
                }
                1 => {
                    _candlerange_1 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_1 = inHigh[i] - inLow[i] - (inClose[i] - inOpen[i]).abs();
                }
                _ => {
                    _candlerange_1 = 0.0;
                }
            }
            BodyLongPeriodTotal[0] = BodyLongPeriodTotal[0] + _candlerange_1;
            i += 1;
        }
        i = startIdx;
        // Proceed with the calculation for the requested range.
        // Must have:
        // - first candle: long black candle
        // - second candle: long white candle with open below previous day low and close at least at 50% of previous day
        // real body
        // The meaning of "long" is specified with TA_SetCandleSettings
        // outInteger is positive (1 to 100): piercing pattern is always bullish
        // the user should consider that a piercing pattern is significant when it appears in a downtrend, while
        // this function does not consider it
        outIdx = 0;
        loop {
            if ((if inClose[i - 1] >= inOpen[i - 1] { 1 } else { 0 - 1 })) as i32 == 0 - 1 && // 1st: black
               (inClose[i - 1] - inOpen[i - 1]).abs() > ((BodyLong_factor) * (if (BodyLong_avgPeriod) != 0 { (BodyLongPeriodTotal[1]) / (BodyLong_avgPeriod as f64) } else { match BodyLong_rangeType { 0 => (inClose[i - 1] - inOpen[i - 1]).abs(), 1 => (inHigh[i - 1]) - (inLow[i - 1]), _ => (inHigh[i - 1]) - (inLow[i - 1]) - ((inClose[i - 1]) - (inOpen[i - 1])).abs() } }) / (if (BodyLong_rangeType) == 2 { 2.0 } else { 1.0 })) && // long
               (if inClose[i] >= inOpen[i] { 1 } else { 0 - 1 }) == 1 && // 2nd: white
               (inClose[i] - inOpen[i]).abs() > ((BodyLong_factor) * (if (BodyLong_avgPeriod) != 0 { (BodyLongPeriodTotal[0]) / (BodyLong_avgPeriod as f64) } else { match BodyLong_rangeType { 0 => (inClose[i] - inOpen[i]).abs(), 1 => (inHigh[i]) - (inLow[i]), _ => (inHigh[i]) - (inLow[i]) - ((inClose[i]) - (inOpen[i])).abs() } }) / (if (BodyLong_rangeType) == 2 { 2.0 } else { 1.0 })) && // long
               inOpen[i] < inLow[i - 1] &&                               // open below prior low
               inClose[i] < inOpen[i - 1] &&                             // close within prior body
               inClose[i] > ((inClose[i - 1] - inOpen[i - 1]).abs() as f64).mul_add(0.5, inClose[i - 1]) // above midpoint
            {
                outInteger[outIdx] = 100;
                outIdx += 1;
            } else {
                outInteger[outIdx] = 0;
                outIdx += 1;
            }
            // add the current range and subtract the first range: this is done after the pattern recognition
            // when avgPeriod is not 0, that means "compare with the previous candles" (it excludes the current candle)
            // for( totIdx = 1; totIdx >= 0; totIdx -= 1 )
            totIdx = 1;
            loop {
                let mut _candlerange_2: f64;
                match BodyLong_rangeType {
                    0 => {
                        _candlerange_2 = (inClose[i - totIdx] - inOpen[i - totIdx]).abs();
                    }
                    1 => {
                        _candlerange_2 = inHigh[i - totIdx] - inLow[i - totIdx];
                    }
                    2 => {
                        _candlerange_2 = inHigh[i - totIdx] - inLow[i - totIdx] - (inClose[i - totIdx] - inOpen[i - totIdx]).abs();
                    }
                    _ => {
                        _candlerange_2 = 0.0;
                    }
                }
                let mut _candlerange_3: f64;
                match BodyLong_rangeType {
                    0 => {
                        _candlerange_3 = (inClose[BodyLongTrailingIdx - totIdx] - inOpen[BodyLongTrailingIdx - totIdx]).abs();
                    }
                    1 => {
                        _candlerange_3 = inHigh[BodyLongTrailingIdx - totIdx] - inLow[BodyLongTrailingIdx - totIdx];
                    }
                    2 => {
                        _candlerange_3 = inHigh[BodyLongTrailingIdx - totIdx] - inLow[BodyLongTrailingIdx - totIdx] - (inClose[BodyLongTrailingIdx - totIdx] - inOpen[BodyLongTrailingIdx - totIdx]).abs();
                    }
                    _ => {
                        _candlerange_3 = 0.0;
                    }
                }
                BodyLongPeriodTotal[totIdx] = BodyLongPeriodTotal[totIdx] + (_candlerange_2 - _candlerange_3);
                if totIdx == 0 { break; }
                totIdx -= 1;
            }
            i += 1;
            BodyLongTrailingIdx += 1;
            if !(i <= endIdx) { break; }
        }
        // All done. Indicate the output limits and return.
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
    /// Unguarded variant of [`Core::cdlpiercing`], used for internal cross-indicator calls.
    ///
    /// Skips parameter validation; indexing stays safe. Every argument must satisfy the constraints
    /// documented on [`Core::cdlpiercing`]; an out-of-range parameter, an input slice not covering
    /// `startIdx..=endIdx`, or an undersized output slice panics (never undefined behavior). Prefer
    /// [`Core::cdlpiercing`].
    #[inline]
    pub fn cdlpiercing_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inOpen: &[f64],
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        let mut BodyLongPeriodTotal: [f64; 2 as usize] = [0.0_f64; 2 as usize];
        let mut i: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut totIdx: usize = 0_usize;
        let mut BodyLongTrailingIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        #[allow(non_snake_case)]
        let BodyLong_rangeType: i32 = self.candle_settings.body_long.range_type;
        #[allow(non_snake_case)]
        let BodyLong_avgPeriod: i32 = self.candle_settings.body_long.avg_period;
        #[allow(non_snake_case)]
        let BodyLong_factor: f64 = self.candle_settings.body_long.factor;
        assert!(endIdx < inOpen.len());
        assert!(endIdx < inHigh.len());
        assert!(endIdx < inLow.len());
        assert!(endIdx < inClose.len());
        let _assertLb = self.cdlpiercing_lookback();
        let _assertStart = if startIdx > _assertLb { startIdx } else { _assertLb };
        assert!(_assertStart > endIdx || endIdx - _assertStart < outInteger.len());
        lookbackTotal = self.cdlpiercing_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        BodyLongPeriodTotal[1] = 0.0;
        BodyLongPeriodTotal[0] = 0.0;
        BodyLongTrailingIdx = startIdx - (BodyLong_avgPeriod) as usize;
        i = BodyLongTrailingIdx;
        while i < startIdx {
            let mut _candlerange_0: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_0 = (inClose[i - 1] - inOpen[i - 1]).abs();
                }
                1 => {
                    _candlerange_0 = inHigh[i - 1] - inLow[i - 1];
                }
                2 => {
                    _candlerange_0 = inHigh[i - 1] - inLow[i - 1] - (inClose[i - 1] - inOpen[i - 1]).abs();
                }
                _ => {
                    _candlerange_0 = 0.0;
                }
            }
            BodyLongPeriodTotal[1] = BodyLongPeriodTotal[1] + _candlerange_0;
            let mut _candlerange_1: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_1 = (inClose[i] - inOpen[i]).abs();
                }
                1 => {
                    _candlerange_1 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_1 = inHigh[i] - inLow[i] - (inClose[i] - inOpen[i]).abs();
                }
                _ => {
                    _candlerange_1 = 0.0;
                }
            }
            BodyLongPeriodTotal[0] = BodyLongPeriodTotal[0] + _candlerange_1;
            i += 1;
        }
        i = startIdx;
        outIdx = 0;
        loop {
            if ((if inClose[i - 1] >= inOpen[i - 1] { 1 } else { 0 - 1 })) as i32 == 0 - 1 && (inClose[i - 1] - inOpen[i - 1]).abs() > ((BodyLong_factor) * (if (BodyLong_avgPeriod) != 0 { (BodyLongPeriodTotal[1]) / (BodyLong_avgPeriod as f64) } else { match BodyLong_rangeType { 0 => (inClose[i - 1] - inOpen[i - 1]).abs(), 1 => (inHigh[i - 1]) - (inLow[i - 1]), _ => (inHigh[i - 1]) - (inLow[i - 1]) - ((inClose[i - 1]) - (inOpen[i - 1])).abs() } }) / (if (BodyLong_rangeType) == 2 { 2.0 } else { 1.0 })) && (if inClose[i] >= inOpen[i] { 1 } else { 0 - 1 }) == 1 && (inClose[i] - inOpen[i]).abs() > ((BodyLong_factor) * (if (BodyLong_avgPeriod) != 0 { (BodyLongPeriodTotal[0]) / (BodyLong_avgPeriod as f64) } else { match BodyLong_rangeType { 0 => (inClose[i] - inOpen[i]).abs(), 1 => (inHigh[i]) - (inLow[i]), _ => (inHigh[i]) - (inLow[i]) - ((inClose[i]) - (inOpen[i])).abs() } }) / (if (BodyLong_rangeType) == 2 { 2.0 } else { 1.0 })) && inOpen[i] < inLow[i - 1] && inClose[i] < inOpen[i - 1] && inClose[i] > ((inClose[i - 1] - inOpen[i - 1]).abs() as f64).mul_add(0.5, inClose[i - 1]) {
                outInteger[outIdx] = 100;
                outIdx += 1;
            } else {
                outInteger[outIdx] = 0;
                outIdx += 1;
            }
            // for( totIdx = 1; totIdx >= 0; totIdx -= 1 )
            totIdx = 1;
            loop {
                let mut _candlerange_2: f64;
                match BodyLong_rangeType {
                    0 => {
                        _candlerange_2 = (inClose[i - totIdx] - inOpen[i - totIdx]).abs();
                    }
                    1 => {
                        _candlerange_2 = inHigh[i - totIdx] - inLow[i - totIdx];
                    }
                    2 => {
                        _candlerange_2 = inHigh[i - totIdx] - inLow[i - totIdx] - (inClose[i - totIdx] - inOpen[i - totIdx]).abs();
                    }
                    _ => {
                        _candlerange_2 = 0.0;
                    }
                }
                let mut _candlerange_3: f64;
                match BodyLong_rangeType {
                    0 => {
                        _candlerange_3 = (inClose[BodyLongTrailingIdx - totIdx] - inOpen[BodyLongTrailingIdx - totIdx]).abs();
                    }
                    1 => {
                        _candlerange_3 = inHigh[BodyLongTrailingIdx - totIdx] - inLow[BodyLongTrailingIdx - totIdx];
                    }
                    2 => {
                        _candlerange_3 = inHigh[BodyLongTrailingIdx - totIdx] - inLow[BodyLongTrailingIdx - totIdx] - (inClose[BodyLongTrailingIdx - totIdx] - inOpen[BodyLongTrailingIdx - totIdx]).abs();
                    }
                    _ => {
                        _candlerange_3 = 0.0;
                    }
                }
                BodyLongPeriodTotal[totIdx] = BodyLongPeriodTotal[totIdx] + (_candlerange_2 - _candlerange_3);
                if totIdx == 0 { break; }
                totIdx -= 1;
            }
            i += 1;
            BodyLongTrailingIdx += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
}
/***************/
/* End of File */
/***************/
