/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility ta_codegen.
 *  Any modifications will be lost on next execution of ta_codegen.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  AC       Angelo Ciceri
 *
 *
 * Change history:
 *
 *  MMDDYY BY   Description
 *  -------------------------------------------------------------------
 *  022005 AC   Creation
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::cdlunique3river`]: the number of leading input values consumed
    /// before the first output value can be produced.
    pub fn cdlunique3river_lookback(&self) -> usize {
        #[allow(non_snake_case)]
        let BodyLong_rangeType: i32 = self.candle_settings.body_long.range_type;
        #[allow(non_snake_case)]
        let BodyLong_avgPeriod: i32 = self.candle_settings.body_long.avg_period;
        #[allow(non_snake_case)]
        let BodyLong_factor: f64 = self.candle_settings.body_long.factor;
        #[allow(non_snake_case)]
        let BodyShort_rangeType: i32 = self.candle_settings.body_short.range_type;
        #[allow(non_snake_case)]
        let BodyShort_avgPeriod: i32 = self.candle_settings.body_short.avg_period;
        #[allow(non_snake_case)]
        let BodyShort_factor: f64 = self.candle_settings.body_short.factor;
        return ((BodyShort_avgPeriod).max(BodyLong_avgPeriod) + 2) as usize;
    }
    /// A three-candle bullish reversal pattern: a long black candle, then a black harami candle
    /// that makes a lower low, then a small white candle. Signals a potential bullish reversal,
    /// ideally in a downtrend (trend not checked by the code). A hit (+100) marks a bullish
    /// reversal; significant in a downtrend, which the function does not verify.
    ///
    /// # Arguments
    ///
    /// * `startIdx` — Start index of the requested calculation range.
    /// * `endIdx` — End index of the requested calculation range (inclusive).
    /// * `inOpen` — Open prices per bar.
    /// * `inHigh` — High prices per bar.
    /// * `inLow` — Low prices per bar.
    /// * `inClose` — Close prices per bar.
    /// * `outBegIdx` — Set to the input index of the first output value.
    /// * `outNBElement` — Set to the number of output values written.
    /// * `outInteger` — +100 when the pattern is present, 0 otherwise. Bullish-only: never emits
    ///   -100.
    ///
    /// # Errors
    ///
    /// Returns [`RetCode::OutOfRangeStartIndex`] when `endIdx < startIdx`.
    ///
    /// # Panics
    ///
    /// Input slices must cover `startIdx..=endIdx` and output slices must hold the number of values
    /// produced for that range; an undersized slice panics. Sizing every output slice to the input
    /// length is always sufficient.
    ///
    /// # Examples
    ///
    /// ```
    /// use ta_lib::{Core, RetCode};
    ///
    /// let open: Vec<f64> = (0..252).map(|i| 100.0 + 10.0 * (0.1 * i as f64 - 0.05).sin()).collect();
    /// let high: Vec<f64> = (0..252).map(|i| 101.0 + 10.0 * (0.1 * i as f64).sin()).collect();
    /// let low: Vec<f64> = (0..252).map(|i| 99.0 + 10.0 * (0.1 * i as f64).sin()).collect();
    /// let close: Vec<f64> = (0..252).map(|i| 100.0 + 10.0 * (0.1 * i as f64).sin()).collect();
    ///
    /// let core = Core::new();
    /// let mut out_beg = 0;
    /// let mut out_nb = 0;
    /// let mut out = vec![0i32; 252];
    ///
    /// let ret = core.cdlunique3river(
    ///     0, open.len() - 1, &open, &high, &low, &close,
    ///     &mut out_beg, &mut out_nb, &mut out,
    /// );
    /// assert_eq!(ret, RetCode::Success);
    /// assert!(out_nb > 0);
    /// ```
    ///
    /// # See also
    ///
    /// [`Core::cdlharami`] · [`Core::cdlhomingpigeon`] · [`Core::cdl3inside`]
    ///
    /// Further reading:
    /// [ta-lib.org/functions/cdlunique3river](https://ta-lib.org/functions/cdlunique3river/)
    #[doc(alias = "Unique3River")]
    #[doc(alias = "UniqueThreeRiverBottom")]
    pub fn cdlunique3river(
        &self,
        startIdx: usize,
        endIdx: usize,
        inOpen: &[f64],
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        let mut startIdx = startIdx;
        let mut BodyShortPeriodTotal: f64 = 0.0_f64;
        let mut BodyLongPeriodTotal: f64 = 0.0_f64;
        let mut i: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut BodyShortTrailingIdx: usize = 0_usize;
        let mut BodyLongTrailingIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        #[allow(non_snake_case)]
        let BodyLong_rangeType: i32 = self.candle_settings.body_long.range_type;
        #[allow(non_snake_case)]
        let BodyLong_avgPeriod: i32 = self.candle_settings.body_long.avg_period;
        #[allow(non_snake_case)]
        let BodyLong_factor: f64 = self.candle_settings.body_long.factor;
        #[allow(non_snake_case)]
        let BodyShort_rangeType: i32 = self.candle_settings.body_short.range_type;
        #[allow(non_snake_case)]
        let BodyShort_avgPeriod: i32 = self.candle_settings.body_short.avg_period;
        #[allow(non_snake_case)]
        let BodyShort_factor: f64 = self.candle_settings.body_short.factor;
        // Identify the minimum number of price bar needed
        // to calculate at least one output.
        lookbackTotal = self.cdlunique3river_lookback();
        // Move up the start index if there is not
        // enough initial data.
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        // Make sure there is still something to evaluate.
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        // Do the calculation using tight loops.
        // Add-up the initial period, except for the last value.
        BodyLongPeriodTotal = 0.0;
        BodyShortPeriodTotal = 0.0;
        BodyLongTrailingIdx = startIdx - 2 - (BodyLong_avgPeriod) as usize;
        BodyShortTrailingIdx = startIdx - (BodyShort_avgPeriod) as usize;
        i = BodyLongTrailingIdx;
        while i < startIdx - 2 {
            let mut _candlerange_0: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_0 = (inClose[i] - inOpen[i]).abs();
                }
                1 => {
                    _candlerange_0 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_0 = inHigh[i] - inLow[i] - (inClose[i] - inOpen[i]).abs();
                }
                _ => {
                    _candlerange_0 = 0.0;
                }
            }
            BodyLongPeriodTotal += _candlerange_0;
            i += 1;
        }
        i = BodyShortTrailingIdx;
        while i < startIdx {
            let mut _candlerange_1: f64;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_1 = (inClose[i] - inOpen[i]).abs();
                }
                1 => {
                    _candlerange_1 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_1 = inHigh[i] - inLow[i] - (inClose[i] - inOpen[i]).abs();
                }
                _ => {
                    _candlerange_1 = 0.0;
                }
            }
            BodyShortPeriodTotal += _candlerange_1;
            i += 1;
        }
        i = startIdx;
        // Proceed with the calculation for the requested range.
        // Must have:
        // - first candle: long black candle
        // - second candle: black harami candle with a lower low than the first candle's low
        // - third candle: small white candle with open not lower than the second candle's low, better if its open and
        //   close are under the second candle's close
        // The meaning of "short" and "long" is specified with TA_SetCandleSettings
        // outInteger is positive (1 to 100): unique 3 river is always bullish and should appear in a downtrend
        // to be significant, while this function does not consider the trend
        outIdx = 0;
        loop {
            if ((if inClose[i - 2] >= inOpen[i - 2] { 1 } else { 0 - 1 })) as i32 == 0 - 1 && // black
               ((if inClose[i - 1] >= inOpen[i - 1] { 1 } else { 0 - 1 })) as i32 == 0 - 1 && // 2nd: black
               (if inClose[i] >= inOpen[i] { 1 } else { 0 - 1 }) == 1 && // white
               inClose[i - 1] > inClose[i - 2] &&
               inOpen[i - 1] <= inOpen[i - 2] &&                         // harami
               inLow[i - 1] < inLow[i - 2] &&                            // lower low
               inOpen[i] > inLow[i - 1] &&                               // open not lower
               (inClose[i - 2] - inOpen[i - 2]).abs() > ((BodyLong_factor) * (if (BodyLong_avgPeriod) != 0 { (BodyLongPeriodTotal) / (BodyLong_avgPeriod as f64) } else { match BodyLong_rangeType { 0 => (inClose[i - 2] - inOpen[i - 2]).abs(), 1 => (inHigh[i - 2]) - (inLow[i - 2]), _ => (inHigh[i - 2]) - (inLow[i - 2]) - ((inClose[i - 2]) - (inOpen[i - 2])).abs() } }) / (if (BodyLong_rangeType) == 2 { 2.0 } else { 1.0 })) && // 1st: long
               (inClose[i] - inOpen[i]).abs() < ((BodyShort_factor) * (if (BodyShort_avgPeriod) != 0 { (BodyShortPeriodTotal) / (BodyShort_avgPeriod as f64) } else { match BodyShort_rangeType { 0 => (inClose[i] - inOpen[i]).abs(), 1 => (inHigh[i]) - (inLow[i]), _ => (inHigh[i]) - (inLow[i]) - ((inClose[i]) - (inOpen[i])).abs() } }) / (if (BodyShort_rangeType) == 2 { 2.0 } else { 1.0 })) // 3rd: short
            {
                outInteger[outIdx] = 100;
                outIdx += 1;
            } else {
                outInteger[outIdx] = 0;
                outIdx += 1;
            }
            // add the current range and subtract the first range: this is done after the pattern recognition
            // when avgPeriod is not 0, that means "compare with the previous candles" (it excludes the current candle)
            let mut _candlerange_2: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_2 = (inClose[i - 2] - inOpen[i - 2]).abs();
                }
                1 => {
                    _candlerange_2 = inHigh[i - 2] - inLow[i - 2];
                }
                2 => {
                    _candlerange_2 = inHigh[i - 2] - inLow[i - 2] - (inClose[i - 2] - inOpen[i - 2]).abs();
                }
                _ => {
                    _candlerange_2 = 0.0;
                }
            }
            let mut _candlerange_3: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_3 = (inClose[BodyLongTrailingIdx] - inOpen[BodyLongTrailingIdx]).abs();
                }
                1 => {
                    _candlerange_3 = inHigh[BodyLongTrailingIdx] - inLow[BodyLongTrailingIdx];
                }
                2 => {
                    _candlerange_3 = inHigh[BodyLongTrailingIdx] - inLow[BodyLongTrailingIdx] - (inClose[BodyLongTrailingIdx] - inOpen[BodyLongTrailingIdx]).abs();
                }
                _ => {
                    _candlerange_3 = 0.0;
                }
            }
            BodyLongPeriodTotal += _candlerange_2 - _candlerange_3;
            let mut _candlerange_4: f64;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_4 = (inClose[i] - inOpen[i]).abs();
                }
                1 => {
                    _candlerange_4 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_4 = inHigh[i] - inLow[i] - (inClose[i] - inOpen[i]).abs();
                }
                _ => {
                    _candlerange_4 = 0.0;
                }
            }
            let mut _candlerange_5: f64;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_5 = (inClose[BodyShortTrailingIdx] - inOpen[BodyShortTrailingIdx]).abs();
                }
                1 => {
                    _candlerange_5 = inHigh[BodyShortTrailingIdx] - inLow[BodyShortTrailingIdx];
                }
                2 => {
                    _candlerange_5 = inHigh[BodyShortTrailingIdx] - inLow[BodyShortTrailingIdx] - (inClose[BodyShortTrailingIdx] - inOpen[BodyShortTrailingIdx]).abs();
                }
                _ => {
                    _candlerange_5 = 0.0;
                }
            }
            BodyShortPeriodTotal += _candlerange_4 - _candlerange_5;
            i += 1;
            BodyLongTrailingIdx += 1;
            BodyShortTrailingIdx += 1;
            if !(i <= endIdx) { break; }
        }
        // All done. Indicate the output limits and return.
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
    /// Unguarded variant of [`Core::cdlunique3river`], used for internal cross-indicator calls.
    ///
    /// Skips parameter validation; indexing stays safe. Every argument must satisfy the constraints
    /// documented on [`Core::cdlunique3river`]; an out-of-range parameter, an input slice not
    /// covering `startIdx..=endIdx`, or an undersized output slice panics (never undefined
    /// behavior). Prefer [`Core::cdlunique3river`].
    #[inline]
    pub fn cdlunique3river_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inOpen: &[f64],
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        let mut BodyShortPeriodTotal: f64 = 0.0_f64;
        let mut BodyLongPeriodTotal: f64 = 0.0_f64;
        let mut i: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut BodyShortTrailingIdx: usize = 0_usize;
        let mut BodyLongTrailingIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        #[allow(non_snake_case)]
        let BodyLong_rangeType: i32 = self.candle_settings.body_long.range_type;
        #[allow(non_snake_case)]
        let BodyLong_avgPeriod: i32 = self.candle_settings.body_long.avg_period;
        #[allow(non_snake_case)]
        let BodyLong_factor: f64 = self.candle_settings.body_long.factor;
        #[allow(non_snake_case)]
        let BodyShort_rangeType: i32 = self.candle_settings.body_short.range_type;
        #[allow(non_snake_case)]
        let BodyShort_avgPeriod: i32 = self.candle_settings.body_short.avg_period;
        #[allow(non_snake_case)]
        let BodyShort_factor: f64 = self.candle_settings.body_short.factor;
        assert!(endIdx < inOpen.len());
        assert!(endIdx < inHigh.len());
        assert!(endIdx < inLow.len());
        assert!(endIdx < inClose.len());
        let _assertLb = self.cdlunique3river_lookback();
        let _assertStart = if startIdx > _assertLb { startIdx } else { _assertLb };
        assert!(_assertStart > endIdx || endIdx - _assertStart < outInteger.len());
        lookbackTotal = self.cdlunique3river_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        BodyLongPeriodTotal = 0.0;
        BodyShortPeriodTotal = 0.0;
        BodyLongTrailingIdx = startIdx - 2 - (BodyLong_avgPeriod) as usize;
        BodyShortTrailingIdx = startIdx - (BodyShort_avgPeriod) as usize;
        i = BodyLongTrailingIdx;
        while i < startIdx - 2 {
            let mut _candlerange_0: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_0 = (inClose[i] - inOpen[i]).abs();
                }
                1 => {
                    _candlerange_0 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_0 = inHigh[i] - inLow[i] - (inClose[i] - inOpen[i]).abs();
                }
                _ => {
                    _candlerange_0 = 0.0;
                }
            }
            BodyLongPeriodTotal += _candlerange_0;
            i += 1;
        }
        i = BodyShortTrailingIdx;
        while i < startIdx {
            let mut _candlerange_1: f64;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_1 = (inClose[i] - inOpen[i]).abs();
                }
                1 => {
                    _candlerange_1 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_1 = inHigh[i] - inLow[i] - (inClose[i] - inOpen[i]).abs();
                }
                _ => {
                    _candlerange_1 = 0.0;
                }
            }
            BodyShortPeriodTotal += _candlerange_1;
            i += 1;
        }
        i = startIdx;
        outIdx = 0;
        loop {
            if ((if inClose[i - 2] >= inOpen[i - 2] { 1 } else { 0 - 1 })) as i32 == 0 - 1 && ((if inClose[i - 1] >= inOpen[i - 1] { 1 } else { 0 - 1 })) as i32 == 0 - 1 && (if inClose[i] >= inOpen[i] { 1 } else { 0 - 1 }) == 1 && inClose[i - 1] > inClose[i - 2] && inOpen[i - 1] <= inOpen[i - 2] && inLow[i - 1] < inLow[i - 2] && inOpen[i] > inLow[i - 1] && (inClose[i - 2] - inOpen[i - 2]).abs() > ((BodyLong_factor) * (if (BodyLong_avgPeriod) != 0 { (BodyLongPeriodTotal) / (BodyLong_avgPeriod as f64) } else { match BodyLong_rangeType { 0 => (inClose[i - 2] - inOpen[i - 2]).abs(), 1 => (inHigh[i - 2]) - (inLow[i - 2]), _ => (inHigh[i - 2]) - (inLow[i - 2]) - ((inClose[i - 2]) - (inOpen[i - 2])).abs() } }) / (if (BodyLong_rangeType) == 2 { 2.0 } else { 1.0 })) && (inClose[i] - inOpen[i]).abs() < ((BodyShort_factor) * (if (BodyShort_avgPeriod) != 0 { (BodyShortPeriodTotal) / (BodyShort_avgPeriod as f64) } else { match BodyShort_rangeType { 0 => (inClose[i] - inOpen[i]).abs(), 1 => (inHigh[i]) - (inLow[i]), _ => (inHigh[i]) - (inLow[i]) - ((inClose[i]) - (inOpen[i])).abs() } }) / (if (BodyShort_rangeType) == 2 { 2.0 } else { 1.0 })) {
                outInteger[outIdx] = 100;
                outIdx += 1;
            } else {
                outInteger[outIdx] = 0;
                outIdx += 1;
            }
            let mut _candlerange_2: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_2 = (inClose[i - 2] - inOpen[i - 2]).abs();
                }
                1 => {
                    _candlerange_2 = inHigh[i - 2] - inLow[i - 2];
                }
                2 => {
                    _candlerange_2 = inHigh[i - 2] - inLow[i - 2] - (inClose[i - 2] - inOpen[i - 2]).abs();
                }
                _ => {
                    _candlerange_2 = 0.0;
                }
            }
            let mut _candlerange_3: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_3 = (inClose[BodyLongTrailingIdx] - inOpen[BodyLongTrailingIdx]).abs();
                }
                1 => {
                    _candlerange_3 = inHigh[BodyLongTrailingIdx] - inLow[BodyLongTrailingIdx];
                }
                2 => {
                    _candlerange_3 = inHigh[BodyLongTrailingIdx] - inLow[BodyLongTrailingIdx] - (inClose[BodyLongTrailingIdx] - inOpen[BodyLongTrailingIdx]).abs();
                }
                _ => {
                    _candlerange_3 = 0.0;
                }
            }
            BodyLongPeriodTotal += _candlerange_2 - _candlerange_3;
            let mut _candlerange_4: f64;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_4 = (inClose[i] - inOpen[i]).abs();
                }
                1 => {
                    _candlerange_4 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_4 = inHigh[i] - inLow[i] - (inClose[i] - inOpen[i]).abs();
                }
                _ => {
                    _candlerange_4 = 0.0;
                }
            }
            let mut _candlerange_5: f64;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_5 = (inClose[BodyShortTrailingIdx] - inOpen[BodyShortTrailingIdx]).abs();
                }
                1 => {
                    _candlerange_5 = inHigh[BodyShortTrailingIdx] - inLow[BodyShortTrailingIdx];
                }
                2 => {
                    _candlerange_5 = inHigh[BodyShortTrailingIdx] - inLow[BodyShortTrailingIdx] - (inClose[BodyShortTrailingIdx] - inOpen[BodyShortTrailingIdx]).abs();
                }
                _ => {
                    _candlerange_5 = 0.0;
                }
            }
            BodyShortPeriodTotal += _candlerange_4 - _candlerange_5;
            i += 1;
            BodyLongTrailingIdx += 1;
            BodyShortTrailingIdx += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
}
/***************/
/* End of File */
/***************/
